#include "Resources.h"
#include "SexyAppFramework/ResourceManager.h"

using namespace Sexy;

#pragma warning(disable:4311 4312)

static bool gNeedRecalcVariableToIdMap = false;

bool Sexy::ExtractResourcesByName(ResourceManager *theManager, const char *theName)
{
	if (strcmp(theName,"3dImages")==0) return Extract3dImagesResources(theManager);
	if (strcmp(theName,"BackDropsLoading")==0) return ExtractBackDropsLoadingResources(theManager);
	if (strcmp(theName,"Init")==0) return ExtractInitResources(theManager);
	if (strcmp(theName,"InitialMainMenu")==0) return ExtractInitialMainMenuResources(theManager);
	if (strcmp(theName,"LoadScreen")==0) return ExtractLoadScreenResources(theManager);
	if (strcmp(theName,"LoadingThread")==0) return ExtractLoadingThreadResources(theManager);
	if (strcmp(theName,"PuzzleImages")==0) return ExtractPuzzleImagesResources(theManager);
	if (strcmp(theName,"Sounds")==0) return ExtractSoundsResources(theManager);
	return false;
}

Sexy::ResourceId Sexy::GetIdByStringId(const char *theStringId)
{
	typedef std::map<std::string,int> MyMap;
	static MyMap aMap;
	if(aMap.empty())
	{
		for(int i=0; i<RESOURCE_ID_MAX; i++)
			aMap[GetStringIdById(i)] = i;
	}

	MyMap::iterator anItr = aMap.find(theStringId);
	if (anItr == aMap.end())
		return RESOURCE_ID_MAX;
	else
		return (ResourceId) anItr->second;
}

// 3dImages Resources
Image* Sexy::IMAGE_BLACK_HOLE;
Image* Sexy::IMAGE_BLACK_HOLE_COVER;
Image* Sexy::IMAGE_FIRE_RING;
Image* Sexy::IMAGE_HYPERSPACE;
Image* Sexy::IMAGE_HYPERSPACE_INITIAL;
Image* Sexy::IMAGE_TUNNEL_END;
Image* Sexy::IMAGE_WARP_LINES;

bool Sexy::Extract3dImagesResources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_BLACK_HOLE = aMgr.GetImageThrow("IMAGE_BLACK_HOLE");
		IMAGE_BLACK_HOLE_COVER = aMgr.GetImageThrow("IMAGE_BLACK_HOLE_COVER");
		IMAGE_FIRE_RING = aMgr.GetImageThrow("IMAGE_FIRE_RING");
		IMAGE_HYPERSPACE = aMgr.GetImageThrow("IMAGE_HYPERSPACE");
		IMAGE_HYPERSPACE_INITIAL = aMgr.GetImageThrow("IMAGE_HYPERSPACE_INITIAL");
		IMAGE_TUNNEL_END = aMgr.GetImageThrow("IMAGE_TUNNEL_END");
		IMAGE_WARP_LINES = aMgr.GetImageThrow("IMAGE_WARP_LINES");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// BackDropsLoading Resources
Image* Sexy::IMAGE_ACHIEVEMENT1;
Image* Sexy::IMAGE_ACHIEVEMENT10;
Image* Sexy::IMAGE_ACHIEVEMENT11;
Image* Sexy::IMAGE_ACHIEVEMENT12;
Image* Sexy::IMAGE_ACHIEVEMENT2;
Image* Sexy::IMAGE_ACHIEVEMENT3;
Image* Sexy::IMAGE_ACHIEVEMENT4;
Image* Sexy::IMAGE_ACHIEVEMENT5;
Image* Sexy::IMAGE_ACHIEVEMENT6;
Image* Sexy::IMAGE_ACHIEVEMENT7;
Image* Sexy::IMAGE_ACHIEVEMENT8;
Image* Sexy::IMAGE_ACHIEVEMENT9;
Image* Sexy::IMAGE_A_BUTTON;
Image* Sexy::IMAGE_BACKDROP00;
Image* Sexy::IMAGE_BACKDROP01;
Image* Sexy::IMAGE_BACKDROP02;
Image* Sexy::IMAGE_BACKDROP03;
Image* Sexy::IMAGE_BACKDROP04;
Image* Sexy::IMAGE_BACKDROP05;
Image* Sexy::IMAGE_BACKDROP06;
Image* Sexy::IMAGE_BACKDROP07;
Image* Sexy::IMAGE_BACKDROP08;
Image* Sexy::IMAGE_BACKDROP09;
Image* Sexy::IMAGE_BACKDROP10;
Image* Sexy::IMAGE_BACKDROP11;
Image* Sexy::IMAGE_BACKDROP12;
Image* Sexy::IMAGE_BACKDROP13;
Image* Sexy::IMAGE_BACKDROP14;
Image* Sexy::IMAGE_BACKDROP15;
Image* Sexy::IMAGE_BACKDROP16;
Image* Sexy::IMAGE_BACKDROP17;
Image* Sexy::IMAGE_B_BUTTON;
Image* Sexy::IMAGE_DPAD_DOWN;
Image* Sexy::IMAGE_DPAD_LEFT;
Image* Sexy::IMAGE_DPAD_LEFTRIGHT;
Image* Sexy::IMAGE_DPAD_RIGHT;
Image* Sexy::IMAGE_DPAD_UP;
Image* Sexy::IMAGE_DPAD_UPDOWN;
Image* Sexy::IMAGE_JOYSTICK;
Image* Sexy::IMAGE_LB_BUTTON;
Image* Sexy::IMAGE_MENU_BUTTON;
Image* Sexy::IMAGE_MENU_BUTTON_GLOW2;
Image* Sexy::IMAGE_NEBULA1;
Image* Sexy::IMAGE_RB_BUTTON;
Image* Sexy::IMAGE_X_BUTTON;
Image* Sexy::IMAGE_Y_BUTTON;
Image* Sexy::IMAGE_ZENDROP1;
Image* Sexy::IMAGE_ZENDROP10;
Image* Sexy::IMAGE_ZENDROP11;
Image* Sexy::IMAGE_ZENDROP12;
Image* Sexy::IMAGE_ZENDROP13;
Image* Sexy::IMAGE_ZENDROP14;
Image* Sexy::IMAGE_ZENDROP15;
Image* Sexy::IMAGE_ZENDROP16;
Image* Sexy::IMAGE_ZENDROP17;
Image* Sexy::IMAGE_ZENDROP18;
Image* Sexy::IMAGE_ZENDROP19;
Image* Sexy::IMAGE_ZENDROP2;
Image* Sexy::IMAGE_ZENDROP20;
Image* Sexy::IMAGE_ZENDROP21;
Image* Sexy::IMAGE_ZENDROP22;
Image* Sexy::IMAGE_ZENDROP23;
Image* Sexy::IMAGE_ZENDROP24;
Image* Sexy::IMAGE_ZENDROP25;
Image* Sexy::IMAGE_ZENDROP26;
Image* Sexy::IMAGE_ZENDROP27;
Image* Sexy::IMAGE_ZENDROP28;
Image* Sexy::IMAGE_ZENDROP29;
Image* Sexy::IMAGE_ZENDROP3;
Image* Sexy::IMAGE_ZENDROP30;
Image* Sexy::IMAGE_ZENDROP31;
Image* Sexy::IMAGE_ZENDROP32;
Image* Sexy::IMAGE_ZENDROP33;
Image* Sexy::IMAGE_ZENDROP34;
Image* Sexy::IMAGE_ZENDROP35;
Image* Sexy::IMAGE_ZENDROP36;
Image* Sexy::IMAGE_ZENDROP37;
Image* Sexy::IMAGE_ZENDROP38;
Image* Sexy::IMAGE_ZENDROP39;
Image* Sexy::IMAGE_ZENDROP4;
Image* Sexy::IMAGE_ZENDROP40;
Image* Sexy::IMAGE_ZENDROP5;
Image* Sexy::IMAGE_ZENDROP6;
Image* Sexy::IMAGE_ZENDROP7;
Image* Sexy::IMAGE_ZENDROP8;
Image* Sexy::IMAGE_ZENDROP9;

bool Sexy::ExtractBackDropsLoadingResources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_ACHIEVEMENT1 = aMgr.GetImageThrow("IMAGE_ACHIEVEMENT1");
		IMAGE_ACHIEVEMENT10 = aMgr.GetImageThrow("IMAGE_ACHIEVEMENT10");
		IMAGE_ACHIEVEMENT11 = aMgr.GetImageThrow("IMAGE_ACHIEVEMENT11");
		IMAGE_ACHIEVEMENT12 = aMgr.GetImageThrow("IMAGE_ACHIEVEMENT12");
		IMAGE_ACHIEVEMENT2 = aMgr.GetImageThrow("IMAGE_ACHIEVEMENT2");
		IMAGE_ACHIEVEMENT3 = aMgr.GetImageThrow("IMAGE_ACHIEVEMENT3");
		IMAGE_ACHIEVEMENT4 = aMgr.GetImageThrow("IMAGE_ACHIEVEMENT4");
		IMAGE_ACHIEVEMENT5 = aMgr.GetImageThrow("IMAGE_ACHIEVEMENT5");
		IMAGE_ACHIEVEMENT6 = aMgr.GetImageThrow("IMAGE_ACHIEVEMENT6");
		IMAGE_ACHIEVEMENT7 = aMgr.GetImageThrow("IMAGE_ACHIEVEMENT7");
		IMAGE_ACHIEVEMENT8 = aMgr.GetImageThrow("IMAGE_ACHIEVEMENT8");
		IMAGE_ACHIEVEMENT9 = aMgr.GetImageThrow("IMAGE_ACHIEVEMENT9");
		IMAGE_A_BUTTON = aMgr.GetImageThrow("IMAGE_A_BUTTON");
		IMAGE_BACKDROP00 = aMgr.GetImageThrow("IMAGE_BACKDROP00");
		IMAGE_BACKDROP01 = aMgr.GetImageThrow("IMAGE_BACKDROP01");
		IMAGE_BACKDROP02 = aMgr.GetImageThrow("IMAGE_BACKDROP02");
		IMAGE_BACKDROP03 = aMgr.GetImageThrow("IMAGE_BACKDROP03");
		IMAGE_BACKDROP04 = aMgr.GetImageThrow("IMAGE_BACKDROP04");
		IMAGE_BACKDROP05 = aMgr.GetImageThrow("IMAGE_BACKDROP05");
		IMAGE_BACKDROP06 = aMgr.GetImageThrow("IMAGE_BACKDROP06");
		IMAGE_BACKDROP07 = aMgr.GetImageThrow("IMAGE_BACKDROP07");
		IMAGE_BACKDROP08 = aMgr.GetImageThrow("IMAGE_BACKDROP08");
		IMAGE_BACKDROP09 = aMgr.GetImageThrow("IMAGE_BACKDROP09");
		IMAGE_BACKDROP10 = aMgr.GetImageThrow("IMAGE_BACKDROP10");
		IMAGE_BACKDROP11 = aMgr.GetImageThrow("IMAGE_BACKDROP11");
		IMAGE_BACKDROP12 = aMgr.GetImageThrow("IMAGE_BACKDROP12");
		IMAGE_BACKDROP13 = aMgr.GetImageThrow("IMAGE_BACKDROP13");
		IMAGE_BACKDROP14 = aMgr.GetImageThrow("IMAGE_BACKDROP14");
		IMAGE_BACKDROP15 = aMgr.GetImageThrow("IMAGE_BACKDROP15");
		IMAGE_BACKDROP16 = aMgr.GetImageThrow("IMAGE_BACKDROP16");
		IMAGE_BACKDROP17 = aMgr.GetImageThrow("IMAGE_BACKDROP17");
		IMAGE_B_BUTTON = aMgr.GetImageThrow("IMAGE_B_BUTTON");
		IMAGE_DPAD_DOWN = aMgr.GetImageThrow("IMAGE_DPAD_DOWN");
		IMAGE_DPAD_LEFT = aMgr.GetImageThrow("IMAGE_DPAD_LEFT");
		IMAGE_DPAD_LEFTRIGHT = aMgr.GetImageThrow("IMAGE_DPAD_LEFTRIGHT");
		IMAGE_DPAD_RIGHT = aMgr.GetImageThrow("IMAGE_DPAD_RIGHT");
		IMAGE_DPAD_UP = aMgr.GetImageThrow("IMAGE_DPAD_UP");
		IMAGE_DPAD_UPDOWN = aMgr.GetImageThrow("IMAGE_DPAD_UPDOWN");
		IMAGE_JOYSTICK = aMgr.GetImageThrow("IMAGE_JOYSTICK");
		IMAGE_LB_BUTTON = aMgr.GetImageThrow("IMAGE_LB_BUTTON");
		IMAGE_MENU_BUTTON = aMgr.GetImageThrow("IMAGE_MENU_BUTTON");
		IMAGE_MENU_BUTTON_GLOW2 = aMgr.GetImageThrow("IMAGE_MENU_BUTTON_GLOW2");
		IMAGE_NEBULA1 = aMgr.GetImageThrow("IMAGE_NEBULA1");
		IMAGE_RB_BUTTON = aMgr.GetImageThrow("IMAGE_RB_BUTTON");
		IMAGE_X_BUTTON = aMgr.GetImageThrow("IMAGE_X_BUTTON");
		IMAGE_Y_BUTTON = aMgr.GetImageThrow("IMAGE_Y_BUTTON");
		IMAGE_ZENDROP1 = aMgr.GetImageThrow("IMAGE_ZENDROP1");
		IMAGE_ZENDROP10 = aMgr.GetImageThrow("IMAGE_ZENDROP10");
		IMAGE_ZENDROP11 = aMgr.GetImageThrow("IMAGE_ZENDROP11");
		IMAGE_ZENDROP12 = aMgr.GetImageThrow("IMAGE_ZENDROP12");
		IMAGE_ZENDROP13 = aMgr.GetImageThrow("IMAGE_ZENDROP13");
		IMAGE_ZENDROP14 = aMgr.GetImageThrow("IMAGE_ZENDROP14");
		IMAGE_ZENDROP15 = aMgr.GetImageThrow("IMAGE_ZENDROP15");
		IMAGE_ZENDROP16 = aMgr.GetImageThrow("IMAGE_ZENDROP16");
		IMAGE_ZENDROP17 = aMgr.GetImageThrow("IMAGE_ZENDROP17");
		IMAGE_ZENDROP18 = aMgr.GetImageThrow("IMAGE_ZENDROP18");
		IMAGE_ZENDROP19 = aMgr.GetImageThrow("IMAGE_ZENDROP19");
		IMAGE_ZENDROP2 = aMgr.GetImageThrow("IMAGE_ZENDROP2");
		IMAGE_ZENDROP20 = aMgr.GetImageThrow("IMAGE_ZENDROP20");
		IMAGE_ZENDROP21 = aMgr.GetImageThrow("IMAGE_ZENDROP21");
		IMAGE_ZENDROP22 = aMgr.GetImageThrow("IMAGE_ZENDROP22");
		IMAGE_ZENDROP23 = aMgr.GetImageThrow("IMAGE_ZENDROP23");
		IMAGE_ZENDROP24 = aMgr.GetImageThrow("IMAGE_ZENDROP24");
		IMAGE_ZENDROP25 = aMgr.GetImageThrow("IMAGE_ZENDROP25");
		IMAGE_ZENDROP26 = aMgr.GetImageThrow("IMAGE_ZENDROP26");
		IMAGE_ZENDROP27 = aMgr.GetImageThrow("IMAGE_ZENDROP27");
		IMAGE_ZENDROP28 = aMgr.GetImageThrow("IMAGE_ZENDROP28");
		IMAGE_ZENDROP29 = aMgr.GetImageThrow("IMAGE_ZENDROP29");
		IMAGE_ZENDROP3 = aMgr.GetImageThrow("IMAGE_ZENDROP3");
		IMAGE_ZENDROP30 = aMgr.GetImageThrow("IMAGE_ZENDROP30");
		IMAGE_ZENDROP31 = aMgr.GetImageThrow("IMAGE_ZENDROP31");
		IMAGE_ZENDROP32 = aMgr.GetImageThrow("IMAGE_ZENDROP32");
		IMAGE_ZENDROP33 = aMgr.GetImageThrow("IMAGE_ZENDROP33");
		IMAGE_ZENDROP34 = aMgr.GetImageThrow("IMAGE_ZENDROP34");
		IMAGE_ZENDROP35 = aMgr.GetImageThrow("IMAGE_ZENDROP35");
		IMAGE_ZENDROP36 = aMgr.GetImageThrow("IMAGE_ZENDROP36");
		IMAGE_ZENDROP37 = aMgr.GetImageThrow("IMAGE_ZENDROP37");
		IMAGE_ZENDROP38 = aMgr.GetImageThrow("IMAGE_ZENDROP38");
		IMAGE_ZENDROP39 = aMgr.GetImageThrow("IMAGE_ZENDROP39");
		IMAGE_ZENDROP4 = aMgr.GetImageThrow("IMAGE_ZENDROP4");
		IMAGE_ZENDROP40 = aMgr.GetImageThrow("IMAGE_ZENDROP40");
		IMAGE_ZENDROP5 = aMgr.GetImageThrow("IMAGE_ZENDROP5");
		IMAGE_ZENDROP6 = aMgr.GetImageThrow("IMAGE_ZENDROP6");
		IMAGE_ZENDROP7 = aMgr.GetImageThrow("IMAGE_ZENDROP7");
		IMAGE_ZENDROP8 = aMgr.GetImageThrow("IMAGE_ZENDROP8");
		IMAGE_ZENDROP9 = aMgr.GetImageThrow("IMAGE_ZENDROP9");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// Init Resources
Font* Sexy::FONT_1;
Font* Sexy::FONT_3;
Font* Sexy::FONT_CONTINUUM_MED_HDR;
Font* Sexy::FONT_CONTINUUM_MED_HDR_GLOW;
Font* Sexy::FONT_CONT_11;
Font* Sexy::FONT_CONT_MED;
Font* Sexy::FONT_GILLSANS14;
Font* Sexy::FONT_SEGOETV11;
Font* Sexy::FONT_SEGOETV11_GLOW;
Font* Sexy::FONT_SEGOETV12;
Font* Sexy::FONT_SEGOETV12_GLOW;
Font* Sexy::FONT_SEGOETV22;
Font* Sexy::FONT_SEGOETV22_GLOW;

bool Sexy::ExtractInitResources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		FONT_1 = aMgr.GetFontThrow("FONT_1");
		FONT_3 = aMgr.GetFontThrow("FONT_3");
		FONT_CONTINUUM_MED_HDR = aMgr.GetFontThrow("FONT_CONTINUUM_MED_HDR");
		FONT_CONTINUUM_MED_HDR_GLOW = aMgr.GetFontThrow("FONT_CONTINUUM_MED_HDR_GLOW");
		FONT_CONT_11 = aMgr.GetFontThrow("FONT_CONT_11");
		FONT_CONT_MED = aMgr.GetFontThrow("FONT_CONT_MED");
		FONT_GILLSANS14 = aMgr.GetFontThrow("FONT_GILLSANS14");
		FONT_SEGOETV11 = aMgr.GetFontThrow("FONT_SEGOETV11");
		FONT_SEGOETV11_GLOW = aMgr.GetFontThrow("FONT_SEGOETV11_GLOW");
		FONT_SEGOETV12 = aMgr.GetFontThrow("FONT_SEGOETV12");
		FONT_SEGOETV12_GLOW = aMgr.GetFontThrow("FONT_SEGOETV12_GLOW");
		FONT_SEGOETV22 = aMgr.GetFontThrow("FONT_SEGOETV22");
		FONT_SEGOETV22_GLOW = aMgr.GetFontThrow("FONT_SEGOETV22_GLOW");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// InitialMainMenu Resources
Image* Sexy::IMAGE_MAIN_BKG;
Image* Sexy::IMAGE_MAIN_COMET;
Image* Sexy::IMAGE_MAIN_FG;
Image* Sexy::IMAGE_MAIN_FOG_BANK;
Image* Sexy::IMAGE_MAIN_FOG_BANK_FG;
Image* Sexy::IMAGE_MAIN_PLANET_1;
Image* Sexy::IMAGE_MAIN_STARFIELD;
Image* Sexy::IMAGE_MAIN_STAR_SPARKLE;

bool Sexy::ExtractInitialMainMenuResources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_MAIN_BKG = aMgr.GetImageThrow("IMAGE_MAIN_BKG");
		IMAGE_MAIN_COMET = aMgr.GetImageThrow("IMAGE_MAIN_COMET");
		IMAGE_MAIN_FG = aMgr.GetImageThrow("IMAGE_MAIN_FG");
		IMAGE_MAIN_FOG_BANK = aMgr.GetImageThrow("IMAGE_MAIN_FOG_BANK");
		IMAGE_MAIN_FOG_BANK_FG = aMgr.GetImageThrow("IMAGE_MAIN_FOG_BANK_FG");
		IMAGE_MAIN_PLANET_1 = aMgr.GetImageThrow("IMAGE_MAIN_PLANET_1");
		IMAGE_MAIN_STARFIELD = aMgr.GetImageThrow("IMAGE_MAIN_STARFIELD");
		IMAGE_MAIN_STAR_SPARKLE = aMgr.GetImageThrow("IMAGE_MAIN_STAR_SPARKLE");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// LoadScreen Resources
Image* Sexy::IMAGE_LOADER_BAR;
Image* Sexy::IMAGE_LOADER_BAR_FLASH;
Image* Sexy::IMAGE_LOADER_BAR_LIT_BLUE;
Image* Sexy::IMAGE_LOADER_BAR_LIT_PURPLE;
Image* Sexy::IMAGE_LOGO;
Image* Sexy::IMAGE_LOGO_2;
Image* Sexy::IMAGE_LOGO_POPCAP;

bool Sexy::ExtractLoadScreenResources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_LOADER_BAR = aMgr.GetImageThrow("IMAGE_LOADER_BAR");
		IMAGE_LOADER_BAR_FLASH = aMgr.GetImageThrow("IMAGE_LOADER_BAR_FLASH");
		IMAGE_LOADER_BAR_LIT_BLUE = aMgr.GetImageThrow("IMAGE_LOADER_BAR_LIT_BLUE");
		IMAGE_LOADER_BAR_LIT_PURPLE = aMgr.GetImageThrow("IMAGE_LOADER_BAR_LIT_PURPLE");
		IMAGE_LOGO = aMgr.GetImageThrow("IMAGE_LOGO");
		IMAGE_LOGO_2 = aMgr.GetImageThrow("IMAGE_LOGO_2");
		IMAGE_LOGO_POPCAP = aMgr.GetImageThrow("IMAGE_LOGO_POPCAP");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// LoadingThread Resources
Font* Sexy::FONT_BOMB;
Font* Sexy::FONT_DIGIT;
Font* Sexy::FONT_ENGSMALL;
Font* Sexy::FONT_HUGE;
Font* Sexy::FONT_LEADERBOARD;
Font* Sexy::FONT_SCORE;
Font* Sexy::FONT_VAG_ROUNDED_11;
Image* Sexy::IMAGE_ARROW_UP;
Image* Sexy::IMAGE_BAR_LEFT;
Image* Sexy::IMAGE_BAR_MID;
Image* Sexy::IMAGE_BAR_RIGHT;
Image* Sexy::IMAGE_BIGSTAR;
Image* Sexy::IMAGE_BOARD_BORDER;
Image* Sexy::IMAGE_BOARD_RED_LIGHT;
Image* Sexy::IMAGE_BOMB;
Image* Sexy::IMAGE_BUTTON_HILITE;
Image* Sexy::IMAGE_CHECKBOX;
Image* Sexy::IMAGE_CONTROLS_CLASSIC;
Image* Sexy::IMAGE_CONTROLS_PUZZLE;
Image* Sexy::IMAGE_CONTROLS_PUZZLE_ALT;
Image* Sexy::IMAGE_CONTROLS_SCORE;
Image* Sexy::IMAGE_DIALOG;
Image* Sexy::IMAGE_DIALOG_BUTTON;
Image* Sexy::IMAGE_DIALOG_BUTTON_GLOW;
Image* Sexy::IMAGE_DIALOG_HEADER;
Image* Sexy::IMAGE_EDIT_BOX;
Image* Sexy::IMAGE_ENDLESS_CENTER_1;
Image* Sexy::IMAGE_ENDLESS_CENTER_2;
Image* Sexy::IMAGE_ENDLESS_CENTER_3;
Image* Sexy::IMAGE_ENDLESS_CENTER_4;
Image* Sexy::IMAGE_ENDLESS_CENTER_5;
Image* Sexy::IMAGE_ENDLESS_CENTER_6;
Image* Sexy::IMAGE_ENDLESS_CENTER_7;
Image* Sexy::IMAGE_ENDLESS_GEM_HILITE;
Image* Sexy::IMAGE_ENDLESS_OUTER_1;
Image* Sexy::IMAGE_ENDLESS_OUTER_2;
Image* Sexy::IMAGE_ENDLESS_OUTER_3;
Image* Sexy::IMAGE_ENDLESS_OUTER_4;
Image* Sexy::IMAGE_ENDLESS_OUTER_5;
Image* Sexy::IMAGE_ENDLESS_OUTER_6;
Image* Sexy::IMAGE_ENDLESS_OUTER_7;
Image* Sexy::IMAGE_ENDLESS_SPARK_1;
Image* Sexy::IMAGE_ENDLESS_SPARK_2;
Image* Sexy::IMAGE_ENDLESS_SPARK_3;
Image* Sexy::IMAGE_ENDLESS_WIDGET;
Image* Sexy::IMAGE_EXPLOSION;
Image* Sexy::IMAGE_GALAXY_BUTTON_HILITE;
Image* Sexy::IMAGE_GALAXY_CLOSE_BUTTON;
Image* Sexy::IMAGE_GALAXY_MAP;
Image* Sexy::IMAGE_GALAXY_MOON_ALPHA;
Image* Sexy::IMAGE_GALAXY_MOON_SELECT;
Image* Sexy::IMAGE_GALAXY_PLANET_ALPHA;
Image* Sexy::IMAGE_GALAXY_PLANET_COMPLETED;
Image* Sexy::IMAGE_GALAXY_PLANET_SELECT;
Image* Sexy::IMAGE_GALAXY_QUESTION;
Image* Sexy::IMAGE_GALAXY_SUN_GLOW;
Image* Sexy::IMAGE_GALAXY_SUN_MOON_ALPHA;
Image* Sexy::IMAGE_GALAXY_SUN_SWIRL;
Image* Sexy::IMAGE_GALAXY_WARP_BUTTON;
Image* Sexy::IMAGE_GEM0;
Image* Sexy::IMAGE_GEM1;
Image* Sexy::IMAGE_GEM2;
Image* Sexy::IMAGE_GEM3;
Image* Sexy::IMAGE_GEM4;
Image* Sexy::IMAGE_GEM5;
Image* Sexy::IMAGE_GEM6;
Image* Sexy::IMAGE_GEM_ADD;
Image* Sexy::IMAGE_GEM_LIGHTING;
Image* Sexy::IMAGE_HELP_ARROW;
Image* Sexy::IMAGE_HELP_GRID_4;
Image* Sexy::IMAGE_HELP_GRID_5;
Image* Sexy::IMAGE_HELP_INDICATOR;
Image* Sexy::IMAGE_HELP_INDICATOR_ALT;
Image* Sexy::IMAGE_HELP_INDICATOR_ARROW;
Image* Sexy::IMAGE_HS_BOTTOM;
Image* Sexy::IMAGE_LIGHTNING;
Image* Sexy::IMAGE_LIGHTNING_CENTER;
Image* Sexy::IMAGE_MAIN_ACTION;
Image* Sexy::IMAGE_MAIN_BIG_OVER;
Image* Sexy::IMAGE_MAIN_BIG_SELECT;
Image* Sexy::IMAGE_MAIN_BOTTOM_GLOW;
Image* Sexy::IMAGE_MAIN_CENTER_GLOW;
Image* Sexy::IMAGE_MAIN_CENTER_TEXT;
Image* Sexy::IMAGE_MAIN_CLASSIC;
Image* Sexy::IMAGE_MAIN_COGNITO;
Image* Sexy::IMAGE_MAIN_ENDLESS;
Image* Sexy::IMAGE_MAIN_FINITY;
Image* Sexy::IMAGE_MAIN_GADGETS;
Image* Sexy::IMAGE_MAIN_HYPER;
Image* Sexy::IMAGE_MAIN_LIGHT_BIG;
Image* Sexy::IMAGE_MAIN_LIGHT_MED;
Image* Sexy::IMAGE_MAIN_LIGHT_SMALL;
Image* Sexy::IMAGE_MAIN_OPTIONS;
Image* Sexy::IMAGE_MAIN_PLAY;
Image* Sexy::IMAGE_MAIN_PLAY_GLOW;
Image* Sexy::IMAGE_MAIN_PUZZLE;
Image* Sexy::IMAGE_MAIN_QUIT;
Image* Sexy::IMAGE_MAIN_SCORES;
Image* Sexy::IMAGE_MAIN_SECRET_FRAME;
Image* Sexy::IMAGE_MAIN_SECRET_GLOW;
Image* Sexy::IMAGE_MAIN_SECRET_SYMBOL;
Image* Sexy::IMAGE_MAIN_SMALL_GLOW;
Image* Sexy::IMAGE_MAIN_TWILIGHT;
Image* Sexy::IMAGE_OLD_GEMS;
Image* Sexy::IMAGE_POWER_GLOW;
Image* Sexy::IMAGE_PUZZLE_DOME;
Image* Sexy::IMAGE_PUZZLE_DOME_MASK;
Image* Sexy::IMAGE_PUZZLE_DOME_SLIVER;
Image* Sexy::IMAGE_PUZZLE_FRAME;
Image* Sexy::IMAGE_PUZZLE_MAP_BUTTON;
Image* Sexy::IMAGE_PUZZLE_MAP_BUTTON_GLOW;
Image* Sexy::IMAGE_PUZZLE_PODS;
Image* Sexy::IMAGE_PUZZLE_PODS_LIT;
Image* Sexy::IMAGE_PUZZLE_PUZZLE_LIT;
Image* Sexy::IMAGE_PUZZLE_THUMB_GEM;
Image* Sexy::IMAGE_PUZZLE_VAPOR1;
Image* Sexy::IMAGE_PUZZLE_VAPOR2;
Image* Sexy::IMAGE_PUZZLE_WARP_BUTTON;
Image* Sexy::IMAGE_PUZZLE_WARP_GLOW;
Image* Sexy::IMAGE_PUZZLE_WIDGET;
Image* Sexy::IMAGE_RING_DUDE;
Image* Sexy::IMAGE_ROCK;
Image* Sexy::IMAGE_ROCK_CHUNK;
Image* Sexy::IMAGE_SELECT;
Image* Sexy::IMAGE_SHARD;
Image* Sexy::IMAGE_SIDEBAR_HINT_BUTTON;
Image* Sexy::IMAGE_SIDEBAR_MENU_BUTTON;
Image* Sexy::IMAGE_SLIDER_THUMB;
Image* Sexy::IMAGE_SLIDER_TRACK;
Image* Sexy::IMAGE_SMALL_GEMS;
Image* Sexy::IMAGE_SPARKLE;
Image* Sexy::IMAGE_UI_BIG_ROLLOVER;
Image* Sexy::IMAGE_UI_BUTTON_HINT;
Image* Sexy::IMAGE_UI_BUTTON_MENU;
Image* Sexy::IMAGE_UI_BUTTON_PAUSE;
Image* Sexy::IMAGE_UI_BUTTON_UNDO;
Image* Sexy::IMAGE_UI_SMALL_ROLLOVER;
Image* Sexy::IMAGE_WARP_BOTTOM_GLOW;
Image* Sexy::IMAGE_WARP_TOP_GLOW;
Image* Sexy::IMAGE_WILDCARD_DESTROYER;

bool Sexy::ExtractLoadingThreadResources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		FONT_BOMB = aMgr.GetFontThrow("FONT_BOMB");
		FONT_DIGIT = aMgr.GetFontThrow("FONT_DIGIT");
		FONT_ENGSMALL = aMgr.GetFontThrow("FONT_ENGSMALL");
		FONT_HUGE = aMgr.GetFontThrow("FONT_HUGE");
		FONT_LEADERBOARD = aMgr.GetFontThrow("FONT_LEADERBOARD");
		FONT_SCORE = aMgr.GetFontThrow("FONT_SCORE");
		FONT_VAG_ROUNDED_11 = aMgr.GetFontThrow("FONT_VAG_ROUNDED_11");
		IMAGE_ARROW_UP = aMgr.GetImageThrow("IMAGE_ARROW_UP");
		IMAGE_BAR_LEFT = aMgr.GetImageThrow("IMAGE_BAR_LEFT");
		IMAGE_BAR_MID = aMgr.GetImageThrow("IMAGE_BAR_MID");
		IMAGE_BAR_RIGHT = aMgr.GetImageThrow("IMAGE_BAR_RIGHT");
		IMAGE_BIGSTAR = aMgr.GetImageThrow("IMAGE_BIGSTAR");
		IMAGE_BOARD_BORDER = aMgr.GetImageThrow("IMAGE_BOARD_BORDER");
		IMAGE_BOARD_RED_LIGHT = aMgr.GetImageThrow("IMAGE_BOARD_RED_LIGHT");
		IMAGE_BOMB = aMgr.GetImageThrow("IMAGE_BOMB");
		IMAGE_BUTTON_HILITE = aMgr.GetImageThrow("IMAGE_BUTTON_HILITE");
		IMAGE_CHECKBOX = aMgr.GetImageThrow("IMAGE_CHECKBOX");
		IMAGE_CONTROLS_CLASSIC = aMgr.GetImageThrow("IMAGE_CONTROLS_CLASSIC");
		IMAGE_CONTROLS_PUZZLE = aMgr.GetImageThrow("IMAGE_CONTROLS_PUZZLE");
		IMAGE_CONTROLS_PUZZLE_ALT = aMgr.GetImageThrow("IMAGE_CONTROLS_PUZZLE_ALT");
		IMAGE_CONTROLS_SCORE = aMgr.GetImageThrow("IMAGE_CONTROLS_SCORE");
		IMAGE_DIALOG = aMgr.GetImageThrow("IMAGE_DIALOG");
		IMAGE_DIALOG_BUTTON = aMgr.GetImageThrow("IMAGE_DIALOG_BUTTON");
		IMAGE_DIALOG_BUTTON_GLOW = aMgr.GetImageThrow("IMAGE_DIALOG_BUTTON_GLOW");
		IMAGE_DIALOG_HEADER = aMgr.GetImageThrow("IMAGE_DIALOG_HEADER");
		IMAGE_EDIT_BOX = aMgr.GetImageThrow("IMAGE_EDIT_BOX");
		IMAGE_ENDLESS_CENTER_1 = aMgr.GetImageThrow("IMAGE_ENDLESS_CENTER_1");
		IMAGE_ENDLESS_CENTER_2 = aMgr.GetImageThrow("IMAGE_ENDLESS_CENTER_2");
		IMAGE_ENDLESS_CENTER_3 = aMgr.GetImageThrow("IMAGE_ENDLESS_CENTER_3");
		IMAGE_ENDLESS_CENTER_4 = aMgr.GetImageThrow("IMAGE_ENDLESS_CENTER_4");
		IMAGE_ENDLESS_CENTER_5 = aMgr.GetImageThrow("IMAGE_ENDLESS_CENTER_5");
		IMAGE_ENDLESS_CENTER_6 = aMgr.GetImageThrow("IMAGE_ENDLESS_CENTER_6");
		IMAGE_ENDLESS_CENTER_7 = aMgr.GetImageThrow("IMAGE_ENDLESS_CENTER_7");
		IMAGE_ENDLESS_GEM_HILITE = aMgr.GetImageThrow("IMAGE_ENDLESS_GEM_HILITE");
		IMAGE_ENDLESS_OUTER_1 = aMgr.GetImageThrow("IMAGE_ENDLESS_OUTER_1");
		IMAGE_ENDLESS_OUTER_2 = aMgr.GetImageThrow("IMAGE_ENDLESS_OUTER_2");
		IMAGE_ENDLESS_OUTER_3 = aMgr.GetImageThrow("IMAGE_ENDLESS_OUTER_3");
		IMAGE_ENDLESS_OUTER_4 = aMgr.GetImageThrow("IMAGE_ENDLESS_OUTER_4");
		IMAGE_ENDLESS_OUTER_5 = aMgr.GetImageThrow("IMAGE_ENDLESS_OUTER_5");
		IMAGE_ENDLESS_OUTER_6 = aMgr.GetImageThrow("IMAGE_ENDLESS_OUTER_6");
		IMAGE_ENDLESS_OUTER_7 = aMgr.GetImageThrow("IMAGE_ENDLESS_OUTER_7");
		IMAGE_ENDLESS_SPARK_1 = aMgr.GetImageThrow("IMAGE_ENDLESS_SPARK_1");
		IMAGE_ENDLESS_SPARK_2 = aMgr.GetImageThrow("IMAGE_ENDLESS_SPARK_2");
		IMAGE_ENDLESS_SPARK_3 = aMgr.GetImageThrow("IMAGE_ENDLESS_SPARK_3");
		IMAGE_ENDLESS_WIDGET = aMgr.GetImageThrow("IMAGE_ENDLESS_WIDGET");
		IMAGE_EXPLOSION = aMgr.GetImageThrow("IMAGE_EXPLOSION");
		IMAGE_GALAXY_BUTTON_HILITE = aMgr.GetImageThrow("IMAGE_GALAXY_BUTTON_HILITE");
		IMAGE_GALAXY_CLOSE_BUTTON = aMgr.GetImageThrow("IMAGE_GALAXY_CLOSE_BUTTON");
		IMAGE_GALAXY_MAP = aMgr.GetImageThrow("IMAGE_GALAXY_MAP");
		IMAGE_GALAXY_MOON_ALPHA = aMgr.GetImageThrow("IMAGE_GALAXY_MOON_ALPHA");
		IMAGE_GALAXY_MOON_SELECT = aMgr.GetImageThrow("IMAGE_GALAXY_MOON_SELECT");
		IMAGE_GALAXY_PLANET_ALPHA = aMgr.GetImageThrow("IMAGE_GALAXY_PLANET_ALPHA");
		IMAGE_GALAXY_PLANET_COMPLETED = aMgr.GetImageThrow("IMAGE_GALAXY_PLANET_COMPLETED");
		IMAGE_GALAXY_PLANET_SELECT = aMgr.GetImageThrow("IMAGE_GALAXY_PLANET_SELECT");
		IMAGE_GALAXY_QUESTION = aMgr.GetImageThrow("IMAGE_GALAXY_QUESTION");
		IMAGE_GALAXY_SUN_GLOW = aMgr.GetImageThrow("IMAGE_GALAXY_SUN_GLOW");
		IMAGE_GALAXY_SUN_MOON_ALPHA = aMgr.GetImageThrow("IMAGE_GALAXY_SUN_MOON_ALPHA");
		IMAGE_GALAXY_SUN_SWIRL = aMgr.GetImageThrow("IMAGE_GALAXY_SUN_SWIRL");
		IMAGE_GALAXY_WARP_BUTTON = aMgr.GetImageThrow("IMAGE_GALAXY_WARP_BUTTON");
		IMAGE_GEM0 = aMgr.GetImageThrow("IMAGE_GEM0");
		IMAGE_GEM1 = aMgr.GetImageThrow("IMAGE_GEM1");
		IMAGE_GEM2 = aMgr.GetImageThrow("IMAGE_GEM2");
		IMAGE_GEM3 = aMgr.GetImageThrow("IMAGE_GEM3");
		IMAGE_GEM4 = aMgr.GetImageThrow("IMAGE_GEM4");
		IMAGE_GEM5 = aMgr.GetImageThrow("IMAGE_GEM5");
		IMAGE_GEM6 = aMgr.GetImageThrow("IMAGE_GEM6");
		IMAGE_GEM_ADD = aMgr.GetImageThrow("IMAGE_GEM_ADD");
		IMAGE_GEM_LIGHTING = aMgr.GetImageThrow("IMAGE_GEM_LIGHTING");
		IMAGE_HELP_ARROW = aMgr.GetImageThrow("IMAGE_HELP_ARROW");
		IMAGE_HELP_GRID_4 = aMgr.GetImageThrow("IMAGE_HELP_GRID_4");
		IMAGE_HELP_GRID_5 = aMgr.GetImageThrow("IMAGE_HELP_GRID_5");
		IMAGE_HELP_INDICATOR = aMgr.GetImageThrow("IMAGE_HELP_INDICATOR");
		IMAGE_HELP_INDICATOR_ALT = aMgr.GetImageThrow("IMAGE_HELP_INDICATOR_ALT");
		IMAGE_HELP_INDICATOR_ARROW = aMgr.GetImageThrow("IMAGE_HELP_INDICATOR_ARROW");
		IMAGE_HS_BOTTOM = aMgr.GetImageThrow("IMAGE_HS_BOTTOM");
		IMAGE_LIGHTNING = aMgr.GetImageThrow("IMAGE_LIGHTNING");
		IMAGE_LIGHTNING_CENTER = aMgr.GetImageThrow("IMAGE_LIGHTNING_CENTER");
		IMAGE_MAIN_ACTION = aMgr.GetImageThrow("IMAGE_MAIN_ACTION");
		IMAGE_MAIN_BIG_OVER = aMgr.GetImageThrow("IMAGE_MAIN_BIG_OVER");
		IMAGE_MAIN_BIG_SELECT = aMgr.GetImageThrow("IMAGE_MAIN_BIG_SELECT");
		IMAGE_MAIN_BOTTOM_GLOW = aMgr.GetImageThrow("IMAGE_MAIN_BOTTOM_GLOW");
		IMAGE_MAIN_CENTER_GLOW = aMgr.GetImageThrow("IMAGE_MAIN_CENTER_GLOW");
		IMAGE_MAIN_CENTER_TEXT = aMgr.GetImageThrow("IMAGE_MAIN_CENTER_TEXT");
		IMAGE_MAIN_CLASSIC = aMgr.GetImageThrow("IMAGE_MAIN_CLASSIC");
		IMAGE_MAIN_COGNITO = aMgr.GetImageThrow("IMAGE_MAIN_COGNITO");
		IMAGE_MAIN_ENDLESS = aMgr.GetImageThrow("IMAGE_MAIN_ENDLESS");
		IMAGE_MAIN_FINITY = aMgr.GetImageThrow("IMAGE_MAIN_FINITY");
		IMAGE_MAIN_GADGETS = aMgr.GetImageThrow("IMAGE_MAIN_GADGETS");
		IMAGE_MAIN_HYPER = aMgr.GetImageThrow("IMAGE_MAIN_HYPER");
		IMAGE_MAIN_LIGHT_BIG = aMgr.GetImageThrow("IMAGE_MAIN_LIGHT_BIG");
		IMAGE_MAIN_LIGHT_MED = aMgr.GetImageThrow("IMAGE_MAIN_LIGHT_MED");
		IMAGE_MAIN_LIGHT_SMALL = aMgr.GetImageThrow("IMAGE_MAIN_LIGHT_SMALL");
		IMAGE_MAIN_OPTIONS = aMgr.GetImageThrow("IMAGE_MAIN_OPTIONS");
		IMAGE_MAIN_PLAY = aMgr.GetImageThrow("IMAGE_MAIN_PLAY");
		IMAGE_MAIN_PLAY_GLOW = aMgr.GetImageThrow("IMAGE_MAIN_PLAY_GLOW");
		IMAGE_MAIN_PUZZLE = aMgr.GetImageThrow("IMAGE_MAIN_PUZZLE");
		IMAGE_MAIN_QUIT = aMgr.GetImageThrow("IMAGE_MAIN_QUIT");
		IMAGE_MAIN_SCORES = aMgr.GetImageThrow("IMAGE_MAIN_SCORES");
		IMAGE_MAIN_SECRET_FRAME = aMgr.GetImageThrow("IMAGE_MAIN_SECRET_FRAME");
		IMAGE_MAIN_SECRET_GLOW = aMgr.GetImageThrow("IMAGE_MAIN_SECRET_GLOW");
		IMAGE_MAIN_SECRET_SYMBOL = aMgr.GetImageThrow("IMAGE_MAIN_SECRET_SYMBOL");
		IMAGE_MAIN_SMALL_GLOW = aMgr.GetImageThrow("IMAGE_MAIN_SMALL_GLOW");
		IMAGE_MAIN_TWILIGHT = aMgr.GetImageThrow("IMAGE_MAIN_TWILIGHT");
		IMAGE_OLD_GEMS = aMgr.GetImageThrow("IMAGE_OLD_GEMS");
		IMAGE_POWER_GLOW = aMgr.GetImageThrow("IMAGE_POWER_GLOW");
		IMAGE_PUZZLE_DOME = aMgr.GetImageThrow("IMAGE_PUZZLE_DOME");
		IMAGE_PUZZLE_DOME_MASK = aMgr.GetImageThrow("IMAGE_PUZZLE_DOME_MASK");
		IMAGE_PUZZLE_DOME_SLIVER = aMgr.GetImageThrow("IMAGE_PUZZLE_DOME_SLIVER");
		IMAGE_PUZZLE_FRAME = aMgr.GetImageThrow("IMAGE_PUZZLE_FRAME");
		IMAGE_PUZZLE_MAP_BUTTON = aMgr.GetImageThrow("IMAGE_PUZZLE_MAP_BUTTON");
		IMAGE_PUZZLE_MAP_BUTTON_GLOW = aMgr.GetImageThrow("IMAGE_PUZZLE_MAP_BUTTON_GLOW");
		IMAGE_PUZZLE_PODS = aMgr.GetImageThrow("IMAGE_PUZZLE_PODS");
		IMAGE_PUZZLE_PODS_LIT = aMgr.GetImageThrow("IMAGE_PUZZLE_PODS_LIT");
		IMAGE_PUZZLE_PUZZLE_LIT = aMgr.GetImageThrow("IMAGE_PUZZLE_PUZZLE_LIT");
		IMAGE_PUZZLE_THUMB_GEM = aMgr.GetImageThrow("IMAGE_PUZZLE_THUMB_GEM");
		IMAGE_PUZZLE_VAPOR1 = aMgr.GetImageThrow("IMAGE_PUZZLE_VAPOR1");
		IMAGE_PUZZLE_VAPOR2 = aMgr.GetImageThrow("IMAGE_PUZZLE_VAPOR2");
		IMAGE_PUZZLE_WARP_BUTTON = aMgr.GetImageThrow("IMAGE_PUZZLE_WARP_BUTTON");
		IMAGE_PUZZLE_WARP_GLOW = aMgr.GetImageThrow("IMAGE_PUZZLE_WARP_GLOW");
		IMAGE_PUZZLE_WIDGET = aMgr.GetImageThrow("IMAGE_PUZZLE_WIDGET");
		IMAGE_RING_DUDE = aMgr.GetImageThrow("IMAGE_RING_DUDE");
		IMAGE_ROCK = aMgr.GetImageThrow("IMAGE_ROCK");
		IMAGE_ROCK_CHUNK = aMgr.GetImageThrow("IMAGE_ROCK_CHUNK");
		IMAGE_SELECT = aMgr.GetImageThrow("IMAGE_SELECT");
		IMAGE_SHARD = aMgr.GetImageThrow("IMAGE_SHARD");
		IMAGE_SIDEBAR_HINT_BUTTON = aMgr.GetImageThrow("IMAGE_SIDEBAR_HINT_BUTTON");
		IMAGE_SIDEBAR_MENU_BUTTON = aMgr.GetImageThrow("IMAGE_SIDEBAR_MENU_BUTTON");
		IMAGE_SLIDER_THUMB = aMgr.GetImageThrow("IMAGE_SLIDER_THUMB");
		IMAGE_SLIDER_TRACK = aMgr.GetImageThrow("IMAGE_SLIDER_TRACK");
		IMAGE_SMALL_GEMS = aMgr.GetImageThrow("IMAGE_SMALL_GEMS");
		IMAGE_SPARKLE = aMgr.GetImageThrow("IMAGE_SPARKLE");
		IMAGE_UI_BIG_ROLLOVER = aMgr.GetImageThrow("IMAGE_UI_BIG_ROLLOVER");
		IMAGE_UI_BUTTON_HINT = aMgr.GetImageThrow("IMAGE_UI_BUTTON_HINT");
		IMAGE_UI_BUTTON_MENU = aMgr.GetImageThrow("IMAGE_UI_BUTTON_MENU");
		IMAGE_UI_BUTTON_PAUSE = aMgr.GetImageThrow("IMAGE_UI_BUTTON_PAUSE");
		IMAGE_UI_BUTTON_UNDO = aMgr.GetImageThrow("IMAGE_UI_BUTTON_UNDO");
		IMAGE_UI_SMALL_ROLLOVER = aMgr.GetImageThrow("IMAGE_UI_SMALL_ROLLOVER");
		IMAGE_WARP_BOTTOM_GLOW = aMgr.GetImageThrow("IMAGE_WARP_BOTTOM_GLOW");
		IMAGE_WARP_TOP_GLOW = aMgr.GetImageThrow("IMAGE_WARP_TOP_GLOW");
		IMAGE_WILDCARD_DESTROYER = aMgr.GetImageThrow("IMAGE_WILDCARD_DESTROYER");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// PuzzleImages Resources
Image* Sexy::IMAGE_PUZZLE_MAP;
Image* Sexy::IMAGE_PUZZLE_MOONS;
Image* Sexy::IMAGE_PUZZLE_PLANETS;

bool Sexy::ExtractPuzzleImagesResources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_PUZZLE_MAP = aMgr.GetImageThrow("IMAGE_PUZZLE_MAP");
		IMAGE_PUZZLE_MOONS = aMgr.GetImageThrow("IMAGE_PUZZLE_MOONS");
		IMAGE_PUZZLE_PLANETS = aMgr.GetImageThrow("IMAGE_PUZZLE_PLANETS");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// Sounds Resources
int Sexy::SOUND_BAD;
int Sexy::SOUND_BOMB_EXPLODE;
int Sexy::SOUND_CLICK;
int Sexy::SOUND_CLICK_DIALOG;
int Sexy::SOUND_COMBO_1;
int Sexy::SOUND_COMBO_2;
int Sexy::SOUND_COMBO_3;
int Sexy::SOUND_COMBO_4;
int Sexy::SOUND_COMBO_5;
int Sexy::SOUND_COMBO_6;
int Sexy::SOUND_ELECTRO_EXPLODE;
int Sexy::SOUND_ELECTRO_PATH;
int Sexy::SOUND_ELECTRO_START;
int Sexy::SOUND_EXCELLENT;
int Sexy::SOUND_EXPLODE;
int Sexy::SOUND_FAIRY_DUST;
int Sexy::SOUND_FIRE_CRACKLE;
int Sexy::SOUND_GALAXY_MAP;
int Sexy::SOUND_GALAXY_PLANET_SELECT;
int Sexy::SOUND_GAME_OVER;
int Sexy::SOUND_GEM_HIT;
int Sexy::SOUND_GET_READY;
int Sexy::SOUND_GO;
int Sexy::SOUND_GOOD;
int Sexy::SOUND_GOODBYE;
int Sexy::SOUND_HIGH_SCORE;
int Sexy::SOUND_HYPERGEM_CREATE;
int Sexy::SOUND_HYPERGEM_DESTROYED;
int Sexy::SOUND_INCREDIBLE;
int Sexy::SOUND_LEVEL_COMPELTE;
int Sexy::SOUND_MAIN_GAME_START;
int Sexy::SOUND_MAIN_LANDING_LIGHTS;
int Sexy::SOUND_MAIN_MOUSE_CLICK;
int Sexy::SOUND_MAIN_MOUSE_LEAVE;
int Sexy::SOUND_MAIN_MOUSE_OVER;
int Sexy::SOUND_MULTISHOT;
int Sexy::SOUND_NO_MORE_MOVES;
int Sexy::SOUND_PANEL_SLIDE;
int Sexy::SOUND_PUZZLE_SOLVED;
int Sexy::SOUND_SELECT;
int Sexy::SOUND_TIME_UP;
int Sexy::SOUND_TRANSFER;
int Sexy::SOUND_TRANSFER_BIG;
int Sexy::SOUND_WARNING;
int Sexy::SOUND_WARP_DRIVE_READY;
int Sexy::SOUND_WELCOME;
int Sexy::SOUND_WELCOME_BACK;
int Sexy::SOUND_WHIRLPOOL;
int Sexy::SOUND_WORLD_COMPELTE;
int Sexy::SOUND_WORLD_COMPLETE;

bool Sexy::ExtractSoundsResources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		SOUND_BAD = aMgr.GetSoundThrow("SOUND_BAD");
		SOUND_BOMB_EXPLODE = aMgr.GetSoundThrow("SOUND_BOMB_EXPLODE");
		SOUND_CLICK = aMgr.GetSoundThrow("SOUND_CLICK");
		SOUND_CLICK_DIALOG = aMgr.GetSoundThrow("SOUND_CLICK_DIALOG");
		SOUND_COMBO_1 = aMgr.GetSoundThrow("SOUND_COMBO_1");
		SOUND_COMBO_2 = aMgr.GetSoundThrow("SOUND_COMBO_2");
		SOUND_COMBO_3 = aMgr.GetSoundThrow("SOUND_COMBO_3");
		SOUND_COMBO_4 = aMgr.GetSoundThrow("SOUND_COMBO_4");
		SOUND_COMBO_5 = aMgr.GetSoundThrow("SOUND_COMBO_5");
		SOUND_COMBO_6 = aMgr.GetSoundThrow("SOUND_COMBO_6");
		SOUND_ELECTRO_EXPLODE = aMgr.GetSoundThrow("SOUND_ELECTRO_EXPLODE");
		SOUND_ELECTRO_PATH = aMgr.GetSoundThrow("SOUND_ELECTRO_PATH");
		SOUND_ELECTRO_START = aMgr.GetSoundThrow("SOUND_ELECTRO_START");
		SOUND_EXCELLENT = aMgr.GetSoundThrow("SOUND_EXCELLENT");
		SOUND_EXPLODE = aMgr.GetSoundThrow("SOUND_EXPLODE");
		SOUND_FAIRY_DUST = aMgr.GetSoundThrow("SOUND_FAIRY_DUST");
		SOUND_FIRE_CRACKLE = aMgr.GetSoundThrow("SOUND_FIRE_CRACKLE");
		SOUND_GALAXY_MAP = aMgr.GetSoundThrow("SOUND_GALAXY_MAP");
		SOUND_GALAXY_PLANET_SELECT = aMgr.GetSoundThrow("SOUND_GALAXY_PLANET_SELECT");
		SOUND_GAME_OVER = aMgr.GetSoundThrow("SOUND_GAME_OVER");
		SOUND_GEM_HIT = aMgr.GetSoundThrow("SOUND_GEM_HIT");
		SOUND_GET_READY = aMgr.GetSoundThrow("SOUND_GET_READY");
		SOUND_GO = aMgr.GetSoundThrow("SOUND_GO");
		SOUND_GOOD = aMgr.GetSoundThrow("SOUND_GOOD");
		SOUND_GOODBYE = aMgr.GetSoundThrow("SOUND_GOODBYE");
		SOUND_HIGH_SCORE = aMgr.GetSoundThrow("SOUND_HIGH_SCORE");
		SOUND_HYPERGEM_CREATE = aMgr.GetSoundThrow("SOUND_HYPERGEM_CREATE");
		SOUND_HYPERGEM_DESTROYED = aMgr.GetSoundThrow("SOUND_HYPERGEM_DESTROYED");
		SOUND_INCREDIBLE = aMgr.GetSoundThrow("SOUND_INCREDIBLE");
		SOUND_LEVEL_COMPELTE = aMgr.GetSoundThrow("SOUND_LEVEL_COMPELTE");
		SOUND_MAIN_GAME_START = aMgr.GetSoundThrow("SOUND_MAIN_GAME_START");
		SOUND_MAIN_LANDING_LIGHTS = aMgr.GetSoundThrow("SOUND_MAIN_LANDING_LIGHTS");
		SOUND_MAIN_MOUSE_CLICK = aMgr.GetSoundThrow("SOUND_MAIN_MOUSE_CLICK");
		SOUND_MAIN_MOUSE_LEAVE = aMgr.GetSoundThrow("SOUND_MAIN_MOUSE_LEAVE");
		SOUND_MAIN_MOUSE_OVER = aMgr.GetSoundThrow("SOUND_MAIN_MOUSE_OVER");
		SOUND_MULTISHOT = aMgr.GetSoundThrow("SOUND_MULTISHOT");
		SOUND_NO_MORE_MOVES = aMgr.GetSoundThrow("SOUND_NO_MORE_MOVES");
		SOUND_PANEL_SLIDE = aMgr.GetSoundThrow("SOUND_PANEL_SLIDE");
		SOUND_PUZZLE_SOLVED = aMgr.GetSoundThrow("SOUND_PUZZLE_SOLVED");
		SOUND_SELECT = aMgr.GetSoundThrow("SOUND_SELECT");
		SOUND_TIME_UP = aMgr.GetSoundThrow("SOUND_TIME_UP");
		SOUND_TRANSFER = aMgr.GetSoundThrow("SOUND_TRANSFER");
		SOUND_TRANSFER_BIG = aMgr.GetSoundThrow("SOUND_TRANSFER_BIG");
		SOUND_WARNING = aMgr.GetSoundThrow("SOUND_WARNING");
		SOUND_WARP_DRIVE_READY = aMgr.GetSoundThrow("SOUND_WARP_DRIVE_READY");
		SOUND_WELCOME = aMgr.GetSoundThrow("SOUND_WELCOME");
		SOUND_WELCOME_BACK = aMgr.GetSoundThrow("SOUND_WELCOME_BACK");
		SOUND_WHIRLPOOL = aMgr.GetSoundThrow("SOUND_WHIRLPOOL");
		SOUND_WORLD_COMPELTE = aMgr.GetSoundThrow("SOUND_WORLD_COMPELTE");
		SOUND_WORLD_COMPLETE = aMgr.GetSoundThrow("SOUND_WORLD_COMPLETE");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

static void* gResources[] =
{
	&IMAGE_LOGO,
	&IMAGE_LOGO_2,
	&IMAGE_LOADER_BAR,
	&IMAGE_LOADER_BAR_LIT_BLUE,
	&IMAGE_LOADER_BAR_LIT_PURPLE,
	&IMAGE_LOADER_BAR_FLASH,
	&IMAGE_LOGO_POPCAP,
	&FONT_1,
	&FONT_3,
	&FONT_CONTINUUM_MED_HDR,
	&FONT_CONTINUUM_MED_HDR_GLOW,
	&FONT_CONT_MED,
	&FONT_SEGOETV11,
	&FONT_SEGOETV11_GLOW,
	&FONT_SEGOETV12,
	&FONT_SEGOETV12_GLOW,
	&FONT_SEGOETV22,
	&FONT_SEGOETV22_GLOW,
	&FONT_GILLSANS14,
	&FONT_CONT_11,
	&SOUND_TRANSFER,
	&SOUND_TRANSFER_BIG,
	&SOUND_COMBO_1,
	&SOUND_COMBO_2,
	&SOUND_COMBO_3,
	&SOUND_COMBO_4,
	&SOUND_COMBO_5,
	&SOUND_COMBO_6,
	&SOUND_BAD,
	&SOUND_GEM_HIT,
	&SOUND_HYPERGEM_CREATE,
	&SOUND_HYPERGEM_DESTROYED,
	&SOUND_EXPLODE,
	&SOUND_CLICK,
	&SOUND_CLICK_DIALOG,
	&SOUND_SELECT,
	&SOUND_MULTISHOT,
	&SOUND_GO,
	&SOUND_GAME_OVER,
	&SOUND_TIME_UP,
	&SOUND_FIRE_CRACKLE,
	&SOUND_WARNING,
	&SOUND_WHIRLPOOL,
	&SOUND_GOOD,
	&SOUND_EXCELLENT,
	&SOUND_INCREDIBLE,
	&SOUND_BOMB_EXPLODE,
	&SOUND_FAIRY_DUST,
	&SOUND_ELECTRO_START,
	&SOUND_ELECTRO_PATH,
	&SOUND_ELECTRO_EXPLODE,
	&SOUND_PANEL_SLIDE,
	&SOUND_HIGH_SCORE,
	&SOUND_MAIN_GAME_START,
	&SOUND_MAIN_MOUSE_CLICK,
	&SOUND_MAIN_MOUSE_OVER,
	&SOUND_MAIN_MOUSE_LEAVE,
	&SOUND_MAIN_LANDING_LIGHTS,
	&SOUND_GALAXY_MAP,
	&SOUND_GALAXY_PLANET_SELECT,
	&SOUND_GET_READY,
	&SOUND_WELCOME,
	&SOUND_GOODBYE,
	&SOUND_WELCOME_BACK,
	&SOUND_PUZZLE_SOLVED,
	&SOUND_LEVEL_COMPELTE,
	&SOUND_WORLD_COMPELTE,
	&SOUND_WARP_DRIVE_READY,
	&SOUND_WORLD_COMPLETE,
	&SOUND_NO_MORE_MOVES,
	&IMAGE_MAIN_BKG,
	&IMAGE_MAIN_FG,
	&IMAGE_MAIN_FOG_BANK,
	&IMAGE_MAIN_FOG_BANK_FG,
	&IMAGE_MAIN_STARFIELD,
	&IMAGE_MAIN_STAR_SPARKLE,
	&IMAGE_MAIN_COMET,
	&IMAGE_MAIN_PLANET_1,
	&IMAGE_HYPERSPACE,
	&IMAGE_HYPERSPACE_INITIAL,
	&IMAGE_TUNNEL_END,
	&IMAGE_WARP_LINES,
	&IMAGE_FIRE_RING,
	&IMAGE_BLACK_HOLE,
	&IMAGE_BLACK_HOLE_COVER,
	&IMAGE_SMALL_GEMS,
	&IMAGE_WILDCARD_DESTROYER,
	&IMAGE_HELP_INDICATOR,
	&IMAGE_HELP_INDICATOR_ALT,
	&IMAGE_HELP_INDICATOR_ARROW,
	&IMAGE_HELP_ARROW,
	&IMAGE_GEM0,
	&IMAGE_GEM1,
	&IMAGE_GEM2,
	&IMAGE_GEM3,
	&IMAGE_GEM4,
	&IMAGE_GEM5,
	&IMAGE_GEM6,
	&IMAGE_OLD_GEMS,
	&IMAGE_GEM_ADD,
	&IMAGE_SELECT,
	&IMAGE_SPARKLE,
	&IMAGE_EDIT_BOX,
	&IMAGE_BOARD_BORDER,
	&IMAGE_BOARD_RED_LIGHT,
	&IMAGE_PUZZLE_FRAME,
	&IMAGE_SIDEBAR_HINT_BUTTON,
	&IMAGE_SIDEBAR_MENU_BUTTON,
	&IMAGE_BOMB,
	&IMAGE_EXPLOSION,
	&IMAGE_SHARD,
	&IMAGE_BIGSTAR,
	&IMAGE_ROCK,
	&IMAGE_ROCK_CHUNK,
	&IMAGE_BAR_LEFT,
	&IMAGE_BAR_RIGHT,
	&IMAGE_BAR_MID,
	&IMAGE_CONTROLS_SCORE,
	&IMAGE_CONTROLS_CLASSIC,
	&IMAGE_CONTROLS_PUZZLE,
	&IMAGE_CONTROLS_PUZZLE_ALT,
	&IMAGE_BUTTON_HILITE,
	&IMAGE_RING_DUDE,
	&IMAGE_GEM_LIGHTING,
	&IMAGE_LIGHTNING,
	&IMAGE_LIGHTNING_CENTER,
	&IMAGE_POWER_GLOW,
	&IMAGE_WARP_TOP_GLOW,
	&IMAGE_WARP_BOTTOM_GLOW,
	&IMAGE_HELP_GRID_4,
	&IMAGE_HELP_GRID_5,
	&IMAGE_ARROW_UP,
	&IMAGE_DIALOG,
	&IMAGE_DIALOG_HEADER,
	&IMAGE_DIALOG_BUTTON,
	&IMAGE_DIALOG_BUTTON_GLOW,
	&IMAGE_SLIDER_TRACK,
	&IMAGE_SLIDER_THUMB,
	&IMAGE_CHECKBOX,
	&IMAGE_UI_BIG_ROLLOVER,
	&IMAGE_UI_SMALL_ROLLOVER,
	&IMAGE_UI_BUTTON_HINT,
	&IMAGE_UI_BUTTON_MENU,
	&IMAGE_UI_BUTTON_UNDO,
	&IMAGE_UI_BUTTON_PAUSE,
	&IMAGE_PUZZLE_WIDGET,
	&IMAGE_PUZZLE_PODS,
	&IMAGE_PUZZLE_PODS_LIT,
	&IMAGE_PUZZLE_DOME,
	&IMAGE_PUZZLE_DOME_MASK,
	&IMAGE_PUZZLE_DOME_SLIVER,
	&IMAGE_PUZZLE_PUZZLE_LIT,
	&IMAGE_PUZZLE_THUMB_GEM,
	&IMAGE_PUZZLE_VAPOR1,
	&IMAGE_PUZZLE_VAPOR2,
	&IMAGE_PUZZLE_MAP_BUTTON,
	&IMAGE_PUZZLE_MAP_BUTTON_GLOW,
	&IMAGE_PUZZLE_WARP_BUTTON,
	&IMAGE_PUZZLE_WARP_GLOW,
	&IMAGE_ENDLESS_WIDGET,
	&IMAGE_ENDLESS_CENTER_1,
	&IMAGE_ENDLESS_CENTER_2,
	&IMAGE_ENDLESS_CENTER_3,
	&IMAGE_ENDLESS_CENTER_4,
	&IMAGE_ENDLESS_CENTER_5,
	&IMAGE_ENDLESS_CENTER_6,
	&IMAGE_ENDLESS_CENTER_7,
	&IMAGE_ENDLESS_OUTER_1,
	&IMAGE_ENDLESS_OUTER_2,
	&IMAGE_ENDLESS_OUTER_3,
	&IMAGE_ENDLESS_OUTER_4,
	&IMAGE_ENDLESS_OUTER_5,
	&IMAGE_ENDLESS_OUTER_6,
	&IMAGE_ENDLESS_OUTER_7,
	&IMAGE_ENDLESS_SPARK_1,
	&IMAGE_ENDLESS_SPARK_2,
	&IMAGE_ENDLESS_SPARK_3,
	&IMAGE_ENDLESS_GEM_HILITE,
	&IMAGE_GALAXY_MAP,
	&IMAGE_GALAXY_BUTTON_HILITE,
	&IMAGE_GALAXY_WARP_BUTTON,
	&IMAGE_GALAXY_CLOSE_BUTTON,
	&IMAGE_GALAXY_PLANET_ALPHA,
	&IMAGE_GALAXY_SUN_MOON_ALPHA,
	&IMAGE_GALAXY_MOON_ALPHA,
	&IMAGE_GALAXY_PLANET_SELECT,
	&IMAGE_GALAXY_PLANET_COMPLETED,
	&IMAGE_GALAXY_SUN_GLOW,
	&IMAGE_GALAXY_SUN_SWIRL,
	&IMAGE_GALAXY_QUESTION,
	&IMAGE_GALAXY_MOON_SELECT,
	&IMAGE_HS_BOTTOM,
	&IMAGE_MAIN_GADGETS,
	&IMAGE_MAIN_BIG_SELECT,
	&IMAGE_MAIN_BIG_OVER,
	&IMAGE_MAIN_SMALL_GLOW,
	&IMAGE_MAIN_PLAY_GLOW,
	&IMAGE_MAIN_BOTTOM_GLOW,
	&IMAGE_MAIN_CLASSIC,
	&IMAGE_MAIN_ACTION,
	&IMAGE_MAIN_PUZZLE,
	&IMAGE_MAIN_ENDLESS,
	&IMAGE_MAIN_TWILIGHT,
	&IMAGE_MAIN_HYPER,
	&IMAGE_MAIN_COGNITO,
	&IMAGE_MAIN_FINITY,
	&IMAGE_MAIN_OPTIONS,
	&IMAGE_MAIN_SCORES,
	&IMAGE_MAIN_PLAY,
	&IMAGE_MAIN_QUIT,
	&IMAGE_MAIN_CENTER_TEXT,
	&IMAGE_MAIN_LIGHT_BIG,
	&IMAGE_MAIN_LIGHT_MED,
	&IMAGE_MAIN_LIGHT_SMALL,
	&IMAGE_MAIN_CENTER_GLOW,
	&IMAGE_MAIN_SECRET_GLOW,
	&IMAGE_MAIN_SECRET_FRAME,
	&IMAGE_MAIN_SECRET_SYMBOL,
	&FONT_VAG_ROUNDED_11,
	&FONT_DIGIT,
	&FONT_BOMB,
	&FONT_HUGE,
	&FONT_SCORE,
	&FONT_LEADERBOARD,
	&FONT_ENGSMALL,
	&IMAGE_BACKDROP00,
	&IMAGE_BACKDROP01,
	&IMAGE_BACKDROP02,
	&IMAGE_BACKDROP03,
	&IMAGE_BACKDROP04,
	&IMAGE_BACKDROP05,
	&IMAGE_BACKDROP06,
	&IMAGE_BACKDROP07,
	&IMAGE_BACKDROP08,
	&IMAGE_BACKDROP09,
	&IMAGE_BACKDROP10,
	&IMAGE_BACKDROP11,
	&IMAGE_BACKDROP12,
	&IMAGE_BACKDROP13,
	&IMAGE_BACKDROP14,
	&IMAGE_BACKDROP15,
	&IMAGE_BACKDROP16,
	&IMAGE_BACKDROP17,
	&IMAGE_ZENDROP1,
	&IMAGE_ZENDROP2,
	&IMAGE_ZENDROP3,
	&IMAGE_ZENDROP4,
	&IMAGE_ZENDROP5,
	&IMAGE_ZENDROP6,
	&IMAGE_ZENDROP7,
	&IMAGE_ZENDROP8,
	&IMAGE_ZENDROP9,
	&IMAGE_ZENDROP10,
	&IMAGE_ZENDROP11,
	&IMAGE_ZENDROP12,
	&IMAGE_ZENDROP13,
	&IMAGE_ZENDROP14,
	&IMAGE_ZENDROP15,
	&IMAGE_ZENDROP16,
	&IMAGE_ZENDROP17,
	&IMAGE_ZENDROP18,
	&IMAGE_ZENDROP19,
	&IMAGE_ZENDROP20,
	&IMAGE_ZENDROP21,
	&IMAGE_ZENDROP22,
	&IMAGE_ZENDROP23,
	&IMAGE_ZENDROP24,
	&IMAGE_ZENDROP25,
	&IMAGE_ZENDROP26,
	&IMAGE_ZENDROP27,
	&IMAGE_ZENDROP28,
	&IMAGE_ZENDROP29,
	&IMAGE_ZENDROP30,
	&IMAGE_ZENDROP31,
	&IMAGE_ZENDROP32,
	&IMAGE_ZENDROP33,
	&IMAGE_ZENDROP34,
	&IMAGE_ZENDROP35,
	&IMAGE_ZENDROP36,
	&IMAGE_ZENDROP37,
	&IMAGE_ZENDROP38,
	&IMAGE_ZENDROP39,
	&IMAGE_ZENDROP40,
	&IMAGE_A_BUTTON,
	&IMAGE_B_BUTTON,
	&IMAGE_X_BUTTON,
	&IMAGE_Y_BUTTON,
	&IMAGE_LB_BUTTON,
	&IMAGE_RB_BUTTON,
	&IMAGE_JOYSTICK,
	&IMAGE_ACHIEVEMENT1,
	&IMAGE_ACHIEVEMENT2,
	&IMAGE_ACHIEVEMENT3,
	&IMAGE_ACHIEVEMENT4,
	&IMAGE_ACHIEVEMENT5,
	&IMAGE_ACHIEVEMENT6,
	&IMAGE_ACHIEVEMENT7,
	&IMAGE_ACHIEVEMENT8,
	&IMAGE_ACHIEVEMENT9,
	&IMAGE_ACHIEVEMENT10,
	&IMAGE_ACHIEVEMENT11,
	&IMAGE_ACHIEVEMENT12,
	&IMAGE_DPAD_LEFT,
	&IMAGE_DPAD_RIGHT,
	&IMAGE_DPAD_UP,
	&IMAGE_DPAD_DOWN,
	&IMAGE_DPAD_UPDOWN,
	&IMAGE_DPAD_LEFTRIGHT,
	&IMAGE_MENU_BUTTON,
	&IMAGE_MENU_BUTTON_GLOW2,
	&IMAGE_NEBULA1,
	&IMAGE_PUZZLE_PLANETS,
	&IMAGE_PUZZLE_MOONS,
	&IMAGE_PUZZLE_MAP,
	NULL
};

Image* Sexy::LoadImageById(ResourceManager *theManager, int theId)
{
	return (*((Image**)gResources[theId]) = theManager->LoadImage(GetStringIdById(theId)));
}

void Sexy::ReplaceImageById(ResourceManager *theManager, int theId, Image *theImage)
{
	theManager->ReplaceImage(GetStringIdById(theId),theImage);
	*(Image**)gResources[theId] = theImage;
}

Image* Sexy::GetImageById(int theId)
{
	return *(Image**)gResources[theId];
}

Font* Sexy::GetFontById(int theId)
{
	return *(Font**)gResources[theId];
}

int Sexy::GetSoundById(int theId)
{
	return *(int*)gResources[theId];
}

Image*& Sexy::GetImageRefById(int theId)
{
	return *(Image**)gResources[theId];
}

Font*& Sexy::GetFontRefById(int theId)
{
	return *(Font**)gResources[theId];
}

int& Sexy::GetSoundRefById(int theId)
{
	return *(int*)gResources[theId];
}

static Sexy::ResourceId GetIdByVariable(const void *theVariable)
{
	typedef std::map<int,int> MyMap;
	static MyMap aMap;
	if(gNeedRecalcVariableToIdMap)
	{
		gNeedRecalcVariableToIdMap = false;
		aMap.clear();
		for(int i=0; i<RESOURCE_ID_MAX; i++)
			aMap[*(int*)gResources[i]] = i;
	}

	MyMap::iterator anItr = aMap.find((int)theVariable);
	if (anItr == aMap.end())
		return RESOURCE_ID_MAX;
	else
		return (ResourceId) anItr->second;
}

Sexy::ResourceId Sexy::GetIdByImage(Image *theImage)
{
	return GetIdByVariable(theImage);
}

Sexy::ResourceId Sexy::GetIdByFont(Font *theFont)
{
	return GetIdByVariable(theFont);
}

Sexy::ResourceId Sexy::GetIdBySound(int theSound)
{
	return GetIdByVariable((void*)theSound);
}

const char* Sexy::GetStringIdById(int theId)
{
	switch(theId)
	{
		case IMAGE_LOGO_ID: return "IMAGE_LOGO";
		case IMAGE_LOGO_2_ID: return "IMAGE_LOGO_2";
		case IMAGE_LOADER_BAR_ID: return "IMAGE_LOADER_BAR";
		case IMAGE_LOADER_BAR_LIT_BLUE_ID: return "IMAGE_LOADER_BAR_LIT_BLUE";
		case IMAGE_LOADER_BAR_LIT_PURPLE_ID: return "IMAGE_LOADER_BAR_LIT_PURPLE";
		case IMAGE_LOADER_BAR_FLASH_ID: return "IMAGE_LOADER_BAR_FLASH";
		case IMAGE_LOGO_POPCAP_ID: return "IMAGE_LOGO_POPCAP";
		case FONT_1_ID: return "FONT_1";
		case FONT_3_ID: return "FONT_3";
		case FONT_CONTINUUM_MED_HDR_ID: return "FONT_CONTINUUM_MED_HDR";
		case FONT_CONTINUUM_MED_HDR_GLOW_ID: return "FONT_CONTINUUM_MED_HDR_GLOW";
		case FONT_CONT_MED_ID: return "FONT_CONT_MED";
		case FONT_SEGOETV11_ID: return "FONT_SEGOETV11";
		case FONT_SEGOETV11_GLOW_ID: return "FONT_SEGOETV11_GLOW";
		case FONT_SEGOETV12_ID: return "FONT_SEGOETV12";
		case FONT_SEGOETV12_GLOW_ID: return "FONT_SEGOETV12_GLOW";
		case FONT_SEGOETV22_ID: return "FONT_SEGOETV22";
		case FONT_SEGOETV22_GLOW_ID: return "FONT_SEGOETV22_GLOW";
		case FONT_GILLSANS14_ID: return "FONT_GILLSANS14";
		case FONT_CONT_11_ID: return "FONT_CONT_11";
		case SOUND_TRANSFER_ID: return "SOUND_TRANSFER";
		case SOUND_TRANSFER_BIG_ID: return "SOUND_TRANSFER_BIG";
		case SOUND_COMBO_1_ID: return "SOUND_COMBO_1";
		case SOUND_COMBO_2_ID: return "SOUND_COMBO_2";
		case SOUND_COMBO_3_ID: return "SOUND_COMBO_3";
		case SOUND_COMBO_4_ID: return "SOUND_COMBO_4";
		case SOUND_COMBO_5_ID: return "SOUND_COMBO_5";
		case SOUND_COMBO_6_ID: return "SOUND_COMBO_6";
		case SOUND_BAD_ID: return "SOUND_BAD";
		case SOUND_GEM_HIT_ID: return "SOUND_GEM_HIT";
		case SOUND_HYPERGEM_CREATE_ID: return "SOUND_HYPERGEM_CREATE";
		case SOUND_HYPERGEM_DESTROYED_ID: return "SOUND_HYPERGEM_DESTROYED";
		case SOUND_EXPLODE_ID: return "SOUND_EXPLODE";
		case SOUND_CLICK_ID: return "SOUND_CLICK";
		case SOUND_CLICK_DIALOG_ID: return "SOUND_CLICK_DIALOG";
		case SOUND_SELECT_ID: return "SOUND_SELECT";
		case SOUND_MULTISHOT_ID: return "SOUND_MULTISHOT";
		case SOUND_GO_ID: return "SOUND_GO";
		case SOUND_GAME_OVER_ID: return "SOUND_GAME_OVER";
		case SOUND_TIME_UP_ID: return "SOUND_TIME_UP";
		case SOUND_FIRE_CRACKLE_ID: return "SOUND_FIRE_CRACKLE";
		case SOUND_WARNING_ID: return "SOUND_WARNING";
		case SOUND_WHIRLPOOL_ID: return "SOUND_WHIRLPOOL";
		case SOUND_GOOD_ID: return "SOUND_GOOD";
		case SOUND_EXCELLENT_ID: return "SOUND_EXCELLENT";
		case SOUND_INCREDIBLE_ID: return "SOUND_INCREDIBLE";
		case SOUND_BOMB_EXPLODE_ID: return "SOUND_BOMB_EXPLODE";
		case SOUND_FAIRY_DUST_ID: return "SOUND_FAIRY_DUST";
		case SOUND_ELECTRO_START_ID: return "SOUND_ELECTRO_START";
		case SOUND_ELECTRO_PATH_ID: return "SOUND_ELECTRO_PATH";
		case SOUND_ELECTRO_EXPLODE_ID: return "SOUND_ELECTRO_EXPLODE";
		case SOUND_PANEL_SLIDE_ID: return "SOUND_PANEL_SLIDE";
		case SOUND_HIGH_SCORE_ID: return "SOUND_HIGH_SCORE";
		case SOUND_MAIN_GAME_START_ID: return "SOUND_MAIN_GAME_START";
		case SOUND_MAIN_MOUSE_CLICK_ID: return "SOUND_MAIN_MOUSE_CLICK";
		case SOUND_MAIN_MOUSE_OVER_ID: return "SOUND_MAIN_MOUSE_OVER";
		case SOUND_MAIN_MOUSE_LEAVE_ID: return "SOUND_MAIN_MOUSE_LEAVE";
		case SOUND_MAIN_LANDING_LIGHTS_ID: return "SOUND_MAIN_LANDING_LIGHTS";
		case SOUND_GALAXY_MAP_ID: return "SOUND_GALAXY_MAP";
		case SOUND_GALAXY_PLANET_SELECT_ID: return "SOUND_GALAXY_PLANET_SELECT";
		case SOUND_GET_READY_ID: return "SOUND_GET_READY";
		case SOUND_WELCOME_ID: return "SOUND_WELCOME";
		case SOUND_GOODBYE_ID: return "SOUND_GOODBYE";
		case SOUND_WELCOME_BACK_ID: return "SOUND_WELCOME_BACK";
		case SOUND_PUZZLE_SOLVED_ID: return "SOUND_PUZZLE_SOLVED";
		case SOUND_LEVEL_COMPELTE_ID: return "SOUND_LEVEL_COMPELTE";
		case SOUND_WORLD_COMPELTE_ID: return "SOUND_WORLD_COMPELTE";
		case SOUND_WARP_DRIVE_READY_ID: return "SOUND_WARP_DRIVE_READY";
		case SOUND_WORLD_COMPLETE_ID: return "SOUND_WORLD_COMPLETE";
		case SOUND_NO_MORE_MOVES_ID: return "SOUND_NO_MORE_MOVES";
		case IMAGE_MAIN_BKG_ID: return "IMAGE_MAIN_BKG";
		case IMAGE_MAIN_FG_ID: return "IMAGE_MAIN_FG";
		case IMAGE_MAIN_FOG_BANK_ID: return "IMAGE_MAIN_FOG_BANK";
		case IMAGE_MAIN_FOG_BANK_FG_ID: return "IMAGE_MAIN_FOG_BANK_FG";
		case IMAGE_MAIN_STARFIELD_ID: return "IMAGE_MAIN_STARFIELD";
		case IMAGE_MAIN_STAR_SPARKLE_ID: return "IMAGE_MAIN_STAR_SPARKLE";
		case IMAGE_MAIN_COMET_ID: return "IMAGE_MAIN_COMET";
		case IMAGE_MAIN_PLANET_1_ID: return "IMAGE_MAIN_PLANET_1";
		case IMAGE_HYPERSPACE_ID: return "IMAGE_HYPERSPACE";
		case IMAGE_HYPERSPACE_INITIAL_ID: return "IMAGE_HYPERSPACE_INITIAL";
		case IMAGE_TUNNEL_END_ID: return "IMAGE_TUNNEL_END";
		case IMAGE_WARP_LINES_ID: return "IMAGE_WARP_LINES";
		case IMAGE_FIRE_RING_ID: return "IMAGE_FIRE_RING";
		case IMAGE_BLACK_HOLE_ID: return "IMAGE_BLACK_HOLE";
		case IMAGE_BLACK_HOLE_COVER_ID: return "IMAGE_BLACK_HOLE_COVER";
		case IMAGE_SMALL_GEMS_ID: return "IMAGE_SMALL_GEMS";
		case IMAGE_WILDCARD_DESTROYER_ID: return "IMAGE_WILDCARD_DESTROYER";
		case IMAGE_HELP_INDICATOR_ID: return "IMAGE_HELP_INDICATOR";
		case IMAGE_HELP_INDICATOR_ALT_ID: return "IMAGE_HELP_INDICATOR_ALT";
		case IMAGE_HELP_INDICATOR_ARROW_ID: return "IMAGE_HELP_INDICATOR_ARROW";
		case IMAGE_HELP_ARROW_ID: return "IMAGE_HELP_ARROW";
		case IMAGE_GEM0_ID: return "IMAGE_GEM0";
		case IMAGE_GEM1_ID: return "IMAGE_GEM1";
		case IMAGE_GEM2_ID: return "IMAGE_GEM2";
		case IMAGE_GEM3_ID: return "IMAGE_GEM3";
		case IMAGE_GEM4_ID: return "IMAGE_GEM4";
		case IMAGE_GEM5_ID: return "IMAGE_GEM5";
		case IMAGE_GEM6_ID: return "IMAGE_GEM6";
		case IMAGE_OLD_GEMS_ID: return "IMAGE_OLD_GEMS";
		case IMAGE_GEM_ADD_ID: return "IMAGE_GEM_ADD";
		case IMAGE_SELECT_ID: return "IMAGE_SELECT";
		case IMAGE_SPARKLE_ID: return "IMAGE_SPARKLE";
		case IMAGE_EDIT_BOX_ID: return "IMAGE_EDIT_BOX";
		case IMAGE_BOARD_BORDER_ID: return "IMAGE_BOARD_BORDER";
		case IMAGE_BOARD_RED_LIGHT_ID: return "IMAGE_BOARD_RED_LIGHT";
		case IMAGE_PUZZLE_FRAME_ID: return "IMAGE_PUZZLE_FRAME";
		case IMAGE_SIDEBAR_HINT_BUTTON_ID: return "IMAGE_SIDEBAR_HINT_BUTTON";
		case IMAGE_SIDEBAR_MENU_BUTTON_ID: return "IMAGE_SIDEBAR_MENU_BUTTON";
		case IMAGE_BOMB_ID: return "IMAGE_BOMB";
		case IMAGE_EXPLOSION_ID: return "IMAGE_EXPLOSION";
		case IMAGE_SHARD_ID: return "IMAGE_SHARD";
		case IMAGE_BIGSTAR_ID: return "IMAGE_BIGSTAR";
		case IMAGE_ROCK_ID: return "IMAGE_ROCK";
		case IMAGE_ROCK_CHUNK_ID: return "IMAGE_ROCK_CHUNK";
		case IMAGE_BAR_LEFT_ID: return "IMAGE_BAR_LEFT";
		case IMAGE_BAR_RIGHT_ID: return "IMAGE_BAR_RIGHT";
		case IMAGE_BAR_MID_ID: return "IMAGE_BAR_MID";
		case IMAGE_CONTROLS_SCORE_ID: return "IMAGE_CONTROLS_SCORE";
		case IMAGE_CONTROLS_CLASSIC_ID: return "IMAGE_CONTROLS_CLASSIC";
		case IMAGE_CONTROLS_PUZZLE_ID: return "IMAGE_CONTROLS_PUZZLE";
		case IMAGE_CONTROLS_PUZZLE_ALT_ID: return "IMAGE_CONTROLS_PUZZLE_ALT";
		case IMAGE_BUTTON_HILITE_ID: return "IMAGE_BUTTON_HILITE";
		case IMAGE_RING_DUDE_ID: return "IMAGE_RING_DUDE";
		case IMAGE_GEM_LIGHTING_ID: return "IMAGE_GEM_LIGHTING";
		case IMAGE_LIGHTNING_ID: return "IMAGE_LIGHTNING";
		case IMAGE_LIGHTNING_CENTER_ID: return "IMAGE_LIGHTNING_CENTER";
		case IMAGE_POWER_GLOW_ID: return "IMAGE_POWER_GLOW";
		case IMAGE_WARP_TOP_GLOW_ID: return "IMAGE_WARP_TOP_GLOW";
		case IMAGE_WARP_BOTTOM_GLOW_ID: return "IMAGE_WARP_BOTTOM_GLOW";
		case IMAGE_HELP_GRID_4_ID: return "IMAGE_HELP_GRID_4";
		case IMAGE_HELP_GRID_5_ID: return "IMAGE_HELP_GRID_5";
		case IMAGE_ARROW_UP_ID: return "IMAGE_ARROW_UP";
		case IMAGE_DIALOG_ID: return "IMAGE_DIALOG";
		case IMAGE_DIALOG_HEADER_ID: return "IMAGE_DIALOG_HEADER";
		case IMAGE_DIALOG_BUTTON_ID: return "IMAGE_DIALOG_BUTTON";
		case IMAGE_DIALOG_BUTTON_GLOW_ID: return "IMAGE_DIALOG_BUTTON_GLOW";
		case IMAGE_SLIDER_TRACK_ID: return "IMAGE_SLIDER_TRACK";
		case IMAGE_SLIDER_THUMB_ID: return "IMAGE_SLIDER_THUMB";
		case IMAGE_CHECKBOX_ID: return "IMAGE_CHECKBOX";
		case IMAGE_UI_BIG_ROLLOVER_ID: return "IMAGE_UI_BIG_ROLLOVER";
		case IMAGE_UI_SMALL_ROLLOVER_ID: return "IMAGE_UI_SMALL_ROLLOVER";
		case IMAGE_UI_BUTTON_HINT_ID: return "IMAGE_UI_BUTTON_HINT";
		case IMAGE_UI_BUTTON_MENU_ID: return "IMAGE_UI_BUTTON_MENU";
		case IMAGE_UI_BUTTON_UNDO_ID: return "IMAGE_UI_BUTTON_UNDO";
		case IMAGE_UI_BUTTON_PAUSE_ID: return "IMAGE_UI_BUTTON_PAUSE";
		case IMAGE_PUZZLE_WIDGET_ID: return "IMAGE_PUZZLE_WIDGET";
		case IMAGE_PUZZLE_PODS_ID: return "IMAGE_PUZZLE_PODS";
		case IMAGE_PUZZLE_PODS_LIT_ID: return "IMAGE_PUZZLE_PODS_LIT";
		case IMAGE_PUZZLE_DOME_ID: return "IMAGE_PUZZLE_DOME";
		case IMAGE_PUZZLE_DOME_MASK_ID: return "IMAGE_PUZZLE_DOME_MASK";
		case IMAGE_PUZZLE_DOME_SLIVER_ID: return "IMAGE_PUZZLE_DOME_SLIVER";
		case IMAGE_PUZZLE_PUZZLE_LIT_ID: return "IMAGE_PUZZLE_PUZZLE_LIT";
		case IMAGE_PUZZLE_THUMB_GEM_ID: return "IMAGE_PUZZLE_THUMB_GEM";
		case IMAGE_PUZZLE_VAPOR1_ID: return "IMAGE_PUZZLE_VAPOR1";
		case IMAGE_PUZZLE_VAPOR2_ID: return "IMAGE_PUZZLE_VAPOR2";
		case IMAGE_PUZZLE_MAP_BUTTON_ID: return "IMAGE_PUZZLE_MAP_BUTTON";
		case IMAGE_PUZZLE_MAP_BUTTON_GLOW_ID: return "IMAGE_PUZZLE_MAP_BUTTON_GLOW";
		case IMAGE_PUZZLE_WARP_BUTTON_ID: return "IMAGE_PUZZLE_WARP_BUTTON";
		case IMAGE_PUZZLE_WARP_GLOW_ID: return "IMAGE_PUZZLE_WARP_GLOW";
		case IMAGE_ENDLESS_WIDGET_ID: return "IMAGE_ENDLESS_WIDGET";
		case IMAGE_ENDLESS_CENTER_1_ID: return "IMAGE_ENDLESS_CENTER_1";
		case IMAGE_ENDLESS_CENTER_2_ID: return "IMAGE_ENDLESS_CENTER_2";
		case IMAGE_ENDLESS_CENTER_3_ID: return "IMAGE_ENDLESS_CENTER_3";
		case IMAGE_ENDLESS_CENTER_4_ID: return "IMAGE_ENDLESS_CENTER_4";
		case IMAGE_ENDLESS_CENTER_5_ID: return "IMAGE_ENDLESS_CENTER_5";
		case IMAGE_ENDLESS_CENTER_6_ID: return "IMAGE_ENDLESS_CENTER_6";
		case IMAGE_ENDLESS_CENTER_7_ID: return "IMAGE_ENDLESS_CENTER_7";
		case IMAGE_ENDLESS_OUTER_1_ID: return "IMAGE_ENDLESS_OUTER_1";
		case IMAGE_ENDLESS_OUTER_2_ID: return "IMAGE_ENDLESS_OUTER_2";
		case IMAGE_ENDLESS_OUTER_3_ID: return "IMAGE_ENDLESS_OUTER_3";
		case IMAGE_ENDLESS_OUTER_4_ID: return "IMAGE_ENDLESS_OUTER_4";
		case IMAGE_ENDLESS_OUTER_5_ID: return "IMAGE_ENDLESS_OUTER_5";
		case IMAGE_ENDLESS_OUTER_6_ID: return "IMAGE_ENDLESS_OUTER_6";
		case IMAGE_ENDLESS_OUTER_7_ID: return "IMAGE_ENDLESS_OUTER_7";
		case IMAGE_ENDLESS_SPARK_1_ID: return "IMAGE_ENDLESS_SPARK_1";
		case IMAGE_ENDLESS_SPARK_2_ID: return "IMAGE_ENDLESS_SPARK_2";
		case IMAGE_ENDLESS_SPARK_3_ID: return "IMAGE_ENDLESS_SPARK_3";
		case IMAGE_ENDLESS_GEM_HILITE_ID: return "IMAGE_ENDLESS_GEM_HILITE";
		case IMAGE_GALAXY_MAP_ID: return "IMAGE_GALAXY_MAP";
		case IMAGE_GALAXY_BUTTON_HILITE_ID: return "IMAGE_GALAXY_BUTTON_HILITE";
		case IMAGE_GALAXY_WARP_BUTTON_ID: return "IMAGE_GALAXY_WARP_BUTTON";
		case IMAGE_GALAXY_CLOSE_BUTTON_ID: return "IMAGE_GALAXY_CLOSE_BUTTON";
		case IMAGE_GALAXY_PLANET_ALPHA_ID: return "IMAGE_GALAXY_PLANET_ALPHA";
		case IMAGE_GALAXY_SUN_MOON_ALPHA_ID: return "IMAGE_GALAXY_SUN_MOON_ALPHA";
		case IMAGE_GALAXY_MOON_ALPHA_ID: return "IMAGE_GALAXY_MOON_ALPHA";
		case IMAGE_GALAXY_PLANET_SELECT_ID: return "IMAGE_GALAXY_PLANET_SELECT";
		case IMAGE_GALAXY_PLANET_COMPLETED_ID: return "IMAGE_GALAXY_PLANET_COMPLETED";
		case IMAGE_GALAXY_SUN_GLOW_ID: return "IMAGE_GALAXY_SUN_GLOW";
		case IMAGE_GALAXY_SUN_SWIRL_ID: return "IMAGE_GALAXY_SUN_SWIRL";
		case IMAGE_GALAXY_QUESTION_ID: return "IMAGE_GALAXY_QUESTION";
		case IMAGE_GALAXY_MOON_SELECT_ID: return "IMAGE_GALAXY_MOON_SELECT";
		case IMAGE_HS_BOTTOM_ID: return "IMAGE_HS_BOTTOM";
		case IMAGE_MAIN_GADGETS_ID: return "IMAGE_MAIN_GADGETS";
		case IMAGE_MAIN_BIG_SELECT_ID: return "IMAGE_MAIN_BIG_SELECT";
		case IMAGE_MAIN_BIG_OVER_ID: return "IMAGE_MAIN_BIG_OVER";
		case IMAGE_MAIN_SMALL_GLOW_ID: return "IMAGE_MAIN_SMALL_GLOW";
		case IMAGE_MAIN_PLAY_GLOW_ID: return "IMAGE_MAIN_PLAY_GLOW";
		case IMAGE_MAIN_BOTTOM_GLOW_ID: return "IMAGE_MAIN_BOTTOM_GLOW";
		case IMAGE_MAIN_CLASSIC_ID: return "IMAGE_MAIN_CLASSIC";
		case IMAGE_MAIN_ACTION_ID: return "IMAGE_MAIN_ACTION";
		case IMAGE_MAIN_PUZZLE_ID: return "IMAGE_MAIN_PUZZLE";
		case IMAGE_MAIN_ENDLESS_ID: return "IMAGE_MAIN_ENDLESS";
		case IMAGE_MAIN_TWILIGHT_ID: return "IMAGE_MAIN_TWILIGHT";
		case IMAGE_MAIN_HYPER_ID: return "IMAGE_MAIN_HYPER";
		case IMAGE_MAIN_COGNITO_ID: return "IMAGE_MAIN_COGNITO";
		case IMAGE_MAIN_FINITY_ID: return "IMAGE_MAIN_FINITY";
		case IMAGE_MAIN_OPTIONS_ID: return "IMAGE_MAIN_OPTIONS";
		case IMAGE_MAIN_SCORES_ID: return "IMAGE_MAIN_SCORES";
		case IMAGE_MAIN_PLAY_ID: return "IMAGE_MAIN_PLAY";
		case IMAGE_MAIN_QUIT_ID: return "IMAGE_MAIN_QUIT";
		case IMAGE_MAIN_CENTER_TEXT_ID: return "IMAGE_MAIN_CENTER_TEXT";
		case IMAGE_MAIN_LIGHT_BIG_ID: return "IMAGE_MAIN_LIGHT_BIG";
		case IMAGE_MAIN_LIGHT_MED_ID: return "IMAGE_MAIN_LIGHT_MED";
		case IMAGE_MAIN_LIGHT_SMALL_ID: return "IMAGE_MAIN_LIGHT_SMALL";
		case IMAGE_MAIN_CENTER_GLOW_ID: return "IMAGE_MAIN_CENTER_GLOW";
		case IMAGE_MAIN_SECRET_GLOW_ID: return "IMAGE_MAIN_SECRET_GLOW";
		case IMAGE_MAIN_SECRET_FRAME_ID: return "IMAGE_MAIN_SECRET_FRAME";
		case IMAGE_MAIN_SECRET_SYMBOL_ID: return "IMAGE_MAIN_SECRET_SYMBOL";
		case FONT_VAG_ROUNDED_11_ID: return "FONT_VAG_ROUNDED_11";
		case FONT_DIGIT_ID: return "FONT_DIGIT";
		case FONT_BOMB_ID: return "FONT_BOMB";
		case FONT_HUGE_ID: return "FONT_HUGE";
		case FONT_SCORE_ID: return "FONT_SCORE";
		case FONT_LEADERBOARD_ID: return "FONT_LEADERBOARD";
		case FONT_ENGSMALL_ID: return "FONT_ENGSMALL";
		case IMAGE_BACKDROP00_ID: return "IMAGE_BACKDROP00";
		case IMAGE_BACKDROP01_ID: return "IMAGE_BACKDROP01";
		case IMAGE_BACKDROP02_ID: return "IMAGE_BACKDROP02";
		case IMAGE_BACKDROP03_ID: return "IMAGE_BACKDROP03";
		case IMAGE_BACKDROP04_ID: return "IMAGE_BACKDROP04";
		case IMAGE_BACKDROP05_ID: return "IMAGE_BACKDROP05";
		case IMAGE_BACKDROP06_ID: return "IMAGE_BACKDROP06";
		case IMAGE_BACKDROP07_ID: return "IMAGE_BACKDROP07";
		case IMAGE_BACKDROP08_ID: return "IMAGE_BACKDROP08";
		case IMAGE_BACKDROP09_ID: return "IMAGE_BACKDROP09";
		case IMAGE_BACKDROP10_ID: return "IMAGE_BACKDROP10";
		case IMAGE_BACKDROP11_ID: return "IMAGE_BACKDROP11";
		case IMAGE_BACKDROP12_ID: return "IMAGE_BACKDROP12";
		case IMAGE_BACKDROP13_ID: return "IMAGE_BACKDROP13";
		case IMAGE_BACKDROP14_ID: return "IMAGE_BACKDROP14";
		case IMAGE_BACKDROP15_ID: return "IMAGE_BACKDROP15";
		case IMAGE_BACKDROP16_ID: return "IMAGE_BACKDROP16";
		case IMAGE_BACKDROP17_ID: return "IMAGE_BACKDROP17";
		case IMAGE_ZENDROP1_ID: return "IMAGE_ZENDROP1";
		case IMAGE_ZENDROP2_ID: return "IMAGE_ZENDROP2";
		case IMAGE_ZENDROP3_ID: return "IMAGE_ZENDROP3";
		case IMAGE_ZENDROP4_ID: return "IMAGE_ZENDROP4";
		case IMAGE_ZENDROP5_ID: return "IMAGE_ZENDROP5";
		case IMAGE_ZENDROP6_ID: return "IMAGE_ZENDROP6";
		case IMAGE_ZENDROP7_ID: return "IMAGE_ZENDROP7";
		case IMAGE_ZENDROP8_ID: return "IMAGE_ZENDROP8";
		case IMAGE_ZENDROP9_ID: return "IMAGE_ZENDROP9";
		case IMAGE_ZENDROP10_ID: return "IMAGE_ZENDROP10";
		case IMAGE_ZENDROP11_ID: return "IMAGE_ZENDROP11";
		case IMAGE_ZENDROP12_ID: return "IMAGE_ZENDROP12";
		case IMAGE_ZENDROP13_ID: return "IMAGE_ZENDROP13";
		case IMAGE_ZENDROP14_ID: return "IMAGE_ZENDROP14";
		case IMAGE_ZENDROP15_ID: return "IMAGE_ZENDROP15";
		case IMAGE_ZENDROP16_ID: return "IMAGE_ZENDROP16";
		case IMAGE_ZENDROP17_ID: return "IMAGE_ZENDROP17";
		case IMAGE_ZENDROP18_ID: return "IMAGE_ZENDROP18";
		case IMAGE_ZENDROP19_ID: return "IMAGE_ZENDROP19";
		case IMAGE_ZENDROP20_ID: return "IMAGE_ZENDROP20";
		case IMAGE_ZENDROP21_ID: return "IMAGE_ZENDROP21";
		case IMAGE_ZENDROP22_ID: return "IMAGE_ZENDROP22";
		case IMAGE_ZENDROP23_ID: return "IMAGE_ZENDROP23";
		case IMAGE_ZENDROP24_ID: return "IMAGE_ZENDROP24";
		case IMAGE_ZENDROP25_ID: return "IMAGE_ZENDROP25";
		case IMAGE_ZENDROP26_ID: return "IMAGE_ZENDROP26";
		case IMAGE_ZENDROP27_ID: return "IMAGE_ZENDROP27";
		case IMAGE_ZENDROP28_ID: return "IMAGE_ZENDROP28";
		case IMAGE_ZENDROP29_ID: return "IMAGE_ZENDROP29";
		case IMAGE_ZENDROP30_ID: return "IMAGE_ZENDROP30";
		case IMAGE_ZENDROP31_ID: return "IMAGE_ZENDROP31";
		case IMAGE_ZENDROP32_ID: return "IMAGE_ZENDROP32";
		case IMAGE_ZENDROP33_ID: return "IMAGE_ZENDROP33";
		case IMAGE_ZENDROP34_ID: return "IMAGE_ZENDROP34";
		case IMAGE_ZENDROP35_ID: return "IMAGE_ZENDROP35";
		case IMAGE_ZENDROP36_ID: return "IMAGE_ZENDROP36";
		case IMAGE_ZENDROP37_ID: return "IMAGE_ZENDROP37";
		case IMAGE_ZENDROP38_ID: return "IMAGE_ZENDROP38";
		case IMAGE_ZENDROP39_ID: return "IMAGE_ZENDROP39";
		case IMAGE_ZENDROP40_ID: return "IMAGE_ZENDROP40";
		case IMAGE_A_BUTTON_ID: return "IMAGE_A_BUTTON";
		case IMAGE_B_BUTTON_ID: return "IMAGE_B_BUTTON";
		case IMAGE_X_BUTTON_ID: return "IMAGE_X_BUTTON";
		case IMAGE_Y_BUTTON_ID: return "IMAGE_Y_BUTTON";
		case IMAGE_LB_BUTTON_ID: return "IMAGE_LB_BUTTON";
		case IMAGE_RB_BUTTON_ID: return "IMAGE_RB_BUTTON";
		case IMAGE_JOYSTICK_ID: return "IMAGE_JOYSTICK";
		case IMAGE_ACHIEVEMENT1_ID: return "IMAGE_ACHIEVEMENT1";
		case IMAGE_ACHIEVEMENT2_ID: return "IMAGE_ACHIEVEMENT2";
		case IMAGE_ACHIEVEMENT3_ID: return "IMAGE_ACHIEVEMENT3";
		case IMAGE_ACHIEVEMENT4_ID: return "IMAGE_ACHIEVEMENT4";
		case IMAGE_ACHIEVEMENT5_ID: return "IMAGE_ACHIEVEMENT5";
		case IMAGE_ACHIEVEMENT6_ID: return "IMAGE_ACHIEVEMENT6";
		case IMAGE_ACHIEVEMENT7_ID: return "IMAGE_ACHIEVEMENT7";
		case IMAGE_ACHIEVEMENT8_ID: return "IMAGE_ACHIEVEMENT8";
		case IMAGE_ACHIEVEMENT9_ID: return "IMAGE_ACHIEVEMENT9";
		case IMAGE_ACHIEVEMENT10_ID: return "IMAGE_ACHIEVEMENT10";
		case IMAGE_ACHIEVEMENT11_ID: return "IMAGE_ACHIEVEMENT11";
		case IMAGE_ACHIEVEMENT12_ID: return "IMAGE_ACHIEVEMENT12";
		case IMAGE_DPAD_LEFT_ID: return "IMAGE_DPAD_LEFT";
		case IMAGE_DPAD_RIGHT_ID: return "IMAGE_DPAD_RIGHT";
		case IMAGE_DPAD_UP_ID: return "IMAGE_DPAD_UP";
		case IMAGE_DPAD_DOWN_ID: return "IMAGE_DPAD_DOWN";
		case IMAGE_DPAD_UPDOWN_ID: return "IMAGE_DPAD_UPDOWN";
		case IMAGE_DPAD_LEFTRIGHT_ID: return "IMAGE_DPAD_LEFTRIGHT";
		case IMAGE_MENU_BUTTON_ID: return "IMAGE_MENU_BUTTON";
		case IMAGE_MENU_BUTTON_GLOW2_ID: return "IMAGE_MENU_BUTTON_GLOW2";
		case IMAGE_NEBULA1_ID: return "IMAGE_NEBULA1";
		case IMAGE_PUZZLE_PLANETS_ID: return "IMAGE_PUZZLE_PLANETS";
		case IMAGE_PUZZLE_MOONS_ID: return "IMAGE_PUZZLE_MOONS";
		case IMAGE_PUZZLE_MAP_ID: return "IMAGE_PUZZLE_MAP";
		default: return "";
	}
}

