#ifndef __Book5_H__
#define __Book5_H__

namespace Sexy
{
	class ResourceManager;
	class Image;
	class Font;

	Image* LoadImageById(ResourceManager *theManager, int theId);
	void ReplaceImageById(ResourceManager *theManager, int theId, Image *theImage);
	bool ExtractResourcesByName(ResourceManager *theManager, const char *theName);

	// BOOK5Common Resources
	bool ExtractBOOK5CommonResources(ResourceManager *theMgr);
	extern Image* IMAGE_B5_LEFT_FACING_ARROW;

	// Book5Chapter1 Resources
	bool ExtractBook5Chapter1Resources(ResourceManager *theMgr);
	extern Image* IMAGE_B5A_BG1;
	extern int SOUND_BOOK5_CH1_DONKEY_BRAY;
	extern int SOUND_BOOK5_CH1_DONKEY_IMPACT;
	extern int SOUND_BOOK5_CH1_FELINE_ENGAGE;
	extern int SOUND_BOOK5_CH1_FELINE_ROAR;
	extern int SOUND_BOOK5_CH1_PIG_ATTACK;
	extern int SOUND_BOOK5_CH1_PIG_SQUEAL2;
	extern int SOUND_BOOK5_CH1_SLICING_ATTACK2;
	extern int SOUND_BOOK5_CH1_SLICING_ATTACK;
	extern int SOUND_BOOK5_CH1_WET_IMPACT1;

	// Book5Chapter10 Resources
	bool ExtractBook5Chapter10Resources(ResourceManager *theMgr);
	extern Image* IMAGE_B5A_BG10;
	extern int SOUND_BOOK5_CH10_ARROW_SHOT;
	extern int SOUND_BOOK5_CH10_DOG_BARK1;
	extern int SOUND_BOOK5_CH10_FIRE_6;
	extern int SOUND_BOOK5_CH10_LIGHTNING_ATTACK;
	extern int SOUND_BOOK5_CH10_MALE_LOW_ANGER;
	extern int SOUND_BOOK5_CH10_MALE_LOW_PAIN;
	extern int SOUND_BOOK5_CH10_MALE_LOW_WARCRY;
	extern int SOUND_BOOK5_CH10_SMOKE_ATTACK2;
	extern int SOUND_BOOK5_CH10_SONIC_ATTACK;
	extern int SOUND_BOOK5_CH10_STRING_ATTACK2;
	extern int SOUND_BOOK5_CH10_STRING_ATTACK;
	extern int SOUND_BOOK5_CH10_SWORD_IMPACT2;
	extern int SOUND_BOOK5_CH10_SWORD_IMPACT3;
	extern int SOUND_BOOK5_CH10_SWORD_IMPACT;

	// Book5Chapter2 Resources
	bool ExtractBook5Chapter2Resources(ResourceManager *theMgr);
	extern Image* IMAGE_B5A_BG2;
	extern int SOUND_BOOK5_CH2_DOPEY_ATTACK;
	extern int SOUND_BOOK5_CH2_DOPEY_IMPACT;
	extern int SOUND_BOOK5_CH2_MALE_ANGER;
	extern int SOUND_BOOK5_CH2_MALE_GRUNT1;
	extern int SOUND_BOOK5_CH2_MALE_GRUNT2;
	extern int SOUND_BOOK5_CH2_MALE_LAUGH2;
	extern int SOUND_BOOK5_CH2_MALE_LAUGH;
	extern int SOUND_BOOK5_CH2_MALE_LOW_ANGER;
	extern int SOUND_BOOK5_CH2_MALE_LOW_PAIN;
	extern int SOUND_BOOK5_CH2_MALE_LOW_WARCRY;
	extern int SOUND_BOOK5_CH2_MALE_PAIN;
	extern int SOUND_BOOK5_CH2_SONIC_ATTACK;

	// Book5Chapter3 Resources
	bool ExtractBook5Chapter3Resources(ResourceManager *theMgr);
	extern Image* IMAGE_B5A_BG3;
	extern int SOUND_BOOK5_CH3_BEAR_ATTACK;
	extern int SOUND_BOOK5_CH3_BEAR_IMPACT;
	extern int SOUND_BOOK5_CH3_BEAR_ROAR;
	extern int SOUND_BOOK5_CH3_CS_BEATDOWN;
	extern int SOUND_BOOK5_CH3_MALE_ANGER;
	extern int SOUND_BOOK5_CH3_MALE_GRUNT1;
	extern int SOUND_BOOK5_CH3_MALE_GRUNT2;
	extern int SOUND_BOOK5_CH3_MALE_LAUGH2;
	extern int SOUND_BOOK5_CH3_MALE_LAUGH;
	extern int SOUND_BOOK5_CH3_MALE_LOW_WARCRY;
	extern int SOUND_BOOK5_CH3_MALE_PAIN;
	extern int SOUND_BOOK5_CH3_MISC_IMPACT2;
	extern int SOUND_BOOK5_CH3_MISC_IMPACT;
	extern int SOUND_BOOK5_CH3_SWORD_IMPACT3;

	// Book5Chapter4 Resources
	bool ExtractBook5Chapter4Resources(ResourceManager *theMgr);
	extern Image* IMAGE_B5A_BG4;
	extern int SOUND_BOOK5_CH4_CHICKEN_ATTACK1;
	extern int SOUND_BOOK5_CH4_DOG_BARK1;
	extern int SOUND_BOOK5_CH4_DOG_BARK2;
	extern int SOUND_BOOK5_CH4_DOG_WHIMPER;
	extern int SOUND_BOOK5_CH4_GENERIC_ANIMAL;
	extern int SOUND_BOOK5_CH4_MISC_IMPACT2;
	extern int SOUND_BOOK5_CH4_MISC_IMPACT;
	extern int SOUND_BOOK5_CH4_SHEEP_BLEAT;
	extern int SOUND_BOOK5_CH4_SNAKE_HISS;
	extern int SOUND_BOOK5_CH4_WET_IMPACT1;
	extern int SOUND_BOOK5_CH4_WOLF_HOWL;

	// Book5Chapter5 Resources
	bool ExtractBook5Chapter5Resources(ResourceManager *theMgr);
	extern Image* IMAGE_B5A_BG5;
	extern int SOUND_BOOK5_CH5_CS_SHACKLE;
	extern int SOUND_BOOK5_CH5_FEMALE_OOOH;
	extern int SOUND_BOOK5_CH5_GHOST_WAIL1;
	extern int SOUND_BOOK5_CH5_GHOST_WAIL2;
	extern int SOUND_BOOK5_CH5_GHOST_WAIL3;
	extern int SOUND_BOOK5_CH5_MALE_LOW_ANGER;
	extern int SOUND_BOOK5_CH5_MALE_LOW_PAIN;
	extern int SOUND_BOOK5_CH5_MALE_LOW_WARCRY;
	extern int SOUND_BOOK5_CH5_SLICING_ATTACK2;
	extern int SOUND_BOOK5_CH5_SMOKE_ATTACK2;
	extern int SOUND_BOOK5_CH5_SMOKE_ATTACK;
	extern int SOUND_BOOK5_CH5_SMOKE_IMPACT;
	extern int SOUND_BOOK5_CH5_SONIC_ATTACK;
	extern int SOUND_BOOK5_CH5_SWORD_IMPACT2;
	extern int SOUND_BOOK5_CH5_SWORD_IMPACT3;
	extern int SOUND_BOOK5_CH5_WAIL2;
	extern int SOUND_BOOK5_CH5_WAIL;

	// Book5Chapter6 Resources
	bool ExtractBook5Chapter6Resources(ResourceManager *theMgr);
	extern Image* IMAGE_B5A_BG6;
	extern int SOUND_BOOK5_CH6_BEAR_ROAR;
	extern int SOUND_BOOK5_CH6_DRAGON_BITE;
	extern int SOUND_BOOK5_CH6_DRAGON_DEATH;
	extern int SOUND_BOOK5_CH6_DRAGON_PAIN;
	extern int SOUND_BOOK5_CH6_DRAGON_ROAR;
	extern int SOUND_BOOK5_CH6_MISC_IMPACT2;
	extern int SOUND_BOOK5_CH6_MISC_IMPACT;
	extern int SOUND_BOOK5_CH6_SLUMP_SMALL;
	extern int SOUND_BOOK5_CH6_SONIC_ATTACK;
	extern int SOUND_BOOK5_CH6_SWORD_IMPACT3;
	extern int SOUND_BOOK5_CH6_WET_IMPACT1;
	extern int SOUND_BOOK5_CH6_WET_IMPACT2;

	// Book5Chapter7 Resources
	bool ExtractBook5Chapter7Resources(ResourceManager *theMgr);
	extern Image* IMAGE_B5A_BG7;
	extern Image* IMAGE_B5A_MONKEYKING_BOSS_BATTLE;
	extern int SOUND_BOOK5_CH7_CS_LIGHT;
	extern int SOUND_BOOK5_CH7_CS_STINGER;
	extern int SOUND_BOOK5_CH7_FIRE_1;
	extern int SOUND_BOOK5_CH7_FIRE_3;
	extern int SOUND_BOOK5_CH7_FIRE_6;
	extern int SOUND_BOOK5_CH7_MALE_LAUGH;
	extern int SOUND_BOOK5_CH7_MONKEY_ATTACK2;
	extern int SOUND_BOOK5_CH7_MONKEY_ATTACK;
	extern int SOUND_BOOK5_CH7_MONKEY_CHALLENGE;
	extern int SOUND_BOOK5_CH7_PULSING_ATTACK;
	extern int SOUND_BOOK5_CH7_SLICING_ATTACK2;
	extern int SOUND_BOOK5_CH7_SMOKE_ATTACK2;
	extern int SOUND_BOOK5_CH7_SMOKE_ATTACK;
	extern int SOUND_BOOK5_CH7_SMOKE_IMPACT;
	extern int SOUND_BOOK5_CH7_SONIC_ATTACK;
	extern int SOUND_BOOK5_CH7_SPARKLE_ATTACK;

	// Book5Chapter8 Resources
	bool ExtractBook5Chapter8Resources(ResourceManager *theMgr);
	extern Image* IMAGE_B5A_BG8;
	extern int SOUND_BOOK5_CH8_FIRE_3;
	extern int SOUND_BOOK5_CH8_FIRE_6;
	extern int SOUND_BOOK5_CH8_GHOST_WAIL1;
	extern int SOUND_BOOK5_CH8_LIGHTNING_ATTACK;
	extern int SOUND_BOOK5_CH8_MONSTER_ATTACK;
	extern int SOUND_BOOK5_CH8_MONSTER_CHALLENGE;
	extern int SOUND_BOOK5_CH8_MONSTER_IMPACT;
	extern int SOUND_BOOK5_CH8_SKELETON_WARCRY;
	extern int SOUND_BOOK5_CH8_SMOKE_ATTACK2;
	extern int SOUND_BOOK5_CH8_SQ_MAM_ATTACK;
	extern int SOUND_BOOK5_CH8_SQ_MAM_DEATH;
	extern int SOUND_BOOK5_CH8_STRING_ATTACK2;
	extern int SOUND_BOOK5_CH8_STRING_ATTACK;
	extern int SOUND_BOOK5_CH8_STRING_DEATH;
	extern int SOUND_BOOK5_CH8_STRING_IMPACT;

	// Book5Chapter9 Resources
	bool ExtractBook5Chapter9Resources(ResourceManager *theMgr);
	extern Image* IMAGE_B5A_BG9;
	extern int SOUND_BOOK5_CH9_SMOKE_ATTACK2;
	extern int SOUND_BOOK5_CH9_SMOKE_ATTACK;
	extern int SOUND_BOOK5_CH9_SMOKE_IMPACT;
	extern int SOUND_BOOK5_CH9_SONIC_ATTACK;
	extern int SOUND_BOOK5_CH9_SPARKLE_ATTACK;
	extern int SOUND_BOOK5_CH9_SWORD_IMPACT2;
	extern int SOUND_BOOK5_CH9_SWORD_IMPACT3;
	extern int SOUND_BOOK5_CH9_SWORD_IMPACT;

	// Book5Init Resources
	bool ExtractBook5InitResources(ResourceManager *theMgr);
	extern Image* IMAGE_B5_ICONANIM10;
	extern Image* IMAGE_B5_ICONANIM1;
	extern Image* IMAGE_B5_ICONANIM2;
	extern Image* IMAGE_B5_ICONANIM3;
	extern Image* IMAGE_B5_ICONANIM4;
	extern Image* IMAGE_B5_ICONANIM5;
	extern Image* IMAGE_B5_ICONANIM6;
	extern Image* IMAGE_B5_ICONANIM7;
	extern Image* IMAGE_B5_ICONANIM8;
	extern Image* IMAGE_B5_ICONANIM9;
	extern Image* IMAGE_B5_ICONMASK10;
	extern Image* IMAGE_B5_ICONMASK1;
	extern Image* IMAGE_B5_ICONMASK2;
	extern Image* IMAGE_B5_ICONMASK3;
	extern Image* IMAGE_B5_ICONMASK4;
	extern Image* IMAGE_B5_ICONMASK5;
	extern Image* IMAGE_B5_ICONMASK6;
	extern Image* IMAGE_B5_ICONMASK7;
	extern Image* IMAGE_B5_ICONMASK8;
	extern Image* IMAGE_B5_ICONMASK9;
	extern Image* IMAGE_B5_MAP;
	extern Image* IMAGE_B5_MAPSCREEN_BANNER;
	extern Image* IMAGE_B5_MINIMAP_ICONS;
	extern Image* IMAGE_TUT_PIC_DRAGON;
	extern Image* IMAGE_TUT_PIC_JADE_EMP;
	extern Image* IMAGE_TUT_PIC_JADE_EMP_R;
	extern Image* IMAGE_TUT_PIC_PIGGY;
	extern Image* IMAGE_TUT_PIC_PRIDEFUL;
	extern Image* IMAGE_TUT_PIC_SIFU;
	extern Image* IMAGE_TUT_PIC_TIGER;

	enum ResourceId
	{
		IMAGE_B5_MINIMAP_ICONS_ID,
		IMAGE_B5_MAPSCREEN_BANNER_ID,
		IMAGE_B5_ICONANIM1_ID,
		IMAGE_B5_ICONANIM2_ID,
		IMAGE_B5_ICONANIM3_ID,
		IMAGE_B5_ICONANIM4_ID,
		IMAGE_B5_ICONANIM5_ID,
		IMAGE_B5_ICONANIM6_ID,
		IMAGE_B5_ICONANIM7_ID,
		IMAGE_B5_ICONANIM8_ID,
		IMAGE_B5_ICONANIM9_ID,
		IMAGE_B5_ICONANIM10_ID,
		IMAGE_B5_ICONMASK1_ID,
		IMAGE_B5_ICONMASK2_ID,
		IMAGE_B5_ICONMASK3_ID,
		IMAGE_B5_ICONMASK4_ID,
		IMAGE_B5_ICONMASK5_ID,
		IMAGE_B5_ICONMASK6_ID,
		IMAGE_B5_ICONMASK7_ID,
		IMAGE_B5_ICONMASK8_ID,
		IMAGE_B5_ICONMASK9_ID,
		IMAGE_B5_ICONMASK10_ID,
		IMAGE_B5_MAP_ID,
		IMAGE_TUT_PIC_PIGGY_ID,
		IMAGE_TUT_PIC_TIGER_ID,
		IMAGE_TUT_PIC_PRIDEFUL_ID,
		IMAGE_TUT_PIC_SIFU_ID,
		IMAGE_TUT_PIC_DRAGON_ID,
		IMAGE_TUT_PIC_JADE_EMP_ID,
		IMAGE_TUT_PIC_JADE_EMP_R_ID,
		IMAGE_B5_LEFT_FACING_ARROW_ID,
		IMAGE_B5A_BG1_ID,
		SOUND_BOOK5_CH1_FELINE_ENGAGE_ID,
		SOUND_BOOK5_CH1_FELINE_ROAR_ID,
		SOUND_BOOK5_CH1_PIG_SQUEAL2_ID,
		SOUND_BOOK5_CH1_PIG_ATTACK_ID,
		SOUND_BOOK5_CH1_DONKEY_BRAY_ID,
		SOUND_BOOK5_CH1_DONKEY_IMPACT_ID,
		SOUND_BOOK5_CH1_SLICING_ATTACK_ID,
		SOUND_BOOK5_CH1_SLICING_ATTACK2_ID,
		SOUND_BOOK5_CH1_WET_IMPACT1_ID,
		IMAGE_B5A_BG2_ID,
		SOUND_BOOK5_CH2_DOPEY_ATTACK_ID,
		SOUND_BOOK5_CH2_DOPEY_IMPACT_ID,
		SOUND_BOOK5_CH2_MALE_GRUNT1_ID,
		SOUND_BOOK5_CH2_MALE_GRUNT2_ID,
		SOUND_BOOK5_CH2_MALE_ANGER_ID,
		SOUND_BOOK5_CH2_MALE_LAUGH_ID,
		SOUND_BOOK5_CH2_MALE_LAUGH2_ID,
		SOUND_BOOK5_CH2_MALE_LOW_ANGER_ID,
		SOUND_BOOK5_CH2_MALE_LOW_PAIN_ID,
		SOUND_BOOK5_CH2_MALE_LOW_WARCRY_ID,
		SOUND_BOOK5_CH2_MALE_PAIN_ID,
		SOUND_BOOK5_CH2_SONIC_ATTACK_ID,
		IMAGE_B5A_BG3_ID,
		SOUND_BOOK5_CH3_MALE_GRUNT1_ID,
		SOUND_BOOK5_CH3_MALE_GRUNT2_ID,
		SOUND_BOOK5_CH3_MALE_ANGER_ID,
		SOUND_BOOK5_CH3_MALE_LAUGH_ID,
		SOUND_BOOK5_CH3_MALE_LAUGH2_ID,
		SOUND_BOOK5_CH3_MALE_LOW_WARCRY_ID,
		SOUND_BOOK5_CH3_MALE_PAIN_ID,
		SOUND_BOOK5_CH3_SWORD_IMPACT3_ID,
		SOUND_BOOK5_CH3_MISC_IMPACT_ID,
		SOUND_BOOK5_CH3_MISC_IMPACT2_ID,
		SOUND_BOOK5_CH3_BEAR_ATTACK_ID,
		SOUND_BOOK5_CH3_BEAR_IMPACT_ID,
		SOUND_BOOK5_CH3_BEAR_ROAR_ID,
		SOUND_BOOK5_CH3_CS_BEATDOWN_ID,
		IMAGE_B5A_BG4_ID,
		SOUND_BOOK5_CH4_SNAKE_HISS_ID,
		SOUND_BOOK5_CH4_SHEEP_BLEAT_ID,
		SOUND_BOOK5_CH4_CHICKEN_ATTACK1_ID,
		SOUND_BOOK5_CH4_DOG_BARK1_ID,
		SOUND_BOOK5_CH4_DOG_BARK2_ID,
		SOUND_BOOK5_CH4_DOG_WHIMPER_ID,
		SOUND_BOOK5_CH4_MISC_IMPACT_ID,
		SOUND_BOOK5_CH4_MISC_IMPACT2_ID,
		SOUND_BOOK5_CH4_WET_IMPACT1_ID,
		SOUND_BOOK5_CH4_GENERIC_ANIMAL_ID,
		SOUND_BOOK5_CH4_WOLF_HOWL_ID,
		IMAGE_B5A_BG5_ID,
		SOUND_BOOK5_CH5_GHOST_WAIL1_ID,
		SOUND_BOOK5_CH5_GHOST_WAIL2_ID,
		SOUND_BOOK5_CH5_GHOST_WAIL3_ID,
		SOUND_BOOK5_CH5_SWORD_IMPACT2_ID,
		SOUND_BOOK5_CH5_WAIL_ID,
		SOUND_BOOK5_CH5_WAIL2_ID,
		SOUND_BOOK5_CH5_SMOKE_ATTACK_ID,
		SOUND_BOOK5_CH5_SMOKE_ATTACK2_ID,
		SOUND_BOOK5_CH5_SMOKE_IMPACT_ID,
		SOUND_BOOK5_CH5_SONIC_ATTACK_ID,
		SOUND_BOOK5_CH5_MALE_LOW_ANGER_ID,
		SOUND_BOOK5_CH5_MALE_LOW_PAIN_ID,
		SOUND_BOOK5_CH5_MALE_LOW_WARCRY_ID,
		SOUND_BOOK5_CH5_SWORD_IMPACT3_ID,
		SOUND_BOOK5_CH5_SLICING_ATTACK2_ID,
		SOUND_BOOK5_CH5_FEMALE_OOOH_ID,
		SOUND_BOOK5_CH5_CS_SHACKLE_ID,
		IMAGE_B5A_BG6_ID,
		SOUND_BOOK5_CH6_DRAGON_BITE_ID,
		SOUND_BOOK5_CH6_DRAGON_DEATH_ID,
		SOUND_BOOK5_CH6_DRAGON_PAIN_ID,
		SOUND_BOOK5_CH6_DRAGON_ROAR_ID,
		SOUND_BOOK5_CH6_WET_IMPACT1_ID,
		SOUND_BOOK5_CH6_WET_IMPACT2_ID,
		SOUND_BOOK5_CH6_MISC_IMPACT_ID,
		SOUND_BOOK5_CH6_MISC_IMPACT2_ID,
		SOUND_BOOK5_CH6_SLUMP_SMALL_ID,
		SOUND_BOOK5_CH6_SWORD_IMPACT3_ID,
		SOUND_BOOK5_CH6_SONIC_ATTACK_ID,
		SOUND_BOOK5_CH6_BEAR_ROAR_ID,
		IMAGE_B5A_BG7_ID,
		IMAGE_B5A_MONKEYKING_BOSS_BATTLE_ID,
		SOUND_BOOK5_CH7_SONIC_ATTACK_ID,
		SOUND_BOOK5_CH7_SPARKLE_ATTACK_ID,
		SOUND_BOOK5_CH7_SMOKE_ATTACK_ID,
		SOUND_BOOK5_CH7_SMOKE_ATTACK2_ID,
		SOUND_BOOK5_CH7_SMOKE_IMPACT_ID,
		SOUND_BOOK5_CH7_PULSING_ATTACK_ID,
		SOUND_BOOK5_CH7_FIRE_1_ID,
		SOUND_BOOK5_CH7_FIRE_3_ID,
		SOUND_BOOK5_CH7_FIRE_6_ID,
		SOUND_BOOK5_CH7_MONKEY_ATTACK_ID,
		SOUND_BOOK5_CH7_MONKEY_ATTACK2_ID,
		SOUND_BOOK5_CH7_MONKEY_CHALLENGE_ID,
		SOUND_BOOK5_CH7_SLICING_ATTACK2_ID,
		SOUND_BOOK5_CH7_MALE_LAUGH_ID,
		SOUND_BOOK5_CH7_CS_STINGER_ID,
		SOUND_BOOK5_CH7_CS_LIGHT_ID,
		IMAGE_B5A_BG8_ID,
		SOUND_BOOK5_CH8_MONSTER_ATTACK_ID,
		SOUND_BOOK5_CH8_MONSTER_CHALLENGE_ID,
		SOUND_BOOK5_CH8_MONSTER_IMPACT_ID,
		SOUND_BOOK5_CH8_STRING_ATTACK_ID,
		SOUND_BOOK5_CH8_STRING_ATTACK2_ID,
		SOUND_BOOK5_CH8_STRING_DEATH_ID,
		SOUND_BOOK5_CH8_STRING_IMPACT_ID,
		SOUND_BOOK5_CH8_SQ_MAM_ATTACK_ID,
		SOUND_BOOK5_CH8_SKELETON_WARCRY_ID,
		SOUND_BOOK5_CH8_SQ_MAM_DEATH_ID,
		SOUND_BOOK5_CH8_FIRE_3_ID,
		SOUND_BOOK5_CH8_FIRE_6_ID,
		SOUND_BOOK5_CH8_GHOST_WAIL1_ID,
		SOUND_BOOK5_CH8_LIGHTNING_ATTACK_ID,
		SOUND_BOOK5_CH8_SMOKE_ATTACK2_ID,
		IMAGE_B5A_BG9_ID,
		SOUND_BOOK5_CH9_SMOKE_ATTACK_ID,
		SOUND_BOOK5_CH9_SMOKE_ATTACK2_ID,
		SOUND_BOOK5_CH9_SMOKE_IMPACT_ID,
		SOUND_BOOK5_CH9_SPARKLE_ATTACK_ID,
		SOUND_BOOK5_CH9_SWORD_IMPACT_ID,
		SOUND_BOOK5_CH9_SWORD_IMPACT2_ID,
		SOUND_BOOK5_CH9_SWORD_IMPACT3_ID,
		SOUND_BOOK5_CH9_SONIC_ATTACK_ID,
		IMAGE_B5A_BG10_ID,
		SOUND_BOOK5_CH10_STRING_ATTACK_ID,
		SOUND_BOOK5_CH10_MALE_LOW_ANGER_ID,
		SOUND_BOOK5_CH10_MALE_LOW_PAIN_ID,
		SOUND_BOOK5_CH10_MALE_LOW_WARCRY_ID,
		SOUND_BOOK5_CH10_SWORD_IMPACT_ID,
		SOUND_BOOK5_CH10_SWORD_IMPACT2_ID,
		SOUND_BOOK5_CH10_SWORD_IMPACT3_ID,
		SOUND_BOOK5_CH10_ARROW_SHOT_ID,
		SOUND_BOOK5_CH10_SONIC_ATTACK_ID,
		SOUND_BOOK5_CH10_STRING_ATTACK2_ID,
		SOUND_BOOK5_CH10_FIRE_6_ID,
		SOUND_BOOK5_CH10_DOG_BARK1_ID,
		SOUND_BOOK5_CH10_LIGHTNING_ATTACK_ID,
		SOUND_BOOK5_CH10_SMOKE_ATTACK2_ID,
		RESOURCE_ID_MAX
	};

	Image* GetImageById(int theId);
	Font* GetFontById(int theId);
	int GetSoundById(int theId);

	Image*& GetImageRefById(int theId);
	Font*& GetFontRefById(int theId);
	int& GetSoundRefById(int theId);

	ResourceId GetIdByImage(Image *theImage);
	ResourceId GetIdByFont(Font *theFont);
	ResourceId GetIdBySound(int theSound);
	const char* GetStringIdById(int theId);
	ResourceId GetIdByStringId(const char *theStringId);

} // namespace Sexy


#endif
