#include "Book5.h"
#include "SexyAppFramework/ResourceManager.h"

using namespace Sexy;

#pragma warning(disable:4311 4312)

static bool gNeedRecalcVariableToIdMap = false;

bool Sexy::ExtractResourcesByName(ResourceManager *theManager, const char *theName)
{
	if (strcmp(theName,"BOOK5Common")==0) return ExtractBOOK5CommonResources(theManager);
	if (strcmp(theName,"Book5Chapter1")==0) return ExtractBook5Chapter1Resources(theManager);
	if (strcmp(theName,"Book5Chapter10")==0) return ExtractBook5Chapter10Resources(theManager);
	if (strcmp(theName,"Book5Chapter2")==0) return ExtractBook5Chapter2Resources(theManager);
	if (strcmp(theName,"Book5Chapter3")==0) return ExtractBook5Chapter3Resources(theManager);
	if (strcmp(theName,"Book5Chapter4")==0) return ExtractBook5Chapter4Resources(theManager);
	if (strcmp(theName,"Book5Chapter5")==0) return ExtractBook5Chapter5Resources(theManager);
	if (strcmp(theName,"Book5Chapter6")==0) return ExtractBook5Chapter6Resources(theManager);
	if (strcmp(theName,"Book5Chapter7")==0) return ExtractBook5Chapter7Resources(theManager);
	if (strcmp(theName,"Book5Chapter8")==0) return ExtractBook5Chapter8Resources(theManager);
	if (strcmp(theName,"Book5Chapter9")==0) return ExtractBook5Chapter9Resources(theManager);
	if (strcmp(theName,"Book5Init")==0) return ExtractBook5InitResources(theManager);
	return false;
}

Sexy::ResourceId Sexy::GetIdByStringId(const char *theStringId)
{
	typedef std::map<std::string,int> MyMap;
	static MyMap aMap;
	if(aMap.empty())
	{
		for(int i=0; i<RESOURCE_ID_MAX; i++)
			aMap[GetStringIdById(i)] = i;
	}

	MyMap::iterator anItr = aMap.find(theStringId);
	if (anItr == aMap.end())
		return RESOURCE_ID_MAX;
	else
		return (ResourceId) anItr->second;
}

// BOOK5Common Resources
Image* Sexy::IMAGE_B5_LEFT_FACING_ARROW;

bool Sexy::ExtractBOOK5CommonResources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_B5_LEFT_FACING_ARROW = aMgr.GetImageThrow("IMAGE_B5_LEFT_FACING_ARROW");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// Book5Chapter1 Resources
Image* Sexy::IMAGE_B5A_BG1;
int Sexy::SOUND_BOOK5_CH1_DONKEY_BRAY;
int Sexy::SOUND_BOOK5_CH1_DONKEY_IMPACT;
int Sexy::SOUND_BOOK5_CH1_FELINE_ENGAGE;
int Sexy::SOUND_BOOK5_CH1_FELINE_ROAR;
int Sexy::SOUND_BOOK5_CH1_PIG_ATTACK;
int Sexy::SOUND_BOOK5_CH1_PIG_SQUEAL2;
int Sexy::SOUND_BOOK5_CH1_SLICING_ATTACK;
int Sexy::SOUND_BOOK5_CH1_SLICING_ATTACK2;
int Sexy::SOUND_BOOK5_CH1_WET_IMPACT1;

bool Sexy::ExtractBook5Chapter1Resources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_B5A_BG1 = aMgr.GetImageThrow("IMAGE_B5A_BG1");
		SOUND_BOOK5_CH1_DONKEY_BRAY = aMgr.GetSoundThrow("SOUND_BOOK5_CH1_DONKEY_BRAY");
		SOUND_BOOK5_CH1_DONKEY_IMPACT = aMgr.GetSoundThrow("SOUND_BOOK5_CH1_DONKEY_IMPACT");
		SOUND_BOOK5_CH1_FELINE_ENGAGE = aMgr.GetSoundThrow("SOUND_BOOK5_CH1_FELINE_ENGAGE");
		SOUND_BOOK5_CH1_FELINE_ROAR = aMgr.GetSoundThrow("SOUND_BOOK5_CH1_FELINE_ROAR");
		SOUND_BOOK5_CH1_PIG_ATTACK = aMgr.GetSoundThrow("SOUND_BOOK5_CH1_PIG_ATTACK");
		SOUND_BOOK5_CH1_PIG_SQUEAL2 = aMgr.GetSoundThrow("SOUND_BOOK5_CH1_PIG_SQUEAL2");
		SOUND_BOOK5_CH1_SLICING_ATTACK = aMgr.GetSoundThrow("SOUND_BOOK5_CH1_SLICING_ATTACK");
		SOUND_BOOK5_CH1_SLICING_ATTACK2 = aMgr.GetSoundThrow("SOUND_BOOK5_CH1_SLICING_ATTACK2");
		SOUND_BOOK5_CH1_WET_IMPACT1 = aMgr.GetSoundThrow("SOUND_BOOK5_CH1_WET_IMPACT1");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// Book5Chapter10 Resources
Image* Sexy::IMAGE_B5A_BG10;
int Sexy::SOUND_BOOK5_CH10_ARROW_SHOT;
int Sexy::SOUND_BOOK5_CH10_DOG_BARK1;
int Sexy::SOUND_BOOK5_CH10_FIRE_6;
int Sexy::SOUND_BOOK5_CH10_LIGHTNING_ATTACK;
int Sexy::SOUND_BOOK5_CH10_MALE_LOW_ANGER;
int Sexy::SOUND_BOOK5_CH10_MALE_LOW_PAIN;
int Sexy::SOUND_BOOK5_CH10_MALE_LOW_WARCRY;
int Sexy::SOUND_BOOK5_CH10_SMOKE_ATTACK2;
int Sexy::SOUND_BOOK5_CH10_SONIC_ATTACK;
int Sexy::SOUND_BOOK5_CH10_STRING_ATTACK;
int Sexy::SOUND_BOOK5_CH10_STRING_ATTACK2;
int Sexy::SOUND_BOOK5_CH10_SWORD_IMPACT;
int Sexy::SOUND_BOOK5_CH10_SWORD_IMPACT2;
int Sexy::SOUND_BOOK5_CH10_SWORD_IMPACT3;

bool Sexy::ExtractBook5Chapter10Resources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_B5A_BG10 = aMgr.GetImageThrow("IMAGE_B5A_BG10");
		SOUND_BOOK5_CH10_ARROW_SHOT = aMgr.GetSoundThrow("SOUND_BOOK5_CH10_ARROW_SHOT");
		SOUND_BOOK5_CH10_DOG_BARK1 = aMgr.GetSoundThrow("SOUND_BOOK5_CH10_DOG_BARK1");
		SOUND_BOOK5_CH10_FIRE_6 = aMgr.GetSoundThrow("SOUND_BOOK5_CH10_FIRE_6");
		SOUND_BOOK5_CH10_LIGHTNING_ATTACK = aMgr.GetSoundThrow("SOUND_BOOK5_CH10_LIGHTNING_ATTACK");
		SOUND_BOOK5_CH10_MALE_LOW_ANGER = aMgr.GetSoundThrow("SOUND_BOOK5_CH10_MALE_LOW_ANGER");
		SOUND_BOOK5_CH10_MALE_LOW_PAIN = aMgr.GetSoundThrow("SOUND_BOOK5_CH10_MALE_LOW_PAIN");
		SOUND_BOOK5_CH10_MALE_LOW_WARCRY = aMgr.GetSoundThrow("SOUND_BOOK5_CH10_MALE_LOW_WARCRY");
		SOUND_BOOK5_CH10_SMOKE_ATTACK2 = aMgr.GetSoundThrow("SOUND_BOOK5_CH10_SMOKE_ATTACK2");
		SOUND_BOOK5_CH10_SONIC_ATTACK = aMgr.GetSoundThrow("SOUND_BOOK5_CH10_SONIC_ATTACK");
		SOUND_BOOK5_CH10_STRING_ATTACK = aMgr.GetSoundThrow("SOUND_BOOK5_CH10_STRING_ATTACK");
		SOUND_BOOK5_CH10_STRING_ATTACK2 = aMgr.GetSoundThrow("SOUND_BOOK5_CH10_STRING_ATTACK2");
		SOUND_BOOK5_CH10_SWORD_IMPACT = aMgr.GetSoundThrow("SOUND_BOOK5_CH10_SWORD_IMPACT");
		SOUND_BOOK5_CH10_SWORD_IMPACT2 = aMgr.GetSoundThrow("SOUND_BOOK5_CH10_SWORD_IMPACT2");
		SOUND_BOOK5_CH10_SWORD_IMPACT3 = aMgr.GetSoundThrow("SOUND_BOOK5_CH10_SWORD_IMPACT3");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// Book5Chapter2 Resources
Image* Sexy::IMAGE_B5A_BG2;
int Sexy::SOUND_BOOK5_CH2_DOPEY_ATTACK;
int Sexy::SOUND_BOOK5_CH2_DOPEY_IMPACT;
int Sexy::SOUND_BOOK5_CH2_MALE_ANGER;
int Sexy::SOUND_BOOK5_CH2_MALE_GRUNT1;
int Sexy::SOUND_BOOK5_CH2_MALE_GRUNT2;
int Sexy::SOUND_BOOK5_CH2_MALE_LAUGH;
int Sexy::SOUND_BOOK5_CH2_MALE_LAUGH2;
int Sexy::SOUND_BOOK5_CH2_MALE_LOW_ANGER;
int Sexy::SOUND_BOOK5_CH2_MALE_LOW_PAIN;
int Sexy::SOUND_BOOK5_CH2_MALE_LOW_WARCRY;
int Sexy::SOUND_BOOK5_CH2_MALE_PAIN;
int Sexy::SOUND_BOOK5_CH2_SONIC_ATTACK;

bool Sexy::ExtractBook5Chapter2Resources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_B5A_BG2 = aMgr.GetImageThrow("IMAGE_B5A_BG2");
		SOUND_BOOK5_CH2_DOPEY_ATTACK = aMgr.GetSoundThrow("SOUND_BOOK5_CH2_DOPEY_ATTACK");
		SOUND_BOOK5_CH2_DOPEY_IMPACT = aMgr.GetSoundThrow("SOUND_BOOK5_CH2_DOPEY_IMPACT");
		SOUND_BOOK5_CH2_MALE_ANGER = aMgr.GetSoundThrow("SOUND_BOOK5_CH2_MALE_ANGER");
		SOUND_BOOK5_CH2_MALE_GRUNT1 = aMgr.GetSoundThrow("SOUND_BOOK5_CH2_MALE_GRUNT1");
		SOUND_BOOK5_CH2_MALE_GRUNT2 = aMgr.GetSoundThrow("SOUND_BOOK5_CH2_MALE_GRUNT2");
		SOUND_BOOK5_CH2_MALE_LAUGH = aMgr.GetSoundThrow("SOUND_BOOK5_CH2_MALE_LAUGH");
		SOUND_BOOK5_CH2_MALE_LAUGH2 = aMgr.GetSoundThrow("SOUND_BOOK5_CH2_MALE_LAUGH2");
		SOUND_BOOK5_CH2_MALE_LOW_ANGER = aMgr.GetSoundThrow("SOUND_BOOK5_CH2_MALE_LOW_ANGER");
		SOUND_BOOK5_CH2_MALE_LOW_PAIN = aMgr.GetSoundThrow("SOUND_BOOK5_CH2_MALE_LOW_PAIN");
		SOUND_BOOK5_CH2_MALE_LOW_WARCRY = aMgr.GetSoundThrow("SOUND_BOOK5_CH2_MALE_LOW_WARCRY");
		SOUND_BOOK5_CH2_MALE_PAIN = aMgr.GetSoundThrow("SOUND_BOOK5_CH2_MALE_PAIN");
		SOUND_BOOK5_CH2_SONIC_ATTACK = aMgr.GetSoundThrow("SOUND_BOOK5_CH2_SONIC_ATTACK");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// Book5Chapter3 Resources
Image* Sexy::IMAGE_B5A_BG3;
int Sexy::SOUND_BOOK5_CH3_BEAR_ATTACK;
int Sexy::SOUND_BOOK5_CH3_BEAR_IMPACT;
int Sexy::SOUND_BOOK5_CH3_BEAR_ROAR;
int Sexy::SOUND_BOOK5_CH3_CS_BEATDOWN;
int Sexy::SOUND_BOOK5_CH3_MALE_ANGER;
int Sexy::SOUND_BOOK5_CH3_MALE_GRUNT1;
int Sexy::SOUND_BOOK5_CH3_MALE_GRUNT2;
int Sexy::SOUND_BOOK5_CH3_MALE_LAUGH;
int Sexy::SOUND_BOOK5_CH3_MALE_LAUGH2;
int Sexy::SOUND_BOOK5_CH3_MALE_LOW_WARCRY;
int Sexy::SOUND_BOOK5_CH3_MALE_PAIN;
int Sexy::SOUND_BOOK5_CH3_MISC_IMPACT;
int Sexy::SOUND_BOOK5_CH3_MISC_IMPACT2;
int Sexy::SOUND_BOOK5_CH3_SWORD_IMPACT3;

bool Sexy::ExtractBook5Chapter3Resources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_B5A_BG3 = aMgr.GetImageThrow("IMAGE_B5A_BG3");
		SOUND_BOOK5_CH3_BEAR_ATTACK = aMgr.GetSoundThrow("SOUND_BOOK5_CH3_BEAR_ATTACK");
		SOUND_BOOK5_CH3_BEAR_IMPACT = aMgr.GetSoundThrow("SOUND_BOOK5_CH3_BEAR_IMPACT");
		SOUND_BOOK5_CH3_BEAR_ROAR = aMgr.GetSoundThrow("SOUND_BOOK5_CH3_BEAR_ROAR");
		SOUND_BOOK5_CH3_CS_BEATDOWN = aMgr.GetSoundThrow("SOUND_BOOK5_CH3_CS_BEATDOWN");
		SOUND_BOOK5_CH3_MALE_ANGER = aMgr.GetSoundThrow("SOUND_BOOK5_CH3_MALE_ANGER");
		SOUND_BOOK5_CH3_MALE_GRUNT1 = aMgr.GetSoundThrow("SOUND_BOOK5_CH3_MALE_GRUNT1");
		SOUND_BOOK5_CH3_MALE_GRUNT2 = aMgr.GetSoundThrow("SOUND_BOOK5_CH3_MALE_GRUNT2");
		SOUND_BOOK5_CH3_MALE_LAUGH = aMgr.GetSoundThrow("SOUND_BOOK5_CH3_MALE_LAUGH");
		SOUND_BOOK5_CH3_MALE_LAUGH2 = aMgr.GetSoundThrow("SOUND_BOOK5_CH3_MALE_LAUGH2");
		SOUND_BOOK5_CH3_MALE_LOW_WARCRY = aMgr.GetSoundThrow("SOUND_BOOK5_CH3_MALE_LOW_WARCRY");
		SOUND_BOOK5_CH3_MALE_PAIN = aMgr.GetSoundThrow("SOUND_BOOK5_CH3_MALE_PAIN");
		SOUND_BOOK5_CH3_MISC_IMPACT = aMgr.GetSoundThrow("SOUND_BOOK5_CH3_MISC_IMPACT");
		SOUND_BOOK5_CH3_MISC_IMPACT2 = aMgr.GetSoundThrow("SOUND_BOOK5_CH3_MISC_IMPACT2");
		SOUND_BOOK5_CH3_SWORD_IMPACT3 = aMgr.GetSoundThrow("SOUND_BOOK5_CH3_SWORD_IMPACT3");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// Book5Chapter4 Resources
Image* Sexy::IMAGE_B5A_BG4;
int Sexy::SOUND_BOOK5_CH4_CHICKEN_ATTACK1;
int Sexy::SOUND_BOOK5_CH4_DOG_BARK1;
int Sexy::SOUND_BOOK5_CH4_DOG_BARK2;
int Sexy::SOUND_BOOK5_CH4_DOG_WHIMPER;
int Sexy::SOUND_BOOK5_CH4_GENERIC_ANIMAL;
int Sexy::SOUND_BOOK5_CH4_MISC_IMPACT;
int Sexy::SOUND_BOOK5_CH4_MISC_IMPACT2;
int Sexy::SOUND_BOOK5_CH4_SHEEP_BLEAT;
int Sexy::SOUND_BOOK5_CH4_SNAKE_HISS;
int Sexy::SOUND_BOOK5_CH4_WET_IMPACT1;
int Sexy::SOUND_BOOK5_CH4_WOLF_HOWL;

bool Sexy::ExtractBook5Chapter4Resources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_B5A_BG4 = aMgr.GetImageThrow("IMAGE_B5A_BG4");
		SOUND_BOOK5_CH4_CHICKEN_ATTACK1 = aMgr.GetSoundThrow("SOUND_BOOK5_CH4_CHICKEN_ATTACK1");
		SOUND_BOOK5_CH4_DOG_BARK1 = aMgr.GetSoundThrow("SOUND_BOOK5_CH4_DOG_BARK1");
		SOUND_BOOK5_CH4_DOG_BARK2 = aMgr.GetSoundThrow("SOUND_BOOK5_CH4_DOG_BARK2");
		SOUND_BOOK5_CH4_DOG_WHIMPER = aMgr.GetSoundThrow("SOUND_BOOK5_CH4_DOG_WHIMPER");
		SOUND_BOOK5_CH4_GENERIC_ANIMAL = aMgr.GetSoundThrow("SOUND_BOOK5_CH4_GENERIC_ANIMAL");
		SOUND_BOOK5_CH4_MISC_IMPACT = aMgr.GetSoundThrow("SOUND_BOOK5_CH4_MISC_IMPACT");
		SOUND_BOOK5_CH4_MISC_IMPACT2 = aMgr.GetSoundThrow("SOUND_BOOK5_CH4_MISC_IMPACT2");
		SOUND_BOOK5_CH4_SHEEP_BLEAT = aMgr.GetSoundThrow("SOUND_BOOK5_CH4_SHEEP_BLEAT");
		SOUND_BOOK5_CH4_SNAKE_HISS = aMgr.GetSoundThrow("SOUND_BOOK5_CH4_SNAKE_HISS");
		SOUND_BOOK5_CH4_WET_IMPACT1 = aMgr.GetSoundThrow("SOUND_BOOK5_CH4_WET_IMPACT1");
		SOUND_BOOK5_CH4_WOLF_HOWL = aMgr.GetSoundThrow("SOUND_BOOK5_CH4_WOLF_HOWL");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// Book5Chapter5 Resources
Image* Sexy::IMAGE_B5A_BG5;
int Sexy::SOUND_BOOK5_CH5_CS_SHACKLE;
int Sexy::SOUND_BOOK5_CH5_FEMALE_OOOH;
int Sexy::SOUND_BOOK5_CH5_GHOST_WAIL1;
int Sexy::SOUND_BOOK5_CH5_GHOST_WAIL2;
int Sexy::SOUND_BOOK5_CH5_GHOST_WAIL3;
int Sexy::SOUND_BOOK5_CH5_MALE_LOW_ANGER;
int Sexy::SOUND_BOOK5_CH5_MALE_LOW_PAIN;
int Sexy::SOUND_BOOK5_CH5_MALE_LOW_WARCRY;
int Sexy::SOUND_BOOK5_CH5_SLICING_ATTACK2;
int Sexy::SOUND_BOOK5_CH5_SMOKE_ATTACK;
int Sexy::SOUND_BOOK5_CH5_SMOKE_ATTACK2;
int Sexy::SOUND_BOOK5_CH5_SMOKE_IMPACT;
int Sexy::SOUND_BOOK5_CH5_SONIC_ATTACK;
int Sexy::SOUND_BOOK5_CH5_SWORD_IMPACT2;
int Sexy::SOUND_BOOK5_CH5_SWORD_IMPACT3;
int Sexy::SOUND_BOOK5_CH5_WAIL;
int Sexy::SOUND_BOOK5_CH5_WAIL2;

bool Sexy::ExtractBook5Chapter5Resources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_B5A_BG5 = aMgr.GetImageThrow("IMAGE_B5A_BG5");
		SOUND_BOOK5_CH5_CS_SHACKLE = aMgr.GetSoundThrow("SOUND_BOOK5_CH5_CS_SHACKLE");
		SOUND_BOOK5_CH5_FEMALE_OOOH = aMgr.GetSoundThrow("SOUND_BOOK5_CH5_FEMALE_OOOH");
		SOUND_BOOK5_CH5_GHOST_WAIL1 = aMgr.GetSoundThrow("SOUND_BOOK5_CH5_GHOST_WAIL1");
		SOUND_BOOK5_CH5_GHOST_WAIL2 = aMgr.GetSoundThrow("SOUND_BOOK5_CH5_GHOST_WAIL2");
		SOUND_BOOK5_CH5_GHOST_WAIL3 = aMgr.GetSoundThrow("SOUND_BOOK5_CH5_GHOST_WAIL3");
		SOUND_BOOK5_CH5_MALE_LOW_ANGER = aMgr.GetSoundThrow("SOUND_BOOK5_CH5_MALE_LOW_ANGER");
		SOUND_BOOK5_CH5_MALE_LOW_PAIN = aMgr.GetSoundThrow("SOUND_BOOK5_CH5_MALE_LOW_PAIN");
		SOUND_BOOK5_CH5_MALE_LOW_WARCRY = aMgr.GetSoundThrow("SOUND_BOOK5_CH5_MALE_LOW_WARCRY");
		SOUND_BOOK5_CH5_SLICING_ATTACK2 = aMgr.GetSoundThrow("SOUND_BOOK5_CH5_SLICING_ATTACK2");
		SOUND_BOOK5_CH5_SMOKE_ATTACK = aMgr.GetSoundThrow("SOUND_BOOK5_CH5_SMOKE_ATTACK");
		SOUND_BOOK5_CH5_SMOKE_ATTACK2 = aMgr.GetSoundThrow("SOUND_BOOK5_CH5_SMOKE_ATTACK2");
		SOUND_BOOK5_CH5_SMOKE_IMPACT = aMgr.GetSoundThrow("SOUND_BOOK5_CH5_SMOKE_IMPACT");
		SOUND_BOOK5_CH5_SONIC_ATTACK = aMgr.GetSoundThrow("SOUND_BOOK5_CH5_SONIC_ATTACK");
		SOUND_BOOK5_CH5_SWORD_IMPACT2 = aMgr.GetSoundThrow("SOUND_BOOK5_CH5_SWORD_IMPACT2");
		SOUND_BOOK5_CH5_SWORD_IMPACT3 = aMgr.GetSoundThrow("SOUND_BOOK5_CH5_SWORD_IMPACT3");
		SOUND_BOOK5_CH5_WAIL = aMgr.GetSoundThrow("SOUND_BOOK5_CH5_WAIL");
		SOUND_BOOK5_CH5_WAIL2 = aMgr.GetSoundThrow("SOUND_BOOK5_CH5_WAIL2");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// Book5Chapter6 Resources
Image* Sexy::IMAGE_B5A_BG6;
int Sexy::SOUND_BOOK5_CH6_BEAR_ROAR;
int Sexy::SOUND_BOOK5_CH6_DRAGON_BITE;
int Sexy::SOUND_BOOK5_CH6_DRAGON_DEATH;
int Sexy::SOUND_BOOK5_CH6_DRAGON_PAIN;
int Sexy::SOUND_BOOK5_CH6_DRAGON_ROAR;
int Sexy::SOUND_BOOK5_CH6_MISC_IMPACT;
int Sexy::SOUND_BOOK5_CH6_MISC_IMPACT2;
int Sexy::SOUND_BOOK5_CH6_SLUMP_SMALL;
int Sexy::SOUND_BOOK5_CH6_SONIC_ATTACK;
int Sexy::SOUND_BOOK5_CH6_SWORD_IMPACT3;
int Sexy::SOUND_BOOK5_CH6_WET_IMPACT1;
int Sexy::SOUND_BOOK5_CH6_WET_IMPACT2;

bool Sexy::ExtractBook5Chapter6Resources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_B5A_BG6 = aMgr.GetImageThrow("IMAGE_B5A_BG6");
		SOUND_BOOK5_CH6_BEAR_ROAR = aMgr.GetSoundThrow("SOUND_BOOK5_CH6_BEAR_ROAR");
		SOUND_BOOK5_CH6_DRAGON_BITE = aMgr.GetSoundThrow("SOUND_BOOK5_CH6_DRAGON_BITE");
		SOUND_BOOK5_CH6_DRAGON_DEATH = aMgr.GetSoundThrow("SOUND_BOOK5_CH6_DRAGON_DEATH");
		SOUND_BOOK5_CH6_DRAGON_PAIN = aMgr.GetSoundThrow("SOUND_BOOK5_CH6_DRAGON_PAIN");
		SOUND_BOOK5_CH6_DRAGON_ROAR = aMgr.GetSoundThrow("SOUND_BOOK5_CH6_DRAGON_ROAR");
		SOUND_BOOK5_CH6_MISC_IMPACT = aMgr.GetSoundThrow("SOUND_BOOK5_CH6_MISC_IMPACT");
		SOUND_BOOK5_CH6_MISC_IMPACT2 = aMgr.GetSoundThrow("SOUND_BOOK5_CH6_MISC_IMPACT2");
		SOUND_BOOK5_CH6_SLUMP_SMALL = aMgr.GetSoundThrow("SOUND_BOOK5_CH6_SLUMP_SMALL");
		SOUND_BOOK5_CH6_SONIC_ATTACK = aMgr.GetSoundThrow("SOUND_BOOK5_CH6_SONIC_ATTACK");
		SOUND_BOOK5_CH6_SWORD_IMPACT3 = aMgr.GetSoundThrow("SOUND_BOOK5_CH6_SWORD_IMPACT3");
		SOUND_BOOK5_CH6_WET_IMPACT1 = aMgr.GetSoundThrow("SOUND_BOOK5_CH6_WET_IMPACT1");
		SOUND_BOOK5_CH6_WET_IMPACT2 = aMgr.GetSoundThrow("SOUND_BOOK5_CH6_WET_IMPACT2");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// Book5Chapter7 Resources
Image* Sexy::IMAGE_B5A_BG7;
Image* Sexy::IMAGE_B5A_MONKEYKING_BOSS_BATTLE;
int Sexy::SOUND_BOOK5_CH7_CS_LIGHT;
int Sexy::SOUND_BOOK5_CH7_CS_STINGER;
int Sexy::SOUND_BOOK5_CH7_FIRE_1;
int Sexy::SOUND_BOOK5_CH7_FIRE_3;
int Sexy::SOUND_BOOK5_CH7_FIRE_6;
int Sexy::SOUND_BOOK5_CH7_MALE_LAUGH;
int Sexy::SOUND_BOOK5_CH7_MONKEY_ATTACK;
int Sexy::SOUND_BOOK5_CH7_MONKEY_ATTACK2;
int Sexy::SOUND_BOOK5_CH7_MONKEY_CHALLENGE;
int Sexy::SOUND_BOOK5_CH7_PULSING_ATTACK;
int Sexy::SOUND_BOOK5_CH7_SLICING_ATTACK2;
int Sexy::SOUND_BOOK5_CH7_SMOKE_ATTACK;
int Sexy::SOUND_BOOK5_CH7_SMOKE_ATTACK2;
int Sexy::SOUND_BOOK5_CH7_SMOKE_IMPACT;
int Sexy::SOUND_BOOK5_CH7_SONIC_ATTACK;
int Sexy::SOUND_BOOK5_CH7_SPARKLE_ATTACK;

bool Sexy::ExtractBook5Chapter7Resources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_B5A_BG7 = aMgr.GetImageThrow("IMAGE_B5A_BG7");
		IMAGE_B5A_MONKEYKING_BOSS_BATTLE = aMgr.GetImageThrow("IMAGE_B5A_MONKEYKING_BOSS_BATTLE");
		SOUND_BOOK5_CH7_CS_LIGHT = aMgr.GetSoundThrow("SOUND_BOOK5_CH7_CS_LIGHT");
		SOUND_BOOK5_CH7_CS_STINGER = aMgr.GetSoundThrow("SOUND_BOOK5_CH7_CS_STINGER");
		SOUND_BOOK5_CH7_FIRE_1 = aMgr.GetSoundThrow("SOUND_BOOK5_CH7_FIRE_1");
		SOUND_BOOK5_CH7_FIRE_3 = aMgr.GetSoundThrow("SOUND_BOOK5_CH7_FIRE_3");
		SOUND_BOOK5_CH7_FIRE_6 = aMgr.GetSoundThrow("SOUND_BOOK5_CH7_FIRE_6");
		SOUND_BOOK5_CH7_MALE_LAUGH = aMgr.GetSoundThrow("SOUND_BOOK5_CH7_MALE_LAUGH");
		SOUND_BOOK5_CH7_MONKEY_ATTACK = aMgr.GetSoundThrow("SOUND_BOOK5_CH7_MONKEY_ATTACK");
		SOUND_BOOK5_CH7_MONKEY_ATTACK2 = aMgr.GetSoundThrow("SOUND_BOOK5_CH7_MONKEY_ATTACK2");
		SOUND_BOOK5_CH7_MONKEY_CHALLENGE = aMgr.GetSoundThrow("SOUND_BOOK5_CH7_MONKEY_CHALLENGE");
		SOUND_BOOK5_CH7_PULSING_ATTACK = aMgr.GetSoundThrow("SOUND_BOOK5_CH7_PULSING_ATTACK");
		SOUND_BOOK5_CH7_SLICING_ATTACK2 = aMgr.GetSoundThrow("SOUND_BOOK5_CH7_SLICING_ATTACK2");
		SOUND_BOOK5_CH7_SMOKE_ATTACK = aMgr.GetSoundThrow("SOUND_BOOK5_CH7_SMOKE_ATTACK");
		SOUND_BOOK5_CH7_SMOKE_ATTACK2 = aMgr.GetSoundThrow("SOUND_BOOK5_CH7_SMOKE_ATTACK2");
		SOUND_BOOK5_CH7_SMOKE_IMPACT = aMgr.GetSoundThrow("SOUND_BOOK5_CH7_SMOKE_IMPACT");
		SOUND_BOOK5_CH7_SONIC_ATTACK = aMgr.GetSoundThrow("SOUND_BOOK5_CH7_SONIC_ATTACK");
		SOUND_BOOK5_CH7_SPARKLE_ATTACK = aMgr.GetSoundThrow("SOUND_BOOK5_CH7_SPARKLE_ATTACK");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// Book5Chapter8 Resources
Image* Sexy::IMAGE_B5A_BG8;
int Sexy::SOUND_BOOK5_CH8_FIRE_3;
int Sexy::SOUND_BOOK5_CH8_FIRE_6;
int Sexy::SOUND_BOOK5_CH8_GHOST_WAIL1;
int Sexy::SOUND_BOOK5_CH8_LIGHTNING_ATTACK;
int Sexy::SOUND_BOOK5_CH8_MONSTER_ATTACK;
int Sexy::SOUND_BOOK5_CH8_MONSTER_CHALLENGE;
int Sexy::SOUND_BOOK5_CH8_MONSTER_IMPACT;
int Sexy::SOUND_BOOK5_CH8_SKELETON_WARCRY;
int Sexy::SOUND_BOOK5_CH8_SMOKE_ATTACK2;
int Sexy::SOUND_BOOK5_CH8_SQ_MAM_ATTACK;
int Sexy::SOUND_BOOK5_CH8_SQ_MAM_DEATH;
int Sexy::SOUND_BOOK5_CH8_STRING_ATTACK;
int Sexy::SOUND_BOOK5_CH8_STRING_ATTACK2;
int Sexy::SOUND_BOOK5_CH8_STRING_DEATH;
int Sexy::SOUND_BOOK5_CH8_STRING_IMPACT;

bool Sexy::ExtractBook5Chapter8Resources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_B5A_BG8 = aMgr.GetImageThrow("IMAGE_B5A_BG8");
		SOUND_BOOK5_CH8_FIRE_3 = aMgr.GetSoundThrow("SOUND_BOOK5_CH8_FIRE_3");
		SOUND_BOOK5_CH8_FIRE_6 = aMgr.GetSoundThrow("SOUND_BOOK5_CH8_FIRE_6");
		SOUND_BOOK5_CH8_GHOST_WAIL1 = aMgr.GetSoundThrow("SOUND_BOOK5_CH8_GHOST_WAIL1");
		SOUND_BOOK5_CH8_LIGHTNING_ATTACK = aMgr.GetSoundThrow("SOUND_BOOK5_CH8_LIGHTNING_ATTACK");
		SOUND_BOOK5_CH8_MONSTER_ATTACK = aMgr.GetSoundThrow("SOUND_BOOK5_CH8_MONSTER_ATTACK");
		SOUND_BOOK5_CH8_MONSTER_CHALLENGE = aMgr.GetSoundThrow("SOUND_BOOK5_CH8_MONSTER_CHALLENGE");
		SOUND_BOOK5_CH8_MONSTER_IMPACT = aMgr.GetSoundThrow("SOUND_BOOK5_CH8_MONSTER_IMPACT");
		SOUND_BOOK5_CH8_SKELETON_WARCRY = aMgr.GetSoundThrow("SOUND_BOOK5_CH8_SKELETON_WARCRY");
		SOUND_BOOK5_CH8_SMOKE_ATTACK2 = aMgr.GetSoundThrow("SOUND_BOOK5_CH8_SMOKE_ATTACK2");
		SOUND_BOOK5_CH8_SQ_MAM_ATTACK = aMgr.GetSoundThrow("SOUND_BOOK5_CH8_SQ_MAM_ATTACK");
		SOUND_BOOK5_CH8_SQ_MAM_DEATH = aMgr.GetSoundThrow("SOUND_BOOK5_CH8_SQ_MAM_DEATH");
		SOUND_BOOK5_CH8_STRING_ATTACK = aMgr.GetSoundThrow("SOUND_BOOK5_CH8_STRING_ATTACK");
		SOUND_BOOK5_CH8_STRING_ATTACK2 = aMgr.GetSoundThrow("SOUND_BOOK5_CH8_STRING_ATTACK2");
		SOUND_BOOK5_CH8_STRING_DEATH = aMgr.GetSoundThrow("SOUND_BOOK5_CH8_STRING_DEATH");
		SOUND_BOOK5_CH8_STRING_IMPACT = aMgr.GetSoundThrow("SOUND_BOOK5_CH8_STRING_IMPACT");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// Book5Chapter9 Resources
Image* Sexy::IMAGE_B5A_BG9;
int Sexy::SOUND_BOOK5_CH9_SMOKE_ATTACK;
int Sexy::SOUND_BOOK5_CH9_SMOKE_ATTACK2;
int Sexy::SOUND_BOOK5_CH9_SMOKE_IMPACT;
int Sexy::SOUND_BOOK5_CH9_SONIC_ATTACK;
int Sexy::SOUND_BOOK5_CH9_SPARKLE_ATTACK;
int Sexy::SOUND_BOOK5_CH9_SWORD_IMPACT;
int Sexy::SOUND_BOOK5_CH9_SWORD_IMPACT2;
int Sexy::SOUND_BOOK5_CH9_SWORD_IMPACT3;

bool Sexy::ExtractBook5Chapter9Resources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_B5A_BG9 = aMgr.GetImageThrow("IMAGE_B5A_BG9");
		SOUND_BOOK5_CH9_SMOKE_ATTACK = aMgr.GetSoundThrow("SOUND_BOOK5_CH9_SMOKE_ATTACK");
		SOUND_BOOK5_CH9_SMOKE_ATTACK2 = aMgr.GetSoundThrow("SOUND_BOOK5_CH9_SMOKE_ATTACK2");
		SOUND_BOOK5_CH9_SMOKE_IMPACT = aMgr.GetSoundThrow("SOUND_BOOK5_CH9_SMOKE_IMPACT");
		SOUND_BOOK5_CH9_SONIC_ATTACK = aMgr.GetSoundThrow("SOUND_BOOK5_CH9_SONIC_ATTACK");
		SOUND_BOOK5_CH9_SPARKLE_ATTACK = aMgr.GetSoundThrow("SOUND_BOOK5_CH9_SPARKLE_ATTACK");
		SOUND_BOOK5_CH9_SWORD_IMPACT = aMgr.GetSoundThrow("SOUND_BOOK5_CH9_SWORD_IMPACT");
		SOUND_BOOK5_CH9_SWORD_IMPACT2 = aMgr.GetSoundThrow("SOUND_BOOK5_CH9_SWORD_IMPACT2");
		SOUND_BOOK5_CH9_SWORD_IMPACT3 = aMgr.GetSoundThrow("SOUND_BOOK5_CH9_SWORD_IMPACT3");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// Book5Init Resources
Image* Sexy::IMAGE_B5_ICONANIM1;
Image* Sexy::IMAGE_B5_ICONANIM10;
Image* Sexy::IMAGE_B5_ICONANIM2;
Image* Sexy::IMAGE_B5_ICONANIM3;
Image* Sexy::IMAGE_B5_ICONANIM4;
Image* Sexy::IMAGE_B5_ICONANIM5;
Image* Sexy::IMAGE_B5_ICONANIM6;
Image* Sexy::IMAGE_B5_ICONANIM7;
Image* Sexy::IMAGE_B5_ICONANIM8;
Image* Sexy::IMAGE_B5_ICONANIM9;
Image* Sexy::IMAGE_B5_ICONMASK1;
Image* Sexy::IMAGE_B5_ICONMASK10;
Image* Sexy::IMAGE_B5_ICONMASK2;
Image* Sexy::IMAGE_B5_ICONMASK3;
Image* Sexy::IMAGE_B5_ICONMASK4;
Image* Sexy::IMAGE_B5_ICONMASK5;
Image* Sexy::IMAGE_B5_ICONMASK6;
Image* Sexy::IMAGE_B5_ICONMASK7;
Image* Sexy::IMAGE_B5_ICONMASK8;
Image* Sexy::IMAGE_B5_ICONMASK9;
Image* Sexy::IMAGE_B5_MAP;
Image* Sexy::IMAGE_B5_MAPSCREEN_BANNER;
Image* Sexy::IMAGE_B5_MINIMAP_ICONS;
Image* Sexy::IMAGE_TUT_PIC_DRAGON;
Image* Sexy::IMAGE_TUT_PIC_JADE_EMP;
Image* Sexy::IMAGE_TUT_PIC_JADE_EMP_R;
Image* Sexy::IMAGE_TUT_PIC_PIGGY;
Image* Sexy::IMAGE_TUT_PIC_PRIDEFUL;
Image* Sexy::IMAGE_TUT_PIC_SIFU;
Image* Sexy::IMAGE_TUT_PIC_TIGER;

bool Sexy::ExtractBook5InitResources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_B5_ICONANIM1 = aMgr.GetImageThrow("IMAGE_B5_ICONANIM1");
		IMAGE_B5_ICONANIM10 = aMgr.GetImageThrow("IMAGE_B5_ICONANIM10");
		IMAGE_B5_ICONANIM2 = aMgr.GetImageThrow("IMAGE_B5_ICONANIM2");
		IMAGE_B5_ICONANIM3 = aMgr.GetImageThrow("IMAGE_B5_ICONANIM3");
		IMAGE_B5_ICONANIM4 = aMgr.GetImageThrow("IMAGE_B5_ICONANIM4");
		IMAGE_B5_ICONANIM5 = aMgr.GetImageThrow("IMAGE_B5_ICONANIM5");
		IMAGE_B5_ICONANIM6 = aMgr.GetImageThrow("IMAGE_B5_ICONANIM6");
		IMAGE_B5_ICONANIM7 = aMgr.GetImageThrow("IMAGE_B5_ICONANIM7");
		IMAGE_B5_ICONANIM8 = aMgr.GetImageThrow("IMAGE_B5_ICONANIM8");
		IMAGE_B5_ICONANIM9 = aMgr.GetImageThrow("IMAGE_B5_ICONANIM9");
		IMAGE_B5_ICONMASK1 = aMgr.GetImageThrow("IMAGE_B5_ICONMASK1");
		IMAGE_B5_ICONMASK10 = aMgr.GetImageThrow("IMAGE_B5_ICONMASK10");
		IMAGE_B5_ICONMASK2 = aMgr.GetImageThrow("IMAGE_B5_ICONMASK2");
		IMAGE_B5_ICONMASK3 = aMgr.GetImageThrow("IMAGE_B5_ICONMASK3");
		IMAGE_B5_ICONMASK4 = aMgr.GetImageThrow("IMAGE_B5_ICONMASK4");
		IMAGE_B5_ICONMASK5 = aMgr.GetImageThrow("IMAGE_B5_ICONMASK5");
		IMAGE_B5_ICONMASK6 = aMgr.GetImageThrow("IMAGE_B5_ICONMASK6");
		IMAGE_B5_ICONMASK7 = aMgr.GetImageThrow("IMAGE_B5_ICONMASK7");
		IMAGE_B5_ICONMASK8 = aMgr.GetImageThrow("IMAGE_B5_ICONMASK8");
		IMAGE_B5_ICONMASK9 = aMgr.GetImageThrow("IMAGE_B5_ICONMASK9");
		IMAGE_B5_MAP = aMgr.GetImageThrow("IMAGE_B5_MAP");
		IMAGE_B5_MAPSCREEN_BANNER = aMgr.GetImageThrow("IMAGE_B5_MAPSCREEN_BANNER");
		IMAGE_B5_MINIMAP_ICONS = aMgr.GetImageThrow("IMAGE_B5_MINIMAP_ICONS");
		IMAGE_TUT_PIC_DRAGON = aMgr.GetImageThrow("IMAGE_TUT_PIC_DRAGON");
		IMAGE_TUT_PIC_JADE_EMP = aMgr.GetImageThrow("IMAGE_TUT_PIC_JADE_EMP");
		IMAGE_TUT_PIC_JADE_EMP_R = aMgr.GetImageThrow("IMAGE_TUT_PIC_JADE_EMP_R");
		IMAGE_TUT_PIC_PIGGY = aMgr.GetImageThrow("IMAGE_TUT_PIC_PIGGY");
		IMAGE_TUT_PIC_PRIDEFUL = aMgr.GetImageThrow("IMAGE_TUT_PIC_PRIDEFUL");
		IMAGE_TUT_PIC_SIFU = aMgr.GetImageThrow("IMAGE_TUT_PIC_SIFU");
		IMAGE_TUT_PIC_TIGER = aMgr.GetImageThrow("IMAGE_TUT_PIC_TIGER");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

static void* gResources[] =
{
	&IMAGE_B5_MINIMAP_ICONS,
	&IMAGE_B5_MAPSCREEN_BANNER,
	&IMAGE_B5_ICONANIM1,
	&IMAGE_B5_ICONANIM2,
	&IMAGE_B5_ICONANIM3,
	&IMAGE_B5_ICONANIM4,
	&IMAGE_B5_ICONANIM5,
	&IMAGE_B5_ICONANIM6,
	&IMAGE_B5_ICONANIM7,
	&IMAGE_B5_ICONANIM8,
	&IMAGE_B5_ICONANIM9,
	&IMAGE_B5_ICONANIM10,
	&IMAGE_B5_ICONMASK1,
	&IMAGE_B5_ICONMASK2,
	&IMAGE_B5_ICONMASK3,
	&IMAGE_B5_ICONMASK4,
	&IMAGE_B5_ICONMASK5,
	&IMAGE_B5_ICONMASK6,
	&IMAGE_B5_ICONMASK7,
	&IMAGE_B5_ICONMASK8,
	&IMAGE_B5_ICONMASK9,
	&IMAGE_B5_ICONMASK10,
	&IMAGE_B5_MAP,
	&IMAGE_TUT_PIC_PIGGY,
	&IMAGE_TUT_PIC_TIGER,
	&IMAGE_TUT_PIC_PRIDEFUL,
	&IMAGE_TUT_PIC_SIFU,
	&IMAGE_TUT_PIC_DRAGON,
	&IMAGE_TUT_PIC_JADE_EMP,
	&IMAGE_TUT_PIC_JADE_EMP_R,
	&IMAGE_B5_LEFT_FACING_ARROW,
	&IMAGE_B5A_BG1,
	&SOUND_BOOK5_CH1_FELINE_ENGAGE,
	&SOUND_BOOK5_CH1_FELINE_ROAR,
	&SOUND_BOOK5_CH1_PIG_SQUEAL2,
	&SOUND_BOOK5_CH1_PIG_ATTACK,
	&SOUND_BOOK5_CH1_DONKEY_BRAY,
	&SOUND_BOOK5_CH1_DONKEY_IMPACT,
	&SOUND_BOOK5_CH1_SLICING_ATTACK,
	&SOUND_BOOK5_CH1_SLICING_ATTACK2,
	&SOUND_BOOK5_CH1_WET_IMPACT1,
	&IMAGE_B5A_BG2,
	&SOUND_BOOK5_CH2_DOPEY_ATTACK,
	&SOUND_BOOK5_CH2_DOPEY_IMPACT,
	&SOUND_BOOK5_CH2_MALE_GRUNT1,
	&SOUND_BOOK5_CH2_MALE_GRUNT2,
	&SOUND_BOOK5_CH2_MALE_ANGER,
	&SOUND_BOOK5_CH2_MALE_LAUGH,
	&SOUND_BOOK5_CH2_MALE_LAUGH2,
	&SOUND_BOOK5_CH2_MALE_LOW_ANGER,
	&SOUND_BOOK5_CH2_MALE_LOW_PAIN,
	&SOUND_BOOK5_CH2_MALE_LOW_WARCRY,
	&SOUND_BOOK5_CH2_MALE_PAIN,
	&SOUND_BOOK5_CH2_SONIC_ATTACK,
	&IMAGE_B5A_BG3,
	&SOUND_BOOK5_CH3_MALE_GRUNT1,
	&SOUND_BOOK5_CH3_MALE_GRUNT2,
	&SOUND_BOOK5_CH3_MALE_ANGER,
	&SOUND_BOOK5_CH3_MALE_LAUGH,
	&SOUND_BOOK5_CH3_MALE_LAUGH2,
	&SOUND_BOOK5_CH3_MALE_LOW_WARCRY,
	&SOUND_BOOK5_CH3_MALE_PAIN,
	&SOUND_BOOK5_CH3_SWORD_IMPACT3,
	&SOUND_BOOK5_CH3_MISC_IMPACT,
	&SOUND_BOOK5_CH3_MISC_IMPACT2,
	&SOUND_BOOK5_CH3_BEAR_ATTACK,
	&SOUND_BOOK5_CH3_BEAR_IMPACT,
	&SOUND_BOOK5_CH3_BEAR_ROAR,
	&SOUND_BOOK5_CH3_CS_BEATDOWN,
	&IMAGE_B5A_BG4,
	&SOUND_BOOK5_CH4_SNAKE_HISS,
	&SOUND_BOOK5_CH4_SHEEP_BLEAT,
	&SOUND_BOOK5_CH4_CHICKEN_ATTACK1,
	&SOUND_BOOK5_CH4_DOG_BARK1,
	&SOUND_BOOK5_CH4_DOG_BARK2,
	&SOUND_BOOK5_CH4_DOG_WHIMPER,
	&SOUND_BOOK5_CH4_MISC_IMPACT,
	&SOUND_BOOK5_CH4_MISC_IMPACT2,
	&SOUND_BOOK5_CH4_WET_IMPACT1,
	&SOUND_BOOK5_CH4_GENERIC_ANIMAL,
	&SOUND_BOOK5_CH4_WOLF_HOWL,
	&IMAGE_B5A_BG5,
	&SOUND_BOOK5_CH5_GHOST_WAIL1,
	&SOUND_BOOK5_CH5_GHOST_WAIL2,
	&SOUND_BOOK5_CH5_GHOST_WAIL3,
	&SOUND_BOOK5_CH5_SWORD_IMPACT2,
	&SOUND_BOOK5_CH5_WAIL,
	&SOUND_BOOK5_CH5_WAIL2,
	&SOUND_BOOK5_CH5_SMOKE_ATTACK,
	&SOUND_BOOK5_CH5_SMOKE_ATTACK2,
	&SOUND_BOOK5_CH5_SMOKE_IMPACT,
	&SOUND_BOOK5_CH5_SONIC_ATTACK,
	&SOUND_BOOK5_CH5_MALE_LOW_ANGER,
	&SOUND_BOOK5_CH5_MALE_LOW_PAIN,
	&SOUND_BOOK5_CH5_MALE_LOW_WARCRY,
	&SOUND_BOOK5_CH5_SWORD_IMPACT3,
	&SOUND_BOOK5_CH5_SLICING_ATTACK2,
	&SOUND_BOOK5_CH5_FEMALE_OOOH,
	&SOUND_BOOK5_CH5_CS_SHACKLE,
	&IMAGE_B5A_BG6,
	&SOUND_BOOK5_CH6_DRAGON_BITE,
	&SOUND_BOOK5_CH6_DRAGON_DEATH,
	&SOUND_BOOK5_CH6_DRAGON_PAIN,
	&SOUND_BOOK5_CH6_DRAGON_ROAR,
	&SOUND_BOOK5_CH6_WET_IMPACT1,
	&SOUND_BOOK5_CH6_WET_IMPACT2,
	&SOUND_BOOK5_CH6_MISC_IMPACT,
	&SOUND_BOOK5_CH6_MISC_IMPACT2,
	&SOUND_BOOK5_CH6_SLUMP_SMALL,
	&SOUND_BOOK5_CH6_SWORD_IMPACT3,
	&SOUND_BOOK5_CH6_SONIC_ATTACK,
	&SOUND_BOOK5_CH6_BEAR_ROAR,
	&IMAGE_B5A_BG7,
	&IMAGE_B5A_MONKEYKING_BOSS_BATTLE,
	&SOUND_BOOK5_CH7_SONIC_ATTACK,
	&SOUND_BOOK5_CH7_SPARKLE_ATTACK,
	&SOUND_BOOK5_CH7_SMOKE_ATTACK,
	&SOUND_BOOK5_CH7_SMOKE_ATTACK2,
	&SOUND_BOOK5_CH7_SMOKE_IMPACT,
	&SOUND_BOOK5_CH7_PULSING_ATTACK,
	&SOUND_BOOK5_CH7_FIRE_1,
	&SOUND_BOOK5_CH7_FIRE_3,
	&SOUND_BOOK5_CH7_FIRE_6,
	&SOUND_BOOK5_CH7_MONKEY_ATTACK,
	&SOUND_BOOK5_CH7_MONKEY_ATTACK2,
	&SOUND_BOOK5_CH7_MONKEY_CHALLENGE,
	&SOUND_BOOK5_CH7_SLICING_ATTACK2,
	&SOUND_BOOK5_CH7_MALE_LAUGH,
	&SOUND_BOOK5_CH7_CS_STINGER,
	&SOUND_BOOK5_CH7_CS_LIGHT,
	&IMAGE_B5A_BG8,
	&SOUND_BOOK5_CH8_MONSTER_ATTACK,
	&SOUND_BOOK5_CH8_MONSTER_CHALLENGE,
	&SOUND_BOOK5_CH8_MONSTER_IMPACT,
	&SOUND_BOOK5_CH8_STRING_ATTACK,
	&SOUND_BOOK5_CH8_STRING_ATTACK2,
	&SOUND_BOOK5_CH8_STRING_DEATH,
	&SOUND_BOOK5_CH8_STRING_IMPACT,
	&SOUND_BOOK5_CH8_SQ_MAM_ATTACK,
	&SOUND_BOOK5_CH8_SKELETON_WARCRY,
	&SOUND_BOOK5_CH8_SQ_MAM_DEATH,
	&SOUND_BOOK5_CH8_FIRE_3,
	&SOUND_BOOK5_CH8_FIRE_6,
	&SOUND_BOOK5_CH8_GHOST_WAIL1,
	&SOUND_BOOK5_CH8_LIGHTNING_ATTACK,
	&SOUND_BOOK5_CH8_SMOKE_ATTACK2,
	&IMAGE_B5A_BG9,
	&SOUND_BOOK5_CH9_SMOKE_ATTACK,
	&SOUND_BOOK5_CH9_SMOKE_ATTACK2,
	&SOUND_BOOK5_CH9_SMOKE_IMPACT,
	&SOUND_BOOK5_CH9_SPARKLE_ATTACK,
	&SOUND_BOOK5_CH9_SWORD_IMPACT,
	&SOUND_BOOK5_CH9_SWORD_IMPACT2,
	&SOUND_BOOK5_CH9_SWORD_IMPACT3,
	&SOUND_BOOK5_CH9_SONIC_ATTACK,
	&IMAGE_B5A_BG10,
	&SOUND_BOOK5_CH10_STRING_ATTACK,
	&SOUND_BOOK5_CH10_MALE_LOW_ANGER,
	&SOUND_BOOK5_CH10_MALE_LOW_PAIN,
	&SOUND_BOOK5_CH10_MALE_LOW_WARCRY,
	&SOUND_BOOK5_CH10_SWORD_IMPACT,
	&SOUND_BOOK5_CH10_SWORD_IMPACT2,
	&SOUND_BOOK5_CH10_SWORD_IMPACT3,
	&SOUND_BOOK5_CH10_ARROW_SHOT,
	&SOUND_BOOK5_CH10_SONIC_ATTACK,
	&SOUND_BOOK5_CH10_STRING_ATTACK2,
	&SOUND_BOOK5_CH10_FIRE_6,
	&SOUND_BOOK5_CH10_DOG_BARK1,
	&SOUND_BOOK5_CH10_LIGHTNING_ATTACK,
	&SOUND_BOOK5_CH10_SMOKE_ATTACK2,
	NULL
};

Image* Sexy::LoadImageById(ResourceManager *theManager, int theId)
{
	return (*((Image**)gResources[theId]) = theManager->LoadImage(GetStringIdById(theId)));
}

void Sexy::ReplaceImageById(ResourceManager *theManager, int theId, Image *theImage)
{
	theManager->ReplaceImage(GetStringIdById(theId),theImage);
	*(Image**)gResources[theId] = theImage;
}

Image* Sexy::GetImageById(int theId)
{
	return *(Image**)gResources[theId];
}

Font* Sexy::GetFontById(int theId)
{
	return *(Font**)gResources[theId];
}

int Sexy::GetSoundById(int theId)
{
	return *(int*)gResources[theId];
}

Image*& Sexy::GetImageRefById(int theId)
{
	return *(Image**)gResources[theId];
}

Font*& Sexy::GetFontRefById(int theId)
{
	return *(Font**)gResources[theId];
}

int& Sexy::GetSoundRefById(int theId)
{
	return *(int*)gResources[theId];
}

static Sexy::ResourceId GetIdByVariable(const void *theVariable)
{
	typedef std::map<int,int> MyMap;
	static MyMap aMap;
	if(gNeedRecalcVariableToIdMap)
	{
		gNeedRecalcVariableToIdMap = false;
		aMap.clear();
		for(int i=0; i<RESOURCE_ID_MAX; i++)
			aMap[*(int*)gResources[i]] = i;
	}

	MyMap::iterator anItr = aMap.find((int)theVariable);
	if (anItr == aMap.end())
		return RESOURCE_ID_MAX;
	else
		return (ResourceId) anItr->second;
}

Sexy::ResourceId Sexy::GetIdByImage(Image *theImage)
{
	return GetIdByVariable(theImage);
}

Sexy::ResourceId Sexy::GetIdByFont(Font *theFont)
{
	return GetIdByVariable(theFont);
}

Sexy::ResourceId Sexy::GetIdBySound(int theSound)
{
	return GetIdByVariable((void*)theSound);
}

const char* Sexy::GetStringIdById(int theId)
{
	switch(theId)
	{
		case IMAGE_B5_MINIMAP_ICONS_ID: return "IMAGE_B5_MINIMAP_ICONS";
		case IMAGE_B5_MAPSCREEN_BANNER_ID: return "IMAGE_B5_MAPSCREEN_BANNER";
		case IMAGE_B5_ICONANIM1_ID: return "IMAGE_B5_ICONANIM1";
		case IMAGE_B5_ICONANIM2_ID: return "IMAGE_B5_ICONANIM2";
		case IMAGE_B5_ICONANIM3_ID: return "IMAGE_B5_ICONANIM3";
		case IMAGE_B5_ICONANIM4_ID: return "IMAGE_B5_ICONANIM4";
		case IMAGE_B5_ICONANIM5_ID: return "IMAGE_B5_ICONANIM5";
		case IMAGE_B5_ICONANIM6_ID: return "IMAGE_B5_ICONANIM6";
		case IMAGE_B5_ICONANIM7_ID: return "IMAGE_B5_ICONANIM7";
		case IMAGE_B5_ICONANIM8_ID: return "IMAGE_B5_ICONANIM8";
		case IMAGE_B5_ICONANIM9_ID: return "IMAGE_B5_ICONANIM9";
		case IMAGE_B5_ICONANIM10_ID: return "IMAGE_B5_ICONANIM10";
		case IMAGE_B5_ICONMASK1_ID: return "IMAGE_B5_ICONMASK1";
		case IMAGE_B5_ICONMASK2_ID: return "IMAGE_B5_ICONMASK2";
		case IMAGE_B5_ICONMASK3_ID: return "IMAGE_B5_ICONMASK3";
		case IMAGE_B5_ICONMASK4_ID: return "IMAGE_B5_ICONMASK4";
		case IMAGE_B5_ICONMASK5_ID: return "IMAGE_B5_ICONMASK5";
		case IMAGE_B5_ICONMASK6_ID: return "IMAGE_B5_ICONMASK6";
		case IMAGE_B5_ICONMASK7_ID: return "IMAGE_B5_ICONMASK7";
		case IMAGE_B5_ICONMASK8_ID: return "IMAGE_B5_ICONMASK8";
		case IMAGE_B5_ICONMASK9_ID: return "IMAGE_B5_ICONMASK9";
		case IMAGE_B5_ICONMASK10_ID: return "IMAGE_B5_ICONMASK10";
		case IMAGE_B5_MAP_ID: return "IMAGE_B5_MAP";
		case IMAGE_TUT_PIC_PIGGY_ID: return "IMAGE_TUT_PIC_PIGGY";
		case IMAGE_TUT_PIC_TIGER_ID: return "IMAGE_TUT_PIC_TIGER";
		case IMAGE_TUT_PIC_PRIDEFUL_ID: return "IMAGE_TUT_PIC_PRIDEFUL";
		case IMAGE_TUT_PIC_SIFU_ID: return "IMAGE_TUT_PIC_SIFU";
		case IMAGE_TUT_PIC_DRAGON_ID: return "IMAGE_TUT_PIC_DRAGON";
		case IMAGE_TUT_PIC_JADE_EMP_ID: return "IMAGE_TUT_PIC_JADE_EMP";
		case IMAGE_TUT_PIC_JADE_EMP_R_ID: return "IMAGE_TUT_PIC_JADE_EMP_R";
		case IMAGE_B5_LEFT_FACING_ARROW_ID: return "IMAGE_B5_LEFT_FACING_ARROW";
		case IMAGE_B5A_BG1_ID: return "IMAGE_B5A_BG1";
		case SOUND_BOOK5_CH1_FELINE_ENGAGE_ID: return "SOUND_BOOK5_CH1_FELINE_ENGAGE";
		case SOUND_BOOK5_CH1_FELINE_ROAR_ID: return "SOUND_BOOK5_CH1_FELINE_ROAR";
		case SOUND_BOOK5_CH1_PIG_SQUEAL2_ID: return "SOUND_BOOK5_CH1_PIG_SQUEAL2";
		case SOUND_BOOK5_CH1_PIG_ATTACK_ID: return "SOUND_BOOK5_CH1_PIG_ATTACK";
		case SOUND_BOOK5_CH1_DONKEY_BRAY_ID: return "SOUND_BOOK5_CH1_DONKEY_BRAY";
		case SOUND_BOOK5_CH1_DONKEY_IMPACT_ID: return "SOUND_BOOK5_CH1_DONKEY_IMPACT";
		case SOUND_BOOK5_CH1_SLICING_ATTACK_ID: return "SOUND_BOOK5_CH1_SLICING_ATTACK";
		case SOUND_BOOK5_CH1_SLICING_ATTACK2_ID: return "SOUND_BOOK5_CH1_SLICING_ATTACK2";
		case SOUND_BOOK5_CH1_WET_IMPACT1_ID: return "SOUND_BOOK5_CH1_WET_IMPACT1";
		case IMAGE_B5A_BG2_ID: return "IMAGE_B5A_BG2";
		case SOUND_BOOK5_CH2_DOPEY_ATTACK_ID: return "SOUND_BOOK5_CH2_DOPEY_ATTACK";
		case SOUND_BOOK5_CH2_DOPEY_IMPACT_ID: return "SOUND_BOOK5_CH2_DOPEY_IMPACT";
		case SOUND_BOOK5_CH2_MALE_GRUNT1_ID: return "SOUND_BOOK5_CH2_MALE_GRUNT1";
		case SOUND_BOOK5_CH2_MALE_GRUNT2_ID: return "SOUND_BOOK5_CH2_MALE_GRUNT2";
		case SOUND_BOOK5_CH2_MALE_ANGER_ID: return "SOUND_BOOK5_CH2_MALE_ANGER";
		case SOUND_BOOK5_CH2_MALE_LAUGH_ID: return "SOUND_BOOK5_CH2_MALE_LAUGH";
		case SOUND_BOOK5_CH2_MALE_LAUGH2_ID: return "SOUND_BOOK5_CH2_MALE_LAUGH2";
		case SOUND_BOOK5_CH2_MALE_LOW_ANGER_ID: return "SOUND_BOOK5_CH2_MALE_LOW_ANGER";
		case SOUND_BOOK5_CH2_MALE_LOW_PAIN_ID: return "SOUND_BOOK5_CH2_MALE_LOW_PAIN";
		case SOUND_BOOK5_CH2_MALE_LOW_WARCRY_ID: return "SOUND_BOOK5_CH2_MALE_LOW_WARCRY";
		case SOUND_BOOK5_CH2_MALE_PAIN_ID: return "SOUND_BOOK5_CH2_MALE_PAIN";
		case SOUND_BOOK5_CH2_SONIC_ATTACK_ID: return "SOUND_BOOK5_CH2_SONIC_ATTACK";
		case IMAGE_B5A_BG3_ID: return "IMAGE_B5A_BG3";
		case SOUND_BOOK5_CH3_MALE_GRUNT1_ID: return "SOUND_BOOK5_CH3_MALE_GRUNT1";
		case SOUND_BOOK5_CH3_MALE_GRUNT2_ID: return "SOUND_BOOK5_CH3_MALE_GRUNT2";
		case SOUND_BOOK5_CH3_MALE_ANGER_ID: return "SOUND_BOOK5_CH3_MALE_ANGER";
		case SOUND_BOOK5_CH3_MALE_LAUGH_ID: return "SOUND_BOOK5_CH3_MALE_LAUGH";
		case SOUND_BOOK5_CH3_MALE_LAUGH2_ID: return "SOUND_BOOK5_CH3_MALE_LAUGH2";
		case SOUND_BOOK5_CH3_MALE_LOW_WARCRY_ID: return "SOUND_BOOK5_CH3_MALE_LOW_WARCRY";
		case SOUND_BOOK5_CH3_MALE_PAIN_ID: return "SOUND_BOOK5_CH3_MALE_PAIN";
		case SOUND_BOOK5_CH3_SWORD_IMPACT3_ID: return "SOUND_BOOK5_CH3_SWORD_IMPACT3";
		case SOUND_BOOK5_CH3_MISC_IMPACT_ID: return "SOUND_BOOK5_CH3_MISC_IMPACT";
		case SOUND_BOOK5_CH3_MISC_IMPACT2_ID: return "SOUND_BOOK5_CH3_MISC_IMPACT2";
		case SOUND_BOOK5_CH3_BEAR_ATTACK_ID: return "SOUND_BOOK5_CH3_BEAR_ATTACK";
		case SOUND_BOOK5_CH3_BEAR_IMPACT_ID: return "SOUND_BOOK5_CH3_BEAR_IMPACT";
		case SOUND_BOOK5_CH3_BEAR_ROAR_ID: return "SOUND_BOOK5_CH3_BEAR_ROAR";
		case SOUND_BOOK5_CH3_CS_BEATDOWN_ID: return "SOUND_BOOK5_CH3_CS_BEATDOWN";
		case IMAGE_B5A_BG4_ID: return "IMAGE_B5A_BG4";
		case SOUND_BOOK5_CH4_SNAKE_HISS_ID: return "SOUND_BOOK5_CH4_SNAKE_HISS";
		case SOUND_BOOK5_CH4_SHEEP_BLEAT_ID: return "SOUND_BOOK5_CH4_SHEEP_BLEAT";
		case SOUND_BOOK5_CH4_CHICKEN_ATTACK1_ID: return "SOUND_BOOK5_CH4_CHICKEN_ATTACK1";
		case SOUND_BOOK5_CH4_DOG_BARK1_ID: return "SOUND_BOOK5_CH4_DOG_BARK1";
		case SOUND_BOOK5_CH4_DOG_BARK2_ID: return "SOUND_BOOK5_CH4_DOG_BARK2";
		case SOUND_BOOK5_CH4_DOG_WHIMPER_ID: return "SOUND_BOOK5_CH4_DOG_WHIMPER";
		case SOUND_BOOK5_CH4_MISC_IMPACT_ID: return "SOUND_BOOK5_CH4_MISC_IMPACT";
		case SOUND_BOOK5_CH4_MISC_IMPACT2_ID: return "SOUND_BOOK5_CH4_MISC_IMPACT2";
		case SOUND_BOOK5_CH4_WET_IMPACT1_ID: return "SOUND_BOOK5_CH4_WET_IMPACT1";
		case SOUND_BOOK5_CH4_GENERIC_ANIMAL_ID: return "SOUND_BOOK5_CH4_GENERIC_ANIMAL";
		case SOUND_BOOK5_CH4_WOLF_HOWL_ID: return "SOUND_BOOK5_CH4_WOLF_HOWL";
		case IMAGE_B5A_BG5_ID: return "IMAGE_B5A_BG5";
		case SOUND_BOOK5_CH5_GHOST_WAIL1_ID: return "SOUND_BOOK5_CH5_GHOST_WAIL1";
		case SOUND_BOOK5_CH5_GHOST_WAIL2_ID: return "SOUND_BOOK5_CH5_GHOST_WAIL2";
		case SOUND_BOOK5_CH5_GHOST_WAIL3_ID: return "SOUND_BOOK5_CH5_GHOST_WAIL3";
		case SOUND_BOOK5_CH5_SWORD_IMPACT2_ID: return "SOUND_BOOK5_CH5_SWORD_IMPACT2";
		case SOUND_BOOK5_CH5_WAIL_ID: return "SOUND_BOOK5_CH5_WAIL";
		case SOUND_BOOK5_CH5_WAIL2_ID: return "SOUND_BOOK5_CH5_WAIL2";
		case SOUND_BOOK5_CH5_SMOKE_ATTACK_ID: return "SOUND_BOOK5_CH5_SMOKE_ATTACK";
		case SOUND_BOOK5_CH5_SMOKE_ATTACK2_ID: return "SOUND_BOOK5_CH5_SMOKE_ATTACK2";
		case SOUND_BOOK5_CH5_SMOKE_IMPACT_ID: return "SOUND_BOOK5_CH5_SMOKE_IMPACT";
		case SOUND_BOOK5_CH5_SONIC_ATTACK_ID: return "SOUND_BOOK5_CH5_SONIC_ATTACK";
		case SOUND_BOOK5_CH5_MALE_LOW_ANGER_ID: return "SOUND_BOOK5_CH5_MALE_LOW_ANGER";
		case SOUND_BOOK5_CH5_MALE_LOW_PAIN_ID: return "SOUND_BOOK5_CH5_MALE_LOW_PAIN";
		case SOUND_BOOK5_CH5_MALE_LOW_WARCRY_ID: return "SOUND_BOOK5_CH5_MALE_LOW_WARCRY";
		case SOUND_BOOK5_CH5_SWORD_IMPACT3_ID: return "SOUND_BOOK5_CH5_SWORD_IMPACT3";
		case SOUND_BOOK5_CH5_SLICING_ATTACK2_ID: return "SOUND_BOOK5_CH5_SLICING_ATTACK2";
		case SOUND_BOOK5_CH5_FEMALE_OOOH_ID: return "SOUND_BOOK5_CH5_FEMALE_OOOH";
		case SOUND_BOOK5_CH5_CS_SHACKLE_ID: return "SOUND_BOOK5_CH5_CS_SHACKLE";
		case IMAGE_B5A_BG6_ID: return "IMAGE_B5A_BG6";
		case SOUND_BOOK5_CH6_DRAGON_BITE_ID: return "SOUND_BOOK5_CH6_DRAGON_BITE";
		case SOUND_BOOK5_CH6_DRAGON_DEATH_ID: return "SOUND_BOOK5_CH6_DRAGON_DEATH";
		case SOUND_BOOK5_CH6_DRAGON_PAIN_ID: return "SOUND_BOOK5_CH6_DRAGON_PAIN";
		case SOUND_BOOK5_CH6_DRAGON_ROAR_ID: return "SOUND_BOOK5_CH6_DRAGON_ROAR";
		case SOUND_BOOK5_CH6_WET_IMPACT1_ID: return "SOUND_BOOK5_CH6_WET_IMPACT1";
		case SOUND_BOOK5_CH6_WET_IMPACT2_ID: return "SOUND_BOOK5_CH6_WET_IMPACT2";
		case SOUND_BOOK5_CH6_MISC_IMPACT_ID: return "SOUND_BOOK5_CH6_MISC_IMPACT";
		case SOUND_BOOK5_CH6_MISC_IMPACT2_ID: return "SOUND_BOOK5_CH6_MISC_IMPACT2";
		case SOUND_BOOK5_CH6_SLUMP_SMALL_ID: return "SOUND_BOOK5_CH6_SLUMP_SMALL";
		case SOUND_BOOK5_CH6_SWORD_IMPACT3_ID: return "SOUND_BOOK5_CH6_SWORD_IMPACT3";
		case SOUND_BOOK5_CH6_SONIC_ATTACK_ID: return "SOUND_BOOK5_CH6_SONIC_ATTACK";
		case SOUND_BOOK5_CH6_BEAR_ROAR_ID: return "SOUND_BOOK5_CH6_BEAR_ROAR";
		case IMAGE_B5A_BG7_ID: return "IMAGE_B5A_BG7";
		case IMAGE_B5A_MONKEYKING_BOSS_BATTLE_ID: return "IMAGE_B5A_MONKEYKING_BOSS_BATTLE";
		case SOUND_BOOK5_CH7_SONIC_ATTACK_ID: return "SOUND_BOOK5_CH7_SONIC_ATTACK";
		case SOUND_BOOK5_CH7_SPARKLE_ATTACK_ID: return "SOUND_BOOK5_CH7_SPARKLE_ATTACK";
		case SOUND_BOOK5_CH7_SMOKE_ATTACK_ID: return "SOUND_BOOK5_CH7_SMOKE_ATTACK";
		case SOUND_BOOK5_CH7_SMOKE_ATTACK2_ID: return "SOUND_BOOK5_CH7_SMOKE_ATTACK2";
		case SOUND_BOOK5_CH7_SMOKE_IMPACT_ID: return "SOUND_BOOK5_CH7_SMOKE_IMPACT";
		case SOUND_BOOK5_CH7_PULSING_ATTACK_ID: return "SOUND_BOOK5_CH7_PULSING_ATTACK";
		case SOUND_BOOK5_CH7_FIRE_1_ID: return "SOUND_BOOK5_CH7_FIRE_1";
		case SOUND_BOOK5_CH7_FIRE_3_ID: return "SOUND_BOOK5_CH7_FIRE_3";
		case SOUND_BOOK5_CH7_FIRE_6_ID: return "SOUND_BOOK5_CH7_FIRE_6";
		case SOUND_BOOK5_CH7_MONKEY_ATTACK_ID: return "SOUND_BOOK5_CH7_MONKEY_ATTACK";
		case SOUND_BOOK5_CH7_MONKEY_ATTACK2_ID: return "SOUND_BOOK5_CH7_MONKEY_ATTACK2";
		case SOUND_BOOK5_CH7_MONKEY_CHALLENGE_ID: return "SOUND_BOOK5_CH7_MONKEY_CHALLENGE";
		case SOUND_BOOK5_CH7_SLICING_ATTACK2_ID: return "SOUND_BOOK5_CH7_SLICING_ATTACK2";
		case SOUND_BOOK5_CH7_MALE_LAUGH_ID: return "SOUND_BOOK5_CH7_MALE_LAUGH";
		case SOUND_BOOK5_CH7_CS_STINGER_ID: return "SOUND_BOOK5_CH7_CS_STINGER";
		case SOUND_BOOK5_CH7_CS_LIGHT_ID: return "SOUND_BOOK5_CH7_CS_LIGHT";
		case IMAGE_B5A_BG8_ID: return "IMAGE_B5A_BG8";
		case SOUND_BOOK5_CH8_MONSTER_ATTACK_ID: return "SOUND_BOOK5_CH8_MONSTER_ATTACK";
		case SOUND_BOOK5_CH8_MONSTER_CHALLENGE_ID: return "SOUND_BOOK5_CH8_MONSTER_CHALLENGE";
		case SOUND_BOOK5_CH8_MONSTER_IMPACT_ID: return "SOUND_BOOK5_CH8_MONSTER_IMPACT";
		case SOUND_BOOK5_CH8_STRING_ATTACK_ID: return "SOUND_BOOK5_CH8_STRING_ATTACK";
		case SOUND_BOOK5_CH8_STRING_ATTACK2_ID: return "SOUND_BOOK5_CH8_STRING_ATTACK2";
		case SOUND_BOOK5_CH8_STRING_DEATH_ID: return "SOUND_BOOK5_CH8_STRING_DEATH";
		case SOUND_BOOK5_CH8_STRING_IMPACT_ID: return "SOUND_BOOK5_CH8_STRING_IMPACT";
		case SOUND_BOOK5_CH8_SQ_MAM_ATTACK_ID: return "SOUND_BOOK5_CH8_SQ_MAM_ATTACK";
		case SOUND_BOOK5_CH8_SKELETON_WARCRY_ID: return "SOUND_BOOK5_CH8_SKELETON_WARCRY";
		case SOUND_BOOK5_CH8_SQ_MAM_DEATH_ID: return "SOUND_BOOK5_CH8_SQ_MAM_DEATH";
		case SOUND_BOOK5_CH8_FIRE_3_ID: return "SOUND_BOOK5_CH8_FIRE_3";
		case SOUND_BOOK5_CH8_FIRE_6_ID: return "SOUND_BOOK5_CH8_FIRE_6";
		case SOUND_BOOK5_CH8_GHOST_WAIL1_ID: return "SOUND_BOOK5_CH8_GHOST_WAIL1";
		case SOUND_BOOK5_CH8_LIGHTNING_ATTACK_ID: return "SOUND_BOOK5_CH8_LIGHTNING_ATTACK";
		case SOUND_BOOK5_CH8_SMOKE_ATTACK2_ID: return "SOUND_BOOK5_CH8_SMOKE_ATTACK2";
		case IMAGE_B5A_BG9_ID: return "IMAGE_B5A_BG9";
		case SOUND_BOOK5_CH9_SMOKE_ATTACK_ID: return "SOUND_BOOK5_CH9_SMOKE_ATTACK";
		case SOUND_BOOK5_CH9_SMOKE_ATTACK2_ID: return "SOUND_BOOK5_CH9_SMOKE_ATTACK2";
		case SOUND_BOOK5_CH9_SMOKE_IMPACT_ID: return "SOUND_BOOK5_CH9_SMOKE_IMPACT";
		case SOUND_BOOK5_CH9_SPARKLE_ATTACK_ID: return "SOUND_BOOK5_CH9_SPARKLE_ATTACK";
		case SOUND_BOOK5_CH9_SWORD_IMPACT_ID: return "SOUND_BOOK5_CH9_SWORD_IMPACT";
		case SOUND_BOOK5_CH9_SWORD_IMPACT2_ID: return "SOUND_BOOK5_CH9_SWORD_IMPACT2";
		case SOUND_BOOK5_CH9_SWORD_IMPACT3_ID: return "SOUND_BOOK5_CH9_SWORD_IMPACT3";
		case SOUND_BOOK5_CH9_SONIC_ATTACK_ID: return "SOUND_BOOK5_CH9_SONIC_ATTACK";
		case IMAGE_B5A_BG10_ID: return "IMAGE_B5A_BG10";
		case SOUND_BOOK5_CH10_STRING_ATTACK_ID: return "SOUND_BOOK5_CH10_STRING_ATTACK";
		case SOUND_BOOK5_CH10_MALE_LOW_ANGER_ID: return "SOUND_BOOK5_CH10_MALE_LOW_ANGER";
		case SOUND_BOOK5_CH10_MALE_LOW_PAIN_ID: return "SOUND_BOOK5_CH10_MALE_LOW_PAIN";
		case SOUND_BOOK5_CH10_MALE_LOW_WARCRY_ID: return "SOUND_BOOK5_CH10_MALE_LOW_WARCRY";
		case SOUND_BOOK5_CH10_SWORD_IMPACT_ID: return "SOUND_BOOK5_CH10_SWORD_IMPACT";
		case SOUND_BOOK5_CH10_SWORD_IMPACT2_ID: return "SOUND_BOOK5_CH10_SWORD_IMPACT2";
		case SOUND_BOOK5_CH10_SWORD_IMPACT3_ID: return "SOUND_BOOK5_CH10_SWORD_IMPACT3";
		case SOUND_BOOK5_CH10_ARROW_SHOT_ID: return "SOUND_BOOK5_CH10_ARROW_SHOT";
		case SOUND_BOOK5_CH10_SONIC_ATTACK_ID: return "SOUND_BOOK5_CH10_SONIC_ATTACK";
		case SOUND_BOOK5_CH10_STRING_ATTACK2_ID: return "SOUND_BOOK5_CH10_STRING_ATTACK2";
		case SOUND_BOOK5_CH10_FIRE_6_ID: return "SOUND_BOOK5_CH10_FIRE_6";
		case SOUND_BOOK5_CH10_DOG_BARK1_ID: return "SOUND_BOOK5_CH10_DOG_BARK1";
		case SOUND_BOOK5_CH10_LIGHTNING_ATTACK_ID: return "SOUND_BOOK5_CH10_LIGHTNING_ATTACK";
		case SOUND_BOOK5_CH10_SMOKE_ATTACK2_ID: return "SOUND_BOOK5_CH10_SMOKE_ATTACK2";
		default: return "";
	}
}

