#include "Book6.h"
#include "SexyAppFramework/ResourceManager.h"

using namespace Sexy;

#pragma warning(disable:4311 4312)

static bool gNeedRecalcVariableToIdMap = false;

bool Sexy::ExtractResourcesByName(ResourceManager *theManager, const char *theName)
{
	if (strcmp(theName,"BOOK6Common")==0) return ExtractBOOK6CommonResources(theManager);
	if (strcmp(theName,"Book6Chapter1")==0) return ExtractBook6Chapter1Resources(theManager);
	if (strcmp(theName,"Book6Chapter10")==0) return ExtractBook6Chapter10Resources(theManager);
	if (strcmp(theName,"Book6Chapter2")==0) return ExtractBook6Chapter2Resources(theManager);
	if (strcmp(theName,"Book6Chapter3")==0) return ExtractBook6Chapter3Resources(theManager);
	if (strcmp(theName,"Book6Chapter4")==0) return ExtractBook6Chapter4Resources(theManager);
	if (strcmp(theName,"Book6Chapter5")==0) return ExtractBook6Chapter5Resources(theManager);
	if (strcmp(theName,"Book6Chapter6")==0) return ExtractBook6Chapter6Resources(theManager);
	if (strcmp(theName,"Book6Chapter7")==0) return ExtractBook6Chapter7Resources(theManager);
	if (strcmp(theName,"Book6Chapter8")==0) return ExtractBook6Chapter8Resources(theManager);
	if (strcmp(theName,"Book6Chapter9")==0) return ExtractBook6Chapter9Resources(theManager);
	if (strcmp(theName,"Book6Init")==0) return ExtractBook6InitResources(theManager);
	return false;
}

Sexy::ResourceId Sexy::GetIdByStringId(const char *theStringId)
{
	typedef std::map<std::string,int> MyMap;
	static MyMap aMap;
	if(aMap.empty())
	{
		for(int i=0; i<RESOURCE_ID_MAX; i++)
			aMap[GetStringIdById(i)] = i;
	}

	MyMap::iterator anItr = aMap.find(theStringId);
	if (anItr == aMap.end())
		return RESOURCE_ID_MAX;
	else
		return (ResourceId) anItr->second;
}

// BOOK6Common Resources
Image* Sexy::IMAGE_B6_LEFT_FACING_ARROW;

bool Sexy::ExtractBOOK6CommonResources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_B6_LEFT_FACING_ARROW = aMgr.GetImageThrow("IMAGE_B6_LEFT_FACING_ARROW");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// Book6Chapter1 Resources
Image* Sexy::IMAGE_B6A_BG1;
Image* Sexy::IMAGE_B6A_SKIFF;
int Sexy::SOUND_BOOK6_CH1_BOVINE_ATTACK1;
int Sexy::SOUND_BOOK6_CH1_EXPLOSION_1;
int Sexy::SOUND_BOOK6_CH1_FELINE_ENGAGE;
int Sexy::SOUND_BOOK6_CH1_FELINE_ROAR;
int Sexy::SOUND_BOOK6_CH1_MONKEY_ATTACK;
int Sexy::SOUND_BOOK6_CH1_ROBOT_ATTACK;
int Sexy::SOUND_BOOK6_CH1_ROBOT_CHALLENGE;
int Sexy::SOUND_BOOK6_CH1_ROBOT_IMPACT;
int Sexy::SOUND_BOOK6_CH1_SCIFI_LASER;
int Sexy::SOUND_BOOK6_CH1_SCIFI_MECH;
int Sexy::SOUND_BOOK6_CH1_SCIFI_MECH2;
int Sexy::SOUND_BOOK6_CH1_SCIFI_TELEPORT;
int Sexy::SOUND_BOOK6_CH1_SMOKE_ATTACK;
int Sexy::SOUND_BOOK6_CH1_SMOKE_ATTACK2;
int Sexy::SOUND_BOOK6_CH1_SMOKE_IMPACT;
int Sexy::SOUND_BOOK6_CH1_SONIC_ATTACK;
int Sexy::SOUND_BOOK6_CH1_SPARKLE_ATTACK;
int Sexy::SOUND_BOOK6_CH1_WET_IMPACT1;

bool Sexy::ExtractBook6Chapter1Resources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_B6A_BG1 = aMgr.GetImageThrow("IMAGE_B6A_BG1");
		IMAGE_B6A_SKIFF = aMgr.GetImageThrow("IMAGE_B6A_SKIFF");
		SOUND_BOOK6_CH1_BOVINE_ATTACK1 = aMgr.GetSoundThrow("SOUND_BOOK6_CH1_BOVINE_ATTACK1");
		SOUND_BOOK6_CH1_EXPLOSION_1 = aMgr.GetSoundThrow("SOUND_BOOK6_CH1_EXPLOSION_1");
		SOUND_BOOK6_CH1_FELINE_ENGAGE = aMgr.GetSoundThrow("SOUND_BOOK6_CH1_FELINE_ENGAGE");
		SOUND_BOOK6_CH1_FELINE_ROAR = aMgr.GetSoundThrow("SOUND_BOOK6_CH1_FELINE_ROAR");
		SOUND_BOOK6_CH1_MONKEY_ATTACK = aMgr.GetSoundThrow("SOUND_BOOK6_CH1_MONKEY_ATTACK");
		SOUND_BOOK6_CH1_ROBOT_ATTACK = aMgr.GetSoundThrow("SOUND_BOOK6_CH1_ROBOT_ATTACK");
		SOUND_BOOK6_CH1_ROBOT_CHALLENGE = aMgr.GetSoundThrow("SOUND_BOOK6_CH1_ROBOT_CHALLENGE");
		SOUND_BOOK6_CH1_ROBOT_IMPACT = aMgr.GetSoundThrow("SOUND_BOOK6_CH1_ROBOT_IMPACT");
		SOUND_BOOK6_CH1_SCIFI_LASER = aMgr.GetSoundThrow("SOUND_BOOK6_CH1_SCIFI_LASER");
		SOUND_BOOK6_CH1_SCIFI_MECH = aMgr.GetSoundThrow("SOUND_BOOK6_CH1_SCIFI_MECH");
		SOUND_BOOK6_CH1_SCIFI_MECH2 = aMgr.GetSoundThrow("SOUND_BOOK6_CH1_SCIFI_MECH2");
		SOUND_BOOK6_CH1_SCIFI_TELEPORT = aMgr.GetSoundThrow("SOUND_BOOK6_CH1_SCIFI_TELEPORT");
		SOUND_BOOK6_CH1_SMOKE_ATTACK = aMgr.GetSoundThrow("SOUND_BOOK6_CH1_SMOKE_ATTACK");
		SOUND_BOOK6_CH1_SMOKE_ATTACK2 = aMgr.GetSoundThrow("SOUND_BOOK6_CH1_SMOKE_ATTACK2");
		SOUND_BOOK6_CH1_SMOKE_IMPACT = aMgr.GetSoundThrow("SOUND_BOOK6_CH1_SMOKE_IMPACT");
		SOUND_BOOK6_CH1_SONIC_ATTACK = aMgr.GetSoundThrow("SOUND_BOOK6_CH1_SONIC_ATTACK");
		SOUND_BOOK6_CH1_SPARKLE_ATTACK = aMgr.GetSoundThrow("SOUND_BOOK6_CH1_SPARKLE_ATTACK");
		SOUND_BOOK6_CH1_WET_IMPACT1 = aMgr.GetSoundThrow("SOUND_BOOK6_CH1_WET_IMPACT1");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// Book6Chapter10 Resources
Image* Sexy::IMAGE_B6A_BG10;
Image* Sexy::IMAGE_B6A_THEMACHINE_BOSS_BATTLE;
int Sexy::SOUND_BOOK6_CH10_BLUNT_IMPACT2;
int Sexy::SOUND_BOOK6_CH10_EXPLOSION_1;
int Sexy::SOUND_BOOK6_CH10_EXPLOSION_3;
int Sexy::SOUND_BOOK6_CH10_FIRE_6;
int Sexy::SOUND_BOOK6_CH10_LIGHTNING_ATTACK;
int Sexy::SOUND_BOOK6_CH10_ROBOT_ATTACK;
int Sexy::SOUND_BOOK6_CH10_ROBOT_CHALLENGE;
int Sexy::SOUND_BOOK6_CH10_ROBOT_IMPACT;
int Sexy::SOUND_BOOK6_CH10_SCIFI_LASER;
int Sexy::SOUND_BOOK6_CH10_SCIFI_MECH;
int Sexy::SOUND_BOOK6_CH10_SCIFI_MECH2;
int Sexy::SOUND_BOOK6_CH10_SCIFI_TELEPORT;
int Sexy::SOUND_BOOK6_CH10_SONIC_ATTACK;
int Sexy::SOUND_BOOK6_CH10_SPARKLE_ATTACK;

bool Sexy::ExtractBook6Chapter10Resources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_B6A_BG10 = aMgr.GetImageThrow("IMAGE_B6A_BG10");
		IMAGE_B6A_THEMACHINE_BOSS_BATTLE = aMgr.GetImageThrow("IMAGE_B6A_THEMACHINE_BOSS_BATTLE");
		SOUND_BOOK6_CH10_BLUNT_IMPACT2 = aMgr.GetSoundThrow("SOUND_BOOK6_CH10_BLUNT_IMPACT2");
		SOUND_BOOK6_CH10_EXPLOSION_1 = aMgr.GetSoundThrow("SOUND_BOOK6_CH10_EXPLOSION_1");
		SOUND_BOOK6_CH10_EXPLOSION_3 = aMgr.GetSoundThrow("SOUND_BOOK6_CH10_EXPLOSION_3");
		SOUND_BOOK6_CH10_FIRE_6 = aMgr.GetSoundThrow("SOUND_BOOK6_CH10_FIRE_6");
		SOUND_BOOK6_CH10_LIGHTNING_ATTACK = aMgr.GetSoundThrow("SOUND_BOOK6_CH10_LIGHTNING_ATTACK");
		SOUND_BOOK6_CH10_ROBOT_ATTACK = aMgr.GetSoundThrow("SOUND_BOOK6_CH10_ROBOT_ATTACK");
		SOUND_BOOK6_CH10_ROBOT_CHALLENGE = aMgr.GetSoundThrow("SOUND_BOOK6_CH10_ROBOT_CHALLENGE");
		SOUND_BOOK6_CH10_ROBOT_IMPACT = aMgr.GetSoundThrow("SOUND_BOOK6_CH10_ROBOT_IMPACT");
		SOUND_BOOK6_CH10_SCIFI_LASER = aMgr.GetSoundThrow("SOUND_BOOK6_CH10_SCIFI_LASER");
		SOUND_BOOK6_CH10_SCIFI_MECH = aMgr.GetSoundThrow("SOUND_BOOK6_CH10_SCIFI_MECH");
		SOUND_BOOK6_CH10_SCIFI_MECH2 = aMgr.GetSoundThrow("SOUND_BOOK6_CH10_SCIFI_MECH2");
		SOUND_BOOK6_CH10_SCIFI_TELEPORT = aMgr.GetSoundThrow("SOUND_BOOK6_CH10_SCIFI_TELEPORT");
		SOUND_BOOK6_CH10_SONIC_ATTACK = aMgr.GetSoundThrow("SOUND_BOOK6_CH10_SONIC_ATTACK");
		SOUND_BOOK6_CH10_SPARKLE_ATTACK = aMgr.GetSoundThrow("SOUND_BOOK6_CH10_SPARKLE_ATTACK");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// Book6Chapter2 Resources
Image* Sexy::IMAGE_B6A_BG2;
int Sexy::SOUND_BOOK6_CH2_DOPEY_ATTACK;
int Sexy::SOUND_BOOK6_CH2_DOPEY_IMPACT;
int Sexy::SOUND_BOOK6_CH2_EXPLOSION_3;
int Sexy::SOUND_BOOK6_CH2_MALE_LOW_ANGER;
int Sexy::SOUND_BOOK6_CH2_MISC_IMPACT;
int Sexy::SOUND_BOOK6_CH2_MONKEY_ATTACK;
int Sexy::SOUND_BOOK6_CH2_MONKEY_ATTACK2;
int Sexy::SOUND_BOOK6_CH2_MONKEY_CHALLENGE;
int Sexy::SOUND_BOOK6_CH2_OGRE_ATTACK;
int Sexy::SOUND_BOOK6_CH2_OGRE_ATTACK2;
int Sexy::SOUND_BOOK6_CH2_OGRE_CHALLENGE;
int Sexy::SOUND_BOOK6_CH2_OGRE_CHALLENGE2;
int Sexy::SOUND_BOOK6_CH2_OGRE_IMPACT;
int Sexy::SOUND_BOOK6_CH2_OGRE_IMPACT2;
int Sexy::SOUND_BOOK6_CH2_OGRE_IMPACT3;
int Sexy::SOUND_BOOK6_CH2_SCIFI_LASER;
int Sexy::SOUND_BOOK6_CH2_WET_IMPACT1;
int Sexy::SOUND_BOOK6_CH2_WET_IMPACT2;

bool Sexy::ExtractBook6Chapter2Resources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_B6A_BG2 = aMgr.GetImageThrow("IMAGE_B6A_BG2");
		SOUND_BOOK6_CH2_DOPEY_ATTACK = aMgr.GetSoundThrow("SOUND_BOOK6_CH2_DOPEY_ATTACK");
		SOUND_BOOK6_CH2_DOPEY_IMPACT = aMgr.GetSoundThrow("SOUND_BOOK6_CH2_DOPEY_IMPACT");
		SOUND_BOOK6_CH2_EXPLOSION_3 = aMgr.GetSoundThrow("SOUND_BOOK6_CH2_EXPLOSION_3");
		SOUND_BOOK6_CH2_MALE_LOW_ANGER = aMgr.GetSoundThrow("SOUND_BOOK6_CH2_MALE_LOW_ANGER");
		SOUND_BOOK6_CH2_MISC_IMPACT = aMgr.GetSoundThrow("SOUND_BOOK6_CH2_MISC_IMPACT");
		SOUND_BOOK6_CH2_MONKEY_ATTACK = aMgr.GetSoundThrow("SOUND_BOOK6_CH2_MONKEY_ATTACK");
		SOUND_BOOK6_CH2_MONKEY_ATTACK2 = aMgr.GetSoundThrow("SOUND_BOOK6_CH2_MONKEY_ATTACK2");
		SOUND_BOOK6_CH2_MONKEY_CHALLENGE = aMgr.GetSoundThrow("SOUND_BOOK6_CH2_MONKEY_CHALLENGE");
		SOUND_BOOK6_CH2_OGRE_ATTACK = aMgr.GetSoundThrow("SOUND_BOOK6_CH2_OGRE_ATTACK");
		SOUND_BOOK6_CH2_OGRE_ATTACK2 = aMgr.GetSoundThrow("SOUND_BOOK6_CH2_OGRE_ATTACK2");
		SOUND_BOOK6_CH2_OGRE_CHALLENGE = aMgr.GetSoundThrow("SOUND_BOOK6_CH2_OGRE_CHALLENGE");
		SOUND_BOOK6_CH2_OGRE_CHALLENGE2 = aMgr.GetSoundThrow("SOUND_BOOK6_CH2_OGRE_CHALLENGE2");
		SOUND_BOOK6_CH2_OGRE_IMPACT = aMgr.GetSoundThrow("SOUND_BOOK6_CH2_OGRE_IMPACT");
		SOUND_BOOK6_CH2_OGRE_IMPACT2 = aMgr.GetSoundThrow("SOUND_BOOK6_CH2_OGRE_IMPACT2");
		SOUND_BOOK6_CH2_OGRE_IMPACT3 = aMgr.GetSoundThrow("SOUND_BOOK6_CH2_OGRE_IMPACT3");
		SOUND_BOOK6_CH2_SCIFI_LASER = aMgr.GetSoundThrow("SOUND_BOOK6_CH2_SCIFI_LASER");
		SOUND_BOOK6_CH2_WET_IMPACT1 = aMgr.GetSoundThrow("SOUND_BOOK6_CH2_WET_IMPACT1");
		SOUND_BOOK6_CH2_WET_IMPACT2 = aMgr.GetSoundThrow("SOUND_BOOK6_CH2_WET_IMPACT2");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// Book6Chapter3 Resources
Image* Sexy::IMAGE_B6A_BG3;
int Sexy::SOUND_BOOK6_CH3_CS_SHACKLE;
int Sexy::SOUND_BOOK6_CH3_DOPEY_ATTACK;
int Sexy::SOUND_BOOK6_CH3_DOPEY_IMPACT;
int Sexy::SOUND_BOOK6_CH3_MALE_ANGER;
int Sexy::SOUND_BOOK6_CH3_MALE_LOW_ANGER;
int Sexy::SOUND_BOOK6_CH3_MALE_PAIN;
int Sexy::SOUND_BOOK6_CH3_OGRE_ATTACK;
int Sexy::SOUND_BOOK6_CH3_OGRE_ATTACK2;
int Sexy::SOUND_BOOK6_CH3_OGRE_CHALLENGE;
int Sexy::SOUND_BOOK6_CH3_OGRE_CHALLENGE2;
int Sexy::SOUND_BOOK6_CH3_OGRE_IMPACT;
int Sexy::SOUND_BOOK6_CH3_OGRE_IMPACT2;
int Sexy::SOUND_BOOK6_CH3_OGRE_IMPACT3;
int Sexy::SOUND_BOOK6_CH3_PIG_ATTACK;
int Sexy::SOUND_BOOK6_CH3_PIG_SQUEAL2;

bool Sexy::ExtractBook6Chapter3Resources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_B6A_BG3 = aMgr.GetImageThrow("IMAGE_B6A_BG3");
		SOUND_BOOK6_CH3_CS_SHACKLE = aMgr.GetSoundThrow("SOUND_BOOK6_CH3_CS_SHACKLE");
		SOUND_BOOK6_CH3_DOPEY_ATTACK = aMgr.GetSoundThrow("SOUND_BOOK6_CH3_DOPEY_ATTACK");
		SOUND_BOOK6_CH3_DOPEY_IMPACT = aMgr.GetSoundThrow("SOUND_BOOK6_CH3_DOPEY_IMPACT");
		SOUND_BOOK6_CH3_MALE_ANGER = aMgr.GetSoundThrow("SOUND_BOOK6_CH3_MALE_ANGER");
		SOUND_BOOK6_CH3_MALE_LOW_ANGER = aMgr.GetSoundThrow("SOUND_BOOK6_CH3_MALE_LOW_ANGER");
		SOUND_BOOK6_CH3_MALE_PAIN = aMgr.GetSoundThrow("SOUND_BOOK6_CH3_MALE_PAIN");
		SOUND_BOOK6_CH3_OGRE_ATTACK = aMgr.GetSoundThrow("SOUND_BOOK6_CH3_OGRE_ATTACK");
		SOUND_BOOK6_CH3_OGRE_ATTACK2 = aMgr.GetSoundThrow("SOUND_BOOK6_CH3_OGRE_ATTACK2");
		SOUND_BOOK6_CH3_OGRE_CHALLENGE = aMgr.GetSoundThrow("SOUND_BOOK6_CH3_OGRE_CHALLENGE");
		SOUND_BOOK6_CH3_OGRE_CHALLENGE2 = aMgr.GetSoundThrow("SOUND_BOOK6_CH3_OGRE_CHALLENGE2");
		SOUND_BOOK6_CH3_OGRE_IMPACT = aMgr.GetSoundThrow("SOUND_BOOK6_CH3_OGRE_IMPACT");
		SOUND_BOOK6_CH3_OGRE_IMPACT2 = aMgr.GetSoundThrow("SOUND_BOOK6_CH3_OGRE_IMPACT2");
		SOUND_BOOK6_CH3_OGRE_IMPACT3 = aMgr.GetSoundThrow("SOUND_BOOK6_CH3_OGRE_IMPACT3");
		SOUND_BOOK6_CH3_PIG_ATTACK = aMgr.GetSoundThrow("SOUND_BOOK6_CH3_PIG_ATTACK");
		SOUND_BOOK6_CH3_PIG_SQUEAL2 = aMgr.GetSoundThrow("SOUND_BOOK6_CH3_PIG_SQUEAL2");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// Book6Chapter4 Resources
Image* Sexy::IMAGE_B6A_BG4;
int Sexy::SOUND_BOOK6_CH4_DRAGON_ROAR;
int Sexy::SOUND_BOOK6_CH4_FEMALE_GROAN1;
int Sexy::SOUND_BOOK6_CH4_FEMALE_GROAN2;
int Sexy::SOUND_BOOK6_CH4_FEMALE_SEDUCE;
int Sexy::SOUND_BOOK6_CH4_PLATE_ATTACK2;
int Sexy::SOUND_BOOK6_CH4_ROBOT_ATTACK;
int Sexy::SOUND_BOOK6_CH4_ROBOT_CHALLENGE;
int Sexy::SOUND_BOOK6_CH4_ROBOT_IMPACT;
int Sexy::SOUND_BOOK6_CH4_SCIFI_LASER;
int Sexy::SOUND_BOOK6_CH4_SCIFI_MECH;
int Sexy::SOUND_BOOK6_CH4_SCIFI_MECH2;
int Sexy::SOUND_BOOK6_CH4_SCIFI_TELEPORT;
int Sexy::SOUND_BOOK6_CH4_SHEEP_BLEAT;
int Sexy::SOUND_BOOK6_CH4_SLICING_ATTACK;
int Sexy::SOUND_BOOK6_CH4_SMOKE_ATTACK;
int Sexy::SOUND_BOOK6_CH4_SONIC_ATTACK;
int Sexy::SOUND_BOOK6_CH4_SWORD_IMPACT3;

bool Sexy::ExtractBook6Chapter4Resources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_B6A_BG4 = aMgr.GetImageThrow("IMAGE_B6A_BG4");
		SOUND_BOOK6_CH4_DRAGON_ROAR = aMgr.GetSoundThrow("SOUND_BOOK6_CH4_DRAGON_ROAR");
		SOUND_BOOK6_CH4_FEMALE_GROAN1 = aMgr.GetSoundThrow("SOUND_BOOK6_CH4_FEMALE_GROAN1");
		SOUND_BOOK6_CH4_FEMALE_GROAN2 = aMgr.GetSoundThrow("SOUND_BOOK6_CH4_FEMALE_GROAN2");
		SOUND_BOOK6_CH4_FEMALE_SEDUCE = aMgr.GetSoundThrow("SOUND_BOOK6_CH4_FEMALE_SEDUCE");
		SOUND_BOOK6_CH4_PLATE_ATTACK2 = aMgr.GetSoundThrow("SOUND_BOOK6_CH4_PLATE_ATTACK2");
		SOUND_BOOK6_CH4_ROBOT_ATTACK = aMgr.GetSoundThrow("SOUND_BOOK6_CH4_ROBOT_ATTACK");
		SOUND_BOOK6_CH4_ROBOT_CHALLENGE = aMgr.GetSoundThrow("SOUND_BOOK6_CH4_ROBOT_CHALLENGE");
		SOUND_BOOK6_CH4_ROBOT_IMPACT = aMgr.GetSoundThrow("SOUND_BOOK6_CH4_ROBOT_IMPACT");
		SOUND_BOOK6_CH4_SCIFI_LASER = aMgr.GetSoundThrow("SOUND_BOOK6_CH4_SCIFI_LASER");
		SOUND_BOOK6_CH4_SCIFI_MECH = aMgr.GetSoundThrow("SOUND_BOOK6_CH4_SCIFI_MECH");
		SOUND_BOOK6_CH4_SCIFI_MECH2 = aMgr.GetSoundThrow("SOUND_BOOK6_CH4_SCIFI_MECH2");
		SOUND_BOOK6_CH4_SCIFI_TELEPORT = aMgr.GetSoundThrow("SOUND_BOOK6_CH4_SCIFI_TELEPORT");
		SOUND_BOOK6_CH4_SHEEP_BLEAT = aMgr.GetSoundThrow("SOUND_BOOK6_CH4_SHEEP_BLEAT");
		SOUND_BOOK6_CH4_SLICING_ATTACK = aMgr.GetSoundThrow("SOUND_BOOK6_CH4_SLICING_ATTACK");
		SOUND_BOOK6_CH4_SMOKE_ATTACK = aMgr.GetSoundThrow("SOUND_BOOK6_CH4_SMOKE_ATTACK");
		SOUND_BOOK6_CH4_SONIC_ATTACK = aMgr.GetSoundThrow("SOUND_BOOK6_CH4_SONIC_ATTACK");
		SOUND_BOOK6_CH4_SWORD_IMPACT3 = aMgr.GetSoundThrow("SOUND_BOOK6_CH4_SWORD_IMPACT3");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// Book6Chapter5 Resources
Image* Sexy::IMAGE_B6A_BG5;
int Sexy::SOUND_BOOK6_CH5_ARROW_SHOT;
int Sexy::SOUND_BOOK6_CH5_BEAR_ROAR;
int Sexy::SOUND_BOOK6_CH5_FEMALE_GROAN1;
int Sexy::SOUND_BOOK6_CH5_FEMALE_GROAN2;
int Sexy::SOUND_BOOK6_CH5_LIGHTNING_ATTACK;
int Sexy::SOUND_BOOK6_CH5_MALE_ANGER;
int Sexy::SOUND_BOOK6_CH5_MALE_LAUGH;
int Sexy::SOUND_BOOK6_CH5_MALE_LAUGH2;
int Sexy::SOUND_BOOK6_CH5_MALE_PAIN;
int Sexy::SOUND_BOOK6_CH5_MISC_IMPACT;
int Sexy::SOUND_BOOK6_CH5_MISC_IMPACT2;
int Sexy::SOUND_BOOK6_CH5_SWORD_IMPACT3;
int Sexy::SOUND_BOOK6_CH5_WET_IMPACT1;
int Sexy::SOUND_BOOK6_CH5_WET_IMPACT2;

bool Sexy::ExtractBook6Chapter5Resources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_B6A_BG5 = aMgr.GetImageThrow("IMAGE_B6A_BG5");
		SOUND_BOOK6_CH5_ARROW_SHOT = aMgr.GetSoundThrow("SOUND_BOOK6_CH5_ARROW_SHOT");
		SOUND_BOOK6_CH5_BEAR_ROAR = aMgr.GetSoundThrow("SOUND_BOOK6_CH5_BEAR_ROAR");
		SOUND_BOOK6_CH5_FEMALE_GROAN1 = aMgr.GetSoundThrow("SOUND_BOOK6_CH5_FEMALE_GROAN1");
		SOUND_BOOK6_CH5_FEMALE_GROAN2 = aMgr.GetSoundThrow("SOUND_BOOK6_CH5_FEMALE_GROAN2");
		SOUND_BOOK6_CH5_LIGHTNING_ATTACK = aMgr.GetSoundThrow("SOUND_BOOK6_CH5_LIGHTNING_ATTACK");
		SOUND_BOOK6_CH5_MALE_ANGER = aMgr.GetSoundThrow("SOUND_BOOK6_CH5_MALE_ANGER");
		SOUND_BOOK6_CH5_MALE_LAUGH = aMgr.GetSoundThrow("SOUND_BOOK6_CH5_MALE_LAUGH");
		SOUND_BOOK6_CH5_MALE_LAUGH2 = aMgr.GetSoundThrow("SOUND_BOOK6_CH5_MALE_LAUGH2");
		SOUND_BOOK6_CH5_MALE_PAIN = aMgr.GetSoundThrow("SOUND_BOOK6_CH5_MALE_PAIN");
		SOUND_BOOK6_CH5_MISC_IMPACT = aMgr.GetSoundThrow("SOUND_BOOK6_CH5_MISC_IMPACT");
		SOUND_BOOK6_CH5_MISC_IMPACT2 = aMgr.GetSoundThrow("SOUND_BOOK6_CH5_MISC_IMPACT2");
		SOUND_BOOK6_CH5_SWORD_IMPACT3 = aMgr.GetSoundThrow("SOUND_BOOK6_CH5_SWORD_IMPACT3");
		SOUND_BOOK6_CH5_WET_IMPACT1 = aMgr.GetSoundThrow("SOUND_BOOK6_CH5_WET_IMPACT1");
		SOUND_BOOK6_CH5_WET_IMPACT2 = aMgr.GetSoundThrow("SOUND_BOOK6_CH5_WET_IMPACT2");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// Book6Chapter6 Resources
Image* Sexy::IMAGE_B6A_BG6;
int Sexy::SOUND_BOOK6_CH6_DRAGON_BITE;
int Sexy::SOUND_BOOK6_CH6_DRAGON_DEATH;
int Sexy::SOUND_BOOK6_CH6_DRAGON_PAIN;
int Sexy::SOUND_BOOK6_CH6_DRAGON_ROAR;
int Sexy::SOUND_BOOK6_CH6_EXPLOSION_3;
int Sexy::SOUND_BOOK6_CH6_LIGHTNING_ATTACK;
int Sexy::SOUND_BOOK6_CH6_MALE_ANGER;
int Sexy::SOUND_BOOK6_CH6_MALE_LAUGH;
int Sexy::SOUND_BOOK6_CH6_MALE_LAUGH2;
int Sexy::SOUND_BOOK6_CH6_MALE_PAIN;
int Sexy::SOUND_BOOK6_CH6_SPARKLE_ATTACK;
int Sexy::SOUND_BOOK6_CH6_SWORD_IMPACT3;

bool Sexy::ExtractBook6Chapter6Resources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_B6A_BG6 = aMgr.GetImageThrow("IMAGE_B6A_BG6");
		SOUND_BOOK6_CH6_DRAGON_BITE = aMgr.GetSoundThrow("SOUND_BOOK6_CH6_DRAGON_BITE");
		SOUND_BOOK6_CH6_DRAGON_DEATH = aMgr.GetSoundThrow("SOUND_BOOK6_CH6_DRAGON_DEATH");
		SOUND_BOOK6_CH6_DRAGON_PAIN = aMgr.GetSoundThrow("SOUND_BOOK6_CH6_DRAGON_PAIN");
		SOUND_BOOK6_CH6_DRAGON_ROAR = aMgr.GetSoundThrow("SOUND_BOOK6_CH6_DRAGON_ROAR");
		SOUND_BOOK6_CH6_EXPLOSION_3 = aMgr.GetSoundThrow("SOUND_BOOK6_CH6_EXPLOSION_3");
		SOUND_BOOK6_CH6_LIGHTNING_ATTACK = aMgr.GetSoundThrow("SOUND_BOOK6_CH6_LIGHTNING_ATTACK");
		SOUND_BOOK6_CH6_MALE_ANGER = aMgr.GetSoundThrow("SOUND_BOOK6_CH6_MALE_ANGER");
		SOUND_BOOK6_CH6_MALE_LAUGH = aMgr.GetSoundThrow("SOUND_BOOK6_CH6_MALE_LAUGH");
		SOUND_BOOK6_CH6_MALE_LAUGH2 = aMgr.GetSoundThrow("SOUND_BOOK6_CH6_MALE_LAUGH2");
		SOUND_BOOK6_CH6_MALE_PAIN = aMgr.GetSoundThrow("SOUND_BOOK6_CH6_MALE_PAIN");
		SOUND_BOOK6_CH6_SPARKLE_ATTACK = aMgr.GetSoundThrow("SOUND_BOOK6_CH6_SPARKLE_ATTACK");
		SOUND_BOOK6_CH6_SWORD_IMPACT3 = aMgr.GetSoundThrow("SOUND_BOOK6_CH6_SWORD_IMPACT3");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// Book6Chapter7 Resources
Image* Sexy::IMAGE_B6A_BG7;
Image* Sexy::IMAGE_B6A_DANCEBATTLE_BOSS_BATTLE;
int Sexy::SOUND_BOOK6_CH7_CS_SKULL;
int Sexy::SOUND_BOOK6_CH7_DANCE_CAMERA;
int Sexy::SOUND_BOOK6_CH7_DANCE_CHEER;
int Sexy::SOUND_BOOK6_CH7_DANCE_DEATH;
int Sexy::SOUND_BOOK6_CH7_DANCE_E;
int Sexy::SOUND_BOOK6_CH7_DANCE_ENGAGE;
int Sexy::SOUND_BOOK6_CH7_DANCE_L;
int Sexy::SOUND_BOOK6_CH7_DANCE_LEX;
int Sexy::SOUND_BOOK6_CH7_DANCE_X;
int Sexy::SOUND_BOOK6_CH7_SOUND1;
int Sexy::SOUND_BOOK6_CH7_SOUND2;
int Sexy::SOUND_BOOK6_CH7_SOUND3;
int Sexy::SOUND_BOOK6_CH7_SOUND4;
int Sexy::SOUND_BOOK6_CH7_SOUND5;
int Sexy::SOUND_BOOK6_CH7_SOUND6;
int Sexy::SOUND_BOOK6_CH7_SOUND7;
int Sexy::SOUND_BOOK6_CH7_SOUND8;
int Sexy::SOUND_BOOK6_CH7_SOUND9;

bool Sexy::ExtractBook6Chapter7Resources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_B6A_BG7 = aMgr.GetImageThrow("IMAGE_B6A_BG7");
		IMAGE_B6A_DANCEBATTLE_BOSS_BATTLE = aMgr.GetImageThrow("IMAGE_B6A_DANCEBATTLE_BOSS_BATTLE");
		SOUND_BOOK6_CH7_CS_SKULL = aMgr.GetSoundThrow("SOUND_BOOK6_CH7_CS_SKULL");
		SOUND_BOOK6_CH7_DANCE_CAMERA = aMgr.GetSoundThrow("SOUND_BOOK6_CH7_DANCE_CAMERA");
		SOUND_BOOK6_CH7_DANCE_CHEER = aMgr.GetSoundThrow("SOUND_BOOK6_CH7_DANCE_CHEER");
		SOUND_BOOK6_CH7_DANCE_DEATH = aMgr.GetSoundThrow("SOUND_BOOK6_CH7_DANCE_DEATH");
		SOUND_BOOK6_CH7_DANCE_E = aMgr.GetSoundThrow("SOUND_BOOK6_CH7_DANCE_E");
		SOUND_BOOK6_CH7_DANCE_ENGAGE = aMgr.GetSoundThrow("SOUND_BOOK6_CH7_DANCE_ENGAGE");
		SOUND_BOOK6_CH7_DANCE_L = aMgr.GetSoundThrow("SOUND_BOOK6_CH7_DANCE_L");
		SOUND_BOOK6_CH7_DANCE_LEX = aMgr.GetSoundThrow("SOUND_BOOK6_CH7_DANCE_LEX");
		SOUND_BOOK6_CH7_DANCE_X = aMgr.GetSoundThrow("SOUND_BOOK6_CH7_DANCE_X");
		SOUND_BOOK6_CH7_SOUND1 = aMgr.GetSoundThrow("SOUND_BOOK6_CH7_SOUND1");
		SOUND_BOOK6_CH7_SOUND2 = aMgr.GetSoundThrow("SOUND_BOOK6_CH7_SOUND2");
		SOUND_BOOK6_CH7_SOUND3 = aMgr.GetSoundThrow("SOUND_BOOK6_CH7_SOUND3");
		SOUND_BOOK6_CH7_SOUND4 = aMgr.GetSoundThrow("SOUND_BOOK6_CH7_SOUND4");
		SOUND_BOOK6_CH7_SOUND5 = aMgr.GetSoundThrow("SOUND_BOOK6_CH7_SOUND5");
		SOUND_BOOK6_CH7_SOUND6 = aMgr.GetSoundThrow("SOUND_BOOK6_CH7_SOUND6");
		SOUND_BOOK6_CH7_SOUND7 = aMgr.GetSoundThrow("SOUND_BOOK6_CH7_SOUND7");
		SOUND_BOOK6_CH7_SOUND8 = aMgr.GetSoundThrow("SOUND_BOOK6_CH7_SOUND8");
		SOUND_BOOK6_CH7_SOUND9 = aMgr.GetSoundThrow("SOUND_BOOK6_CH7_SOUND9");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// Book6Chapter8 Resources
Image* Sexy::IMAGE_B6A_BG8;
int Sexy::SOUND_BOOK6_CH8_DOPEY_ATTACK;
int Sexy::SOUND_BOOK6_CH8_DOPEY_IMPACT;
int Sexy::SOUND_BOOK6_CH8_FEMALE_GROAN2;
int Sexy::SOUND_BOOK6_CH8_FEMALE_OOOH;
int Sexy::SOUND_BOOK6_CH8_FEMALE_SEDUCE;
int Sexy::SOUND_BOOK6_CH8_LIGHTNING_ATTACK;
int Sexy::SOUND_BOOK6_CH8_MALE_GRUNT1;
int Sexy::SOUND_BOOK6_CH8_MALE_LAUGH2;
int Sexy::SOUND_BOOK6_CH8_SCIFI_LASER;
int Sexy::SOUND_BOOK6_CH8_SCIFI_MECH;
int Sexy::SOUND_BOOK6_CH8_SCIFI_MECH2;
int Sexy::SOUND_BOOK6_CH8_SCIFI_TELEPORT;
int Sexy::SOUND_BOOK6_CH8_SMOKE_ATTACK;
int Sexy::SOUND_BOOK6_CH8_SMOKE_ATTACK2;
int Sexy::SOUND_BOOK6_CH8_SMOKE_IMPACT;
int Sexy::SOUND_BOOK6_CH8_SONIC_ATTACK;
int Sexy::SOUND_BOOK6_CH8_SPARKLE_ATTACK;

bool Sexy::ExtractBook6Chapter8Resources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_B6A_BG8 = aMgr.GetImageThrow("IMAGE_B6A_BG8");
		SOUND_BOOK6_CH8_DOPEY_ATTACK = aMgr.GetSoundThrow("SOUND_BOOK6_CH8_DOPEY_ATTACK");
		SOUND_BOOK6_CH8_DOPEY_IMPACT = aMgr.GetSoundThrow("SOUND_BOOK6_CH8_DOPEY_IMPACT");
		SOUND_BOOK6_CH8_FEMALE_GROAN2 = aMgr.GetSoundThrow("SOUND_BOOK6_CH8_FEMALE_GROAN2");
		SOUND_BOOK6_CH8_FEMALE_OOOH = aMgr.GetSoundThrow("SOUND_BOOK6_CH8_FEMALE_OOOH");
		SOUND_BOOK6_CH8_FEMALE_SEDUCE = aMgr.GetSoundThrow("SOUND_BOOK6_CH8_FEMALE_SEDUCE");
		SOUND_BOOK6_CH8_LIGHTNING_ATTACK = aMgr.GetSoundThrow("SOUND_BOOK6_CH8_LIGHTNING_ATTACK");
		SOUND_BOOK6_CH8_MALE_GRUNT1 = aMgr.GetSoundThrow("SOUND_BOOK6_CH8_MALE_GRUNT1");
		SOUND_BOOK6_CH8_MALE_LAUGH2 = aMgr.GetSoundThrow("SOUND_BOOK6_CH8_MALE_LAUGH2");
		SOUND_BOOK6_CH8_SCIFI_LASER = aMgr.GetSoundThrow("SOUND_BOOK6_CH8_SCIFI_LASER");
		SOUND_BOOK6_CH8_SCIFI_MECH = aMgr.GetSoundThrow("SOUND_BOOK6_CH8_SCIFI_MECH");
		SOUND_BOOK6_CH8_SCIFI_MECH2 = aMgr.GetSoundThrow("SOUND_BOOK6_CH8_SCIFI_MECH2");
		SOUND_BOOK6_CH8_SCIFI_TELEPORT = aMgr.GetSoundThrow("SOUND_BOOK6_CH8_SCIFI_TELEPORT");
		SOUND_BOOK6_CH8_SMOKE_ATTACK = aMgr.GetSoundThrow("SOUND_BOOK6_CH8_SMOKE_ATTACK");
		SOUND_BOOK6_CH8_SMOKE_ATTACK2 = aMgr.GetSoundThrow("SOUND_BOOK6_CH8_SMOKE_ATTACK2");
		SOUND_BOOK6_CH8_SMOKE_IMPACT = aMgr.GetSoundThrow("SOUND_BOOK6_CH8_SMOKE_IMPACT");
		SOUND_BOOK6_CH8_SONIC_ATTACK = aMgr.GetSoundThrow("SOUND_BOOK6_CH8_SONIC_ATTACK");
		SOUND_BOOK6_CH8_SPARKLE_ATTACK = aMgr.GetSoundThrow("SOUND_BOOK6_CH8_SPARKLE_ATTACK");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// Book6Chapter9 Resources
Image* Sexy::IMAGE_B6A_BG9;
int Sexy::SOUND_BOOK6_CH9_BLUNT_IMPACT2;
int Sexy::SOUND_BOOK6_CH9_DOG_BARK2;
int Sexy::SOUND_BOOK6_CH9_EXPLOSION_1;
int Sexy::SOUND_BOOK6_CH9_FIRE_6;
int Sexy::SOUND_BOOK6_CH9_LIGHTNING_ATTACK;
int Sexy::SOUND_BOOK6_CH9_MALE_ANGER;
int Sexy::SOUND_BOOK6_CH9_MALE_LAUGH;
int Sexy::SOUND_BOOK6_CH9_MALE_LAUGH2;
int Sexy::SOUND_BOOK6_CH9_MALE_LOW_ANGER;
int Sexy::SOUND_BOOK6_CH9_MALE_LOW_PAIN;
int Sexy::SOUND_BOOK6_CH9_MALE_LOW_WARCRY;
int Sexy::SOUND_BOOK6_CH9_MALE_PAIN;
int Sexy::SOUND_BOOK6_CH9_ROBOT_ATTACK;
int Sexy::SOUND_BOOK6_CH9_ROBOT_CHALLENGE;
int Sexy::SOUND_BOOK6_CH9_ROBOT_IMPACT;
int Sexy::SOUND_BOOK6_CH9_SCIFI_LASER;
int Sexy::SOUND_BOOK6_CH9_SCIFI_MECH;
int Sexy::SOUND_BOOK6_CH9_SCIFI_MECH2;
int Sexy::SOUND_BOOK6_CH9_SCIFI_TELEPORT;
int Sexy::SOUND_BOOK6_CH9_SONIC_ATTACK;
int Sexy::SOUND_BOOK6_CH9_SPARKLE_ATTACK;

bool Sexy::ExtractBook6Chapter9Resources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_B6A_BG9 = aMgr.GetImageThrow("IMAGE_B6A_BG9");
		SOUND_BOOK6_CH9_BLUNT_IMPACT2 = aMgr.GetSoundThrow("SOUND_BOOK6_CH9_BLUNT_IMPACT2");
		SOUND_BOOK6_CH9_DOG_BARK2 = aMgr.GetSoundThrow("SOUND_BOOK6_CH9_DOG_BARK2");
		SOUND_BOOK6_CH9_EXPLOSION_1 = aMgr.GetSoundThrow("SOUND_BOOK6_CH9_EXPLOSION_1");
		SOUND_BOOK6_CH9_FIRE_6 = aMgr.GetSoundThrow("SOUND_BOOK6_CH9_FIRE_6");
		SOUND_BOOK6_CH9_LIGHTNING_ATTACK = aMgr.GetSoundThrow("SOUND_BOOK6_CH9_LIGHTNING_ATTACK");
		SOUND_BOOK6_CH9_MALE_ANGER = aMgr.GetSoundThrow("SOUND_BOOK6_CH9_MALE_ANGER");
		SOUND_BOOK6_CH9_MALE_LAUGH = aMgr.GetSoundThrow("SOUND_BOOK6_CH9_MALE_LAUGH");
		SOUND_BOOK6_CH9_MALE_LAUGH2 = aMgr.GetSoundThrow("SOUND_BOOK6_CH9_MALE_LAUGH2");
		SOUND_BOOK6_CH9_MALE_LOW_ANGER = aMgr.GetSoundThrow("SOUND_BOOK6_CH9_MALE_LOW_ANGER");
		SOUND_BOOK6_CH9_MALE_LOW_PAIN = aMgr.GetSoundThrow("SOUND_BOOK6_CH9_MALE_LOW_PAIN");
		SOUND_BOOK6_CH9_MALE_LOW_WARCRY = aMgr.GetSoundThrow("SOUND_BOOK6_CH9_MALE_LOW_WARCRY");
		SOUND_BOOK6_CH9_MALE_PAIN = aMgr.GetSoundThrow("SOUND_BOOK6_CH9_MALE_PAIN");
		SOUND_BOOK6_CH9_ROBOT_ATTACK = aMgr.GetSoundThrow("SOUND_BOOK6_CH9_ROBOT_ATTACK");
		SOUND_BOOK6_CH9_ROBOT_CHALLENGE = aMgr.GetSoundThrow("SOUND_BOOK6_CH9_ROBOT_CHALLENGE");
		SOUND_BOOK6_CH9_ROBOT_IMPACT = aMgr.GetSoundThrow("SOUND_BOOK6_CH9_ROBOT_IMPACT");
		SOUND_BOOK6_CH9_SCIFI_LASER = aMgr.GetSoundThrow("SOUND_BOOK6_CH9_SCIFI_LASER");
		SOUND_BOOK6_CH9_SCIFI_MECH = aMgr.GetSoundThrow("SOUND_BOOK6_CH9_SCIFI_MECH");
		SOUND_BOOK6_CH9_SCIFI_MECH2 = aMgr.GetSoundThrow("SOUND_BOOK6_CH9_SCIFI_MECH2");
		SOUND_BOOK6_CH9_SCIFI_TELEPORT = aMgr.GetSoundThrow("SOUND_BOOK6_CH9_SCIFI_TELEPORT");
		SOUND_BOOK6_CH9_SONIC_ATTACK = aMgr.GetSoundThrow("SOUND_BOOK6_CH9_SONIC_ATTACK");
		SOUND_BOOK6_CH9_SPARKLE_ATTACK = aMgr.GetSoundThrow("SOUND_BOOK6_CH9_SPARKLE_ATTACK");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// Book6Init Resources
Image* Sexy::IMAGE_B6_ICONANIM1;
Image* Sexy::IMAGE_B6_ICONANIM10;
Image* Sexy::IMAGE_B6_ICONANIM2;
Image* Sexy::IMAGE_B6_ICONANIM3;
Image* Sexy::IMAGE_B6_ICONANIM4;
Image* Sexy::IMAGE_B6_ICONANIM5;
Image* Sexy::IMAGE_B6_ICONANIM6;
Image* Sexy::IMAGE_B6_ICONANIM7;
Image* Sexy::IMAGE_B6_ICONANIM8;
Image* Sexy::IMAGE_B6_ICONANIM9;
Image* Sexy::IMAGE_B6_ICONMASK1;
Image* Sexy::IMAGE_B6_ICONMASK10;
Image* Sexy::IMAGE_B6_ICONMASK2;
Image* Sexy::IMAGE_B6_ICONMASK3;
Image* Sexy::IMAGE_B6_ICONMASK4;
Image* Sexy::IMAGE_B6_ICONMASK5;
Image* Sexy::IMAGE_B6_ICONMASK6;
Image* Sexy::IMAGE_B6_ICONMASK7;
Image* Sexy::IMAGE_B6_ICONMASK8;
Image* Sexy::IMAGE_B6_ICONMASK9;
Image* Sexy::IMAGE_B6_MAP;
Image* Sexy::IMAGE_B6_MAPSCREEN_BANNER;
Image* Sexy::IMAGE_B6_MINIMAP_ICONS;
Image* Sexy::IMAGE_TUT_PIC_BIGBROTHER;
Image* Sexy::IMAGE_TUT_PIC_MAGICPEN;
Image* Sexy::IMAGE_TUT_PIC_PREV_LEX;
Image* Sexy::IMAGE_TUT_PIC_SKELETROX;

bool Sexy::ExtractBook6InitResources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_B6_ICONANIM1 = aMgr.GetImageThrow("IMAGE_B6_ICONANIM1");
		IMAGE_B6_ICONANIM10 = aMgr.GetImageThrow("IMAGE_B6_ICONANIM10");
		IMAGE_B6_ICONANIM2 = aMgr.GetImageThrow("IMAGE_B6_ICONANIM2");
		IMAGE_B6_ICONANIM3 = aMgr.GetImageThrow("IMAGE_B6_ICONANIM3");
		IMAGE_B6_ICONANIM4 = aMgr.GetImageThrow("IMAGE_B6_ICONANIM4");
		IMAGE_B6_ICONANIM5 = aMgr.GetImageThrow("IMAGE_B6_ICONANIM5");
		IMAGE_B6_ICONANIM6 = aMgr.GetImageThrow("IMAGE_B6_ICONANIM6");
		IMAGE_B6_ICONANIM7 = aMgr.GetImageThrow("IMAGE_B6_ICONANIM7");
		IMAGE_B6_ICONANIM8 = aMgr.GetImageThrow("IMAGE_B6_ICONANIM8");
		IMAGE_B6_ICONANIM9 = aMgr.GetImageThrow("IMAGE_B6_ICONANIM9");
		IMAGE_B6_ICONMASK1 = aMgr.GetImageThrow("IMAGE_B6_ICONMASK1");
		IMAGE_B6_ICONMASK10 = aMgr.GetImageThrow("IMAGE_B6_ICONMASK10");
		IMAGE_B6_ICONMASK2 = aMgr.GetImageThrow("IMAGE_B6_ICONMASK2");
		IMAGE_B6_ICONMASK3 = aMgr.GetImageThrow("IMAGE_B6_ICONMASK3");
		IMAGE_B6_ICONMASK4 = aMgr.GetImageThrow("IMAGE_B6_ICONMASK4");
		IMAGE_B6_ICONMASK5 = aMgr.GetImageThrow("IMAGE_B6_ICONMASK5");
		IMAGE_B6_ICONMASK6 = aMgr.GetImageThrow("IMAGE_B6_ICONMASK6");
		IMAGE_B6_ICONMASK7 = aMgr.GetImageThrow("IMAGE_B6_ICONMASK7");
		IMAGE_B6_ICONMASK8 = aMgr.GetImageThrow("IMAGE_B6_ICONMASK8");
		IMAGE_B6_ICONMASK9 = aMgr.GetImageThrow("IMAGE_B6_ICONMASK9");
		IMAGE_B6_MAP = aMgr.GetImageThrow("IMAGE_B6_MAP");
		IMAGE_B6_MAPSCREEN_BANNER = aMgr.GetImageThrow("IMAGE_B6_MAPSCREEN_BANNER");
		IMAGE_B6_MINIMAP_ICONS = aMgr.GetImageThrow("IMAGE_B6_MINIMAP_ICONS");
		IMAGE_TUT_PIC_BIGBROTHER = aMgr.GetImageThrow("IMAGE_TUT_PIC_BIGBROTHER");
		IMAGE_TUT_PIC_MAGICPEN = aMgr.GetImageThrow("IMAGE_TUT_PIC_MAGICPEN");
		IMAGE_TUT_PIC_PREV_LEX = aMgr.GetImageThrow("IMAGE_TUT_PIC_PREV_LEX");
		IMAGE_TUT_PIC_SKELETROX = aMgr.GetImageThrow("IMAGE_TUT_PIC_SKELETROX");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

static void* gResources[] =
{
	&IMAGE_B6_MINIMAP_ICONS,
	&IMAGE_B6_MAPSCREEN_BANNER,
	&IMAGE_B6_ICONANIM1,
	&IMAGE_B6_ICONANIM2,
	&IMAGE_B6_ICONANIM3,
	&IMAGE_B6_ICONANIM4,
	&IMAGE_B6_ICONANIM5,
	&IMAGE_B6_ICONANIM6,
	&IMAGE_B6_ICONANIM7,
	&IMAGE_B6_ICONANIM8,
	&IMAGE_B6_ICONANIM9,
	&IMAGE_B6_ICONANIM10,
	&IMAGE_B6_ICONMASK1,
	&IMAGE_B6_ICONMASK2,
	&IMAGE_B6_ICONMASK3,
	&IMAGE_B6_ICONMASK4,
	&IMAGE_B6_ICONMASK5,
	&IMAGE_B6_ICONMASK6,
	&IMAGE_B6_ICONMASK7,
	&IMAGE_B6_ICONMASK8,
	&IMAGE_B6_ICONMASK9,
	&IMAGE_B6_ICONMASK10,
	&IMAGE_B6_MAP,
	&IMAGE_TUT_PIC_SKELETROX,
	&IMAGE_TUT_PIC_BIGBROTHER,
	&IMAGE_TUT_PIC_MAGICPEN,
	&IMAGE_TUT_PIC_PREV_LEX,
	&IMAGE_B6_LEFT_FACING_ARROW,
	&IMAGE_B6A_SKIFF,
	&IMAGE_B6A_BG1,
	&SOUND_BOOK6_CH1_FELINE_ENGAGE,
	&SOUND_BOOK6_CH1_FELINE_ROAR,
	&SOUND_BOOK6_CH1_SCIFI_LASER,
	&SOUND_BOOK6_CH1_SCIFI_MECH,
	&SOUND_BOOK6_CH1_SCIFI_MECH2,
	&SOUND_BOOK6_CH1_SCIFI_TELEPORT,
	&SOUND_BOOK6_CH1_SONIC_ATTACK,
	&SOUND_BOOK6_CH1_SPARKLE_ATTACK,
	&SOUND_BOOK6_CH1_MONKEY_ATTACK,
	&SOUND_BOOK6_CH1_ROBOT_ATTACK,
	&SOUND_BOOK6_CH1_ROBOT_CHALLENGE,
	&SOUND_BOOK6_CH1_ROBOT_IMPACT,
	&SOUND_BOOK6_CH1_SMOKE_ATTACK,
	&SOUND_BOOK6_CH1_SMOKE_ATTACK2,
	&SOUND_BOOK6_CH1_SMOKE_IMPACT,
	&SOUND_BOOK6_CH1_WET_IMPACT1,
	&SOUND_BOOK6_CH1_BOVINE_ATTACK1,
	&SOUND_BOOK6_CH1_EXPLOSION_1,
	&IMAGE_B6A_BG2,
	&SOUND_BOOK6_CH2_MONKEY_ATTACK,
	&SOUND_BOOK6_CH2_MONKEY_ATTACK2,
	&SOUND_BOOK6_CH2_MONKEY_CHALLENGE,
	&SOUND_BOOK6_CH2_DOPEY_ATTACK,
	&SOUND_BOOK6_CH2_DOPEY_IMPACT,
	&SOUND_BOOK6_CH2_MALE_LOW_ANGER,
	&SOUND_BOOK6_CH2_OGRE_ATTACK,
	&SOUND_BOOK6_CH2_OGRE_ATTACK2,
	&SOUND_BOOK6_CH2_OGRE_CHALLENGE,
	&SOUND_BOOK6_CH2_OGRE_CHALLENGE2,
	&SOUND_BOOK6_CH2_OGRE_IMPACT,
	&SOUND_BOOK6_CH2_OGRE_IMPACT2,
	&SOUND_BOOK6_CH2_OGRE_IMPACT3,
	&SOUND_BOOK6_CH2_WET_IMPACT1,
	&SOUND_BOOK6_CH2_WET_IMPACT2,
	&SOUND_BOOK6_CH2_EXPLOSION_3,
	&SOUND_BOOK6_CH2_SCIFI_LASER,
	&SOUND_BOOK6_CH2_MISC_IMPACT,
	&IMAGE_B6A_BG3,
	&SOUND_BOOK6_CH3_DOPEY_ATTACK,
	&SOUND_BOOK6_CH3_DOPEY_IMPACT,
	&SOUND_BOOK6_CH3_MALE_LOW_ANGER,
	&SOUND_BOOK6_CH3_OGRE_ATTACK,
	&SOUND_BOOK6_CH3_OGRE_ATTACK2,
	&SOUND_BOOK6_CH3_OGRE_CHALLENGE,
	&SOUND_BOOK6_CH3_OGRE_CHALLENGE2,
	&SOUND_BOOK6_CH3_OGRE_IMPACT,
	&SOUND_BOOK6_CH3_OGRE_IMPACT2,
	&SOUND_BOOK6_CH3_OGRE_IMPACT3,
	&SOUND_BOOK6_CH3_MALE_ANGER,
	&SOUND_BOOK6_CH3_PIG_ATTACK,
	&SOUND_BOOK6_CH3_PIG_SQUEAL2,
	&SOUND_BOOK6_CH3_MALE_PAIN,
	&SOUND_BOOK6_CH3_CS_SHACKLE,
	&IMAGE_B6A_BG4,
	&SOUND_BOOK6_CH4_ROBOT_ATTACK,
	&SOUND_BOOK6_CH4_ROBOT_CHALLENGE,
	&SOUND_BOOK6_CH4_ROBOT_IMPACT,
	&SOUND_BOOK6_CH4_SCIFI_LASER,
	&SOUND_BOOK6_CH4_SCIFI_MECH,
	&SOUND_BOOK6_CH4_SCIFI_MECH2,
	&SOUND_BOOK6_CH4_SCIFI_TELEPORT,
	&SOUND_BOOK6_CH4_SONIC_ATTACK,
	&SOUND_BOOK6_CH4_FEMALE_SEDUCE,
	&SOUND_BOOK6_CH4_FEMALE_GROAN1,
	&SOUND_BOOK6_CH4_FEMALE_GROAN2,
	&SOUND_BOOK6_CH4_PLATE_ATTACK2,
	&SOUND_BOOK6_CH4_SHEEP_BLEAT,
	&SOUND_BOOK6_CH4_SMOKE_ATTACK,
	&SOUND_BOOK6_CH4_DRAGON_ROAR,
	&SOUND_BOOK6_CH4_SWORD_IMPACT3,
	&SOUND_BOOK6_CH4_SLICING_ATTACK,
	&IMAGE_B6A_BG5,
	&SOUND_BOOK6_CH5_FEMALE_GROAN1,
	&SOUND_BOOK6_CH5_FEMALE_GROAN2,
	&SOUND_BOOK6_CH5_ARROW_SHOT,
	&SOUND_BOOK6_CH5_MALE_ANGER,
	&SOUND_BOOK6_CH5_MALE_LAUGH,
	&SOUND_BOOK6_CH5_MALE_LAUGH2,
	&SOUND_BOOK6_CH5_MALE_PAIN,
	&SOUND_BOOK6_CH5_WET_IMPACT1,
	&SOUND_BOOK6_CH5_WET_IMPACT2,
	&SOUND_BOOK6_CH5_MISC_IMPACT,
	&SOUND_BOOK6_CH5_MISC_IMPACT2,
	&SOUND_BOOK6_CH5_SWORD_IMPACT3,
	&SOUND_BOOK6_CH5_LIGHTNING_ATTACK,
	&SOUND_BOOK6_CH5_BEAR_ROAR,
	&IMAGE_B6A_BG6,
	&SOUND_BOOK6_CH6_DRAGON_BITE,
	&SOUND_BOOK6_CH6_DRAGON_DEATH,
	&SOUND_BOOK6_CH6_DRAGON_PAIN,
	&SOUND_BOOK6_CH6_DRAGON_ROAR,
	&SOUND_BOOK6_CH6_MALE_ANGER,
	&SOUND_BOOK6_CH6_MALE_LAUGH,
	&SOUND_BOOK6_CH6_MALE_LAUGH2,
	&SOUND_BOOK6_CH6_MALE_PAIN,
	&SOUND_BOOK6_CH6_SPARKLE_ATTACK,
	&SOUND_BOOK6_CH6_EXPLOSION_3,
	&SOUND_BOOK6_CH6_LIGHTNING_ATTACK,
	&SOUND_BOOK6_CH6_SWORD_IMPACT3,
	&IMAGE_B6A_BG7,
	&IMAGE_B6A_DANCEBATTLE_BOSS_BATTLE,
	&SOUND_BOOK6_CH7_SOUND1,
	&SOUND_BOOK6_CH7_SOUND2,
	&SOUND_BOOK6_CH7_SOUND3,
	&SOUND_BOOK6_CH7_SOUND4,
	&SOUND_BOOK6_CH7_SOUND5,
	&SOUND_BOOK6_CH7_SOUND6,
	&SOUND_BOOK6_CH7_SOUND7,
	&SOUND_BOOK6_CH7_SOUND8,
	&SOUND_BOOK6_CH7_SOUND9,
	&SOUND_BOOK6_CH7_DANCE_ENGAGE,
	&SOUND_BOOK6_CH7_DANCE_DEATH,
	&SOUND_BOOK6_CH7_DANCE_CAMERA,
	&SOUND_BOOK6_CH7_DANCE_CHEER,
	&SOUND_BOOK6_CH7_DANCE_L,
	&SOUND_BOOK6_CH7_DANCE_E,
	&SOUND_BOOK6_CH7_DANCE_X,
	&SOUND_BOOK6_CH7_DANCE_LEX,
	&SOUND_BOOK6_CH7_CS_SKULL,
	&IMAGE_B6A_BG8,
	&SOUND_BOOK6_CH8_DOPEY_ATTACK,
	&SOUND_BOOK6_CH8_DOPEY_IMPACT,
	&SOUND_BOOK6_CH8_FEMALE_SEDUCE,
	&SOUND_BOOK6_CH8_MALE_GRUNT1,
	&SOUND_BOOK6_CH8_LIGHTNING_ATTACK,
	&SOUND_BOOK6_CH8_MALE_LAUGH2,
	&SOUND_BOOK6_CH8_FEMALE_GROAN2,
	&SOUND_BOOK6_CH8_SCIFI_LASER,
	&SOUND_BOOK6_CH8_SCIFI_MECH,
	&SOUND_BOOK6_CH8_SCIFI_MECH2,
	&SOUND_BOOK6_CH8_SCIFI_TELEPORT,
	&SOUND_BOOK6_CH8_SONIC_ATTACK,
	&SOUND_BOOK6_CH8_SPARKLE_ATTACK,
	&SOUND_BOOK6_CH8_SMOKE_ATTACK,
	&SOUND_BOOK6_CH8_SMOKE_ATTACK2,
	&SOUND_BOOK6_CH8_SMOKE_IMPACT,
	&SOUND_BOOK6_CH8_FEMALE_OOOH,
	&IMAGE_B6A_BG9,
	&SOUND_BOOK6_CH9_MALE_ANGER,
	&SOUND_BOOK6_CH9_MALE_LAUGH,
	&SOUND_BOOK6_CH9_MALE_LAUGH2,
	&SOUND_BOOK6_CH9_MALE_LOW_ANGER,
	&SOUND_BOOK6_CH9_MALE_LOW_PAIN,
	&SOUND_BOOK6_CH9_MALE_LOW_WARCRY,
	&SOUND_BOOK6_CH9_MALE_PAIN,
	&SOUND_BOOK6_CH9_ROBOT_ATTACK,
	&SOUND_BOOK6_CH9_ROBOT_CHALLENGE,
	&SOUND_BOOK6_CH9_ROBOT_IMPACT,
	&SOUND_BOOK6_CH9_SCIFI_LASER,
	&SOUND_BOOK6_CH9_SCIFI_MECH,
	&SOUND_BOOK6_CH9_SCIFI_MECH2,
	&SOUND_BOOK6_CH9_SCIFI_TELEPORT,
	&SOUND_BOOK6_CH9_FIRE_6,
	&SOUND_BOOK6_CH9_SONIC_ATTACK,
	&SOUND_BOOK6_CH9_SPARKLE_ATTACK,
	&SOUND_BOOK6_CH9_LIGHTNING_ATTACK,
	&SOUND_BOOK6_CH9_EXPLOSION_1,
	&SOUND_BOOK6_CH9_BLUNT_IMPACT2,
	&SOUND_BOOK6_CH9_DOG_BARK2,
	&IMAGE_B6A_BG10,
	&IMAGE_B6A_THEMACHINE_BOSS_BATTLE,
	&SOUND_BOOK6_CH10_ROBOT_ATTACK,
	&SOUND_BOOK6_CH10_ROBOT_CHALLENGE,
	&SOUND_BOOK6_CH10_ROBOT_IMPACT,
	&SOUND_BOOK6_CH10_SCIFI_LASER,
	&SOUND_BOOK6_CH10_SCIFI_MECH,
	&SOUND_BOOK6_CH10_SCIFI_MECH2,
	&SOUND_BOOK6_CH10_SCIFI_TELEPORT,
	&SOUND_BOOK6_CH10_FIRE_6,
	&SOUND_BOOK6_CH10_SONIC_ATTACK,
	&SOUND_BOOK6_CH10_SPARKLE_ATTACK,
	&SOUND_BOOK6_CH10_LIGHTNING_ATTACK,
	&SOUND_BOOK6_CH10_EXPLOSION_1,
	&SOUND_BOOK6_CH10_BLUNT_IMPACT2,
	&SOUND_BOOK6_CH10_EXPLOSION_3,
	NULL
};

Image* Sexy::LoadImageById(ResourceManager *theManager, int theId)
{
	return (*((Image**)gResources[theId]) = theManager->LoadImage(GetStringIdById(theId)));
}

void Sexy::ReplaceImageById(ResourceManager *theManager, int theId, Image *theImage)
{
	theManager->ReplaceImage(GetStringIdById(theId),theImage);
	*(Image**)gResources[theId] = theImage;
}

Image* Sexy::GetImageById(int theId)
{
	return *(Image**)gResources[theId];
}

Font* Sexy::GetFontById(int theId)
{
	return *(Font**)gResources[theId];
}

int Sexy::GetSoundById(int theId)
{
	return *(int*)gResources[theId];
}

Image*& Sexy::GetImageRefById(int theId)
{
	return *(Image**)gResources[theId];
}

Font*& Sexy::GetFontRefById(int theId)
{
	return *(Font**)gResources[theId];
}

int& Sexy::GetSoundRefById(int theId)
{
	return *(int*)gResources[theId];
}

static Sexy::ResourceId GetIdByVariable(const void *theVariable)
{
	typedef std::map<int,int> MyMap;
	static MyMap aMap;
	if(gNeedRecalcVariableToIdMap)
	{
		gNeedRecalcVariableToIdMap = false;
		aMap.clear();
		for(int i=0; i<RESOURCE_ID_MAX; i++)
			aMap[*(int*)gResources[i]] = i;
	}

	MyMap::iterator anItr = aMap.find((int)theVariable);
	if (anItr == aMap.end())
		return RESOURCE_ID_MAX;
	else
		return (ResourceId) anItr->second;
}

Sexy::ResourceId Sexy::GetIdByImage(Image *theImage)
{
	return GetIdByVariable(theImage);
}

Sexy::ResourceId Sexy::GetIdByFont(Font *theFont)
{
	return GetIdByVariable(theFont);
}

Sexy::ResourceId Sexy::GetIdBySound(int theSound)
{
	return GetIdByVariable((void*)theSound);
}

const char* Sexy::GetStringIdById(int theId)
{
	switch(theId)
	{
		case IMAGE_B6_MINIMAP_ICONS_ID: return "IMAGE_B6_MINIMAP_ICONS";
		case IMAGE_B6_MAPSCREEN_BANNER_ID: return "IMAGE_B6_MAPSCREEN_BANNER";
		case IMAGE_B6_ICONANIM1_ID: return "IMAGE_B6_ICONANIM1";
		case IMAGE_B6_ICONANIM2_ID: return "IMAGE_B6_ICONANIM2";
		case IMAGE_B6_ICONANIM3_ID: return "IMAGE_B6_ICONANIM3";
		case IMAGE_B6_ICONANIM4_ID: return "IMAGE_B6_ICONANIM4";
		case IMAGE_B6_ICONANIM5_ID: return "IMAGE_B6_ICONANIM5";
		case IMAGE_B6_ICONANIM6_ID: return "IMAGE_B6_ICONANIM6";
		case IMAGE_B6_ICONANIM7_ID: return "IMAGE_B6_ICONANIM7";
		case IMAGE_B6_ICONANIM8_ID: return "IMAGE_B6_ICONANIM8";
		case IMAGE_B6_ICONANIM9_ID: return "IMAGE_B6_ICONANIM9";
		case IMAGE_B6_ICONANIM10_ID: return "IMAGE_B6_ICONANIM10";
		case IMAGE_B6_ICONMASK1_ID: return "IMAGE_B6_ICONMASK1";
		case IMAGE_B6_ICONMASK2_ID: return "IMAGE_B6_ICONMASK2";
		case IMAGE_B6_ICONMASK3_ID: return "IMAGE_B6_ICONMASK3";
		case IMAGE_B6_ICONMASK4_ID: return "IMAGE_B6_ICONMASK4";
		case IMAGE_B6_ICONMASK5_ID: return "IMAGE_B6_ICONMASK5";
		case IMAGE_B6_ICONMASK6_ID: return "IMAGE_B6_ICONMASK6";
		case IMAGE_B6_ICONMASK7_ID: return "IMAGE_B6_ICONMASK7";
		case IMAGE_B6_ICONMASK8_ID: return "IMAGE_B6_ICONMASK8";
		case IMAGE_B6_ICONMASK9_ID: return "IMAGE_B6_ICONMASK9";
		case IMAGE_B6_ICONMASK10_ID: return "IMAGE_B6_ICONMASK10";
		case IMAGE_B6_MAP_ID: return "IMAGE_B6_MAP";
		case IMAGE_TUT_PIC_SKELETROX_ID: return "IMAGE_TUT_PIC_SKELETROX";
		case IMAGE_TUT_PIC_BIGBROTHER_ID: return "IMAGE_TUT_PIC_BIGBROTHER";
		case IMAGE_TUT_PIC_MAGICPEN_ID: return "IMAGE_TUT_PIC_MAGICPEN";
		case IMAGE_TUT_PIC_PREV_LEX_ID: return "IMAGE_TUT_PIC_PREV_LEX";
		case IMAGE_B6_LEFT_FACING_ARROW_ID: return "IMAGE_B6_LEFT_FACING_ARROW";
		case IMAGE_B6A_SKIFF_ID: return "IMAGE_B6A_SKIFF";
		case IMAGE_B6A_BG1_ID: return "IMAGE_B6A_BG1";
		case SOUND_BOOK6_CH1_FELINE_ENGAGE_ID: return "SOUND_BOOK6_CH1_FELINE_ENGAGE";
		case SOUND_BOOK6_CH1_FELINE_ROAR_ID: return "SOUND_BOOK6_CH1_FELINE_ROAR";
		case SOUND_BOOK6_CH1_SCIFI_LASER_ID: return "SOUND_BOOK6_CH1_SCIFI_LASER";
		case SOUND_BOOK6_CH1_SCIFI_MECH_ID: return "SOUND_BOOK6_CH1_SCIFI_MECH";
		case SOUND_BOOK6_CH1_SCIFI_MECH2_ID: return "SOUND_BOOK6_CH1_SCIFI_MECH2";
		case SOUND_BOOK6_CH1_SCIFI_TELEPORT_ID: return "SOUND_BOOK6_CH1_SCIFI_TELEPORT";
		case SOUND_BOOK6_CH1_SONIC_ATTACK_ID: return "SOUND_BOOK6_CH1_SONIC_ATTACK";
		case SOUND_BOOK6_CH1_SPARKLE_ATTACK_ID: return "SOUND_BOOK6_CH1_SPARKLE_ATTACK";
		case SOUND_BOOK6_CH1_MONKEY_ATTACK_ID: return "SOUND_BOOK6_CH1_MONKEY_ATTACK";
		case SOUND_BOOK6_CH1_ROBOT_ATTACK_ID: return "SOUND_BOOK6_CH1_ROBOT_ATTACK";
		case SOUND_BOOK6_CH1_ROBOT_CHALLENGE_ID: return "SOUND_BOOK6_CH1_ROBOT_CHALLENGE";
		case SOUND_BOOK6_CH1_ROBOT_IMPACT_ID: return "SOUND_BOOK6_CH1_ROBOT_IMPACT";
		case SOUND_BOOK6_CH1_SMOKE_ATTACK_ID: return "SOUND_BOOK6_CH1_SMOKE_ATTACK";
		case SOUND_BOOK6_CH1_SMOKE_ATTACK2_ID: return "SOUND_BOOK6_CH1_SMOKE_ATTACK2";
		case SOUND_BOOK6_CH1_SMOKE_IMPACT_ID: return "SOUND_BOOK6_CH1_SMOKE_IMPACT";
		case SOUND_BOOK6_CH1_WET_IMPACT1_ID: return "SOUND_BOOK6_CH1_WET_IMPACT1";
		case SOUND_BOOK6_CH1_BOVINE_ATTACK1_ID: return "SOUND_BOOK6_CH1_BOVINE_ATTACK1";
		case SOUND_BOOK6_CH1_EXPLOSION_1_ID: return "SOUND_BOOK6_CH1_EXPLOSION_1";
		case IMAGE_B6A_BG2_ID: return "IMAGE_B6A_BG2";
		case SOUND_BOOK6_CH2_MONKEY_ATTACK_ID: return "SOUND_BOOK6_CH2_MONKEY_ATTACK";
		case SOUND_BOOK6_CH2_MONKEY_ATTACK2_ID: return "SOUND_BOOK6_CH2_MONKEY_ATTACK2";
		case SOUND_BOOK6_CH2_MONKEY_CHALLENGE_ID: return "SOUND_BOOK6_CH2_MONKEY_CHALLENGE";
		case SOUND_BOOK6_CH2_DOPEY_ATTACK_ID: return "SOUND_BOOK6_CH2_DOPEY_ATTACK";
		case SOUND_BOOK6_CH2_DOPEY_IMPACT_ID: return "SOUND_BOOK6_CH2_DOPEY_IMPACT";
		case SOUND_BOOK6_CH2_MALE_LOW_ANGER_ID: return "SOUND_BOOK6_CH2_MALE_LOW_ANGER";
		case SOUND_BOOK6_CH2_OGRE_ATTACK_ID: return "SOUND_BOOK6_CH2_OGRE_ATTACK";
		case SOUND_BOOK6_CH2_OGRE_ATTACK2_ID: return "SOUND_BOOK6_CH2_OGRE_ATTACK2";
		case SOUND_BOOK6_CH2_OGRE_CHALLENGE_ID: return "SOUND_BOOK6_CH2_OGRE_CHALLENGE";
		case SOUND_BOOK6_CH2_OGRE_CHALLENGE2_ID: return "SOUND_BOOK6_CH2_OGRE_CHALLENGE2";
		case SOUND_BOOK6_CH2_OGRE_IMPACT_ID: return "SOUND_BOOK6_CH2_OGRE_IMPACT";
		case SOUND_BOOK6_CH2_OGRE_IMPACT2_ID: return "SOUND_BOOK6_CH2_OGRE_IMPACT2";
		case SOUND_BOOK6_CH2_OGRE_IMPACT3_ID: return "SOUND_BOOK6_CH2_OGRE_IMPACT3";
		case SOUND_BOOK6_CH2_WET_IMPACT1_ID: return "SOUND_BOOK6_CH2_WET_IMPACT1";
		case SOUND_BOOK6_CH2_WET_IMPACT2_ID: return "SOUND_BOOK6_CH2_WET_IMPACT2";
		case SOUND_BOOK6_CH2_EXPLOSION_3_ID: return "SOUND_BOOK6_CH2_EXPLOSION_3";
		case SOUND_BOOK6_CH2_SCIFI_LASER_ID: return "SOUND_BOOK6_CH2_SCIFI_LASER";
		case SOUND_BOOK6_CH2_MISC_IMPACT_ID: return "SOUND_BOOK6_CH2_MISC_IMPACT";
		case IMAGE_B6A_BG3_ID: return "IMAGE_B6A_BG3";
		case SOUND_BOOK6_CH3_DOPEY_ATTACK_ID: return "SOUND_BOOK6_CH3_DOPEY_ATTACK";
		case SOUND_BOOK6_CH3_DOPEY_IMPACT_ID: return "SOUND_BOOK6_CH3_DOPEY_IMPACT";
		case SOUND_BOOK6_CH3_MALE_LOW_ANGER_ID: return "SOUND_BOOK6_CH3_MALE_LOW_ANGER";
		case SOUND_BOOK6_CH3_OGRE_ATTACK_ID: return "SOUND_BOOK6_CH3_OGRE_ATTACK";
		case SOUND_BOOK6_CH3_OGRE_ATTACK2_ID: return "SOUND_BOOK6_CH3_OGRE_ATTACK2";
		case SOUND_BOOK6_CH3_OGRE_CHALLENGE_ID: return "SOUND_BOOK6_CH3_OGRE_CHALLENGE";
		case SOUND_BOOK6_CH3_OGRE_CHALLENGE2_ID: return "SOUND_BOOK6_CH3_OGRE_CHALLENGE2";
		case SOUND_BOOK6_CH3_OGRE_IMPACT_ID: return "SOUND_BOOK6_CH3_OGRE_IMPACT";
		case SOUND_BOOK6_CH3_OGRE_IMPACT2_ID: return "SOUND_BOOK6_CH3_OGRE_IMPACT2";
		case SOUND_BOOK6_CH3_OGRE_IMPACT3_ID: return "SOUND_BOOK6_CH3_OGRE_IMPACT3";
		case SOUND_BOOK6_CH3_MALE_ANGER_ID: return "SOUND_BOOK6_CH3_MALE_ANGER";
		case SOUND_BOOK6_CH3_PIG_ATTACK_ID: return "SOUND_BOOK6_CH3_PIG_ATTACK";
		case SOUND_BOOK6_CH3_PIG_SQUEAL2_ID: return "SOUND_BOOK6_CH3_PIG_SQUEAL2";
		case SOUND_BOOK6_CH3_MALE_PAIN_ID: return "SOUND_BOOK6_CH3_MALE_PAIN";
		case SOUND_BOOK6_CH3_CS_SHACKLE_ID: return "SOUND_BOOK6_CH3_CS_SHACKLE";
		case IMAGE_B6A_BG4_ID: return "IMAGE_B6A_BG4";
		case SOUND_BOOK6_CH4_ROBOT_ATTACK_ID: return "SOUND_BOOK6_CH4_ROBOT_ATTACK";
		case SOUND_BOOK6_CH4_ROBOT_CHALLENGE_ID: return "SOUND_BOOK6_CH4_ROBOT_CHALLENGE";
		case SOUND_BOOK6_CH4_ROBOT_IMPACT_ID: return "SOUND_BOOK6_CH4_ROBOT_IMPACT";
		case SOUND_BOOK6_CH4_SCIFI_LASER_ID: return "SOUND_BOOK6_CH4_SCIFI_LASER";
		case SOUND_BOOK6_CH4_SCIFI_MECH_ID: return "SOUND_BOOK6_CH4_SCIFI_MECH";
		case SOUND_BOOK6_CH4_SCIFI_MECH2_ID: return "SOUND_BOOK6_CH4_SCIFI_MECH2";
		case SOUND_BOOK6_CH4_SCIFI_TELEPORT_ID: return "SOUND_BOOK6_CH4_SCIFI_TELEPORT";
		case SOUND_BOOK6_CH4_SONIC_ATTACK_ID: return "SOUND_BOOK6_CH4_SONIC_ATTACK";
		case SOUND_BOOK6_CH4_FEMALE_SEDUCE_ID: return "SOUND_BOOK6_CH4_FEMALE_SEDUCE";
		case SOUND_BOOK6_CH4_FEMALE_GROAN1_ID: return "SOUND_BOOK6_CH4_FEMALE_GROAN1";
		case SOUND_BOOK6_CH4_FEMALE_GROAN2_ID: return "SOUND_BOOK6_CH4_FEMALE_GROAN2";
		case SOUND_BOOK6_CH4_PLATE_ATTACK2_ID: return "SOUND_BOOK6_CH4_PLATE_ATTACK2";
		case SOUND_BOOK6_CH4_SHEEP_BLEAT_ID: return "SOUND_BOOK6_CH4_SHEEP_BLEAT";
		case SOUND_BOOK6_CH4_SMOKE_ATTACK_ID: return "SOUND_BOOK6_CH4_SMOKE_ATTACK";
		case SOUND_BOOK6_CH4_DRAGON_ROAR_ID: return "SOUND_BOOK6_CH4_DRAGON_ROAR";
		case SOUND_BOOK6_CH4_SWORD_IMPACT3_ID: return "SOUND_BOOK6_CH4_SWORD_IMPACT3";
		case SOUND_BOOK6_CH4_SLICING_ATTACK_ID: return "SOUND_BOOK6_CH4_SLICING_ATTACK";
		case IMAGE_B6A_BG5_ID: return "IMAGE_B6A_BG5";
		case SOUND_BOOK6_CH5_FEMALE_GROAN1_ID: return "SOUND_BOOK6_CH5_FEMALE_GROAN1";
		case SOUND_BOOK6_CH5_FEMALE_GROAN2_ID: return "SOUND_BOOK6_CH5_FEMALE_GROAN2";
		case SOUND_BOOK6_CH5_ARROW_SHOT_ID: return "SOUND_BOOK6_CH5_ARROW_SHOT";
		case SOUND_BOOK6_CH5_MALE_ANGER_ID: return "SOUND_BOOK6_CH5_MALE_ANGER";
		case SOUND_BOOK6_CH5_MALE_LAUGH_ID: return "SOUND_BOOK6_CH5_MALE_LAUGH";
		case SOUND_BOOK6_CH5_MALE_LAUGH2_ID: return "SOUND_BOOK6_CH5_MALE_LAUGH2";
		case SOUND_BOOK6_CH5_MALE_PAIN_ID: return "SOUND_BOOK6_CH5_MALE_PAIN";
		case SOUND_BOOK6_CH5_WET_IMPACT1_ID: return "SOUND_BOOK6_CH5_WET_IMPACT1";
		case SOUND_BOOK6_CH5_WET_IMPACT2_ID: return "SOUND_BOOK6_CH5_WET_IMPACT2";
		case SOUND_BOOK6_CH5_MISC_IMPACT_ID: return "SOUND_BOOK6_CH5_MISC_IMPACT";
		case SOUND_BOOK6_CH5_MISC_IMPACT2_ID: return "SOUND_BOOK6_CH5_MISC_IMPACT2";
		case SOUND_BOOK6_CH5_SWORD_IMPACT3_ID: return "SOUND_BOOK6_CH5_SWORD_IMPACT3";
		case SOUND_BOOK6_CH5_LIGHTNING_ATTACK_ID: return "SOUND_BOOK6_CH5_LIGHTNING_ATTACK";
		case SOUND_BOOK6_CH5_BEAR_ROAR_ID: return "SOUND_BOOK6_CH5_BEAR_ROAR";
		case IMAGE_B6A_BG6_ID: return "IMAGE_B6A_BG6";
		case SOUND_BOOK6_CH6_DRAGON_BITE_ID: return "SOUND_BOOK6_CH6_DRAGON_BITE";
		case SOUND_BOOK6_CH6_DRAGON_DEATH_ID: return "SOUND_BOOK6_CH6_DRAGON_DEATH";
		case SOUND_BOOK6_CH6_DRAGON_PAIN_ID: return "SOUND_BOOK6_CH6_DRAGON_PAIN";
		case SOUND_BOOK6_CH6_DRAGON_ROAR_ID: return "SOUND_BOOK6_CH6_DRAGON_ROAR";
		case SOUND_BOOK6_CH6_MALE_ANGER_ID: return "SOUND_BOOK6_CH6_MALE_ANGER";
		case SOUND_BOOK6_CH6_MALE_LAUGH_ID: return "SOUND_BOOK6_CH6_MALE_LAUGH";
		case SOUND_BOOK6_CH6_MALE_LAUGH2_ID: return "SOUND_BOOK6_CH6_MALE_LAUGH2";
		case SOUND_BOOK6_CH6_MALE_PAIN_ID: return "SOUND_BOOK6_CH6_MALE_PAIN";
		case SOUND_BOOK6_CH6_SPARKLE_ATTACK_ID: return "SOUND_BOOK6_CH6_SPARKLE_ATTACK";
		case SOUND_BOOK6_CH6_EXPLOSION_3_ID: return "SOUND_BOOK6_CH6_EXPLOSION_3";
		case SOUND_BOOK6_CH6_LIGHTNING_ATTACK_ID: return "SOUND_BOOK6_CH6_LIGHTNING_ATTACK";
		case SOUND_BOOK6_CH6_SWORD_IMPACT3_ID: return "SOUND_BOOK6_CH6_SWORD_IMPACT3";
		case IMAGE_B6A_BG7_ID: return "IMAGE_B6A_BG7";
		case IMAGE_B6A_DANCEBATTLE_BOSS_BATTLE_ID: return "IMAGE_B6A_DANCEBATTLE_BOSS_BATTLE";
		case SOUND_BOOK6_CH7_SOUND1_ID: return "SOUND_BOOK6_CH7_SOUND1";
		case SOUND_BOOK6_CH7_SOUND2_ID: return "SOUND_BOOK6_CH7_SOUND2";
		case SOUND_BOOK6_CH7_SOUND3_ID: return "SOUND_BOOK6_CH7_SOUND3";
		case SOUND_BOOK6_CH7_SOUND4_ID: return "SOUND_BOOK6_CH7_SOUND4";
		case SOUND_BOOK6_CH7_SOUND5_ID: return "SOUND_BOOK6_CH7_SOUND5";
		case SOUND_BOOK6_CH7_SOUND6_ID: return "SOUND_BOOK6_CH7_SOUND6";
		case SOUND_BOOK6_CH7_SOUND7_ID: return "SOUND_BOOK6_CH7_SOUND7";
		case SOUND_BOOK6_CH7_SOUND8_ID: return "SOUND_BOOK6_CH7_SOUND8";
		case SOUND_BOOK6_CH7_SOUND9_ID: return "SOUND_BOOK6_CH7_SOUND9";
		case SOUND_BOOK6_CH7_DANCE_ENGAGE_ID: return "SOUND_BOOK6_CH7_DANCE_ENGAGE";
		case SOUND_BOOK6_CH7_DANCE_DEATH_ID: return "SOUND_BOOK6_CH7_DANCE_DEATH";
		case SOUND_BOOK6_CH7_DANCE_CAMERA_ID: return "SOUND_BOOK6_CH7_DANCE_CAMERA";
		case SOUND_BOOK6_CH7_DANCE_CHEER_ID: return "SOUND_BOOK6_CH7_DANCE_CHEER";
		case SOUND_BOOK6_CH7_DANCE_L_ID: return "SOUND_BOOK6_CH7_DANCE_L";
		case SOUND_BOOK6_CH7_DANCE_E_ID: return "SOUND_BOOK6_CH7_DANCE_E";
		case SOUND_BOOK6_CH7_DANCE_X_ID: return "SOUND_BOOK6_CH7_DANCE_X";
		case SOUND_BOOK6_CH7_DANCE_LEX_ID: return "SOUND_BOOK6_CH7_DANCE_LEX";
		case SOUND_BOOK6_CH7_CS_SKULL_ID: return "SOUND_BOOK6_CH7_CS_SKULL";
		case IMAGE_B6A_BG8_ID: return "IMAGE_B6A_BG8";
		case SOUND_BOOK6_CH8_DOPEY_ATTACK_ID: return "SOUND_BOOK6_CH8_DOPEY_ATTACK";
		case SOUND_BOOK6_CH8_DOPEY_IMPACT_ID: return "SOUND_BOOK6_CH8_DOPEY_IMPACT";
		case SOUND_BOOK6_CH8_FEMALE_SEDUCE_ID: return "SOUND_BOOK6_CH8_FEMALE_SEDUCE";
		case SOUND_BOOK6_CH8_MALE_GRUNT1_ID: return "SOUND_BOOK6_CH8_MALE_GRUNT1";
		case SOUND_BOOK6_CH8_LIGHTNING_ATTACK_ID: return "SOUND_BOOK6_CH8_LIGHTNING_ATTACK";
		case SOUND_BOOK6_CH8_MALE_LAUGH2_ID: return "SOUND_BOOK6_CH8_MALE_LAUGH2";
		case SOUND_BOOK6_CH8_FEMALE_GROAN2_ID: return "SOUND_BOOK6_CH8_FEMALE_GROAN2";
		case SOUND_BOOK6_CH8_SCIFI_LASER_ID: return "SOUND_BOOK6_CH8_SCIFI_LASER";
		case SOUND_BOOK6_CH8_SCIFI_MECH_ID: return "SOUND_BOOK6_CH8_SCIFI_MECH";
		case SOUND_BOOK6_CH8_SCIFI_MECH2_ID: return "SOUND_BOOK6_CH8_SCIFI_MECH2";
		case SOUND_BOOK6_CH8_SCIFI_TELEPORT_ID: return "SOUND_BOOK6_CH8_SCIFI_TELEPORT";
		case SOUND_BOOK6_CH8_SONIC_ATTACK_ID: return "SOUND_BOOK6_CH8_SONIC_ATTACK";
		case SOUND_BOOK6_CH8_SPARKLE_ATTACK_ID: return "SOUND_BOOK6_CH8_SPARKLE_ATTACK";
		case SOUND_BOOK6_CH8_SMOKE_ATTACK_ID: return "SOUND_BOOK6_CH8_SMOKE_ATTACK";
		case SOUND_BOOK6_CH8_SMOKE_ATTACK2_ID: return "SOUND_BOOK6_CH8_SMOKE_ATTACK2";
		case SOUND_BOOK6_CH8_SMOKE_IMPACT_ID: return "SOUND_BOOK6_CH8_SMOKE_IMPACT";
		case SOUND_BOOK6_CH8_FEMALE_OOOH_ID: return "SOUND_BOOK6_CH8_FEMALE_OOOH";
		case IMAGE_B6A_BG9_ID: return "IMAGE_B6A_BG9";
		case SOUND_BOOK6_CH9_MALE_ANGER_ID: return "SOUND_BOOK6_CH9_MALE_ANGER";
		case SOUND_BOOK6_CH9_MALE_LAUGH_ID: return "SOUND_BOOK6_CH9_MALE_LAUGH";
		case SOUND_BOOK6_CH9_MALE_LAUGH2_ID: return "SOUND_BOOK6_CH9_MALE_LAUGH2";
		case SOUND_BOOK6_CH9_MALE_LOW_ANGER_ID: return "SOUND_BOOK6_CH9_MALE_LOW_ANGER";
		case SOUND_BOOK6_CH9_MALE_LOW_PAIN_ID: return "SOUND_BOOK6_CH9_MALE_LOW_PAIN";
		case SOUND_BOOK6_CH9_MALE_LOW_WARCRY_ID: return "SOUND_BOOK6_CH9_MALE_LOW_WARCRY";
		case SOUND_BOOK6_CH9_MALE_PAIN_ID: return "SOUND_BOOK6_CH9_MALE_PAIN";
		case SOUND_BOOK6_CH9_ROBOT_ATTACK_ID: return "SOUND_BOOK6_CH9_ROBOT_ATTACK";
		case SOUND_BOOK6_CH9_ROBOT_CHALLENGE_ID: return "SOUND_BOOK6_CH9_ROBOT_CHALLENGE";
		case SOUND_BOOK6_CH9_ROBOT_IMPACT_ID: return "SOUND_BOOK6_CH9_ROBOT_IMPACT";
		case SOUND_BOOK6_CH9_SCIFI_LASER_ID: return "SOUND_BOOK6_CH9_SCIFI_LASER";
		case SOUND_BOOK6_CH9_SCIFI_MECH_ID: return "SOUND_BOOK6_CH9_SCIFI_MECH";
		case SOUND_BOOK6_CH9_SCIFI_MECH2_ID: return "SOUND_BOOK6_CH9_SCIFI_MECH2";
		case SOUND_BOOK6_CH9_SCIFI_TELEPORT_ID: return "SOUND_BOOK6_CH9_SCIFI_TELEPORT";
		case SOUND_BOOK6_CH9_FIRE_6_ID: return "SOUND_BOOK6_CH9_FIRE_6";
		case SOUND_BOOK6_CH9_SONIC_ATTACK_ID: return "SOUND_BOOK6_CH9_SONIC_ATTACK";
		case SOUND_BOOK6_CH9_SPARKLE_ATTACK_ID: return "SOUND_BOOK6_CH9_SPARKLE_ATTACK";
		case SOUND_BOOK6_CH9_LIGHTNING_ATTACK_ID: return "SOUND_BOOK6_CH9_LIGHTNING_ATTACK";
		case SOUND_BOOK6_CH9_EXPLOSION_1_ID: return "SOUND_BOOK6_CH9_EXPLOSION_1";
		case SOUND_BOOK6_CH9_BLUNT_IMPACT2_ID: return "SOUND_BOOK6_CH9_BLUNT_IMPACT2";
		case SOUND_BOOK6_CH9_DOG_BARK2_ID: return "SOUND_BOOK6_CH9_DOG_BARK2";
		case IMAGE_B6A_BG10_ID: return "IMAGE_B6A_BG10";
		case IMAGE_B6A_THEMACHINE_BOSS_BATTLE_ID: return "IMAGE_B6A_THEMACHINE_BOSS_BATTLE";
		case SOUND_BOOK6_CH10_ROBOT_ATTACK_ID: return "SOUND_BOOK6_CH10_ROBOT_ATTACK";
		case SOUND_BOOK6_CH10_ROBOT_CHALLENGE_ID: return "SOUND_BOOK6_CH10_ROBOT_CHALLENGE";
		case SOUND_BOOK6_CH10_ROBOT_IMPACT_ID: return "SOUND_BOOK6_CH10_ROBOT_IMPACT";
		case SOUND_BOOK6_CH10_SCIFI_LASER_ID: return "SOUND_BOOK6_CH10_SCIFI_LASER";
		case SOUND_BOOK6_CH10_SCIFI_MECH_ID: return "SOUND_BOOK6_CH10_SCIFI_MECH";
		case SOUND_BOOK6_CH10_SCIFI_MECH2_ID: return "SOUND_BOOK6_CH10_SCIFI_MECH2";
		case SOUND_BOOK6_CH10_SCIFI_TELEPORT_ID: return "SOUND_BOOK6_CH10_SCIFI_TELEPORT";
		case SOUND_BOOK6_CH10_FIRE_6_ID: return "SOUND_BOOK6_CH10_FIRE_6";
		case SOUND_BOOK6_CH10_SONIC_ATTACK_ID: return "SOUND_BOOK6_CH10_SONIC_ATTACK";
		case SOUND_BOOK6_CH10_SPARKLE_ATTACK_ID: return "SOUND_BOOK6_CH10_SPARKLE_ATTACK";
		case SOUND_BOOK6_CH10_LIGHTNING_ATTACK_ID: return "SOUND_BOOK6_CH10_LIGHTNING_ATTACK";
		case SOUND_BOOK6_CH10_EXPLOSION_1_ID: return "SOUND_BOOK6_CH10_EXPLOSION_1";
		case SOUND_BOOK6_CH10_BLUNT_IMPACT2_ID: return "SOUND_BOOK6_CH10_BLUNT_IMPACT2";
		case SOUND_BOOK6_CH10_EXPLOSION_3_ID: return "SOUND_BOOK6_CH10_EXPLOSION_3";
		default: return "";
	}
}

