#include "Book4.h"
#include "SexyAppFramework/ResourceManager.h"

using namespace Sexy;

#pragma warning(disable:4311 4312)

static bool gNeedRecalcVariableToIdMap = false;

bool Sexy::ExtractResourcesByName(ResourceManager *theManager, const char *theName)
{
	if (strcmp(theName,"BOOK5Common")==0) return ExtractBOOK5CommonResources(theManager);
	if (strcmp(theName,"Book4Chapter1")==0) return ExtractBook4Chapter1Resources(theManager);
	if (strcmp(theName,"Book4Chapter10")==0) return ExtractBook4Chapter10Resources(theManager);
	if (strcmp(theName,"Book4Chapter2")==0) return ExtractBook4Chapter2Resources(theManager);
	if (strcmp(theName,"Book4Chapter3")==0) return ExtractBook4Chapter3Resources(theManager);
	if (strcmp(theName,"Book4Chapter4")==0) return ExtractBook4Chapter4Resources(theManager);
	if (strcmp(theName,"Book4Chapter5")==0) return ExtractBook4Chapter5Resources(theManager);
	if (strcmp(theName,"Book4Chapter6")==0) return ExtractBook4Chapter6Resources(theManager);
	if (strcmp(theName,"Book4Chapter7")==0) return ExtractBook4Chapter7Resources(theManager);
	if (strcmp(theName,"Book4Chapter8")==0) return ExtractBook4Chapter8Resources(theManager);
	if (strcmp(theName,"Book4Chapter9")==0) return ExtractBook4Chapter9Resources(theManager);
	if (strcmp(theName,"Book4Init")==0) return ExtractBook4InitResources(theManager);
	return false;
}

Sexy::ResourceId Sexy::GetIdByStringId(const char *theStringId)
{
	typedef std::map<std::string,int> MyMap;
	static MyMap aMap;
	if(aMap.empty())
	{
		for(int i=0; i<RESOURCE_ID_MAX; i++)
			aMap[GetStringIdById(i)] = i;
	}

	MyMap::iterator anItr = aMap.find(theStringId);
	if (anItr == aMap.end())
		return RESOURCE_ID_MAX;
	else
		return (ResourceId) anItr->second;
}

// BOOK5Common Resources
Image* Sexy::IMAGE_B4_LEFT_FACING_ARROW;

bool Sexy::ExtractBOOK5CommonResources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_B4_LEFT_FACING_ARROW = aMgr.GetImageThrow("IMAGE_B4_LEFT_FACING_ARROW");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// Book4Chapter1 Resources
Image* Sexy::IMAGE_B4A_BG1;
int Sexy::SOUND_BOOK4_CH1_BOVINE_ATTACK1;
int Sexy::SOUND_BOOK4_CH1_BOVINE_ATTACK2;
int Sexy::SOUND_BOOK4_CH1_BOVINE_IMPACT;
int Sexy::SOUND_BOOK4_CH1_FELINE_ENGAGE;
int Sexy::SOUND_BOOK4_CH1_FELINE_ROAR;
int Sexy::SOUND_BOOK4_CH1_FIRE_6;
int Sexy::SOUND_BOOK4_CH1_PLATE_ATTACK2;
int Sexy::SOUND_BOOK4_CH1_PLATE_ATTACK3;
int Sexy::SOUND_BOOK4_CH1_PLATE_IMPACT3;
int Sexy::SOUND_BOOK4_CH1_PLATE_IMPACT4;
int Sexy::SOUND_BOOK4_CH1_PLATE_IMPACT5;
int Sexy::SOUND_BOOK4_CH1_PLATE_IMPACT6;
int Sexy::SOUND_BOOK4_CH1_SPARKLE_ATTACK;
int Sexy::SOUND_BOOK4_CH1_STRING_ATTACK;
int Sexy::SOUND_BOOK4_CH1_STRING_DEATH;
int Sexy::SOUND_BOOK4_CH1_STRING_IMPACT;

bool Sexy::ExtractBook4Chapter1Resources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_B4A_BG1 = aMgr.GetImageThrow("IMAGE_B4A_BG1");
		SOUND_BOOK4_CH1_BOVINE_ATTACK1 = aMgr.GetSoundThrow("SOUND_BOOK4_CH1_BOVINE_ATTACK1");
		SOUND_BOOK4_CH1_BOVINE_ATTACK2 = aMgr.GetSoundThrow("SOUND_BOOK4_CH1_BOVINE_ATTACK2");
		SOUND_BOOK4_CH1_BOVINE_IMPACT = aMgr.GetSoundThrow("SOUND_BOOK4_CH1_BOVINE_IMPACT");
		SOUND_BOOK4_CH1_FELINE_ENGAGE = aMgr.GetSoundThrow("SOUND_BOOK4_CH1_FELINE_ENGAGE");
		SOUND_BOOK4_CH1_FELINE_ROAR = aMgr.GetSoundThrow("SOUND_BOOK4_CH1_FELINE_ROAR");
		SOUND_BOOK4_CH1_FIRE_6 = aMgr.GetSoundThrow("SOUND_BOOK4_CH1_FIRE_6");
		SOUND_BOOK4_CH1_PLATE_ATTACK2 = aMgr.GetSoundThrow("SOUND_BOOK4_CH1_PLATE_ATTACK2");
		SOUND_BOOK4_CH1_PLATE_ATTACK3 = aMgr.GetSoundThrow("SOUND_BOOK4_CH1_PLATE_ATTACK3");
		SOUND_BOOK4_CH1_PLATE_IMPACT3 = aMgr.GetSoundThrow("SOUND_BOOK4_CH1_PLATE_IMPACT3");
		SOUND_BOOK4_CH1_PLATE_IMPACT4 = aMgr.GetSoundThrow("SOUND_BOOK4_CH1_PLATE_IMPACT4");
		SOUND_BOOK4_CH1_PLATE_IMPACT5 = aMgr.GetSoundThrow("SOUND_BOOK4_CH1_PLATE_IMPACT5");
		SOUND_BOOK4_CH1_PLATE_IMPACT6 = aMgr.GetSoundThrow("SOUND_BOOK4_CH1_PLATE_IMPACT6");
		SOUND_BOOK4_CH1_SPARKLE_ATTACK = aMgr.GetSoundThrow("SOUND_BOOK4_CH1_SPARKLE_ATTACK");
		SOUND_BOOK4_CH1_STRING_ATTACK = aMgr.GetSoundThrow("SOUND_BOOK4_CH1_STRING_ATTACK");
		SOUND_BOOK4_CH1_STRING_DEATH = aMgr.GetSoundThrow("SOUND_BOOK4_CH1_STRING_DEATH");
		SOUND_BOOK4_CH1_STRING_IMPACT = aMgr.GetSoundThrow("SOUND_BOOK4_CH1_STRING_IMPACT");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// Book4Chapter10 Resources
Image* Sexy::IMAGE_B4A_BG10;
int Sexy::SOUND_BOOK4_CH10_DOPEY_ATTACK;
int Sexy::SOUND_BOOK4_CH10_DOPEY_IMPACT;
int Sexy::SOUND_BOOK4_CH10_FEMALE_GROAN1;
int Sexy::SOUND_BOOK4_CH10_FEMALE_GROAN2;
int Sexy::SOUND_BOOK4_CH10_MALE_LAUGH;
int Sexy::SOUND_BOOK4_CH10_MALE_LAUGH2;
int Sexy::SOUND_BOOK4_CH10_MALE_PAIN;
int Sexy::SOUND_BOOK4_CH10_SLICING_ATTACK;
int Sexy::SOUND_BOOK4_CH10_SLICING_ATTACK2;
int Sexy::SOUND_BOOK4_CH10_SMOKE_ATTACK2;
int Sexy::SOUND_BOOK4_CH10_SQ_MAM_ATTACK2;
int Sexy::SOUND_BOOK4_CH10_SQ_MAM_DEATH;
int Sexy::SOUND_BOOK4_CH10_WITCH_LAUGH;
int Sexy::SOUND_BOOK4_CH10_WITCH_LAUGH2;

bool Sexy::ExtractBook4Chapter10Resources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_B4A_BG10 = aMgr.GetImageThrow("IMAGE_B4A_BG10");
		SOUND_BOOK4_CH10_DOPEY_ATTACK = aMgr.GetSoundThrow("SOUND_BOOK4_CH10_DOPEY_ATTACK");
		SOUND_BOOK4_CH10_DOPEY_IMPACT = aMgr.GetSoundThrow("SOUND_BOOK4_CH10_DOPEY_IMPACT");
		SOUND_BOOK4_CH10_FEMALE_GROAN1 = aMgr.GetSoundThrow("SOUND_BOOK4_CH10_FEMALE_GROAN1");
		SOUND_BOOK4_CH10_FEMALE_GROAN2 = aMgr.GetSoundThrow("SOUND_BOOK4_CH10_FEMALE_GROAN2");
		SOUND_BOOK4_CH10_MALE_LAUGH = aMgr.GetSoundThrow("SOUND_BOOK4_CH10_MALE_LAUGH");
		SOUND_BOOK4_CH10_MALE_LAUGH2 = aMgr.GetSoundThrow("SOUND_BOOK4_CH10_MALE_LAUGH2");
		SOUND_BOOK4_CH10_MALE_PAIN = aMgr.GetSoundThrow("SOUND_BOOK4_CH10_MALE_PAIN");
		SOUND_BOOK4_CH10_SLICING_ATTACK = aMgr.GetSoundThrow("SOUND_BOOK4_CH10_SLICING_ATTACK");
		SOUND_BOOK4_CH10_SLICING_ATTACK2 = aMgr.GetSoundThrow("SOUND_BOOK4_CH10_SLICING_ATTACK2");
		SOUND_BOOK4_CH10_SMOKE_ATTACK2 = aMgr.GetSoundThrow("SOUND_BOOK4_CH10_SMOKE_ATTACK2");
		SOUND_BOOK4_CH10_SQ_MAM_ATTACK2 = aMgr.GetSoundThrow("SOUND_BOOK4_CH10_SQ_MAM_ATTACK2");
		SOUND_BOOK4_CH10_SQ_MAM_DEATH = aMgr.GetSoundThrow("SOUND_BOOK4_CH10_SQ_MAM_DEATH");
		SOUND_BOOK4_CH10_WITCH_LAUGH = aMgr.GetSoundThrow("SOUND_BOOK4_CH10_WITCH_LAUGH");
		SOUND_BOOK4_CH10_WITCH_LAUGH2 = aMgr.GetSoundThrow("SOUND_BOOK4_CH10_WITCH_LAUGH2");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// Book4Chapter2 Resources
Image* Sexy::IMAGE_B4A_BG2;
int Sexy::SOUND_BOOK4_CH2_BOVINE_ATTACK1;
int Sexy::SOUND_BOOK4_CH2_BOVINE_ATTACK2;
int Sexy::SOUND_BOOK4_CH2_BOVINE_IMPACT;
int Sexy::SOUND_BOOK4_CH2_CHICKEN_ATTACK1;
int Sexy::SOUND_BOOK4_CH2_CHICKEN_ATTACK2;
int Sexy::SOUND_BOOK4_CH2_CHICKEN_IMPACT;
int Sexy::SOUND_BOOK4_CH2_EXPLOSION_1;
int Sexy::SOUND_BOOK4_CH2_MALE_LAUGH2;
int Sexy::SOUND_BOOK4_CH2_MALE_LOW_PAIN;
int Sexy::SOUND_BOOK4_CH2_MALE_PAIN;
int Sexy::SOUND_BOOK4_CH2_PIG_ATTACK;
int Sexy::SOUND_BOOK4_CH2_PIG_ATTACK2;
int Sexy::SOUND_BOOK4_CH2_PIG_SQUEAL2;
int Sexy::SOUND_BOOK4_CH2_SHEEP_BLEAT;
int Sexy::SOUND_BOOK4_CH2_SLICING_ATTACK2;

bool Sexy::ExtractBook4Chapter2Resources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_B4A_BG2 = aMgr.GetImageThrow("IMAGE_B4A_BG2");
		SOUND_BOOK4_CH2_BOVINE_ATTACK1 = aMgr.GetSoundThrow("SOUND_BOOK4_CH2_BOVINE_ATTACK1");
		SOUND_BOOK4_CH2_BOVINE_ATTACK2 = aMgr.GetSoundThrow("SOUND_BOOK4_CH2_BOVINE_ATTACK2");
		SOUND_BOOK4_CH2_BOVINE_IMPACT = aMgr.GetSoundThrow("SOUND_BOOK4_CH2_BOVINE_IMPACT");
		SOUND_BOOK4_CH2_CHICKEN_ATTACK1 = aMgr.GetSoundThrow("SOUND_BOOK4_CH2_CHICKEN_ATTACK1");
		SOUND_BOOK4_CH2_CHICKEN_ATTACK2 = aMgr.GetSoundThrow("SOUND_BOOK4_CH2_CHICKEN_ATTACK2");
		SOUND_BOOK4_CH2_CHICKEN_IMPACT = aMgr.GetSoundThrow("SOUND_BOOK4_CH2_CHICKEN_IMPACT");
		SOUND_BOOK4_CH2_EXPLOSION_1 = aMgr.GetSoundThrow("SOUND_BOOK4_CH2_EXPLOSION_1");
		SOUND_BOOK4_CH2_MALE_LAUGH2 = aMgr.GetSoundThrow("SOUND_BOOK4_CH2_MALE_LAUGH2");
		SOUND_BOOK4_CH2_MALE_LOW_PAIN = aMgr.GetSoundThrow("SOUND_BOOK4_CH2_MALE_LOW_PAIN");
		SOUND_BOOK4_CH2_MALE_PAIN = aMgr.GetSoundThrow("SOUND_BOOK4_CH2_MALE_PAIN");
		SOUND_BOOK4_CH2_PIG_ATTACK = aMgr.GetSoundThrow("SOUND_BOOK4_CH2_PIG_ATTACK");
		SOUND_BOOK4_CH2_PIG_ATTACK2 = aMgr.GetSoundThrow("SOUND_BOOK4_CH2_PIG_ATTACK2");
		SOUND_BOOK4_CH2_PIG_SQUEAL2 = aMgr.GetSoundThrow("SOUND_BOOK4_CH2_PIG_SQUEAL2");
		SOUND_BOOK4_CH2_SHEEP_BLEAT = aMgr.GetSoundThrow("SOUND_BOOK4_CH2_SHEEP_BLEAT");
		SOUND_BOOK4_CH2_SLICING_ATTACK2 = aMgr.GetSoundThrow("SOUND_BOOK4_CH2_SLICING_ATTACK2");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// Book4Chapter3 Resources
Image* Sexy::IMAGE_B4A_BG3;
int Sexy::SOUND_BOOK4_CH3_CS_GOOSE;
int Sexy::SOUND_BOOK4_CH3_DOG_BARK1;
int Sexy::SOUND_BOOK4_CH3_DOG_BARK2;
int Sexy::SOUND_BOOK4_CH3_DOG_WHIMPER;
int Sexy::SOUND_BOOK4_CH3_MISC_IMPACT;
int Sexy::SOUND_BOOK4_CH3_MISC_IMPACT2;
int Sexy::SOUND_BOOK4_CH3_PIG_ATTACK;
int Sexy::SOUND_BOOK4_CH3_PIG_ATTACK2;
int Sexy::SOUND_BOOK4_CH3_PIG_SQUEAL;
int Sexy::SOUND_BOOK4_CH3_PIG_SQUEAL2;
int Sexy::SOUND_BOOK4_CH3_WITCH_GROAN;
int Sexy::SOUND_BOOK4_CH3_WITCH_LAUGH;
int Sexy::SOUND_BOOK4_CH3_WITCH_LAUGH2;
int Sexy::SOUND_BOOK4_CH3_WOLF_HOWL;

bool Sexy::ExtractBook4Chapter3Resources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_B4A_BG3 = aMgr.GetImageThrow("IMAGE_B4A_BG3");
		SOUND_BOOK4_CH3_CS_GOOSE = aMgr.GetSoundThrow("SOUND_BOOK4_CH3_CS_GOOSE");
		SOUND_BOOK4_CH3_DOG_BARK1 = aMgr.GetSoundThrow("SOUND_BOOK4_CH3_DOG_BARK1");
		SOUND_BOOK4_CH3_DOG_BARK2 = aMgr.GetSoundThrow("SOUND_BOOK4_CH3_DOG_BARK2");
		SOUND_BOOK4_CH3_DOG_WHIMPER = aMgr.GetSoundThrow("SOUND_BOOK4_CH3_DOG_WHIMPER");
		SOUND_BOOK4_CH3_MISC_IMPACT = aMgr.GetSoundThrow("SOUND_BOOK4_CH3_MISC_IMPACT");
		SOUND_BOOK4_CH3_MISC_IMPACT2 = aMgr.GetSoundThrow("SOUND_BOOK4_CH3_MISC_IMPACT2");
		SOUND_BOOK4_CH3_PIG_ATTACK = aMgr.GetSoundThrow("SOUND_BOOK4_CH3_PIG_ATTACK");
		SOUND_BOOK4_CH3_PIG_ATTACK2 = aMgr.GetSoundThrow("SOUND_BOOK4_CH3_PIG_ATTACK2");
		SOUND_BOOK4_CH3_PIG_SQUEAL = aMgr.GetSoundThrow("SOUND_BOOK4_CH3_PIG_SQUEAL");
		SOUND_BOOK4_CH3_PIG_SQUEAL2 = aMgr.GetSoundThrow("SOUND_BOOK4_CH3_PIG_SQUEAL2");
		SOUND_BOOK4_CH3_WITCH_GROAN = aMgr.GetSoundThrow("SOUND_BOOK4_CH3_WITCH_GROAN");
		SOUND_BOOK4_CH3_WITCH_LAUGH = aMgr.GetSoundThrow("SOUND_BOOK4_CH3_WITCH_LAUGH");
		SOUND_BOOK4_CH3_WITCH_LAUGH2 = aMgr.GetSoundThrow("SOUND_BOOK4_CH3_WITCH_LAUGH2");
		SOUND_BOOK4_CH3_WOLF_HOWL = aMgr.GetSoundThrow("SOUND_BOOK4_CH3_WOLF_HOWL");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// Book4Chapter4 Resources
Image* Sexy::IMAGE_B4A_BG4;
int Sexy::SOUND_BOOK4_CH4_BLUNT_IMPACT1;
int Sexy::SOUND_BOOK4_CH4_CHICKEN_ATTACK1;
int Sexy::SOUND_BOOK4_CH4_CHICKEN_IMPACT;
int Sexy::SOUND_BOOK4_CH4_EXPLOSION_1;
int Sexy::SOUND_BOOK4_CH4_EXPLOSION_3;
int Sexy::SOUND_BOOK4_CH4_FEMALE_GROAN2;
int Sexy::SOUND_BOOK4_CH4_FIREWORK_1;
int Sexy::SOUND_BOOK4_CH4_FIRE_3;
int Sexy::SOUND_BOOK4_CH4_GENERIC_SLOSH;
int Sexy::SOUND_BOOK4_CH4_GIANT_GRUNT2;
int Sexy::SOUND_BOOK4_CH4_KUBWA_ROAR;
int Sexy::SOUND_BOOK4_CH4_MALE_ANGER;
int Sexy::SOUND_BOOK4_CH4_MALE_GRUNT1;
int Sexy::SOUND_BOOK4_CH4_MALE_GRUNT2;
int Sexy::SOUND_BOOK4_CH4_MALE_LAUGH;
int Sexy::SOUND_BOOK4_CH4_MALE_LAUGH2;
int Sexy::SOUND_BOOK4_CH4_MALE_LOW_ANGER;
int Sexy::SOUND_BOOK4_CH4_MISC_IMPACT2;
int Sexy::SOUND_BOOK4_CH4_SWORD_IMPACT3;
int Sexy::SOUND_BOOK4_CH4_WET_IMPACT2;

bool Sexy::ExtractBook4Chapter4Resources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_B4A_BG4 = aMgr.GetImageThrow("IMAGE_B4A_BG4");
		SOUND_BOOK4_CH4_BLUNT_IMPACT1 = aMgr.GetSoundThrow("SOUND_BOOK4_CH4_BLUNT_IMPACT1");
		SOUND_BOOK4_CH4_CHICKEN_ATTACK1 = aMgr.GetSoundThrow("SOUND_BOOK4_CH4_CHICKEN_ATTACK1");
		SOUND_BOOK4_CH4_CHICKEN_IMPACT = aMgr.GetSoundThrow("SOUND_BOOK4_CH4_CHICKEN_IMPACT");
		SOUND_BOOK4_CH4_EXPLOSION_1 = aMgr.GetSoundThrow("SOUND_BOOK4_CH4_EXPLOSION_1");
		SOUND_BOOK4_CH4_EXPLOSION_3 = aMgr.GetSoundThrow("SOUND_BOOK4_CH4_EXPLOSION_3");
		SOUND_BOOK4_CH4_FEMALE_GROAN2 = aMgr.GetSoundThrow("SOUND_BOOK4_CH4_FEMALE_GROAN2");
		SOUND_BOOK4_CH4_FIREWORK_1 = aMgr.GetSoundThrow("SOUND_BOOK4_CH4_FIREWORK_1");
		SOUND_BOOK4_CH4_FIRE_3 = aMgr.GetSoundThrow("SOUND_BOOK4_CH4_FIRE_3");
		SOUND_BOOK4_CH4_GENERIC_SLOSH = aMgr.GetSoundThrow("SOUND_BOOK4_CH4_GENERIC_SLOSH");
		SOUND_BOOK4_CH4_GIANT_GRUNT2 = aMgr.GetSoundThrow("SOUND_BOOK4_CH4_GIANT_GRUNT2");
		SOUND_BOOK4_CH4_KUBWA_ROAR = aMgr.GetSoundThrow("SOUND_BOOK4_CH4_KUBWA_ROAR");
		SOUND_BOOK4_CH4_MALE_ANGER = aMgr.GetSoundThrow("SOUND_BOOK4_CH4_MALE_ANGER");
		SOUND_BOOK4_CH4_MALE_GRUNT1 = aMgr.GetSoundThrow("SOUND_BOOK4_CH4_MALE_GRUNT1");
		SOUND_BOOK4_CH4_MALE_GRUNT2 = aMgr.GetSoundThrow("SOUND_BOOK4_CH4_MALE_GRUNT2");
		SOUND_BOOK4_CH4_MALE_LAUGH = aMgr.GetSoundThrow("SOUND_BOOK4_CH4_MALE_LAUGH");
		SOUND_BOOK4_CH4_MALE_LAUGH2 = aMgr.GetSoundThrow("SOUND_BOOK4_CH4_MALE_LAUGH2");
		SOUND_BOOK4_CH4_MALE_LOW_ANGER = aMgr.GetSoundThrow("SOUND_BOOK4_CH4_MALE_LOW_ANGER");
		SOUND_BOOK4_CH4_MISC_IMPACT2 = aMgr.GetSoundThrow("SOUND_BOOK4_CH4_MISC_IMPACT2");
		SOUND_BOOK4_CH4_SWORD_IMPACT3 = aMgr.GetSoundThrow("SOUND_BOOK4_CH4_SWORD_IMPACT3");
		SOUND_BOOK4_CH4_WET_IMPACT2 = aMgr.GetSoundThrow("SOUND_BOOK4_CH4_WET_IMPACT2");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// Book4Chapter5 Resources
Image* Sexy::IMAGE_B4A_BG5;
int Sexy::SOUND_BOOK4_CH5_BEAR_ATTACK;
int Sexy::SOUND_BOOK4_CH5_BEAR_IMPACT;
int Sexy::SOUND_BOOK4_CH5_BEAR_ROAR;
int Sexy::SOUND_BOOK4_CH5_FIRE_3;
int Sexy::SOUND_BOOK4_CH5_FIRE_6;
int Sexy::SOUND_BOOK4_CH5_PLATE_ATTACK4;
int Sexy::SOUND_BOOK4_CH5_PLATE_IMPACT5;
int Sexy::SOUND_BOOK4_CH5_WET_IMPACT1;

bool Sexy::ExtractBook4Chapter5Resources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_B4A_BG5 = aMgr.GetImageThrow("IMAGE_B4A_BG5");
		SOUND_BOOK4_CH5_BEAR_ATTACK = aMgr.GetSoundThrow("SOUND_BOOK4_CH5_BEAR_ATTACK");
		SOUND_BOOK4_CH5_BEAR_IMPACT = aMgr.GetSoundThrow("SOUND_BOOK4_CH5_BEAR_IMPACT");
		SOUND_BOOK4_CH5_BEAR_ROAR = aMgr.GetSoundThrow("SOUND_BOOK4_CH5_BEAR_ROAR");
		SOUND_BOOK4_CH5_FIRE_3 = aMgr.GetSoundThrow("SOUND_BOOK4_CH5_FIRE_3");
		SOUND_BOOK4_CH5_FIRE_6 = aMgr.GetSoundThrow("SOUND_BOOK4_CH5_FIRE_6");
		SOUND_BOOK4_CH5_PLATE_ATTACK4 = aMgr.GetSoundThrow("SOUND_BOOK4_CH5_PLATE_ATTACK4");
		SOUND_BOOK4_CH5_PLATE_IMPACT5 = aMgr.GetSoundThrow("SOUND_BOOK4_CH5_PLATE_IMPACT5");
		SOUND_BOOK4_CH5_WET_IMPACT1 = aMgr.GetSoundThrow("SOUND_BOOK4_CH5_WET_IMPACT1");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// Book4Chapter6 Resources
Image* Sexy::IMAGE_B4A_BG6;
int Sexy::SOUND_BOOK4_CH6_EXPLOSION_1;
int Sexy::SOUND_BOOK4_CH6_EXPLOSION_3;
int Sexy::SOUND_BOOK4_CH6_FEMALE_GROAN2;
int Sexy::SOUND_BOOK4_CH6_FEMALE_MMMMM;
int Sexy::SOUND_BOOK4_CH6_MALE_LAUGH;
int Sexy::SOUND_BOOK4_CH6_MALE_LAUGH2;
int Sexy::SOUND_BOOK4_CH6_MALE_PAIN;
int Sexy::SOUND_BOOK4_CH6_SLUMP_SMALL;
int Sexy::SOUND_BOOK4_CH6_SMOKE_ATTACK2;
int Sexy::SOUND_BOOK4_CH6_WITCH_GROAN;
int Sexy::SOUND_BOOK4_CH6_WITCH_LAUGH;
int Sexy::SOUND_BOOK4_CH6_WITCH_LAUGH2;

bool Sexy::ExtractBook4Chapter6Resources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_B4A_BG6 = aMgr.GetImageThrow("IMAGE_B4A_BG6");
		SOUND_BOOK4_CH6_EXPLOSION_1 = aMgr.GetSoundThrow("SOUND_BOOK4_CH6_EXPLOSION_1");
		SOUND_BOOK4_CH6_EXPLOSION_3 = aMgr.GetSoundThrow("SOUND_BOOK4_CH6_EXPLOSION_3");
		SOUND_BOOK4_CH6_FEMALE_GROAN2 = aMgr.GetSoundThrow("SOUND_BOOK4_CH6_FEMALE_GROAN2");
		SOUND_BOOK4_CH6_FEMALE_MMMMM = aMgr.GetSoundThrow("SOUND_BOOK4_CH6_FEMALE_MMMMM");
		SOUND_BOOK4_CH6_MALE_LAUGH = aMgr.GetSoundThrow("SOUND_BOOK4_CH6_MALE_LAUGH");
		SOUND_BOOK4_CH6_MALE_LAUGH2 = aMgr.GetSoundThrow("SOUND_BOOK4_CH6_MALE_LAUGH2");
		SOUND_BOOK4_CH6_MALE_PAIN = aMgr.GetSoundThrow("SOUND_BOOK4_CH6_MALE_PAIN");
		SOUND_BOOK4_CH6_SLUMP_SMALL = aMgr.GetSoundThrow("SOUND_BOOK4_CH6_SLUMP_SMALL");
		SOUND_BOOK4_CH6_SMOKE_ATTACK2 = aMgr.GetSoundThrow("SOUND_BOOK4_CH6_SMOKE_ATTACK2");
		SOUND_BOOK4_CH6_WITCH_GROAN = aMgr.GetSoundThrow("SOUND_BOOK4_CH6_WITCH_GROAN");
		SOUND_BOOK4_CH6_WITCH_LAUGH = aMgr.GetSoundThrow("SOUND_BOOK4_CH6_WITCH_LAUGH");
		SOUND_BOOK4_CH6_WITCH_LAUGH2 = aMgr.GetSoundThrow("SOUND_BOOK4_CH6_WITCH_LAUGH2");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// Book4Chapter7 Resources
Image* Sexy::IMAGE_B4A_BG7;
Image* Sexy::IMAGE_B4A_CATEPILLAR_BOSS_BATTLE;
int Sexy::SOUND_BOOK4_CH7_CS_CAT;
int Sexy::SOUND_BOOK4_CH7_MALE_LAUGH;
int Sexy::SOUND_BOOK4_CH7_MALE_LAUGH2;
int Sexy::SOUND_BOOK4_CH7_SMOKE_ATTACK;
int Sexy::SOUND_BOOK4_CH7_SMOKE_ATTACK2;
int Sexy::SOUND_BOOK4_CH7_SMOKE_IMPACT;

bool Sexy::ExtractBook4Chapter7Resources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_B4A_BG7 = aMgr.GetImageThrow("IMAGE_B4A_BG7");
		IMAGE_B4A_CATEPILLAR_BOSS_BATTLE = aMgr.GetImageThrow("IMAGE_B4A_CATEPILLAR_BOSS_BATTLE");
		SOUND_BOOK4_CH7_CS_CAT = aMgr.GetSoundThrow("SOUND_BOOK4_CH7_CS_CAT");
		SOUND_BOOK4_CH7_MALE_LAUGH = aMgr.GetSoundThrow("SOUND_BOOK4_CH7_MALE_LAUGH");
		SOUND_BOOK4_CH7_MALE_LAUGH2 = aMgr.GetSoundThrow("SOUND_BOOK4_CH7_MALE_LAUGH2");
		SOUND_BOOK4_CH7_SMOKE_ATTACK = aMgr.GetSoundThrow("SOUND_BOOK4_CH7_SMOKE_ATTACK");
		SOUND_BOOK4_CH7_SMOKE_ATTACK2 = aMgr.GetSoundThrow("SOUND_BOOK4_CH7_SMOKE_ATTACK2");
		SOUND_BOOK4_CH7_SMOKE_IMPACT = aMgr.GetSoundThrow("SOUND_BOOK4_CH7_SMOKE_IMPACT");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// Book4Chapter8 Resources
Image* Sexy::IMAGE_B4A_BG8;
int Sexy::SOUND_BOOK4_CH8_FIRE_3;
int Sexy::SOUND_BOOK4_CH8_FIRE_6;
int Sexy::SOUND_BOOK4_CH8_MALE_LAUGH;
int Sexy::SOUND_BOOK4_CH8_MALE_LAUGH2;
int Sexy::SOUND_BOOK4_CH8_PLATE_ATTACK2;
int Sexy::SOUND_BOOK4_CH8_PLATE_ATTACK3;
int Sexy::SOUND_BOOK4_CH8_PLATE_ATTACK4;
int Sexy::SOUND_BOOK4_CH8_PLATE_IMPACT3;
int Sexy::SOUND_BOOK4_CH8_PLATE_IMPACT4;
int Sexy::SOUND_BOOK4_CH8_PLATE_IMPACT5;
int Sexy::SOUND_BOOK4_CH8_PLATE_IMPACT6;
int Sexy::SOUND_BOOK4_CH8_SQ_MAM_ATTACK;
int Sexy::SOUND_BOOK4_CH8_SQ_MAM_ATTACK2;
int Sexy::SOUND_BOOK4_CH8_SQ_MAM_DEATH;

bool Sexy::ExtractBook4Chapter8Resources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_B4A_BG8 = aMgr.GetImageThrow("IMAGE_B4A_BG8");
		SOUND_BOOK4_CH8_FIRE_3 = aMgr.GetSoundThrow("SOUND_BOOK4_CH8_FIRE_3");
		SOUND_BOOK4_CH8_FIRE_6 = aMgr.GetSoundThrow("SOUND_BOOK4_CH8_FIRE_6");
		SOUND_BOOK4_CH8_MALE_LAUGH = aMgr.GetSoundThrow("SOUND_BOOK4_CH8_MALE_LAUGH");
		SOUND_BOOK4_CH8_MALE_LAUGH2 = aMgr.GetSoundThrow("SOUND_BOOK4_CH8_MALE_LAUGH2");
		SOUND_BOOK4_CH8_PLATE_ATTACK2 = aMgr.GetSoundThrow("SOUND_BOOK4_CH8_PLATE_ATTACK2");
		SOUND_BOOK4_CH8_PLATE_ATTACK3 = aMgr.GetSoundThrow("SOUND_BOOK4_CH8_PLATE_ATTACK3");
		SOUND_BOOK4_CH8_PLATE_ATTACK4 = aMgr.GetSoundThrow("SOUND_BOOK4_CH8_PLATE_ATTACK4");
		SOUND_BOOK4_CH8_PLATE_IMPACT3 = aMgr.GetSoundThrow("SOUND_BOOK4_CH8_PLATE_IMPACT3");
		SOUND_BOOK4_CH8_PLATE_IMPACT4 = aMgr.GetSoundThrow("SOUND_BOOK4_CH8_PLATE_IMPACT4");
		SOUND_BOOK4_CH8_PLATE_IMPACT5 = aMgr.GetSoundThrow("SOUND_BOOK4_CH8_PLATE_IMPACT5");
		SOUND_BOOK4_CH8_PLATE_IMPACT6 = aMgr.GetSoundThrow("SOUND_BOOK4_CH8_PLATE_IMPACT6");
		SOUND_BOOK4_CH8_SQ_MAM_ATTACK = aMgr.GetSoundThrow("SOUND_BOOK4_CH8_SQ_MAM_ATTACK");
		SOUND_BOOK4_CH8_SQ_MAM_ATTACK2 = aMgr.GetSoundThrow("SOUND_BOOK4_CH8_SQ_MAM_ATTACK2");
		SOUND_BOOK4_CH8_SQ_MAM_DEATH = aMgr.GetSoundThrow("SOUND_BOOK4_CH8_SQ_MAM_DEATH");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// Book4Chapter9 Resources
Image* Sexy::IMAGE_B4A_BG9;
int Sexy::SOUND_BOOK4_CH9_DOPEY_ATTACK;
int Sexy::SOUND_BOOK4_CH9_DOPEY_IMPACT;
int Sexy::SOUND_BOOK4_CH9_DRAGON_BITE;
int Sexy::SOUND_BOOK4_CH9_DRAGON_DEATH;
int Sexy::SOUND_BOOK4_CH9_DRAGON_PAIN;
int Sexy::SOUND_BOOK4_CH9_DRAGON_ROAR;
int Sexy::SOUND_BOOK4_CH9_MALE_LAUGH;
int Sexy::SOUND_BOOK4_CH9_MALE_LAUGH2;
int Sexy::SOUND_BOOK4_CH9_MALE_PAIN;
int Sexy::SOUND_BOOK4_CH9_OGRE_CHALLENGE;
int Sexy::SOUND_BOOK4_CH9_OGRE_IMPACT;
int Sexy::SOUND_BOOK4_CH9_SLICING_ATTACK;
int Sexy::SOUND_BOOK4_CH9_SLICING_ATTACK2;
int Sexy::SOUND_BOOK4_CH9_SMOKE_ATTACK2;

bool Sexy::ExtractBook4Chapter9Resources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_B4A_BG9 = aMgr.GetImageThrow("IMAGE_B4A_BG9");
		SOUND_BOOK4_CH9_DOPEY_ATTACK = aMgr.GetSoundThrow("SOUND_BOOK4_CH9_DOPEY_ATTACK");
		SOUND_BOOK4_CH9_DOPEY_IMPACT = aMgr.GetSoundThrow("SOUND_BOOK4_CH9_DOPEY_IMPACT");
		SOUND_BOOK4_CH9_DRAGON_BITE = aMgr.GetSoundThrow("SOUND_BOOK4_CH9_DRAGON_BITE");
		SOUND_BOOK4_CH9_DRAGON_DEATH = aMgr.GetSoundThrow("SOUND_BOOK4_CH9_DRAGON_DEATH");
		SOUND_BOOK4_CH9_DRAGON_PAIN = aMgr.GetSoundThrow("SOUND_BOOK4_CH9_DRAGON_PAIN");
		SOUND_BOOK4_CH9_DRAGON_ROAR = aMgr.GetSoundThrow("SOUND_BOOK4_CH9_DRAGON_ROAR");
		SOUND_BOOK4_CH9_MALE_LAUGH = aMgr.GetSoundThrow("SOUND_BOOK4_CH9_MALE_LAUGH");
		SOUND_BOOK4_CH9_MALE_LAUGH2 = aMgr.GetSoundThrow("SOUND_BOOK4_CH9_MALE_LAUGH2");
		SOUND_BOOK4_CH9_MALE_PAIN = aMgr.GetSoundThrow("SOUND_BOOK4_CH9_MALE_PAIN");
		SOUND_BOOK4_CH9_OGRE_CHALLENGE = aMgr.GetSoundThrow("SOUND_BOOK4_CH9_OGRE_CHALLENGE");
		SOUND_BOOK4_CH9_OGRE_IMPACT = aMgr.GetSoundThrow("SOUND_BOOK4_CH9_OGRE_IMPACT");
		SOUND_BOOK4_CH9_SLICING_ATTACK = aMgr.GetSoundThrow("SOUND_BOOK4_CH9_SLICING_ATTACK");
		SOUND_BOOK4_CH9_SLICING_ATTACK2 = aMgr.GetSoundThrow("SOUND_BOOK4_CH9_SLICING_ATTACK2");
		SOUND_BOOK4_CH9_SMOKE_ATTACK2 = aMgr.GetSoundThrow("SOUND_BOOK4_CH9_SMOKE_ATTACK2");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// Book4Init Resources
Image* Sexy::IMAGE_B4_ICONANIM1;
Image* Sexy::IMAGE_B4_ICONANIM10;
Image* Sexy::IMAGE_B4_ICONANIM2;
Image* Sexy::IMAGE_B4_ICONANIM3;
Image* Sexy::IMAGE_B4_ICONANIM4;
Image* Sexy::IMAGE_B4_ICONANIM5;
Image* Sexy::IMAGE_B4_ICONANIM6;
Image* Sexy::IMAGE_B4_ICONANIM7;
Image* Sexy::IMAGE_B4_ICONANIM8;
Image* Sexy::IMAGE_B4_ICONANIM9;
Image* Sexy::IMAGE_B4_ICONMASK1;
Image* Sexy::IMAGE_B4_ICONMASK10;
Image* Sexy::IMAGE_B4_ICONMASK2;
Image* Sexy::IMAGE_B4_ICONMASK3;
Image* Sexy::IMAGE_B4_ICONMASK4;
Image* Sexy::IMAGE_B4_ICONMASK5;
Image* Sexy::IMAGE_B4_ICONMASK6;
Image* Sexy::IMAGE_B4_ICONMASK7;
Image* Sexy::IMAGE_B4_ICONMASK8;
Image* Sexy::IMAGE_B4_ICONMASK9;
Image* Sexy::IMAGE_B4_MAP;
Image* Sexy::IMAGE_B4_MAPSCREEN_BANNER;
Image* Sexy::IMAGE_B4_MINIMAP_ICONS;
Image* Sexy::IMAGE_TUT_PIC_OLDMC;
Image* Sexy::IMAGE_TUT_PIC_QUEEN;
Image* Sexy::IMAGE_TUT_PIC_QUEEN_ANGRY;

bool Sexy::ExtractBook4InitResources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_B4_ICONANIM1 = aMgr.GetImageThrow("IMAGE_B4_ICONANIM1");
		IMAGE_B4_ICONANIM10 = aMgr.GetImageThrow("IMAGE_B4_ICONANIM10");
		IMAGE_B4_ICONANIM2 = aMgr.GetImageThrow("IMAGE_B4_ICONANIM2");
		IMAGE_B4_ICONANIM3 = aMgr.GetImageThrow("IMAGE_B4_ICONANIM3");
		IMAGE_B4_ICONANIM4 = aMgr.GetImageThrow("IMAGE_B4_ICONANIM4");
		IMAGE_B4_ICONANIM5 = aMgr.GetImageThrow("IMAGE_B4_ICONANIM5");
		IMAGE_B4_ICONANIM6 = aMgr.GetImageThrow("IMAGE_B4_ICONANIM6");
		IMAGE_B4_ICONANIM7 = aMgr.GetImageThrow("IMAGE_B4_ICONANIM7");
		IMAGE_B4_ICONANIM8 = aMgr.GetImageThrow("IMAGE_B4_ICONANIM8");
		IMAGE_B4_ICONANIM9 = aMgr.GetImageThrow("IMAGE_B4_ICONANIM9");
		IMAGE_B4_ICONMASK1 = aMgr.GetImageThrow("IMAGE_B4_ICONMASK1");
		IMAGE_B4_ICONMASK10 = aMgr.GetImageThrow("IMAGE_B4_ICONMASK10");
		IMAGE_B4_ICONMASK2 = aMgr.GetImageThrow("IMAGE_B4_ICONMASK2");
		IMAGE_B4_ICONMASK3 = aMgr.GetImageThrow("IMAGE_B4_ICONMASK3");
		IMAGE_B4_ICONMASK4 = aMgr.GetImageThrow("IMAGE_B4_ICONMASK4");
		IMAGE_B4_ICONMASK5 = aMgr.GetImageThrow("IMAGE_B4_ICONMASK5");
		IMAGE_B4_ICONMASK6 = aMgr.GetImageThrow("IMAGE_B4_ICONMASK6");
		IMAGE_B4_ICONMASK7 = aMgr.GetImageThrow("IMAGE_B4_ICONMASK7");
		IMAGE_B4_ICONMASK8 = aMgr.GetImageThrow("IMAGE_B4_ICONMASK8");
		IMAGE_B4_ICONMASK9 = aMgr.GetImageThrow("IMAGE_B4_ICONMASK9");
		IMAGE_B4_MAP = aMgr.GetImageThrow("IMAGE_B4_MAP");
		IMAGE_B4_MAPSCREEN_BANNER = aMgr.GetImageThrow("IMAGE_B4_MAPSCREEN_BANNER");
		IMAGE_B4_MINIMAP_ICONS = aMgr.GetImageThrow("IMAGE_B4_MINIMAP_ICONS");
		IMAGE_TUT_PIC_OLDMC = aMgr.GetImageThrow("IMAGE_TUT_PIC_OLDMC");
		IMAGE_TUT_PIC_QUEEN = aMgr.GetImageThrow("IMAGE_TUT_PIC_QUEEN");
		IMAGE_TUT_PIC_QUEEN_ANGRY = aMgr.GetImageThrow("IMAGE_TUT_PIC_QUEEN_ANGRY");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

static void* gResources[] =
{
	&IMAGE_B4_MINIMAP_ICONS,
	&IMAGE_B4_MAPSCREEN_BANNER,
	&IMAGE_B4_ICONANIM1,
	&IMAGE_B4_ICONANIM2,
	&IMAGE_B4_ICONANIM3,
	&IMAGE_B4_ICONANIM4,
	&IMAGE_B4_ICONANIM5,
	&IMAGE_B4_ICONANIM6,
	&IMAGE_B4_ICONANIM7,
	&IMAGE_B4_ICONANIM8,
	&IMAGE_B4_ICONANIM9,
	&IMAGE_B4_ICONANIM10,
	&IMAGE_B4_ICONMASK1,
	&IMAGE_B4_ICONMASK2,
	&IMAGE_B4_ICONMASK3,
	&IMAGE_B4_ICONMASK4,
	&IMAGE_B4_ICONMASK5,
	&IMAGE_B4_ICONMASK6,
	&IMAGE_B4_ICONMASK7,
	&IMAGE_B4_ICONMASK8,
	&IMAGE_B4_ICONMASK9,
	&IMAGE_B4_ICONMASK10,
	&IMAGE_B4_MAP,
	&IMAGE_TUT_PIC_OLDMC,
	&IMAGE_TUT_PIC_QUEEN_ANGRY,
	&IMAGE_TUT_PIC_QUEEN,
	&IMAGE_B4_LEFT_FACING_ARROW,
	&IMAGE_B4A_BG1,
	&SOUND_BOOK4_CH1_FELINE_ENGAGE,
	&SOUND_BOOK4_CH1_FELINE_ROAR,
	&SOUND_BOOK4_CH1_STRING_ATTACK,
	&SOUND_BOOK4_CH1_STRING_DEATH,
	&SOUND_BOOK4_CH1_STRING_IMPACT,
	&SOUND_BOOK4_CH1_BOVINE_ATTACK1,
	&SOUND_BOOK4_CH1_BOVINE_ATTACK2,
	&SOUND_BOOK4_CH1_BOVINE_IMPACT,
	&SOUND_BOOK4_CH1_FIRE_6,
	&SOUND_BOOK4_CH1_SPARKLE_ATTACK,
	&SOUND_BOOK4_CH1_PLATE_ATTACK2,
	&SOUND_BOOK4_CH1_PLATE_ATTACK3,
	&SOUND_BOOK4_CH1_PLATE_IMPACT3,
	&SOUND_BOOK4_CH1_PLATE_IMPACT4,
	&SOUND_BOOK4_CH1_PLATE_IMPACT5,
	&SOUND_BOOK4_CH1_PLATE_IMPACT6,
	&IMAGE_B4A_BG2,
	&SOUND_BOOK4_CH2_PIG_SQUEAL2,
	&SOUND_BOOK4_CH2_PIG_ATTACK,
	&SOUND_BOOK4_CH2_PIG_ATTACK2,
	&SOUND_BOOK4_CH2_SHEEP_BLEAT,
	&SOUND_BOOK4_CH2_SLICING_ATTACK2,
	&SOUND_BOOK4_CH2_MALE_LOW_PAIN,
	&SOUND_BOOK4_CH2_MALE_LAUGH2,
	&SOUND_BOOK4_CH2_MALE_PAIN,
	&SOUND_BOOK4_CH2_BOVINE_ATTACK2,
	&SOUND_BOOK4_CH2_CHICKEN_ATTACK1,
	&SOUND_BOOK4_CH2_CHICKEN_ATTACK2,
	&SOUND_BOOK4_CH2_CHICKEN_IMPACT,
	&SOUND_BOOK4_CH2_EXPLOSION_1,
	&SOUND_BOOK4_CH2_BOVINE_ATTACK1,
	&SOUND_BOOK4_CH2_BOVINE_IMPACT,
	&IMAGE_B4A_BG3,
	&SOUND_BOOK4_CH3_DOG_BARK1,
	&SOUND_BOOK4_CH3_DOG_BARK2,
	&SOUND_BOOK4_CH3_DOG_WHIMPER,
	&SOUND_BOOK4_CH3_MISC_IMPACT,
	&SOUND_BOOK4_CH3_MISC_IMPACT2,
	&SOUND_BOOK4_CH3_PIG_SQUEAL,
	&SOUND_BOOK4_CH3_PIG_SQUEAL2,
	&SOUND_BOOK4_CH3_PIG_ATTACK,
	&SOUND_BOOK4_CH3_PIG_ATTACK2,
	&SOUND_BOOK4_CH3_WITCH_GROAN,
	&SOUND_BOOK4_CH3_WITCH_LAUGH,
	&SOUND_BOOK4_CH3_WITCH_LAUGH2,
	&SOUND_BOOK4_CH3_WOLF_HOWL,
	&SOUND_BOOK4_CH3_CS_GOOSE,
	&IMAGE_B4A_BG4,
	&SOUND_BOOK4_CH4_EXPLOSION_1,
	&SOUND_BOOK4_CH4_EXPLOSION_3,
	&SOUND_BOOK4_CH4_CHICKEN_ATTACK1,
	&SOUND_BOOK4_CH4_BLUNT_IMPACT1,
	&SOUND_BOOK4_CH4_CHICKEN_IMPACT,
	&SOUND_BOOK4_CH4_MALE_ANGER,
	&SOUND_BOOK4_CH4_MALE_LAUGH,
	&SOUND_BOOK4_CH4_MALE_LAUGH2,
	&SOUND_BOOK4_CH4_MALE_LOW_ANGER,
	&SOUND_BOOK4_CH4_MALE_GRUNT1,
	&SOUND_BOOK4_CH4_MALE_GRUNT2,
	&SOUND_BOOK4_CH4_GENERIC_SLOSH,
	&SOUND_BOOK4_CH4_FEMALE_GROAN2,
	&SOUND_BOOK4_CH4_MISC_IMPACT2,
	&SOUND_BOOK4_CH4_WET_IMPACT2,
	&SOUND_BOOK4_CH4_KUBWA_ROAR,
	&SOUND_BOOK4_CH4_GIANT_GRUNT2,
	&SOUND_BOOK4_CH4_FIRE_3,
	&SOUND_BOOK4_CH4_FIREWORK_1,
	&SOUND_BOOK4_CH4_SWORD_IMPACT3,
	&IMAGE_B4A_BG5,
	&SOUND_BOOK4_CH5_PLATE_ATTACK4,
	&SOUND_BOOK4_CH5_PLATE_IMPACT5,
	&SOUND_BOOK4_CH5_FIRE_3,
	&SOUND_BOOK4_CH5_FIRE_6,
	&SOUND_BOOK4_CH5_BEAR_ATTACK,
	&SOUND_BOOK4_CH5_BEAR_IMPACT,
	&SOUND_BOOK4_CH5_BEAR_ROAR,
	&SOUND_BOOK4_CH5_WET_IMPACT1,
	&IMAGE_B4A_BG6,
	&SOUND_BOOK4_CH6_MALE_LAUGH,
	&SOUND_BOOK4_CH6_MALE_LAUGH2,
	&SOUND_BOOK4_CH6_MALE_PAIN,
	&SOUND_BOOK4_CH6_FEMALE_GROAN2,
	&SOUND_BOOK4_CH6_SMOKE_ATTACK2,
	&SOUND_BOOK4_CH6_EXPLOSION_1,
	&SOUND_BOOK4_CH6_EXPLOSION_3,
	&SOUND_BOOK4_CH6_SLUMP_SMALL,
	&SOUND_BOOK4_CH6_WITCH_GROAN,
	&SOUND_BOOK4_CH6_WITCH_LAUGH,
	&SOUND_BOOK4_CH6_WITCH_LAUGH2,
	&SOUND_BOOK4_CH6_FEMALE_MMMMM,
	&IMAGE_B4A_BG7,
	&IMAGE_B4A_CATEPILLAR_BOSS_BATTLE,
	&SOUND_BOOK4_CH7_SMOKE_ATTACK,
	&SOUND_BOOK4_CH7_SMOKE_ATTACK2,
	&SOUND_BOOK4_CH7_SMOKE_IMPACT,
	&SOUND_BOOK4_CH7_MALE_LAUGH,
	&SOUND_BOOK4_CH7_MALE_LAUGH2,
	&SOUND_BOOK4_CH7_CS_CAT,
	&IMAGE_B4A_BG8,
	&SOUND_BOOK4_CH8_SQ_MAM_ATTACK,
	&SOUND_BOOK4_CH8_SQ_MAM_ATTACK2,
	&SOUND_BOOK4_CH8_SQ_MAM_DEATH,
	&SOUND_BOOK4_CH8_MALE_LAUGH,
	&SOUND_BOOK4_CH8_MALE_LAUGH2,
	&SOUND_BOOK4_CH8_PLATE_ATTACK2,
	&SOUND_BOOK4_CH8_PLATE_ATTACK3,
	&SOUND_BOOK4_CH8_PLATE_ATTACK4,
	&SOUND_BOOK4_CH8_PLATE_IMPACT3,
	&SOUND_BOOK4_CH8_PLATE_IMPACT4,
	&SOUND_BOOK4_CH8_PLATE_IMPACT5,
	&SOUND_BOOK4_CH8_PLATE_IMPACT6,
	&SOUND_BOOK4_CH8_FIRE_3,
	&SOUND_BOOK4_CH8_FIRE_6,
	&IMAGE_B4A_BG9,
	&SOUND_BOOK4_CH9_OGRE_CHALLENGE,
	&SOUND_BOOK4_CH9_OGRE_IMPACT,
	&SOUND_BOOK4_CH9_DOPEY_ATTACK,
	&SOUND_BOOK4_CH9_DOPEY_IMPACT,
	&SOUND_BOOK4_CH9_SMOKE_ATTACK2,
	&SOUND_BOOK4_CH9_DRAGON_BITE,
	&SOUND_BOOK4_CH9_DRAGON_DEATH,
	&SOUND_BOOK4_CH9_DRAGON_PAIN,
	&SOUND_BOOK4_CH9_DRAGON_ROAR,
	&SOUND_BOOK4_CH9_MALE_LAUGH,
	&SOUND_BOOK4_CH9_MALE_LAUGH2,
	&SOUND_BOOK4_CH9_MALE_PAIN,
	&SOUND_BOOK4_CH9_SLICING_ATTACK,
	&SOUND_BOOK4_CH9_SLICING_ATTACK2,
	&IMAGE_B4A_BG10,
	&SOUND_BOOK4_CH10_DOPEY_ATTACK,
	&SOUND_BOOK4_CH10_DOPEY_IMPACT,
	&SOUND_BOOK4_CH10_SMOKE_ATTACK2,
	&SOUND_BOOK4_CH10_WITCH_LAUGH,
	&SOUND_BOOK4_CH10_WITCH_LAUGH2,
	&SOUND_BOOK4_CH10_FEMALE_GROAN2,
	&SOUND_BOOK4_CH10_FEMALE_GROAN1,
	&SOUND_BOOK4_CH10_SLICING_ATTACK,
	&SOUND_BOOK4_CH10_SLICING_ATTACK2,
	&SOUND_BOOK4_CH10_MALE_LAUGH,
	&SOUND_BOOK4_CH10_MALE_LAUGH2,
	&SOUND_BOOK4_CH10_MALE_PAIN,
	&SOUND_BOOK4_CH10_SQ_MAM_ATTACK2,
	&SOUND_BOOK4_CH10_SQ_MAM_DEATH,
	NULL
};

Image* Sexy::LoadImageById(ResourceManager *theManager, int theId)
{
	return (*((Image**)gResources[theId]) = theManager->LoadImage(GetStringIdById(theId)));
}

void Sexy::ReplaceImageById(ResourceManager *theManager, int theId, Image *theImage)
{
	theManager->ReplaceImage(GetStringIdById(theId),theImage);
	*(Image**)gResources[theId] = theImage;
}

Image* Sexy::GetImageById(int theId)
{
	return *(Image**)gResources[theId];
}

Font* Sexy::GetFontById(int theId)
{
	return *(Font**)gResources[theId];
}

int Sexy::GetSoundById(int theId)
{
	return *(int*)gResources[theId];
}

Image*& Sexy::GetImageRefById(int theId)
{
	return *(Image**)gResources[theId];
}

Font*& Sexy::GetFontRefById(int theId)
{
	return *(Font**)gResources[theId];
}

int& Sexy::GetSoundRefById(int theId)
{
	return *(int*)gResources[theId];
}

static Sexy::ResourceId GetIdByVariable(const void *theVariable)
{
	typedef std::map<int,int> MyMap;
	static MyMap aMap;
	if(gNeedRecalcVariableToIdMap)
	{
		gNeedRecalcVariableToIdMap = false;
		aMap.clear();
		for(int i=0; i<RESOURCE_ID_MAX; i++)
			aMap[*(int*)gResources[i]] = i;
	}

	MyMap::iterator anItr = aMap.find((int)theVariable);
	if (anItr == aMap.end())
		return RESOURCE_ID_MAX;
	else
		return (ResourceId) anItr->second;
}

Sexy::ResourceId Sexy::GetIdByImage(Image *theImage)
{
	return GetIdByVariable(theImage);
}

Sexy::ResourceId Sexy::GetIdByFont(Font *theFont)
{
	return GetIdByVariable(theFont);
}

Sexy::ResourceId Sexy::GetIdBySound(int theSound)
{
	return GetIdByVariable((void*)theSound);
}

const char* Sexy::GetStringIdById(int theId)
{
	switch(theId)
	{
		case IMAGE_B4_MINIMAP_ICONS_ID: return "IMAGE_B4_MINIMAP_ICONS";
		case IMAGE_B4_MAPSCREEN_BANNER_ID: return "IMAGE_B4_MAPSCREEN_BANNER";
		case IMAGE_B4_ICONANIM1_ID: return "IMAGE_B4_ICONANIM1";
		case IMAGE_B4_ICONANIM2_ID: return "IMAGE_B4_ICONANIM2";
		case IMAGE_B4_ICONANIM3_ID: return "IMAGE_B4_ICONANIM3";
		case IMAGE_B4_ICONANIM4_ID: return "IMAGE_B4_ICONANIM4";
		case IMAGE_B4_ICONANIM5_ID: return "IMAGE_B4_ICONANIM5";
		case IMAGE_B4_ICONANIM6_ID: return "IMAGE_B4_ICONANIM6";
		case IMAGE_B4_ICONANIM7_ID: return "IMAGE_B4_ICONANIM7";
		case IMAGE_B4_ICONANIM8_ID: return "IMAGE_B4_ICONANIM8";
		case IMAGE_B4_ICONANIM9_ID: return "IMAGE_B4_ICONANIM9";
		case IMAGE_B4_ICONANIM10_ID: return "IMAGE_B4_ICONANIM10";
		case IMAGE_B4_ICONMASK1_ID: return "IMAGE_B4_ICONMASK1";
		case IMAGE_B4_ICONMASK2_ID: return "IMAGE_B4_ICONMASK2";
		case IMAGE_B4_ICONMASK3_ID: return "IMAGE_B4_ICONMASK3";
		case IMAGE_B4_ICONMASK4_ID: return "IMAGE_B4_ICONMASK4";
		case IMAGE_B4_ICONMASK5_ID: return "IMAGE_B4_ICONMASK5";
		case IMAGE_B4_ICONMASK6_ID: return "IMAGE_B4_ICONMASK6";
		case IMAGE_B4_ICONMASK7_ID: return "IMAGE_B4_ICONMASK7";
		case IMAGE_B4_ICONMASK8_ID: return "IMAGE_B4_ICONMASK8";
		case IMAGE_B4_ICONMASK9_ID: return "IMAGE_B4_ICONMASK9";
		case IMAGE_B4_ICONMASK10_ID: return "IMAGE_B4_ICONMASK10";
		case IMAGE_B4_MAP_ID: return "IMAGE_B4_MAP";
		case IMAGE_TUT_PIC_OLDMC_ID: return "IMAGE_TUT_PIC_OLDMC";
		case IMAGE_TUT_PIC_QUEEN_ANGRY_ID: return "IMAGE_TUT_PIC_QUEEN_ANGRY";
		case IMAGE_TUT_PIC_QUEEN_ID: return "IMAGE_TUT_PIC_QUEEN";
		case IMAGE_B4_LEFT_FACING_ARROW_ID: return "IMAGE_B4_LEFT_FACING_ARROW";
		case IMAGE_B4A_BG1_ID: return "IMAGE_B4A_BG1";
		case SOUND_BOOK4_CH1_FELINE_ENGAGE_ID: return "SOUND_BOOK4_CH1_FELINE_ENGAGE";
		case SOUND_BOOK4_CH1_FELINE_ROAR_ID: return "SOUND_BOOK4_CH1_FELINE_ROAR";
		case SOUND_BOOK4_CH1_STRING_ATTACK_ID: return "SOUND_BOOK4_CH1_STRING_ATTACK";
		case SOUND_BOOK4_CH1_STRING_DEATH_ID: return "SOUND_BOOK4_CH1_STRING_DEATH";
		case SOUND_BOOK4_CH1_STRING_IMPACT_ID: return "SOUND_BOOK4_CH1_STRING_IMPACT";
		case SOUND_BOOK4_CH1_BOVINE_ATTACK1_ID: return "SOUND_BOOK4_CH1_BOVINE_ATTACK1";
		case SOUND_BOOK4_CH1_BOVINE_ATTACK2_ID: return "SOUND_BOOK4_CH1_BOVINE_ATTACK2";
		case SOUND_BOOK4_CH1_BOVINE_IMPACT_ID: return "SOUND_BOOK4_CH1_BOVINE_IMPACT";
		case SOUND_BOOK4_CH1_FIRE_6_ID: return "SOUND_BOOK4_CH1_FIRE_6";
		case SOUND_BOOK4_CH1_SPARKLE_ATTACK_ID: return "SOUND_BOOK4_CH1_SPARKLE_ATTACK";
		case SOUND_BOOK4_CH1_PLATE_ATTACK2_ID: return "SOUND_BOOK4_CH1_PLATE_ATTACK2";
		case SOUND_BOOK4_CH1_PLATE_ATTACK3_ID: return "SOUND_BOOK4_CH1_PLATE_ATTACK3";
		case SOUND_BOOK4_CH1_PLATE_IMPACT3_ID: return "SOUND_BOOK4_CH1_PLATE_IMPACT3";
		case SOUND_BOOK4_CH1_PLATE_IMPACT4_ID: return "SOUND_BOOK4_CH1_PLATE_IMPACT4";
		case SOUND_BOOK4_CH1_PLATE_IMPACT5_ID: return "SOUND_BOOK4_CH1_PLATE_IMPACT5";
		case SOUND_BOOK4_CH1_PLATE_IMPACT6_ID: return "SOUND_BOOK4_CH1_PLATE_IMPACT6";
		case IMAGE_B4A_BG2_ID: return "IMAGE_B4A_BG2";
		case SOUND_BOOK4_CH2_PIG_SQUEAL2_ID: return "SOUND_BOOK4_CH2_PIG_SQUEAL2";
		case SOUND_BOOK4_CH2_PIG_ATTACK_ID: return "SOUND_BOOK4_CH2_PIG_ATTACK";
		case SOUND_BOOK4_CH2_PIG_ATTACK2_ID: return "SOUND_BOOK4_CH2_PIG_ATTACK2";
		case SOUND_BOOK4_CH2_SHEEP_BLEAT_ID: return "SOUND_BOOK4_CH2_SHEEP_BLEAT";
		case SOUND_BOOK4_CH2_SLICING_ATTACK2_ID: return "SOUND_BOOK4_CH2_SLICING_ATTACK2";
		case SOUND_BOOK4_CH2_MALE_LOW_PAIN_ID: return "SOUND_BOOK4_CH2_MALE_LOW_PAIN";
		case SOUND_BOOK4_CH2_MALE_LAUGH2_ID: return "SOUND_BOOK4_CH2_MALE_LAUGH2";
		case SOUND_BOOK4_CH2_MALE_PAIN_ID: return "SOUND_BOOK4_CH2_MALE_PAIN";
		case SOUND_BOOK4_CH2_BOVINE_ATTACK2_ID: return "SOUND_BOOK4_CH2_BOVINE_ATTACK2";
		case SOUND_BOOK4_CH2_CHICKEN_ATTACK1_ID: return "SOUND_BOOK4_CH2_CHICKEN_ATTACK1";
		case SOUND_BOOK4_CH2_CHICKEN_ATTACK2_ID: return "SOUND_BOOK4_CH2_CHICKEN_ATTACK2";
		case SOUND_BOOK4_CH2_CHICKEN_IMPACT_ID: return "SOUND_BOOK4_CH2_CHICKEN_IMPACT";
		case SOUND_BOOK4_CH2_EXPLOSION_1_ID: return "SOUND_BOOK4_CH2_EXPLOSION_1";
		case SOUND_BOOK4_CH2_BOVINE_ATTACK1_ID: return "SOUND_BOOK4_CH2_BOVINE_ATTACK1";
		case SOUND_BOOK4_CH2_BOVINE_IMPACT_ID: return "SOUND_BOOK4_CH2_BOVINE_IMPACT";
		case IMAGE_B4A_BG3_ID: return "IMAGE_B4A_BG3";
		case SOUND_BOOK4_CH3_DOG_BARK1_ID: return "SOUND_BOOK4_CH3_DOG_BARK1";
		case SOUND_BOOK4_CH3_DOG_BARK2_ID: return "SOUND_BOOK4_CH3_DOG_BARK2";
		case SOUND_BOOK4_CH3_DOG_WHIMPER_ID: return "SOUND_BOOK4_CH3_DOG_WHIMPER";
		case SOUND_BOOK4_CH3_MISC_IMPACT_ID: return "SOUND_BOOK4_CH3_MISC_IMPACT";
		case SOUND_BOOK4_CH3_MISC_IMPACT2_ID: return "SOUND_BOOK4_CH3_MISC_IMPACT2";
		case SOUND_BOOK4_CH3_PIG_SQUEAL_ID: return "SOUND_BOOK4_CH3_PIG_SQUEAL";
		case SOUND_BOOK4_CH3_PIG_SQUEAL2_ID: return "SOUND_BOOK4_CH3_PIG_SQUEAL2";
		case SOUND_BOOK4_CH3_PIG_ATTACK_ID: return "SOUND_BOOK4_CH3_PIG_ATTACK";
		case SOUND_BOOK4_CH3_PIG_ATTACK2_ID: return "SOUND_BOOK4_CH3_PIG_ATTACK2";
		case SOUND_BOOK4_CH3_WITCH_GROAN_ID: return "SOUND_BOOK4_CH3_WITCH_GROAN";
		case SOUND_BOOK4_CH3_WITCH_LAUGH_ID: return "SOUND_BOOK4_CH3_WITCH_LAUGH";
		case SOUND_BOOK4_CH3_WITCH_LAUGH2_ID: return "SOUND_BOOK4_CH3_WITCH_LAUGH2";
		case SOUND_BOOK4_CH3_WOLF_HOWL_ID: return "SOUND_BOOK4_CH3_WOLF_HOWL";
		case SOUND_BOOK4_CH3_CS_GOOSE_ID: return "SOUND_BOOK4_CH3_CS_GOOSE";
		case IMAGE_B4A_BG4_ID: return "IMAGE_B4A_BG4";
		case SOUND_BOOK4_CH4_EXPLOSION_1_ID: return "SOUND_BOOK4_CH4_EXPLOSION_1";
		case SOUND_BOOK4_CH4_EXPLOSION_3_ID: return "SOUND_BOOK4_CH4_EXPLOSION_3";
		case SOUND_BOOK4_CH4_CHICKEN_ATTACK1_ID: return "SOUND_BOOK4_CH4_CHICKEN_ATTACK1";
		case SOUND_BOOK4_CH4_BLUNT_IMPACT1_ID: return "SOUND_BOOK4_CH4_BLUNT_IMPACT1";
		case SOUND_BOOK4_CH4_CHICKEN_IMPACT_ID: return "SOUND_BOOK4_CH4_CHICKEN_IMPACT";
		case SOUND_BOOK4_CH4_MALE_ANGER_ID: return "SOUND_BOOK4_CH4_MALE_ANGER";
		case SOUND_BOOK4_CH4_MALE_LAUGH_ID: return "SOUND_BOOK4_CH4_MALE_LAUGH";
		case SOUND_BOOK4_CH4_MALE_LAUGH2_ID: return "SOUND_BOOK4_CH4_MALE_LAUGH2";
		case SOUND_BOOK4_CH4_MALE_LOW_ANGER_ID: return "SOUND_BOOK4_CH4_MALE_LOW_ANGER";
		case SOUND_BOOK4_CH4_MALE_GRUNT1_ID: return "SOUND_BOOK4_CH4_MALE_GRUNT1";
		case SOUND_BOOK4_CH4_MALE_GRUNT2_ID: return "SOUND_BOOK4_CH4_MALE_GRUNT2";
		case SOUND_BOOK4_CH4_GENERIC_SLOSH_ID: return "SOUND_BOOK4_CH4_GENERIC_SLOSH";
		case SOUND_BOOK4_CH4_FEMALE_GROAN2_ID: return "SOUND_BOOK4_CH4_FEMALE_GROAN2";
		case SOUND_BOOK4_CH4_MISC_IMPACT2_ID: return "SOUND_BOOK4_CH4_MISC_IMPACT2";
		case SOUND_BOOK4_CH4_WET_IMPACT2_ID: return "SOUND_BOOK4_CH4_WET_IMPACT2";
		case SOUND_BOOK4_CH4_KUBWA_ROAR_ID: return "SOUND_BOOK4_CH4_KUBWA_ROAR";
		case SOUND_BOOK4_CH4_GIANT_GRUNT2_ID: return "SOUND_BOOK4_CH4_GIANT_GRUNT2";
		case SOUND_BOOK4_CH4_FIRE_3_ID: return "SOUND_BOOK4_CH4_FIRE_3";
		case SOUND_BOOK4_CH4_FIREWORK_1_ID: return "SOUND_BOOK4_CH4_FIREWORK_1";
		case SOUND_BOOK4_CH4_SWORD_IMPACT3_ID: return "SOUND_BOOK4_CH4_SWORD_IMPACT3";
		case IMAGE_B4A_BG5_ID: return "IMAGE_B4A_BG5";
		case SOUND_BOOK4_CH5_PLATE_ATTACK4_ID: return "SOUND_BOOK4_CH5_PLATE_ATTACK4";
		case SOUND_BOOK4_CH5_PLATE_IMPACT5_ID: return "SOUND_BOOK4_CH5_PLATE_IMPACT5";
		case SOUND_BOOK4_CH5_FIRE_3_ID: return "SOUND_BOOK4_CH5_FIRE_3";
		case SOUND_BOOK4_CH5_FIRE_6_ID: return "SOUND_BOOK4_CH5_FIRE_6";
		case SOUND_BOOK4_CH5_BEAR_ATTACK_ID: return "SOUND_BOOK4_CH5_BEAR_ATTACK";
		case SOUND_BOOK4_CH5_BEAR_IMPACT_ID: return "SOUND_BOOK4_CH5_BEAR_IMPACT";
		case SOUND_BOOK4_CH5_BEAR_ROAR_ID: return "SOUND_BOOK4_CH5_BEAR_ROAR";
		case SOUND_BOOK4_CH5_WET_IMPACT1_ID: return "SOUND_BOOK4_CH5_WET_IMPACT1";
		case IMAGE_B4A_BG6_ID: return "IMAGE_B4A_BG6";
		case SOUND_BOOK4_CH6_MALE_LAUGH_ID: return "SOUND_BOOK4_CH6_MALE_LAUGH";
		case SOUND_BOOK4_CH6_MALE_LAUGH2_ID: return "SOUND_BOOK4_CH6_MALE_LAUGH2";
		case SOUND_BOOK4_CH6_MALE_PAIN_ID: return "SOUND_BOOK4_CH6_MALE_PAIN";
		case SOUND_BOOK4_CH6_FEMALE_GROAN2_ID: return "SOUND_BOOK4_CH6_FEMALE_GROAN2";
		case SOUND_BOOK4_CH6_SMOKE_ATTACK2_ID: return "SOUND_BOOK4_CH6_SMOKE_ATTACK2";
		case SOUND_BOOK4_CH6_EXPLOSION_1_ID: return "SOUND_BOOK4_CH6_EXPLOSION_1";
		case SOUND_BOOK4_CH6_EXPLOSION_3_ID: return "SOUND_BOOK4_CH6_EXPLOSION_3";
		case SOUND_BOOK4_CH6_SLUMP_SMALL_ID: return "SOUND_BOOK4_CH6_SLUMP_SMALL";
		case SOUND_BOOK4_CH6_WITCH_GROAN_ID: return "SOUND_BOOK4_CH6_WITCH_GROAN";
		case SOUND_BOOK4_CH6_WITCH_LAUGH_ID: return "SOUND_BOOK4_CH6_WITCH_LAUGH";
		case SOUND_BOOK4_CH6_WITCH_LAUGH2_ID: return "SOUND_BOOK4_CH6_WITCH_LAUGH2";
		case SOUND_BOOK4_CH6_FEMALE_MMMMM_ID: return "SOUND_BOOK4_CH6_FEMALE_MMMMM";
		case IMAGE_B4A_BG7_ID: return "IMAGE_B4A_BG7";
		case IMAGE_B4A_CATEPILLAR_BOSS_BATTLE_ID: return "IMAGE_B4A_CATEPILLAR_BOSS_BATTLE";
		case SOUND_BOOK4_CH7_SMOKE_ATTACK_ID: return "SOUND_BOOK4_CH7_SMOKE_ATTACK";
		case SOUND_BOOK4_CH7_SMOKE_ATTACK2_ID: return "SOUND_BOOK4_CH7_SMOKE_ATTACK2";
		case SOUND_BOOK4_CH7_SMOKE_IMPACT_ID: return "SOUND_BOOK4_CH7_SMOKE_IMPACT";
		case SOUND_BOOK4_CH7_MALE_LAUGH_ID: return "SOUND_BOOK4_CH7_MALE_LAUGH";
		case SOUND_BOOK4_CH7_MALE_LAUGH2_ID: return "SOUND_BOOK4_CH7_MALE_LAUGH2";
		case SOUND_BOOK4_CH7_CS_CAT_ID: return "SOUND_BOOK4_CH7_CS_CAT";
		case IMAGE_B4A_BG8_ID: return "IMAGE_B4A_BG8";
		case SOUND_BOOK4_CH8_SQ_MAM_ATTACK_ID: return "SOUND_BOOK4_CH8_SQ_MAM_ATTACK";
		case SOUND_BOOK4_CH8_SQ_MAM_ATTACK2_ID: return "SOUND_BOOK4_CH8_SQ_MAM_ATTACK2";
		case SOUND_BOOK4_CH8_SQ_MAM_DEATH_ID: return "SOUND_BOOK4_CH8_SQ_MAM_DEATH";
		case SOUND_BOOK4_CH8_MALE_LAUGH_ID: return "SOUND_BOOK4_CH8_MALE_LAUGH";
		case SOUND_BOOK4_CH8_MALE_LAUGH2_ID: return "SOUND_BOOK4_CH8_MALE_LAUGH2";
		case SOUND_BOOK4_CH8_PLATE_ATTACK2_ID: return "SOUND_BOOK4_CH8_PLATE_ATTACK2";
		case SOUND_BOOK4_CH8_PLATE_ATTACK3_ID: return "SOUND_BOOK4_CH8_PLATE_ATTACK3";
		case SOUND_BOOK4_CH8_PLATE_ATTACK4_ID: return "SOUND_BOOK4_CH8_PLATE_ATTACK4";
		case SOUND_BOOK4_CH8_PLATE_IMPACT3_ID: return "SOUND_BOOK4_CH8_PLATE_IMPACT3";
		case SOUND_BOOK4_CH8_PLATE_IMPACT4_ID: return "SOUND_BOOK4_CH8_PLATE_IMPACT4";
		case SOUND_BOOK4_CH8_PLATE_IMPACT5_ID: return "SOUND_BOOK4_CH8_PLATE_IMPACT5";
		case SOUND_BOOK4_CH8_PLATE_IMPACT6_ID: return "SOUND_BOOK4_CH8_PLATE_IMPACT6";
		case SOUND_BOOK4_CH8_FIRE_3_ID: return "SOUND_BOOK4_CH8_FIRE_3";
		case SOUND_BOOK4_CH8_FIRE_6_ID: return "SOUND_BOOK4_CH8_FIRE_6";
		case IMAGE_B4A_BG9_ID: return "IMAGE_B4A_BG9";
		case SOUND_BOOK4_CH9_OGRE_CHALLENGE_ID: return "SOUND_BOOK4_CH9_OGRE_CHALLENGE";
		case SOUND_BOOK4_CH9_OGRE_IMPACT_ID: return "SOUND_BOOK4_CH9_OGRE_IMPACT";
		case SOUND_BOOK4_CH9_DOPEY_ATTACK_ID: return "SOUND_BOOK4_CH9_DOPEY_ATTACK";
		case SOUND_BOOK4_CH9_DOPEY_IMPACT_ID: return "SOUND_BOOK4_CH9_DOPEY_IMPACT";
		case SOUND_BOOK4_CH9_SMOKE_ATTACK2_ID: return "SOUND_BOOK4_CH9_SMOKE_ATTACK2";
		case SOUND_BOOK4_CH9_DRAGON_BITE_ID: return "SOUND_BOOK4_CH9_DRAGON_BITE";
		case SOUND_BOOK4_CH9_DRAGON_DEATH_ID: return "SOUND_BOOK4_CH9_DRAGON_DEATH";
		case SOUND_BOOK4_CH9_DRAGON_PAIN_ID: return "SOUND_BOOK4_CH9_DRAGON_PAIN";
		case SOUND_BOOK4_CH9_DRAGON_ROAR_ID: return "SOUND_BOOK4_CH9_DRAGON_ROAR";
		case SOUND_BOOK4_CH9_MALE_LAUGH_ID: return "SOUND_BOOK4_CH9_MALE_LAUGH";
		case SOUND_BOOK4_CH9_MALE_LAUGH2_ID: return "SOUND_BOOK4_CH9_MALE_LAUGH2";
		case SOUND_BOOK4_CH9_MALE_PAIN_ID: return "SOUND_BOOK4_CH9_MALE_PAIN";
		case SOUND_BOOK4_CH9_SLICING_ATTACK_ID: return "SOUND_BOOK4_CH9_SLICING_ATTACK";
		case SOUND_BOOK4_CH9_SLICING_ATTACK2_ID: return "SOUND_BOOK4_CH9_SLICING_ATTACK2";
		case IMAGE_B4A_BG10_ID: return "IMAGE_B4A_BG10";
		case SOUND_BOOK4_CH10_DOPEY_ATTACK_ID: return "SOUND_BOOK4_CH10_DOPEY_ATTACK";
		case SOUND_BOOK4_CH10_DOPEY_IMPACT_ID: return "SOUND_BOOK4_CH10_DOPEY_IMPACT";
		case SOUND_BOOK4_CH10_SMOKE_ATTACK2_ID: return "SOUND_BOOK4_CH10_SMOKE_ATTACK2";
		case SOUND_BOOK4_CH10_WITCH_LAUGH_ID: return "SOUND_BOOK4_CH10_WITCH_LAUGH";
		case SOUND_BOOK4_CH10_WITCH_LAUGH2_ID: return "SOUND_BOOK4_CH10_WITCH_LAUGH2";
		case SOUND_BOOK4_CH10_FEMALE_GROAN2_ID: return "SOUND_BOOK4_CH10_FEMALE_GROAN2";
		case SOUND_BOOK4_CH10_FEMALE_GROAN1_ID: return "SOUND_BOOK4_CH10_FEMALE_GROAN1";
		case SOUND_BOOK4_CH10_SLICING_ATTACK_ID: return "SOUND_BOOK4_CH10_SLICING_ATTACK";
		case SOUND_BOOK4_CH10_SLICING_ATTACK2_ID: return "SOUND_BOOK4_CH10_SLICING_ATTACK2";
		case SOUND_BOOK4_CH10_MALE_LAUGH_ID: return "SOUND_BOOK4_CH10_MALE_LAUGH";
		case SOUND_BOOK4_CH10_MALE_LAUGH2_ID: return "SOUND_BOOK4_CH10_MALE_LAUGH2";
		case SOUND_BOOK4_CH10_MALE_PAIN_ID: return "SOUND_BOOK4_CH10_MALE_PAIN";
		case SOUND_BOOK4_CH10_SQ_MAM_ATTACK2_ID: return "SOUND_BOOK4_CH10_SQ_MAM_ATTACK2";
		case SOUND_BOOK4_CH10_SQ_MAM_DEATH_ID: return "SOUND_BOOK4_CH10_SQ_MAM_DEATH";
		default: return "";
	}
}

