#ifndef __InitialMiniGames_H__
#define __InitialMiniGames_H__

namespace Sexy
{
	class ResourceManager;
	class Image;
	class Font;

	Image* LoadImageById(ResourceManager *theManager, int theId);
	void ReplaceImageById(ResourceManager *theManager, int theId, Image *theImage);
	bool ExtractResourcesByName(ResourceManager *theManager, const char *theName);

	// InitialMiniGames Resources
	bool ExtractInitialMiniGamesResources(ResourceManager *theMgr);
	extern Image* IMAGE_MINIMENU_GOLDENCOINS_BTN;
	extern Image* IMAGE_MINIMENU_LETTER_RIP_BTN;
	extern Image* IMAGE_MINIMENU_LINKNSPELL_BTN;
	extern Image* IMAGE_MINIMENU_MUTANTWORDS_BTN;
	extern Image* IMAGE_MINIMENU_WORDMASTER_BTN;
	extern Image* IMAGE_MINIMENU_WORDUP_BTN;

	// MiniGame1 Resources
	bool ExtractMiniGame1Resources(ResourceManager *theMgr);
	extern Image* IMAGE_MINIGAME1_BRACKET;
	extern Image* IMAGE_MINIGAME1_ENTRY_BOXES;
	extern Image* IMAGE_MINIGAME1_LABEL_TURNS;
	extern Image* IMAGE_MINIGAME1_LEGEND;
	extern Image* IMAGE_MINIGAME1_TAB_LEFT_DARK;
	extern Image* IMAGE_MINIGAME1_TAB_LEFT_LIT;
	extern Image* IMAGE_MINIGAME1_TILE_GOLD;
	extern Image* IMAGE_MINIGAME1_TILE_RED;
	extern Image* IMAGE_MINIGAME1_TILE_SILVER;
	extern Image* IMAGE_MINIGAME1_TITLE_WORDMASTER;
	extern Image* IMAGE_MINIGAME1_TURN_NUMBERS;
	extern Image* IMAGE_MINIGAME1_X_CHECK;

	// MiniGame2 Resources
	bool ExtractMiniGame2Resources(ResourceManager *theMgr);
	extern Image* IMAGE_MINIGAME2_GOLD_FILL;
	extern Image* IMAGE_MINIGAME2_LABEL_TIME;
	extern Image* IMAGE_MINIGAME2_SPELLING_BOX;
	extern Image* IMAGE_MINIGAME2_TIMER_FILLBAR;
	extern Image* IMAGE_MINIGAME2_TIMER_LEFT;
	extern Image* IMAGE_MINIGAME2_TITLE;

	// MiniGame3 Resources
	bool ExtractMiniGame3Resources(ResourceManager *theMgr);
	extern Image* IMAGE_MINIGAME3_BRACKET;
	extern Image* IMAGE_MINIGAME3_ENTRY_BOXES;
	extern Image* IMAGE_MINIGAME3_LABEL_TIME;
	extern Image* IMAGE_MINIGAME3_TILE_GOLD;
	extern Image* IMAGE_MINIGAME3_TILE_SILVER;
	extern Image* IMAGE_MINIGAME3_TIMER_FILLBAR;
	extern Image* IMAGE_MINIGAME3_TIMER_LEFT;
	extern Image* IMAGE_MINIGAME3_TITLE;
	extern Image* IMAGE_MINIGAME3_X_CHECK;

	// MiniGame4 Resources
	bool ExtractMiniGame4Resources(ResourceManager *theMgr);
	extern Image* IMAGE_MINIGAME4_ARROW_LARGE;
	extern Image* IMAGE_MINIGAME4_ARROW_SMALL;
	extern Image* IMAGE_MINIGAME4_BG;
	extern Image* IMAGE_MINIGAME4_GOOD;
	extern Image* IMAGE_MINIGAME4_GREAT;
	extern Image* IMAGE_MINIGAME4_HINTBOX;
	extern Image* IMAGE_MINIGAME4_HINTGLOW;
	extern Image* IMAGE_MINIGAME4_LABEL_TIME;
	extern Image* IMAGE_MINIGAME4_TILEHL;
	extern Image* IMAGE_MINIGAME4_TILE_GOLD;
	extern Image* IMAGE_MINIGAME4_TILE_RED;
	extern Image* IMAGE_MINIGAME4_TIMER_DIVIDER;
	extern Image* IMAGE_MINIGAME4_TIMER_FILLBAR;
	extern Image* IMAGE_MINIGAME4_TIMER_LEFT;
	extern Image* IMAGE_MINIGAME4_TRAY3;
	extern Image* IMAGE_MINIGAME4_TRAY3_GOLD;
	extern Image* IMAGE_MINIGAME4_TRAY4;
	extern Image* IMAGE_MINIGAME4_TRAY4_GOLD;
	extern Image* IMAGE_MINIGAME4_TRAY5;
	extern Image* IMAGE_MINIGAME4_TRAY5_GOLD;
	extern Image* IMAGE_MINIGAME4_TRAY6;
	extern Image* IMAGE_MINIGAME4_TRAY6_GOLD;
	extern Image* IMAGE_MINIGAME4_TRAY7;
	extern Image* IMAGE_MINIGAME4_TRAY7_GOLD;

	// MiniGame5 Resources
	bool ExtractMiniGame5Resources(ResourceManager *theMgr);
	extern Image* IMAGE_MINIGAME5_CLOUDS;
	extern Image* IMAGE_MINIGAME5_CURTAINS;
	extern Image* IMAGE_MINIGAME5_FLAG_GREEN;
	extern Image* IMAGE_MINIGAME5_FLAG_YELLOW;
	extern Image* IMAGE_MINIGAME5_MOUNTAIN1;
	extern Image* IMAGE_MINIGAME5_MOUNTAIN2;
	extern Image* IMAGE_MINIGAME5_MOXIE_STUN;
	extern Image* IMAGE_MINIGAME5_OHNO;
	extern Image* IMAGE_MINIGAME5_PUPPET_LEX;
	extern Image* IMAGE_MINIGAME5_PUPPET_MOXIE;
	extern Image* IMAGE_MINIGAME5_SIGN;
	extern Image* IMAGE_MINIGAME5_SKY;
	extern Image* IMAGE_MINIGAME5_SPELLING_BOX;
	extern Image* IMAGE_MINIGAME5_SUN;
	extern Image* IMAGE_MINIGAME5_TITLE;

	// MiniGame6 Resources
	bool ExtractMiniGame6Resources(ResourceManager *theMgr);
	extern Image* IMAGE_MINIGAME6_BG;
	extern Image* IMAGE_MINIGAME6_BOARD;
	extern Image* IMAGE_MINIGAME6_LABEL_TIME;
	extern Image* IMAGE_MINIGAME6_TILE_GOLD;
	extern Image* IMAGE_MINIGAME6_TIMER_FILLBAR;
	extern Image* IMAGE_MINIGAME6_TIMER_LEFT;
	extern Image* IMAGE_MINIGAME6_TITLESCROLL;
	extern Image* IMAGE_MINIGAME6_TRAY3;
	extern Image* IMAGE_MINIGAME6_TRAY3_GOLD;
	extern Image* IMAGE_MINIGAME6_TRAY4;
	extern Image* IMAGE_MINIGAME6_TRAY4_GOLD;
	extern Image* IMAGE_MINIGAME6_TRAY5;
	extern Image* IMAGE_MINIGAME6_TRAY5_GOLD;
	extern Image* IMAGE_MINIGAME6_TRAY6;
	extern Image* IMAGE_MINIGAME6_TRAY6_GOLD;
	extern Image* IMAGE_MINIGAME6_TRAY7;
	extern Image* IMAGE_MINIGAME6_TRAY7_GOLD;

	// MiniGame7 Resources
	bool ExtractMiniGame7Resources(ResourceManager *theMgr);
	extern Image* IMAGE_MINIGAME7_BG;
	extern Image* IMAGE_MINIGAME7_BOARD;
	extern Image* IMAGE_MINIGAME7_BRONZE_COIN;
	extern Image* IMAGE_MINIGAME7_GOLD_COIN;
	extern Image* IMAGE_MINIGAME7_TILE_GOLD;
	extern Image* IMAGE_MINIGAME7_TITLESCROLL;

	enum ResourceId
	{
		IMAGE_MINIMENU_LETTER_RIP_BTN_ID,
		IMAGE_MINIMENU_LINKNSPELL_BTN_ID,
		IMAGE_MINIMENU_WORDMASTER_BTN_ID,
		IMAGE_MINIMENU_WORDUP_BTN_ID,
		IMAGE_MINIMENU_MUTANTWORDS_BTN_ID,
		IMAGE_MINIMENU_GOLDENCOINS_BTN_ID,
		IMAGE_MINIGAME1_BRACKET_ID,
		IMAGE_MINIGAME1_ENTRY_BOXES_ID,
		IMAGE_MINIGAME1_LABEL_TURNS_ID,
		IMAGE_MINIGAME1_X_CHECK_ID,
		IMAGE_MINIGAME1_TAB_LEFT_DARK_ID,
		IMAGE_MINIGAME1_TAB_LEFT_LIT_ID,
		IMAGE_MINIGAME1_TILE_GOLD_ID,
		IMAGE_MINIGAME1_TILE_SILVER_ID,
		IMAGE_MINIGAME1_TILE_RED_ID,
		IMAGE_MINIGAME1_TITLE_WORDMASTER_ID,
		IMAGE_MINIGAME1_TURN_NUMBERS_ID,
		IMAGE_MINIGAME1_LEGEND_ID,
		IMAGE_MINIGAME2_TITLE_ID,
		IMAGE_MINIGAME2_GOLD_FILL_ID,
		IMAGE_MINIGAME2_LABEL_TIME_ID,
		IMAGE_MINIGAME2_SPELLING_BOX_ID,
		IMAGE_MINIGAME2_TIMER_FILLBAR_ID,
		IMAGE_MINIGAME2_TIMER_LEFT_ID,
		IMAGE_MINIGAME3_TITLE_ID,
		IMAGE_MINIGAME3_ENTRY_BOXES_ID,
		IMAGE_MINIGAME3_TIMER_FILLBAR_ID,
		IMAGE_MINIGAME3_TIMER_LEFT_ID,
		IMAGE_MINIGAME3_LABEL_TIME_ID,
		IMAGE_MINIGAME3_TILE_GOLD_ID,
		IMAGE_MINIGAME3_TILE_SILVER_ID,
		IMAGE_MINIGAME3_BRACKET_ID,
		IMAGE_MINIGAME3_X_CHECK_ID,
		IMAGE_MINIGAME4_BG_ID,
		IMAGE_MINIGAME4_GOOD_ID,
		IMAGE_MINIGAME4_GREAT_ID,
		IMAGE_MINIGAME4_TIMER_FILLBAR_ID,
		IMAGE_MINIGAME4_ARROW_LARGE_ID,
		IMAGE_MINIGAME4_ARROW_SMALL_ID,
		IMAGE_MINIGAME4_HINTBOX_ID,
		IMAGE_MINIGAME4_TIMER_DIVIDER_ID,
		IMAGE_MINIGAME4_TRAY3_ID,
		IMAGE_MINIGAME4_TRAY3_GOLD_ID,
		IMAGE_MINIGAME4_TRAY4_ID,
		IMAGE_MINIGAME4_TRAY4_GOLD_ID,
		IMAGE_MINIGAME4_TRAY5_ID,
		IMAGE_MINIGAME4_TRAY5_GOLD_ID,
		IMAGE_MINIGAME4_TRAY6_ID,
		IMAGE_MINIGAME4_TRAY6_GOLD_ID,
		IMAGE_MINIGAME4_TRAY7_ID,
		IMAGE_MINIGAME4_TRAY7_GOLD_ID,
		IMAGE_MINIGAME4_TILEHL_ID,
		IMAGE_MINIGAME4_TIMER_LEFT_ID,
		IMAGE_MINIGAME4_LABEL_TIME_ID,
		IMAGE_MINIGAME4_TILE_GOLD_ID,
		IMAGE_MINIGAME4_TILE_RED_ID,
		IMAGE_MINIGAME4_HINTGLOW_ID,
		IMAGE_MINIGAME5_TITLE_ID,
		IMAGE_MINIGAME5_SPELLING_BOX_ID,
		IMAGE_MINIGAME5_CLOUDS_ID,
		IMAGE_MINIGAME5_CURTAINS_ID,
		IMAGE_MINIGAME5_FLAG_GREEN_ID,
		IMAGE_MINIGAME5_FLAG_YELLOW_ID,
		IMAGE_MINIGAME5_MOUNTAIN1_ID,
		IMAGE_MINIGAME5_MOUNTAIN2_ID,
		IMAGE_MINIGAME5_PUPPET_LEX_ID,
		IMAGE_MINIGAME5_PUPPET_MOXIE_ID,
		IMAGE_MINIGAME5_SIGN_ID,
		IMAGE_MINIGAME5_SKY_ID,
		IMAGE_MINIGAME5_SUN_ID,
		IMAGE_MINIGAME5_MOXIE_STUN_ID,
		IMAGE_MINIGAME5_OHNO_ID,
		IMAGE_MINIGAME6_TITLESCROLL_ID,
		IMAGE_MINIGAME6_BG_ID,
		IMAGE_MINIGAME6_BOARD_ID,
		IMAGE_MINIGAME6_TRAY3_ID,
		IMAGE_MINIGAME6_TRAY3_GOLD_ID,
		IMAGE_MINIGAME6_TRAY4_ID,
		IMAGE_MINIGAME6_TRAY4_GOLD_ID,
		IMAGE_MINIGAME6_TRAY5_ID,
		IMAGE_MINIGAME6_TRAY5_GOLD_ID,
		IMAGE_MINIGAME6_TRAY6_ID,
		IMAGE_MINIGAME6_TRAY6_GOLD_ID,
		IMAGE_MINIGAME6_TRAY7_ID,
		IMAGE_MINIGAME6_TRAY7_GOLD_ID,
		IMAGE_MINIGAME6_TIMER_FILLBAR_ID,
		IMAGE_MINIGAME6_TIMER_LEFT_ID,
		IMAGE_MINIGAME6_LABEL_TIME_ID,
		IMAGE_MINIGAME6_TILE_GOLD_ID,
		IMAGE_MINIGAME7_TITLESCROLL_ID,
		IMAGE_MINIGAME7_BG_ID,
		IMAGE_MINIGAME7_BOARD_ID,
		IMAGE_MINIGAME7_BRONZE_COIN_ID,
		IMAGE_MINIGAME7_GOLD_COIN_ID,
		IMAGE_MINIGAME7_TILE_GOLD_ID,
		RESOURCE_ID_MAX
	};

	Image* GetImageById(int theId);
	Font* GetFontById(int theId);
	int GetSoundById(int theId);

	Image*& GetImageRefById(int theId);
	Font*& GetFontRefById(int theId);
	int& GetSoundRefById(int theId);

	ResourceId GetIdByImage(Image *theImage);
	ResourceId GetIdByFont(Font *theFont);
	ResourceId GetIdBySound(int theSound);
	const char* GetStringIdById(int theId);
	ResourceId GetIdByStringId(const char *theStringId);

} // namespace Sexy


#endif
