#ifndef __Book3_H__
#define __Book3_H__

namespace Sexy
{
	class ResourceManager;
	class Image;
	class Font;

	Image* LoadImageById(ResourceManager *theManager, int theId);
	void ReplaceImageById(ResourceManager *theManager, int theId, Image *theImage);
	bool ExtractResourcesByName(ResourceManager *theManager, const char *theName);

	// Book3Chapter1 Resources
	bool ExtractBook3Chapter1Resources(ResourceManager *theMgr);
	extern Image* IMAGE_B3A_BG1;
	extern int SOUND_BOOK3_CH1_SOUND10;
	extern int SOUND_BOOK3_CH1_SOUND1;
	extern int SOUND_BOOK3_CH1_SOUND2;
	extern int SOUND_BOOK3_CH1_SOUND3;
	extern int SOUND_BOOK3_CH1_SOUND4;
	extern int SOUND_BOOK3_CH1_SOUND5;
	extern int SOUND_BOOK3_CH1_SOUND6;
	extern int SOUND_BOOK3_CH1_SOUND7;
	extern int SOUND_BOOK3_CH1_SOUND8;
	extern int SOUND_BOOK3_CH1_SOUND9;

	// Book3Chapter10 Resources
	bool ExtractBook3Chapter10Resources(ResourceManager *theMgr);
	extern Image* IMAGE_B3A_BG10;
	extern Image* IMAGE_B3A_CODEX_BOSS_BATTLE;
	extern int SOUND_BOOK3_CH10_AUTOLOGICAL;
	extern int SOUND_BOOK3_CH10_CODEXFLINCH;
	extern int SOUND_BOOK3_CH10_CODEXLAUGH;
	extern int SOUND_BOOK3_CH10_CODEXNYAH;
	extern int SOUND_BOOK3_CH10_CODEXSUMMON;
	extern int SOUND_BOOK3_CH10_LEXBEAM;
	extern int SOUND_BOOK3_CH10_SOUND1;
	extern int SOUND_BOOK3_CH10_SOUND2;
	extern int SOUND_BOOK3_CH10_SOUND3;
	extern int SOUND_BOOK3_CH10_SOUND4;
	extern int SOUND_BOOK3_CH10_SOUND5;
	extern int SOUND_BOOK3_CH10_SOUND7;

	// Book3Chapter2 Resources
	bool ExtractBook3Chapter2Resources(ResourceManager *theMgr);
	extern Image* IMAGE_B3A_BG2;
	extern int SOUND_BOOK3_CH2_SOUND10;
	extern int SOUND_BOOK3_CH2_SOUND11;
	extern int SOUND_BOOK3_CH2_SOUND12;
	extern int SOUND_BOOK3_CH2_SOUND13;
	extern int SOUND_BOOK3_CH2_SOUND14;
	extern int SOUND_BOOK3_CH2_SOUND15;
	extern int SOUND_BOOK3_CH2_SOUND1;
	extern int SOUND_BOOK3_CH2_SOUND2;
	extern int SOUND_BOOK3_CH2_SOUND3;
	extern int SOUND_BOOK3_CH2_SOUND4;
	extern int SOUND_BOOK3_CH2_SOUND5;
	extern int SOUND_BOOK3_CH2_SOUND6;
	extern int SOUND_BOOK3_CH2_SOUND7;
	extern int SOUND_BOOK3_CH2_SOUND8;
	extern int SOUND_BOOK3_CH2_SOUND9;

	// Book3Chapter3 Resources
	bool ExtractBook3Chapter3Resources(ResourceManager *theMgr);
	extern Image* IMAGE_B3A_BG3;
	extern int SOUND_BOOK3_CH3_SOUND10;
	extern int SOUND_BOOK3_CH3_SOUND11;
	extern int SOUND_BOOK3_CH3_SOUND1;
	extern int SOUND_BOOK3_CH3_SOUND2;
	extern int SOUND_BOOK3_CH3_SOUND3;
	extern int SOUND_BOOK3_CH3_SOUND4;
	extern int SOUND_BOOK3_CH3_SOUND5;
	extern int SOUND_BOOK3_CH3_SOUND6;
	extern int SOUND_BOOK3_CH3_SOUND7;
	extern int SOUND_BOOK3_CH3_SOUND8;
	extern int SOUND_BOOK3_CH3_SOUND9;

	// Book3Chapter4 Resources
	bool ExtractBook3Chapter4Resources(ResourceManager *theMgr);
	extern Image* IMAGE_B3A_BG4;
	extern int SOUND_BOOK3_CH4_SOUND10;
	extern int SOUND_BOOK3_CH4_SOUND11;
	extern int SOUND_BOOK3_CH4_SOUND1;
	extern int SOUND_BOOK3_CH4_SOUND2;
	extern int SOUND_BOOK3_CH4_SOUND3;
	extern int SOUND_BOOK3_CH4_SOUND4;
	extern int SOUND_BOOK3_CH4_SOUND5;
	extern int SOUND_BOOK3_CH4_SOUND6;
	extern int SOUND_BOOK3_CH4_SOUND7;
	extern int SOUND_BOOK3_CH4_SOUND8;
	extern int SOUND_BOOK3_CH4_SOUND9;

	// Book3Chapter5 Resources
	bool ExtractBook3Chapter5Resources(ResourceManager *theMgr);
	extern Image* IMAGE_B3A_BG5;
	extern int SOUND_BOOK3_CH5_SOUND10;
	extern int SOUND_BOOK3_CH5_SOUND11;
	extern int SOUND_BOOK3_CH5_SOUND12;
	extern int SOUND_BOOK3_CH5_SOUND1;
	extern int SOUND_BOOK3_CH5_SOUND2;
	extern int SOUND_BOOK3_CH5_SOUND3;
	extern int SOUND_BOOK3_CH5_SOUND4;
	extern int SOUND_BOOK3_CH5_SOUND5;
	extern int SOUND_BOOK3_CH5_SOUND6;
	extern int SOUND_BOOK3_CH5_SOUND7;
	extern int SOUND_BOOK3_CH5_SOUND8;
	extern int SOUND_BOOK3_CH5_SOUND9;

	// Book3Chapter6 Resources
	bool ExtractBook3Chapter6Resources(ResourceManager *theMgr);
	extern Image* IMAGE_B3A_BG6;
	extern int SOUND_BOOK3_CH6_SOUND10;
	extern int SOUND_BOOK3_CH6_SOUND11;
	extern int SOUND_BOOK3_CH6_SOUND12;
	extern int SOUND_BOOK3_CH6_SOUND1;
	extern int SOUND_BOOK3_CH6_SOUND2;
	extern int SOUND_BOOK3_CH6_SOUND3;
	extern int SOUND_BOOK3_CH6_SOUND4;
	extern int SOUND_BOOK3_CH6_SOUND5;
	extern int SOUND_BOOK3_CH6_SOUND6;
	extern int SOUND_BOOK3_CH6_SOUND7;
	extern int SOUND_BOOK3_CH6_SOUND8;
	extern int SOUND_BOOK3_CH6_SOUND9;

	// Book3Chapter7 Resources
	bool ExtractBook3Chapter7Resources(ResourceManager *theMgr);
	extern Image* IMAGE_B3A_BG7;
	extern Image* IMAGE_B3A_HYDRA_BOSS_BATTLE;
	extern int SOUND_BOOK3_CH7_SOUND1;
	extern int SOUND_BOOK3_CH7_SOUND2;
	extern int SOUND_BOOK3_CH7_SOUND3;
	extern int SOUND_BOOK3_CH7_SOUND4;
	extern int SOUND_BOOK3_CH7_SOUND5;
	extern int SOUND_BOOK3_CH7_SOUND6;
	extern int SOUND_BOOK3_CH7_SOUND7;
	extern int SOUND_BOOK3_CH7_SOUND8;
	extern int SOUND_BOOK3_CH7_SOUND9;

	// Book3Chapter8 Resources
	bool ExtractBook3Chapter8Resources(ResourceManager *theMgr);
	extern Image* IMAGE_B3A_BG8;
	extern int SOUND_BOOK3_CH8_SOUND1;
	extern int SOUND_BOOK3_CH8_SOUND2;
	extern int SOUND_BOOK3_CH8_SOUND3;
	extern int SOUND_BOOK3_CH8_SOUND4;
	extern int SOUND_BOOK3_CH8_SOUND5;
	extern int SOUND_BOOK3_CH8_SOUND6;
	extern int SOUND_BOOK3_CH8_SOUND7;

	// Book3Chapter9 Resources
	bool ExtractBook3Chapter9Resources(ResourceManager *theMgr);
	extern Image* IMAGE_B3A_BG9;
	extern int SOUND_BOOK3_CH9_SOUND10;
	extern int SOUND_BOOK3_CH9_SOUND12;
	extern int SOUND_BOOK3_CH9_SOUND13;
	extern int SOUND_BOOK3_CH9_SOUND1;
	extern int SOUND_BOOK3_CH9_SOUND2;
	extern int SOUND_BOOK3_CH9_SOUND3;
	extern int SOUND_BOOK3_CH9_SOUND4;
	extern int SOUND_BOOK3_CH9_SOUND5;
	extern int SOUND_BOOK3_CH9_SOUND6;
	extern int SOUND_BOOK3_CH9_SOUND7;
	extern int SOUND_BOOK3_CH9_SOUND8;
	extern int SOUND_BOOK3_CH9_SOUND9;

	// Book3Common Resources
	bool ExtractBook3CommonResources(ResourceManager *theMgr);
	extern Image* IMAGE_B3_LEFT_FACING_ARROW;

	// Book3Init Resources
	bool ExtractBook3InitResources(ResourceManager *theMgr);
	extern Image* IMAGE_B3_ICONANIM10;
	extern Image* IMAGE_B3_ICONANIM1;
	extern Image* IMAGE_B3_ICONANIM2;
	extern Image* IMAGE_B3_ICONANIM3;
	extern Image* IMAGE_B3_ICONANIM4;
	extern Image* IMAGE_B3_ICONANIM5;
	extern Image* IMAGE_B3_ICONANIM6;
	extern Image* IMAGE_B3_ICONANIM7;
	extern Image* IMAGE_B3_ICONANIM8;
	extern Image* IMAGE_B3_ICONANIM9;
	extern Image* IMAGE_B3_ICONMASK10;
	extern Image* IMAGE_B3_ICONMASK1;
	extern Image* IMAGE_B3_ICONMASK2;
	extern Image* IMAGE_B3_ICONMASK3;
	extern Image* IMAGE_B3_ICONMASK4;
	extern Image* IMAGE_B3_ICONMASK5;
	extern Image* IMAGE_B3_ICONMASK6;
	extern Image* IMAGE_B3_ICONMASK7;
	extern Image* IMAGE_B3_ICONMASK8;
	extern Image* IMAGE_B3_ICONMASK9;
	extern Image* IMAGE_B3_MAP;
	extern Image* IMAGE_B3_MAPSCREEN_BANNER;
	extern Image* IMAGE_B3_MINIMAP_ICONS;
	extern Image* IMAGE_TUT_PIC_CODEX_EVIL;
	extern Image* IMAGE_TUT_PIC_CODEX_EVIL_PEN;
	extern Image* IMAGE_TUT_PIC_DRACULA;
	extern Image* IMAGE_TUT_PIC_FHUNT;
	extern Image* IMAGE_TUT_PIC_FRANKMD;
	extern Image* IMAGE_TUT_PIC_FSWASH;
	extern Image* IMAGE_TUT_PIC_FWARRIOR;
	extern Image* IMAGE_TUT_PIC_FWIZARD;
	extern Image* IMAGE_TUT_PIC_GRIM;
	extern Image* IMAGE_TUT_PIC_MAGISTRATE;
	extern Image* IMAGE_TUT_PIC_THE_CREATURE;
	extern Image* IMAGE_TUT_PIC_WOLFMAN;

	enum ResourceId
	{
		IMAGE_B3_MINIMAP_ICONS_ID,
		IMAGE_B3_MAPSCREEN_BANNER_ID,
		IMAGE_B3_ICONANIM1_ID,
		IMAGE_B3_ICONANIM2_ID,
		IMAGE_B3_ICONANIM3_ID,
		IMAGE_B3_ICONANIM4_ID,
		IMAGE_B3_ICONANIM5_ID,
		IMAGE_B3_ICONANIM6_ID,
		IMAGE_B3_ICONANIM7_ID,
		IMAGE_B3_ICONANIM8_ID,
		IMAGE_B3_ICONANIM9_ID,
		IMAGE_B3_ICONANIM10_ID,
		IMAGE_B3_ICONMASK1_ID,
		IMAGE_B3_ICONMASK2_ID,
		IMAGE_B3_ICONMASK3_ID,
		IMAGE_B3_ICONMASK4_ID,
		IMAGE_B3_ICONMASK5_ID,
		IMAGE_B3_ICONMASK6_ID,
		IMAGE_B3_ICONMASK7_ID,
		IMAGE_B3_ICONMASK8_ID,
		IMAGE_B3_ICONMASK9_ID,
		IMAGE_B3_ICONMASK10_ID,
		IMAGE_B3_MAP_ID,
		IMAGE_TUT_PIC_MAGISTRATE_ID,
		IMAGE_TUT_PIC_FRANKMD_ID,
		IMAGE_TUT_PIC_WOLFMAN_ID,
		IMAGE_TUT_PIC_THE_CREATURE_ID,
		IMAGE_TUT_PIC_GRIM_ID,
		IMAGE_TUT_PIC_FWARRIOR_ID,
		IMAGE_TUT_PIC_FSWASH_ID,
		IMAGE_TUT_PIC_FHUNT_ID,
		IMAGE_TUT_PIC_FWIZARD_ID,
		IMAGE_TUT_PIC_DRACULA_ID,
		IMAGE_TUT_PIC_CODEX_EVIL_ID,
		IMAGE_TUT_PIC_CODEX_EVIL_PEN_ID,
		IMAGE_B3_LEFT_FACING_ARROW_ID,
		IMAGE_B3A_BG1_ID,
		SOUND_BOOK3_CH1_SOUND1_ID,
		SOUND_BOOK3_CH1_SOUND2_ID,
		SOUND_BOOK3_CH1_SOUND3_ID,
		SOUND_BOOK3_CH1_SOUND4_ID,
		SOUND_BOOK3_CH1_SOUND5_ID,
		SOUND_BOOK3_CH1_SOUND6_ID,
		SOUND_BOOK3_CH1_SOUND7_ID,
		SOUND_BOOK3_CH1_SOUND8_ID,
		SOUND_BOOK3_CH1_SOUND9_ID,
		SOUND_BOOK3_CH1_SOUND10_ID,
		IMAGE_B3A_BG2_ID,
		SOUND_BOOK3_CH2_SOUND1_ID,
		SOUND_BOOK3_CH2_SOUND2_ID,
		SOUND_BOOK3_CH2_SOUND3_ID,
		SOUND_BOOK3_CH2_SOUND4_ID,
		SOUND_BOOK3_CH2_SOUND5_ID,
		SOUND_BOOK3_CH2_SOUND6_ID,
		SOUND_BOOK3_CH2_SOUND7_ID,
		SOUND_BOOK3_CH2_SOUND8_ID,
		SOUND_BOOK3_CH2_SOUND9_ID,
		SOUND_BOOK3_CH2_SOUND10_ID,
		SOUND_BOOK3_CH2_SOUND11_ID,
		SOUND_BOOK3_CH2_SOUND12_ID,
		SOUND_BOOK3_CH2_SOUND13_ID,
		SOUND_BOOK3_CH2_SOUND14_ID,
		SOUND_BOOK3_CH2_SOUND15_ID,
		IMAGE_B3A_BG3_ID,
		SOUND_BOOK3_CH3_SOUND1_ID,
		SOUND_BOOK3_CH3_SOUND2_ID,
		SOUND_BOOK3_CH3_SOUND3_ID,
		SOUND_BOOK3_CH3_SOUND4_ID,
		SOUND_BOOK3_CH3_SOUND5_ID,
		SOUND_BOOK3_CH3_SOUND6_ID,
		SOUND_BOOK3_CH3_SOUND7_ID,
		SOUND_BOOK3_CH3_SOUND8_ID,
		SOUND_BOOK3_CH3_SOUND9_ID,
		SOUND_BOOK3_CH3_SOUND10_ID,
		SOUND_BOOK3_CH3_SOUND11_ID,
		IMAGE_B3A_BG4_ID,
		SOUND_BOOK3_CH4_SOUND1_ID,
		SOUND_BOOK3_CH4_SOUND2_ID,
		SOUND_BOOK3_CH4_SOUND3_ID,
		SOUND_BOOK3_CH4_SOUND4_ID,
		SOUND_BOOK3_CH4_SOUND5_ID,
		SOUND_BOOK3_CH4_SOUND6_ID,
		SOUND_BOOK3_CH4_SOUND7_ID,
		SOUND_BOOK3_CH4_SOUND8_ID,
		SOUND_BOOK3_CH4_SOUND9_ID,
		SOUND_BOOK3_CH4_SOUND10_ID,
		SOUND_BOOK3_CH4_SOUND11_ID,
		IMAGE_B3A_BG5_ID,
		SOUND_BOOK3_CH5_SOUND1_ID,
		SOUND_BOOK3_CH5_SOUND2_ID,
		SOUND_BOOK3_CH5_SOUND3_ID,
		SOUND_BOOK3_CH5_SOUND4_ID,
		SOUND_BOOK3_CH5_SOUND5_ID,
		SOUND_BOOK3_CH5_SOUND6_ID,
		SOUND_BOOK3_CH5_SOUND7_ID,
		SOUND_BOOK3_CH5_SOUND8_ID,
		SOUND_BOOK3_CH5_SOUND9_ID,
		SOUND_BOOK3_CH5_SOUND10_ID,
		SOUND_BOOK3_CH5_SOUND11_ID,
		SOUND_BOOK3_CH5_SOUND12_ID,
		IMAGE_B3A_BG6_ID,
		SOUND_BOOK3_CH6_SOUND1_ID,
		SOUND_BOOK3_CH6_SOUND2_ID,
		SOUND_BOOK3_CH6_SOUND3_ID,
		SOUND_BOOK3_CH6_SOUND4_ID,
		SOUND_BOOK3_CH6_SOUND5_ID,
		SOUND_BOOK3_CH6_SOUND6_ID,
		SOUND_BOOK3_CH6_SOUND7_ID,
		SOUND_BOOK3_CH6_SOUND8_ID,
		SOUND_BOOK3_CH6_SOUND9_ID,
		SOUND_BOOK3_CH6_SOUND10_ID,
		SOUND_BOOK3_CH6_SOUND11_ID,
		SOUND_BOOK3_CH6_SOUND12_ID,
		IMAGE_B3A_BG7_ID,
		IMAGE_B3A_HYDRA_BOSS_BATTLE_ID,
		SOUND_BOOK3_CH7_SOUND1_ID,
		SOUND_BOOK3_CH7_SOUND2_ID,
		SOUND_BOOK3_CH7_SOUND3_ID,
		SOUND_BOOK3_CH7_SOUND4_ID,
		SOUND_BOOK3_CH7_SOUND5_ID,
		SOUND_BOOK3_CH7_SOUND6_ID,
		SOUND_BOOK3_CH7_SOUND7_ID,
		SOUND_BOOK3_CH7_SOUND8_ID,
		SOUND_BOOK3_CH7_SOUND9_ID,
		IMAGE_B3A_BG8_ID,
		SOUND_BOOK3_CH8_SOUND1_ID,
		SOUND_BOOK3_CH8_SOUND2_ID,
		SOUND_BOOK3_CH8_SOUND3_ID,
		SOUND_BOOK3_CH8_SOUND4_ID,
		SOUND_BOOK3_CH8_SOUND5_ID,
		SOUND_BOOK3_CH8_SOUND6_ID,
		SOUND_BOOK3_CH8_SOUND7_ID,
		IMAGE_B3A_BG9_ID,
		SOUND_BOOK3_CH9_SOUND1_ID,
		SOUND_BOOK3_CH9_SOUND2_ID,
		SOUND_BOOK3_CH9_SOUND3_ID,
		SOUND_BOOK3_CH9_SOUND4_ID,
		SOUND_BOOK3_CH9_SOUND5_ID,
		SOUND_BOOK3_CH9_SOUND6_ID,
		SOUND_BOOK3_CH9_SOUND7_ID,
		SOUND_BOOK3_CH9_SOUND8_ID,
		SOUND_BOOK3_CH9_SOUND9_ID,
		SOUND_BOOK3_CH9_SOUND10_ID,
		SOUND_BOOK3_CH9_SOUND12_ID,
		SOUND_BOOK3_CH9_SOUND13_ID,
		IMAGE_B3A_BG10_ID,
		IMAGE_B3A_CODEX_BOSS_BATTLE_ID,
		SOUND_BOOK3_CH10_SOUND1_ID,
		SOUND_BOOK3_CH10_SOUND2_ID,
		SOUND_BOOK3_CH10_SOUND3_ID,
		SOUND_BOOK3_CH10_SOUND4_ID,
		SOUND_BOOK3_CH10_SOUND5_ID,
		SOUND_BOOK3_CH10_SOUND7_ID,
		SOUND_BOOK3_CH10_CODEXSUMMON_ID,
		SOUND_BOOK3_CH10_CODEXLAUGH_ID,
		SOUND_BOOK3_CH10_CODEXFLINCH_ID,
		SOUND_BOOK3_CH10_CODEXNYAH_ID,
		SOUND_BOOK3_CH10_LEXBEAM_ID,
		SOUND_BOOK3_CH10_AUTOLOGICAL_ID,
		RESOURCE_ID_MAX
	};

	Image* GetImageById(int theId);
	Font* GetFontById(int theId);
	int GetSoundById(int theId);

	Image*& GetImageRefById(int theId);
	Font*& GetFontRefById(int theId);
	int& GetSoundRefById(int theId);

	ResourceId GetIdByImage(Image *theImage);
	ResourceId GetIdByFont(Font *theFont);
	ResourceId GetIdBySound(int theSound);
	const char* GetStringIdById(int theId);
	ResourceId GetIdByStringId(const char *theStringId);

} // namespace Sexy


#endif
