#ifndef __Book2_H__
#define __Book2_H__

namespace Sexy
{
	class ResourceManager;
	class Image;
	class Font;

	Image* LoadImageById(ResourceManager *theManager, int theId);
	void ReplaceImageById(ResourceManager *theManager, int theId, Image *theImage);
	bool ExtractResourcesByName(ResourceManager *theManager, const char *theName);

	// Book2Chapter1 Resources
	bool ExtractBook2Chapter1Resources(ResourceManager *theMgr);
	extern Image* IMAGE_B2A_DOCKSKY;
	extern int SOUND_BOOK2_CH1_FEMALE1;
	extern int SOUND_BOOK2_CH1_FEMALE2;
	extern int SOUND_BOOK2_CH1_IMPACT1;
	extern int SOUND_BOOK2_CH1_IMPACT2;
	extern int SOUND_BOOK2_CH1_IMPACT3;
	extern int SOUND_BOOK2_CH1_MALE1;
	extern int SOUND_BOOK2_CH1_MALE2;
	extern int SOUND_BOOK2_CH1_MALE3;
	extern int SOUND_BOOK2_CH1_MALE4;
	extern int SOUND_BOOK2_CH1_MALE5;
	extern int SOUND_BOOK2_CH1_MALE6;
	extern int SOUND_BOOK2_CH1_MALE7;
	extern int SOUND_BOOK2_CH1_MALE8;
	extern int SOUND_BOOK2_CH1_MALE9;
	extern int SOUND_BOOK2_CH1_SPECIAL1;
	extern int SOUND_BOOK2_CH1_SPECIAL2;

	// Book2Chapter10 Resources
	bool ExtractBook2Chapter10Resources(ResourceManager *theMgr);
	extern Image* IMAGE_B2A_SUNSET;
	extern int SOUND_BOOK2_CH10_SOUND10;
	extern int SOUND_BOOK2_CH10_SOUND12;
	extern int SOUND_BOOK2_CH10_SOUND13;
	extern int SOUND_BOOK2_CH10_SOUND14;
	extern int SOUND_BOOK2_CH10_SOUND1;
	extern int SOUND_BOOK2_CH10_SOUND2;
	extern int SOUND_BOOK2_CH10_SOUND4;
	extern int SOUND_BOOK2_CH10_SOUND5;
	extern int SOUND_BOOK2_CH10_SOUND6;
	extern int SOUND_BOOK2_CH10_SOUND8;

	// Book2Chapter2 Resources
	bool ExtractBook2Chapter2Resources(ResourceManager *theMgr);
	extern Image* IMAGE_B2A_BLACK3;
	extern int SOUND_BOOK2_CH2_DOG1;
	extern int SOUND_BOOK2_CH2_DOG2;
	extern int SOUND_BOOK2_CH2_DOG3;
	extern int SOUND_BOOK2_CH2_DOG4;
	extern int SOUND_BOOK2_CH2_IMPACT1;
	extern int SOUND_BOOK2_CH2_IMPACT2;
	extern int SOUND_BOOK2_CH2_IMPACT4;
	extern int SOUND_BOOK2_CH2_KUBWA1;
	extern int SOUND_BOOK2_CH2_KUBWA2;
	extern int SOUND_BOOK2_CH2_KUBWA3;
	extern int SOUND_BOOK2_CH2_KUBWA4;
	extern int SOUND_BOOK2_CH2_LARGEIMPACT;
	extern int SOUND_BOOK2_CH2_MALE10;
	extern int SOUND_BOOK2_CH2_MALE1;
	extern int SOUND_BOOK2_CH2_MALE2;
	extern int SOUND_BOOK2_CH2_MALE3;
	extern int SOUND_BOOK2_CH2_MALE4;
	extern int SOUND_BOOK2_CH2_MALE6;
	extern int SOUND_BOOK2_CH2_MALE7;
	extern int SOUND_BOOK2_CH2_MALE8;
	extern int SOUND_BOOK2_CH2_MALE9;
	extern int SOUND_BOOK2_CH2_SPECIAL3;
	extern int SOUND_BOOK2_CH2_WARP;

	// Book2Chapter3 Resources
	bool ExtractBook2Chapter3Resources(ResourceManager *theMgr);
	extern Image* IMAGE_B2A_BLACK2;
	extern int SOUND_BOOK2_CH3_DOG1;
	extern int SOUND_BOOK2_CH3_DOG2;
	extern int SOUND_BOOK2_CH3_DOG3;
	extern int SOUND_BOOK2_CH3_DOG4;
	extern int SOUND_BOOK2_CH3_DRAGON1;
	extern int SOUND_BOOK2_CH3_DRAGON2;
	extern int SOUND_BOOK2_CH3_DRAGON3;
	extern int SOUND_BOOK2_CH3_DRAGON4;
	extern int SOUND_BOOK2_CH3_HISS;
	extern int SOUND_BOOK2_CH3_IMPACT1;
	extern int SOUND_BOOK2_CH3_IMPACT2;
	extern int SOUND_BOOK2_CH3_MALE1;
	extern int SOUND_BOOK2_CH3_MALE2;
	extern int SOUND_BOOK2_CH3_MALE3;
	extern int SOUND_BOOK2_CH3_MALE4;
	extern int SOUND_BOOK2_CH3_SPECIAL1;
	extern int SOUND_BOOK2_CH3_SPECIAL2;
	extern int SOUND_BOOK2_CH3_SPECIAL3;
	extern int SOUND_BOOK2_CH3_SQUEAL1;
	extern int SOUND_BOOK2_CH3_SQUEAL2;

	// Book2Chapter4 Resources
	bool ExtractBook2Chapter4Resources(ResourceManager *theMgr);
	extern Image* IMAGE_B2A_PYRA_SKY;
	extern Image* IMAGE_B2_SPHINX_BOSS_BATTLE;
	extern Image* IMAGE_B2_SPHINX_RIDDLE;
	extern int SOUND_BOOK2_CH4_ATTACK;
	extern int SOUND_BOOK2_CH4_DEATH;

	// Book2Chapter5 Resources
	bool ExtractBook2Chapter5Resources(ResourceManager *theMgr);
	extern Image* IMAGE_B2A_BLUE_SEA;
	extern int SOUND_BOOK2_CH5_ATTACK1;
	extern int SOUND_BOOK2_CH5_ATTACK6;
	extern int SOUND_BOOK2_CH5_DOG1;
	extern int SOUND_BOOK2_CH5_DOG2;
	extern int SOUND_BOOK2_CH5_DOG3;
	extern int SOUND_BOOK2_CH5_DOG4;
	extern int SOUND_BOOK2_CH5_HIT1;
	extern int SOUND_BOOK2_CH5_MALE1;
	extern int SOUND_BOOK2_CH5_MALE2;
	extern int SOUND_BOOK2_CH5_MALE3;
	extern int SOUND_BOOK2_CH5_MALE4;
	extern int SOUND_BOOK2_CH5_MALE5;
	extern int SOUND_BOOK2_CH5_MALE6;
	extern int SOUND_BOOK2_CH5_MALE7;
	extern int SOUND_BOOK2_CH5_MALE8;

	// Book2Chapter6 Resources
	bool ExtractBook2Chapter6Resources(ResourceManager *theMgr);
	extern Image* IMAGE_B2A_BLUE_SEA2;
	extern int SOUND_BOOK2_CH6_SOUND10;
	extern int SOUND_BOOK2_CH6_SOUND11;
	extern int SOUND_BOOK2_CH6_SOUND12;
	extern int SOUND_BOOK2_CH6_SOUND1;
	extern int SOUND_BOOK2_CH6_SOUND3;
	extern int SOUND_BOOK2_CH6_SOUND4;
	extern int SOUND_BOOK2_CH6_SOUND6;
	extern int SOUND_BOOK2_CH6_SOUND7;
	extern int SOUND_BOOK2_CH6_SOUND8;
	extern int SOUND_BOOK2_CH6_SOUND9;

	// Book2Chapter7 Resources
	bool ExtractBook2Chapter7Resources(ResourceManager *theMgr);
	extern Image* IMAGE_B2A_MIRAGE;
	extern int SOUND_BOOK2_CH7_SOUND12;
	extern int SOUND_BOOK2_CH7_SOUND13;
	extern int SOUND_BOOK2_CH7_SOUND15;
	extern int SOUND_BOOK2_CH7_SOUND16;
	extern int SOUND_BOOK2_CH7_SOUND17;
	extern int SOUND_BOOK2_CH7_SOUND18;
	extern int SOUND_BOOK2_CH7_SOUND1;
	extern int SOUND_BOOK2_CH7_SOUND2;
	extern int SOUND_BOOK2_CH7_SOUND4;
	extern int SOUND_BOOK2_CH7_SOUND5;
	extern int SOUND_BOOK2_CH7_SOUND6;

	// Book2Chapter8 Resources
	bool ExtractBook2Chapter8Resources(ResourceManager *theMgr);
	extern Image* IMAGE_B2A_SKY8;
	extern int SOUND_BOOK2_CH8_SOUND10;
	extern int SOUND_BOOK2_CH8_SOUND12;
	extern int SOUND_BOOK2_CH8_SOUND13;
	extern int SOUND_BOOK2_CH8_SOUND14;
	extern int SOUND_BOOK2_CH8_SOUND15;
	extern int SOUND_BOOK2_CH8_SOUND16;
	extern int SOUND_BOOK2_CH8_SOUND18;
	extern int SOUND_BOOK2_CH8_SOUND1;
	extern int SOUND_BOOK2_CH8_SOUND2;
	extern int SOUND_BOOK2_CH8_SOUND3;
	extern int SOUND_BOOK2_CH8_SOUND4;
	extern int SOUND_BOOK2_CH8_SOUND5;
	extern int SOUND_BOOK2_CH8_SOUND7;
	extern int SOUND_BOOK2_CH8_SOUND8;
	extern int SOUND_BOOK2_CH8_SOUND9;

	// Book2Chapter9 Resources
	bool ExtractBook2Chapter9Resources(ResourceManager *theMgr);
	extern Image* IMAGE_B2A_SKY9;
	extern int SOUND_BOOK2_CH9_SOUND12;
	extern int SOUND_BOOK2_CH9_SOUND13;
	extern int SOUND_BOOK2_CH9_SOUND15;
	extern int SOUND_BOOK2_CH9_SOUND1;
	extern int SOUND_BOOK2_CH9_SOUND2;
	extern int SOUND_BOOK2_CH9_SOUND3;
	extern int SOUND_BOOK2_CH9_SOUND4;
	extern int SOUND_BOOK2_CH9_SOUND5;
	extern int SOUND_BOOK2_CH9_SOUND7;
	extern int SOUND_BOOK2_CH9_SOUND8;

	// Book2Common Resources
	bool ExtractBook2CommonResources(ResourceManager *theMgr);
	extern Image* IMAGE_B2_LEFT_FACING_ARROW;

	// Book2Init Resources
	bool ExtractBook2InitResources(ResourceManager *theMgr);
	extern Image* IMAGE_B2_ICONANIM10;
	extern Image* IMAGE_B2_ICONANIM1;
	extern Image* IMAGE_B2_ICONANIM2;
	extern Image* IMAGE_B2_ICONANIM3;
	extern Image* IMAGE_B2_ICONANIM4;
	extern Image* IMAGE_B2_ICONANIM5;
	extern Image* IMAGE_B2_ICONANIM6;
	extern Image* IMAGE_B2_ICONANIM7;
	extern Image* IMAGE_B2_ICONANIM8;
	extern Image* IMAGE_B2_ICONANIM9;
	extern Image* IMAGE_B2_ICONMASK10;
	extern Image* IMAGE_B2_ICONMASK1;
	extern Image* IMAGE_B2_ICONMASK2;
	extern Image* IMAGE_B2_ICONMASK3;
	extern Image* IMAGE_B2_ICONMASK4;
	extern Image* IMAGE_B2_ICONMASK5;
	extern Image* IMAGE_B2_ICONMASK6;
	extern Image* IMAGE_B2_ICONMASK7;
	extern Image* IMAGE_B2_ICONMASK8;
	extern Image* IMAGE_B2_ICONMASK9;
	extern Image* IMAGE_B2_MAP;
	extern Image* IMAGE_B2_MAPSCREEN_BANNER;
	extern Image* IMAGE_B2_MINIMAP_ICONS;
	extern Image* IMAGE_TUT_PIC_MALADIN;
	extern Image* IMAGE_TUT_PIC_MURRAY;
	extern Image* IMAGE_TUT_PIC_SCHE1;
	extern Image* IMAGE_TUT_PIC_SCHE2;
	extern Image* IMAGE_TUT_PIC_SINBAD;
	extern Image* IMAGE_TUT_PIC_VIZIER;

	enum ResourceId
	{
		IMAGE_B2_MINIMAP_ICONS_ID,
		IMAGE_B2_MAPSCREEN_BANNER_ID,
		IMAGE_B2_ICONANIM1_ID,
		IMAGE_B2_ICONANIM2_ID,
		IMAGE_B2_ICONANIM3_ID,
		IMAGE_B2_ICONANIM4_ID,
		IMAGE_B2_ICONANIM5_ID,
		IMAGE_B2_ICONANIM6_ID,
		IMAGE_B2_ICONANIM7_ID,
		IMAGE_B2_ICONANIM8_ID,
		IMAGE_B2_ICONANIM9_ID,
		IMAGE_B2_ICONANIM10_ID,
		IMAGE_B2_ICONMASK1_ID,
		IMAGE_B2_ICONMASK2_ID,
		IMAGE_B2_ICONMASK3_ID,
		IMAGE_B2_ICONMASK4_ID,
		IMAGE_B2_ICONMASK5_ID,
		IMAGE_B2_ICONMASK6_ID,
		IMAGE_B2_ICONMASK7_ID,
		IMAGE_B2_ICONMASK8_ID,
		IMAGE_B2_ICONMASK9_ID,
		IMAGE_B2_ICONMASK10_ID,
		IMAGE_B2_MAP_ID,
		IMAGE_TUT_PIC_MURRAY_ID,
		IMAGE_TUT_PIC_SCHE1_ID,
		IMAGE_TUT_PIC_SCHE2_ID,
		IMAGE_TUT_PIC_SINBAD_ID,
		IMAGE_TUT_PIC_VIZIER_ID,
		IMAGE_TUT_PIC_MALADIN_ID,
		IMAGE_B2_LEFT_FACING_ARROW_ID,
		IMAGE_B2A_DOCKSKY_ID,
		SOUND_BOOK2_CH1_MALE1_ID,
		SOUND_BOOK2_CH1_MALE2_ID,
		SOUND_BOOK2_CH1_MALE3_ID,
		SOUND_BOOK2_CH1_MALE4_ID,
		SOUND_BOOK2_CH1_MALE5_ID,
		SOUND_BOOK2_CH1_MALE6_ID,
		SOUND_BOOK2_CH1_MALE7_ID,
		SOUND_BOOK2_CH1_MALE8_ID,
		SOUND_BOOK2_CH1_MALE9_ID,
		SOUND_BOOK2_CH1_FEMALE1_ID,
		SOUND_BOOK2_CH1_FEMALE2_ID,
		SOUND_BOOK2_CH1_IMPACT1_ID,
		SOUND_BOOK2_CH1_IMPACT2_ID,
		SOUND_BOOK2_CH1_IMPACT3_ID,
		SOUND_BOOK2_CH1_SPECIAL1_ID,
		SOUND_BOOK2_CH1_SPECIAL2_ID,
		IMAGE_B2A_BLACK3_ID,
		SOUND_BOOK2_CH2_MALE1_ID,
		SOUND_BOOK2_CH2_MALE2_ID,
		SOUND_BOOK2_CH2_MALE3_ID,
		SOUND_BOOK2_CH2_MALE4_ID,
		SOUND_BOOK2_CH2_MALE6_ID,
		SOUND_BOOK2_CH2_MALE7_ID,
		SOUND_BOOK2_CH2_MALE8_ID,
		SOUND_BOOK2_CH2_MALE9_ID,
		SOUND_BOOK2_CH2_MALE10_ID,
		SOUND_BOOK2_CH2_IMPACT1_ID,
		SOUND_BOOK2_CH2_IMPACT2_ID,
		SOUND_BOOK2_CH2_IMPACT4_ID,
		SOUND_BOOK2_CH2_SPECIAL3_ID,
		SOUND_BOOK2_CH2_DOG1_ID,
		SOUND_BOOK2_CH2_DOG2_ID,
		SOUND_BOOK2_CH2_DOG3_ID,
		SOUND_BOOK2_CH2_DOG4_ID,
		SOUND_BOOK2_CH2_LARGEIMPACT_ID,
		SOUND_BOOK2_CH2_WARP_ID,
		SOUND_BOOK2_CH2_KUBWA1_ID,
		SOUND_BOOK2_CH2_KUBWA2_ID,
		SOUND_BOOK2_CH2_KUBWA3_ID,
		SOUND_BOOK2_CH2_KUBWA4_ID,
		IMAGE_B2A_BLACK2_ID,
		SOUND_BOOK2_CH3_SQUEAL1_ID,
		SOUND_BOOK2_CH3_SQUEAL2_ID,
		SOUND_BOOK2_CH3_HISS_ID,
		SOUND_BOOK2_CH3_DRAGON1_ID,
		SOUND_BOOK2_CH3_DRAGON2_ID,
		SOUND_BOOK2_CH3_DRAGON3_ID,
		SOUND_BOOK2_CH3_DRAGON4_ID,
		SOUND_BOOK2_CH3_DOG1_ID,
		SOUND_BOOK2_CH3_DOG2_ID,
		SOUND_BOOK2_CH3_DOG3_ID,
		SOUND_BOOK2_CH3_DOG4_ID,
		SOUND_BOOK2_CH3_IMPACT1_ID,
		SOUND_BOOK2_CH3_IMPACT2_ID,
		SOUND_BOOK2_CH3_SPECIAL1_ID,
		SOUND_BOOK2_CH3_SPECIAL2_ID,
		SOUND_BOOK2_CH3_SPECIAL3_ID,
		SOUND_BOOK2_CH3_MALE1_ID,
		SOUND_BOOK2_CH3_MALE2_ID,
		SOUND_BOOK2_CH3_MALE3_ID,
		SOUND_BOOK2_CH3_MALE4_ID,
		IMAGE_B2A_PYRA_SKY_ID,
		IMAGE_B2_SPHINX_RIDDLE_ID,
		IMAGE_B2_SPHINX_BOSS_BATTLE_ID,
		SOUND_BOOK2_CH4_DEATH_ID,
		SOUND_BOOK2_CH4_ATTACK_ID,
		IMAGE_B2A_BLUE_SEA_ID,
		SOUND_BOOK2_CH5_DOG1_ID,
		SOUND_BOOK2_CH5_DOG2_ID,
		SOUND_BOOK2_CH5_DOG3_ID,
		SOUND_BOOK2_CH5_DOG4_ID,
		SOUND_BOOK2_CH5_HIT1_ID,
		SOUND_BOOK2_CH5_MALE1_ID,
		SOUND_BOOK2_CH5_MALE2_ID,
		SOUND_BOOK2_CH5_MALE3_ID,
		SOUND_BOOK2_CH5_MALE4_ID,
		SOUND_BOOK2_CH5_MALE5_ID,
		SOUND_BOOK2_CH5_MALE6_ID,
		SOUND_BOOK2_CH5_MALE7_ID,
		SOUND_BOOK2_CH5_MALE8_ID,
		SOUND_BOOK2_CH5_ATTACK1_ID,
		SOUND_BOOK2_CH5_ATTACK6_ID,
		IMAGE_B2A_BLUE_SEA2_ID,
		SOUND_BOOK2_CH6_SOUND1_ID,
		SOUND_BOOK2_CH6_SOUND3_ID,
		SOUND_BOOK2_CH6_SOUND4_ID,
		SOUND_BOOK2_CH6_SOUND6_ID,
		SOUND_BOOK2_CH6_SOUND7_ID,
		SOUND_BOOK2_CH6_SOUND8_ID,
		SOUND_BOOK2_CH6_SOUND9_ID,
		SOUND_BOOK2_CH6_SOUND10_ID,
		SOUND_BOOK2_CH6_SOUND11_ID,
		SOUND_BOOK2_CH6_SOUND12_ID,
		IMAGE_B2A_MIRAGE_ID,
		SOUND_BOOK2_CH7_SOUND1_ID,
		SOUND_BOOK2_CH7_SOUND2_ID,
		SOUND_BOOK2_CH7_SOUND4_ID,
		SOUND_BOOK2_CH7_SOUND5_ID,
		SOUND_BOOK2_CH7_SOUND6_ID,
		SOUND_BOOK2_CH7_SOUND12_ID,
		SOUND_BOOK2_CH7_SOUND13_ID,
		SOUND_BOOK2_CH7_SOUND15_ID,
		SOUND_BOOK2_CH7_SOUND16_ID,
		SOUND_BOOK2_CH7_SOUND17_ID,
		SOUND_BOOK2_CH7_SOUND18_ID,
		IMAGE_B2A_SKY8_ID,
		SOUND_BOOK2_CH8_SOUND1_ID,
		SOUND_BOOK2_CH8_SOUND2_ID,
		SOUND_BOOK2_CH8_SOUND3_ID,
		SOUND_BOOK2_CH8_SOUND4_ID,
		SOUND_BOOK2_CH8_SOUND5_ID,
		SOUND_BOOK2_CH8_SOUND7_ID,
		SOUND_BOOK2_CH8_SOUND8_ID,
		SOUND_BOOK2_CH8_SOUND9_ID,
		SOUND_BOOK2_CH8_SOUND10_ID,
		SOUND_BOOK2_CH8_SOUND12_ID,
		SOUND_BOOK2_CH8_SOUND13_ID,
		SOUND_BOOK2_CH8_SOUND14_ID,
		SOUND_BOOK2_CH8_SOUND15_ID,
		SOUND_BOOK2_CH8_SOUND16_ID,
		SOUND_BOOK2_CH8_SOUND18_ID,
		IMAGE_B2A_SKY9_ID,
		SOUND_BOOK2_CH9_SOUND1_ID,
		SOUND_BOOK2_CH9_SOUND2_ID,
		SOUND_BOOK2_CH9_SOUND3_ID,
		SOUND_BOOK2_CH9_SOUND4_ID,
		SOUND_BOOK2_CH9_SOUND5_ID,
		SOUND_BOOK2_CH9_SOUND7_ID,
		SOUND_BOOK2_CH9_SOUND8_ID,
		SOUND_BOOK2_CH9_SOUND12_ID,
		SOUND_BOOK2_CH9_SOUND13_ID,
		SOUND_BOOK2_CH9_SOUND15_ID,
		IMAGE_B2A_SUNSET_ID,
		SOUND_BOOK2_CH10_SOUND1_ID,
		SOUND_BOOK2_CH10_SOUND2_ID,
		SOUND_BOOK2_CH10_SOUND4_ID,
		SOUND_BOOK2_CH10_SOUND5_ID,
		SOUND_BOOK2_CH10_SOUND6_ID,
		SOUND_BOOK2_CH10_SOUND8_ID,
		SOUND_BOOK2_CH10_SOUND10_ID,
		SOUND_BOOK2_CH10_SOUND12_ID,
		SOUND_BOOK2_CH10_SOUND13_ID,
		SOUND_BOOK2_CH10_SOUND14_ID,
		RESOURCE_ID_MAX
	};

	Image* GetImageById(int theId);
	Font* GetFontById(int theId);
	int GetSoundById(int theId);

	Image*& GetImageRefById(int theId);
	Font*& GetFontRefById(int theId);
	int& GetSoundRefById(int theId);

	ResourceId GetIdByImage(Image *theImage);
	ResourceId GetIdByFont(Font *theFont);
	ResourceId GetIdBySound(int theSound);
	const char* GetStringIdById(int theId);
	ResourceId GetIdByStringId(const char *theStringId);

} // namespace Sexy


#endif
