#include "Book3.h"
#include "SexyAppFramework/ResourceManager.h"

using namespace Sexy;

#pragma warning(disable:4311 4312)

static bool gNeedRecalcVariableToIdMap = false;

bool Sexy::ExtractResourcesByName(ResourceManager *theManager, const char *theName)
{
	if (strcmp(theName,"Book3Chapter1")==0) return ExtractBook3Chapter1Resources(theManager);
	if (strcmp(theName,"Book3Chapter10")==0) return ExtractBook3Chapter10Resources(theManager);
	if (strcmp(theName,"Book3Chapter2")==0) return ExtractBook3Chapter2Resources(theManager);
	if (strcmp(theName,"Book3Chapter3")==0) return ExtractBook3Chapter3Resources(theManager);
	if (strcmp(theName,"Book3Chapter4")==0) return ExtractBook3Chapter4Resources(theManager);
	if (strcmp(theName,"Book3Chapter5")==0) return ExtractBook3Chapter5Resources(theManager);
	if (strcmp(theName,"Book3Chapter6")==0) return ExtractBook3Chapter6Resources(theManager);
	if (strcmp(theName,"Book3Chapter7")==0) return ExtractBook3Chapter7Resources(theManager);
	if (strcmp(theName,"Book3Chapter8")==0) return ExtractBook3Chapter8Resources(theManager);
	if (strcmp(theName,"Book3Chapter9")==0) return ExtractBook3Chapter9Resources(theManager);
	if (strcmp(theName,"Book3Common")==0) return ExtractBook3CommonResources(theManager);
	if (strcmp(theName,"Book3Init")==0) return ExtractBook3InitResources(theManager);
	return false;
}

Sexy::ResourceId Sexy::GetIdByStringId(const char *theStringId)
{
	typedef std::map<std::string,int> MyMap;
	static MyMap aMap;
	if(aMap.empty())
	{
		for(int i=0; i<RESOURCE_ID_MAX; i++)
			aMap[GetStringIdById(i)] = i;
	}

	MyMap::iterator anItr = aMap.find(theStringId);
	if (anItr == aMap.end())
		return RESOURCE_ID_MAX;
	else
		return (ResourceId) anItr->second;
}

// Book3Chapter1 Resources
Image* Sexy::IMAGE_B3A_BG1;
int Sexy::SOUND_BOOK3_CH1_SOUND1;
int Sexy::SOUND_BOOK3_CH1_SOUND10;
int Sexy::SOUND_BOOK3_CH1_SOUND2;
int Sexy::SOUND_BOOK3_CH1_SOUND3;
int Sexy::SOUND_BOOK3_CH1_SOUND4;
int Sexy::SOUND_BOOK3_CH1_SOUND5;
int Sexy::SOUND_BOOK3_CH1_SOUND6;
int Sexy::SOUND_BOOK3_CH1_SOUND7;
int Sexy::SOUND_BOOK3_CH1_SOUND8;
int Sexy::SOUND_BOOK3_CH1_SOUND9;

bool Sexy::ExtractBook3Chapter1Resources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_B3A_BG1 = aMgr.GetImageThrow("IMAGE_B3A_BG1");
		SOUND_BOOK3_CH1_SOUND1 = aMgr.GetSoundThrow("SOUND_BOOK3_CH1_SOUND1");
		SOUND_BOOK3_CH1_SOUND10 = aMgr.GetSoundThrow("SOUND_BOOK3_CH1_SOUND10");
		SOUND_BOOK3_CH1_SOUND2 = aMgr.GetSoundThrow("SOUND_BOOK3_CH1_SOUND2");
		SOUND_BOOK3_CH1_SOUND3 = aMgr.GetSoundThrow("SOUND_BOOK3_CH1_SOUND3");
		SOUND_BOOK3_CH1_SOUND4 = aMgr.GetSoundThrow("SOUND_BOOK3_CH1_SOUND4");
		SOUND_BOOK3_CH1_SOUND5 = aMgr.GetSoundThrow("SOUND_BOOK3_CH1_SOUND5");
		SOUND_BOOK3_CH1_SOUND6 = aMgr.GetSoundThrow("SOUND_BOOK3_CH1_SOUND6");
		SOUND_BOOK3_CH1_SOUND7 = aMgr.GetSoundThrow("SOUND_BOOK3_CH1_SOUND7");
		SOUND_BOOK3_CH1_SOUND8 = aMgr.GetSoundThrow("SOUND_BOOK3_CH1_SOUND8");
		SOUND_BOOK3_CH1_SOUND9 = aMgr.GetSoundThrow("SOUND_BOOK3_CH1_SOUND9");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// Book3Chapter10 Resources
Image* Sexy::IMAGE_B3A_BG10;
Image* Sexy::IMAGE_B3A_CODEX_BOSS_BATTLE;
int Sexy::SOUND_BOOK3_CH10_AUTOLOGICAL;
int Sexy::SOUND_BOOK3_CH10_CODEXFLINCH;
int Sexy::SOUND_BOOK3_CH10_CODEXLAUGH;
int Sexy::SOUND_BOOK3_CH10_CODEXNYAH;
int Sexy::SOUND_BOOK3_CH10_CODEXSUMMON;
int Sexy::SOUND_BOOK3_CH10_LEXBEAM;
int Sexy::SOUND_BOOK3_CH10_SOUND1;
int Sexy::SOUND_BOOK3_CH10_SOUND2;
int Sexy::SOUND_BOOK3_CH10_SOUND3;
int Sexy::SOUND_BOOK3_CH10_SOUND4;
int Sexy::SOUND_BOOK3_CH10_SOUND5;
int Sexy::SOUND_BOOK3_CH10_SOUND7;

bool Sexy::ExtractBook3Chapter10Resources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_B3A_BG10 = aMgr.GetImageThrow("IMAGE_B3A_BG10");
		IMAGE_B3A_CODEX_BOSS_BATTLE = aMgr.GetImageThrow("IMAGE_B3A_CODEX_BOSS_BATTLE");
		SOUND_BOOK3_CH10_AUTOLOGICAL = aMgr.GetSoundThrow("SOUND_BOOK3_CH10_AUTOLOGICAL");
		SOUND_BOOK3_CH10_CODEXFLINCH = aMgr.GetSoundThrow("SOUND_BOOK3_CH10_CODEXFLINCH");
		SOUND_BOOK3_CH10_CODEXLAUGH = aMgr.GetSoundThrow("SOUND_BOOK3_CH10_CODEXLAUGH");
		SOUND_BOOK3_CH10_CODEXNYAH = aMgr.GetSoundThrow("SOUND_BOOK3_CH10_CODEXNYAH");
		SOUND_BOOK3_CH10_CODEXSUMMON = aMgr.GetSoundThrow("SOUND_BOOK3_CH10_CODEXSUMMON");
		SOUND_BOOK3_CH10_LEXBEAM = aMgr.GetSoundThrow("SOUND_BOOK3_CH10_LEXBEAM");
		SOUND_BOOK3_CH10_SOUND1 = aMgr.GetSoundThrow("SOUND_BOOK3_CH10_SOUND1");
		SOUND_BOOK3_CH10_SOUND2 = aMgr.GetSoundThrow("SOUND_BOOK3_CH10_SOUND2");
		SOUND_BOOK3_CH10_SOUND3 = aMgr.GetSoundThrow("SOUND_BOOK3_CH10_SOUND3");
		SOUND_BOOK3_CH10_SOUND4 = aMgr.GetSoundThrow("SOUND_BOOK3_CH10_SOUND4");
		SOUND_BOOK3_CH10_SOUND5 = aMgr.GetSoundThrow("SOUND_BOOK3_CH10_SOUND5");
		SOUND_BOOK3_CH10_SOUND7 = aMgr.GetSoundThrow("SOUND_BOOK3_CH10_SOUND7");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// Book3Chapter2 Resources
Image* Sexy::IMAGE_B3A_BG2;
int Sexy::SOUND_BOOK3_CH2_SOUND1;
int Sexy::SOUND_BOOK3_CH2_SOUND10;
int Sexy::SOUND_BOOK3_CH2_SOUND11;
int Sexy::SOUND_BOOK3_CH2_SOUND12;
int Sexy::SOUND_BOOK3_CH2_SOUND13;
int Sexy::SOUND_BOOK3_CH2_SOUND14;
int Sexy::SOUND_BOOK3_CH2_SOUND15;
int Sexy::SOUND_BOOK3_CH2_SOUND2;
int Sexy::SOUND_BOOK3_CH2_SOUND3;
int Sexy::SOUND_BOOK3_CH2_SOUND4;
int Sexy::SOUND_BOOK3_CH2_SOUND5;
int Sexy::SOUND_BOOK3_CH2_SOUND6;
int Sexy::SOUND_BOOK3_CH2_SOUND7;
int Sexy::SOUND_BOOK3_CH2_SOUND8;
int Sexy::SOUND_BOOK3_CH2_SOUND9;

bool Sexy::ExtractBook3Chapter2Resources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_B3A_BG2 = aMgr.GetImageThrow("IMAGE_B3A_BG2");
		SOUND_BOOK3_CH2_SOUND1 = aMgr.GetSoundThrow("SOUND_BOOK3_CH2_SOUND1");
		SOUND_BOOK3_CH2_SOUND10 = aMgr.GetSoundThrow("SOUND_BOOK3_CH2_SOUND10");
		SOUND_BOOK3_CH2_SOUND11 = aMgr.GetSoundThrow("SOUND_BOOK3_CH2_SOUND11");
		SOUND_BOOK3_CH2_SOUND12 = aMgr.GetSoundThrow("SOUND_BOOK3_CH2_SOUND12");
		SOUND_BOOK3_CH2_SOUND13 = aMgr.GetSoundThrow("SOUND_BOOK3_CH2_SOUND13");
		SOUND_BOOK3_CH2_SOUND14 = aMgr.GetSoundThrow("SOUND_BOOK3_CH2_SOUND14");
		SOUND_BOOK3_CH2_SOUND15 = aMgr.GetSoundThrow("SOUND_BOOK3_CH2_SOUND15");
		SOUND_BOOK3_CH2_SOUND2 = aMgr.GetSoundThrow("SOUND_BOOK3_CH2_SOUND2");
		SOUND_BOOK3_CH2_SOUND3 = aMgr.GetSoundThrow("SOUND_BOOK3_CH2_SOUND3");
		SOUND_BOOK3_CH2_SOUND4 = aMgr.GetSoundThrow("SOUND_BOOK3_CH2_SOUND4");
		SOUND_BOOK3_CH2_SOUND5 = aMgr.GetSoundThrow("SOUND_BOOK3_CH2_SOUND5");
		SOUND_BOOK3_CH2_SOUND6 = aMgr.GetSoundThrow("SOUND_BOOK3_CH2_SOUND6");
		SOUND_BOOK3_CH2_SOUND7 = aMgr.GetSoundThrow("SOUND_BOOK3_CH2_SOUND7");
		SOUND_BOOK3_CH2_SOUND8 = aMgr.GetSoundThrow("SOUND_BOOK3_CH2_SOUND8");
		SOUND_BOOK3_CH2_SOUND9 = aMgr.GetSoundThrow("SOUND_BOOK3_CH2_SOUND9");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// Book3Chapter3 Resources
Image* Sexy::IMAGE_B3A_BG3;
int Sexy::SOUND_BOOK3_CH3_SOUND1;
int Sexy::SOUND_BOOK3_CH3_SOUND10;
int Sexy::SOUND_BOOK3_CH3_SOUND11;
int Sexy::SOUND_BOOK3_CH3_SOUND2;
int Sexy::SOUND_BOOK3_CH3_SOUND3;
int Sexy::SOUND_BOOK3_CH3_SOUND4;
int Sexy::SOUND_BOOK3_CH3_SOUND5;
int Sexy::SOUND_BOOK3_CH3_SOUND6;
int Sexy::SOUND_BOOK3_CH3_SOUND7;
int Sexy::SOUND_BOOK3_CH3_SOUND8;
int Sexy::SOUND_BOOK3_CH3_SOUND9;

bool Sexy::ExtractBook3Chapter3Resources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_B3A_BG3 = aMgr.GetImageThrow("IMAGE_B3A_BG3");
		SOUND_BOOK3_CH3_SOUND1 = aMgr.GetSoundThrow("SOUND_BOOK3_CH3_SOUND1");
		SOUND_BOOK3_CH3_SOUND10 = aMgr.GetSoundThrow("SOUND_BOOK3_CH3_SOUND10");
		SOUND_BOOK3_CH3_SOUND11 = aMgr.GetSoundThrow("SOUND_BOOK3_CH3_SOUND11");
		SOUND_BOOK3_CH3_SOUND2 = aMgr.GetSoundThrow("SOUND_BOOK3_CH3_SOUND2");
		SOUND_BOOK3_CH3_SOUND3 = aMgr.GetSoundThrow("SOUND_BOOK3_CH3_SOUND3");
		SOUND_BOOK3_CH3_SOUND4 = aMgr.GetSoundThrow("SOUND_BOOK3_CH3_SOUND4");
		SOUND_BOOK3_CH3_SOUND5 = aMgr.GetSoundThrow("SOUND_BOOK3_CH3_SOUND5");
		SOUND_BOOK3_CH3_SOUND6 = aMgr.GetSoundThrow("SOUND_BOOK3_CH3_SOUND6");
		SOUND_BOOK3_CH3_SOUND7 = aMgr.GetSoundThrow("SOUND_BOOK3_CH3_SOUND7");
		SOUND_BOOK3_CH3_SOUND8 = aMgr.GetSoundThrow("SOUND_BOOK3_CH3_SOUND8");
		SOUND_BOOK3_CH3_SOUND9 = aMgr.GetSoundThrow("SOUND_BOOK3_CH3_SOUND9");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// Book3Chapter4 Resources
Image* Sexy::IMAGE_B3A_BG4;
int Sexy::SOUND_BOOK3_CH4_SOUND1;
int Sexy::SOUND_BOOK3_CH4_SOUND10;
int Sexy::SOUND_BOOK3_CH4_SOUND11;
int Sexy::SOUND_BOOK3_CH4_SOUND2;
int Sexy::SOUND_BOOK3_CH4_SOUND3;
int Sexy::SOUND_BOOK3_CH4_SOUND4;
int Sexy::SOUND_BOOK3_CH4_SOUND5;
int Sexy::SOUND_BOOK3_CH4_SOUND6;
int Sexy::SOUND_BOOK3_CH4_SOUND7;
int Sexy::SOUND_BOOK3_CH4_SOUND8;
int Sexy::SOUND_BOOK3_CH4_SOUND9;

bool Sexy::ExtractBook3Chapter4Resources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_B3A_BG4 = aMgr.GetImageThrow("IMAGE_B3A_BG4");
		SOUND_BOOK3_CH4_SOUND1 = aMgr.GetSoundThrow("SOUND_BOOK3_CH4_SOUND1");
		SOUND_BOOK3_CH4_SOUND10 = aMgr.GetSoundThrow("SOUND_BOOK3_CH4_SOUND10");
		SOUND_BOOK3_CH4_SOUND11 = aMgr.GetSoundThrow("SOUND_BOOK3_CH4_SOUND11");
		SOUND_BOOK3_CH4_SOUND2 = aMgr.GetSoundThrow("SOUND_BOOK3_CH4_SOUND2");
		SOUND_BOOK3_CH4_SOUND3 = aMgr.GetSoundThrow("SOUND_BOOK3_CH4_SOUND3");
		SOUND_BOOK3_CH4_SOUND4 = aMgr.GetSoundThrow("SOUND_BOOK3_CH4_SOUND4");
		SOUND_BOOK3_CH4_SOUND5 = aMgr.GetSoundThrow("SOUND_BOOK3_CH4_SOUND5");
		SOUND_BOOK3_CH4_SOUND6 = aMgr.GetSoundThrow("SOUND_BOOK3_CH4_SOUND6");
		SOUND_BOOK3_CH4_SOUND7 = aMgr.GetSoundThrow("SOUND_BOOK3_CH4_SOUND7");
		SOUND_BOOK3_CH4_SOUND8 = aMgr.GetSoundThrow("SOUND_BOOK3_CH4_SOUND8");
		SOUND_BOOK3_CH4_SOUND9 = aMgr.GetSoundThrow("SOUND_BOOK3_CH4_SOUND9");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// Book3Chapter5 Resources
Image* Sexy::IMAGE_B3A_BG5;
int Sexy::SOUND_BOOK3_CH5_SOUND1;
int Sexy::SOUND_BOOK3_CH5_SOUND10;
int Sexy::SOUND_BOOK3_CH5_SOUND11;
int Sexy::SOUND_BOOK3_CH5_SOUND12;
int Sexy::SOUND_BOOK3_CH5_SOUND2;
int Sexy::SOUND_BOOK3_CH5_SOUND3;
int Sexy::SOUND_BOOK3_CH5_SOUND4;
int Sexy::SOUND_BOOK3_CH5_SOUND5;
int Sexy::SOUND_BOOK3_CH5_SOUND6;
int Sexy::SOUND_BOOK3_CH5_SOUND7;
int Sexy::SOUND_BOOK3_CH5_SOUND8;
int Sexy::SOUND_BOOK3_CH5_SOUND9;

bool Sexy::ExtractBook3Chapter5Resources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_B3A_BG5 = aMgr.GetImageThrow("IMAGE_B3A_BG5");
		SOUND_BOOK3_CH5_SOUND1 = aMgr.GetSoundThrow("SOUND_BOOK3_CH5_SOUND1");
		SOUND_BOOK3_CH5_SOUND10 = aMgr.GetSoundThrow("SOUND_BOOK3_CH5_SOUND10");
		SOUND_BOOK3_CH5_SOUND11 = aMgr.GetSoundThrow("SOUND_BOOK3_CH5_SOUND11");
		SOUND_BOOK3_CH5_SOUND12 = aMgr.GetSoundThrow("SOUND_BOOK3_CH5_SOUND12");
		SOUND_BOOK3_CH5_SOUND2 = aMgr.GetSoundThrow("SOUND_BOOK3_CH5_SOUND2");
		SOUND_BOOK3_CH5_SOUND3 = aMgr.GetSoundThrow("SOUND_BOOK3_CH5_SOUND3");
		SOUND_BOOK3_CH5_SOUND4 = aMgr.GetSoundThrow("SOUND_BOOK3_CH5_SOUND4");
		SOUND_BOOK3_CH5_SOUND5 = aMgr.GetSoundThrow("SOUND_BOOK3_CH5_SOUND5");
		SOUND_BOOK3_CH5_SOUND6 = aMgr.GetSoundThrow("SOUND_BOOK3_CH5_SOUND6");
		SOUND_BOOK3_CH5_SOUND7 = aMgr.GetSoundThrow("SOUND_BOOK3_CH5_SOUND7");
		SOUND_BOOK3_CH5_SOUND8 = aMgr.GetSoundThrow("SOUND_BOOK3_CH5_SOUND8");
		SOUND_BOOK3_CH5_SOUND9 = aMgr.GetSoundThrow("SOUND_BOOK3_CH5_SOUND9");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// Book3Chapter6 Resources
Image* Sexy::IMAGE_B3A_BG6;
int Sexy::SOUND_BOOK3_CH6_SOUND1;
int Sexy::SOUND_BOOK3_CH6_SOUND10;
int Sexy::SOUND_BOOK3_CH6_SOUND11;
int Sexy::SOUND_BOOK3_CH6_SOUND12;
int Sexy::SOUND_BOOK3_CH6_SOUND2;
int Sexy::SOUND_BOOK3_CH6_SOUND3;
int Sexy::SOUND_BOOK3_CH6_SOUND4;
int Sexy::SOUND_BOOK3_CH6_SOUND5;
int Sexy::SOUND_BOOK3_CH6_SOUND6;
int Sexy::SOUND_BOOK3_CH6_SOUND7;
int Sexy::SOUND_BOOK3_CH6_SOUND8;
int Sexy::SOUND_BOOK3_CH6_SOUND9;

bool Sexy::ExtractBook3Chapter6Resources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_B3A_BG6 = aMgr.GetImageThrow("IMAGE_B3A_BG6");
		SOUND_BOOK3_CH6_SOUND1 = aMgr.GetSoundThrow("SOUND_BOOK3_CH6_SOUND1");
		SOUND_BOOK3_CH6_SOUND10 = aMgr.GetSoundThrow("SOUND_BOOK3_CH6_SOUND10");
		SOUND_BOOK3_CH6_SOUND11 = aMgr.GetSoundThrow("SOUND_BOOK3_CH6_SOUND11");
		SOUND_BOOK3_CH6_SOUND12 = aMgr.GetSoundThrow("SOUND_BOOK3_CH6_SOUND12");
		SOUND_BOOK3_CH6_SOUND2 = aMgr.GetSoundThrow("SOUND_BOOK3_CH6_SOUND2");
		SOUND_BOOK3_CH6_SOUND3 = aMgr.GetSoundThrow("SOUND_BOOK3_CH6_SOUND3");
		SOUND_BOOK3_CH6_SOUND4 = aMgr.GetSoundThrow("SOUND_BOOK3_CH6_SOUND4");
		SOUND_BOOK3_CH6_SOUND5 = aMgr.GetSoundThrow("SOUND_BOOK3_CH6_SOUND5");
		SOUND_BOOK3_CH6_SOUND6 = aMgr.GetSoundThrow("SOUND_BOOK3_CH6_SOUND6");
		SOUND_BOOK3_CH6_SOUND7 = aMgr.GetSoundThrow("SOUND_BOOK3_CH6_SOUND7");
		SOUND_BOOK3_CH6_SOUND8 = aMgr.GetSoundThrow("SOUND_BOOK3_CH6_SOUND8");
		SOUND_BOOK3_CH6_SOUND9 = aMgr.GetSoundThrow("SOUND_BOOK3_CH6_SOUND9");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// Book3Chapter7 Resources
Image* Sexy::IMAGE_B3A_BG7;
Image* Sexy::IMAGE_B3A_HYDRA_BOSS_BATTLE;
int Sexy::SOUND_BOOK3_CH7_SOUND1;
int Sexy::SOUND_BOOK3_CH7_SOUND2;
int Sexy::SOUND_BOOK3_CH7_SOUND3;
int Sexy::SOUND_BOOK3_CH7_SOUND4;
int Sexy::SOUND_BOOK3_CH7_SOUND5;
int Sexy::SOUND_BOOK3_CH7_SOUND6;
int Sexy::SOUND_BOOK3_CH7_SOUND7;
int Sexy::SOUND_BOOK3_CH7_SOUND8;
int Sexy::SOUND_BOOK3_CH7_SOUND9;

bool Sexy::ExtractBook3Chapter7Resources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_B3A_BG7 = aMgr.GetImageThrow("IMAGE_B3A_BG7");
		IMAGE_B3A_HYDRA_BOSS_BATTLE = aMgr.GetImageThrow("IMAGE_B3A_HYDRA_BOSS_BATTLE");
		SOUND_BOOK3_CH7_SOUND1 = aMgr.GetSoundThrow("SOUND_BOOK3_CH7_SOUND1");
		SOUND_BOOK3_CH7_SOUND2 = aMgr.GetSoundThrow("SOUND_BOOK3_CH7_SOUND2");
		SOUND_BOOK3_CH7_SOUND3 = aMgr.GetSoundThrow("SOUND_BOOK3_CH7_SOUND3");
		SOUND_BOOK3_CH7_SOUND4 = aMgr.GetSoundThrow("SOUND_BOOK3_CH7_SOUND4");
		SOUND_BOOK3_CH7_SOUND5 = aMgr.GetSoundThrow("SOUND_BOOK3_CH7_SOUND5");
		SOUND_BOOK3_CH7_SOUND6 = aMgr.GetSoundThrow("SOUND_BOOK3_CH7_SOUND6");
		SOUND_BOOK3_CH7_SOUND7 = aMgr.GetSoundThrow("SOUND_BOOK3_CH7_SOUND7");
		SOUND_BOOK3_CH7_SOUND8 = aMgr.GetSoundThrow("SOUND_BOOK3_CH7_SOUND8");
		SOUND_BOOK3_CH7_SOUND9 = aMgr.GetSoundThrow("SOUND_BOOK3_CH7_SOUND9");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// Book3Chapter8 Resources
Image* Sexy::IMAGE_B3A_BG8;
int Sexy::SOUND_BOOK3_CH8_SOUND1;
int Sexy::SOUND_BOOK3_CH8_SOUND2;
int Sexy::SOUND_BOOK3_CH8_SOUND3;
int Sexy::SOUND_BOOK3_CH8_SOUND4;
int Sexy::SOUND_BOOK3_CH8_SOUND5;
int Sexy::SOUND_BOOK3_CH8_SOUND6;
int Sexy::SOUND_BOOK3_CH8_SOUND7;

bool Sexy::ExtractBook3Chapter8Resources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_B3A_BG8 = aMgr.GetImageThrow("IMAGE_B3A_BG8");
		SOUND_BOOK3_CH8_SOUND1 = aMgr.GetSoundThrow("SOUND_BOOK3_CH8_SOUND1");
		SOUND_BOOK3_CH8_SOUND2 = aMgr.GetSoundThrow("SOUND_BOOK3_CH8_SOUND2");
		SOUND_BOOK3_CH8_SOUND3 = aMgr.GetSoundThrow("SOUND_BOOK3_CH8_SOUND3");
		SOUND_BOOK3_CH8_SOUND4 = aMgr.GetSoundThrow("SOUND_BOOK3_CH8_SOUND4");
		SOUND_BOOK3_CH8_SOUND5 = aMgr.GetSoundThrow("SOUND_BOOK3_CH8_SOUND5");
		SOUND_BOOK3_CH8_SOUND6 = aMgr.GetSoundThrow("SOUND_BOOK3_CH8_SOUND6");
		SOUND_BOOK3_CH8_SOUND7 = aMgr.GetSoundThrow("SOUND_BOOK3_CH8_SOUND7");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// Book3Chapter9 Resources
Image* Sexy::IMAGE_B3A_BG9;
int Sexy::SOUND_BOOK3_CH9_SOUND1;
int Sexy::SOUND_BOOK3_CH9_SOUND10;
int Sexy::SOUND_BOOK3_CH9_SOUND12;
int Sexy::SOUND_BOOK3_CH9_SOUND13;
int Sexy::SOUND_BOOK3_CH9_SOUND2;
int Sexy::SOUND_BOOK3_CH9_SOUND3;
int Sexy::SOUND_BOOK3_CH9_SOUND4;
int Sexy::SOUND_BOOK3_CH9_SOUND5;
int Sexy::SOUND_BOOK3_CH9_SOUND6;
int Sexy::SOUND_BOOK3_CH9_SOUND7;
int Sexy::SOUND_BOOK3_CH9_SOUND8;
int Sexy::SOUND_BOOK3_CH9_SOUND9;

bool Sexy::ExtractBook3Chapter9Resources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_B3A_BG9 = aMgr.GetImageThrow("IMAGE_B3A_BG9");
		SOUND_BOOK3_CH9_SOUND1 = aMgr.GetSoundThrow("SOUND_BOOK3_CH9_SOUND1");
		SOUND_BOOK3_CH9_SOUND10 = aMgr.GetSoundThrow("SOUND_BOOK3_CH9_SOUND10");
		SOUND_BOOK3_CH9_SOUND12 = aMgr.GetSoundThrow("SOUND_BOOK3_CH9_SOUND12");
		SOUND_BOOK3_CH9_SOUND13 = aMgr.GetSoundThrow("SOUND_BOOK3_CH9_SOUND13");
		SOUND_BOOK3_CH9_SOUND2 = aMgr.GetSoundThrow("SOUND_BOOK3_CH9_SOUND2");
		SOUND_BOOK3_CH9_SOUND3 = aMgr.GetSoundThrow("SOUND_BOOK3_CH9_SOUND3");
		SOUND_BOOK3_CH9_SOUND4 = aMgr.GetSoundThrow("SOUND_BOOK3_CH9_SOUND4");
		SOUND_BOOK3_CH9_SOUND5 = aMgr.GetSoundThrow("SOUND_BOOK3_CH9_SOUND5");
		SOUND_BOOK3_CH9_SOUND6 = aMgr.GetSoundThrow("SOUND_BOOK3_CH9_SOUND6");
		SOUND_BOOK3_CH9_SOUND7 = aMgr.GetSoundThrow("SOUND_BOOK3_CH9_SOUND7");
		SOUND_BOOK3_CH9_SOUND8 = aMgr.GetSoundThrow("SOUND_BOOK3_CH9_SOUND8");
		SOUND_BOOK3_CH9_SOUND9 = aMgr.GetSoundThrow("SOUND_BOOK3_CH9_SOUND9");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// Book3Common Resources
Image* Sexy::IMAGE_B3_LEFT_FACING_ARROW;

bool Sexy::ExtractBook3CommonResources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_B3_LEFT_FACING_ARROW = aMgr.GetImageThrow("IMAGE_B3_LEFT_FACING_ARROW");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// Book3Init Resources
Image* Sexy::IMAGE_B3_ICONANIM1;
Image* Sexy::IMAGE_B3_ICONANIM10;
Image* Sexy::IMAGE_B3_ICONANIM2;
Image* Sexy::IMAGE_B3_ICONANIM3;
Image* Sexy::IMAGE_B3_ICONANIM4;
Image* Sexy::IMAGE_B3_ICONANIM5;
Image* Sexy::IMAGE_B3_ICONANIM6;
Image* Sexy::IMAGE_B3_ICONANIM7;
Image* Sexy::IMAGE_B3_ICONANIM8;
Image* Sexy::IMAGE_B3_ICONANIM9;
Image* Sexy::IMAGE_B3_ICONMASK1;
Image* Sexy::IMAGE_B3_ICONMASK10;
Image* Sexy::IMAGE_B3_ICONMASK2;
Image* Sexy::IMAGE_B3_ICONMASK3;
Image* Sexy::IMAGE_B3_ICONMASK4;
Image* Sexy::IMAGE_B3_ICONMASK5;
Image* Sexy::IMAGE_B3_ICONMASK6;
Image* Sexy::IMAGE_B3_ICONMASK7;
Image* Sexy::IMAGE_B3_ICONMASK8;
Image* Sexy::IMAGE_B3_ICONMASK9;
Image* Sexy::IMAGE_B3_MAP;
Image* Sexy::IMAGE_B3_MAPSCREEN_BANNER;
Image* Sexy::IMAGE_B3_MINIMAP_ICONS;
Image* Sexy::IMAGE_TUT_PIC_CODEX_EVIL;
Image* Sexy::IMAGE_TUT_PIC_CODEX_EVIL_PEN;
Image* Sexy::IMAGE_TUT_PIC_DRACULA;
Image* Sexy::IMAGE_TUT_PIC_FHUNT;
Image* Sexy::IMAGE_TUT_PIC_FRANKMD;
Image* Sexy::IMAGE_TUT_PIC_FSWASH;
Image* Sexy::IMAGE_TUT_PIC_FWARRIOR;
Image* Sexy::IMAGE_TUT_PIC_FWIZARD;
Image* Sexy::IMAGE_TUT_PIC_GRIM;
Image* Sexy::IMAGE_TUT_PIC_MAGISTRATE;
Image* Sexy::IMAGE_TUT_PIC_THE_CREATURE;
Image* Sexy::IMAGE_TUT_PIC_WOLFMAN;

bool Sexy::ExtractBook3InitResources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_B3_ICONANIM1 = aMgr.GetImageThrow("IMAGE_B3_ICONANIM1");
		IMAGE_B3_ICONANIM10 = aMgr.GetImageThrow("IMAGE_B3_ICONANIM10");
		IMAGE_B3_ICONANIM2 = aMgr.GetImageThrow("IMAGE_B3_ICONANIM2");
		IMAGE_B3_ICONANIM3 = aMgr.GetImageThrow("IMAGE_B3_ICONANIM3");
		IMAGE_B3_ICONANIM4 = aMgr.GetImageThrow("IMAGE_B3_ICONANIM4");
		IMAGE_B3_ICONANIM5 = aMgr.GetImageThrow("IMAGE_B3_ICONANIM5");
		IMAGE_B3_ICONANIM6 = aMgr.GetImageThrow("IMAGE_B3_ICONANIM6");
		IMAGE_B3_ICONANIM7 = aMgr.GetImageThrow("IMAGE_B3_ICONANIM7");
		IMAGE_B3_ICONANIM8 = aMgr.GetImageThrow("IMAGE_B3_ICONANIM8");
		IMAGE_B3_ICONANIM9 = aMgr.GetImageThrow("IMAGE_B3_ICONANIM9");
		IMAGE_B3_ICONMASK1 = aMgr.GetImageThrow("IMAGE_B3_ICONMASK1");
		IMAGE_B3_ICONMASK10 = aMgr.GetImageThrow("IMAGE_B3_ICONMASK10");
		IMAGE_B3_ICONMASK2 = aMgr.GetImageThrow("IMAGE_B3_ICONMASK2");
		IMAGE_B3_ICONMASK3 = aMgr.GetImageThrow("IMAGE_B3_ICONMASK3");
		IMAGE_B3_ICONMASK4 = aMgr.GetImageThrow("IMAGE_B3_ICONMASK4");
		IMAGE_B3_ICONMASK5 = aMgr.GetImageThrow("IMAGE_B3_ICONMASK5");
		IMAGE_B3_ICONMASK6 = aMgr.GetImageThrow("IMAGE_B3_ICONMASK6");
		IMAGE_B3_ICONMASK7 = aMgr.GetImageThrow("IMAGE_B3_ICONMASK7");
		IMAGE_B3_ICONMASK8 = aMgr.GetImageThrow("IMAGE_B3_ICONMASK8");
		IMAGE_B3_ICONMASK9 = aMgr.GetImageThrow("IMAGE_B3_ICONMASK9");
		IMAGE_B3_MAP = aMgr.GetImageThrow("IMAGE_B3_MAP");
		IMAGE_B3_MAPSCREEN_BANNER = aMgr.GetImageThrow("IMAGE_B3_MAPSCREEN_BANNER");
		IMAGE_B3_MINIMAP_ICONS = aMgr.GetImageThrow("IMAGE_B3_MINIMAP_ICONS");
		IMAGE_TUT_PIC_CODEX_EVIL = aMgr.GetImageThrow("IMAGE_TUT_PIC_CODEX_EVIL");
		IMAGE_TUT_PIC_CODEX_EVIL_PEN = aMgr.GetImageThrow("IMAGE_TUT_PIC_CODEX_EVIL_PEN");
		IMAGE_TUT_PIC_DRACULA = aMgr.GetImageThrow("IMAGE_TUT_PIC_DRACULA");
		IMAGE_TUT_PIC_FHUNT = aMgr.GetImageThrow("IMAGE_TUT_PIC_FHUNT");
		IMAGE_TUT_PIC_FRANKMD = aMgr.GetImageThrow("IMAGE_TUT_PIC_FRANKMD");
		IMAGE_TUT_PIC_FSWASH = aMgr.GetImageThrow("IMAGE_TUT_PIC_FSWASH");
		IMAGE_TUT_PIC_FWARRIOR = aMgr.GetImageThrow("IMAGE_TUT_PIC_FWARRIOR");
		IMAGE_TUT_PIC_FWIZARD = aMgr.GetImageThrow("IMAGE_TUT_PIC_FWIZARD");
		IMAGE_TUT_PIC_GRIM = aMgr.GetImageThrow("IMAGE_TUT_PIC_GRIM");
		IMAGE_TUT_PIC_MAGISTRATE = aMgr.GetImageThrow("IMAGE_TUT_PIC_MAGISTRATE");
		IMAGE_TUT_PIC_THE_CREATURE = aMgr.GetImageThrow("IMAGE_TUT_PIC_THE_CREATURE");
		IMAGE_TUT_PIC_WOLFMAN = aMgr.GetImageThrow("IMAGE_TUT_PIC_WOLFMAN");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

static void* gResources[] =
{
	&IMAGE_B3_MINIMAP_ICONS,
	&IMAGE_B3_MAPSCREEN_BANNER,
	&IMAGE_B3_ICONANIM1,
	&IMAGE_B3_ICONANIM2,
	&IMAGE_B3_ICONANIM3,
	&IMAGE_B3_ICONANIM4,
	&IMAGE_B3_ICONANIM5,
	&IMAGE_B3_ICONANIM6,
	&IMAGE_B3_ICONANIM7,
	&IMAGE_B3_ICONANIM8,
	&IMAGE_B3_ICONANIM9,
	&IMAGE_B3_ICONANIM10,
	&IMAGE_B3_ICONMASK1,
	&IMAGE_B3_ICONMASK2,
	&IMAGE_B3_ICONMASK3,
	&IMAGE_B3_ICONMASK4,
	&IMAGE_B3_ICONMASK5,
	&IMAGE_B3_ICONMASK6,
	&IMAGE_B3_ICONMASK7,
	&IMAGE_B3_ICONMASK8,
	&IMAGE_B3_ICONMASK9,
	&IMAGE_B3_ICONMASK10,
	&IMAGE_B3_MAP,
	&IMAGE_TUT_PIC_MAGISTRATE,
	&IMAGE_TUT_PIC_FRANKMD,
	&IMAGE_TUT_PIC_WOLFMAN,
	&IMAGE_TUT_PIC_THE_CREATURE,
	&IMAGE_TUT_PIC_GRIM,
	&IMAGE_TUT_PIC_FWARRIOR,
	&IMAGE_TUT_PIC_FSWASH,
	&IMAGE_TUT_PIC_FHUNT,
	&IMAGE_TUT_PIC_FWIZARD,
	&IMAGE_TUT_PIC_DRACULA,
	&IMAGE_TUT_PIC_CODEX_EVIL,
	&IMAGE_TUT_PIC_CODEX_EVIL_PEN,
	&IMAGE_B3_LEFT_FACING_ARROW,
	&IMAGE_B3A_BG1,
	&SOUND_BOOK3_CH1_SOUND1,
	&SOUND_BOOK3_CH1_SOUND2,
	&SOUND_BOOK3_CH1_SOUND3,
	&SOUND_BOOK3_CH1_SOUND4,
	&SOUND_BOOK3_CH1_SOUND5,
	&SOUND_BOOK3_CH1_SOUND6,
	&SOUND_BOOK3_CH1_SOUND7,
	&SOUND_BOOK3_CH1_SOUND8,
	&SOUND_BOOK3_CH1_SOUND9,
	&SOUND_BOOK3_CH1_SOUND10,
	&IMAGE_B3A_BG2,
	&SOUND_BOOK3_CH2_SOUND1,
	&SOUND_BOOK3_CH2_SOUND2,
	&SOUND_BOOK3_CH2_SOUND3,
	&SOUND_BOOK3_CH2_SOUND4,
	&SOUND_BOOK3_CH2_SOUND5,
	&SOUND_BOOK3_CH2_SOUND6,
	&SOUND_BOOK3_CH2_SOUND7,
	&SOUND_BOOK3_CH2_SOUND8,
	&SOUND_BOOK3_CH2_SOUND9,
	&SOUND_BOOK3_CH2_SOUND10,
	&SOUND_BOOK3_CH2_SOUND11,
	&SOUND_BOOK3_CH2_SOUND12,
	&SOUND_BOOK3_CH2_SOUND13,
	&SOUND_BOOK3_CH2_SOUND14,
	&SOUND_BOOK3_CH2_SOUND15,
	&IMAGE_B3A_BG3,
	&SOUND_BOOK3_CH3_SOUND1,
	&SOUND_BOOK3_CH3_SOUND2,
	&SOUND_BOOK3_CH3_SOUND3,
	&SOUND_BOOK3_CH3_SOUND4,
	&SOUND_BOOK3_CH3_SOUND5,
	&SOUND_BOOK3_CH3_SOUND6,
	&SOUND_BOOK3_CH3_SOUND7,
	&SOUND_BOOK3_CH3_SOUND8,
	&SOUND_BOOK3_CH3_SOUND9,
	&SOUND_BOOK3_CH3_SOUND10,
	&SOUND_BOOK3_CH3_SOUND11,
	&IMAGE_B3A_BG4,
	&SOUND_BOOK3_CH4_SOUND1,
	&SOUND_BOOK3_CH4_SOUND2,
	&SOUND_BOOK3_CH4_SOUND3,
	&SOUND_BOOK3_CH4_SOUND4,
	&SOUND_BOOK3_CH4_SOUND5,
	&SOUND_BOOK3_CH4_SOUND6,
	&SOUND_BOOK3_CH4_SOUND7,
	&SOUND_BOOK3_CH4_SOUND8,
	&SOUND_BOOK3_CH4_SOUND9,
	&SOUND_BOOK3_CH4_SOUND10,
	&SOUND_BOOK3_CH4_SOUND11,
	&IMAGE_B3A_BG5,
	&SOUND_BOOK3_CH5_SOUND1,
	&SOUND_BOOK3_CH5_SOUND2,
	&SOUND_BOOK3_CH5_SOUND3,
	&SOUND_BOOK3_CH5_SOUND4,
	&SOUND_BOOK3_CH5_SOUND5,
	&SOUND_BOOK3_CH5_SOUND6,
	&SOUND_BOOK3_CH5_SOUND7,
	&SOUND_BOOK3_CH5_SOUND8,
	&SOUND_BOOK3_CH5_SOUND9,
	&SOUND_BOOK3_CH5_SOUND10,
	&SOUND_BOOK3_CH5_SOUND11,
	&SOUND_BOOK3_CH5_SOUND12,
	&IMAGE_B3A_BG6,
	&SOUND_BOOK3_CH6_SOUND1,
	&SOUND_BOOK3_CH6_SOUND2,
	&SOUND_BOOK3_CH6_SOUND3,
	&SOUND_BOOK3_CH6_SOUND4,
	&SOUND_BOOK3_CH6_SOUND5,
	&SOUND_BOOK3_CH6_SOUND6,
	&SOUND_BOOK3_CH6_SOUND7,
	&SOUND_BOOK3_CH6_SOUND8,
	&SOUND_BOOK3_CH6_SOUND9,
	&SOUND_BOOK3_CH6_SOUND10,
	&SOUND_BOOK3_CH6_SOUND11,
	&SOUND_BOOK3_CH6_SOUND12,
	&IMAGE_B3A_BG7,
	&IMAGE_B3A_HYDRA_BOSS_BATTLE,
	&SOUND_BOOK3_CH7_SOUND1,
	&SOUND_BOOK3_CH7_SOUND2,
	&SOUND_BOOK3_CH7_SOUND3,
	&SOUND_BOOK3_CH7_SOUND4,
	&SOUND_BOOK3_CH7_SOUND5,
	&SOUND_BOOK3_CH7_SOUND6,
	&SOUND_BOOK3_CH7_SOUND7,
	&SOUND_BOOK3_CH7_SOUND8,
	&SOUND_BOOK3_CH7_SOUND9,
	&IMAGE_B3A_BG8,
	&SOUND_BOOK3_CH8_SOUND1,
	&SOUND_BOOK3_CH8_SOUND2,
	&SOUND_BOOK3_CH8_SOUND3,
	&SOUND_BOOK3_CH8_SOUND4,
	&SOUND_BOOK3_CH8_SOUND5,
	&SOUND_BOOK3_CH8_SOUND6,
	&SOUND_BOOK3_CH8_SOUND7,
	&IMAGE_B3A_BG9,
	&SOUND_BOOK3_CH9_SOUND1,
	&SOUND_BOOK3_CH9_SOUND2,
	&SOUND_BOOK3_CH9_SOUND3,
	&SOUND_BOOK3_CH9_SOUND4,
	&SOUND_BOOK3_CH9_SOUND5,
	&SOUND_BOOK3_CH9_SOUND6,
	&SOUND_BOOK3_CH9_SOUND7,
	&SOUND_BOOK3_CH9_SOUND8,
	&SOUND_BOOK3_CH9_SOUND9,
	&SOUND_BOOK3_CH9_SOUND10,
	&SOUND_BOOK3_CH9_SOUND12,
	&SOUND_BOOK3_CH9_SOUND13,
	&IMAGE_B3A_BG10,
	&IMAGE_B3A_CODEX_BOSS_BATTLE,
	&SOUND_BOOK3_CH10_SOUND1,
	&SOUND_BOOK3_CH10_SOUND2,
	&SOUND_BOOK3_CH10_SOUND3,
	&SOUND_BOOK3_CH10_SOUND4,
	&SOUND_BOOK3_CH10_SOUND5,
	&SOUND_BOOK3_CH10_SOUND7,
	&SOUND_BOOK3_CH10_CODEXSUMMON,
	&SOUND_BOOK3_CH10_CODEXLAUGH,
	&SOUND_BOOK3_CH10_CODEXFLINCH,
	&SOUND_BOOK3_CH10_CODEXNYAH,
	&SOUND_BOOK3_CH10_LEXBEAM,
	&SOUND_BOOK3_CH10_AUTOLOGICAL,
	NULL
};

Image* Sexy::LoadImageById(ResourceManager *theManager, int theId)
{
	return (*((Image**)gResources[theId]) = theManager->LoadImage(GetStringIdById(theId)));
}

void Sexy::ReplaceImageById(ResourceManager *theManager, int theId, Image *theImage)
{
	theManager->ReplaceImage(GetStringIdById(theId),theImage);
	*(Image**)gResources[theId] = theImage;
}

Image* Sexy::GetImageById(int theId)
{
	return *(Image**)gResources[theId];
}

Font* Sexy::GetFontById(int theId)
{
	return *(Font**)gResources[theId];
}

int Sexy::GetSoundById(int theId)
{
	return *(int*)gResources[theId];
}

Image*& Sexy::GetImageRefById(int theId)
{
	return *(Image**)gResources[theId];
}

Font*& Sexy::GetFontRefById(int theId)
{
	return *(Font**)gResources[theId];
}

int& Sexy::GetSoundRefById(int theId)
{
	return *(int*)gResources[theId];
}

static Sexy::ResourceId GetIdByVariable(const void *theVariable)
{
	typedef std::map<int,int> MyMap;
	static MyMap aMap;
	if(gNeedRecalcVariableToIdMap)
	{
		gNeedRecalcVariableToIdMap = false;
		aMap.clear();
		for(int i=0; i<RESOURCE_ID_MAX; i++)
			aMap[*(int*)gResources[i]] = i;
	}

	MyMap::iterator anItr = aMap.find((int)theVariable);
	if (anItr == aMap.end())
		return RESOURCE_ID_MAX;
	else
		return (ResourceId) anItr->second;
}

Sexy::ResourceId Sexy::GetIdByImage(Image *theImage)
{
	return GetIdByVariable(theImage);
}

Sexy::ResourceId Sexy::GetIdByFont(Font *theFont)
{
	return GetIdByVariable(theFont);
}

Sexy::ResourceId Sexy::GetIdBySound(int theSound)
{
	return GetIdByVariable((void*)theSound);
}

const char* Sexy::GetStringIdById(int theId)
{
	switch(theId)
	{
		case IMAGE_B3_MINIMAP_ICONS_ID: return "IMAGE_B3_MINIMAP_ICONS";
		case IMAGE_B3_MAPSCREEN_BANNER_ID: return "IMAGE_B3_MAPSCREEN_BANNER";
		case IMAGE_B3_ICONANIM1_ID: return "IMAGE_B3_ICONANIM1";
		case IMAGE_B3_ICONANIM2_ID: return "IMAGE_B3_ICONANIM2";
		case IMAGE_B3_ICONANIM3_ID: return "IMAGE_B3_ICONANIM3";
		case IMAGE_B3_ICONANIM4_ID: return "IMAGE_B3_ICONANIM4";
		case IMAGE_B3_ICONANIM5_ID: return "IMAGE_B3_ICONANIM5";
		case IMAGE_B3_ICONANIM6_ID: return "IMAGE_B3_ICONANIM6";
		case IMAGE_B3_ICONANIM7_ID: return "IMAGE_B3_ICONANIM7";
		case IMAGE_B3_ICONANIM8_ID: return "IMAGE_B3_ICONANIM8";
		case IMAGE_B3_ICONANIM9_ID: return "IMAGE_B3_ICONANIM9";
		case IMAGE_B3_ICONANIM10_ID: return "IMAGE_B3_ICONANIM10";
		case IMAGE_B3_ICONMASK1_ID: return "IMAGE_B3_ICONMASK1";
		case IMAGE_B3_ICONMASK2_ID: return "IMAGE_B3_ICONMASK2";
		case IMAGE_B3_ICONMASK3_ID: return "IMAGE_B3_ICONMASK3";
		case IMAGE_B3_ICONMASK4_ID: return "IMAGE_B3_ICONMASK4";
		case IMAGE_B3_ICONMASK5_ID: return "IMAGE_B3_ICONMASK5";
		case IMAGE_B3_ICONMASK6_ID: return "IMAGE_B3_ICONMASK6";
		case IMAGE_B3_ICONMASK7_ID: return "IMAGE_B3_ICONMASK7";
		case IMAGE_B3_ICONMASK8_ID: return "IMAGE_B3_ICONMASK8";
		case IMAGE_B3_ICONMASK9_ID: return "IMAGE_B3_ICONMASK9";
		case IMAGE_B3_ICONMASK10_ID: return "IMAGE_B3_ICONMASK10";
		case IMAGE_B3_MAP_ID: return "IMAGE_B3_MAP";
		case IMAGE_TUT_PIC_MAGISTRATE_ID: return "IMAGE_TUT_PIC_MAGISTRATE";
		case IMAGE_TUT_PIC_FRANKMD_ID: return "IMAGE_TUT_PIC_FRANKMD";
		case IMAGE_TUT_PIC_WOLFMAN_ID: return "IMAGE_TUT_PIC_WOLFMAN";
		case IMAGE_TUT_PIC_THE_CREATURE_ID: return "IMAGE_TUT_PIC_THE_CREATURE";
		case IMAGE_TUT_PIC_GRIM_ID: return "IMAGE_TUT_PIC_GRIM";
		case IMAGE_TUT_PIC_FWARRIOR_ID: return "IMAGE_TUT_PIC_FWARRIOR";
		case IMAGE_TUT_PIC_FSWASH_ID: return "IMAGE_TUT_PIC_FSWASH";
		case IMAGE_TUT_PIC_FHUNT_ID: return "IMAGE_TUT_PIC_FHUNT";
		case IMAGE_TUT_PIC_FWIZARD_ID: return "IMAGE_TUT_PIC_FWIZARD";
		case IMAGE_TUT_PIC_DRACULA_ID: return "IMAGE_TUT_PIC_DRACULA";
		case IMAGE_TUT_PIC_CODEX_EVIL_ID: return "IMAGE_TUT_PIC_CODEX_EVIL";
		case IMAGE_TUT_PIC_CODEX_EVIL_PEN_ID: return "IMAGE_TUT_PIC_CODEX_EVIL_PEN";
		case IMAGE_B3_LEFT_FACING_ARROW_ID: return "IMAGE_B3_LEFT_FACING_ARROW";
		case IMAGE_B3A_BG1_ID: return "IMAGE_B3A_BG1";
		case SOUND_BOOK3_CH1_SOUND1_ID: return "SOUND_BOOK3_CH1_SOUND1";
		case SOUND_BOOK3_CH1_SOUND2_ID: return "SOUND_BOOK3_CH1_SOUND2";
		case SOUND_BOOK3_CH1_SOUND3_ID: return "SOUND_BOOK3_CH1_SOUND3";
		case SOUND_BOOK3_CH1_SOUND4_ID: return "SOUND_BOOK3_CH1_SOUND4";
		case SOUND_BOOK3_CH1_SOUND5_ID: return "SOUND_BOOK3_CH1_SOUND5";
		case SOUND_BOOK3_CH1_SOUND6_ID: return "SOUND_BOOK3_CH1_SOUND6";
		case SOUND_BOOK3_CH1_SOUND7_ID: return "SOUND_BOOK3_CH1_SOUND7";
		case SOUND_BOOK3_CH1_SOUND8_ID: return "SOUND_BOOK3_CH1_SOUND8";
		case SOUND_BOOK3_CH1_SOUND9_ID: return "SOUND_BOOK3_CH1_SOUND9";
		case SOUND_BOOK3_CH1_SOUND10_ID: return "SOUND_BOOK3_CH1_SOUND10";
		case IMAGE_B3A_BG2_ID: return "IMAGE_B3A_BG2";
		case SOUND_BOOK3_CH2_SOUND1_ID: return "SOUND_BOOK3_CH2_SOUND1";
		case SOUND_BOOK3_CH2_SOUND2_ID: return "SOUND_BOOK3_CH2_SOUND2";
		case SOUND_BOOK3_CH2_SOUND3_ID: return "SOUND_BOOK3_CH2_SOUND3";
		case SOUND_BOOK3_CH2_SOUND4_ID: return "SOUND_BOOK3_CH2_SOUND4";
		case SOUND_BOOK3_CH2_SOUND5_ID: return "SOUND_BOOK3_CH2_SOUND5";
		case SOUND_BOOK3_CH2_SOUND6_ID: return "SOUND_BOOK3_CH2_SOUND6";
		case SOUND_BOOK3_CH2_SOUND7_ID: return "SOUND_BOOK3_CH2_SOUND7";
		case SOUND_BOOK3_CH2_SOUND8_ID: return "SOUND_BOOK3_CH2_SOUND8";
		case SOUND_BOOK3_CH2_SOUND9_ID: return "SOUND_BOOK3_CH2_SOUND9";
		case SOUND_BOOK3_CH2_SOUND10_ID: return "SOUND_BOOK3_CH2_SOUND10";
		case SOUND_BOOK3_CH2_SOUND11_ID: return "SOUND_BOOK3_CH2_SOUND11";
		case SOUND_BOOK3_CH2_SOUND12_ID: return "SOUND_BOOK3_CH2_SOUND12";
		case SOUND_BOOK3_CH2_SOUND13_ID: return "SOUND_BOOK3_CH2_SOUND13";
		case SOUND_BOOK3_CH2_SOUND14_ID: return "SOUND_BOOK3_CH2_SOUND14";
		case SOUND_BOOK3_CH2_SOUND15_ID: return "SOUND_BOOK3_CH2_SOUND15";
		case IMAGE_B3A_BG3_ID: return "IMAGE_B3A_BG3";
		case SOUND_BOOK3_CH3_SOUND1_ID: return "SOUND_BOOK3_CH3_SOUND1";
		case SOUND_BOOK3_CH3_SOUND2_ID: return "SOUND_BOOK3_CH3_SOUND2";
		case SOUND_BOOK3_CH3_SOUND3_ID: return "SOUND_BOOK3_CH3_SOUND3";
		case SOUND_BOOK3_CH3_SOUND4_ID: return "SOUND_BOOK3_CH3_SOUND4";
		case SOUND_BOOK3_CH3_SOUND5_ID: return "SOUND_BOOK3_CH3_SOUND5";
		case SOUND_BOOK3_CH3_SOUND6_ID: return "SOUND_BOOK3_CH3_SOUND6";
		case SOUND_BOOK3_CH3_SOUND7_ID: return "SOUND_BOOK3_CH3_SOUND7";
		case SOUND_BOOK3_CH3_SOUND8_ID: return "SOUND_BOOK3_CH3_SOUND8";
		case SOUND_BOOK3_CH3_SOUND9_ID: return "SOUND_BOOK3_CH3_SOUND9";
		case SOUND_BOOK3_CH3_SOUND10_ID: return "SOUND_BOOK3_CH3_SOUND10";
		case SOUND_BOOK3_CH3_SOUND11_ID: return "SOUND_BOOK3_CH3_SOUND11";
		case IMAGE_B3A_BG4_ID: return "IMAGE_B3A_BG4";
		case SOUND_BOOK3_CH4_SOUND1_ID: return "SOUND_BOOK3_CH4_SOUND1";
		case SOUND_BOOK3_CH4_SOUND2_ID: return "SOUND_BOOK3_CH4_SOUND2";
		case SOUND_BOOK3_CH4_SOUND3_ID: return "SOUND_BOOK3_CH4_SOUND3";
		case SOUND_BOOK3_CH4_SOUND4_ID: return "SOUND_BOOK3_CH4_SOUND4";
		case SOUND_BOOK3_CH4_SOUND5_ID: return "SOUND_BOOK3_CH4_SOUND5";
		case SOUND_BOOK3_CH4_SOUND6_ID: return "SOUND_BOOK3_CH4_SOUND6";
		case SOUND_BOOK3_CH4_SOUND7_ID: return "SOUND_BOOK3_CH4_SOUND7";
		case SOUND_BOOK3_CH4_SOUND8_ID: return "SOUND_BOOK3_CH4_SOUND8";
		case SOUND_BOOK3_CH4_SOUND9_ID: return "SOUND_BOOK3_CH4_SOUND9";
		case SOUND_BOOK3_CH4_SOUND10_ID: return "SOUND_BOOK3_CH4_SOUND10";
		case SOUND_BOOK3_CH4_SOUND11_ID: return "SOUND_BOOK3_CH4_SOUND11";
		case IMAGE_B3A_BG5_ID: return "IMAGE_B3A_BG5";
		case SOUND_BOOK3_CH5_SOUND1_ID: return "SOUND_BOOK3_CH5_SOUND1";
		case SOUND_BOOK3_CH5_SOUND2_ID: return "SOUND_BOOK3_CH5_SOUND2";
		case SOUND_BOOK3_CH5_SOUND3_ID: return "SOUND_BOOK3_CH5_SOUND3";
		case SOUND_BOOK3_CH5_SOUND4_ID: return "SOUND_BOOK3_CH5_SOUND4";
		case SOUND_BOOK3_CH5_SOUND5_ID: return "SOUND_BOOK3_CH5_SOUND5";
		case SOUND_BOOK3_CH5_SOUND6_ID: return "SOUND_BOOK3_CH5_SOUND6";
		case SOUND_BOOK3_CH5_SOUND7_ID: return "SOUND_BOOK3_CH5_SOUND7";
		case SOUND_BOOK3_CH5_SOUND8_ID: return "SOUND_BOOK3_CH5_SOUND8";
		case SOUND_BOOK3_CH5_SOUND9_ID: return "SOUND_BOOK3_CH5_SOUND9";
		case SOUND_BOOK3_CH5_SOUND10_ID: return "SOUND_BOOK3_CH5_SOUND10";
		case SOUND_BOOK3_CH5_SOUND11_ID: return "SOUND_BOOK3_CH5_SOUND11";
		case SOUND_BOOK3_CH5_SOUND12_ID: return "SOUND_BOOK3_CH5_SOUND12";
		case IMAGE_B3A_BG6_ID: return "IMAGE_B3A_BG6";
		case SOUND_BOOK3_CH6_SOUND1_ID: return "SOUND_BOOK3_CH6_SOUND1";
		case SOUND_BOOK3_CH6_SOUND2_ID: return "SOUND_BOOK3_CH6_SOUND2";
		case SOUND_BOOK3_CH6_SOUND3_ID: return "SOUND_BOOK3_CH6_SOUND3";
		case SOUND_BOOK3_CH6_SOUND4_ID: return "SOUND_BOOK3_CH6_SOUND4";
		case SOUND_BOOK3_CH6_SOUND5_ID: return "SOUND_BOOK3_CH6_SOUND5";
		case SOUND_BOOK3_CH6_SOUND6_ID: return "SOUND_BOOK3_CH6_SOUND6";
		case SOUND_BOOK3_CH6_SOUND7_ID: return "SOUND_BOOK3_CH6_SOUND7";
		case SOUND_BOOK3_CH6_SOUND8_ID: return "SOUND_BOOK3_CH6_SOUND8";
		case SOUND_BOOK3_CH6_SOUND9_ID: return "SOUND_BOOK3_CH6_SOUND9";
		case SOUND_BOOK3_CH6_SOUND10_ID: return "SOUND_BOOK3_CH6_SOUND10";
		case SOUND_BOOK3_CH6_SOUND11_ID: return "SOUND_BOOK3_CH6_SOUND11";
		case SOUND_BOOK3_CH6_SOUND12_ID: return "SOUND_BOOK3_CH6_SOUND12";
		case IMAGE_B3A_BG7_ID: return "IMAGE_B3A_BG7";
		case IMAGE_B3A_HYDRA_BOSS_BATTLE_ID: return "IMAGE_B3A_HYDRA_BOSS_BATTLE";
		case SOUND_BOOK3_CH7_SOUND1_ID: return "SOUND_BOOK3_CH7_SOUND1";
		case SOUND_BOOK3_CH7_SOUND2_ID: return "SOUND_BOOK3_CH7_SOUND2";
		case SOUND_BOOK3_CH7_SOUND3_ID: return "SOUND_BOOK3_CH7_SOUND3";
		case SOUND_BOOK3_CH7_SOUND4_ID: return "SOUND_BOOK3_CH7_SOUND4";
		case SOUND_BOOK3_CH7_SOUND5_ID: return "SOUND_BOOK3_CH7_SOUND5";
		case SOUND_BOOK3_CH7_SOUND6_ID: return "SOUND_BOOK3_CH7_SOUND6";
		case SOUND_BOOK3_CH7_SOUND7_ID: return "SOUND_BOOK3_CH7_SOUND7";
		case SOUND_BOOK3_CH7_SOUND8_ID: return "SOUND_BOOK3_CH7_SOUND8";
		case SOUND_BOOK3_CH7_SOUND9_ID: return "SOUND_BOOK3_CH7_SOUND9";
		case IMAGE_B3A_BG8_ID: return "IMAGE_B3A_BG8";
		case SOUND_BOOK3_CH8_SOUND1_ID: return "SOUND_BOOK3_CH8_SOUND1";
		case SOUND_BOOK3_CH8_SOUND2_ID: return "SOUND_BOOK3_CH8_SOUND2";
		case SOUND_BOOK3_CH8_SOUND3_ID: return "SOUND_BOOK3_CH8_SOUND3";
		case SOUND_BOOK3_CH8_SOUND4_ID: return "SOUND_BOOK3_CH8_SOUND4";
		case SOUND_BOOK3_CH8_SOUND5_ID: return "SOUND_BOOK3_CH8_SOUND5";
		case SOUND_BOOK3_CH8_SOUND6_ID: return "SOUND_BOOK3_CH8_SOUND6";
		case SOUND_BOOK3_CH8_SOUND7_ID: return "SOUND_BOOK3_CH8_SOUND7";
		case IMAGE_B3A_BG9_ID: return "IMAGE_B3A_BG9";
		case SOUND_BOOK3_CH9_SOUND1_ID: return "SOUND_BOOK3_CH9_SOUND1";
		case SOUND_BOOK3_CH9_SOUND2_ID: return "SOUND_BOOK3_CH9_SOUND2";
		case SOUND_BOOK3_CH9_SOUND3_ID: return "SOUND_BOOK3_CH9_SOUND3";
		case SOUND_BOOK3_CH9_SOUND4_ID: return "SOUND_BOOK3_CH9_SOUND4";
		case SOUND_BOOK3_CH9_SOUND5_ID: return "SOUND_BOOK3_CH9_SOUND5";
		case SOUND_BOOK3_CH9_SOUND6_ID: return "SOUND_BOOK3_CH9_SOUND6";
		case SOUND_BOOK3_CH9_SOUND7_ID: return "SOUND_BOOK3_CH9_SOUND7";
		case SOUND_BOOK3_CH9_SOUND8_ID: return "SOUND_BOOK3_CH9_SOUND8";
		case SOUND_BOOK3_CH9_SOUND9_ID: return "SOUND_BOOK3_CH9_SOUND9";
		case SOUND_BOOK3_CH9_SOUND10_ID: return "SOUND_BOOK3_CH9_SOUND10";
		case SOUND_BOOK3_CH9_SOUND12_ID: return "SOUND_BOOK3_CH9_SOUND12";
		case SOUND_BOOK3_CH9_SOUND13_ID: return "SOUND_BOOK3_CH9_SOUND13";
		case IMAGE_B3A_BG10_ID: return "IMAGE_B3A_BG10";
		case IMAGE_B3A_CODEX_BOSS_BATTLE_ID: return "IMAGE_B3A_CODEX_BOSS_BATTLE";
		case SOUND_BOOK3_CH10_SOUND1_ID: return "SOUND_BOOK3_CH10_SOUND1";
		case SOUND_BOOK3_CH10_SOUND2_ID: return "SOUND_BOOK3_CH10_SOUND2";
		case SOUND_BOOK3_CH10_SOUND3_ID: return "SOUND_BOOK3_CH10_SOUND3";
		case SOUND_BOOK3_CH10_SOUND4_ID: return "SOUND_BOOK3_CH10_SOUND4";
		case SOUND_BOOK3_CH10_SOUND5_ID: return "SOUND_BOOK3_CH10_SOUND5";
		case SOUND_BOOK3_CH10_SOUND7_ID: return "SOUND_BOOK3_CH10_SOUND7";
		case SOUND_BOOK3_CH10_CODEXSUMMON_ID: return "SOUND_BOOK3_CH10_CODEXSUMMON";
		case SOUND_BOOK3_CH10_CODEXLAUGH_ID: return "SOUND_BOOK3_CH10_CODEXLAUGH";
		case SOUND_BOOK3_CH10_CODEXFLINCH_ID: return "SOUND_BOOK3_CH10_CODEXFLINCH";
		case SOUND_BOOK3_CH10_CODEXNYAH_ID: return "SOUND_BOOK3_CH10_CODEXNYAH";
		case SOUND_BOOK3_CH10_LEXBEAM_ID: return "SOUND_BOOK3_CH10_LEXBEAM";
		case SOUND_BOOK3_CH10_AUTOLOGICAL_ID: return "SOUND_BOOK3_CH10_AUTOLOGICAL";
		default: return "";
	}
}

