#include "Book2.h"
#include "SexyAppFramework/ResourceManager.h"

using namespace Sexy;

#pragma warning(disable:4311 4312)

static bool gNeedRecalcVariableToIdMap = false;

bool Sexy::ExtractResourcesByName(ResourceManager *theManager, const char *theName)
{
	if (strcmp(theName,"Book2Chapter1")==0) return ExtractBook2Chapter1Resources(theManager);
	if (strcmp(theName,"Book2Chapter10")==0) return ExtractBook2Chapter10Resources(theManager);
	if (strcmp(theName,"Book2Chapter2")==0) return ExtractBook2Chapter2Resources(theManager);
	if (strcmp(theName,"Book2Chapter3")==0) return ExtractBook2Chapter3Resources(theManager);
	if (strcmp(theName,"Book2Chapter4")==0) return ExtractBook2Chapter4Resources(theManager);
	if (strcmp(theName,"Book2Chapter5")==0) return ExtractBook2Chapter5Resources(theManager);
	if (strcmp(theName,"Book2Chapter6")==0) return ExtractBook2Chapter6Resources(theManager);
	if (strcmp(theName,"Book2Chapter7")==0) return ExtractBook2Chapter7Resources(theManager);
	if (strcmp(theName,"Book2Chapter8")==0) return ExtractBook2Chapter8Resources(theManager);
	if (strcmp(theName,"Book2Chapter9")==0) return ExtractBook2Chapter9Resources(theManager);
	if (strcmp(theName,"Book2Common")==0) return ExtractBook2CommonResources(theManager);
	if (strcmp(theName,"Book2Init")==0) return ExtractBook2InitResources(theManager);
	return false;
}

Sexy::ResourceId Sexy::GetIdByStringId(const char *theStringId)
{
	typedef std::map<std::string,int> MyMap;
	static MyMap aMap;
	if(aMap.empty())
	{
		for(int i=0; i<RESOURCE_ID_MAX; i++)
			aMap[GetStringIdById(i)] = i;
	}

	MyMap::iterator anItr = aMap.find(theStringId);
	if (anItr == aMap.end())
		return RESOURCE_ID_MAX;
	else
		return (ResourceId) anItr->second;
}

// Book2Chapter1 Resources
Image* Sexy::IMAGE_B2A_DOCKSKY;
int Sexy::SOUND_BOOK2_CH1_FEMALE1;
int Sexy::SOUND_BOOK2_CH1_FEMALE2;
int Sexy::SOUND_BOOK2_CH1_IMPACT1;
int Sexy::SOUND_BOOK2_CH1_IMPACT2;
int Sexy::SOUND_BOOK2_CH1_IMPACT3;
int Sexy::SOUND_BOOK2_CH1_MALE1;
int Sexy::SOUND_BOOK2_CH1_MALE2;
int Sexy::SOUND_BOOK2_CH1_MALE3;
int Sexy::SOUND_BOOK2_CH1_MALE4;
int Sexy::SOUND_BOOK2_CH1_MALE5;
int Sexy::SOUND_BOOK2_CH1_MALE6;
int Sexy::SOUND_BOOK2_CH1_MALE7;
int Sexy::SOUND_BOOK2_CH1_MALE8;
int Sexy::SOUND_BOOK2_CH1_MALE9;
int Sexy::SOUND_BOOK2_CH1_SPECIAL1;
int Sexy::SOUND_BOOK2_CH1_SPECIAL2;

bool Sexy::ExtractBook2Chapter1Resources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_B2A_DOCKSKY = aMgr.GetImageThrow("IMAGE_B2A_DOCKSKY");
		SOUND_BOOK2_CH1_FEMALE1 = aMgr.GetSoundThrow("SOUND_BOOK2_CH1_FEMALE1");
		SOUND_BOOK2_CH1_FEMALE2 = aMgr.GetSoundThrow("SOUND_BOOK2_CH1_FEMALE2");
		SOUND_BOOK2_CH1_IMPACT1 = aMgr.GetSoundThrow("SOUND_BOOK2_CH1_IMPACT1");
		SOUND_BOOK2_CH1_IMPACT2 = aMgr.GetSoundThrow("SOUND_BOOK2_CH1_IMPACT2");
		SOUND_BOOK2_CH1_IMPACT3 = aMgr.GetSoundThrow("SOUND_BOOK2_CH1_IMPACT3");
		SOUND_BOOK2_CH1_MALE1 = aMgr.GetSoundThrow("SOUND_BOOK2_CH1_MALE1");
		SOUND_BOOK2_CH1_MALE2 = aMgr.GetSoundThrow("SOUND_BOOK2_CH1_MALE2");
		SOUND_BOOK2_CH1_MALE3 = aMgr.GetSoundThrow("SOUND_BOOK2_CH1_MALE3");
		SOUND_BOOK2_CH1_MALE4 = aMgr.GetSoundThrow("SOUND_BOOK2_CH1_MALE4");
		SOUND_BOOK2_CH1_MALE5 = aMgr.GetSoundThrow("SOUND_BOOK2_CH1_MALE5");
		SOUND_BOOK2_CH1_MALE6 = aMgr.GetSoundThrow("SOUND_BOOK2_CH1_MALE6");
		SOUND_BOOK2_CH1_MALE7 = aMgr.GetSoundThrow("SOUND_BOOK2_CH1_MALE7");
		SOUND_BOOK2_CH1_MALE8 = aMgr.GetSoundThrow("SOUND_BOOK2_CH1_MALE8");
		SOUND_BOOK2_CH1_MALE9 = aMgr.GetSoundThrow("SOUND_BOOK2_CH1_MALE9");
		SOUND_BOOK2_CH1_SPECIAL1 = aMgr.GetSoundThrow("SOUND_BOOK2_CH1_SPECIAL1");
		SOUND_BOOK2_CH1_SPECIAL2 = aMgr.GetSoundThrow("SOUND_BOOK2_CH1_SPECIAL2");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// Book2Chapter10 Resources
Image* Sexy::IMAGE_B2A_SUNSET;
int Sexy::SOUND_BOOK2_CH10_SOUND1;
int Sexy::SOUND_BOOK2_CH10_SOUND10;
int Sexy::SOUND_BOOK2_CH10_SOUND12;
int Sexy::SOUND_BOOK2_CH10_SOUND13;
int Sexy::SOUND_BOOK2_CH10_SOUND14;
int Sexy::SOUND_BOOK2_CH10_SOUND2;
int Sexy::SOUND_BOOK2_CH10_SOUND4;
int Sexy::SOUND_BOOK2_CH10_SOUND5;
int Sexy::SOUND_BOOK2_CH10_SOUND6;
int Sexy::SOUND_BOOK2_CH10_SOUND8;

bool Sexy::ExtractBook2Chapter10Resources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_B2A_SUNSET = aMgr.GetImageThrow("IMAGE_B2A_SUNSET");
		SOUND_BOOK2_CH10_SOUND1 = aMgr.GetSoundThrow("SOUND_BOOK2_CH10_SOUND1");
		SOUND_BOOK2_CH10_SOUND10 = aMgr.GetSoundThrow("SOUND_BOOK2_CH10_SOUND10");
		SOUND_BOOK2_CH10_SOUND12 = aMgr.GetSoundThrow("SOUND_BOOK2_CH10_SOUND12");
		SOUND_BOOK2_CH10_SOUND13 = aMgr.GetSoundThrow("SOUND_BOOK2_CH10_SOUND13");
		SOUND_BOOK2_CH10_SOUND14 = aMgr.GetSoundThrow("SOUND_BOOK2_CH10_SOUND14");
		SOUND_BOOK2_CH10_SOUND2 = aMgr.GetSoundThrow("SOUND_BOOK2_CH10_SOUND2");
		SOUND_BOOK2_CH10_SOUND4 = aMgr.GetSoundThrow("SOUND_BOOK2_CH10_SOUND4");
		SOUND_BOOK2_CH10_SOUND5 = aMgr.GetSoundThrow("SOUND_BOOK2_CH10_SOUND5");
		SOUND_BOOK2_CH10_SOUND6 = aMgr.GetSoundThrow("SOUND_BOOK2_CH10_SOUND6");
		SOUND_BOOK2_CH10_SOUND8 = aMgr.GetSoundThrow("SOUND_BOOK2_CH10_SOUND8");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// Book2Chapter2 Resources
Image* Sexy::IMAGE_B2A_BLACK3;
int Sexy::SOUND_BOOK2_CH2_DOG1;
int Sexy::SOUND_BOOK2_CH2_DOG2;
int Sexy::SOUND_BOOK2_CH2_DOG3;
int Sexy::SOUND_BOOK2_CH2_DOG4;
int Sexy::SOUND_BOOK2_CH2_IMPACT1;
int Sexy::SOUND_BOOK2_CH2_IMPACT2;
int Sexy::SOUND_BOOK2_CH2_IMPACT4;
int Sexy::SOUND_BOOK2_CH2_KUBWA1;
int Sexy::SOUND_BOOK2_CH2_KUBWA2;
int Sexy::SOUND_BOOK2_CH2_KUBWA3;
int Sexy::SOUND_BOOK2_CH2_KUBWA4;
int Sexy::SOUND_BOOK2_CH2_LARGEIMPACT;
int Sexy::SOUND_BOOK2_CH2_MALE1;
int Sexy::SOUND_BOOK2_CH2_MALE10;
int Sexy::SOUND_BOOK2_CH2_MALE2;
int Sexy::SOUND_BOOK2_CH2_MALE3;
int Sexy::SOUND_BOOK2_CH2_MALE4;
int Sexy::SOUND_BOOK2_CH2_MALE6;
int Sexy::SOUND_BOOK2_CH2_MALE7;
int Sexy::SOUND_BOOK2_CH2_MALE8;
int Sexy::SOUND_BOOK2_CH2_MALE9;
int Sexy::SOUND_BOOK2_CH2_SPECIAL3;
int Sexy::SOUND_BOOK2_CH2_WARP;

bool Sexy::ExtractBook2Chapter2Resources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_B2A_BLACK3 = aMgr.GetImageThrow("IMAGE_B2A_BLACK3");
		SOUND_BOOK2_CH2_DOG1 = aMgr.GetSoundThrow("SOUND_BOOK2_CH2_DOG1");
		SOUND_BOOK2_CH2_DOG2 = aMgr.GetSoundThrow("SOUND_BOOK2_CH2_DOG2");
		SOUND_BOOK2_CH2_DOG3 = aMgr.GetSoundThrow("SOUND_BOOK2_CH2_DOG3");
		SOUND_BOOK2_CH2_DOG4 = aMgr.GetSoundThrow("SOUND_BOOK2_CH2_DOG4");
		SOUND_BOOK2_CH2_IMPACT1 = aMgr.GetSoundThrow("SOUND_BOOK2_CH2_IMPACT1");
		SOUND_BOOK2_CH2_IMPACT2 = aMgr.GetSoundThrow("SOUND_BOOK2_CH2_IMPACT2");
		SOUND_BOOK2_CH2_IMPACT4 = aMgr.GetSoundThrow("SOUND_BOOK2_CH2_IMPACT4");
		SOUND_BOOK2_CH2_KUBWA1 = aMgr.GetSoundThrow("SOUND_BOOK2_CH2_KUBWA1");
		SOUND_BOOK2_CH2_KUBWA2 = aMgr.GetSoundThrow("SOUND_BOOK2_CH2_KUBWA2");
		SOUND_BOOK2_CH2_KUBWA3 = aMgr.GetSoundThrow("SOUND_BOOK2_CH2_KUBWA3");
		SOUND_BOOK2_CH2_KUBWA4 = aMgr.GetSoundThrow("SOUND_BOOK2_CH2_KUBWA4");
		SOUND_BOOK2_CH2_LARGEIMPACT = aMgr.GetSoundThrow("SOUND_BOOK2_CH2_LARGEIMPACT");
		SOUND_BOOK2_CH2_MALE1 = aMgr.GetSoundThrow("SOUND_BOOK2_CH2_MALE1");
		SOUND_BOOK2_CH2_MALE10 = aMgr.GetSoundThrow("SOUND_BOOK2_CH2_MALE10");
		SOUND_BOOK2_CH2_MALE2 = aMgr.GetSoundThrow("SOUND_BOOK2_CH2_MALE2");
		SOUND_BOOK2_CH2_MALE3 = aMgr.GetSoundThrow("SOUND_BOOK2_CH2_MALE3");
		SOUND_BOOK2_CH2_MALE4 = aMgr.GetSoundThrow("SOUND_BOOK2_CH2_MALE4");
		SOUND_BOOK2_CH2_MALE6 = aMgr.GetSoundThrow("SOUND_BOOK2_CH2_MALE6");
		SOUND_BOOK2_CH2_MALE7 = aMgr.GetSoundThrow("SOUND_BOOK2_CH2_MALE7");
		SOUND_BOOK2_CH2_MALE8 = aMgr.GetSoundThrow("SOUND_BOOK2_CH2_MALE8");
		SOUND_BOOK2_CH2_MALE9 = aMgr.GetSoundThrow("SOUND_BOOK2_CH2_MALE9");
		SOUND_BOOK2_CH2_SPECIAL3 = aMgr.GetSoundThrow("SOUND_BOOK2_CH2_SPECIAL3");
		SOUND_BOOK2_CH2_WARP = aMgr.GetSoundThrow("SOUND_BOOK2_CH2_WARP");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// Book2Chapter3 Resources
Image* Sexy::IMAGE_B2A_BLACK2;
int Sexy::SOUND_BOOK2_CH3_DOG1;
int Sexy::SOUND_BOOK2_CH3_DOG2;
int Sexy::SOUND_BOOK2_CH3_DOG3;
int Sexy::SOUND_BOOK2_CH3_DOG4;
int Sexy::SOUND_BOOK2_CH3_DRAGON1;
int Sexy::SOUND_BOOK2_CH3_DRAGON2;
int Sexy::SOUND_BOOK2_CH3_DRAGON3;
int Sexy::SOUND_BOOK2_CH3_DRAGON4;
int Sexy::SOUND_BOOK2_CH3_HISS;
int Sexy::SOUND_BOOK2_CH3_IMPACT1;
int Sexy::SOUND_BOOK2_CH3_IMPACT2;
int Sexy::SOUND_BOOK2_CH3_MALE1;
int Sexy::SOUND_BOOK2_CH3_MALE2;
int Sexy::SOUND_BOOK2_CH3_MALE3;
int Sexy::SOUND_BOOK2_CH3_MALE4;
int Sexy::SOUND_BOOK2_CH3_SPECIAL1;
int Sexy::SOUND_BOOK2_CH3_SPECIAL2;
int Sexy::SOUND_BOOK2_CH3_SPECIAL3;
int Sexy::SOUND_BOOK2_CH3_SQUEAL1;
int Sexy::SOUND_BOOK2_CH3_SQUEAL2;

bool Sexy::ExtractBook2Chapter3Resources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_B2A_BLACK2 = aMgr.GetImageThrow("IMAGE_B2A_BLACK2");
		SOUND_BOOK2_CH3_DOG1 = aMgr.GetSoundThrow("SOUND_BOOK2_CH3_DOG1");
		SOUND_BOOK2_CH3_DOG2 = aMgr.GetSoundThrow("SOUND_BOOK2_CH3_DOG2");
		SOUND_BOOK2_CH3_DOG3 = aMgr.GetSoundThrow("SOUND_BOOK2_CH3_DOG3");
		SOUND_BOOK2_CH3_DOG4 = aMgr.GetSoundThrow("SOUND_BOOK2_CH3_DOG4");
		SOUND_BOOK2_CH3_DRAGON1 = aMgr.GetSoundThrow("SOUND_BOOK2_CH3_DRAGON1");
		SOUND_BOOK2_CH3_DRAGON2 = aMgr.GetSoundThrow("SOUND_BOOK2_CH3_DRAGON2");
		SOUND_BOOK2_CH3_DRAGON3 = aMgr.GetSoundThrow("SOUND_BOOK2_CH3_DRAGON3");
		SOUND_BOOK2_CH3_DRAGON4 = aMgr.GetSoundThrow("SOUND_BOOK2_CH3_DRAGON4");
		SOUND_BOOK2_CH3_HISS = aMgr.GetSoundThrow("SOUND_BOOK2_CH3_HISS");
		SOUND_BOOK2_CH3_IMPACT1 = aMgr.GetSoundThrow("SOUND_BOOK2_CH3_IMPACT1");
		SOUND_BOOK2_CH3_IMPACT2 = aMgr.GetSoundThrow("SOUND_BOOK2_CH3_IMPACT2");
		SOUND_BOOK2_CH3_MALE1 = aMgr.GetSoundThrow("SOUND_BOOK2_CH3_MALE1");
		SOUND_BOOK2_CH3_MALE2 = aMgr.GetSoundThrow("SOUND_BOOK2_CH3_MALE2");
		SOUND_BOOK2_CH3_MALE3 = aMgr.GetSoundThrow("SOUND_BOOK2_CH3_MALE3");
		SOUND_BOOK2_CH3_MALE4 = aMgr.GetSoundThrow("SOUND_BOOK2_CH3_MALE4");
		SOUND_BOOK2_CH3_SPECIAL1 = aMgr.GetSoundThrow("SOUND_BOOK2_CH3_SPECIAL1");
		SOUND_BOOK2_CH3_SPECIAL2 = aMgr.GetSoundThrow("SOUND_BOOK2_CH3_SPECIAL2");
		SOUND_BOOK2_CH3_SPECIAL3 = aMgr.GetSoundThrow("SOUND_BOOK2_CH3_SPECIAL3");
		SOUND_BOOK2_CH3_SQUEAL1 = aMgr.GetSoundThrow("SOUND_BOOK2_CH3_SQUEAL1");
		SOUND_BOOK2_CH3_SQUEAL2 = aMgr.GetSoundThrow("SOUND_BOOK2_CH3_SQUEAL2");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// Book2Chapter4 Resources
Image* Sexy::IMAGE_B2A_PYRA_SKY;
Image* Sexy::IMAGE_B2_SPHINX_BOSS_BATTLE;
Image* Sexy::IMAGE_B2_SPHINX_RIDDLE;
int Sexy::SOUND_BOOK2_CH4_ATTACK;
int Sexy::SOUND_BOOK2_CH4_DEATH;

bool Sexy::ExtractBook2Chapter4Resources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_B2A_PYRA_SKY = aMgr.GetImageThrow("IMAGE_B2A_PYRA_SKY");
		IMAGE_B2_SPHINX_BOSS_BATTLE = aMgr.GetImageThrow("IMAGE_B2_SPHINX_BOSS_BATTLE");
		IMAGE_B2_SPHINX_RIDDLE = aMgr.GetImageThrow("IMAGE_B2_SPHINX_RIDDLE");
		SOUND_BOOK2_CH4_ATTACK = aMgr.GetSoundThrow("SOUND_BOOK2_CH4_ATTACK");
		SOUND_BOOK2_CH4_DEATH = aMgr.GetSoundThrow("SOUND_BOOK2_CH4_DEATH");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// Book2Chapter5 Resources
Image* Sexy::IMAGE_B2A_BLUE_SEA;
int Sexy::SOUND_BOOK2_CH5_ATTACK1;
int Sexy::SOUND_BOOK2_CH5_ATTACK6;
int Sexy::SOUND_BOOK2_CH5_DOG1;
int Sexy::SOUND_BOOK2_CH5_DOG2;
int Sexy::SOUND_BOOK2_CH5_DOG3;
int Sexy::SOUND_BOOK2_CH5_DOG4;
int Sexy::SOUND_BOOK2_CH5_HIT1;
int Sexy::SOUND_BOOK2_CH5_MALE1;
int Sexy::SOUND_BOOK2_CH5_MALE2;
int Sexy::SOUND_BOOK2_CH5_MALE3;
int Sexy::SOUND_BOOK2_CH5_MALE4;
int Sexy::SOUND_BOOK2_CH5_MALE5;
int Sexy::SOUND_BOOK2_CH5_MALE6;
int Sexy::SOUND_BOOK2_CH5_MALE7;
int Sexy::SOUND_BOOK2_CH5_MALE8;

bool Sexy::ExtractBook2Chapter5Resources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_B2A_BLUE_SEA = aMgr.GetImageThrow("IMAGE_B2A_BLUE_SEA");
		SOUND_BOOK2_CH5_ATTACK1 = aMgr.GetSoundThrow("SOUND_BOOK2_CH5_ATTACK1");
		SOUND_BOOK2_CH5_ATTACK6 = aMgr.GetSoundThrow("SOUND_BOOK2_CH5_ATTACK6");
		SOUND_BOOK2_CH5_DOG1 = aMgr.GetSoundThrow("SOUND_BOOK2_CH5_DOG1");
		SOUND_BOOK2_CH5_DOG2 = aMgr.GetSoundThrow("SOUND_BOOK2_CH5_DOG2");
		SOUND_BOOK2_CH5_DOG3 = aMgr.GetSoundThrow("SOUND_BOOK2_CH5_DOG3");
		SOUND_BOOK2_CH5_DOG4 = aMgr.GetSoundThrow("SOUND_BOOK2_CH5_DOG4");
		SOUND_BOOK2_CH5_HIT1 = aMgr.GetSoundThrow("SOUND_BOOK2_CH5_HIT1");
		SOUND_BOOK2_CH5_MALE1 = aMgr.GetSoundThrow("SOUND_BOOK2_CH5_MALE1");
		SOUND_BOOK2_CH5_MALE2 = aMgr.GetSoundThrow("SOUND_BOOK2_CH5_MALE2");
		SOUND_BOOK2_CH5_MALE3 = aMgr.GetSoundThrow("SOUND_BOOK2_CH5_MALE3");
		SOUND_BOOK2_CH5_MALE4 = aMgr.GetSoundThrow("SOUND_BOOK2_CH5_MALE4");
		SOUND_BOOK2_CH5_MALE5 = aMgr.GetSoundThrow("SOUND_BOOK2_CH5_MALE5");
		SOUND_BOOK2_CH5_MALE6 = aMgr.GetSoundThrow("SOUND_BOOK2_CH5_MALE6");
		SOUND_BOOK2_CH5_MALE7 = aMgr.GetSoundThrow("SOUND_BOOK2_CH5_MALE7");
		SOUND_BOOK2_CH5_MALE8 = aMgr.GetSoundThrow("SOUND_BOOK2_CH5_MALE8");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// Book2Chapter6 Resources
Image* Sexy::IMAGE_B2A_BLUE_SEA2;
int Sexy::SOUND_BOOK2_CH6_SOUND1;
int Sexy::SOUND_BOOK2_CH6_SOUND10;
int Sexy::SOUND_BOOK2_CH6_SOUND11;
int Sexy::SOUND_BOOK2_CH6_SOUND12;
int Sexy::SOUND_BOOK2_CH6_SOUND3;
int Sexy::SOUND_BOOK2_CH6_SOUND4;
int Sexy::SOUND_BOOK2_CH6_SOUND6;
int Sexy::SOUND_BOOK2_CH6_SOUND7;
int Sexy::SOUND_BOOK2_CH6_SOUND8;
int Sexy::SOUND_BOOK2_CH6_SOUND9;

bool Sexy::ExtractBook2Chapter6Resources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_B2A_BLUE_SEA2 = aMgr.GetImageThrow("IMAGE_B2A_BLUE_SEA2");
		SOUND_BOOK2_CH6_SOUND1 = aMgr.GetSoundThrow("SOUND_BOOK2_CH6_SOUND1");
		SOUND_BOOK2_CH6_SOUND10 = aMgr.GetSoundThrow("SOUND_BOOK2_CH6_SOUND10");
		SOUND_BOOK2_CH6_SOUND11 = aMgr.GetSoundThrow("SOUND_BOOK2_CH6_SOUND11");
		SOUND_BOOK2_CH6_SOUND12 = aMgr.GetSoundThrow("SOUND_BOOK2_CH6_SOUND12");
		SOUND_BOOK2_CH6_SOUND3 = aMgr.GetSoundThrow("SOUND_BOOK2_CH6_SOUND3");
		SOUND_BOOK2_CH6_SOUND4 = aMgr.GetSoundThrow("SOUND_BOOK2_CH6_SOUND4");
		SOUND_BOOK2_CH6_SOUND6 = aMgr.GetSoundThrow("SOUND_BOOK2_CH6_SOUND6");
		SOUND_BOOK2_CH6_SOUND7 = aMgr.GetSoundThrow("SOUND_BOOK2_CH6_SOUND7");
		SOUND_BOOK2_CH6_SOUND8 = aMgr.GetSoundThrow("SOUND_BOOK2_CH6_SOUND8");
		SOUND_BOOK2_CH6_SOUND9 = aMgr.GetSoundThrow("SOUND_BOOK2_CH6_SOUND9");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// Book2Chapter7 Resources
Image* Sexy::IMAGE_B2A_MIRAGE;
int Sexy::SOUND_BOOK2_CH7_SOUND1;
int Sexy::SOUND_BOOK2_CH7_SOUND12;
int Sexy::SOUND_BOOK2_CH7_SOUND13;
int Sexy::SOUND_BOOK2_CH7_SOUND15;
int Sexy::SOUND_BOOK2_CH7_SOUND16;
int Sexy::SOUND_BOOK2_CH7_SOUND17;
int Sexy::SOUND_BOOK2_CH7_SOUND18;
int Sexy::SOUND_BOOK2_CH7_SOUND2;
int Sexy::SOUND_BOOK2_CH7_SOUND4;
int Sexy::SOUND_BOOK2_CH7_SOUND5;
int Sexy::SOUND_BOOK2_CH7_SOUND6;

bool Sexy::ExtractBook2Chapter7Resources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_B2A_MIRAGE = aMgr.GetImageThrow("IMAGE_B2A_MIRAGE");
		SOUND_BOOK2_CH7_SOUND1 = aMgr.GetSoundThrow("SOUND_BOOK2_CH7_SOUND1");
		SOUND_BOOK2_CH7_SOUND12 = aMgr.GetSoundThrow("SOUND_BOOK2_CH7_SOUND12");
		SOUND_BOOK2_CH7_SOUND13 = aMgr.GetSoundThrow("SOUND_BOOK2_CH7_SOUND13");
		SOUND_BOOK2_CH7_SOUND15 = aMgr.GetSoundThrow("SOUND_BOOK2_CH7_SOUND15");
		SOUND_BOOK2_CH7_SOUND16 = aMgr.GetSoundThrow("SOUND_BOOK2_CH7_SOUND16");
		SOUND_BOOK2_CH7_SOUND17 = aMgr.GetSoundThrow("SOUND_BOOK2_CH7_SOUND17");
		SOUND_BOOK2_CH7_SOUND18 = aMgr.GetSoundThrow("SOUND_BOOK2_CH7_SOUND18");
		SOUND_BOOK2_CH7_SOUND2 = aMgr.GetSoundThrow("SOUND_BOOK2_CH7_SOUND2");
		SOUND_BOOK2_CH7_SOUND4 = aMgr.GetSoundThrow("SOUND_BOOK2_CH7_SOUND4");
		SOUND_BOOK2_CH7_SOUND5 = aMgr.GetSoundThrow("SOUND_BOOK2_CH7_SOUND5");
		SOUND_BOOK2_CH7_SOUND6 = aMgr.GetSoundThrow("SOUND_BOOK2_CH7_SOUND6");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// Book2Chapter8 Resources
Image* Sexy::IMAGE_B2A_SKY8;
int Sexy::SOUND_BOOK2_CH8_SOUND1;
int Sexy::SOUND_BOOK2_CH8_SOUND10;
int Sexy::SOUND_BOOK2_CH8_SOUND12;
int Sexy::SOUND_BOOK2_CH8_SOUND13;
int Sexy::SOUND_BOOK2_CH8_SOUND14;
int Sexy::SOUND_BOOK2_CH8_SOUND15;
int Sexy::SOUND_BOOK2_CH8_SOUND16;
int Sexy::SOUND_BOOK2_CH8_SOUND18;
int Sexy::SOUND_BOOK2_CH8_SOUND2;
int Sexy::SOUND_BOOK2_CH8_SOUND3;
int Sexy::SOUND_BOOK2_CH8_SOUND4;
int Sexy::SOUND_BOOK2_CH8_SOUND5;
int Sexy::SOUND_BOOK2_CH8_SOUND7;
int Sexy::SOUND_BOOK2_CH8_SOUND8;
int Sexy::SOUND_BOOK2_CH8_SOUND9;

bool Sexy::ExtractBook2Chapter8Resources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_B2A_SKY8 = aMgr.GetImageThrow("IMAGE_B2A_SKY8");
		SOUND_BOOK2_CH8_SOUND1 = aMgr.GetSoundThrow("SOUND_BOOK2_CH8_SOUND1");
		SOUND_BOOK2_CH8_SOUND10 = aMgr.GetSoundThrow("SOUND_BOOK2_CH8_SOUND10");
		SOUND_BOOK2_CH8_SOUND12 = aMgr.GetSoundThrow("SOUND_BOOK2_CH8_SOUND12");
		SOUND_BOOK2_CH8_SOUND13 = aMgr.GetSoundThrow("SOUND_BOOK2_CH8_SOUND13");
		SOUND_BOOK2_CH8_SOUND14 = aMgr.GetSoundThrow("SOUND_BOOK2_CH8_SOUND14");
		SOUND_BOOK2_CH8_SOUND15 = aMgr.GetSoundThrow("SOUND_BOOK2_CH8_SOUND15");
		SOUND_BOOK2_CH8_SOUND16 = aMgr.GetSoundThrow("SOUND_BOOK2_CH8_SOUND16");
		SOUND_BOOK2_CH8_SOUND18 = aMgr.GetSoundThrow("SOUND_BOOK2_CH8_SOUND18");
		SOUND_BOOK2_CH8_SOUND2 = aMgr.GetSoundThrow("SOUND_BOOK2_CH8_SOUND2");
		SOUND_BOOK2_CH8_SOUND3 = aMgr.GetSoundThrow("SOUND_BOOK2_CH8_SOUND3");
		SOUND_BOOK2_CH8_SOUND4 = aMgr.GetSoundThrow("SOUND_BOOK2_CH8_SOUND4");
		SOUND_BOOK2_CH8_SOUND5 = aMgr.GetSoundThrow("SOUND_BOOK2_CH8_SOUND5");
		SOUND_BOOK2_CH8_SOUND7 = aMgr.GetSoundThrow("SOUND_BOOK2_CH8_SOUND7");
		SOUND_BOOK2_CH8_SOUND8 = aMgr.GetSoundThrow("SOUND_BOOK2_CH8_SOUND8");
		SOUND_BOOK2_CH8_SOUND9 = aMgr.GetSoundThrow("SOUND_BOOK2_CH8_SOUND9");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// Book2Chapter9 Resources
Image* Sexy::IMAGE_B2A_SKY9;
int Sexy::SOUND_BOOK2_CH9_SOUND1;
int Sexy::SOUND_BOOK2_CH9_SOUND12;
int Sexy::SOUND_BOOK2_CH9_SOUND13;
int Sexy::SOUND_BOOK2_CH9_SOUND15;
int Sexy::SOUND_BOOK2_CH9_SOUND2;
int Sexy::SOUND_BOOK2_CH9_SOUND3;
int Sexy::SOUND_BOOK2_CH9_SOUND4;
int Sexy::SOUND_BOOK2_CH9_SOUND5;
int Sexy::SOUND_BOOK2_CH9_SOUND7;
int Sexy::SOUND_BOOK2_CH9_SOUND8;

bool Sexy::ExtractBook2Chapter9Resources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_B2A_SKY9 = aMgr.GetImageThrow("IMAGE_B2A_SKY9");
		SOUND_BOOK2_CH9_SOUND1 = aMgr.GetSoundThrow("SOUND_BOOK2_CH9_SOUND1");
		SOUND_BOOK2_CH9_SOUND12 = aMgr.GetSoundThrow("SOUND_BOOK2_CH9_SOUND12");
		SOUND_BOOK2_CH9_SOUND13 = aMgr.GetSoundThrow("SOUND_BOOK2_CH9_SOUND13");
		SOUND_BOOK2_CH9_SOUND15 = aMgr.GetSoundThrow("SOUND_BOOK2_CH9_SOUND15");
		SOUND_BOOK2_CH9_SOUND2 = aMgr.GetSoundThrow("SOUND_BOOK2_CH9_SOUND2");
		SOUND_BOOK2_CH9_SOUND3 = aMgr.GetSoundThrow("SOUND_BOOK2_CH9_SOUND3");
		SOUND_BOOK2_CH9_SOUND4 = aMgr.GetSoundThrow("SOUND_BOOK2_CH9_SOUND4");
		SOUND_BOOK2_CH9_SOUND5 = aMgr.GetSoundThrow("SOUND_BOOK2_CH9_SOUND5");
		SOUND_BOOK2_CH9_SOUND7 = aMgr.GetSoundThrow("SOUND_BOOK2_CH9_SOUND7");
		SOUND_BOOK2_CH9_SOUND8 = aMgr.GetSoundThrow("SOUND_BOOK2_CH9_SOUND8");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// Book2Common Resources
Image* Sexy::IMAGE_B2_LEFT_FACING_ARROW;

bool Sexy::ExtractBook2CommonResources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_B2_LEFT_FACING_ARROW = aMgr.GetImageThrow("IMAGE_B2_LEFT_FACING_ARROW");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// Book2Init Resources
Image* Sexy::IMAGE_B2_ICONANIM1;
Image* Sexy::IMAGE_B2_ICONANIM10;
Image* Sexy::IMAGE_B2_ICONANIM2;
Image* Sexy::IMAGE_B2_ICONANIM3;
Image* Sexy::IMAGE_B2_ICONANIM4;
Image* Sexy::IMAGE_B2_ICONANIM5;
Image* Sexy::IMAGE_B2_ICONANIM6;
Image* Sexy::IMAGE_B2_ICONANIM7;
Image* Sexy::IMAGE_B2_ICONANIM8;
Image* Sexy::IMAGE_B2_ICONANIM9;
Image* Sexy::IMAGE_B2_ICONMASK1;
Image* Sexy::IMAGE_B2_ICONMASK10;
Image* Sexy::IMAGE_B2_ICONMASK2;
Image* Sexy::IMAGE_B2_ICONMASK3;
Image* Sexy::IMAGE_B2_ICONMASK4;
Image* Sexy::IMAGE_B2_ICONMASK5;
Image* Sexy::IMAGE_B2_ICONMASK6;
Image* Sexy::IMAGE_B2_ICONMASK7;
Image* Sexy::IMAGE_B2_ICONMASK8;
Image* Sexy::IMAGE_B2_ICONMASK9;
Image* Sexy::IMAGE_B2_MAP;
Image* Sexy::IMAGE_B2_MAPSCREEN_BANNER;
Image* Sexy::IMAGE_B2_MINIMAP_ICONS;
Image* Sexy::IMAGE_TUT_PIC_MALADIN;
Image* Sexy::IMAGE_TUT_PIC_MURRAY;
Image* Sexy::IMAGE_TUT_PIC_SCHE1;
Image* Sexy::IMAGE_TUT_PIC_SCHE2;
Image* Sexy::IMAGE_TUT_PIC_SINBAD;
Image* Sexy::IMAGE_TUT_PIC_VIZIER;

bool Sexy::ExtractBook2InitResources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_B2_ICONANIM1 = aMgr.GetImageThrow("IMAGE_B2_ICONANIM1");
		IMAGE_B2_ICONANIM10 = aMgr.GetImageThrow("IMAGE_B2_ICONANIM10");
		IMAGE_B2_ICONANIM2 = aMgr.GetImageThrow("IMAGE_B2_ICONANIM2");
		IMAGE_B2_ICONANIM3 = aMgr.GetImageThrow("IMAGE_B2_ICONANIM3");
		IMAGE_B2_ICONANIM4 = aMgr.GetImageThrow("IMAGE_B2_ICONANIM4");
		IMAGE_B2_ICONANIM5 = aMgr.GetImageThrow("IMAGE_B2_ICONANIM5");
		IMAGE_B2_ICONANIM6 = aMgr.GetImageThrow("IMAGE_B2_ICONANIM6");
		IMAGE_B2_ICONANIM7 = aMgr.GetImageThrow("IMAGE_B2_ICONANIM7");
		IMAGE_B2_ICONANIM8 = aMgr.GetImageThrow("IMAGE_B2_ICONANIM8");
		IMAGE_B2_ICONANIM9 = aMgr.GetImageThrow("IMAGE_B2_ICONANIM9");
		IMAGE_B2_ICONMASK1 = aMgr.GetImageThrow("IMAGE_B2_ICONMASK1");
		IMAGE_B2_ICONMASK10 = aMgr.GetImageThrow("IMAGE_B2_ICONMASK10");
		IMAGE_B2_ICONMASK2 = aMgr.GetImageThrow("IMAGE_B2_ICONMASK2");
		IMAGE_B2_ICONMASK3 = aMgr.GetImageThrow("IMAGE_B2_ICONMASK3");
		IMAGE_B2_ICONMASK4 = aMgr.GetImageThrow("IMAGE_B2_ICONMASK4");
		IMAGE_B2_ICONMASK5 = aMgr.GetImageThrow("IMAGE_B2_ICONMASK5");
		IMAGE_B2_ICONMASK6 = aMgr.GetImageThrow("IMAGE_B2_ICONMASK6");
		IMAGE_B2_ICONMASK7 = aMgr.GetImageThrow("IMAGE_B2_ICONMASK7");
		IMAGE_B2_ICONMASK8 = aMgr.GetImageThrow("IMAGE_B2_ICONMASK8");
		IMAGE_B2_ICONMASK9 = aMgr.GetImageThrow("IMAGE_B2_ICONMASK9");
		IMAGE_B2_MAP = aMgr.GetImageThrow("IMAGE_B2_MAP");
		IMAGE_B2_MAPSCREEN_BANNER = aMgr.GetImageThrow("IMAGE_B2_MAPSCREEN_BANNER");
		IMAGE_B2_MINIMAP_ICONS = aMgr.GetImageThrow("IMAGE_B2_MINIMAP_ICONS");
		IMAGE_TUT_PIC_MALADIN = aMgr.GetImageThrow("IMAGE_TUT_PIC_MALADIN");
		IMAGE_TUT_PIC_MURRAY = aMgr.GetImageThrow("IMAGE_TUT_PIC_MURRAY");
		IMAGE_TUT_PIC_SCHE1 = aMgr.GetImageThrow("IMAGE_TUT_PIC_SCHE1");
		IMAGE_TUT_PIC_SCHE2 = aMgr.GetImageThrow("IMAGE_TUT_PIC_SCHE2");
		IMAGE_TUT_PIC_SINBAD = aMgr.GetImageThrow("IMAGE_TUT_PIC_SINBAD");
		IMAGE_TUT_PIC_VIZIER = aMgr.GetImageThrow("IMAGE_TUT_PIC_VIZIER");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

static void* gResources[] =
{
	&IMAGE_B2_MINIMAP_ICONS,
	&IMAGE_B2_MAPSCREEN_BANNER,
	&IMAGE_B2_ICONANIM1,
	&IMAGE_B2_ICONANIM2,
	&IMAGE_B2_ICONANIM3,
	&IMAGE_B2_ICONANIM4,
	&IMAGE_B2_ICONANIM5,
	&IMAGE_B2_ICONANIM6,
	&IMAGE_B2_ICONANIM7,
	&IMAGE_B2_ICONANIM8,
	&IMAGE_B2_ICONANIM9,
	&IMAGE_B2_ICONANIM10,
	&IMAGE_B2_ICONMASK1,
	&IMAGE_B2_ICONMASK2,
	&IMAGE_B2_ICONMASK3,
	&IMAGE_B2_ICONMASK4,
	&IMAGE_B2_ICONMASK5,
	&IMAGE_B2_ICONMASK6,
	&IMAGE_B2_ICONMASK7,
	&IMAGE_B2_ICONMASK8,
	&IMAGE_B2_ICONMASK9,
	&IMAGE_B2_ICONMASK10,
	&IMAGE_B2_MAP,
	&IMAGE_TUT_PIC_MURRAY,
	&IMAGE_TUT_PIC_SCHE1,
	&IMAGE_TUT_PIC_SCHE2,
	&IMAGE_TUT_PIC_SINBAD,
	&IMAGE_TUT_PIC_VIZIER,
	&IMAGE_TUT_PIC_MALADIN,
	&IMAGE_B2_LEFT_FACING_ARROW,
	&IMAGE_B2A_DOCKSKY,
	&SOUND_BOOK2_CH1_MALE1,
	&SOUND_BOOK2_CH1_MALE2,
	&SOUND_BOOK2_CH1_MALE3,
	&SOUND_BOOK2_CH1_MALE4,
	&SOUND_BOOK2_CH1_MALE5,
	&SOUND_BOOK2_CH1_MALE6,
	&SOUND_BOOK2_CH1_MALE7,
	&SOUND_BOOK2_CH1_MALE8,
	&SOUND_BOOK2_CH1_MALE9,
	&SOUND_BOOK2_CH1_FEMALE1,
	&SOUND_BOOK2_CH1_FEMALE2,
	&SOUND_BOOK2_CH1_IMPACT1,
	&SOUND_BOOK2_CH1_IMPACT2,
	&SOUND_BOOK2_CH1_IMPACT3,
	&SOUND_BOOK2_CH1_SPECIAL1,
	&SOUND_BOOK2_CH1_SPECIAL2,
	&IMAGE_B2A_BLACK3,
	&SOUND_BOOK2_CH2_MALE1,
	&SOUND_BOOK2_CH2_MALE2,
	&SOUND_BOOK2_CH2_MALE3,
	&SOUND_BOOK2_CH2_MALE4,
	&SOUND_BOOK2_CH2_MALE6,
	&SOUND_BOOK2_CH2_MALE7,
	&SOUND_BOOK2_CH2_MALE8,
	&SOUND_BOOK2_CH2_MALE9,
	&SOUND_BOOK2_CH2_MALE10,
	&SOUND_BOOK2_CH2_IMPACT1,
	&SOUND_BOOK2_CH2_IMPACT2,
	&SOUND_BOOK2_CH2_IMPACT4,
	&SOUND_BOOK2_CH2_SPECIAL3,
	&SOUND_BOOK2_CH2_DOG1,
	&SOUND_BOOK2_CH2_DOG2,
	&SOUND_BOOK2_CH2_DOG3,
	&SOUND_BOOK2_CH2_DOG4,
	&SOUND_BOOK2_CH2_LARGEIMPACT,
	&SOUND_BOOK2_CH2_WARP,
	&SOUND_BOOK2_CH2_KUBWA1,
	&SOUND_BOOK2_CH2_KUBWA2,
	&SOUND_BOOK2_CH2_KUBWA3,
	&SOUND_BOOK2_CH2_KUBWA4,
	&IMAGE_B2A_BLACK2,
	&SOUND_BOOK2_CH3_SQUEAL1,
	&SOUND_BOOK2_CH3_SQUEAL2,
	&SOUND_BOOK2_CH3_HISS,
	&SOUND_BOOK2_CH3_DRAGON1,
	&SOUND_BOOK2_CH3_DRAGON2,
	&SOUND_BOOK2_CH3_DRAGON3,
	&SOUND_BOOK2_CH3_DRAGON4,
	&SOUND_BOOK2_CH3_DOG1,
	&SOUND_BOOK2_CH3_DOG2,
	&SOUND_BOOK2_CH3_DOG3,
	&SOUND_BOOK2_CH3_DOG4,
	&SOUND_BOOK2_CH3_IMPACT1,
	&SOUND_BOOK2_CH3_IMPACT2,
	&SOUND_BOOK2_CH3_SPECIAL1,
	&SOUND_BOOK2_CH3_SPECIAL2,
	&SOUND_BOOK2_CH3_SPECIAL3,
	&SOUND_BOOK2_CH3_MALE1,
	&SOUND_BOOK2_CH3_MALE2,
	&SOUND_BOOK2_CH3_MALE3,
	&SOUND_BOOK2_CH3_MALE4,
	&IMAGE_B2A_PYRA_SKY,
	&IMAGE_B2_SPHINX_RIDDLE,
	&IMAGE_B2_SPHINX_BOSS_BATTLE,
	&SOUND_BOOK2_CH4_DEATH,
	&SOUND_BOOK2_CH4_ATTACK,
	&IMAGE_B2A_BLUE_SEA,
	&SOUND_BOOK2_CH5_DOG1,
	&SOUND_BOOK2_CH5_DOG2,
	&SOUND_BOOK2_CH5_DOG3,
	&SOUND_BOOK2_CH5_DOG4,
	&SOUND_BOOK2_CH5_HIT1,
	&SOUND_BOOK2_CH5_MALE1,
	&SOUND_BOOK2_CH5_MALE2,
	&SOUND_BOOK2_CH5_MALE3,
	&SOUND_BOOK2_CH5_MALE4,
	&SOUND_BOOK2_CH5_MALE5,
	&SOUND_BOOK2_CH5_MALE6,
	&SOUND_BOOK2_CH5_MALE7,
	&SOUND_BOOK2_CH5_MALE8,
	&SOUND_BOOK2_CH5_ATTACK1,
	&SOUND_BOOK2_CH5_ATTACK6,
	&IMAGE_B2A_BLUE_SEA2,
	&SOUND_BOOK2_CH6_SOUND1,
	&SOUND_BOOK2_CH6_SOUND3,
	&SOUND_BOOK2_CH6_SOUND4,
	&SOUND_BOOK2_CH6_SOUND6,
	&SOUND_BOOK2_CH6_SOUND7,
	&SOUND_BOOK2_CH6_SOUND8,
	&SOUND_BOOK2_CH6_SOUND9,
	&SOUND_BOOK2_CH6_SOUND10,
	&SOUND_BOOK2_CH6_SOUND11,
	&SOUND_BOOK2_CH6_SOUND12,
	&IMAGE_B2A_MIRAGE,
	&SOUND_BOOK2_CH7_SOUND1,
	&SOUND_BOOK2_CH7_SOUND2,
	&SOUND_BOOK2_CH7_SOUND4,
	&SOUND_BOOK2_CH7_SOUND5,
	&SOUND_BOOK2_CH7_SOUND6,
	&SOUND_BOOK2_CH7_SOUND12,
	&SOUND_BOOK2_CH7_SOUND13,
	&SOUND_BOOK2_CH7_SOUND15,
	&SOUND_BOOK2_CH7_SOUND16,
	&SOUND_BOOK2_CH7_SOUND17,
	&SOUND_BOOK2_CH7_SOUND18,
	&IMAGE_B2A_SKY8,
	&SOUND_BOOK2_CH8_SOUND1,
	&SOUND_BOOK2_CH8_SOUND2,
	&SOUND_BOOK2_CH8_SOUND3,
	&SOUND_BOOK2_CH8_SOUND4,
	&SOUND_BOOK2_CH8_SOUND5,
	&SOUND_BOOK2_CH8_SOUND7,
	&SOUND_BOOK2_CH8_SOUND8,
	&SOUND_BOOK2_CH8_SOUND9,
	&SOUND_BOOK2_CH8_SOUND10,
	&SOUND_BOOK2_CH8_SOUND12,
	&SOUND_BOOK2_CH8_SOUND13,
	&SOUND_BOOK2_CH8_SOUND14,
	&SOUND_BOOK2_CH8_SOUND15,
	&SOUND_BOOK2_CH8_SOUND16,
	&SOUND_BOOK2_CH8_SOUND18,
	&IMAGE_B2A_SKY9,
	&SOUND_BOOK2_CH9_SOUND1,
	&SOUND_BOOK2_CH9_SOUND2,
	&SOUND_BOOK2_CH9_SOUND3,
	&SOUND_BOOK2_CH9_SOUND4,
	&SOUND_BOOK2_CH9_SOUND5,
	&SOUND_BOOK2_CH9_SOUND7,
	&SOUND_BOOK2_CH9_SOUND8,
	&SOUND_BOOK2_CH9_SOUND12,
	&SOUND_BOOK2_CH9_SOUND13,
	&SOUND_BOOK2_CH9_SOUND15,
	&IMAGE_B2A_SUNSET,
	&SOUND_BOOK2_CH10_SOUND1,
	&SOUND_BOOK2_CH10_SOUND2,
	&SOUND_BOOK2_CH10_SOUND4,
	&SOUND_BOOK2_CH10_SOUND5,
	&SOUND_BOOK2_CH10_SOUND6,
	&SOUND_BOOK2_CH10_SOUND8,
	&SOUND_BOOK2_CH10_SOUND10,
	&SOUND_BOOK2_CH10_SOUND12,
	&SOUND_BOOK2_CH10_SOUND13,
	&SOUND_BOOK2_CH10_SOUND14,
	NULL
};

Image* Sexy::LoadImageById(ResourceManager *theManager, int theId)
{
	return (*((Image**)gResources[theId]) = theManager->LoadImage(GetStringIdById(theId)));
}

void Sexy::ReplaceImageById(ResourceManager *theManager, int theId, Image *theImage)
{
	theManager->ReplaceImage(GetStringIdById(theId),theImage);
	*(Image**)gResources[theId] = theImage;
}

Image* Sexy::GetImageById(int theId)
{
	return *(Image**)gResources[theId];
}

Font* Sexy::GetFontById(int theId)
{
	return *(Font**)gResources[theId];
}

int Sexy::GetSoundById(int theId)
{
	return *(int*)gResources[theId];
}

Image*& Sexy::GetImageRefById(int theId)
{
	return *(Image**)gResources[theId];
}

Font*& Sexy::GetFontRefById(int theId)
{
	return *(Font**)gResources[theId];
}

int& Sexy::GetSoundRefById(int theId)
{
	return *(int*)gResources[theId];
}

static Sexy::ResourceId GetIdByVariable(const void *theVariable)
{
	typedef std::map<int,int> MyMap;
	static MyMap aMap;
	if(gNeedRecalcVariableToIdMap)
	{
		gNeedRecalcVariableToIdMap = false;
		aMap.clear();
		for(int i=0; i<RESOURCE_ID_MAX; i++)
			aMap[*(int*)gResources[i]] = i;
	}

	MyMap::iterator anItr = aMap.find((int)theVariable);
	if (anItr == aMap.end())
		return RESOURCE_ID_MAX;
	else
		return (ResourceId) anItr->second;
}

Sexy::ResourceId Sexy::GetIdByImage(Image *theImage)
{
	return GetIdByVariable(theImage);
}

Sexy::ResourceId Sexy::GetIdByFont(Font *theFont)
{
	return GetIdByVariable(theFont);
}

Sexy::ResourceId Sexy::GetIdBySound(int theSound)
{
	return GetIdByVariable((void*)theSound);
}

const char* Sexy::GetStringIdById(int theId)
{
	switch(theId)
	{
		case IMAGE_B2_MINIMAP_ICONS_ID: return "IMAGE_B2_MINIMAP_ICONS";
		case IMAGE_B2_MAPSCREEN_BANNER_ID: return "IMAGE_B2_MAPSCREEN_BANNER";
		case IMAGE_B2_ICONANIM1_ID: return "IMAGE_B2_ICONANIM1";
		case IMAGE_B2_ICONANIM2_ID: return "IMAGE_B2_ICONANIM2";
		case IMAGE_B2_ICONANIM3_ID: return "IMAGE_B2_ICONANIM3";
		case IMAGE_B2_ICONANIM4_ID: return "IMAGE_B2_ICONANIM4";
		case IMAGE_B2_ICONANIM5_ID: return "IMAGE_B2_ICONANIM5";
		case IMAGE_B2_ICONANIM6_ID: return "IMAGE_B2_ICONANIM6";
		case IMAGE_B2_ICONANIM7_ID: return "IMAGE_B2_ICONANIM7";
		case IMAGE_B2_ICONANIM8_ID: return "IMAGE_B2_ICONANIM8";
		case IMAGE_B2_ICONANIM9_ID: return "IMAGE_B2_ICONANIM9";
		case IMAGE_B2_ICONANIM10_ID: return "IMAGE_B2_ICONANIM10";
		case IMAGE_B2_ICONMASK1_ID: return "IMAGE_B2_ICONMASK1";
		case IMAGE_B2_ICONMASK2_ID: return "IMAGE_B2_ICONMASK2";
		case IMAGE_B2_ICONMASK3_ID: return "IMAGE_B2_ICONMASK3";
		case IMAGE_B2_ICONMASK4_ID: return "IMAGE_B2_ICONMASK4";
		case IMAGE_B2_ICONMASK5_ID: return "IMAGE_B2_ICONMASK5";
		case IMAGE_B2_ICONMASK6_ID: return "IMAGE_B2_ICONMASK6";
		case IMAGE_B2_ICONMASK7_ID: return "IMAGE_B2_ICONMASK7";
		case IMAGE_B2_ICONMASK8_ID: return "IMAGE_B2_ICONMASK8";
		case IMAGE_B2_ICONMASK9_ID: return "IMAGE_B2_ICONMASK9";
		case IMAGE_B2_ICONMASK10_ID: return "IMAGE_B2_ICONMASK10";
		case IMAGE_B2_MAP_ID: return "IMAGE_B2_MAP";
		case IMAGE_TUT_PIC_MURRAY_ID: return "IMAGE_TUT_PIC_MURRAY";
		case IMAGE_TUT_PIC_SCHE1_ID: return "IMAGE_TUT_PIC_SCHE1";
		case IMAGE_TUT_PIC_SCHE2_ID: return "IMAGE_TUT_PIC_SCHE2";
		case IMAGE_TUT_PIC_SINBAD_ID: return "IMAGE_TUT_PIC_SINBAD";
		case IMAGE_TUT_PIC_VIZIER_ID: return "IMAGE_TUT_PIC_VIZIER";
		case IMAGE_TUT_PIC_MALADIN_ID: return "IMAGE_TUT_PIC_MALADIN";
		case IMAGE_B2_LEFT_FACING_ARROW_ID: return "IMAGE_B2_LEFT_FACING_ARROW";
		case IMAGE_B2A_DOCKSKY_ID: return "IMAGE_B2A_DOCKSKY";
		case SOUND_BOOK2_CH1_MALE1_ID: return "SOUND_BOOK2_CH1_MALE1";
		case SOUND_BOOK2_CH1_MALE2_ID: return "SOUND_BOOK2_CH1_MALE2";
		case SOUND_BOOK2_CH1_MALE3_ID: return "SOUND_BOOK2_CH1_MALE3";
		case SOUND_BOOK2_CH1_MALE4_ID: return "SOUND_BOOK2_CH1_MALE4";
		case SOUND_BOOK2_CH1_MALE5_ID: return "SOUND_BOOK2_CH1_MALE5";
		case SOUND_BOOK2_CH1_MALE6_ID: return "SOUND_BOOK2_CH1_MALE6";
		case SOUND_BOOK2_CH1_MALE7_ID: return "SOUND_BOOK2_CH1_MALE7";
		case SOUND_BOOK2_CH1_MALE8_ID: return "SOUND_BOOK2_CH1_MALE8";
		case SOUND_BOOK2_CH1_MALE9_ID: return "SOUND_BOOK2_CH1_MALE9";
		case SOUND_BOOK2_CH1_FEMALE1_ID: return "SOUND_BOOK2_CH1_FEMALE1";
		case SOUND_BOOK2_CH1_FEMALE2_ID: return "SOUND_BOOK2_CH1_FEMALE2";
		case SOUND_BOOK2_CH1_IMPACT1_ID: return "SOUND_BOOK2_CH1_IMPACT1";
		case SOUND_BOOK2_CH1_IMPACT2_ID: return "SOUND_BOOK2_CH1_IMPACT2";
		case SOUND_BOOK2_CH1_IMPACT3_ID: return "SOUND_BOOK2_CH1_IMPACT3";
		case SOUND_BOOK2_CH1_SPECIAL1_ID: return "SOUND_BOOK2_CH1_SPECIAL1";
		case SOUND_BOOK2_CH1_SPECIAL2_ID: return "SOUND_BOOK2_CH1_SPECIAL2";
		case IMAGE_B2A_BLACK3_ID: return "IMAGE_B2A_BLACK3";
		case SOUND_BOOK2_CH2_MALE1_ID: return "SOUND_BOOK2_CH2_MALE1";
		case SOUND_BOOK2_CH2_MALE2_ID: return "SOUND_BOOK2_CH2_MALE2";
		case SOUND_BOOK2_CH2_MALE3_ID: return "SOUND_BOOK2_CH2_MALE3";
		case SOUND_BOOK2_CH2_MALE4_ID: return "SOUND_BOOK2_CH2_MALE4";
		case SOUND_BOOK2_CH2_MALE6_ID: return "SOUND_BOOK2_CH2_MALE6";
		case SOUND_BOOK2_CH2_MALE7_ID: return "SOUND_BOOK2_CH2_MALE7";
		case SOUND_BOOK2_CH2_MALE8_ID: return "SOUND_BOOK2_CH2_MALE8";
		case SOUND_BOOK2_CH2_MALE9_ID: return "SOUND_BOOK2_CH2_MALE9";
		case SOUND_BOOK2_CH2_MALE10_ID: return "SOUND_BOOK2_CH2_MALE10";
		case SOUND_BOOK2_CH2_IMPACT1_ID: return "SOUND_BOOK2_CH2_IMPACT1";
		case SOUND_BOOK2_CH2_IMPACT2_ID: return "SOUND_BOOK2_CH2_IMPACT2";
		case SOUND_BOOK2_CH2_IMPACT4_ID: return "SOUND_BOOK2_CH2_IMPACT4";
		case SOUND_BOOK2_CH2_SPECIAL3_ID: return "SOUND_BOOK2_CH2_SPECIAL3";
		case SOUND_BOOK2_CH2_DOG1_ID: return "SOUND_BOOK2_CH2_DOG1";
		case SOUND_BOOK2_CH2_DOG2_ID: return "SOUND_BOOK2_CH2_DOG2";
		case SOUND_BOOK2_CH2_DOG3_ID: return "SOUND_BOOK2_CH2_DOG3";
		case SOUND_BOOK2_CH2_DOG4_ID: return "SOUND_BOOK2_CH2_DOG4";
		case SOUND_BOOK2_CH2_LARGEIMPACT_ID: return "SOUND_BOOK2_CH2_LARGEIMPACT";
		case SOUND_BOOK2_CH2_WARP_ID: return "SOUND_BOOK2_CH2_WARP";
		case SOUND_BOOK2_CH2_KUBWA1_ID: return "SOUND_BOOK2_CH2_KUBWA1";
		case SOUND_BOOK2_CH2_KUBWA2_ID: return "SOUND_BOOK2_CH2_KUBWA2";
		case SOUND_BOOK2_CH2_KUBWA3_ID: return "SOUND_BOOK2_CH2_KUBWA3";
		case SOUND_BOOK2_CH2_KUBWA4_ID: return "SOUND_BOOK2_CH2_KUBWA4";
		case IMAGE_B2A_BLACK2_ID: return "IMAGE_B2A_BLACK2";
		case SOUND_BOOK2_CH3_SQUEAL1_ID: return "SOUND_BOOK2_CH3_SQUEAL1";
		case SOUND_BOOK2_CH3_SQUEAL2_ID: return "SOUND_BOOK2_CH3_SQUEAL2";
		case SOUND_BOOK2_CH3_HISS_ID: return "SOUND_BOOK2_CH3_HISS";
		case SOUND_BOOK2_CH3_DRAGON1_ID: return "SOUND_BOOK2_CH3_DRAGON1";
		case SOUND_BOOK2_CH3_DRAGON2_ID: return "SOUND_BOOK2_CH3_DRAGON2";
		case SOUND_BOOK2_CH3_DRAGON3_ID: return "SOUND_BOOK2_CH3_DRAGON3";
		case SOUND_BOOK2_CH3_DRAGON4_ID: return "SOUND_BOOK2_CH3_DRAGON4";
		case SOUND_BOOK2_CH3_DOG1_ID: return "SOUND_BOOK2_CH3_DOG1";
		case SOUND_BOOK2_CH3_DOG2_ID: return "SOUND_BOOK2_CH3_DOG2";
		case SOUND_BOOK2_CH3_DOG3_ID: return "SOUND_BOOK2_CH3_DOG3";
		case SOUND_BOOK2_CH3_DOG4_ID: return "SOUND_BOOK2_CH3_DOG4";
		case SOUND_BOOK2_CH3_IMPACT1_ID: return "SOUND_BOOK2_CH3_IMPACT1";
		case SOUND_BOOK2_CH3_IMPACT2_ID: return "SOUND_BOOK2_CH3_IMPACT2";
		case SOUND_BOOK2_CH3_SPECIAL1_ID: return "SOUND_BOOK2_CH3_SPECIAL1";
		case SOUND_BOOK2_CH3_SPECIAL2_ID: return "SOUND_BOOK2_CH3_SPECIAL2";
		case SOUND_BOOK2_CH3_SPECIAL3_ID: return "SOUND_BOOK2_CH3_SPECIAL3";
		case SOUND_BOOK2_CH3_MALE1_ID: return "SOUND_BOOK2_CH3_MALE1";
		case SOUND_BOOK2_CH3_MALE2_ID: return "SOUND_BOOK2_CH3_MALE2";
		case SOUND_BOOK2_CH3_MALE3_ID: return "SOUND_BOOK2_CH3_MALE3";
		case SOUND_BOOK2_CH3_MALE4_ID: return "SOUND_BOOK2_CH3_MALE4";
		case IMAGE_B2A_PYRA_SKY_ID: return "IMAGE_B2A_PYRA_SKY";
		case IMAGE_B2_SPHINX_RIDDLE_ID: return "IMAGE_B2_SPHINX_RIDDLE";
		case IMAGE_B2_SPHINX_BOSS_BATTLE_ID: return "IMAGE_B2_SPHINX_BOSS_BATTLE";
		case SOUND_BOOK2_CH4_DEATH_ID: return "SOUND_BOOK2_CH4_DEATH";
		case SOUND_BOOK2_CH4_ATTACK_ID: return "SOUND_BOOK2_CH4_ATTACK";
		case IMAGE_B2A_BLUE_SEA_ID: return "IMAGE_B2A_BLUE_SEA";
		case SOUND_BOOK2_CH5_DOG1_ID: return "SOUND_BOOK2_CH5_DOG1";
		case SOUND_BOOK2_CH5_DOG2_ID: return "SOUND_BOOK2_CH5_DOG2";
		case SOUND_BOOK2_CH5_DOG3_ID: return "SOUND_BOOK2_CH5_DOG3";
		case SOUND_BOOK2_CH5_DOG4_ID: return "SOUND_BOOK2_CH5_DOG4";
		case SOUND_BOOK2_CH5_HIT1_ID: return "SOUND_BOOK2_CH5_HIT1";
		case SOUND_BOOK2_CH5_MALE1_ID: return "SOUND_BOOK2_CH5_MALE1";
		case SOUND_BOOK2_CH5_MALE2_ID: return "SOUND_BOOK2_CH5_MALE2";
		case SOUND_BOOK2_CH5_MALE3_ID: return "SOUND_BOOK2_CH5_MALE3";
		case SOUND_BOOK2_CH5_MALE4_ID: return "SOUND_BOOK2_CH5_MALE4";
		case SOUND_BOOK2_CH5_MALE5_ID: return "SOUND_BOOK2_CH5_MALE5";
		case SOUND_BOOK2_CH5_MALE6_ID: return "SOUND_BOOK2_CH5_MALE6";
		case SOUND_BOOK2_CH5_MALE7_ID: return "SOUND_BOOK2_CH5_MALE7";
		case SOUND_BOOK2_CH5_MALE8_ID: return "SOUND_BOOK2_CH5_MALE8";
		case SOUND_BOOK2_CH5_ATTACK1_ID: return "SOUND_BOOK2_CH5_ATTACK1";
		case SOUND_BOOK2_CH5_ATTACK6_ID: return "SOUND_BOOK2_CH5_ATTACK6";
		case IMAGE_B2A_BLUE_SEA2_ID: return "IMAGE_B2A_BLUE_SEA2";
		case SOUND_BOOK2_CH6_SOUND1_ID: return "SOUND_BOOK2_CH6_SOUND1";
		case SOUND_BOOK2_CH6_SOUND3_ID: return "SOUND_BOOK2_CH6_SOUND3";
		case SOUND_BOOK2_CH6_SOUND4_ID: return "SOUND_BOOK2_CH6_SOUND4";
		case SOUND_BOOK2_CH6_SOUND6_ID: return "SOUND_BOOK2_CH6_SOUND6";
		case SOUND_BOOK2_CH6_SOUND7_ID: return "SOUND_BOOK2_CH6_SOUND7";
		case SOUND_BOOK2_CH6_SOUND8_ID: return "SOUND_BOOK2_CH6_SOUND8";
		case SOUND_BOOK2_CH6_SOUND9_ID: return "SOUND_BOOK2_CH6_SOUND9";
		case SOUND_BOOK2_CH6_SOUND10_ID: return "SOUND_BOOK2_CH6_SOUND10";
		case SOUND_BOOK2_CH6_SOUND11_ID: return "SOUND_BOOK2_CH6_SOUND11";
		case SOUND_BOOK2_CH6_SOUND12_ID: return "SOUND_BOOK2_CH6_SOUND12";
		case IMAGE_B2A_MIRAGE_ID: return "IMAGE_B2A_MIRAGE";
		case SOUND_BOOK2_CH7_SOUND1_ID: return "SOUND_BOOK2_CH7_SOUND1";
		case SOUND_BOOK2_CH7_SOUND2_ID: return "SOUND_BOOK2_CH7_SOUND2";
		case SOUND_BOOK2_CH7_SOUND4_ID: return "SOUND_BOOK2_CH7_SOUND4";
		case SOUND_BOOK2_CH7_SOUND5_ID: return "SOUND_BOOK2_CH7_SOUND5";
		case SOUND_BOOK2_CH7_SOUND6_ID: return "SOUND_BOOK2_CH7_SOUND6";
		case SOUND_BOOK2_CH7_SOUND12_ID: return "SOUND_BOOK2_CH7_SOUND12";
		case SOUND_BOOK2_CH7_SOUND13_ID: return "SOUND_BOOK2_CH7_SOUND13";
		case SOUND_BOOK2_CH7_SOUND15_ID: return "SOUND_BOOK2_CH7_SOUND15";
		case SOUND_BOOK2_CH7_SOUND16_ID: return "SOUND_BOOK2_CH7_SOUND16";
		case SOUND_BOOK2_CH7_SOUND17_ID: return "SOUND_BOOK2_CH7_SOUND17";
		case SOUND_BOOK2_CH7_SOUND18_ID: return "SOUND_BOOK2_CH7_SOUND18";
		case IMAGE_B2A_SKY8_ID: return "IMAGE_B2A_SKY8";
		case SOUND_BOOK2_CH8_SOUND1_ID: return "SOUND_BOOK2_CH8_SOUND1";
		case SOUND_BOOK2_CH8_SOUND2_ID: return "SOUND_BOOK2_CH8_SOUND2";
		case SOUND_BOOK2_CH8_SOUND3_ID: return "SOUND_BOOK2_CH8_SOUND3";
		case SOUND_BOOK2_CH8_SOUND4_ID: return "SOUND_BOOK2_CH8_SOUND4";
		case SOUND_BOOK2_CH8_SOUND5_ID: return "SOUND_BOOK2_CH8_SOUND5";
		case SOUND_BOOK2_CH8_SOUND7_ID: return "SOUND_BOOK2_CH8_SOUND7";
		case SOUND_BOOK2_CH8_SOUND8_ID: return "SOUND_BOOK2_CH8_SOUND8";
		case SOUND_BOOK2_CH8_SOUND9_ID: return "SOUND_BOOK2_CH8_SOUND9";
		case SOUND_BOOK2_CH8_SOUND10_ID: return "SOUND_BOOK2_CH8_SOUND10";
		case SOUND_BOOK2_CH8_SOUND12_ID: return "SOUND_BOOK2_CH8_SOUND12";
		case SOUND_BOOK2_CH8_SOUND13_ID: return "SOUND_BOOK2_CH8_SOUND13";
		case SOUND_BOOK2_CH8_SOUND14_ID: return "SOUND_BOOK2_CH8_SOUND14";
		case SOUND_BOOK2_CH8_SOUND15_ID: return "SOUND_BOOK2_CH8_SOUND15";
		case SOUND_BOOK2_CH8_SOUND16_ID: return "SOUND_BOOK2_CH8_SOUND16";
		case SOUND_BOOK2_CH8_SOUND18_ID: return "SOUND_BOOK2_CH8_SOUND18";
		case IMAGE_B2A_SKY9_ID: return "IMAGE_B2A_SKY9";
		case SOUND_BOOK2_CH9_SOUND1_ID: return "SOUND_BOOK2_CH9_SOUND1";
		case SOUND_BOOK2_CH9_SOUND2_ID: return "SOUND_BOOK2_CH9_SOUND2";
		case SOUND_BOOK2_CH9_SOUND3_ID: return "SOUND_BOOK2_CH9_SOUND3";
		case SOUND_BOOK2_CH9_SOUND4_ID: return "SOUND_BOOK2_CH9_SOUND4";
		case SOUND_BOOK2_CH9_SOUND5_ID: return "SOUND_BOOK2_CH9_SOUND5";
		case SOUND_BOOK2_CH9_SOUND7_ID: return "SOUND_BOOK2_CH9_SOUND7";
		case SOUND_BOOK2_CH9_SOUND8_ID: return "SOUND_BOOK2_CH9_SOUND8";
		case SOUND_BOOK2_CH9_SOUND12_ID: return "SOUND_BOOK2_CH9_SOUND12";
		case SOUND_BOOK2_CH9_SOUND13_ID: return "SOUND_BOOK2_CH9_SOUND13";
		case SOUND_BOOK2_CH9_SOUND15_ID: return "SOUND_BOOK2_CH9_SOUND15";
		case IMAGE_B2A_SUNSET_ID: return "IMAGE_B2A_SUNSET";
		case SOUND_BOOK2_CH10_SOUND1_ID: return "SOUND_BOOK2_CH10_SOUND1";
		case SOUND_BOOK2_CH10_SOUND2_ID: return "SOUND_BOOK2_CH10_SOUND2";
		case SOUND_BOOK2_CH10_SOUND4_ID: return "SOUND_BOOK2_CH10_SOUND4";
		case SOUND_BOOK2_CH10_SOUND5_ID: return "SOUND_BOOK2_CH10_SOUND5";
		case SOUND_BOOK2_CH10_SOUND6_ID: return "SOUND_BOOK2_CH10_SOUND6";
		case SOUND_BOOK2_CH10_SOUND8_ID: return "SOUND_BOOK2_CH10_SOUND8";
		case SOUND_BOOK2_CH10_SOUND10_ID: return "SOUND_BOOK2_CH10_SOUND10";
		case SOUND_BOOK2_CH10_SOUND12_ID: return "SOUND_BOOK2_CH10_SOUND12";
		case SOUND_BOOK2_CH10_SOUND13_ID: return "SOUND_BOOK2_CH10_SOUND13";
		case SOUND_BOOK2_CH10_SOUND14_ID: return "SOUND_BOOK2_CH10_SOUND14";
		default: return "";
	}
}

