#include "Res.h"
#include "SexyAppFramework/ResourceManager.h"

using namespace Sexy;

#pragma warning(disable:4311 4312)

static bool gNeedRecalcVariableToIdMap = false;

bool Sexy::ExtractResourcesByName(ResourceManager *theManager, const char *theName)
{
	if (strcmp(theName,"CommonGame")==0) return ExtractCommonGameResources(theManager);
	if (strcmp(theName,"Credits")==0) return ExtractCreditsResources(theManager);
	if (strcmp(theName,"HallOfFame")==0) return ExtractHallOfFameResources(theManager);
	if (strcmp(theName,"Init")==0) return ExtractInitResources(theManager);
	if (strcmp(theName,"MiniGameCommon")==0) return ExtractMiniGameCommonResources(theManager);
	if (strcmp(theName,"MiniGameMenu")==0) return ExtractMiniGameMenuResources(theManager);
	if (strcmp(theName,"StatsBook")==0) return ExtractStatsBookResources(theManager);
	if (strcmp(theName,"TitleAndMM")==0) return ExtractTitleAndMMResources(theManager);
	if (strcmp(theName,"UpsellTrailer")==0) return ExtractUpsellTrailerResources(theManager);
	return false;
}

Sexy::ResourceId Sexy::GetIdByStringId(const char *theStringId)
{
	typedef std::map<std::string,int> MyMap;
	static MyMap aMap;
	if(aMap.empty())
	{
		for(int i=0; i<RESOURCE_ID_MAX; i++)
			aMap[GetStringIdById(i)] = i;
	}

	MyMap::iterator anItr = aMap.find(theStringId);
	if (anItr == aMap.end())
		return RESOURCE_ID_MAX;
	else
		return (ResourceId) anItr->second;
}

// CommonGame Resources
Image* Sexy::IMAGE_ALTAR;
Image* Sexy::IMAGE_ALTAR_BUBBLE;
Image* Sexy::IMAGE_ALTAR_GLOW1;
Image* Sexy::IMAGE_ALTAR_GLOW2;
Image* Sexy::IMAGE_ALTAR_GLOW3;
Image* Sexy::IMAGE_BANNER_LARGE;
Image* Sexy::IMAGE_BANNER_SMALL;
Image* Sexy::IMAGE_BLUE_SPARKLE;
Image* Sexy::IMAGE_BOOKSHELF_LEFT;
Image* Sexy::IMAGE_BOOKSHELF_RIGHT;
Image* Sexy::IMAGE_BOSS_BANNER;
Image* Sexy::IMAGE_BOSS_TEXT;
Image* Sexy::IMAGE_BURNING_RESISTED;
Image* Sexy::IMAGE_BUTTON_ATTACK;
Image* Sexy::IMAGE_BUTTON_MENU;
Image* Sexy::IMAGE_BUTTON_SCRAMBLE;
Image* Sexy::IMAGE_BUTTON_SCRAMBLE_SHADOW;
Image* Sexy::IMAGE_COMBAT_UI_BOTTOM1;
Image* Sexy::IMAGE_COMBAT_UI_BOTTOM2;
Image* Sexy::IMAGE_COMBAT_UI_TOP;
Image* Sexy::IMAGE_CUTSCENE_BOTTOM;
Image* Sexy::IMAGE_CUTSCENE_TOP;
Image* Sexy::IMAGE_GRAVESTONE;
Image* Sexy::IMAGE_GRAVESTONE_GLOW;
Image* Sexy::IMAGE_GRAVESTONE_SMOKE;
Image* Sexy::IMAGE_GRAYBAR_BG;
Image* Sexy::IMAGE_GS_GO;
Image* Sexy::IMAGE_GS_SHIP1;
Image* Sexy::IMAGE_GS_SHIP1_WARPJET;
Image* Sexy::IMAGE_GS_SHIP2;
Image* Sexy::IMAGE_GS_SHIP3;
Image* Sexy::IMAGE_GS_SHIP4;
Image* Sexy::IMAGE_HEARTBLINK;
Image* Sexy::IMAGE_HEARTBLINK_CC;
Image* Sexy::IMAGE_HEARTS;
Image* Sexy::IMAGE_HEARTS_BG;
Image* Sexy::IMAGE_HEARTS_CC;
Image* Sexy::IMAGE_HEART_BITS;
Image* Sexy::IMAGE_HEART_MASK;
Image* Sexy::IMAGE_HEART_MASK_CC;
Image* Sexy::IMAGE_HINT_ARROW_BOX;
Image* Sexy::IMAGE_HINT_ARROW_DOWN;
Image* Sexy::IMAGE_HINT_ARROW_DOWNX;
Image* Sexy::IMAGE_HINT_ARROW_GLOW_ADD;
Image* Sexy::IMAGE_HINT_ARROW_LEFT;
Image* Sexy::IMAGE_HINT_ARROW_LEFTX;
Image* Sexy::IMAGE_HINT_ARROW_RIGHT;
Image* Sexy::IMAGE_HINT_ARROW_RIGHTX;
Image* Sexy::IMAGE_HINT_ARROW_TITLE;
Image* Sexy::IMAGE_HINT_ARROW_UP;
Image* Sexy::IMAGE_HINT_ARROW_UPX;
Image* Sexy::IMAGE_IMPACT_LARGE;
Image* Sexy::IMAGE_IMPACT_SMALL;
Image* Sexy::IMAGE_ITEM_ATTACK;
Image* Sexy::IMAGE_ITEM_ATTACK_NB;
Image* Sexy::IMAGE_ITEM_HEALTH;
Image* Sexy::IMAGE_ITEM_HEALTH_NB;
Image* Sexy::IMAGE_ITEM_PURIFY;
Image* Sexy::IMAGE_ITEM_PURIFY_NB;
Image* Sexy::IMAGE_LEVELUP_BANNER;
Image* Sexy::IMAGE_LEVELUP_ICONS;
Image* Sexy::IMAGE_LEVELUP_SPARKLE;
Image* Sexy::IMAGE_LEVELUP_STAR;
Image* Sexy::IMAGE_LEVELUP_TEXT;
Image* Sexy::IMAGE_LEVELUP_TROPHY;
Image* Sexy::IMAGE_LEVELUP_TROPHY_GLOW;
Image* Sexy::IMAGE_LEVELUP_TROPHY_PARTICLES;
Image* Sexy::IMAGE_LEVELUP_WATERMARK;
Image* Sexy::IMAGE_LEX_ICON;
Image* Sexy::IMAGE_LIBRARY_TITLE;
Image* Sexy::IMAGE_LORE_PLATE;
Image* Sexy::IMAGE_LORE_PLATE_LIT;
Image* Sexy::IMAGE_LORE_PLATE_TILABLE;
Image* Sexy::IMAGE_LOW_HEALTH_OUTLINE;
Image* Sexy::IMAGE_MAP_BOOK2;
Image* Sexy::IMAGE_MAP_CHECK;
Image* Sexy::IMAGE_MAP_LEX_WARP;
Image* Sexy::IMAGE_MAP_MINIGAME_ANIM;
Image* Sexy::IMAGE_MINIGAME_ICON;
Image* Sexy::IMAGE_OVERKILL_ANNIHILATED;
Image* Sexy::IMAGE_OVERKILL_CRUSHED;
Image* Sexy::IMAGE_OVERKILL_DECIMATED;
Image* Sexy::IMAGE_OVERKILL_DESTROYED;
Image* Sexy::IMAGE_OVERKILL_OBLITERATED;
Image* Sexy::IMAGE_OVERKILL_ROUTED;
Image* Sexy::IMAGE_OVERKILL_VANQUISHED;
Image* Sexy::IMAGE_OVERKILL_WHOMPED;
Image* Sexy::IMAGE_PAUSED_BANNER;
Image* Sexy::IMAGE_PETRIFY_RESISTED;
Image* Sexy::IMAGE_POISON_RESISTED;
Image* Sexy::IMAGE_POTION_PEDESTAL;
Image* Sexy::IMAGE_POWER_DOWN;
Image* Sexy::IMAGE_PROGRESS_METER;
Image* Sexy::IMAGE_RED_SPARKLE;
Image* Sexy::IMAGE_STATS_BOX;
Image* Sexy::IMAGE_STATUE_CODEX;
Image* Sexy::IMAGE_STATUE_LEX;
Image* Sexy::IMAGE_STATUSTEXT_BLEEDING;
Image* Sexy::IMAGE_STATUSTEXT_BONUS_WORD;
Image* Sexy::IMAGE_STATUSTEXT_BURNING;
Image* Sexy::IMAGE_STATUSTEXT_FROZEN;
Image* Sexy::IMAGE_STATUSTEXT_PETRIFIED;
Image* Sexy::IMAGE_STATUSTEXT_POISONED;
Image* Sexy::IMAGE_STATUSTEXT_POWERDOWN;
Image* Sexy::IMAGE_STATUSTEXT_POWERUP;
Image* Sexy::IMAGE_STATUSTEXT_SHIELDED;
Image* Sexy::IMAGE_STATUSTEXT_STUNNED;
Image* Sexy::IMAGE_STATUS_ICONS;
Image* Sexy::IMAGE_STUN_RESISTED;
Image* Sexy::IMAGE_TILE_BASIC;
Image* Sexy::IMAGE_TILE_PIPS;
Image* Sexy::IMAGE_TMA_UI_TOP;
Image* Sexy::IMAGE_TM_BONUS_TEXT;
Image* Sexy::IMAGE_TM_INTRO_TITLE;
Image* Sexy::IMAGE_TM_LEVELUP_TOKEN;
Image* Sexy::IMAGE_TM_LEVELUP_TOKEN_GOLD;
Image* Sexy::IMAGE_TM_SPOTLIGHT;
Image* Sexy::IMAGE_TREASURE_BANNER;
Image* Sexy::IMAGE_TREASURE_BG;
Image* Sexy::IMAGE_TREASURE_BOX;
Image* Sexy::IMAGE_TREASURE_BULB;
Image* Sexy::IMAGE_TREASURE_HILIGHT;
Image* Sexy::IMAGE_TREASURE_HINT;
Image* Sexy::IMAGE_TREASURE_TEXTBOX;
Image* Sexy::IMAGE_TUT_ARROW;
Image* Sexy::IMAGE_TUT_CURTAIN_LEFT;
Image* Sexy::IMAGE_TUT_CURTAIN_RIGHT;
Image* Sexy::IMAGE_TUT_GRID_BOX;
Image* Sexy::IMAGE_TUT_MG_BUTTON;
Image* Sexy::IMAGE_TUT_PIC_CASS;
Image* Sexy::IMAGE_TUT_PIC_CASS_WORRY;
Image* Sexy::IMAGE_TUT_PIC_CIRCE;
Image* Sexy::IMAGE_TUT_PIC_CODEX;
Image* Sexy::IMAGE_TUT_PIC_HEPH;
Image* Sexy::IMAGE_TUT_PIC_LEX;
Image* Sexy::IMAGE_TUT_PIC_LEX_WORRY;
Image* Sexy::IMAGE_TUT_PIC_MOXIE;
Image* Sexy::IMAGE_TUT_PIC_NEMESIS;
Image* Sexy::IMAGE_TUT_PLAY_BLUR;
Image* Sexy::IMAGE_TUT_PLAY_DIAGRAM;
Image* Sexy::IMAGE_TUT_SCRAMBLE_BOX;
Image* Sexy::IMAGE_TUT_TITLE;
Image* Sexy::IMAGE_TUT_TREASURE_BLUR_BOX;
Image* Sexy::IMAGE_UI_BOOK_AVAILABLE;
Image* Sexy::IMAGE_UI_BOOK_BACK_BUTTON;
Image* Sexy::IMAGE_UI_BOOK_DOTS;
Image* Sexy::IMAGE_UI_BOOK_END_STATS_BOX;
Image* Sexy::IMAGE_UI_BOOK_END_STATS_TITLE;
Image* Sexy::IMAGE_UI_BOOK_ENTER_BUTTON;
Image* Sexy::IMAGE_UI_BOOK_HILIGHT;
Image* Sexy::IMAGE_UI_BOOK_OPTIONS_BUTTON;
Image* Sexy::IMAGE_UI_BOOK_TS_CONTINUE_BUTTON;
Image* Sexy::IMAGE_UI_BOTTOM;
Image* Sexy::IMAGE_UI_DESCRIPTION_BOX;
Image* Sexy::IMAGE_UI_LEFT;
Image* Sexy::IMAGE_UI_RIGHT;
Image* Sexy::IMAGE_UI_TOP;
Image* Sexy::IMAGE_WORDPOWER_GLOW_INNER_LEFT;
Image* Sexy::IMAGE_WORDPOWER_GLOW_INNER_MID;
Image* Sexy::IMAGE_WORDPOWER_GLOW_INNER_RIGHT;
Image* Sexy::IMAGE_WORDPOWER_GLOW_LEFT;
Image* Sexy::IMAGE_WORDPOWER_GLOW_LEFT_SMALL;
Image* Sexy::IMAGE_WORDPOWER_GLOW_MIDDLE;
Image* Sexy::IMAGE_WORDPOWER_GLOW_MIDDLE_SMALL;
Image* Sexy::IMAGE_WORDPOWER_GLOW_RIGHT;
Image* Sexy::IMAGE_WORDPOWER_GLOW_RIGHT_SMALL;
Image* Sexy::IMAGE_WORD_BUBBLE;
Image* Sexy::IMAGE_WORD_BUBBLE_DOWN_ARROW;
Image* Sexy::IMAGE_WORD_BUBBLE_LEFT;
Image* Sexy::IMAGE_WORD_BUBBLE_RIGHT;
Image* Sexy::IMAGE_WORD_BUBBLE_TEX;
Image* Sexy::IMAGE_WP_SPARKLE_MEDIUM;
Image* Sexy::IMAGE_WP_SPARKLE_SMALL;
Image* Sexy::IMAGE_WS_BESTWORD_TITLE;
Image* Sexy::IMAGE_WS_PAPER;
Image* Sexy::IMAGE_WS_SCROLL;
Image* Sexy::IMAGE_XPBAR_GLOW;
Image* Sexy::IMAGE_XP_BAR_EFFECT;
Image* Sexy::IMAGE_XP_BAR_EFFECT_WHITE;
Image* Sexy::IMAGE_XP_BAR_EMPTY;
Image* Sexy::IMAGE_XP_BAR_FULL;
int Sexy::SOUND_1;
int Sexy::SOUND_2;
int Sexy::SOUND_3;
int Sexy::SOUND_CHACHING;
int Sexy::SOUND_CLICK1;
int Sexy::SOUND_CLICK2;
int Sexy::SOUND_COUNT;
int Sexy::SOUND_CROWD_CHEER;
int Sexy::SOUND_EFFECT_FIRE;
int Sexy::SOUND_EFFECT_FROZEN;
int Sexy::SOUND_EFFECT_PETRIFY;
int Sexy::SOUND_EFFECT_POISON;
int Sexy::SOUND_EFFECT_WEAKEN;
int Sexy::SOUND_FIREWORK1;
int Sexy::SOUND_FIREWORK2;
int Sexy::SOUND_FREEZE;
int Sexy::SOUND_GEMSPAWN;
int Sexy::SOUND_GO;
int Sexy::SOUND_HEAL;
int Sexy::SOUND_IMPACT_LARGE;
int Sexy::SOUND_IMPACT_SMALL;
int Sexy::SOUND_LEX_ASTONISHING;
int Sexy::SOUND_LEX_ATTACK1;
int Sexy::SOUND_LEX_ATTACK4;
int Sexy::SOUND_LEX_ATTACK5;
int Sexy::SOUND_LEX_ATTACK6;
int Sexy::SOUND_LEX_ATTACK7;
int Sexy::SOUND_LEX_AUTOLOGICAL;
int Sexy::SOUND_LEX_AWESOME;
int Sexy::SOUND_LEX_BITE;
int Sexy::SOUND_LEX_BOSS_BATTLE;
int Sexy::SOUND_LEX_BURP;
int Sexy::SOUND_LEX_CASHMONEY;
int Sexy::SOUND_LEX_EXCELLENT;
int Sexy::SOUND_LEX_FANTASTIC;
int Sexy::SOUND_LEX_GIGGLE1;
int Sexy::SOUND_LEX_GIGGLE2;
int Sexy::SOUND_LEX_GOOD;
int Sexy::SOUND_LEX_ILOVEYOU;
int Sexy::SOUND_LEX_INCREDIBLE;
int Sexy::SOUND_LEX_LEVELUP;
int Sexy::SOUND_LEX_NICE;
int Sexy::SOUND_LEX_SHEEPBLEAT;
int Sexy::SOUND_LEX_SNEEZE;
int Sexy::SOUND_LEX_VERYGOOD;
int Sexy::SOUND_LEX_WARPIN;
int Sexy::SOUND_LEX_WARPOUT;
int Sexy::SOUND_LEX_WATCHOUT;
int Sexy::SOUND_LEX_WOW;
int Sexy::SOUND_LIGHTNING;
int Sexy::SOUND_LOW_HEALTH;
int Sexy::SOUND_MM_ADVENTURE;
int Sexy::SOUND_MM_ARENA;
int Sexy::SOUND_MM_BUY_NOW;
int Sexy::SOUND_MM_CNG;
int Sexy::SOUND_MM_DONTLEAVE;
int Sexy::SOUND_MM_HS;
int Sexy::SOUND_MM_MINIGAMES;
int Sexy::SOUND_MM_OPTIONS;
int Sexy::SOUND_MM_QUIT;
int Sexy::SOUND_MM_TOK;
int Sexy::SOUND_NEW_MINIGAME;
int Sexy::SOUND_NEW_TREASURE;
int Sexy::SOUND_OVERKILL_ANNIHILATED;
int Sexy::SOUND_OVERKILL_CRUSHED;
int Sexy::SOUND_OVERKILL_DECIMATED;
int Sexy::SOUND_OVERKILL_DESTROYED;
int Sexy::SOUND_OVERKILL_OBLITERATED;
int Sexy::SOUND_OVERKILL_ROUTED;
int Sexy::SOUND_OVERKILL_VANQUISHED;
int Sexy::SOUND_OVERKILL_WHOMPED;
int Sexy::SOUND_PETRIFY;
int Sexy::SOUND_PLAGUE;
int Sexy::SOUND_POISON;
int Sexy::SOUND_POTION_HEAL;
int Sexy::SOUND_POTION_PICKUP;
int Sexy::SOUND_POTION_POWERUP;
int Sexy::SOUND_POTION_PURIFY;
int Sexy::SOUND_POWERDOWN;
int Sexy::SOUND_POWERUP;
int Sexy::SOUND_SCRAMBLE;
int Sexy::SOUND_SLOWDOWN;
int Sexy::SOUND_STUN;
int Sexy::SOUND_SUBMIT_FAILED;
int Sexy::SOUND_TEXT_BLIP;
int Sexy::SOUND_TILELOCK;
int Sexy::SOUND_TILESMASH;
int Sexy::SOUND_TILE_SELECT;
int Sexy::SOUND_WELCOME;
int Sexy::SOUND_WORD_POWER;
int Sexy::SOUND_XP_STREAM;

bool Sexy::ExtractCommonGameResources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_ALTAR = aMgr.GetImageThrow("IMAGE_ALTAR");
		IMAGE_ALTAR_BUBBLE = aMgr.GetImageThrow("IMAGE_ALTAR_BUBBLE");
		IMAGE_ALTAR_GLOW1 = aMgr.GetImageThrow("IMAGE_ALTAR_GLOW1");
		IMAGE_ALTAR_GLOW2 = aMgr.GetImageThrow("IMAGE_ALTAR_GLOW2");
		IMAGE_ALTAR_GLOW3 = aMgr.GetImageThrow("IMAGE_ALTAR_GLOW3");
		IMAGE_BANNER_LARGE = aMgr.GetImageThrow("IMAGE_BANNER_LARGE");
		IMAGE_BANNER_SMALL = aMgr.GetImageThrow("IMAGE_BANNER_SMALL");
		IMAGE_BLUE_SPARKLE = aMgr.GetImageThrow("IMAGE_BLUE_SPARKLE");
		IMAGE_BOOKSHELF_LEFT = aMgr.GetImageThrow("IMAGE_BOOKSHELF_LEFT");
		IMAGE_BOOKSHELF_RIGHT = aMgr.GetImageThrow("IMAGE_BOOKSHELF_RIGHT");
		IMAGE_BOSS_BANNER = aMgr.GetImageThrow("IMAGE_BOSS_BANNER");
		IMAGE_BOSS_TEXT = aMgr.GetImageThrow("IMAGE_BOSS_TEXT");
		IMAGE_BURNING_RESISTED = aMgr.GetImageThrow("IMAGE_BURNING_RESISTED");
		IMAGE_BUTTON_ATTACK = aMgr.GetImageThrow("IMAGE_BUTTON_ATTACK");
		IMAGE_BUTTON_MENU = aMgr.GetImageThrow("IMAGE_BUTTON_MENU");
		IMAGE_BUTTON_SCRAMBLE = aMgr.GetImageThrow("IMAGE_BUTTON_SCRAMBLE");
		IMAGE_BUTTON_SCRAMBLE_SHADOW = aMgr.GetImageThrow("IMAGE_BUTTON_SCRAMBLE_SHADOW");
		IMAGE_COMBAT_UI_BOTTOM1 = aMgr.GetImageThrow("IMAGE_COMBAT_UI_BOTTOM1");
		IMAGE_COMBAT_UI_BOTTOM2 = aMgr.GetImageThrow("IMAGE_COMBAT_UI_BOTTOM2");
		IMAGE_COMBAT_UI_TOP = aMgr.GetImageThrow("IMAGE_COMBAT_UI_TOP");
		IMAGE_CUTSCENE_BOTTOM = aMgr.GetImageThrow("IMAGE_CUTSCENE_BOTTOM");
		IMAGE_CUTSCENE_TOP = aMgr.GetImageThrow("IMAGE_CUTSCENE_TOP");
		IMAGE_GRAVESTONE = aMgr.GetImageThrow("IMAGE_GRAVESTONE");
		IMAGE_GRAVESTONE_GLOW = aMgr.GetImageThrow("IMAGE_GRAVESTONE_GLOW");
		IMAGE_GRAVESTONE_SMOKE = aMgr.GetImageThrow("IMAGE_GRAVESTONE_SMOKE");
		IMAGE_GRAYBAR_BG = aMgr.GetImageThrow("IMAGE_GRAYBAR_BG");
		IMAGE_GS_GO = aMgr.GetImageThrow("IMAGE_GS_GO");
		IMAGE_GS_SHIP1 = aMgr.GetImageThrow("IMAGE_GS_SHIP1");
		IMAGE_GS_SHIP1_WARPJET = aMgr.GetImageThrow("IMAGE_GS_SHIP1_WARPJET");
		IMAGE_GS_SHIP2 = aMgr.GetImageThrow("IMAGE_GS_SHIP2");
		IMAGE_GS_SHIP3 = aMgr.GetImageThrow("IMAGE_GS_SHIP3");
		IMAGE_GS_SHIP4 = aMgr.GetImageThrow("IMAGE_GS_SHIP4");
		IMAGE_HEARTBLINK = aMgr.GetImageThrow("IMAGE_HEARTBLINK");
		IMAGE_HEARTBLINK_CC = aMgr.GetImageThrow("IMAGE_HEARTBLINK_CC");
		IMAGE_HEARTS = aMgr.GetImageThrow("IMAGE_HEARTS");
		IMAGE_HEARTS_BG = aMgr.GetImageThrow("IMAGE_HEARTS_BG");
		IMAGE_HEARTS_CC = aMgr.GetImageThrow("IMAGE_HEARTS_CC");
		IMAGE_HEART_BITS = aMgr.GetImageThrow("IMAGE_HEART_BITS");
		IMAGE_HEART_MASK = aMgr.GetImageThrow("IMAGE_HEART_MASK");
		IMAGE_HEART_MASK_CC = aMgr.GetImageThrow("IMAGE_HEART_MASK_CC");
		IMAGE_HINT_ARROW_BOX = aMgr.GetImageThrow("IMAGE_HINT_ARROW_BOX");
		IMAGE_HINT_ARROW_DOWN = aMgr.GetImageThrow("IMAGE_HINT_ARROW_DOWN");
		IMAGE_HINT_ARROW_DOWNX = aMgr.GetImageThrow("IMAGE_HINT_ARROW_DOWNX");
		IMAGE_HINT_ARROW_GLOW_ADD = aMgr.GetImageThrow("IMAGE_HINT_ARROW_GLOW_ADD");
		IMAGE_HINT_ARROW_LEFT = aMgr.GetImageThrow("IMAGE_HINT_ARROW_LEFT");
		IMAGE_HINT_ARROW_LEFTX = aMgr.GetImageThrow("IMAGE_HINT_ARROW_LEFTX");
		IMAGE_HINT_ARROW_RIGHT = aMgr.GetImageThrow("IMAGE_HINT_ARROW_RIGHT");
		IMAGE_HINT_ARROW_RIGHTX = aMgr.GetImageThrow("IMAGE_HINT_ARROW_RIGHTX");
		IMAGE_HINT_ARROW_TITLE = aMgr.GetImageThrow("IMAGE_HINT_ARROW_TITLE");
		IMAGE_HINT_ARROW_UP = aMgr.GetImageThrow("IMAGE_HINT_ARROW_UP");
		IMAGE_HINT_ARROW_UPX = aMgr.GetImageThrow("IMAGE_HINT_ARROW_UPX");
		IMAGE_IMPACT_LARGE = aMgr.GetImageThrow("IMAGE_IMPACT_LARGE");
		IMAGE_IMPACT_SMALL = aMgr.GetImageThrow("IMAGE_IMPACT_SMALL");
		IMAGE_ITEM_ATTACK = aMgr.GetImageThrow("IMAGE_ITEM_ATTACK");
		IMAGE_ITEM_ATTACK_NB = aMgr.GetImageThrow("IMAGE_ITEM_ATTACK_NB");
		IMAGE_ITEM_HEALTH = aMgr.GetImageThrow("IMAGE_ITEM_HEALTH");
		IMAGE_ITEM_HEALTH_NB = aMgr.GetImageThrow("IMAGE_ITEM_HEALTH_NB");
		IMAGE_ITEM_PURIFY = aMgr.GetImageThrow("IMAGE_ITEM_PURIFY");
		IMAGE_ITEM_PURIFY_NB = aMgr.GetImageThrow("IMAGE_ITEM_PURIFY_NB");
		IMAGE_LEVELUP_BANNER = aMgr.GetImageThrow("IMAGE_LEVELUP_BANNER");
		IMAGE_LEVELUP_ICONS = aMgr.GetImageThrow("IMAGE_LEVELUP_ICONS");
		IMAGE_LEVELUP_SPARKLE = aMgr.GetImageThrow("IMAGE_LEVELUP_SPARKLE");
		IMAGE_LEVELUP_STAR = aMgr.GetImageThrow("IMAGE_LEVELUP_STAR");
		IMAGE_LEVELUP_TEXT = aMgr.GetImageThrow("IMAGE_LEVELUP_TEXT");
		IMAGE_LEVELUP_TROPHY = aMgr.GetImageThrow("IMAGE_LEVELUP_TROPHY");
		IMAGE_LEVELUP_TROPHY_GLOW = aMgr.GetImageThrow("IMAGE_LEVELUP_TROPHY_GLOW");
		IMAGE_LEVELUP_TROPHY_PARTICLES = aMgr.GetImageThrow("IMAGE_LEVELUP_TROPHY_PARTICLES");
		IMAGE_LEVELUP_WATERMARK = aMgr.GetImageThrow("IMAGE_LEVELUP_WATERMARK");
		IMAGE_LEX_ICON = aMgr.GetImageThrow("IMAGE_LEX_ICON");
		IMAGE_LIBRARY_TITLE = aMgr.GetImageThrow("IMAGE_LIBRARY_TITLE");
		IMAGE_LORE_PLATE = aMgr.GetImageThrow("IMAGE_LORE_PLATE");
		IMAGE_LORE_PLATE_LIT = aMgr.GetImageThrow("IMAGE_LORE_PLATE_LIT");
		IMAGE_LORE_PLATE_TILABLE = aMgr.GetImageThrow("IMAGE_LORE_PLATE_TILABLE");
		IMAGE_LOW_HEALTH_OUTLINE = aMgr.GetImageThrow("IMAGE_LOW_HEALTH_OUTLINE");
		IMAGE_MAP_BOOK2 = aMgr.GetImageThrow("IMAGE_MAP_BOOK2");
		IMAGE_MAP_CHECK = aMgr.GetImageThrow("IMAGE_MAP_CHECK");
		IMAGE_MAP_LEX_WARP = aMgr.GetImageThrow("IMAGE_MAP_LEX_WARP");
		IMAGE_MAP_MINIGAME_ANIM = aMgr.GetImageThrow("IMAGE_MAP_MINIGAME_ANIM");
		IMAGE_MINIGAME_ICON = aMgr.GetImageThrow("IMAGE_MINIGAME_ICON");
		IMAGE_OVERKILL_ANNIHILATED = aMgr.GetImageThrow("IMAGE_OVERKILL_ANNIHILATED");
		IMAGE_OVERKILL_CRUSHED = aMgr.GetImageThrow("IMAGE_OVERKILL_CRUSHED");
		IMAGE_OVERKILL_DECIMATED = aMgr.GetImageThrow("IMAGE_OVERKILL_DECIMATED");
		IMAGE_OVERKILL_DESTROYED = aMgr.GetImageThrow("IMAGE_OVERKILL_DESTROYED");
		IMAGE_OVERKILL_OBLITERATED = aMgr.GetImageThrow("IMAGE_OVERKILL_OBLITERATED");
		IMAGE_OVERKILL_ROUTED = aMgr.GetImageThrow("IMAGE_OVERKILL_ROUTED");
		IMAGE_OVERKILL_VANQUISHED = aMgr.GetImageThrow("IMAGE_OVERKILL_VANQUISHED");
		IMAGE_OVERKILL_WHOMPED = aMgr.GetImageThrow("IMAGE_OVERKILL_WHOMPED");
		IMAGE_PAUSED_BANNER = aMgr.GetImageThrow("IMAGE_PAUSED_BANNER");
		IMAGE_PETRIFY_RESISTED = aMgr.GetImageThrow("IMAGE_PETRIFY_RESISTED");
		IMAGE_POISON_RESISTED = aMgr.GetImageThrow("IMAGE_POISON_RESISTED");
		IMAGE_POTION_PEDESTAL = aMgr.GetImageThrow("IMAGE_POTION_PEDESTAL");
		IMAGE_POWER_DOWN = aMgr.GetImageThrow("IMAGE_POWER_DOWN");
		IMAGE_PROGRESS_METER = aMgr.GetImageThrow("IMAGE_PROGRESS_METER");
		IMAGE_RED_SPARKLE = aMgr.GetImageThrow("IMAGE_RED_SPARKLE");
		IMAGE_STATS_BOX = aMgr.GetImageThrow("IMAGE_STATS_BOX");
		IMAGE_STATUE_CODEX = aMgr.GetImageThrow("IMAGE_STATUE_CODEX");
		IMAGE_STATUE_LEX = aMgr.GetImageThrow("IMAGE_STATUE_LEX");
		IMAGE_STATUSTEXT_BLEEDING = aMgr.GetImageThrow("IMAGE_STATUSTEXT_BLEEDING");
		IMAGE_STATUSTEXT_BONUS_WORD = aMgr.GetImageThrow("IMAGE_STATUSTEXT_BONUS_WORD");
		IMAGE_STATUSTEXT_BURNING = aMgr.GetImageThrow("IMAGE_STATUSTEXT_BURNING");
		IMAGE_STATUSTEXT_FROZEN = aMgr.GetImageThrow("IMAGE_STATUSTEXT_FROZEN");
		IMAGE_STATUSTEXT_PETRIFIED = aMgr.GetImageThrow("IMAGE_STATUSTEXT_PETRIFIED");
		IMAGE_STATUSTEXT_POISONED = aMgr.GetImageThrow("IMAGE_STATUSTEXT_POISONED");
		IMAGE_STATUSTEXT_POWERDOWN = aMgr.GetImageThrow("IMAGE_STATUSTEXT_POWERDOWN");
		IMAGE_STATUSTEXT_POWERUP = aMgr.GetImageThrow("IMAGE_STATUSTEXT_POWERUP");
		IMAGE_STATUSTEXT_SHIELDED = aMgr.GetImageThrow("IMAGE_STATUSTEXT_SHIELDED");
		IMAGE_STATUSTEXT_STUNNED = aMgr.GetImageThrow("IMAGE_STATUSTEXT_STUNNED");
		IMAGE_STATUS_ICONS = aMgr.GetImageThrow("IMAGE_STATUS_ICONS");
		IMAGE_STUN_RESISTED = aMgr.GetImageThrow("IMAGE_STUN_RESISTED");
		IMAGE_TILE_BASIC = aMgr.GetImageThrow("IMAGE_TILE_BASIC");
		IMAGE_TILE_PIPS = aMgr.GetImageThrow("IMAGE_TILE_PIPS");
		IMAGE_TMA_UI_TOP = aMgr.GetImageThrow("IMAGE_TMA_UI_TOP");
		IMAGE_TM_BONUS_TEXT = aMgr.GetImageThrow("IMAGE_TM_BONUS_TEXT");
		IMAGE_TM_INTRO_TITLE = aMgr.GetImageThrow("IMAGE_TM_INTRO_TITLE");
		IMAGE_TM_LEVELUP_TOKEN = aMgr.GetImageThrow("IMAGE_TM_LEVELUP_TOKEN");
		IMAGE_TM_LEVELUP_TOKEN_GOLD = aMgr.GetImageThrow("IMAGE_TM_LEVELUP_TOKEN_GOLD");
		IMAGE_TM_SPOTLIGHT = aMgr.GetImageThrow("IMAGE_TM_SPOTLIGHT");
		IMAGE_TREASURE_BANNER = aMgr.GetImageThrow("IMAGE_TREASURE_BANNER");
		IMAGE_TREASURE_BG = aMgr.GetImageThrow("IMAGE_TREASURE_BG");
		IMAGE_TREASURE_BOX = aMgr.GetImageThrow("IMAGE_TREASURE_BOX");
		IMAGE_TREASURE_BULB = aMgr.GetImageThrow("IMAGE_TREASURE_BULB");
		IMAGE_TREASURE_HILIGHT = aMgr.GetImageThrow("IMAGE_TREASURE_HILIGHT");
		IMAGE_TREASURE_HINT = aMgr.GetImageThrow("IMAGE_TREASURE_HINT");
		IMAGE_TREASURE_TEXTBOX = aMgr.GetImageThrow("IMAGE_TREASURE_TEXTBOX");
		IMAGE_TUT_ARROW = aMgr.GetImageThrow("IMAGE_TUT_ARROW");
		IMAGE_TUT_CURTAIN_LEFT = aMgr.GetImageThrow("IMAGE_TUT_CURTAIN_LEFT");
		IMAGE_TUT_CURTAIN_RIGHT = aMgr.GetImageThrow("IMAGE_TUT_CURTAIN_RIGHT");
		IMAGE_TUT_GRID_BOX = aMgr.GetImageThrow("IMAGE_TUT_GRID_BOX");
		IMAGE_TUT_MG_BUTTON = aMgr.GetImageThrow("IMAGE_TUT_MG_BUTTON");
		IMAGE_TUT_PIC_CASS = aMgr.GetImageThrow("IMAGE_TUT_PIC_CASS");
		IMAGE_TUT_PIC_CASS_WORRY = aMgr.GetImageThrow("IMAGE_TUT_PIC_CASS_WORRY");
		IMAGE_TUT_PIC_CIRCE = aMgr.GetImageThrow("IMAGE_TUT_PIC_CIRCE");
		IMAGE_TUT_PIC_CODEX = aMgr.GetImageThrow("IMAGE_TUT_PIC_CODEX");
		IMAGE_TUT_PIC_HEPH = aMgr.GetImageThrow("IMAGE_TUT_PIC_HEPH");
		IMAGE_TUT_PIC_LEX = aMgr.GetImageThrow("IMAGE_TUT_PIC_LEX");
		IMAGE_TUT_PIC_LEX_WORRY = aMgr.GetImageThrow("IMAGE_TUT_PIC_LEX_WORRY");
		IMAGE_TUT_PIC_MOXIE = aMgr.GetImageThrow("IMAGE_TUT_PIC_MOXIE");
		IMAGE_TUT_PIC_NEMESIS = aMgr.GetImageThrow("IMAGE_TUT_PIC_NEMESIS");
		IMAGE_TUT_PLAY_BLUR = aMgr.GetImageThrow("IMAGE_TUT_PLAY_BLUR");
		IMAGE_TUT_PLAY_DIAGRAM = aMgr.GetImageThrow("IMAGE_TUT_PLAY_DIAGRAM");
		IMAGE_TUT_SCRAMBLE_BOX = aMgr.GetImageThrow("IMAGE_TUT_SCRAMBLE_BOX");
		IMAGE_TUT_TITLE = aMgr.GetImageThrow("IMAGE_TUT_TITLE");
		IMAGE_TUT_TREASURE_BLUR_BOX = aMgr.GetImageThrow("IMAGE_TUT_TREASURE_BLUR_BOX");
		IMAGE_UI_BOOK_AVAILABLE = aMgr.GetImageThrow("IMAGE_UI_BOOK_AVAILABLE");
		IMAGE_UI_BOOK_BACK_BUTTON = aMgr.GetImageThrow("IMAGE_UI_BOOK_BACK_BUTTON");
		IMAGE_UI_BOOK_DOTS = aMgr.GetImageThrow("IMAGE_UI_BOOK_DOTS");
		IMAGE_UI_BOOK_END_STATS_BOX = aMgr.GetImageThrow("IMAGE_UI_BOOK_END_STATS_BOX");
		IMAGE_UI_BOOK_END_STATS_TITLE = aMgr.GetImageThrow("IMAGE_UI_BOOK_END_STATS_TITLE");
		IMAGE_UI_BOOK_ENTER_BUTTON = aMgr.GetImageThrow("IMAGE_UI_BOOK_ENTER_BUTTON");
		IMAGE_UI_BOOK_HILIGHT = aMgr.GetImageThrow("IMAGE_UI_BOOK_HILIGHT");
		IMAGE_UI_BOOK_OPTIONS_BUTTON = aMgr.GetImageThrow("IMAGE_UI_BOOK_OPTIONS_BUTTON");
		IMAGE_UI_BOOK_TS_CONTINUE_BUTTON = aMgr.GetImageThrow("IMAGE_UI_BOOK_TS_CONTINUE_BUTTON");
		IMAGE_UI_BOTTOM = aMgr.GetImageThrow("IMAGE_UI_BOTTOM");
		IMAGE_UI_DESCRIPTION_BOX = aMgr.GetImageThrow("IMAGE_UI_DESCRIPTION_BOX");
		IMAGE_UI_LEFT = aMgr.GetImageThrow("IMAGE_UI_LEFT");
		IMAGE_UI_RIGHT = aMgr.GetImageThrow("IMAGE_UI_RIGHT");
		IMAGE_UI_TOP = aMgr.GetImageThrow("IMAGE_UI_TOP");
		IMAGE_WORDPOWER_GLOW_INNER_LEFT = aMgr.GetImageThrow("IMAGE_WORDPOWER_GLOW_INNER_LEFT");
		IMAGE_WORDPOWER_GLOW_INNER_MID = aMgr.GetImageThrow("IMAGE_WORDPOWER_GLOW_INNER_MID");
		IMAGE_WORDPOWER_GLOW_INNER_RIGHT = aMgr.GetImageThrow("IMAGE_WORDPOWER_GLOW_INNER_RIGHT");
		IMAGE_WORDPOWER_GLOW_LEFT = aMgr.GetImageThrow("IMAGE_WORDPOWER_GLOW_LEFT");
		IMAGE_WORDPOWER_GLOW_LEFT_SMALL = aMgr.GetImageThrow("IMAGE_WORDPOWER_GLOW_LEFT_SMALL");
		IMAGE_WORDPOWER_GLOW_MIDDLE = aMgr.GetImageThrow("IMAGE_WORDPOWER_GLOW_MIDDLE");
		IMAGE_WORDPOWER_GLOW_MIDDLE_SMALL = aMgr.GetImageThrow("IMAGE_WORDPOWER_GLOW_MIDDLE_SMALL");
		IMAGE_WORDPOWER_GLOW_RIGHT = aMgr.GetImageThrow("IMAGE_WORDPOWER_GLOW_RIGHT");
		IMAGE_WORDPOWER_GLOW_RIGHT_SMALL = aMgr.GetImageThrow("IMAGE_WORDPOWER_GLOW_RIGHT_SMALL");
		IMAGE_WORD_BUBBLE = aMgr.GetImageThrow("IMAGE_WORD_BUBBLE");
		IMAGE_WORD_BUBBLE_DOWN_ARROW = aMgr.GetImageThrow("IMAGE_WORD_BUBBLE_DOWN_ARROW");
		IMAGE_WORD_BUBBLE_LEFT = aMgr.GetImageThrow("IMAGE_WORD_BUBBLE_LEFT");
		IMAGE_WORD_BUBBLE_RIGHT = aMgr.GetImageThrow("IMAGE_WORD_BUBBLE_RIGHT");
		IMAGE_WORD_BUBBLE_TEX = aMgr.GetImageThrow("IMAGE_WORD_BUBBLE_TEX");
		IMAGE_WP_SPARKLE_MEDIUM = aMgr.GetImageThrow("IMAGE_WP_SPARKLE_MEDIUM");
		IMAGE_WP_SPARKLE_SMALL = aMgr.GetImageThrow("IMAGE_WP_SPARKLE_SMALL");
		IMAGE_WS_BESTWORD_TITLE = aMgr.GetImageThrow("IMAGE_WS_BESTWORD_TITLE");
		IMAGE_WS_PAPER = aMgr.GetImageThrow("IMAGE_WS_PAPER");
		IMAGE_WS_SCROLL = aMgr.GetImageThrow("IMAGE_WS_SCROLL");
		IMAGE_XPBAR_GLOW = aMgr.GetImageThrow("IMAGE_XPBAR_GLOW");
		IMAGE_XP_BAR_EFFECT = aMgr.GetImageThrow("IMAGE_XP_BAR_EFFECT");
		IMAGE_XP_BAR_EFFECT_WHITE = aMgr.GetImageThrow("IMAGE_XP_BAR_EFFECT_WHITE");
		IMAGE_XP_BAR_EMPTY = aMgr.GetImageThrow("IMAGE_XP_BAR_EMPTY");
		IMAGE_XP_BAR_FULL = aMgr.GetImageThrow("IMAGE_XP_BAR_FULL");
		SOUND_1 = aMgr.GetSoundThrow("SOUND_1");
		SOUND_2 = aMgr.GetSoundThrow("SOUND_2");
		SOUND_3 = aMgr.GetSoundThrow("SOUND_3");
		SOUND_CHACHING = aMgr.GetSoundThrow("SOUND_CHACHING");
		SOUND_CLICK1 = aMgr.GetSoundThrow("SOUND_CLICK1");
		SOUND_CLICK2 = aMgr.GetSoundThrow("SOUND_CLICK2");
		SOUND_COUNT = aMgr.GetSoundThrow("SOUND_COUNT");
		SOUND_CROWD_CHEER = aMgr.GetSoundThrow("SOUND_CROWD_CHEER");
		SOUND_EFFECT_FIRE = aMgr.GetSoundThrow("SOUND_EFFECT_FIRE");
		SOUND_EFFECT_FROZEN = aMgr.GetSoundThrow("SOUND_EFFECT_FROZEN");
		SOUND_EFFECT_PETRIFY = aMgr.GetSoundThrow("SOUND_EFFECT_PETRIFY");
		SOUND_EFFECT_POISON = aMgr.GetSoundThrow("SOUND_EFFECT_POISON");
		SOUND_EFFECT_WEAKEN = aMgr.GetSoundThrow("SOUND_EFFECT_WEAKEN");
		SOUND_FIREWORK1 = aMgr.GetSoundThrow("SOUND_FIREWORK1");
		SOUND_FIREWORK2 = aMgr.GetSoundThrow("SOUND_FIREWORK2");
		SOUND_FREEZE = aMgr.GetSoundThrow("SOUND_FREEZE");
		SOUND_GEMSPAWN = aMgr.GetSoundThrow("SOUND_GEMSPAWN");
		SOUND_GO = aMgr.GetSoundThrow("SOUND_GO");
		SOUND_HEAL = aMgr.GetSoundThrow("SOUND_HEAL");
		SOUND_IMPACT_LARGE = aMgr.GetSoundThrow("SOUND_IMPACT_LARGE");
		SOUND_IMPACT_SMALL = aMgr.GetSoundThrow("SOUND_IMPACT_SMALL");
		SOUND_LEX_ASTONISHING = aMgr.GetSoundThrow("SOUND_LEX_ASTONISHING");
		SOUND_LEX_ATTACK1 = aMgr.GetSoundThrow("SOUND_LEX_ATTACK1");
		SOUND_LEX_ATTACK4 = aMgr.GetSoundThrow("SOUND_LEX_ATTACK4");
		SOUND_LEX_ATTACK5 = aMgr.GetSoundThrow("SOUND_LEX_ATTACK5");
		SOUND_LEX_ATTACK6 = aMgr.GetSoundThrow("SOUND_LEX_ATTACK6");
		SOUND_LEX_ATTACK7 = aMgr.GetSoundThrow("SOUND_LEX_ATTACK7");
		SOUND_LEX_AUTOLOGICAL = aMgr.GetSoundThrow("SOUND_LEX_AUTOLOGICAL");
		SOUND_LEX_AWESOME = aMgr.GetSoundThrow("SOUND_LEX_AWESOME");
		SOUND_LEX_BITE = aMgr.GetSoundThrow("SOUND_LEX_BITE");
		SOUND_LEX_BOSS_BATTLE = aMgr.GetSoundThrow("SOUND_LEX_BOSS_BATTLE");
		SOUND_LEX_BURP = aMgr.GetSoundThrow("SOUND_LEX_BURP");
		SOUND_LEX_CASHMONEY = aMgr.GetSoundThrow("SOUND_LEX_CASHMONEY");
		SOUND_LEX_EXCELLENT = aMgr.GetSoundThrow("SOUND_LEX_EXCELLENT");
		SOUND_LEX_FANTASTIC = aMgr.GetSoundThrow("SOUND_LEX_FANTASTIC");
		SOUND_LEX_GIGGLE1 = aMgr.GetSoundThrow("SOUND_LEX_GIGGLE1");
		SOUND_LEX_GIGGLE2 = aMgr.GetSoundThrow("SOUND_LEX_GIGGLE2");
		SOUND_LEX_GOOD = aMgr.GetSoundThrow("SOUND_LEX_GOOD");
		SOUND_LEX_ILOVEYOU = aMgr.GetSoundThrow("SOUND_LEX_ILOVEYOU");
		SOUND_LEX_INCREDIBLE = aMgr.GetSoundThrow("SOUND_LEX_INCREDIBLE");
		SOUND_LEX_LEVELUP = aMgr.GetSoundThrow("SOUND_LEX_LEVELUP");
		SOUND_LEX_NICE = aMgr.GetSoundThrow("SOUND_LEX_NICE");
		SOUND_LEX_SHEEPBLEAT = aMgr.GetSoundThrow("SOUND_LEX_SHEEPBLEAT");
		SOUND_LEX_SNEEZE = aMgr.GetSoundThrow("SOUND_LEX_SNEEZE");
		SOUND_LEX_VERYGOOD = aMgr.GetSoundThrow("SOUND_LEX_VERYGOOD");
		SOUND_LEX_WARPIN = aMgr.GetSoundThrow("SOUND_LEX_WARPIN");
		SOUND_LEX_WARPOUT = aMgr.GetSoundThrow("SOUND_LEX_WARPOUT");
		SOUND_LEX_WATCHOUT = aMgr.GetSoundThrow("SOUND_LEX_WATCHOUT");
		SOUND_LEX_WOW = aMgr.GetSoundThrow("SOUND_LEX_WOW");
		SOUND_LIGHTNING = aMgr.GetSoundThrow("SOUND_LIGHTNING");
		SOUND_LOW_HEALTH = aMgr.GetSoundThrow("SOUND_LOW_HEALTH");
		SOUND_MM_ADVENTURE = aMgr.GetSoundThrow("SOUND_MM_ADVENTURE");
		SOUND_MM_ARENA = aMgr.GetSoundThrow("SOUND_MM_ARENA");
		SOUND_MM_BUY_NOW = aMgr.GetSoundThrow("SOUND_MM_BUY_NOW");
		SOUND_MM_CNG = aMgr.GetSoundThrow("SOUND_MM_CNG");
		SOUND_MM_DONTLEAVE = aMgr.GetSoundThrow("SOUND_MM_DONTLEAVE");
		SOUND_MM_HS = aMgr.GetSoundThrow("SOUND_MM_HS");
		SOUND_MM_MINIGAMES = aMgr.GetSoundThrow("SOUND_MM_MINIGAMES");
		SOUND_MM_OPTIONS = aMgr.GetSoundThrow("SOUND_MM_OPTIONS");
		SOUND_MM_QUIT = aMgr.GetSoundThrow("SOUND_MM_QUIT");
		SOUND_MM_TOK = aMgr.GetSoundThrow("SOUND_MM_TOK");
		SOUND_NEW_MINIGAME = aMgr.GetSoundThrow("SOUND_NEW_MINIGAME");
		SOUND_NEW_TREASURE = aMgr.GetSoundThrow("SOUND_NEW_TREASURE");
		SOUND_OVERKILL_ANNIHILATED = aMgr.GetSoundThrow("SOUND_OVERKILL_ANNIHILATED");
		SOUND_OVERKILL_CRUSHED = aMgr.GetSoundThrow("SOUND_OVERKILL_CRUSHED");
		SOUND_OVERKILL_DECIMATED = aMgr.GetSoundThrow("SOUND_OVERKILL_DECIMATED");
		SOUND_OVERKILL_DESTROYED = aMgr.GetSoundThrow("SOUND_OVERKILL_DESTROYED");
		SOUND_OVERKILL_OBLITERATED = aMgr.GetSoundThrow("SOUND_OVERKILL_OBLITERATED");
		SOUND_OVERKILL_ROUTED = aMgr.GetSoundThrow("SOUND_OVERKILL_ROUTED");
		SOUND_OVERKILL_VANQUISHED = aMgr.GetSoundThrow("SOUND_OVERKILL_VANQUISHED");
		SOUND_OVERKILL_WHOMPED = aMgr.GetSoundThrow("SOUND_OVERKILL_WHOMPED");
		SOUND_PETRIFY = aMgr.GetSoundThrow("SOUND_PETRIFY");
		SOUND_PLAGUE = aMgr.GetSoundThrow("SOUND_PLAGUE");
		SOUND_POISON = aMgr.GetSoundThrow("SOUND_POISON");
		SOUND_POTION_HEAL = aMgr.GetSoundThrow("SOUND_POTION_HEAL");
		SOUND_POTION_PICKUP = aMgr.GetSoundThrow("SOUND_POTION_PICKUP");
		SOUND_POTION_POWERUP = aMgr.GetSoundThrow("SOUND_POTION_POWERUP");
		SOUND_POTION_PURIFY = aMgr.GetSoundThrow("SOUND_POTION_PURIFY");
		SOUND_POWERDOWN = aMgr.GetSoundThrow("SOUND_POWERDOWN");
		SOUND_POWERUP = aMgr.GetSoundThrow("SOUND_POWERUP");
		SOUND_SCRAMBLE = aMgr.GetSoundThrow("SOUND_SCRAMBLE");
		SOUND_SLOWDOWN = aMgr.GetSoundThrow("SOUND_SLOWDOWN");
		SOUND_STUN = aMgr.GetSoundThrow("SOUND_STUN");
		SOUND_SUBMIT_FAILED = aMgr.GetSoundThrow("SOUND_SUBMIT_FAILED");
		SOUND_TEXT_BLIP = aMgr.GetSoundThrow("SOUND_TEXT_BLIP");
		SOUND_TILELOCK = aMgr.GetSoundThrow("SOUND_TILELOCK");
		SOUND_TILESMASH = aMgr.GetSoundThrow("SOUND_TILESMASH");
		SOUND_TILE_SELECT = aMgr.GetSoundThrow("SOUND_TILE_SELECT");
		SOUND_WELCOME = aMgr.GetSoundThrow("SOUND_WELCOME");
		SOUND_WORD_POWER = aMgr.GetSoundThrow("SOUND_WORD_POWER");
		SOUND_XP_STREAM = aMgr.GetSoundThrow("SOUND_XP_STREAM");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// Credits Resources
Image* Sexy::IMAGE_CREDITS_GRASS;

bool Sexy::ExtractCreditsResources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_CREDITS_GRASS = aMgr.GetImageThrow("IMAGE_CREDITS_GRASS");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// HallOfFame Resources
Image* Sexy::IMAGE_HOF_BANNER_BOSS;
Image* Sexy::IMAGE_HOF_BANNER_LEX_POWER;
Image* Sexy::IMAGE_HOF_BANNER_LEX_SKILL;
Image* Sexy::IMAGE_HOF_BANNER_LNS;
Image* Sexy::IMAGE_HOF_BANNER_LR;
Image* Sexy::IMAGE_HOF_BANNER_TOP_10;
Image* Sexy::IMAGE_HOF_BANNER_WM;
Image* Sexy::IMAGE_HOF_BG;
Image* Sexy::IMAGE_HOF_BTN_MAINMENU;
Image* Sexy::IMAGE_HOF_BTN_MG_NEXT;
Image* Sexy::IMAGE_HOF_BTN_MG_PREV;
Image* Sexy::IMAGE_HOF_BTN_PLAYAGAIN;
Image* Sexy::IMAGE_HOF_PANEL_2;
Image* Sexy::IMAGE_HOF_PANEL_3;
Image* Sexy::IMAGE_HOF_POWER_RATING;
Image* Sexy::IMAGE_HOF_TAB_ADVENTURE;
Image* Sexy::IMAGE_HOF_TAB_ARENA;
Image* Sexy::IMAGE_HOF_TAB_MINIGAMES;

bool Sexy::ExtractHallOfFameResources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_HOF_BANNER_BOSS = aMgr.GetImageThrow("IMAGE_HOF_BANNER_BOSS");
		IMAGE_HOF_BANNER_LEX_POWER = aMgr.GetImageThrow("IMAGE_HOF_BANNER_LEX_POWER");
		IMAGE_HOF_BANNER_LEX_SKILL = aMgr.GetImageThrow("IMAGE_HOF_BANNER_LEX_SKILL");
		IMAGE_HOF_BANNER_LNS = aMgr.GetImageThrow("IMAGE_HOF_BANNER_LNS");
		IMAGE_HOF_BANNER_LR = aMgr.GetImageThrow("IMAGE_HOF_BANNER_LR");
		IMAGE_HOF_BANNER_TOP_10 = aMgr.GetImageThrow("IMAGE_HOF_BANNER_TOP_10");
		IMAGE_HOF_BANNER_WM = aMgr.GetImageThrow("IMAGE_HOF_BANNER_WM");
		IMAGE_HOF_BG = aMgr.GetImageThrow("IMAGE_HOF_BG");
		IMAGE_HOF_BTN_MAINMENU = aMgr.GetImageThrow("IMAGE_HOF_BTN_MAINMENU");
		IMAGE_HOF_BTN_MG_NEXT = aMgr.GetImageThrow("IMAGE_HOF_BTN_MG_NEXT");
		IMAGE_HOF_BTN_MG_PREV = aMgr.GetImageThrow("IMAGE_HOF_BTN_MG_PREV");
		IMAGE_HOF_BTN_PLAYAGAIN = aMgr.GetImageThrow("IMAGE_HOF_BTN_PLAYAGAIN");
		IMAGE_HOF_PANEL_2 = aMgr.GetImageThrow("IMAGE_HOF_PANEL_2");
		IMAGE_HOF_PANEL_3 = aMgr.GetImageThrow("IMAGE_HOF_PANEL_3");
		IMAGE_HOF_POWER_RATING = aMgr.GetImageThrow("IMAGE_HOF_POWER_RATING");
		IMAGE_HOF_TAB_ADVENTURE = aMgr.GetImageThrow("IMAGE_HOF_TAB_ADVENTURE");
		IMAGE_HOF_TAB_ARENA = aMgr.GetImageThrow("IMAGE_HOF_TAB_ARENA");
		IMAGE_HOF_TAB_MINIGAMES = aMgr.GetImageThrow("IMAGE_HOF_TAB_MINIGAMES");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// Init Resources
Font* Sexy::FONT_BANTER;
Font* Sexy::FONT_HUGE;
Font* Sexy::FONT_LARGE;
Font* Sexy::FONT_LARGER;
Font* Sexy::FONT_LARGE_OUTLINE;
Font* Sexy::FONT_MEDIUM;
Font* Sexy::FONT_MEDIUM_BOLD;
Font* Sexy::FONT_SMALL;
Font* Sexy::FONT_TILE;
Font* Sexy::FONT_TILE_STATUS;
Image* Sexy::IMAGE_ARENA_WIN_BANNER;
Image* Sexy::IMAGE_BANNER_CREDITS;
Image* Sexy::IMAGE_CURTAIN_ANIM;
Image* Sexy::IMAGE_CURTAIN_CORD;
Image* Sexy::IMAGE_CURTAIN_TOP;
Image* Sexy::IMAGE_CUSTOM_DRAGGING;
Image* Sexy::IMAGE_CUSTOM_HAND;
Image* Sexy::IMAGE_CUSTOM_POINTER;
Image* Sexy::IMAGE_CUSTOM_TEXT;
Image* Sexy::IMAGE_DIALOG;
Image* Sexy::IMAGE_DIALOG_BANNER_HOWTOPLAY;
Image* Sexy::IMAGE_DIALOG_BANNER_LOADING;
Image* Sexy::IMAGE_DIALOG_BANNER_MENU;
Image* Sexy::IMAGE_DIALOG_BANNER_NEWUSER;
Image* Sexy::IMAGE_DIALOG_BANNER_OPTIONS;
Image* Sexy::IMAGE_DIALOG_BANNER_RUSURE;
Image* Sexy::IMAGE_DIALOG_BANNER_WELCOME;
Image* Sexy::IMAGE_DIALOG_BUTTON;
Image* Sexy::IMAGE_DIALOG_CHECKBOX;
Image* Sexy::IMAGE_DIALOG_DIVIDER_BOT;
Image* Sexy::IMAGE_DIALOG_DIVIDER_TOP;
Image* Sexy::IMAGE_DIALOG_USER_ENTRY;
Image* Sexy::IMAGE_FILM_REEL;
Image* Sexy::IMAGE_ORANGE_STAR;
Image* Sexy::IMAGE_RED_STAR;
Image* Sexy::IMAGE_SLIDER_THUMB;
Image* Sexy::IMAGE_SLIDER_TRACK;
Image* Sexy::IMAGE_SLIDER_TRACK_VERT;
Image* Sexy::IMAGE_WAIT_BAR;
Image* Sexy::IMAGE_YELLOW_STAR;
int Sexy::SOUND_CHOMP;

bool Sexy::ExtractInitResources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		FONT_BANTER = aMgr.GetFontThrow("FONT_BANTER");
		FONT_HUGE = aMgr.GetFontThrow("FONT_HUGE");
		FONT_LARGE = aMgr.GetFontThrow("FONT_LARGE");
		FONT_LARGER = aMgr.GetFontThrow("FONT_LARGER");
		FONT_LARGE_OUTLINE = aMgr.GetFontThrow("FONT_LARGE_OUTLINE");
		FONT_MEDIUM = aMgr.GetFontThrow("FONT_MEDIUM");
		FONT_MEDIUM_BOLD = aMgr.GetFontThrow("FONT_MEDIUM_BOLD");
		FONT_SMALL = aMgr.GetFontThrow("FONT_SMALL");
		FONT_TILE = aMgr.GetFontThrow("FONT_TILE");
		FONT_TILE_STATUS = aMgr.GetFontThrow("FONT_TILE_STATUS");
		IMAGE_ARENA_WIN_BANNER = aMgr.GetImageThrow("IMAGE_ARENA_WIN_BANNER");
		IMAGE_BANNER_CREDITS = aMgr.GetImageThrow("IMAGE_BANNER_CREDITS");
		IMAGE_CURTAIN_ANIM = aMgr.GetImageThrow("IMAGE_CURTAIN_ANIM");
		IMAGE_CURTAIN_CORD = aMgr.GetImageThrow("IMAGE_CURTAIN_CORD");
		IMAGE_CURTAIN_TOP = aMgr.GetImageThrow("IMAGE_CURTAIN_TOP");
		IMAGE_CUSTOM_DRAGGING = aMgr.GetImageThrow("IMAGE_CUSTOM_DRAGGING");
		IMAGE_CUSTOM_HAND = aMgr.GetImageThrow("IMAGE_CUSTOM_HAND");
		IMAGE_CUSTOM_POINTER = aMgr.GetImageThrow("IMAGE_CUSTOM_POINTER");
		IMAGE_CUSTOM_TEXT = aMgr.GetImageThrow("IMAGE_CUSTOM_TEXT");
		IMAGE_DIALOG = aMgr.GetImageThrow("IMAGE_DIALOG");
		IMAGE_DIALOG_BANNER_HOWTOPLAY = aMgr.GetImageThrow("IMAGE_DIALOG_BANNER_HOWTOPLAY");
		IMAGE_DIALOG_BANNER_LOADING = aMgr.GetImageThrow("IMAGE_DIALOG_BANNER_LOADING");
		IMAGE_DIALOG_BANNER_MENU = aMgr.GetImageThrow("IMAGE_DIALOG_BANNER_MENU");
		IMAGE_DIALOG_BANNER_NEWUSER = aMgr.GetImageThrow("IMAGE_DIALOG_BANNER_NEWUSER");
		IMAGE_DIALOG_BANNER_OPTIONS = aMgr.GetImageThrow("IMAGE_DIALOG_BANNER_OPTIONS");
		IMAGE_DIALOG_BANNER_RUSURE = aMgr.GetImageThrow("IMAGE_DIALOG_BANNER_RUSURE");
		IMAGE_DIALOG_BANNER_WELCOME = aMgr.GetImageThrow("IMAGE_DIALOG_BANNER_WELCOME");
		IMAGE_DIALOG_BUTTON = aMgr.GetImageThrow("IMAGE_DIALOG_BUTTON");
		IMAGE_DIALOG_CHECKBOX = aMgr.GetImageThrow("IMAGE_DIALOG_CHECKBOX");
		IMAGE_DIALOG_DIVIDER_BOT = aMgr.GetImageThrow("IMAGE_DIALOG_DIVIDER_BOT");
		IMAGE_DIALOG_DIVIDER_TOP = aMgr.GetImageThrow("IMAGE_DIALOG_DIVIDER_TOP");
		IMAGE_DIALOG_USER_ENTRY = aMgr.GetImageThrow("IMAGE_DIALOG_USER_ENTRY");
		IMAGE_FILM_REEL = aMgr.GetImageThrow("IMAGE_FILM_REEL");
		IMAGE_ORANGE_STAR = aMgr.GetImageThrow("IMAGE_ORANGE_STAR");
		IMAGE_RED_STAR = aMgr.GetImageThrow("IMAGE_RED_STAR");
		IMAGE_SLIDER_THUMB = aMgr.GetImageThrow("IMAGE_SLIDER_THUMB");
		IMAGE_SLIDER_TRACK = aMgr.GetImageThrow("IMAGE_SLIDER_TRACK");
		IMAGE_SLIDER_TRACK_VERT = aMgr.GetImageThrow("IMAGE_SLIDER_TRACK_VERT");
		IMAGE_WAIT_BAR = aMgr.GetImageThrow("IMAGE_WAIT_BAR");
		IMAGE_YELLOW_STAR = aMgr.GetImageThrow("IMAGE_YELLOW_STAR");
		SOUND_CHOMP = aMgr.GetSoundThrow("SOUND_CHOMP");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// MiniGameCommon Resources
Image* Sexy::IMAGE_MINICOMMON_BANNER_NICE_TRY;
Image* Sexy::IMAGE_MINICOMMON_BANNER_WELL_DONE;
Image* Sexy::IMAGE_MINICOMMON_BANNER_WINNINGS;
Image* Sexy::IMAGE_MINICOMMON_BTN_CLICK_ANYWHERE;
Image* Sexy::IMAGE_MINICOMMON_BTN_SUBMIT;
Image* Sexy::IMAGE_MINICOMMON_COUNTDOWN;
Image* Sexy::IMAGE_MINICOMMON_GAMEOVER;
Image* Sexy::IMAGE_MINICOMMON_LABEL_BONUS;
Image* Sexy::IMAGE_MINICOMMON_ORANGE_STAR;
Image* Sexy::IMAGE_MINICOMMON_ORANGE_STAR_SAT;
Image* Sexy::IMAGE_MINICOMMON_RED_STAR;
Image* Sexy::IMAGE_MINICOMMON_RED_STAR_SAT;
Image* Sexy::IMAGE_MINICOMMON_SCOREBOX;
Image* Sexy::IMAGE_MINICOMMON_TAB_RIGHT_DARK;
Image* Sexy::IMAGE_MINICOMMON_TAB_RIGHT_LIT;
Image* Sexy::IMAGE_MINICOMMON_TENT_BG;
Image* Sexy::IMAGE_MINICOMMON_TITLE_BONUSROUND;
Image* Sexy::IMAGE_MINICOMMON_TITLE_TOOBAD;
Image* Sexy::IMAGE_MINICOMMON_TITLE_WELLDONE;
Image* Sexy::IMAGE_MINICOMMON_WHITE_BG;
Image* Sexy::IMAGE_MINICOMMON_YELLOW_STAR;
Image* Sexy::IMAGE_MINICOMMON_YELLOW_STAR_SAT;

bool Sexy::ExtractMiniGameCommonResources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_MINICOMMON_BANNER_NICE_TRY = aMgr.GetImageThrow("IMAGE_MINICOMMON_BANNER_NICE_TRY");
		IMAGE_MINICOMMON_BANNER_WELL_DONE = aMgr.GetImageThrow("IMAGE_MINICOMMON_BANNER_WELL_DONE");
		IMAGE_MINICOMMON_BANNER_WINNINGS = aMgr.GetImageThrow("IMAGE_MINICOMMON_BANNER_WINNINGS");
		IMAGE_MINICOMMON_BTN_CLICK_ANYWHERE = aMgr.GetImageThrow("IMAGE_MINICOMMON_BTN_CLICK_ANYWHERE");
		IMAGE_MINICOMMON_BTN_SUBMIT = aMgr.GetImageThrow("IMAGE_MINICOMMON_BTN_SUBMIT");
		IMAGE_MINICOMMON_COUNTDOWN = aMgr.GetImageThrow("IMAGE_MINICOMMON_COUNTDOWN");
		IMAGE_MINICOMMON_GAMEOVER = aMgr.GetImageThrow("IMAGE_MINICOMMON_GAMEOVER");
		IMAGE_MINICOMMON_LABEL_BONUS = aMgr.GetImageThrow("IMAGE_MINICOMMON_LABEL_BONUS");
		IMAGE_MINICOMMON_ORANGE_STAR = aMgr.GetImageThrow("IMAGE_MINICOMMON_ORANGE_STAR");
		IMAGE_MINICOMMON_ORANGE_STAR_SAT = aMgr.GetImageThrow("IMAGE_MINICOMMON_ORANGE_STAR_SAT");
		IMAGE_MINICOMMON_RED_STAR = aMgr.GetImageThrow("IMAGE_MINICOMMON_RED_STAR");
		IMAGE_MINICOMMON_RED_STAR_SAT = aMgr.GetImageThrow("IMAGE_MINICOMMON_RED_STAR_SAT");
		IMAGE_MINICOMMON_SCOREBOX = aMgr.GetImageThrow("IMAGE_MINICOMMON_SCOREBOX");
		IMAGE_MINICOMMON_TAB_RIGHT_DARK = aMgr.GetImageThrow("IMAGE_MINICOMMON_TAB_RIGHT_DARK");
		IMAGE_MINICOMMON_TAB_RIGHT_LIT = aMgr.GetImageThrow("IMAGE_MINICOMMON_TAB_RIGHT_LIT");
		IMAGE_MINICOMMON_TENT_BG = aMgr.GetImageThrow("IMAGE_MINICOMMON_TENT_BG");
		IMAGE_MINICOMMON_TITLE_BONUSROUND = aMgr.GetImageThrow("IMAGE_MINICOMMON_TITLE_BONUSROUND");
		IMAGE_MINICOMMON_TITLE_TOOBAD = aMgr.GetImageThrow("IMAGE_MINICOMMON_TITLE_TOOBAD");
		IMAGE_MINICOMMON_TITLE_WELLDONE = aMgr.GetImageThrow("IMAGE_MINICOMMON_TITLE_WELLDONE");
		IMAGE_MINICOMMON_WHITE_BG = aMgr.GetImageThrow("IMAGE_MINICOMMON_WHITE_BG");
		IMAGE_MINICOMMON_YELLOW_STAR = aMgr.GetImageThrow("IMAGE_MINICOMMON_YELLOW_STAR");
		IMAGE_MINICOMMON_YELLOW_STAR_SAT = aMgr.GetImageThrow("IMAGE_MINICOMMON_YELLOW_STAR_SAT");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// MiniGameMenu Resources
Image* Sexy::IMAGE_MINIMENU_BTN_MAINMENU;
Image* Sexy::IMAGE_MINIMENU_PLAIN_BG;
Image* Sexy::IMAGE_MINIMENU_TENT_BG;
Image* Sexy::IMAGE_MINIMENU_TITLE;

bool Sexy::ExtractMiniGameMenuResources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_MINIMENU_BTN_MAINMENU = aMgr.GetImageThrow("IMAGE_MINIMENU_BTN_MAINMENU");
		IMAGE_MINIMENU_PLAIN_BG = aMgr.GetImageThrow("IMAGE_MINIMENU_PLAIN_BG");
		IMAGE_MINIMENU_TENT_BG = aMgr.GetImageThrow("IMAGE_MINIMENU_TENT_BG");
		IMAGE_MINIMENU_TITLE = aMgr.GetImageThrow("IMAGE_MINIMENU_TITLE");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// StatsBook Resources
Image* Sexy::IMAGE_MP_CLIPS;
Image* Sexy::IMAGE_MP_FRAME;
Image* Sexy::IMAGE_MP_PLAY;
Image* Sexy::IMAGE_MP_TITLE;
Image* Sexy::IMAGE_SB_AREA;
Image* Sexy::IMAGE_SB_BESTWORDS;
Image* Sexy::IMAGE_SB_BGX;
Image* Sexy::IMAGE_SB_BUTTON_MENU;
Image* Sexy::IMAGE_SB_CHARACTER;
Image* Sexy::IMAGE_SB_CHARS_SEEN;
Image* Sexy::IMAGE_SB_CLOCK;
Image* Sexy::IMAGE_SB_ENEMY;
Image* Sexy::IMAGE_SB_GAMEOVER;
Image* Sexy::IMAGE_SB_GEMS;
Image* Sexy::IMAGE_SB_HEART_PLATE;
Image* Sexy::IMAGE_SB_HILIGHT_BAR;
Image* Sexy::IMAGE_SB_SCROLL_DOWN;
Image* Sexy::IMAGE_SB_SCROLL_UP;
Image* Sexy::IMAGE_SB_SECRETS;
Image* Sexy::IMAGE_SB_STAGE;
Image* Sexy::IMAGE_SB_STAGEBG;
Image* Sexy::IMAGE_SB_TIME;
Image* Sexy::IMAGE_SB_TOTAL_TIME;
Image* Sexy::IMAGE_SB_TREASURES;
Image* Sexy::IMAGE_TOK_TITLE;

bool Sexy::ExtractStatsBookResources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_MP_CLIPS = aMgr.GetImageThrow("IMAGE_MP_CLIPS");
		IMAGE_MP_FRAME = aMgr.GetImageThrow("IMAGE_MP_FRAME");
		IMAGE_MP_PLAY = aMgr.GetImageThrow("IMAGE_MP_PLAY");
		IMAGE_MP_TITLE = aMgr.GetImageThrow("IMAGE_MP_TITLE");
		IMAGE_SB_AREA = aMgr.GetImageThrow("IMAGE_SB_AREA");
		IMAGE_SB_BESTWORDS = aMgr.GetImageThrow("IMAGE_SB_BESTWORDS");
		IMAGE_SB_BGX = aMgr.GetImageThrow("IMAGE_SB_BGX");
		IMAGE_SB_BUTTON_MENU = aMgr.GetImageThrow("IMAGE_SB_BUTTON_MENU");
		IMAGE_SB_CHARACTER = aMgr.GetImageThrow("IMAGE_SB_CHARACTER");
		IMAGE_SB_CHARS_SEEN = aMgr.GetImageThrow("IMAGE_SB_CHARS_SEEN");
		IMAGE_SB_CLOCK = aMgr.GetImageThrow("IMAGE_SB_CLOCK");
		IMAGE_SB_ENEMY = aMgr.GetImageThrow("IMAGE_SB_ENEMY");
		IMAGE_SB_GAMEOVER = aMgr.GetImageThrow("IMAGE_SB_GAMEOVER");
		IMAGE_SB_GEMS = aMgr.GetImageThrow("IMAGE_SB_GEMS");
		IMAGE_SB_HEART_PLATE = aMgr.GetImageThrow("IMAGE_SB_HEART_PLATE");
		IMAGE_SB_HILIGHT_BAR = aMgr.GetImageThrow("IMAGE_SB_HILIGHT_BAR");
		IMAGE_SB_SCROLL_DOWN = aMgr.GetImageThrow("IMAGE_SB_SCROLL_DOWN");
		IMAGE_SB_SCROLL_UP = aMgr.GetImageThrow("IMAGE_SB_SCROLL_UP");
		IMAGE_SB_SECRETS = aMgr.GetImageThrow("IMAGE_SB_SECRETS");
		IMAGE_SB_STAGE = aMgr.GetImageThrow("IMAGE_SB_STAGE");
		IMAGE_SB_STAGEBG = aMgr.GetImageThrow("IMAGE_SB_STAGEBG");
		IMAGE_SB_TIME = aMgr.GetImageThrow("IMAGE_SB_TIME");
		IMAGE_SB_TOTAL_TIME = aMgr.GetImageThrow("IMAGE_SB_TOTAL_TIME");
		IMAGE_SB_TREASURES = aMgr.GetImageThrow("IMAGE_SB_TREASURES");
		IMAGE_TOK_TITLE = aMgr.GetImageThrow("IMAGE_TOK_TITLE");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// TitleAndMM Resources
Image* Sexy::IMAGE_MM_ADVENTURE;
Image* Sexy::IMAGE_MM_ADVENTURE_OVER;
Image* Sexy::IMAGE_MM_ADV_COMPLETE;
Image* Sexy::IMAGE_MM_ARENA;
Image* Sexy::IMAGE_MM_ARENA_OVER;
Image* Sexy::IMAGE_MM_BG;
Image* Sexy::IMAGE_MM_CLICKHERE;
Image* Sexy::IMAGE_MM_CNG_TITLE;
Image* Sexy::IMAGE_MM_EXP_PACK_AVAILABLE;
Image* Sexy::IMAGE_MM_FILM_REEL_DOWN;
Image* Sexy::IMAGE_MM_FILM_REEL_OVER;
Image* Sexy::IMAGE_MM_HIGHSCORES;
Image* Sexy::IMAGE_MM_HS_OVER;
Image* Sexy::IMAGE_MM_LOCKED_LEFT;
Image* Sexy::IMAGE_MM_LOCKED_RIGHT;
Image* Sexy::IMAGE_MM_LOGO;
Image* Sexy::IMAGE_MM_MINIGAMES;
Image* Sexy::IMAGE_MM_MINI_OVER;
Image* Sexy::IMAGE_MM_OPTIONS;
Image* Sexy::IMAGE_MM_OPTIONS_OVER;
Image* Sexy::IMAGE_MM_QUITGAME;
Image* Sexy::IMAGE_MM_QUIT_OVER;
Image* Sexy::IMAGE_MM_REALLY_QUIT_BANNER;
Image* Sexy::IMAGE_MM_REALLY_QUIT_WEEPY;
Image* Sexy::IMAGE_MM_SCROLL;
Image* Sexy::IMAGE_MM_SCROLLBACK;
Image* Sexy::IMAGE_MM_TOME;
Image* Sexy::IMAGE_MM_TOME_OVER;
Image* Sexy::IMAGE_MM_TOME_TEXT;
Image* Sexy::IMAGE_TS_DELUXE;
Image* Sexy::IMAGE_TS_POPCAP;
Image* Sexy::IMAGE_TS_TILE;

bool Sexy::ExtractTitleAndMMResources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_MM_ADVENTURE = aMgr.GetImageThrow("IMAGE_MM_ADVENTURE");
		IMAGE_MM_ADVENTURE_OVER = aMgr.GetImageThrow("IMAGE_MM_ADVENTURE_OVER");
		IMAGE_MM_ADV_COMPLETE = aMgr.GetImageThrow("IMAGE_MM_ADV_COMPLETE");
		IMAGE_MM_ARENA = aMgr.GetImageThrow("IMAGE_MM_ARENA");
		IMAGE_MM_ARENA_OVER = aMgr.GetImageThrow("IMAGE_MM_ARENA_OVER");
		IMAGE_MM_BG = aMgr.GetImageThrow("IMAGE_MM_BG");
		IMAGE_MM_CLICKHERE = aMgr.GetImageThrow("IMAGE_MM_CLICKHERE");
		IMAGE_MM_CNG_TITLE = aMgr.GetImageThrow("IMAGE_MM_CNG_TITLE");
		IMAGE_MM_EXP_PACK_AVAILABLE = aMgr.GetImageThrow("IMAGE_MM_EXP_PACK_AVAILABLE");
		IMAGE_MM_FILM_REEL_DOWN = aMgr.GetImageThrow("IMAGE_MM_FILM_REEL_DOWN");
		IMAGE_MM_FILM_REEL_OVER = aMgr.GetImageThrow("IMAGE_MM_FILM_REEL_OVER");
		IMAGE_MM_HIGHSCORES = aMgr.GetImageThrow("IMAGE_MM_HIGHSCORES");
		IMAGE_MM_HS_OVER = aMgr.GetImageThrow("IMAGE_MM_HS_OVER");
		IMAGE_MM_LOCKED_LEFT = aMgr.GetImageThrow("IMAGE_MM_LOCKED_LEFT");
		IMAGE_MM_LOCKED_RIGHT = aMgr.GetImageThrow("IMAGE_MM_LOCKED_RIGHT");
		IMAGE_MM_LOGO = aMgr.GetImageThrow("IMAGE_MM_LOGO");
		IMAGE_MM_MINIGAMES = aMgr.GetImageThrow("IMAGE_MM_MINIGAMES");
		IMAGE_MM_MINI_OVER = aMgr.GetImageThrow("IMAGE_MM_MINI_OVER");
		IMAGE_MM_OPTIONS = aMgr.GetImageThrow("IMAGE_MM_OPTIONS");
		IMAGE_MM_OPTIONS_OVER = aMgr.GetImageThrow("IMAGE_MM_OPTIONS_OVER");
		IMAGE_MM_QUITGAME = aMgr.GetImageThrow("IMAGE_MM_QUITGAME");
		IMAGE_MM_QUIT_OVER = aMgr.GetImageThrow("IMAGE_MM_QUIT_OVER");
		IMAGE_MM_REALLY_QUIT_BANNER = aMgr.GetImageThrow("IMAGE_MM_REALLY_QUIT_BANNER");
		IMAGE_MM_REALLY_QUIT_WEEPY = aMgr.GetImageThrow("IMAGE_MM_REALLY_QUIT_WEEPY");
		IMAGE_MM_SCROLL = aMgr.GetImageThrow("IMAGE_MM_SCROLL");
		IMAGE_MM_SCROLLBACK = aMgr.GetImageThrow("IMAGE_MM_SCROLLBACK");
		IMAGE_MM_TOME = aMgr.GetImageThrow("IMAGE_MM_TOME");
		IMAGE_MM_TOME_OVER = aMgr.GetImageThrow("IMAGE_MM_TOME_OVER");
		IMAGE_MM_TOME_TEXT = aMgr.GetImageThrow("IMAGE_MM_TOME_TEXT");
		IMAGE_TS_DELUXE = aMgr.GetImageThrow("IMAGE_TS_DELUXE");
		IMAGE_TS_POPCAP = aMgr.GetImageThrow("IMAGE_TS_POPCAP");
		IMAGE_TS_TILE = aMgr.GetImageThrow("IMAGE_TS_TILE");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// UpsellTrailer Resources
Image* Sexy::IMAGE_UT_ALTAR;
Image* Sexy::IMAGE_UT_ALTAR_GLOW1;
Image* Sexy::IMAGE_UT_ALTAR_GLOW2;
Image* Sexy::IMAGE_UT_ALTAR_GLOW3;
Image* Sexy::IMAGE_UT_ARENA_BG;
Image* Sexy::IMAGE_UT_ARENA_TEXT;
Image* Sexy::IMAGE_UT_BUY_BUTTON;
Image* Sexy::IMAGE_UT_BUY_NOW;
Image* Sexy::IMAGE_UT_GRASS;
Image* Sexy::IMAGE_UT_MONSTER_BG;
Image* Sexy::IMAGE_UT_NECRO_BG;
Image* Sexy::IMAGE_UT_NO_BUTTON;
Image* Sexy::IMAGE_UT_TEXT_BG;
Image* Sexy::IMAGE_UT_TILE_CRYSTAL;
Image* Sexy::IMAGE_UT_TILE_CRYSTAL_GLOW;
Image* Sexy::IMAGE_UT_TILE_DIAMOND;
Image* Sexy::IMAGE_UT_TILE_DIAMOND_GLOW;
Image* Sexy::IMAGE_UT_TILE_GARNET;
Image* Sexy::IMAGE_UT_TILE_GARNET_GLOW;
Image* Sexy::IMAGE_UT_TILE_GLINT_CRYSTAL;
Image* Sexy::IMAGE_UT_TILE_GLINT_DIAMOND;
Image* Sexy::IMAGE_UT_TILE_GLINT_GARNET;
Image* Sexy::IMAGE_UT_TILE_NORMAL;
Image* Sexy::IMAGE_UT_TREASURE1;
Image* Sexy::IMAGE_UT_TREASURE10;
Image* Sexy::IMAGE_UT_TREASURE11;
Image* Sexy::IMAGE_UT_TREASURE12;
Image* Sexy::IMAGE_UT_TREASURE13;
Image* Sexy::IMAGE_UT_TREASURE14;
Image* Sexy::IMAGE_UT_TREASURE15;
Image* Sexy::IMAGE_UT_TREASURE16;
Image* Sexy::IMAGE_UT_TREASURE17;
Image* Sexy::IMAGE_UT_TREASURE18;
Image* Sexy::IMAGE_UT_TREASURE19;
Image* Sexy::IMAGE_UT_TREASURE2;
Image* Sexy::IMAGE_UT_TREASURE20;
Image* Sexy::IMAGE_UT_TREASURE21;
Image* Sexy::IMAGE_UT_TREASURE22;
Image* Sexy::IMAGE_UT_TREASURE23;
Image* Sexy::IMAGE_UT_TREASURE24;
Image* Sexy::IMAGE_UT_TREASURE25;
Image* Sexy::IMAGE_UT_TREASURE26;
Image* Sexy::IMAGE_UT_TREASURE27;
Image* Sexy::IMAGE_UT_TREASURE28;
Image* Sexy::IMAGE_UT_TREASURE29;
Image* Sexy::IMAGE_UT_TREASURE3;
Image* Sexy::IMAGE_UT_TREASURE30;
Image* Sexy::IMAGE_UT_TREASURE4;
Image* Sexy::IMAGE_UT_TREASURE5;
Image* Sexy::IMAGE_UT_TREASURE6;
Image* Sexy::IMAGE_UT_TREASURE7;
Image* Sexy::IMAGE_UT_TREASURE8;
Image* Sexy::IMAGE_UT_TREASURE9;
Image* Sexy::IMAGE_UT_TREASURES_BG;
Image* Sexy::IMAGE_UT_TREASURE_BULB;
Image* Sexy::IMAGE_UT_TREASURE_BULB_HL;
Image* Sexy::IMAGE_UT_TRIAL_EXPIRED;
int Sexy::SOUND_UT_ATTACK_02;
int Sexy::SOUND_UT_BUY_NOW;
int Sexy::SOUND_UT_CHOMP;
int Sexy::SOUND_UT_GEMSPAWN;
int Sexy::SOUND_UT_LEX_ATTACK1;
int Sexy::SOUND_UT_LEX_ATTACK4;
int Sexy::SOUND_UT_LEX_ATTACK5;
int Sexy::SOUND_UT_NEW_TREASURE;
int Sexy::SOUND_UT_PETRIFY;
int Sexy::SOUND_UT_SLUMP;
int Sexy::SOUND_UT_WAIL_01;
int Sexy::SOUND_UT_WAIL_02;
int Sexy::SOUND_UT_WAIL_03;

bool Sexy::ExtractUpsellTrailerResources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_UT_ALTAR = aMgr.GetImageThrow("IMAGE_UT_ALTAR");
		IMAGE_UT_ALTAR_GLOW1 = aMgr.GetImageThrow("IMAGE_UT_ALTAR_GLOW1");
		IMAGE_UT_ALTAR_GLOW2 = aMgr.GetImageThrow("IMAGE_UT_ALTAR_GLOW2");
		IMAGE_UT_ALTAR_GLOW3 = aMgr.GetImageThrow("IMAGE_UT_ALTAR_GLOW3");
		IMAGE_UT_ARENA_BG = aMgr.GetImageThrow("IMAGE_UT_ARENA_BG");
		IMAGE_UT_ARENA_TEXT = aMgr.GetImageThrow("IMAGE_UT_ARENA_TEXT");
		IMAGE_UT_BUY_BUTTON = aMgr.GetImageThrow("IMAGE_UT_BUY_BUTTON");
		IMAGE_UT_BUY_NOW = aMgr.GetImageThrow("IMAGE_UT_BUY_NOW");
		IMAGE_UT_GRASS = aMgr.GetImageThrow("IMAGE_UT_GRASS");
		IMAGE_UT_MONSTER_BG = aMgr.GetImageThrow("IMAGE_UT_MONSTER_BG");
		IMAGE_UT_NECRO_BG = aMgr.GetImageThrow("IMAGE_UT_NECRO_BG");
		IMAGE_UT_NO_BUTTON = aMgr.GetImageThrow("IMAGE_UT_NO_BUTTON");
		IMAGE_UT_TEXT_BG = aMgr.GetImageThrow("IMAGE_UT_TEXT_BG");
		IMAGE_UT_TILE_CRYSTAL = aMgr.GetImageThrow("IMAGE_UT_TILE_CRYSTAL");
		IMAGE_UT_TILE_CRYSTAL_GLOW = aMgr.GetImageThrow("IMAGE_UT_TILE_CRYSTAL_GLOW");
		IMAGE_UT_TILE_DIAMOND = aMgr.GetImageThrow("IMAGE_UT_TILE_DIAMOND");
		IMAGE_UT_TILE_DIAMOND_GLOW = aMgr.GetImageThrow("IMAGE_UT_TILE_DIAMOND_GLOW");
		IMAGE_UT_TILE_GARNET = aMgr.GetImageThrow("IMAGE_UT_TILE_GARNET");
		IMAGE_UT_TILE_GARNET_GLOW = aMgr.GetImageThrow("IMAGE_UT_TILE_GARNET_GLOW");
		IMAGE_UT_TILE_GLINT_CRYSTAL = aMgr.GetImageThrow("IMAGE_UT_TILE_GLINT_CRYSTAL");
		IMAGE_UT_TILE_GLINT_DIAMOND = aMgr.GetImageThrow("IMAGE_UT_TILE_GLINT_DIAMOND");
		IMAGE_UT_TILE_GLINT_GARNET = aMgr.GetImageThrow("IMAGE_UT_TILE_GLINT_GARNET");
		IMAGE_UT_TILE_NORMAL = aMgr.GetImageThrow("IMAGE_UT_TILE_NORMAL");
		IMAGE_UT_TREASURE1 = aMgr.GetImageThrow("IMAGE_UT_TREASURE1");
		IMAGE_UT_TREASURE10 = aMgr.GetImageThrow("IMAGE_UT_TREASURE10");
		IMAGE_UT_TREASURE11 = aMgr.GetImageThrow("IMAGE_UT_TREASURE11");
		IMAGE_UT_TREASURE12 = aMgr.GetImageThrow("IMAGE_UT_TREASURE12");
		IMAGE_UT_TREASURE13 = aMgr.GetImageThrow("IMAGE_UT_TREASURE13");
		IMAGE_UT_TREASURE14 = aMgr.GetImageThrow("IMAGE_UT_TREASURE14");
		IMAGE_UT_TREASURE15 = aMgr.GetImageThrow("IMAGE_UT_TREASURE15");
		IMAGE_UT_TREASURE16 = aMgr.GetImageThrow("IMAGE_UT_TREASURE16");
		IMAGE_UT_TREASURE17 = aMgr.GetImageThrow("IMAGE_UT_TREASURE17");
		IMAGE_UT_TREASURE18 = aMgr.GetImageThrow("IMAGE_UT_TREASURE18");
		IMAGE_UT_TREASURE19 = aMgr.GetImageThrow("IMAGE_UT_TREASURE19");
		IMAGE_UT_TREASURE2 = aMgr.GetImageThrow("IMAGE_UT_TREASURE2");
		IMAGE_UT_TREASURE20 = aMgr.GetImageThrow("IMAGE_UT_TREASURE20");
		IMAGE_UT_TREASURE21 = aMgr.GetImageThrow("IMAGE_UT_TREASURE21");
		IMAGE_UT_TREASURE22 = aMgr.GetImageThrow("IMAGE_UT_TREASURE22");
		IMAGE_UT_TREASURE23 = aMgr.GetImageThrow("IMAGE_UT_TREASURE23");
		IMAGE_UT_TREASURE24 = aMgr.GetImageThrow("IMAGE_UT_TREASURE24");
		IMAGE_UT_TREASURE25 = aMgr.GetImageThrow("IMAGE_UT_TREASURE25");
		IMAGE_UT_TREASURE26 = aMgr.GetImageThrow("IMAGE_UT_TREASURE26");
		IMAGE_UT_TREASURE27 = aMgr.GetImageThrow("IMAGE_UT_TREASURE27");
		IMAGE_UT_TREASURE28 = aMgr.GetImageThrow("IMAGE_UT_TREASURE28");
		IMAGE_UT_TREASURE29 = aMgr.GetImageThrow("IMAGE_UT_TREASURE29");
		IMAGE_UT_TREASURE3 = aMgr.GetImageThrow("IMAGE_UT_TREASURE3");
		IMAGE_UT_TREASURE30 = aMgr.GetImageThrow("IMAGE_UT_TREASURE30");
		IMAGE_UT_TREASURE4 = aMgr.GetImageThrow("IMAGE_UT_TREASURE4");
		IMAGE_UT_TREASURE5 = aMgr.GetImageThrow("IMAGE_UT_TREASURE5");
		IMAGE_UT_TREASURE6 = aMgr.GetImageThrow("IMAGE_UT_TREASURE6");
		IMAGE_UT_TREASURE7 = aMgr.GetImageThrow("IMAGE_UT_TREASURE7");
		IMAGE_UT_TREASURE8 = aMgr.GetImageThrow("IMAGE_UT_TREASURE8");
		IMAGE_UT_TREASURE9 = aMgr.GetImageThrow("IMAGE_UT_TREASURE9");
		IMAGE_UT_TREASURES_BG = aMgr.GetImageThrow("IMAGE_UT_TREASURES_BG");
		IMAGE_UT_TREASURE_BULB = aMgr.GetImageThrow("IMAGE_UT_TREASURE_BULB");
		IMAGE_UT_TREASURE_BULB_HL = aMgr.GetImageThrow("IMAGE_UT_TREASURE_BULB_HL");
		IMAGE_UT_TRIAL_EXPIRED = aMgr.GetImageThrow("IMAGE_UT_TRIAL_EXPIRED");
		SOUND_UT_ATTACK_02 = aMgr.GetSoundThrow("SOUND_UT_ATTACK_02");
		SOUND_UT_BUY_NOW = aMgr.GetSoundThrow("SOUND_UT_BUY_NOW");
		SOUND_UT_CHOMP = aMgr.GetSoundThrow("SOUND_UT_CHOMP");
		SOUND_UT_GEMSPAWN = aMgr.GetSoundThrow("SOUND_UT_GEMSPAWN");
		SOUND_UT_LEX_ATTACK1 = aMgr.GetSoundThrow("SOUND_UT_LEX_ATTACK1");
		SOUND_UT_LEX_ATTACK4 = aMgr.GetSoundThrow("SOUND_UT_LEX_ATTACK4");
		SOUND_UT_LEX_ATTACK5 = aMgr.GetSoundThrow("SOUND_UT_LEX_ATTACK5");
		SOUND_UT_NEW_TREASURE = aMgr.GetSoundThrow("SOUND_UT_NEW_TREASURE");
		SOUND_UT_PETRIFY = aMgr.GetSoundThrow("SOUND_UT_PETRIFY");
		SOUND_UT_SLUMP = aMgr.GetSoundThrow("SOUND_UT_SLUMP");
		SOUND_UT_WAIL_01 = aMgr.GetSoundThrow("SOUND_UT_WAIL_01");
		SOUND_UT_WAIL_02 = aMgr.GetSoundThrow("SOUND_UT_WAIL_02");
		SOUND_UT_WAIL_03 = aMgr.GetSoundThrow("SOUND_UT_WAIL_03");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

static void* gResources[] =
{
	&FONT_SMALL,
	&FONT_MEDIUM,
	&FONT_MEDIUM_BOLD,
	&FONT_LARGE,
	&FONT_LARGE_OUTLINE,
	&FONT_HUGE,
	&FONT_TILE,
	&FONT_TILE_STATUS,
	&FONT_LARGER,
	&FONT_BANTER,
	&SOUND_CHOMP,
	&IMAGE_WAIT_BAR,
	&IMAGE_DIALOG_BANNER_MENU,
	&IMAGE_DIALOG_BANNER_NEWUSER,
	&IMAGE_DIALOG_BANNER_OPTIONS,
	&IMAGE_DIALOG_BANNER_RUSURE,
	&IMAGE_DIALOG_BANNER_HOWTOPLAY,
	&IMAGE_DIALOG_BANNER_LOADING,
	&IMAGE_DIALOG_BANNER_WELCOME,
	&IMAGE_DIALOG_DIVIDER_BOT,
	&IMAGE_DIALOG_DIVIDER_TOP,
	&IMAGE_DIALOG,
	&IMAGE_DIALOG_BUTTON,
	&IMAGE_DIALOG_CHECKBOX,
	&IMAGE_DIALOG_USER_ENTRY,
	&IMAGE_ARENA_WIN_BANNER,
	&IMAGE_FILM_REEL,
	&IMAGE_BANNER_CREDITS,
	&IMAGE_YELLOW_STAR,
	&IMAGE_ORANGE_STAR,
	&IMAGE_RED_STAR,
	&IMAGE_SLIDER_THUMB,
	&IMAGE_SLIDER_TRACK,
	&IMAGE_SLIDER_TRACK_VERT,
	&IMAGE_CUSTOM_POINTER,
	&IMAGE_CUSTOM_HAND,
	&IMAGE_CUSTOM_DRAGGING,
	&IMAGE_CUSTOM_TEXT,
	&IMAGE_CURTAIN_ANIM,
	&IMAGE_CURTAIN_CORD,
	&IMAGE_CURTAIN_TOP,
	&IMAGE_CREDITS_GRASS,
	&IMAGE_HOF_BG,
	&IMAGE_HOF_BANNER_BOSS,
	&IMAGE_HOF_BANNER_LR,
	&IMAGE_HOF_BANNER_LEX_POWER,
	&IMAGE_HOF_BANNER_LNS,
	&IMAGE_HOF_BANNER_TOP_10,
	&IMAGE_HOF_BANNER_WM,
	&IMAGE_HOF_BANNER_LEX_SKILL,
	&IMAGE_HOF_BTN_MAINMENU,
	&IMAGE_HOF_BTN_PLAYAGAIN,
	&IMAGE_HOF_BTN_MG_PREV,
	&IMAGE_HOF_BTN_MG_NEXT,
	&IMAGE_HOF_PANEL_2,
	&IMAGE_HOF_PANEL_3,
	&IMAGE_HOF_TAB_ADVENTURE,
	&IMAGE_HOF_TAB_ARENA,
	&IMAGE_HOF_TAB_MINIGAMES,
	&IMAGE_HOF_POWER_RATING,
	&IMAGE_TS_TILE,
	&IMAGE_TS_DELUXE,
	&IMAGE_TS_POPCAP,
	&IMAGE_MM_QUITGAME,
	&IMAGE_MM_SCROLL,
	&IMAGE_MM_SCROLLBACK,
	&IMAGE_MM_ADVENTURE,
	&IMAGE_MM_ARENA,
	&IMAGE_MM_MINIGAMES,
	&IMAGE_MM_BG,
	&IMAGE_MM_CLICKHERE,
	&IMAGE_MM_HIGHSCORES,
	&IMAGE_MM_LOGO,
	&IMAGE_MM_OPTIONS,
	&IMAGE_MM_OPTIONS_OVER,
	&IMAGE_MM_QUIT_OVER,
	&IMAGE_MM_ADVENTURE_OVER,
	&IMAGE_MM_MINI_OVER,
	&IMAGE_MM_ARENA_OVER,
	&IMAGE_MM_HS_OVER,
	&IMAGE_MM_TOME,
	&IMAGE_MM_TOME_OVER,
	&IMAGE_MM_TOME_TEXT,
	&IMAGE_MM_LOCKED_LEFT,
	&IMAGE_MM_LOCKED_RIGHT,
	&IMAGE_MM_ADV_COMPLETE,
	&IMAGE_MM_REALLY_QUIT_BANNER,
	&IMAGE_MM_REALLY_QUIT_WEEPY,
	&IMAGE_MM_EXP_PACK_AVAILABLE,
	&IMAGE_MM_CNG_TITLE,
	&IMAGE_MM_FILM_REEL_OVER,
	&IMAGE_MM_FILM_REEL_DOWN,
	&IMAGE_GRAYBAR_BG,
	&IMAGE_XP_BAR_EMPTY,
	&IMAGE_XP_BAR_FULL,
	&IMAGE_XP_BAR_EFFECT,
	&IMAGE_XP_BAR_EFFECT_WHITE,
	&IMAGE_HEARTS,
	&IMAGE_HEART_MASK,
	&IMAGE_HEART_MASK_CC,
	&IMAGE_HEARTBLINK,
	&IMAGE_HEARTBLINK_CC,
	&IMAGE_HEARTS_BG,
	&IMAGE_HEARTS_CC,
	&IMAGE_BOSS_BANNER,
	&IMAGE_BOSS_TEXT,
	&IMAGE_STATS_BOX,
	&IMAGE_TM_BONUS_TEXT,
	&IMAGE_TM_LEVELUP_TOKEN,
	&IMAGE_TM_LEVELUP_TOKEN_GOLD,
	&IMAGE_TM_INTRO_TITLE,
	&IMAGE_TM_SPOTLIGHT,
	&IMAGE_MAP_LEX_WARP,
	&IMAGE_MAP_MINIGAME_ANIM,
	&IMAGE_MINIGAME_ICON,
	&IMAGE_GS_SHIP1,
	&IMAGE_GS_SHIP2,
	&IMAGE_GS_SHIP3,
	&IMAGE_GS_SHIP4,
	&IMAGE_GS_SHIP1_WARPJET,
	&IMAGE_GS_GO,
	&IMAGE_LIBRARY_TITLE,
	&IMAGE_TREASURE_HILIGHT,
	&IMAGE_TREASURE_BOX,
	&IMAGE_TREASURE_BULB,
	&IMAGE_TREASURE_BG,
	&IMAGE_TREASURE_HINT,
	&IMAGE_TREASURE_BANNER,
	&IMAGE_BOOKSHELF_LEFT,
	&IMAGE_BOOKSHELF_RIGHT,
	&IMAGE_UI_BOTTOM,
	&IMAGE_UI_DESCRIPTION_BOX,
	&IMAGE_UI_LEFT,
	&IMAGE_UI_RIGHT,
	&IMAGE_UI_TOP,
	&IMAGE_TREASURE_TEXTBOX,
	&IMAGE_BANNER_LARGE,
	&IMAGE_BANNER_SMALL,
	&IMAGE_MAP_BOOK2,
	&IMAGE_LEX_ICON,
	&IMAGE_STATUE_CODEX,
	&IMAGE_STATUE_LEX,
	&IMAGE_MAP_CHECK,
	&IMAGE_RED_SPARKLE,
	&IMAGE_BLUE_SPARKLE,
	&IMAGE_WP_SPARKLE_SMALL,
	&IMAGE_WP_SPARKLE_MEDIUM,
	&IMAGE_HINT_ARROW_BOX,
	&IMAGE_HINT_ARROW_DOWN,
	&IMAGE_HINT_ARROW_LEFT,
	&IMAGE_HINT_ARROW_RIGHT,
	&IMAGE_HINT_ARROW_TITLE,
	&IMAGE_HINT_ARROW_UP,
	&IMAGE_HINT_ARROW_DOWNX,
	&IMAGE_HINT_ARROW_LEFTX,
	&IMAGE_HINT_ARROW_RIGHTX,
	&IMAGE_HINT_ARROW_UPX,
	&IMAGE_HINT_ARROW_GLOW_ADD,
	&IMAGE_TILE_PIPS,
	&IMAGE_TILE_BASIC,
	&IMAGE_WORDPOWER_GLOW_LEFT,
	&IMAGE_WORDPOWER_GLOW_RIGHT,
	&IMAGE_WORDPOWER_GLOW_MIDDLE,
	&IMAGE_WORDPOWER_GLOW_LEFT_SMALL,
	&IMAGE_WORDPOWER_GLOW_MIDDLE_SMALL,
	&IMAGE_WORDPOWER_GLOW_RIGHT_SMALL,
	&IMAGE_WORDPOWER_GLOW_INNER_LEFT,
	&IMAGE_WORDPOWER_GLOW_INNER_MID,
	&IMAGE_WORDPOWER_GLOW_INNER_RIGHT,
	&IMAGE_CUTSCENE_TOP,
	&IMAGE_CUTSCENE_BOTTOM,
	&IMAGE_TUT_PIC_CASS,
	&IMAGE_TUT_PIC_CASS_WORRY,
	&IMAGE_TUT_PIC_LEX,
	&IMAGE_TUT_PIC_LEX_WORRY,
	&IMAGE_TUT_PIC_HEPH,
	&IMAGE_TUT_PIC_CIRCE,
	&IMAGE_TUT_PIC_NEMESIS,
	&IMAGE_TUT_PIC_MOXIE,
	&IMAGE_TUT_PIC_CODEX,
	&IMAGE_TUT_ARROW,
	&IMAGE_TUT_MG_BUTTON,
	&IMAGE_TUT_TITLE,
	&IMAGE_TUT_PLAY_BLUR,
	&IMAGE_TUT_PLAY_DIAGRAM,
	&IMAGE_TUT_TREASURE_BLUR_BOX,
	&IMAGE_TUT_GRID_BOX,
	&IMAGE_TUT_SCRAMBLE_BOX,
	&IMAGE_TUT_CURTAIN_LEFT,
	&IMAGE_TUT_CURTAIN_RIGHT,
	&IMAGE_ITEM_ATTACK,
	&IMAGE_ITEM_ATTACK_NB,
	&IMAGE_ITEM_HEALTH,
	&IMAGE_ITEM_HEALTH_NB,
	&IMAGE_ITEM_PURIFY,
	&IMAGE_ITEM_PURIFY_NB,
	&IMAGE_STATUSTEXT_BLEEDING,
	&IMAGE_STATUSTEXT_BURNING,
	&IMAGE_STATUSTEXT_FROZEN,
	&IMAGE_STATUSTEXT_PETRIFIED,
	&IMAGE_STATUSTEXT_POISONED,
	&IMAGE_STATUSTEXT_POWERDOWN,
	&IMAGE_STATUSTEXT_POWERUP,
	&IMAGE_STATUSTEXT_SHIELDED,
	&IMAGE_STATUSTEXT_STUNNED,
	&IMAGE_STATUSTEXT_BONUS_WORD,
	&IMAGE_HEART_BITS,
	&IMAGE_IMPACT_LARGE,
	&IMAGE_IMPACT_SMALL,
	&IMAGE_STATUS_ICONS,
	&IMAGE_STUN_RESISTED,
	&IMAGE_POISON_RESISTED,
	&IMAGE_PETRIFY_RESISTED,
	&IMAGE_BURNING_RESISTED,
	&IMAGE_POWER_DOWN,
	&IMAGE_WORD_BUBBLE_LEFT,
	&IMAGE_WORD_BUBBLE_RIGHT,
	&IMAGE_WORD_BUBBLE,
	&IMAGE_WORD_BUBBLE_TEX,
	&IMAGE_WORD_BUBBLE_DOWN_ARROW,
	&IMAGE_OVERKILL_ANNIHILATED,
	&IMAGE_OVERKILL_CRUSHED,
	&IMAGE_OVERKILL_DECIMATED,
	&IMAGE_OVERKILL_DESTROYED,
	&IMAGE_OVERKILL_OBLITERATED,
	&IMAGE_OVERKILL_ROUTED,
	&IMAGE_OVERKILL_VANQUISHED,
	&IMAGE_OVERKILL_WHOMPED,
	&IMAGE_LOW_HEALTH_OUTLINE,
	&IMAGE_PAUSED_BANNER,
	&IMAGE_XPBAR_GLOW,
	&IMAGE_BUTTON_ATTACK,
	&IMAGE_BUTTON_MENU,
	&IMAGE_BUTTON_SCRAMBLE,
	&IMAGE_BUTTON_SCRAMBLE_SHADOW,
	&IMAGE_GRAVESTONE,
	&IMAGE_GRAVESTONE_GLOW,
	&IMAGE_GRAVESTONE_SMOKE,
	&IMAGE_TMA_UI_TOP,
	&IMAGE_COMBAT_UI_TOP,
	&IMAGE_COMBAT_UI_BOTTOM1,
	&IMAGE_COMBAT_UI_BOTTOM2,
	&IMAGE_POTION_PEDESTAL,
	&IMAGE_LORE_PLATE,
	&IMAGE_LORE_PLATE_LIT,
	&IMAGE_LORE_PLATE_TILABLE,
	&IMAGE_PROGRESS_METER,
	&IMAGE_ALTAR,
	&IMAGE_ALTAR_BUBBLE,
	&IMAGE_ALTAR_GLOW1,
	&IMAGE_ALTAR_GLOW2,
	&IMAGE_ALTAR_GLOW3,
	&IMAGE_UI_BOOK_OPTIONS_BUTTON,
	&IMAGE_UI_BOOK_BACK_BUTTON,
	&IMAGE_UI_BOOK_ENTER_BUTTON,
	&IMAGE_UI_BOOK_TS_CONTINUE_BUTTON,
	&IMAGE_UI_BOOK_HILIGHT,
	&IMAGE_UI_BOOK_AVAILABLE,
	&IMAGE_UI_BOOK_DOTS,
	&IMAGE_UI_BOOK_END_STATS_BOX,
	&IMAGE_UI_BOOK_END_STATS_TITLE,
	&IMAGE_LEVELUP_BANNER,
	&IMAGE_LEVELUP_TEXT,
	&IMAGE_LEVELUP_TROPHY,
	&IMAGE_LEVELUP_WATERMARK,
	&IMAGE_LEVELUP_ICONS,
	&IMAGE_LEVELUP_SPARKLE,
	&IMAGE_LEVELUP_STAR,
	&IMAGE_LEVELUP_TROPHY_GLOW,
	&IMAGE_LEVELUP_TROPHY_PARTICLES,
	&IMAGE_WS_PAPER,
	&IMAGE_WS_SCROLL,
	&IMAGE_WS_BESTWORD_TITLE,
	&SOUND_TILE_SELECT,
	&SOUND_CLICK1,
	&SOUND_CLICK2,
	&SOUND_SUBMIT_FAILED,
	&SOUND_GEMSPAWN,
	&SOUND_MM_ADVENTURE,
	&SOUND_MM_ARENA,
	&SOUND_MM_HS,
	&SOUND_MM_MINIGAMES,
	&SOUND_MM_OPTIONS,
	&SOUND_MM_QUIT,
	&SOUND_MM_TOK,
	&SOUND_MM_DONTLEAVE,
	&SOUND_MM_CNG,
	&SOUND_MM_BUY_NOW,
	&SOUND_TEXT_BLIP,
	&SOUND_CHACHING,
	&SOUND_CROWD_CHEER,
	&SOUND_FIREWORK1,
	&SOUND_FIREWORK2,
	&SOUND_LEX_LEVELUP,
	&SOUND_NEW_TREASURE,
	&SOUND_LEX_ATTACK1,
	&SOUND_LEX_ATTACK4,
	&SOUND_LEX_ATTACK5,
	&SOUND_LEX_ATTACK6,
	&SOUND_LEX_ATTACK7,
	&SOUND_LEX_BOSS_BATTLE,
	&SOUND_LEX_WARPIN,
	&SOUND_LEX_WARPOUT,
	&SOUND_LEX_WOW,
	&SOUND_LEX_ASTONISHING,
	&SOUND_LEX_AWESOME,
	&SOUND_LEX_EXCELLENT,
	&SOUND_LEX_FANTASTIC,
	&SOUND_LEX_GOOD,
	&SOUND_LEX_AUTOLOGICAL,
	&SOUND_LEX_VERYGOOD,
	&SOUND_LEX_NICE,
	&SOUND_LEX_INCREDIBLE,
	&SOUND_LEX_WATCHOUT,
	&SOUND_LEX_GIGGLE1,
	&SOUND_LEX_GIGGLE2,
	&SOUND_LEX_SNEEZE,
	&SOUND_LEX_BURP,
	&SOUND_SCRAMBLE,
	&SOUND_SLOWDOWN,
	&SOUND_LEX_ILOVEYOU,
	&SOUND_LEX_CASHMONEY,
	&SOUND_LEX_SHEEPBLEAT,
	&SOUND_3,
	&SOUND_2,
	&SOUND_1,
	&SOUND_GO,
	&SOUND_NEW_MINIGAME,
	&SOUND_WELCOME,
	&SOUND_COUNT,
	&SOUND_XP_STREAM,
	&SOUND_EFFECT_FIRE,
	&SOUND_EFFECT_POISON,
	&SOUND_EFFECT_FROZEN,
	&SOUND_EFFECT_PETRIFY,
	&SOUND_EFFECT_WEAKEN,
	&SOUND_POTION_HEAL,
	&SOUND_POTION_PURIFY,
	&SOUND_POTION_POWERUP,
	&SOUND_POTION_PICKUP,
	&SOUND_LOW_HEALTH,
	&SOUND_WORD_POWER,
	&SOUND_OVERKILL_ANNIHILATED,
	&SOUND_OVERKILL_CRUSHED,
	&SOUND_OVERKILL_DECIMATED,
	&SOUND_OVERKILL_DESTROYED,
	&SOUND_OVERKILL_OBLITERATED,
	&SOUND_OVERKILL_ROUTED,
	&SOUND_OVERKILL_VANQUISHED,
	&SOUND_OVERKILL_WHOMPED,
	&SOUND_POISON,
	&SOUND_STUN,
	&SOUND_TILESMASH,
	&SOUND_IMPACT_LARGE,
	&SOUND_IMPACT_SMALL,
	&SOUND_HEAL,
	&SOUND_POWERUP,
	&SOUND_POWERDOWN,
	&SOUND_FREEZE,
	&SOUND_TILELOCK,
	&SOUND_LIGHTNING,
	&SOUND_PLAGUE,
	&SOUND_PETRIFY,
	&SOUND_LEX_BITE,
	&IMAGE_MINICOMMON_BTN_SUBMIT,
	&IMAGE_MINICOMMON_TAB_RIGHT_DARK,
	&IMAGE_MINICOMMON_TAB_RIGHT_LIT,
	&IMAGE_MINICOMMON_LABEL_BONUS,
	&IMAGE_MINICOMMON_TENT_BG,
	&IMAGE_MINICOMMON_TITLE_BONUSROUND,
	&IMAGE_MINICOMMON_TITLE_TOOBAD,
	&IMAGE_MINICOMMON_TITLE_WELLDONE,
	&IMAGE_MINICOMMON_BANNER_NICE_TRY,
	&IMAGE_MINICOMMON_BANNER_WELL_DONE,
	&IMAGE_MINICOMMON_BANNER_WINNINGS,
	&IMAGE_MINICOMMON_BTN_CLICK_ANYWHERE,
	&IMAGE_MINICOMMON_WHITE_BG,
	&IMAGE_MINICOMMON_YELLOW_STAR,
	&IMAGE_MINICOMMON_ORANGE_STAR,
	&IMAGE_MINICOMMON_RED_STAR,
	&IMAGE_MINICOMMON_YELLOW_STAR_SAT,
	&IMAGE_MINICOMMON_ORANGE_STAR_SAT,
	&IMAGE_MINICOMMON_RED_STAR_SAT,
	&IMAGE_MINICOMMON_COUNTDOWN,
	&IMAGE_MINICOMMON_SCOREBOX,
	&IMAGE_MINICOMMON_GAMEOVER,
	&IMAGE_MINIMENU_TENT_BG,
	&IMAGE_MINIMENU_TITLE,
	&IMAGE_MINIMENU_PLAIN_BG,
	&IMAGE_MINIMENU_BTN_MAINMENU,
	&IMAGE_UT_GRASS,
	&IMAGE_UT_BUY_BUTTON,
	&IMAGE_UT_NO_BUTTON,
	&IMAGE_UT_BUY_NOW,
	&IMAGE_UT_TRIAL_EXPIRED,
	&IMAGE_UT_TEXT_BG,
	&IMAGE_UT_ALTAR,
	&IMAGE_UT_ALTAR_GLOW1,
	&IMAGE_UT_ALTAR_GLOW2,
	&IMAGE_UT_ALTAR_GLOW3,
	&IMAGE_UT_ARENA_TEXT,
	&IMAGE_UT_MONSTER_BG,
	&IMAGE_UT_NECRO_BG,
	&IMAGE_UT_TREASURES_BG,
	&IMAGE_UT_TREASURE1,
	&IMAGE_UT_TREASURE2,
	&IMAGE_UT_TREASURE3,
	&IMAGE_UT_TREASURE4,
	&IMAGE_UT_TREASURE5,
	&IMAGE_UT_TREASURE6,
	&IMAGE_UT_TREASURE7,
	&IMAGE_UT_TREASURE8,
	&IMAGE_UT_TREASURE9,
	&IMAGE_UT_TREASURE10,
	&IMAGE_UT_TREASURE11,
	&IMAGE_UT_TREASURE12,
	&IMAGE_UT_TREASURE13,
	&IMAGE_UT_TREASURE14,
	&IMAGE_UT_TREASURE15,
	&IMAGE_UT_TREASURE16,
	&IMAGE_UT_TREASURE17,
	&IMAGE_UT_TREASURE18,
	&IMAGE_UT_TREASURE19,
	&IMAGE_UT_TREASURE20,
	&IMAGE_UT_TREASURE21,
	&IMAGE_UT_TREASURE22,
	&IMAGE_UT_TREASURE23,
	&IMAGE_UT_TREASURE24,
	&IMAGE_UT_TREASURE25,
	&IMAGE_UT_TREASURE26,
	&IMAGE_UT_TREASURE27,
	&IMAGE_UT_TREASURE28,
	&IMAGE_UT_TREASURE29,
	&IMAGE_UT_TREASURE30,
	&IMAGE_UT_TREASURE_BULB,
	&IMAGE_UT_TREASURE_BULB_HL,
	&IMAGE_UT_TILE_CRYSTAL,
	&IMAGE_UT_TILE_DIAMOND,
	&IMAGE_UT_TILE_GARNET,
	&IMAGE_UT_TILE_NORMAL,
	&IMAGE_UT_TILE_GLINT_CRYSTAL,
	&IMAGE_UT_TILE_GLINT_DIAMOND,
	&IMAGE_UT_TILE_GLINT_GARNET,
	&IMAGE_UT_TILE_CRYSTAL_GLOW,
	&IMAGE_UT_TILE_DIAMOND_GLOW,
	&IMAGE_UT_TILE_GARNET_GLOW,
	&IMAGE_UT_ARENA_BG,
	&SOUND_UT_WAIL_02,
	&SOUND_UT_WAIL_03,
	&SOUND_UT_WAIL_01,
	&SOUND_UT_NEW_TREASURE,
	&SOUND_UT_PETRIFY,
	&SOUND_UT_GEMSPAWN,
	&SOUND_UT_ATTACK_02,
	&SOUND_UT_SLUMP,
	&SOUND_UT_CHOMP,
	&SOUND_UT_BUY_NOW,
	&SOUND_UT_LEX_ATTACK1,
	&SOUND_UT_LEX_ATTACK4,
	&SOUND_UT_LEX_ATTACK5,
	&IMAGE_SB_TOTAL_TIME,
	&IMAGE_SB_BGX,
	&IMAGE_SB_ENEMY,
	&IMAGE_SB_GAMEOVER,
	&IMAGE_SB_STAGE,
	&IMAGE_SB_STAGEBG,
	&IMAGE_SB_TIME,
	&IMAGE_SB_HILIGHT_BAR,
	&IMAGE_SB_CLOCK,
	&IMAGE_SB_BESTWORDS,
	&IMAGE_SB_HEART_PLATE,
	&IMAGE_TOK_TITLE,
	&IMAGE_SB_BUTTON_MENU,
	&IMAGE_SB_AREA,
	&IMAGE_SB_CHARACTER,
	&IMAGE_SB_CHARS_SEEN,
	&IMAGE_SB_GEMS,
	&IMAGE_SB_SECRETS,
	&IMAGE_SB_TREASURES,
	&IMAGE_SB_SCROLL_UP,
	&IMAGE_SB_SCROLL_DOWN,
	&IMAGE_MP_TITLE,
	&IMAGE_MP_FRAME,
	&IMAGE_MP_CLIPS,
	&IMAGE_MP_PLAY,
	NULL
};

Image* Sexy::LoadImageById(ResourceManager *theManager, int theId)
{
	return (*((Image**)gResources[theId]) = theManager->LoadImage(GetStringIdById(theId)));
}

void Sexy::ReplaceImageById(ResourceManager *theManager, int theId, Image *theImage)
{
	theManager->ReplaceImage(GetStringIdById(theId),theImage);
	*(Image**)gResources[theId] = theImage;
}

Image* Sexy::GetImageById(int theId)
{
	return *(Image**)gResources[theId];
}

Font* Sexy::GetFontById(int theId)
{
	return *(Font**)gResources[theId];
}

int Sexy::GetSoundById(int theId)
{
	return *(int*)gResources[theId];
}

Image*& Sexy::GetImageRefById(int theId)
{
	return *(Image**)gResources[theId];
}

Font*& Sexy::GetFontRefById(int theId)
{
	return *(Font**)gResources[theId];
}

int& Sexy::GetSoundRefById(int theId)
{
	return *(int*)gResources[theId];
}

static Sexy::ResourceId GetIdByVariable(const void *theVariable)
{
	typedef std::map<int,int> MyMap;
	static MyMap aMap;
	if(gNeedRecalcVariableToIdMap)
	{
		gNeedRecalcVariableToIdMap = false;
		aMap.clear();
		for(int i=0; i<RESOURCE_ID_MAX; i++)
			aMap[*(int*)gResources[i]] = i;
	}

	MyMap::iterator anItr = aMap.find((int)theVariable);
	if (anItr == aMap.end())
		return RESOURCE_ID_MAX;
	else
		return (ResourceId) anItr->second;
}

Sexy::ResourceId Sexy::GetIdByImage(Image *theImage)
{
	return GetIdByVariable(theImage);
}

Sexy::ResourceId Sexy::GetIdByFont(Font *theFont)
{
	return GetIdByVariable(theFont);
}

Sexy::ResourceId Sexy::GetIdBySound(int theSound)
{
	return GetIdByVariable((void*)theSound);
}

const char* Sexy::GetStringIdById(int theId)
{
	switch(theId)
	{
		case FONT_SMALL_ID: return "FONT_SMALL";
		case FONT_MEDIUM_ID: return "FONT_MEDIUM";
		case FONT_MEDIUM_BOLD_ID: return "FONT_MEDIUM_BOLD";
		case FONT_LARGE_ID: return "FONT_LARGE";
		case FONT_LARGE_OUTLINE_ID: return "FONT_LARGE_OUTLINE";
		case FONT_HUGE_ID: return "FONT_HUGE";
		case FONT_TILE_ID: return "FONT_TILE";
		case FONT_TILE_STATUS_ID: return "FONT_TILE_STATUS";
		case FONT_LARGER_ID: return "FONT_LARGER";
		case FONT_BANTER_ID: return "FONT_BANTER";
		case SOUND_CHOMP_ID: return "SOUND_CHOMP";
		case IMAGE_WAIT_BAR_ID: return "IMAGE_WAIT_BAR";
		case IMAGE_DIALOG_BANNER_MENU_ID: return "IMAGE_DIALOG_BANNER_MENU";
		case IMAGE_DIALOG_BANNER_NEWUSER_ID: return "IMAGE_DIALOG_BANNER_NEWUSER";
		case IMAGE_DIALOG_BANNER_OPTIONS_ID: return "IMAGE_DIALOG_BANNER_OPTIONS";
		case IMAGE_DIALOG_BANNER_RUSURE_ID: return "IMAGE_DIALOG_BANNER_RUSURE";
		case IMAGE_DIALOG_BANNER_HOWTOPLAY_ID: return "IMAGE_DIALOG_BANNER_HOWTOPLAY";
		case IMAGE_DIALOG_BANNER_LOADING_ID: return "IMAGE_DIALOG_BANNER_LOADING";
		case IMAGE_DIALOG_BANNER_WELCOME_ID: return "IMAGE_DIALOG_BANNER_WELCOME";
		case IMAGE_DIALOG_DIVIDER_BOT_ID: return "IMAGE_DIALOG_DIVIDER_BOT";
		case IMAGE_DIALOG_DIVIDER_TOP_ID: return "IMAGE_DIALOG_DIVIDER_TOP";
		case IMAGE_DIALOG_ID: return "IMAGE_DIALOG";
		case IMAGE_DIALOG_BUTTON_ID: return "IMAGE_DIALOG_BUTTON";
		case IMAGE_DIALOG_CHECKBOX_ID: return "IMAGE_DIALOG_CHECKBOX";
		case IMAGE_DIALOG_USER_ENTRY_ID: return "IMAGE_DIALOG_USER_ENTRY";
		case IMAGE_ARENA_WIN_BANNER_ID: return "IMAGE_ARENA_WIN_BANNER";
		case IMAGE_FILM_REEL_ID: return "IMAGE_FILM_REEL";
		case IMAGE_BANNER_CREDITS_ID: return "IMAGE_BANNER_CREDITS";
		case IMAGE_YELLOW_STAR_ID: return "IMAGE_YELLOW_STAR";
		case IMAGE_ORANGE_STAR_ID: return "IMAGE_ORANGE_STAR";
		case IMAGE_RED_STAR_ID: return "IMAGE_RED_STAR";
		case IMAGE_SLIDER_THUMB_ID: return "IMAGE_SLIDER_THUMB";
		case IMAGE_SLIDER_TRACK_ID: return "IMAGE_SLIDER_TRACK";
		case IMAGE_SLIDER_TRACK_VERT_ID: return "IMAGE_SLIDER_TRACK_VERT";
		case IMAGE_CUSTOM_POINTER_ID: return "IMAGE_CUSTOM_POINTER";
		case IMAGE_CUSTOM_HAND_ID: return "IMAGE_CUSTOM_HAND";
		case IMAGE_CUSTOM_DRAGGING_ID: return "IMAGE_CUSTOM_DRAGGING";
		case IMAGE_CUSTOM_TEXT_ID: return "IMAGE_CUSTOM_TEXT";
		case IMAGE_CURTAIN_ANIM_ID: return "IMAGE_CURTAIN_ANIM";
		case IMAGE_CURTAIN_CORD_ID: return "IMAGE_CURTAIN_CORD";
		case IMAGE_CURTAIN_TOP_ID: return "IMAGE_CURTAIN_TOP";
		case IMAGE_CREDITS_GRASS_ID: return "IMAGE_CREDITS_GRASS";
		case IMAGE_HOF_BG_ID: return "IMAGE_HOF_BG";
		case IMAGE_HOF_BANNER_BOSS_ID: return "IMAGE_HOF_BANNER_BOSS";
		case IMAGE_HOF_BANNER_LR_ID: return "IMAGE_HOF_BANNER_LR";
		case IMAGE_HOF_BANNER_LEX_POWER_ID: return "IMAGE_HOF_BANNER_LEX_POWER";
		case IMAGE_HOF_BANNER_LNS_ID: return "IMAGE_HOF_BANNER_LNS";
		case IMAGE_HOF_BANNER_TOP_10_ID: return "IMAGE_HOF_BANNER_TOP_10";
		case IMAGE_HOF_BANNER_WM_ID: return "IMAGE_HOF_BANNER_WM";
		case IMAGE_HOF_BANNER_LEX_SKILL_ID: return "IMAGE_HOF_BANNER_LEX_SKILL";
		case IMAGE_HOF_BTN_MAINMENU_ID: return "IMAGE_HOF_BTN_MAINMENU";
		case IMAGE_HOF_BTN_PLAYAGAIN_ID: return "IMAGE_HOF_BTN_PLAYAGAIN";
		case IMAGE_HOF_BTN_MG_PREV_ID: return "IMAGE_HOF_BTN_MG_PREV";
		case IMAGE_HOF_BTN_MG_NEXT_ID: return "IMAGE_HOF_BTN_MG_NEXT";
		case IMAGE_HOF_PANEL_2_ID: return "IMAGE_HOF_PANEL_2";
		case IMAGE_HOF_PANEL_3_ID: return "IMAGE_HOF_PANEL_3";
		case IMAGE_HOF_TAB_ADVENTURE_ID: return "IMAGE_HOF_TAB_ADVENTURE";
		case IMAGE_HOF_TAB_ARENA_ID: return "IMAGE_HOF_TAB_ARENA";
		case IMAGE_HOF_TAB_MINIGAMES_ID: return "IMAGE_HOF_TAB_MINIGAMES";
		case IMAGE_HOF_POWER_RATING_ID: return "IMAGE_HOF_POWER_RATING";
		case IMAGE_TS_TILE_ID: return "IMAGE_TS_TILE";
		case IMAGE_TS_DELUXE_ID: return "IMAGE_TS_DELUXE";
		case IMAGE_TS_POPCAP_ID: return "IMAGE_TS_POPCAP";
		case IMAGE_MM_QUITGAME_ID: return "IMAGE_MM_QUITGAME";
		case IMAGE_MM_SCROLL_ID: return "IMAGE_MM_SCROLL";
		case IMAGE_MM_SCROLLBACK_ID: return "IMAGE_MM_SCROLLBACK";
		case IMAGE_MM_ADVENTURE_ID: return "IMAGE_MM_ADVENTURE";
		case IMAGE_MM_ARENA_ID: return "IMAGE_MM_ARENA";
		case IMAGE_MM_MINIGAMES_ID: return "IMAGE_MM_MINIGAMES";
		case IMAGE_MM_BG_ID: return "IMAGE_MM_BG";
		case IMAGE_MM_CLICKHERE_ID: return "IMAGE_MM_CLICKHERE";
		case IMAGE_MM_HIGHSCORES_ID: return "IMAGE_MM_HIGHSCORES";
		case IMAGE_MM_LOGO_ID: return "IMAGE_MM_LOGO";
		case IMAGE_MM_OPTIONS_ID: return "IMAGE_MM_OPTIONS";
		case IMAGE_MM_OPTIONS_OVER_ID: return "IMAGE_MM_OPTIONS_OVER";
		case IMAGE_MM_QUIT_OVER_ID: return "IMAGE_MM_QUIT_OVER";
		case IMAGE_MM_ADVENTURE_OVER_ID: return "IMAGE_MM_ADVENTURE_OVER";
		case IMAGE_MM_MINI_OVER_ID: return "IMAGE_MM_MINI_OVER";
		case IMAGE_MM_ARENA_OVER_ID: return "IMAGE_MM_ARENA_OVER";
		case IMAGE_MM_HS_OVER_ID: return "IMAGE_MM_HS_OVER";
		case IMAGE_MM_TOME_ID: return "IMAGE_MM_TOME";
		case IMAGE_MM_TOME_OVER_ID: return "IMAGE_MM_TOME_OVER";
		case IMAGE_MM_TOME_TEXT_ID: return "IMAGE_MM_TOME_TEXT";
		case IMAGE_MM_LOCKED_LEFT_ID: return "IMAGE_MM_LOCKED_LEFT";
		case IMAGE_MM_LOCKED_RIGHT_ID: return "IMAGE_MM_LOCKED_RIGHT";
		case IMAGE_MM_ADV_COMPLETE_ID: return "IMAGE_MM_ADV_COMPLETE";
		case IMAGE_MM_REALLY_QUIT_BANNER_ID: return "IMAGE_MM_REALLY_QUIT_BANNER";
		case IMAGE_MM_REALLY_QUIT_WEEPY_ID: return "IMAGE_MM_REALLY_QUIT_WEEPY";
		case IMAGE_MM_EXP_PACK_AVAILABLE_ID: return "IMAGE_MM_EXP_PACK_AVAILABLE";
		case IMAGE_MM_CNG_TITLE_ID: return "IMAGE_MM_CNG_TITLE";
		case IMAGE_MM_FILM_REEL_OVER_ID: return "IMAGE_MM_FILM_REEL_OVER";
		case IMAGE_MM_FILM_REEL_DOWN_ID: return "IMAGE_MM_FILM_REEL_DOWN";
		case IMAGE_GRAYBAR_BG_ID: return "IMAGE_GRAYBAR_BG";
		case IMAGE_XP_BAR_EMPTY_ID: return "IMAGE_XP_BAR_EMPTY";
		case IMAGE_XP_BAR_FULL_ID: return "IMAGE_XP_BAR_FULL";
		case IMAGE_XP_BAR_EFFECT_ID: return "IMAGE_XP_BAR_EFFECT";
		case IMAGE_XP_BAR_EFFECT_WHITE_ID: return "IMAGE_XP_BAR_EFFECT_WHITE";
		case IMAGE_HEARTS_ID: return "IMAGE_HEARTS";
		case IMAGE_HEART_MASK_ID: return "IMAGE_HEART_MASK";
		case IMAGE_HEART_MASK_CC_ID: return "IMAGE_HEART_MASK_CC";
		case IMAGE_HEARTBLINK_ID: return "IMAGE_HEARTBLINK";
		case IMAGE_HEARTBLINK_CC_ID: return "IMAGE_HEARTBLINK_CC";
		case IMAGE_HEARTS_BG_ID: return "IMAGE_HEARTS_BG";
		case IMAGE_HEARTS_CC_ID: return "IMAGE_HEARTS_CC";
		case IMAGE_BOSS_BANNER_ID: return "IMAGE_BOSS_BANNER";
		case IMAGE_BOSS_TEXT_ID: return "IMAGE_BOSS_TEXT";
		case IMAGE_STATS_BOX_ID: return "IMAGE_STATS_BOX";
		case IMAGE_TM_BONUS_TEXT_ID: return "IMAGE_TM_BONUS_TEXT";
		case IMAGE_TM_LEVELUP_TOKEN_ID: return "IMAGE_TM_LEVELUP_TOKEN";
		case IMAGE_TM_LEVELUP_TOKEN_GOLD_ID: return "IMAGE_TM_LEVELUP_TOKEN_GOLD";
		case IMAGE_TM_INTRO_TITLE_ID: return "IMAGE_TM_INTRO_TITLE";
		case IMAGE_TM_SPOTLIGHT_ID: return "IMAGE_TM_SPOTLIGHT";
		case IMAGE_MAP_LEX_WARP_ID: return "IMAGE_MAP_LEX_WARP";
		case IMAGE_MAP_MINIGAME_ANIM_ID: return "IMAGE_MAP_MINIGAME_ANIM";
		case IMAGE_MINIGAME_ICON_ID: return "IMAGE_MINIGAME_ICON";
		case IMAGE_GS_SHIP1_ID: return "IMAGE_GS_SHIP1";
		case IMAGE_GS_SHIP2_ID: return "IMAGE_GS_SHIP2";
		case IMAGE_GS_SHIP3_ID: return "IMAGE_GS_SHIP3";
		case IMAGE_GS_SHIP4_ID: return "IMAGE_GS_SHIP4";
		case IMAGE_GS_SHIP1_WARPJET_ID: return "IMAGE_GS_SHIP1_WARPJET";
		case IMAGE_GS_GO_ID: return "IMAGE_GS_GO";
		case IMAGE_LIBRARY_TITLE_ID: return "IMAGE_LIBRARY_TITLE";
		case IMAGE_TREASURE_HILIGHT_ID: return "IMAGE_TREASURE_HILIGHT";
		case IMAGE_TREASURE_BOX_ID: return "IMAGE_TREASURE_BOX";
		case IMAGE_TREASURE_BULB_ID: return "IMAGE_TREASURE_BULB";
		case IMAGE_TREASURE_BG_ID: return "IMAGE_TREASURE_BG";
		case IMAGE_TREASURE_HINT_ID: return "IMAGE_TREASURE_HINT";
		case IMAGE_TREASURE_BANNER_ID: return "IMAGE_TREASURE_BANNER";
		case IMAGE_BOOKSHELF_LEFT_ID: return "IMAGE_BOOKSHELF_LEFT";
		case IMAGE_BOOKSHELF_RIGHT_ID: return "IMAGE_BOOKSHELF_RIGHT";
		case IMAGE_UI_BOTTOM_ID: return "IMAGE_UI_BOTTOM";
		case IMAGE_UI_DESCRIPTION_BOX_ID: return "IMAGE_UI_DESCRIPTION_BOX";
		case IMAGE_UI_LEFT_ID: return "IMAGE_UI_LEFT";
		case IMAGE_UI_RIGHT_ID: return "IMAGE_UI_RIGHT";
		case IMAGE_UI_TOP_ID: return "IMAGE_UI_TOP";
		case IMAGE_TREASURE_TEXTBOX_ID: return "IMAGE_TREASURE_TEXTBOX";
		case IMAGE_BANNER_LARGE_ID: return "IMAGE_BANNER_LARGE";
		case IMAGE_BANNER_SMALL_ID: return "IMAGE_BANNER_SMALL";
		case IMAGE_MAP_BOOK2_ID: return "IMAGE_MAP_BOOK2";
		case IMAGE_LEX_ICON_ID: return "IMAGE_LEX_ICON";
		case IMAGE_STATUE_CODEX_ID: return "IMAGE_STATUE_CODEX";
		case IMAGE_STATUE_LEX_ID: return "IMAGE_STATUE_LEX";
		case IMAGE_MAP_CHECK_ID: return "IMAGE_MAP_CHECK";
		case IMAGE_RED_SPARKLE_ID: return "IMAGE_RED_SPARKLE";
		case IMAGE_BLUE_SPARKLE_ID: return "IMAGE_BLUE_SPARKLE";
		case IMAGE_WP_SPARKLE_SMALL_ID: return "IMAGE_WP_SPARKLE_SMALL";
		case IMAGE_WP_SPARKLE_MEDIUM_ID: return "IMAGE_WP_SPARKLE_MEDIUM";
		case IMAGE_HINT_ARROW_BOX_ID: return "IMAGE_HINT_ARROW_BOX";
		case IMAGE_HINT_ARROW_DOWN_ID: return "IMAGE_HINT_ARROW_DOWN";
		case IMAGE_HINT_ARROW_LEFT_ID: return "IMAGE_HINT_ARROW_LEFT";
		case IMAGE_HINT_ARROW_RIGHT_ID: return "IMAGE_HINT_ARROW_RIGHT";
		case IMAGE_HINT_ARROW_TITLE_ID: return "IMAGE_HINT_ARROW_TITLE";
		case IMAGE_HINT_ARROW_UP_ID: return "IMAGE_HINT_ARROW_UP";
		case IMAGE_HINT_ARROW_DOWNX_ID: return "IMAGE_HINT_ARROW_DOWNX";
		case IMAGE_HINT_ARROW_LEFTX_ID: return "IMAGE_HINT_ARROW_LEFTX";
		case IMAGE_HINT_ARROW_RIGHTX_ID: return "IMAGE_HINT_ARROW_RIGHTX";
		case IMAGE_HINT_ARROW_UPX_ID: return "IMAGE_HINT_ARROW_UPX";
		case IMAGE_HINT_ARROW_GLOW_ADD_ID: return "IMAGE_HINT_ARROW_GLOW_ADD";
		case IMAGE_TILE_PIPS_ID: return "IMAGE_TILE_PIPS";
		case IMAGE_TILE_BASIC_ID: return "IMAGE_TILE_BASIC";
		case IMAGE_WORDPOWER_GLOW_LEFT_ID: return "IMAGE_WORDPOWER_GLOW_LEFT";
		case IMAGE_WORDPOWER_GLOW_RIGHT_ID: return "IMAGE_WORDPOWER_GLOW_RIGHT";
		case IMAGE_WORDPOWER_GLOW_MIDDLE_ID: return "IMAGE_WORDPOWER_GLOW_MIDDLE";
		case IMAGE_WORDPOWER_GLOW_LEFT_SMALL_ID: return "IMAGE_WORDPOWER_GLOW_LEFT_SMALL";
		case IMAGE_WORDPOWER_GLOW_MIDDLE_SMALL_ID: return "IMAGE_WORDPOWER_GLOW_MIDDLE_SMALL";
		case IMAGE_WORDPOWER_GLOW_RIGHT_SMALL_ID: return "IMAGE_WORDPOWER_GLOW_RIGHT_SMALL";
		case IMAGE_WORDPOWER_GLOW_INNER_LEFT_ID: return "IMAGE_WORDPOWER_GLOW_INNER_LEFT";
		case IMAGE_WORDPOWER_GLOW_INNER_MID_ID: return "IMAGE_WORDPOWER_GLOW_INNER_MID";
		case IMAGE_WORDPOWER_GLOW_INNER_RIGHT_ID: return "IMAGE_WORDPOWER_GLOW_INNER_RIGHT";
		case IMAGE_CUTSCENE_TOP_ID: return "IMAGE_CUTSCENE_TOP";
		case IMAGE_CUTSCENE_BOTTOM_ID: return "IMAGE_CUTSCENE_BOTTOM";
		case IMAGE_TUT_PIC_CASS_ID: return "IMAGE_TUT_PIC_CASS";
		case IMAGE_TUT_PIC_CASS_WORRY_ID: return "IMAGE_TUT_PIC_CASS_WORRY";
		case IMAGE_TUT_PIC_LEX_ID: return "IMAGE_TUT_PIC_LEX";
		case IMAGE_TUT_PIC_LEX_WORRY_ID: return "IMAGE_TUT_PIC_LEX_WORRY";
		case IMAGE_TUT_PIC_HEPH_ID: return "IMAGE_TUT_PIC_HEPH";
		case IMAGE_TUT_PIC_CIRCE_ID: return "IMAGE_TUT_PIC_CIRCE";
		case IMAGE_TUT_PIC_NEMESIS_ID: return "IMAGE_TUT_PIC_NEMESIS";
		case IMAGE_TUT_PIC_MOXIE_ID: return "IMAGE_TUT_PIC_MOXIE";
		case IMAGE_TUT_PIC_CODEX_ID: return "IMAGE_TUT_PIC_CODEX";
		case IMAGE_TUT_ARROW_ID: return "IMAGE_TUT_ARROW";
		case IMAGE_TUT_MG_BUTTON_ID: return "IMAGE_TUT_MG_BUTTON";
		case IMAGE_TUT_TITLE_ID: return "IMAGE_TUT_TITLE";
		case IMAGE_TUT_PLAY_BLUR_ID: return "IMAGE_TUT_PLAY_BLUR";
		case IMAGE_TUT_PLAY_DIAGRAM_ID: return "IMAGE_TUT_PLAY_DIAGRAM";
		case IMAGE_TUT_TREASURE_BLUR_BOX_ID: return "IMAGE_TUT_TREASURE_BLUR_BOX";
		case IMAGE_TUT_GRID_BOX_ID: return "IMAGE_TUT_GRID_BOX";
		case IMAGE_TUT_SCRAMBLE_BOX_ID: return "IMAGE_TUT_SCRAMBLE_BOX";
		case IMAGE_TUT_CURTAIN_LEFT_ID: return "IMAGE_TUT_CURTAIN_LEFT";
		case IMAGE_TUT_CURTAIN_RIGHT_ID: return "IMAGE_TUT_CURTAIN_RIGHT";
		case IMAGE_ITEM_ATTACK_ID: return "IMAGE_ITEM_ATTACK";
		case IMAGE_ITEM_ATTACK_NB_ID: return "IMAGE_ITEM_ATTACK_NB";
		case IMAGE_ITEM_HEALTH_ID: return "IMAGE_ITEM_HEALTH";
		case IMAGE_ITEM_HEALTH_NB_ID: return "IMAGE_ITEM_HEALTH_NB";
		case IMAGE_ITEM_PURIFY_ID: return "IMAGE_ITEM_PURIFY";
		case IMAGE_ITEM_PURIFY_NB_ID: return "IMAGE_ITEM_PURIFY_NB";
		case IMAGE_STATUSTEXT_BLEEDING_ID: return "IMAGE_STATUSTEXT_BLEEDING";
		case IMAGE_STATUSTEXT_BURNING_ID: return "IMAGE_STATUSTEXT_BURNING";
		case IMAGE_STATUSTEXT_FROZEN_ID: return "IMAGE_STATUSTEXT_FROZEN";
		case IMAGE_STATUSTEXT_PETRIFIED_ID: return "IMAGE_STATUSTEXT_PETRIFIED";
		case IMAGE_STATUSTEXT_POISONED_ID: return "IMAGE_STATUSTEXT_POISONED";
		case IMAGE_STATUSTEXT_POWERDOWN_ID: return "IMAGE_STATUSTEXT_POWERDOWN";
		case IMAGE_STATUSTEXT_POWERUP_ID: return "IMAGE_STATUSTEXT_POWERUP";
		case IMAGE_STATUSTEXT_SHIELDED_ID: return "IMAGE_STATUSTEXT_SHIELDED";
		case IMAGE_STATUSTEXT_STUNNED_ID: return "IMAGE_STATUSTEXT_STUNNED";
		case IMAGE_STATUSTEXT_BONUS_WORD_ID: return "IMAGE_STATUSTEXT_BONUS_WORD";
		case IMAGE_HEART_BITS_ID: return "IMAGE_HEART_BITS";
		case IMAGE_IMPACT_LARGE_ID: return "IMAGE_IMPACT_LARGE";
		case IMAGE_IMPACT_SMALL_ID: return "IMAGE_IMPACT_SMALL";
		case IMAGE_STATUS_ICONS_ID: return "IMAGE_STATUS_ICONS";
		case IMAGE_STUN_RESISTED_ID: return "IMAGE_STUN_RESISTED";
		case IMAGE_POISON_RESISTED_ID: return "IMAGE_POISON_RESISTED";
		case IMAGE_PETRIFY_RESISTED_ID: return "IMAGE_PETRIFY_RESISTED";
		case IMAGE_BURNING_RESISTED_ID: return "IMAGE_BURNING_RESISTED";
		case IMAGE_POWER_DOWN_ID: return "IMAGE_POWER_DOWN";
		case IMAGE_WORD_BUBBLE_LEFT_ID: return "IMAGE_WORD_BUBBLE_LEFT";
		case IMAGE_WORD_BUBBLE_RIGHT_ID: return "IMAGE_WORD_BUBBLE_RIGHT";
		case IMAGE_WORD_BUBBLE_ID: return "IMAGE_WORD_BUBBLE";
		case IMAGE_WORD_BUBBLE_TEX_ID: return "IMAGE_WORD_BUBBLE_TEX";
		case IMAGE_WORD_BUBBLE_DOWN_ARROW_ID: return "IMAGE_WORD_BUBBLE_DOWN_ARROW";
		case IMAGE_OVERKILL_ANNIHILATED_ID: return "IMAGE_OVERKILL_ANNIHILATED";
		case IMAGE_OVERKILL_CRUSHED_ID: return "IMAGE_OVERKILL_CRUSHED";
		case IMAGE_OVERKILL_DECIMATED_ID: return "IMAGE_OVERKILL_DECIMATED";
		case IMAGE_OVERKILL_DESTROYED_ID: return "IMAGE_OVERKILL_DESTROYED";
		case IMAGE_OVERKILL_OBLITERATED_ID: return "IMAGE_OVERKILL_OBLITERATED";
		case IMAGE_OVERKILL_ROUTED_ID: return "IMAGE_OVERKILL_ROUTED";
		case IMAGE_OVERKILL_VANQUISHED_ID: return "IMAGE_OVERKILL_VANQUISHED";
		case IMAGE_OVERKILL_WHOMPED_ID: return "IMAGE_OVERKILL_WHOMPED";
		case IMAGE_LOW_HEALTH_OUTLINE_ID: return "IMAGE_LOW_HEALTH_OUTLINE";
		case IMAGE_PAUSED_BANNER_ID: return "IMAGE_PAUSED_BANNER";
		case IMAGE_XPBAR_GLOW_ID: return "IMAGE_XPBAR_GLOW";
		case IMAGE_BUTTON_ATTACK_ID: return "IMAGE_BUTTON_ATTACK";
		case IMAGE_BUTTON_MENU_ID: return "IMAGE_BUTTON_MENU";
		case IMAGE_BUTTON_SCRAMBLE_ID: return "IMAGE_BUTTON_SCRAMBLE";
		case IMAGE_BUTTON_SCRAMBLE_SHADOW_ID: return "IMAGE_BUTTON_SCRAMBLE_SHADOW";
		case IMAGE_GRAVESTONE_ID: return "IMAGE_GRAVESTONE";
		case IMAGE_GRAVESTONE_GLOW_ID: return "IMAGE_GRAVESTONE_GLOW";
		case IMAGE_GRAVESTONE_SMOKE_ID: return "IMAGE_GRAVESTONE_SMOKE";
		case IMAGE_TMA_UI_TOP_ID: return "IMAGE_TMA_UI_TOP";
		case IMAGE_COMBAT_UI_TOP_ID: return "IMAGE_COMBAT_UI_TOP";
		case IMAGE_COMBAT_UI_BOTTOM1_ID: return "IMAGE_COMBAT_UI_BOTTOM1";
		case IMAGE_COMBAT_UI_BOTTOM2_ID: return "IMAGE_COMBAT_UI_BOTTOM2";
		case IMAGE_POTION_PEDESTAL_ID: return "IMAGE_POTION_PEDESTAL";
		case IMAGE_LORE_PLATE_ID: return "IMAGE_LORE_PLATE";
		case IMAGE_LORE_PLATE_LIT_ID: return "IMAGE_LORE_PLATE_LIT";
		case IMAGE_LORE_PLATE_TILABLE_ID: return "IMAGE_LORE_PLATE_TILABLE";
		case IMAGE_PROGRESS_METER_ID: return "IMAGE_PROGRESS_METER";
		case IMAGE_ALTAR_ID: return "IMAGE_ALTAR";
		case IMAGE_ALTAR_BUBBLE_ID: return "IMAGE_ALTAR_BUBBLE";
		case IMAGE_ALTAR_GLOW1_ID: return "IMAGE_ALTAR_GLOW1";
		case IMAGE_ALTAR_GLOW2_ID: return "IMAGE_ALTAR_GLOW2";
		case IMAGE_ALTAR_GLOW3_ID: return "IMAGE_ALTAR_GLOW3";
		case IMAGE_UI_BOOK_OPTIONS_BUTTON_ID: return "IMAGE_UI_BOOK_OPTIONS_BUTTON";
		case IMAGE_UI_BOOK_BACK_BUTTON_ID: return "IMAGE_UI_BOOK_BACK_BUTTON";
		case IMAGE_UI_BOOK_ENTER_BUTTON_ID: return "IMAGE_UI_BOOK_ENTER_BUTTON";
		case IMAGE_UI_BOOK_TS_CONTINUE_BUTTON_ID: return "IMAGE_UI_BOOK_TS_CONTINUE_BUTTON";
		case IMAGE_UI_BOOK_HILIGHT_ID: return "IMAGE_UI_BOOK_HILIGHT";
		case IMAGE_UI_BOOK_AVAILABLE_ID: return "IMAGE_UI_BOOK_AVAILABLE";
		case IMAGE_UI_BOOK_DOTS_ID: return "IMAGE_UI_BOOK_DOTS";
		case IMAGE_UI_BOOK_END_STATS_BOX_ID: return "IMAGE_UI_BOOK_END_STATS_BOX";
		case IMAGE_UI_BOOK_END_STATS_TITLE_ID: return "IMAGE_UI_BOOK_END_STATS_TITLE";
		case IMAGE_LEVELUP_BANNER_ID: return "IMAGE_LEVELUP_BANNER";
		case IMAGE_LEVELUP_TEXT_ID: return "IMAGE_LEVELUP_TEXT";
		case IMAGE_LEVELUP_TROPHY_ID: return "IMAGE_LEVELUP_TROPHY";
		case IMAGE_LEVELUP_WATERMARK_ID: return "IMAGE_LEVELUP_WATERMARK";
		case IMAGE_LEVELUP_ICONS_ID: return "IMAGE_LEVELUP_ICONS";
		case IMAGE_LEVELUP_SPARKLE_ID: return "IMAGE_LEVELUP_SPARKLE";
		case IMAGE_LEVELUP_STAR_ID: return "IMAGE_LEVELUP_STAR";
		case IMAGE_LEVELUP_TROPHY_GLOW_ID: return "IMAGE_LEVELUP_TROPHY_GLOW";
		case IMAGE_LEVELUP_TROPHY_PARTICLES_ID: return "IMAGE_LEVELUP_TROPHY_PARTICLES";
		case IMAGE_WS_PAPER_ID: return "IMAGE_WS_PAPER";
		case IMAGE_WS_SCROLL_ID: return "IMAGE_WS_SCROLL";
		case IMAGE_WS_BESTWORD_TITLE_ID: return "IMAGE_WS_BESTWORD_TITLE";
		case SOUND_TILE_SELECT_ID: return "SOUND_TILE_SELECT";
		case SOUND_CLICK1_ID: return "SOUND_CLICK1";
		case SOUND_CLICK2_ID: return "SOUND_CLICK2";
		case SOUND_SUBMIT_FAILED_ID: return "SOUND_SUBMIT_FAILED";
		case SOUND_GEMSPAWN_ID: return "SOUND_GEMSPAWN";
		case SOUND_MM_ADVENTURE_ID: return "SOUND_MM_ADVENTURE";
		case SOUND_MM_ARENA_ID: return "SOUND_MM_ARENA";
		case SOUND_MM_HS_ID: return "SOUND_MM_HS";
		case SOUND_MM_MINIGAMES_ID: return "SOUND_MM_MINIGAMES";
		case SOUND_MM_OPTIONS_ID: return "SOUND_MM_OPTIONS";
		case SOUND_MM_QUIT_ID: return "SOUND_MM_QUIT";
		case SOUND_MM_TOK_ID: return "SOUND_MM_TOK";
		case SOUND_MM_DONTLEAVE_ID: return "SOUND_MM_DONTLEAVE";
		case SOUND_MM_CNG_ID: return "SOUND_MM_CNG";
		case SOUND_MM_BUY_NOW_ID: return "SOUND_MM_BUY_NOW";
		case SOUND_TEXT_BLIP_ID: return "SOUND_TEXT_BLIP";
		case SOUND_CHACHING_ID: return "SOUND_CHACHING";
		case SOUND_CROWD_CHEER_ID: return "SOUND_CROWD_CHEER";
		case SOUND_FIREWORK1_ID: return "SOUND_FIREWORK1";
		case SOUND_FIREWORK2_ID: return "SOUND_FIREWORK2";
		case SOUND_LEX_LEVELUP_ID: return "SOUND_LEX_LEVELUP";
		case SOUND_NEW_TREASURE_ID: return "SOUND_NEW_TREASURE";
		case SOUND_LEX_ATTACK1_ID: return "SOUND_LEX_ATTACK1";
		case SOUND_LEX_ATTACK4_ID: return "SOUND_LEX_ATTACK4";
		case SOUND_LEX_ATTACK5_ID: return "SOUND_LEX_ATTACK5";
		case SOUND_LEX_ATTACK6_ID: return "SOUND_LEX_ATTACK6";
		case SOUND_LEX_ATTACK7_ID: return "SOUND_LEX_ATTACK7";
		case SOUND_LEX_BOSS_BATTLE_ID: return "SOUND_LEX_BOSS_BATTLE";
		case SOUND_LEX_WARPIN_ID: return "SOUND_LEX_WARPIN";
		case SOUND_LEX_WARPOUT_ID: return "SOUND_LEX_WARPOUT";
		case SOUND_LEX_WOW_ID: return "SOUND_LEX_WOW";
		case SOUND_LEX_ASTONISHING_ID: return "SOUND_LEX_ASTONISHING";
		case SOUND_LEX_AWESOME_ID: return "SOUND_LEX_AWESOME";
		case SOUND_LEX_EXCELLENT_ID: return "SOUND_LEX_EXCELLENT";
		case SOUND_LEX_FANTASTIC_ID: return "SOUND_LEX_FANTASTIC";
		case SOUND_LEX_GOOD_ID: return "SOUND_LEX_GOOD";
		case SOUND_LEX_AUTOLOGICAL_ID: return "SOUND_LEX_AUTOLOGICAL";
		case SOUND_LEX_VERYGOOD_ID: return "SOUND_LEX_VERYGOOD";
		case SOUND_LEX_NICE_ID: return "SOUND_LEX_NICE";
		case SOUND_LEX_INCREDIBLE_ID: return "SOUND_LEX_INCREDIBLE";
		case SOUND_LEX_WATCHOUT_ID: return "SOUND_LEX_WATCHOUT";
		case SOUND_LEX_GIGGLE1_ID: return "SOUND_LEX_GIGGLE1";
		case SOUND_LEX_GIGGLE2_ID: return "SOUND_LEX_GIGGLE2";
		case SOUND_LEX_SNEEZE_ID: return "SOUND_LEX_SNEEZE";
		case SOUND_LEX_BURP_ID: return "SOUND_LEX_BURP";
		case SOUND_SCRAMBLE_ID: return "SOUND_SCRAMBLE";
		case SOUND_SLOWDOWN_ID: return "SOUND_SLOWDOWN";
		case SOUND_LEX_ILOVEYOU_ID: return "SOUND_LEX_ILOVEYOU";
		case SOUND_LEX_CASHMONEY_ID: return "SOUND_LEX_CASHMONEY";
		case SOUND_LEX_SHEEPBLEAT_ID: return "SOUND_LEX_SHEEPBLEAT";
		case SOUND_3_ID: return "SOUND_3";
		case SOUND_2_ID: return "SOUND_2";
		case SOUND_1_ID: return "SOUND_1";
		case SOUND_GO_ID: return "SOUND_GO";
		case SOUND_NEW_MINIGAME_ID: return "SOUND_NEW_MINIGAME";
		case SOUND_WELCOME_ID: return "SOUND_WELCOME";
		case SOUND_COUNT_ID: return "SOUND_COUNT";
		case SOUND_XP_STREAM_ID: return "SOUND_XP_STREAM";
		case SOUND_EFFECT_FIRE_ID: return "SOUND_EFFECT_FIRE";
		case SOUND_EFFECT_POISON_ID: return "SOUND_EFFECT_POISON";
		case SOUND_EFFECT_FROZEN_ID: return "SOUND_EFFECT_FROZEN";
		case SOUND_EFFECT_PETRIFY_ID: return "SOUND_EFFECT_PETRIFY";
		case SOUND_EFFECT_WEAKEN_ID: return "SOUND_EFFECT_WEAKEN";
		case SOUND_POTION_HEAL_ID: return "SOUND_POTION_HEAL";
		case SOUND_POTION_PURIFY_ID: return "SOUND_POTION_PURIFY";
		case SOUND_POTION_POWERUP_ID: return "SOUND_POTION_POWERUP";
		case SOUND_POTION_PICKUP_ID: return "SOUND_POTION_PICKUP";
		case SOUND_LOW_HEALTH_ID: return "SOUND_LOW_HEALTH";
		case SOUND_WORD_POWER_ID: return "SOUND_WORD_POWER";
		case SOUND_OVERKILL_ANNIHILATED_ID: return "SOUND_OVERKILL_ANNIHILATED";
		case SOUND_OVERKILL_CRUSHED_ID: return "SOUND_OVERKILL_CRUSHED";
		case SOUND_OVERKILL_DECIMATED_ID: return "SOUND_OVERKILL_DECIMATED";
		case SOUND_OVERKILL_DESTROYED_ID: return "SOUND_OVERKILL_DESTROYED";
		case SOUND_OVERKILL_OBLITERATED_ID: return "SOUND_OVERKILL_OBLITERATED";
		case SOUND_OVERKILL_ROUTED_ID: return "SOUND_OVERKILL_ROUTED";
		case SOUND_OVERKILL_VANQUISHED_ID: return "SOUND_OVERKILL_VANQUISHED";
		case SOUND_OVERKILL_WHOMPED_ID: return "SOUND_OVERKILL_WHOMPED";
		case SOUND_POISON_ID: return "SOUND_POISON";
		case SOUND_STUN_ID: return "SOUND_STUN";
		case SOUND_TILESMASH_ID: return "SOUND_TILESMASH";
		case SOUND_IMPACT_LARGE_ID: return "SOUND_IMPACT_LARGE";
		case SOUND_IMPACT_SMALL_ID: return "SOUND_IMPACT_SMALL";
		case SOUND_HEAL_ID: return "SOUND_HEAL";
		case SOUND_POWERUP_ID: return "SOUND_POWERUP";
		case SOUND_POWERDOWN_ID: return "SOUND_POWERDOWN";
		case SOUND_FREEZE_ID: return "SOUND_FREEZE";
		case SOUND_TILELOCK_ID: return "SOUND_TILELOCK";
		case SOUND_LIGHTNING_ID: return "SOUND_LIGHTNING";
		case SOUND_PLAGUE_ID: return "SOUND_PLAGUE";
		case SOUND_PETRIFY_ID: return "SOUND_PETRIFY";
		case SOUND_LEX_BITE_ID: return "SOUND_LEX_BITE";
		case IMAGE_MINICOMMON_BTN_SUBMIT_ID: return "IMAGE_MINICOMMON_BTN_SUBMIT";
		case IMAGE_MINICOMMON_TAB_RIGHT_DARK_ID: return "IMAGE_MINICOMMON_TAB_RIGHT_DARK";
		case IMAGE_MINICOMMON_TAB_RIGHT_LIT_ID: return "IMAGE_MINICOMMON_TAB_RIGHT_LIT";
		case IMAGE_MINICOMMON_LABEL_BONUS_ID: return "IMAGE_MINICOMMON_LABEL_BONUS";
		case IMAGE_MINICOMMON_TENT_BG_ID: return "IMAGE_MINICOMMON_TENT_BG";
		case IMAGE_MINICOMMON_TITLE_BONUSROUND_ID: return "IMAGE_MINICOMMON_TITLE_BONUSROUND";
		case IMAGE_MINICOMMON_TITLE_TOOBAD_ID: return "IMAGE_MINICOMMON_TITLE_TOOBAD";
		case IMAGE_MINICOMMON_TITLE_WELLDONE_ID: return "IMAGE_MINICOMMON_TITLE_WELLDONE";
		case IMAGE_MINICOMMON_BANNER_NICE_TRY_ID: return "IMAGE_MINICOMMON_BANNER_NICE_TRY";
		case IMAGE_MINICOMMON_BANNER_WELL_DONE_ID: return "IMAGE_MINICOMMON_BANNER_WELL_DONE";
		case IMAGE_MINICOMMON_BANNER_WINNINGS_ID: return "IMAGE_MINICOMMON_BANNER_WINNINGS";
		case IMAGE_MINICOMMON_BTN_CLICK_ANYWHERE_ID: return "IMAGE_MINICOMMON_BTN_CLICK_ANYWHERE";
		case IMAGE_MINICOMMON_WHITE_BG_ID: return "IMAGE_MINICOMMON_WHITE_BG";
		case IMAGE_MINICOMMON_YELLOW_STAR_ID: return "IMAGE_MINICOMMON_YELLOW_STAR";
		case IMAGE_MINICOMMON_ORANGE_STAR_ID: return "IMAGE_MINICOMMON_ORANGE_STAR";
		case IMAGE_MINICOMMON_RED_STAR_ID: return "IMAGE_MINICOMMON_RED_STAR";
		case IMAGE_MINICOMMON_YELLOW_STAR_SAT_ID: return "IMAGE_MINICOMMON_YELLOW_STAR_SAT";
		case IMAGE_MINICOMMON_ORANGE_STAR_SAT_ID: return "IMAGE_MINICOMMON_ORANGE_STAR_SAT";
		case IMAGE_MINICOMMON_RED_STAR_SAT_ID: return "IMAGE_MINICOMMON_RED_STAR_SAT";
		case IMAGE_MINICOMMON_COUNTDOWN_ID: return "IMAGE_MINICOMMON_COUNTDOWN";
		case IMAGE_MINICOMMON_SCOREBOX_ID: return "IMAGE_MINICOMMON_SCOREBOX";
		case IMAGE_MINICOMMON_GAMEOVER_ID: return "IMAGE_MINICOMMON_GAMEOVER";
		case IMAGE_MINIMENU_TENT_BG_ID: return "IMAGE_MINIMENU_TENT_BG";
		case IMAGE_MINIMENU_TITLE_ID: return "IMAGE_MINIMENU_TITLE";
		case IMAGE_MINIMENU_PLAIN_BG_ID: return "IMAGE_MINIMENU_PLAIN_BG";
		case IMAGE_MINIMENU_BTN_MAINMENU_ID: return "IMAGE_MINIMENU_BTN_MAINMENU";
		case IMAGE_UT_GRASS_ID: return "IMAGE_UT_GRASS";
		case IMAGE_UT_BUY_BUTTON_ID: return "IMAGE_UT_BUY_BUTTON";
		case IMAGE_UT_NO_BUTTON_ID: return "IMAGE_UT_NO_BUTTON";
		case IMAGE_UT_BUY_NOW_ID: return "IMAGE_UT_BUY_NOW";
		case IMAGE_UT_TRIAL_EXPIRED_ID: return "IMAGE_UT_TRIAL_EXPIRED";
		case IMAGE_UT_TEXT_BG_ID: return "IMAGE_UT_TEXT_BG";
		case IMAGE_UT_ALTAR_ID: return "IMAGE_UT_ALTAR";
		case IMAGE_UT_ALTAR_GLOW1_ID: return "IMAGE_UT_ALTAR_GLOW1";
		case IMAGE_UT_ALTAR_GLOW2_ID: return "IMAGE_UT_ALTAR_GLOW2";
		case IMAGE_UT_ALTAR_GLOW3_ID: return "IMAGE_UT_ALTAR_GLOW3";
		case IMAGE_UT_ARENA_TEXT_ID: return "IMAGE_UT_ARENA_TEXT";
		case IMAGE_UT_MONSTER_BG_ID: return "IMAGE_UT_MONSTER_BG";
		case IMAGE_UT_NECRO_BG_ID: return "IMAGE_UT_NECRO_BG";
		case IMAGE_UT_TREASURES_BG_ID: return "IMAGE_UT_TREASURES_BG";
		case IMAGE_UT_TREASURE1_ID: return "IMAGE_UT_TREASURE1";
		case IMAGE_UT_TREASURE2_ID: return "IMAGE_UT_TREASURE2";
		case IMAGE_UT_TREASURE3_ID: return "IMAGE_UT_TREASURE3";
		case IMAGE_UT_TREASURE4_ID: return "IMAGE_UT_TREASURE4";
		case IMAGE_UT_TREASURE5_ID: return "IMAGE_UT_TREASURE5";
		case IMAGE_UT_TREASURE6_ID: return "IMAGE_UT_TREASURE6";
		case IMAGE_UT_TREASURE7_ID: return "IMAGE_UT_TREASURE7";
		case IMAGE_UT_TREASURE8_ID: return "IMAGE_UT_TREASURE8";
		case IMAGE_UT_TREASURE9_ID: return "IMAGE_UT_TREASURE9";
		case IMAGE_UT_TREASURE10_ID: return "IMAGE_UT_TREASURE10";
		case IMAGE_UT_TREASURE11_ID: return "IMAGE_UT_TREASURE11";
		case IMAGE_UT_TREASURE12_ID: return "IMAGE_UT_TREASURE12";
		case IMAGE_UT_TREASURE13_ID: return "IMAGE_UT_TREASURE13";
		case IMAGE_UT_TREASURE14_ID: return "IMAGE_UT_TREASURE14";
		case IMAGE_UT_TREASURE15_ID: return "IMAGE_UT_TREASURE15";
		case IMAGE_UT_TREASURE16_ID: return "IMAGE_UT_TREASURE16";
		case IMAGE_UT_TREASURE17_ID: return "IMAGE_UT_TREASURE17";
		case IMAGE_UT_TREASURE18_ID: return "IMAGE_UT_TREASURE18";
		case IMAGE_UT_TREASURE19_ID: return "IMAGE_UT_TREASURE19";
		case IMAGE_UT_TREASURE20_ID: return "IMAGE_UT_TREASURE20";
		case IMAGE_UT_TREASURE21_ID: return "IMAGE_UT_TREASURE21";
		case IMAGE_UT_TREASURE22_ID: return "IMAGE_UT_TREASURE22";
		case IMAGE_UT_TREASURE23_ID: return "IMAGE_UT_TREASURE23";
		case IMAGE_UT_TREASURE24_ID: return "IMAGE_UT_TREASURE24";
		case IMAGE_UT_TREASURE25_ID: return "IMAGE_UT_TREASURE25";
		case IMAGE_UT_TREASURE26_ID: return "IMAGE_UT_TREASURE26";
		case IMAGE_UT_TREASURE27_ID: return "IMAGE_UT_TREASURE27";
		case IMAGE_UT_TREASURE28_ID: return "IMAGE_UT_TREASURE28";
		case IMAGE_UT_TREASURE29_ID: return "IMAGE_UT_TREASURE29";
		case IMAGE_UT_TREASURE30_ID: return "IMAGE_UT_TREASURE30";
		case IMAGE_UT_TREASURE_BULB_ID: return "IMAGE_UT_TREASURE_BULB";
		case IMAGE_UT_TREASURE_BULB_HL_ID: return "IMAGE_UT_TREASURE_BULB_HL";
		case IMAGE_UT_TILE_CRYSTAL_ID: return "IMAGE_UT_TILE_CRYSTAL";
		case IMAGE_UT_TILE_DIAMOND_ID: return "IMAGE_UT_TILE_DIAMOND";
		case IMAGE_UT_TILE_GARNET_ID: return "IMAGE_UT_TILE_GARNET";
		case IMAGE_UT_TILE_NORMAL_ID: return "IMAGE_UT_TILE_NORMAL";
		case IMAGE_UT_TILE_GLINT_CRYSTAL_ID: return "IMAGE_UT_TILE_GLINT_CRYSTAL";
		case IMAGE_UT_TILE_GLINT_DIAMOND_ID: return "IMAGE_UT_TILE_GLINT_DIAMOND";
		case IMAGE_UT_TILE_GLINT_GARNET_ID: return "IMAGE_UT_TILE_GLINT_GARNET";
		case IMAGE_UT_TILE_CRYSTAL_GLOW_ID: return "IMAGE_UT_TILE_CRYSTAL_GLOW";
		case IMAGE_UT_TILE_DIAMOND_GLOW_ID: return "IMAGE_UT_TILE_DIAMOND_GLOW";
		case IMAGE_UT_TILE_GARNET_GLOW_ID: return "IMAGE_UT_TILE_GARNET_GLOW";
		case IMAGE_UT_ARENA_BG_ID: return "IMAGE_UT_ARENA_BG";
		case SOUND_UT_WAIL_02_ID: return "SOUND_UT_WAIL_02";
		case SOUND_UT_WAIL_03_ID: return "SOUND_UT_WAIL_03";
		case SOUND_UT_WAIL_01_ID: return "SOUND_UT_WAIL_01";
		case SOUND_UT_NEW_TREASURE_ID: return "SOUND_UT_NEW_TREASURE";
		case SOUND_UT_PETRIFY_ID: return "SOUND_UT_PETRIFY";
		case SOUND_UT_GEMSPAWN_ID: return "SOUND_UT_GEMSPAWN";
		case SOUND_UT_ATTACK_02_ID: return "SOUND_UT_ATTACK_02";
		case SOUND_UT_SLUMP_ID: return "SOUND_UT_SLUMP";
		case SOUND_UT_CHOMP_ID: return "SOUND_UT_CHOMP";
		case SOUND_UT_BUY_NOW_ID: return "SOUND_UT_BUY_NOW";
		case SOUND_UT_LEX_ATTACK1_ID: return "SOUND_UT_LEX_ATTACK1";
		case SOUND_UT_LEX_ATTACK4_ID: return "SOUND_UT_LEX_ATTACK4";
		case SOUND_UT_LEX_ATTACK5_ID: return "SOUND_UT_LEX_ATTACK5";
		case IMAGE_SB_TOTAL_TIME_ID: return "IMAGE_SB_TOTAL_TIME";
		case IMAGE_SB_BGX_ID: return "IMAGE_SB_BGX";
		case IMAGE_SB_ENEMY_ID: return "IMAGE_SB_ENEMY";
		case IMAGE_SB_GAMEOVER_ID: return "IMAGE_SB_GAMEOVER";
		case IMAGE_SB_STAGE_ID: return "IMAGE_SB_STAGE";
		case IMAGE_SB_STAGEBG_ID: return "IMAGE_SB_STAGEBG";
		case IMAGE_SB_TIME_ID: return "IMAGE_SB_TIME";
		case IMAGE_SB_HILIGHT_BAR_ID: return "IMAGE_SB_HILIGHT_BAR";
		case IMAGE_SB_CLOCK_ID: return "IMAGE_SB_CLOCK";
		case IMAGE_SB_BESTWORDS_ID: return "IMAGE_SB_BESTWORDS";
		case IMAGE_SB_HEART_PLATE_ID: return "IMAGE_SB_HEART_PLATE";
		case IMAGE_TOK_TITLE_ID: return "IMAGE_TOK_TITLE";
		case IMAGE_SB_BUTTON_MENU_ID: return "IMAGE_SB_BUTTON_MENU";
		case IMAGE_SB_AREA_ID: return "IMAGE_SB_AREA";
		case IMAGE_SB_CHARACTER_ID: return "IMAGE_SB_CHARACTER";
		case IMAGE_SB_CHARS_SEEN_ID: return "IMAGE_SB_CHARS_SEEN";
		case IMAGE_SB_GEMS_ID: return "IMAGE_SB_GEMS";
		case IMAGE_SB_SECRETS_ID: return "IMAGE_SB_SECRETS";
		case IMAGE_SB_TREASURES_ID: return "IMAGE_SB_TREASURES";
		case IMAGE_SB_SCROLL_UP_ID: return "IMAGE_SB_SCROLL_UP";
		case IMAGE_SB_SCROLL_DOWN_ID: return "IMAGE_SB_SCROLL_DOWN";
		case IMAGE_MP_TITLE_ID: return "IMAGE_MP_TITLE";
		case IMAGE_MP_FRAME_ID: return "IMAGE_MP_FRAME";
		case IMAGE_MP_CLIPS_ID: return "IMAGE_MP_CLIPS";
		case IMAGE_MP_PLAY_ID: return "IMAGE_MP_PLAY";
		default: return "";
	}
}

