#ifndef __Book5_H__
#define __Book5_H__

namespace Sexy
{
	class ResourceManager;
	class Image;
	class Font;

	Image* LoadImageById(ResourceManager *theManager, int theId);
	void ReplaceImageById(ResourceManager *theManager, int theId, Image *theImage);
	bool ExtractResourcesByName(ResourceManager *theManager, const char *theName);

	// BOOK5Common Resources
	bool ExtractBOOK5CommonResources(ResourceManager *theMgr);
	extern Image* IMAGE_B4_LEFT_FACING_ARROW;

	// Book4Chapter1 Resources
	bool ExtractBook4Chapter1Resources(ResourceManager *theMgr);
	extern Image* IMAGE_B4A_BG1;
	extern int SOUND_BOOK4_CH1_BOVINE_ATTACK1;
	extern int SOUND_BOOK4_CH1_BOVINE_ATTACK2;
	extern int SOUND_BOOK4_CH1_BOVINE_IMPACT;
	extern int SOUND_BOOK4_CH1_FELINE_ENGAGE;
	extern int SOUND_BOOK4_CH1_FELINE_ROAR;
	extern int SOUND_BOOK4_CH1_FIRE_6;
	extern int SOUND_BOOK4_CH1_PLATE_ATTACK2;
	extern int SOUND_BOOK4_CH1_PLATE_ATTACK3;
	extern int SOUND_BOOK4_CH1_PLATE_IMPACT3;
	extern int SOUND_BOOK4_CH1_PLATE_IMPACT4;
	extern int SOUND_BOOK4_CH1_PLATE_IMPACT5;
	extern int SOUND_BOOK4_CH1_PLATE_IMPACT6;
	extern int SOUND_BOOK4_CH1_SPARKLE_ATTACK;
	extern int SOUND_BOOK4_CH1_STRING_ATTACK;
	extern int SOUND_BOOK4_CH1_STRING_DEATH;
	extern int SOUND_BOOK4_CH1_STRING_IMPACT;

	// Book4Chapter10 Resources
	bool ExtractBook4Chapter10Resources(ResourceManager *theMgr);
	extern Image* IMAGE_B4A_BG10;
	extern int SOUND_BOOK4_CH10_DOPEY_ATTACK;
	extern int SOUND_BOOK4_CH10_DOPEY_IMPACT;
	extern int SOUND_BOOK4_CH10_FEMALE_GROAN1;
	extern int SOUND_BOOK4_CH10_FEMALE_GROAN2;
	extern int SOUND_BOOK4_CH10_MALE_LAUGH2;
	extern int SOUND_BOOK4_CH10_MALE_LAUGH;
	extern int SOUND_BOOK4_CH10_MALE_PAIN;
	extern int SOUND_BOOK4_CH10_SLICING_ATTACK2;
	extern int SOUND_BOOK4_CH10_SLICING_ATTACK;
	extern int SOUND_BOOK4_CH10_SMOKE_ATTACK2;
	extern int SOUND_BOOK4_CH10_SQ_MAM_ATTACK2;
	extern int SOUND_BOOK4_CH10_SQ_MAM_DEATH;
	extern int SOUND_BOOK4_CH10_WITCH_LAUGH2;
	extern int SOUND_BOOK4_CH10_WITCH_LAUGH;

	// Book4Chapter2 Resources
	bool ExtractBook4Chapter2Resources(ResourceManager *theMgr);
	extern Image* IMAGE_B4A_BG2;
	extern int SOUND_BOOK4_CH2_BOVINE_ATTACK1;
	extern int SOUND_BOOK4_CH2_BOVINE_ATTACK2;
	extern int SOUND_BOOK4_CH2_BOVINE_IMPACT;
	extern int SOUND_BOOK4_CH2_CHICKEN_ATTACK1;
	extern int SOUND_BOOK4_CH2_CHICKEN_ATTACK2;
	extern int SOUND_BOOK4_CH2_CHICKEN_IMPACT;
	extern int SOUND_BOOK4_CH2_EXPLOSION_1;
	extern int SOUND_BOOK4_CH2_MALE_LAUGH2;
	extern int SOUND_BOOK4_CH2_MALE_LOW_PAIN;
	extern int SOUND_BOOK4_CH2_MALE_PAIN;
	extern int SOUND_BOOK4_CH2_PIG_ATTACK2;
	extern int SOUND_BOOK4_CH2_PIG_ATTACK;
	extern int SOUND_BOOK4_CH2_PIG_SQUEAL2;
	extern int SOUND_BOOK4_CH2_SHEEP_BLEAT;
	extern int SOUND_BOOK4_CH2_SLICING_ATTACK2;

	// Book4Chapter3 Resources
	bool ExtractBook4Chapter3Resources(ResourceManager *theMgr);
	extern Image* IMAGE_B4A_BG3;
	extern int SOUND_BOOK4_CH3_CS_GOOSE;
	extern int SOUND_BOOK4_CH3_DOG_BARK1;
	extern int SOUND_BOOK4_CH3_DOG_BARK2;
	extern int SOUND_BOOK4_CH3_DOG_WHIMPER;
	extern int SOUND_BOOK4_CH3_MISC_IMPACT2;
	extern int SOUND_BOOK4_CH3_MISC_IMPACT;
	extern int SOUND_BOOK4_CH3_PIG_ATTACK2;
	extern int SOUND_BOOK4_CH3_PIG_ATTACK;
	extern int SOUND_BOOK4_CH3_PIG_SQUEAL2;
	extern int SOUND_BOOK4_CH3_PIG_SQUEAL;
	extern int SOUND_BOOK4_CH3_WITCH_GROAN;
	extern int SOUND_BOOK4_CH3_WITCH_LAUGH2;
	extern int SOUND_BOOK4_CH3_WITCH_LAUGH;
	extern int SOUND_BOOK4_CH3_WOLF_HOWL;

	// Book4Chapter4 Resources
	bool ExtractBook4Chapter4Resources(ResourceManager *theMgr);
	extern Image* IMAGE_B4A_BG4;
	extern int SOUND_BOOK4_CH4_BLUNT_IMPACT1;
	extern int SOUND_BOOK4_CH4_CHICKEN_ATTACK1;
	extern int SOUND_BOOK4_CH4_CHICKEN_IMPACT;
	extern int SOUND_BOOK4_CH4_EXPLOSION_1;
	extern int SOUND_BOOK4_CH4_EXPLOSION_3;
	extern int SOUND_BOOK4_CH4_FEMALE_GROAN2;
	extern int SOUND_BOOK4_CH4_FIREWORK_1;
	extern int SOUND_BOOK4_CH4_FIRE_3;
	extern int SOUND_BOOK4_CH4_GENERIC_SLOSH;
	extern int SOUND_BOOK4_CH4_GIANT_GRUNT2;
	extern int SOUND_BOOK4_CH4_KUBWA_ROAR;
	extern int SOUND_BOOK4_CH4_MALE_ANGER;
	extern int SOUND_BOOK4_CH4_MALE_GRUNT1;
	extern int SOUND_BOOK4_CH4_MALE_GRUNT2;
	extern int SOUND_BOOK4_CH4_MALE_LAUGH2;
	extern int SOUND_BOOK4_CH4_MALE_LAUGH;
	extern int SOUND_BOOK4_CH4_MALE_LOW_ANGER;
	extern int SOUND_BOOK4_CH4_MISC_IMPACT2;
	extern int SOUND_BOOK4_CH4_SWORD_IMPACT3;
	extern int SOUND_BOOK4_CH4_WET_IMPACT2;

	// Book4Chapter5 Resources
	bool ExtractBook4Chapter5Resources(ResourceManager *theMgr);
	extern Image* IMAGE_B4A_BG5;
	extern int SOUND_BOOK4_CH5_BEAR_ATTACK;
	extern int SOUND_BOOK4_CH5_BEAR_IMPACT;
	extern int SOUND_BOOK4_CH5_BEAR_ROAR;
	extern int SOUND_BOOK4_CH5_FIRE_3;
	extern int SOUND_BOOK4_CH5_FIRE_6;
	extern int SOUND_BOOK4_CH5_PLATE_ATTACK4;
	extern int SOUND_BOOK4_CH5_PLATE_IMPACT5;
	extern int SOUND_BOOK4_CH5_WET_IMPACT1;

	// Book4Chapter6 Resources
	bool ExtractBook4Chapter6Resources(ResourceManager *theMgr);
	extern Image* IMAGE_B4A_BG6;
	extern int SOUND_BOOK4_CH6_EXPLOSION_1;
	extern int SOUND_BOOK4_CH6_EXPLOSION_3;
	extern int SOUND_BOOK4_CH6_FEMALE_GROAN2;
	extern int SOUND_BOOK4_CH6_FEMALE_MMMMM;
	extern int SOUND_BOOK4_CH6_MALE_LAUGH2;
	extern int SOUND_BOOK4_CH6_MALE_LAUGH;
	extern int SOUND_BOOK4_CH6_MALE_PAIN;
	extern int SOUND_BOOK4_CH6_SLUMP_SMALL;
	extern int SOUND_BOOK4_CH6_SMOKE_ATTACK2;
	extern int SOUND_BOOK4_CH6_WITCH_GROAN;
	extern int SOUND_BOOK4_CH6_WITCH_LAUGH2;
	extern int SOUND_BOOK4_CH6_WITCH_LAUGH;

	// Book4Chapter7 Resources
	bool ExtractBook4Chapter7Resources(ResourceManager *theMgr);
	extern Image* IMAGE_B4A_BG7;
	extern Image* IMAGE_B4A_CATEPILLAR_BOSS_BATTLE;
	extern int SOUND_BOOK4_CH7_CS_CAT;
	extern int SOUND_BOOK4_CH7_MALE_LAUGH2;
	extern int SOUND_BOOK4_CH7_MALE_LAUGH;
	extern int SOUND_BOOK4_CH7_SMOKE_ATTACK2;
	extern int SOUND_BOOK4_CH7_SMOKE_ATTACK;
	extern int SOUND_BOOK4_CH7_SMOKE_IMPACT;

	// Book4Chapter8 Resources
	bool ExtractBook4Chapter8Resources(ResourceManager *theMgr);
	extern Image* IMAGE_B4A_BG8;
	extern int SOUND_BOOK4_CH8_FIRE_3;
	extern int SOUND_BOOK4_CH8_FIRE_6;
	extern int SOUND_BOOK4_CH8_MALE_LAUGH2;
	extern int SOUND_BOOK4_CH8_MALE_LAUGH;
	extern int SOUND_BOOK4_CH8_PLATE_ATTACK2;
	extern int SOUND_BOOK4_CH8_PLATE_ATTACK3;
	extern int SOUND_BOOK4_CH8_PLATE_ATTACK4;
	extern int SOUND_BOOK4_CH8_PLATE_IMPACT3;
	extern int SOUND_BOOK4_CH8_PLATE_IMPACT4;
	extern int SOUND_BOOK4_CH8_PLATE_IMPACT5;
	extern int SOUND_BOOK4_CH8_PLATE_IMPACT6;
	extern int SOUND_BOOK4_CH8_SQ_MAM_ATTACK2;
	extern int SOUND_BOOK4_CH8_SQ_MAM_ATTACK;
	extern int SOUND_BOOK4_CH8_SQ_MAM_DEATH;

	// Book4Chapter9 Resources
	bool ExtractBook4Chapter9Resources(ResourceManager *theMgr);
	extern Image* IMAGE_B4A_BG9;
	extern int SOUND_BOOK4_CH9_DOPEY_ATTACK;
	extern int SOUND_BOOK4_CH9_DOPEY_IMPACT;
	extern int SOUND_BOOK4_CH9_DRAGON_BITE;
	extern int SOUND_BOOK4_CH9_DRAGON_DEATH;
	extern int SOUND_BOOK4_CH9_DRAGON_PAIN;
	extern int SOUND_BOOK4_CH9_DRAGON_ROAR;
	extern int SOUND_BOOK4_CH9_MALE_LAUGH2;
	extern int SOUND_BOOK4_CH9_MALE_LAUGH;
	extern int SOUND_BOOK4_CH9_MALE_PAIN;
	extern int SOUND_BOOK4_CH9_OGRE_CHALLENGE;
	extern int SOUND_BOOK4_CH9_OGRE_IMPACT;
	extern int SOUND_BOOK4_CH9_SLICING_ATTACK2;
	extern int SOUND_BOOK4_CH9_SLICING_ATTACK;
	extern int SOUND_BOOK4_CH9_SMOKE_ATTACK2;

	// Book4Init Resources
	bool ExtractBook4InitResources(ResourceManager *theMgr);
	extern Image* IMAGE_B4_ICONANIM10;
	extern Image* IMAGE_B4_ICONANIM1;
	extern Image* IMAGE_B4_ICONANIM2;
	extern Image* IMAGE_B4_ICONANIM3;
	extern Image* IMAGE_B4_ICONANIM4;
	extern Image* IMAGE_B4_ICONANIM5;
	extern Image* IMAGE_B4_ICONANIM6;
	extern Image* IMAGE_B4_ICONANIM7;
	extern Image* IMAGE_B4_ICONANIM8;
	extern Image* IMAGE_B4_ICONANIM9;
	extern Image* IMAGE_B4_ICONMASK10;
	extern Image* IMAGE_B4_ICONMASK1;
	extern Image* IMAGE_B4_ICONMASK2;
	extern Image* IMAGE_B4_ICONMASK3;
	extern Image* IMAGE_B4_ICONMASK4;
	extern Image* IMAGE_B4_ICONMASK5;
	extern Image* IMAGE_B4_ICONMASK6;
	extern Image* IMAGE_B4_ICONMASK7;
	extern Image* IMAGE_B4_ICONMASK8;
	extern Image* IMAGE_B4_ICONMASK9;
	extern Image* IMAGE_B4_MAP;
	extern Image* IMAGE_B4_MAPSCREEN_BANNER;
	extern Image* IMAGE_B4_MINIMAP_ICONS;
	extern Image* IMAGE_TUT_PIC_OLDMC;
	extern Image* IMAGE_TUT_PIC_QUEEN;
	extern Image* IMAGE_TUT_PIC_QUEEN_ANGRY;

	enum ResourceId
	{
		IMAGE_B4_MINIMAP_ICONS_ID,
		IMAGE_B4_MAPSCREEN_BANNER_ID,
		IMAGE_B4_ICONANIM1_ID,
		IMAGE_B4_ICONANIM2_ID,
		IMAGE_B4_ICONANIM3_ID,
		IMAGE_B4_ICONANIM4_ID,
		IMAGE_B4_ICONANIM5_ID,
		IMAGE_B4_ICONANIM6_ID,
		IMAGE_B4_ICONANIM7_ID,
		IMAGE_B4_ICONANIM8_ID,
		IMAGE_B4_ICONANIM9_ID,
		IMAGE_B4_ICONANIM10_ID,
		IMAGE_B4_ICONMASK1_ID,
		IMAGE_B4_ICONMASK2_ID,
		IMAGE_B4_ICONMASK3_ID,
		IMAGE_B4_ICONMASK4_ID,
		IMAGE_B4_ICONMASK5_ID,
		IMAGE_B4_ICONMASK6_ID,
		IMAGE_B4_ICONMASK7_ID,
		IMAGE_B4_ICONMASK8_ID,
		IMAGE_B4_ICONMASK9_ID,
		IMAGE_B4_ICONMASK10_ID,
		IMAGE_B4_MAP_ID,
		IMAGE_TUT_PIC_OLDMC_ID,
		IMAGE_TUT_PIC_QUEEN_ANGRY_ID,
		IMAGE_TUT_PIC_QUEEN_ID,
		IMAGE_B4_LEFT_FACING_ARROW_ID,
		IMAGE_B4A_BG1_ID,
		SOUND_BOOK4_CH1_FELINE_ENGAGE_ID,
		SOUND_BOOK4_CH1_FELINE_ROAR_ID,
		SOUND_BOOK4_CH1_STRING_ATTACK_ID,
		SOUND_BOOK4_CH1_STRING_DEATH_ID,
		SOUND_BOOK4_CH1_STRING_IMPACT_ID,
		SOUND_BOOK4_CH1_BOVINE_ATTACK1_ID,
		SOUND_BOOK4_CH1_BOVINE_ATTACK2_ID,
		SOUND_BOOK4_CH1_BOVINE_IMPACT_ID,
		SOUND_BOOK4_CH1_FIRE_6_ID,
		SOUND_BOOK4_CH1_SPARKLE_ATTACK_ID,
		SOUND_BOOK4_CH1_PLATE_ATTACK2_ID,
		SOUND_BOOK4_CH1_PLATE_ATTACK3_ID,
		SOUND_BOOK4_CH1_PLATE_IMPACT3_ID,
		SOUND_BOOK4_CH1_PLATE_IMPACT4_ID,
		SOUND_BOOK4_CH1_PLATE_IMPACT5_ID,
		SOUND_BOOK4_CH1_PLATE_IMPACT6_ID,
		IMAGE_B4A_BG2_ID,
		SOUND_BOOK4_CH2_PIG_SQUEAL2_ID,
		SOUND_BOOK4_CH2_PIG_ATTACK_ID,
		SOUND_BOOK4_CH2_PIG_ATTACK2_ID,
		SOUND_BOOK4_CH2_SHEEP_BLEAT_ID,
		SOUND_BOOK4_CH2_SLICING_ATTACK2_ID,
		SOUND_BOOK4_CH2_MALE_LOW_PAIN_ID,
		SOUND_BOOK4_CH2_MALE_LAUGH2_ID,
		SOUND_BOOK4_CH2_MALE_PAIN_ID,
		SOUND_BOOK4_CH2_BOVINE_ATTACK2_ID,
		SOUND_BOOK4_CH2_CHICKEN_ATTACK1_ID,
		SOUND_BOOK4_CH2_CHICKEN_ATTACK2_ID,
		SOUND_BOOK4_CH2_CHICKEN_IMPACT_ID,
		SOUND_BOOK4_CH2_EXPLOSION_1_ID,
		SOUND_BOOK4_CH2_BOVINE_ATTACK1_ID,
		SOUND_BOOK4_CH2_BOVINE_IMPACT_ID,
		IMAGE_B4A_BG3_ID,
		SOUND_BOOK4_CH3_DOG_BARK1_ID,
		SOUND_BOOK4_CH3_DOG_BARK2_ID,
		SOUND_BOOK4_CH3_DOG_WHIMPER_ID,
		SOUND_BOOK4_CH3_MISC_IMPACT_ID,
		SOUND_BOOK4_CH3_MISC_IMPACT2_ID,
		SOUND_BOOK4_CH3_PIG_SQUEAL_ID,
		SOUND_BOOK4_CH3_PIG_SQUEAL2_ID,
		SOUND_BOOK4_CH3_PIG_ATTACK_ID,
		SOUND_BOOK4_CH3_PIG_ATTACK2_ID,
		SOUND_BOOK4_CH3_WITCH_GROAN_ID,
		SOUND_BOOK4_CH3_WITCH_LAUGH_ID,
		SOUND_BOOK4_CH3_WITCH_LAUGH2_ID,
		SOUND_BOOK4_CH3_WOLF_HOWL_ID,
		SOUND_BOOK4_CH3_CS_GOOSE_ID,
		IMAGE_B4A_BG4_ID,
		SOUND_BOOK4_CH4_EXPLOSION_1_ID,
		SOUND_BOOK4_CH4_EXPLOSION_3_ID,
		SOUND_BOOK4_CH4_CHICKEN_ATTACK1_ID,
		SOUND_BOOK4_CH4_BLUNT_IMPACT1_ID,
		SOUND_BOOK4_CH4_CHICKEN_IMPACT_ID,
		SOUND_BOOK4_CH4_MALE_ANGER_ID,
		SOUND_BOOK4_CH4_MALE_LAUGH_ID,
		SOUND_BOOK4_CH4_MALE_LAUGH2_ID,
		SOUND_BOOK4_CH4_MALE_LOW_ANGER_ID,
		SOUND_BOOK4_CH4_MALE_GRUNT1_ID,
		SOUND_BOOK4_CH4_MALE_GRUNT2_ID,
		SOUND_BOOK4_CH4_GENERIC_SLOSH_ID,
		SOUND_BOOK4_CH4_FEMALE_GROAN2_ID,
		SOUND_BOOK4_CH4_MISC_IMPACT2_ID,
		SOUND_BOOK4_CH4_WET_IMPACT2_ID,
		SOUND_BOOK4_CH4_KUBWA_ROAR_ID,
		SOUND_BOOK4_CH4_GIANT_GRUNT2_ID,
		SOUND_BOOK4_CH4_FIRE_3_ID,
		SOUND_BOOK4_CH4_FIREWORK_1_ID,
		SOUND_BOOK4_CH4_SWORD_IMPACT3_ID,
		IMAGE_B4A_BG5_ID,
		SOUND_BOOK4_CH5_PLATE_ATTACK4_ID,
		SOUND_BOOK4_CH5_PLATE_IMPACT5_ID,
		SOUND_BOOK4_CH5_FIRE_3_ID,
		SOUND_BOOK4_CH5_FIRE_6_ID,
		SOUND_BOOK4_CH5_BEAR_ATTACK_ID,
		SOUND_BOOK4_CH5_BEAR_IMPACT_ID,
		SOUND_BOOK4_CH5_BEAR_ROAR_ID,
		SOUND_BOOK4_CH5_WET_IMPACT1_ID,
		IMAGE_B4A_BG6_ID,
		SOUND_BOOK4_CH6_MALE_LAUGH_ID,
		SOUND_BOOK4_CH6_MALE_LAUGH2_ID,
		SOUND_BOOK4_CH6_MALE_PAIN_ID,
		SOUND_BOOK4_CH6_FEMALE_GROAN2_ID,
		SOUND_BOOK4_CH6_SMOKE_ATTACK2_ID,
		SOUND_BOOK4_CH6_EXPLOSION_1_ID,
		SOUND_BOOK4_CH6_EXPLOSION_3_ID,
		SOUND_BOOK4_CH6_SLUMP_SMALL_ID,
		SOUND_BOOK4_CH6_WITCH_GROAN_ID,
		SOUND_BOOK4_CH6_WITCH_LAUGH_ID,
		SOUND_BOOK4_CH6_WITCH_LAUGH2_ID,
		SOUND_BOOK4_CH6_FEMALE_MMMMM_ID,
		IMAGE_B4A_BG7_ID,
		IMAGE_B4A_CATEPILLAR_BOSS_BATTLE_ID,
		SOUND_BOOK4_CH7_SMOKE_ATTACK_ID,
		SOUND_BOOK4_CH7_SMOKE_ATTACK2_ID,
		SOUND_BOOK4_CH7_SMOKE_IMPACT_ID,
		SOUND_BOOK4_CH7_MALE_LAUGH_ID,
		SOUND_BOOK4_CH7_MALE_LAUGH2_ID,
		SOUND_BOOK4_CH7_CS_CAT_ID,
		IMAGE_B4A_BG8_ID,
		SOUND_BOOK4_CH8_SQ_MAM_ATTACK_ID,
		SOUND_BOOK4_CH8_SQ_MAM_ATTACK2_ID,
		SOUND_BOOK4_CH8_SQ_MAM_DEATH_ID,
		SOUND_BOOK4_CH8_MALE_LAUGH_ID,
		SOUND_BOOK4_CH8_MALE_LAUGH2_ID,
		SOUND_BOOK4_CH8_PLATE_ATTACK2_ID,
		SOUND_BOOK4_CH8_PLATE_ATTACK3_ID,
		SOUND_BOOK4_CH8_PLATE_ATTACK4_ID,
		SOUND_BOOK4_CH8_PLATE_IMPACT3_ID,
		SOUND_BOOK4_CH8_PLATE_IMPACT4_ID,
		SOUND_BOOK4_CH8_PLATE_IMPACT5_ID,
		SOUND_BOOK4_CH8_PLATE_IMPACT6_ID,
		SOUND_BOOK4_CH8_FIRE_3_ID,
		SOUND_BOOK4_CH8_FIRE_6_ID,
		IMAGE_B4A_BG9_ID,
		SOUND_BOOK4_CH9_OGRE_CHALLENGE_ID,
		SOUND_BOOK4_CH9_OGRE_IMPACT_ID,
		SOUND_BOOK4_CH9_DOPEY_ATTACK_ID,
		SOUND_BOOK4_CH9_DOPEY_IMPACT_ID,
		SOUND_BOOK4_CH9_SMOKE_ATTACK2_ID,
		SOUND_BOOK4_CH9_DRAGON_BITE_ID,
		SOUND_BOOK4_CH9_DRAGON_DEATH_ID,
		SOUND_BOOK4_CH9_DRAGON_PAIN_ID,
		SOUND_BOOK4_CH9_DRAGON_ROAR_ID,
		SOUND_BOOK4_CH9_MALE_LAUGH_ID,
		SOUND_BOOK4_CH9_MALE_LAUGH2_ID,
		SOUND_BOOK4_CH9_MALE_PAIN_ID,
		SOUND_BOOK4_CH9_SLICING_ATTACK_ID,
		SOUND_BOOK4_CH9_SLICING_ATTACK2_ID,
		IMAGE_B4A_BG10_ID,
		SOUND_BOOK4_CH10_DOPEY_ATTACK_ID,
		SOUND_BOOK4_CH10_DOPEY_IMPACT_ID,
		SOUND_BOOK4_CH10_SMOKE_ATTACK2_ID,
		SOUND_BOOK4_CH10_WITCH_LAUGH_ID,
		SOUND_BOOK4_CH10_WITCH_LAUGH2_ID,
		SOUND_BOOK4_CH10_FEMALE_GROAN2_ID,
		SOUND_BOOK4_CH10_FEMALE_GROAN1_ID,
		SOUND_BOOK4_CH10_SLICING_ATTACK_ID,
		SOUND_BOOK4_CH10_SLICING_ATTACK2_ID,
		SOUND_BOOK4_CH10_MALE_LAUGH_ID,
		SOUND_BOOK4_CH10_MALE_LAUGH2_ID,
		SOUND_BOOK4_CH10_MALE_PAIN_ID,
		SOUND_BOOK4_CH10_SQ_MAM_ATTACK2_ID,
		SOUND_BOOK4_CH10_SQ_MAM_DEATH_ID,
		RESOURCE_ID_MAX
	};

	Image* GetImageById(int theId);
	Font* GetFontById(int theId);
	int GetSoundById(int theId);

	Image*& GetImageRefById(int theId);
	Font*& GetFontRefById(int theId);
	int& GetSoundRefById(int theId);

	ResourceId GetIdByImage(Image *theImage);
	ResourceId GetIdByFont(Font *theFont);
	ResourceId GetIdBySound(int theSound);
	const char* GetStringIdById(int theId);
	ResourceId GetIdByStringId(const char *theStringId);

} // namespace Sexy


#endif
