#ifndef __Book6_H__
#define __Book6_H__

namespace Sexy
{
	class ResourceManager;
	class Image;
	class Font;

	Image* LoadImageById(ResourceManager *theManager, int theId);
	void ReplaceImageById(ResourceManager *theManager, int theId, Image *theImage);
	bool ExtractResourcesByName(ResourceManager *theManager, const char *theName);

	// BOOK6Common Resources
	bool ExtractBOOK6CommonResources(ResourceManager *theMgr);
	extern Image* IMAGE_B6_LEFT_FACING_ARROW;

	// Book6Chapter1 Resources
	bool ExtractBook6Chapter1Resources(ResourceManager *theMgr);
	extern Image* IMAGE_B6A_BG1;
	extern Image* IMAGE_B6A_SKIFF;
	extern int SOUND_BOOK6_CH1_BOVINE_ATTACK1;
	extern int SOUND_BOOK6_CH1_EXPLOSION_1;
	extern int SOUND_BOOK6_CH1_FELINE_ENGAGE;
	extern int SOUND_BOOK6_CH1_FELINE_ROAR;
	extern int SOUND_BOOK6_CH1_MONKEY_ATTACK;
	extern int SOUND_BOOK6_CH1_ROBOT_ATTACK;
	extern int SOUND_BOOK6_CH1_ROBOT_CHALLENGE;
	extern int SOUND_BOOK6_CH1_ROBOT_IMPACT;
	extern int SOUND_BOOK6_CH1_SCIFI_LASER;
	extern int SOUND_BOOK6_CH1_SCIFI_MECH2;
	extern int SOUND_BOOK6_CH1_SCIFI_MECH;
	extern int SOUND_BOOK6_CH1_SCIFI_TELEPORT;
	extern int SOUND_BOOK6_CH1_SMOKE_ATTACK2;
	extern int SOUND_BOOK6_CH1_SMOKE_ATTACK;
	extern int SOUND_BOOK6_CH1_SMOKE_IMPACT;
	extern int SOUND_BOOK6_CH1_SONIC_ATTACK;
	extern int SOUND_BOOK6_CH1_SPARKLE_ATTACK;
	extern int SOUND_BOOK6_CH1_WET_IMPACT1;

	// Book6Chapter10 Resources
	bool ExtractBook6Chapter10Resources(ResourceManager *theMgr);
	extern Image* IMAGE_B6A_BG10;
	extern Image* IMAGE_B6A_THEMACHINE_BOSS_BATTLE;
	extern int SOUND_BOOK6_CH10_BLUNT_IMPACT2;
	extern int SOUND_BOOK6_CH10_EXPLOSION_1;
	extern int SOUND_BOOK6_CH10_EXPLOSION_3;
	extern int SOUND_BOOK6_CH10_FIRE_6;
	extern int SOUND_BOOK6_CH10_LIGHTNING_ATTACK;
	extern int SOUND_BOOK6_CH10_ROBOT_ATTACK;
	extern int SOUND_BOOK6_CH10_ROBOT_CHALLENGE;
	extern int SOUND_BOOK6_CH10_ROBOT_IMPACT;
	extern int SOUND_BOOK6_CH10_SCIFI_LASER;
	extern int SOUND_BOOK6_CH10_SCIFI_MECH2;
	extern int SOUND_BOOK6_CH10_SCIFI_MECH;
	extern int SOUND_BOOK6_CH10_SCIFI_TELEPORT;
	extern int SOUND_BOOK6_CH10_SONIC_ATTACK;
	extern int SOUND_BOOK6_CH10_SPARKLE_ATTACK;

	// Book6Chapter2 Resources
	bool ExtractBook6Chapter2Resources(ResourceManager *theMgr);
	extern Image* IMAGE_B6A_BG2;
	extern int SOUND_BOOK6_CH2_DOPEY_ATTACK;
	extern int SOUND_BOOK6_CH2_DOPEY_IMPACT;
	extern int SOUND_BOOK6_CH2_EXPLOSION_3;
	extern int SOUND_BOOK6_CH2_MALE_LOW_ANGER;
	extern int SOUND_BOOK6_CH2_MISC_IMPACT;
	extern int SOUND_BOOK6_CH2_MONKEY_ATTACK2;
	extern int SOUND_BOOK6_CH2_MONKEY_ATTACK;
	extern int SOUND_BOOK6_CH2_MONKEY_CHALLENGE;
	extern int SOUND_BOOK6_CH2_OGRE_ATTACK2;
	extern int SOUND_BOOK6_CH2_OGRE_ATTACK;
	extern int SOUND_BOOK6_CH2_OGRE_CHALLENGE2;
	extern int SOUND_BOOK6_CH2_OGRE_CHALLENGE;
	extern int SOUND_BOOK6_CH2_OGRE_IMPACT2;
	extern int SOUND_BOOK6_CH2_OGRE_IMPACT3;
	extern int SOUND_BOOK6_CH2_OGRE_IMPACT;
	extern int SOUND_BOOK6_CH2_SCIFI_LASER;
	extern int SOUND_BOOK6_CH2_WET_IMPACT1;
	extern int SOUND_BOOK6_CH2_WET_IMPACT2;

	// Book6Chapter3 Resources
	bool ExtractBook6Chapter3Resources(ResourceManager *theMgr);
	extern Image* IMAGE_B6A_BG3;
	extern int SOUND_BOOK6_CH3_CS_SHACKLE;
	extern int SOUND_BOOK6_CH3_DOPEY_ATTACK;
	extern int SOUND_BOOK6_CH3_DOPEY_IMPACT;
	extern int SOUND_BOOK6_CH3_MALE_ANGER;
	extern int SOUND_BOOK6_CH3_MALE_LOW_ANGER;
	extern int SOUND_BOOK6_CH3_MALE_PAIN;
	extern int SOUND_BOOK6_CH3_OGRE_ATTACK2;
	extern int SOUND_BOOK6_CH3_OGRE_ATTACK;
	extern int SOUND_BOOK6_CH3_OGRE_CHALLENGE2;
	extern int SOUND_BOOK6_CH3_OGRE_CHALLENGE;
	extern int SOUND_BOOK6_CH3_OGRE_IMPACT2;
	extern int SOUND_BOOK6_CH3_OGRE_IMPACT3;
	extern int SOUND_BOOK6_CH3_OGRE_IMPACT;
	extern int SOUND_BOOK6_CH3_PIG_ATTACK;
	extern int SOUND_BOOK6_CH3_PIG_SQUEAL2;

	// Book6Chapter4 Resources
	bool ExtractBook6Chapter4Resources(ResourceManager *theMgr);
	extern Image* IMAGE_B6A_BG4;
	extern int SOUND_BOOK6_CH4_DRAGON_ROAR;
	extern int SOUND_BOOK6_CH4_FEMALE_GROAN1;
	extern int SOUND_BOOK6_CH4_FEMALE_GROAN2;
	extern int SOUND_BOOK6_CH4_FEMALE_SEDUCE;
	extern int SOUND_BOOK6_CH4_PLATE_ATTACK2;
	extern int SOUND_BOOK6_CH4_ROBOT_ATTACK;
	extern int SOUND_BOOK6_CH4_ROBOT_CHALLENGE;
	extern int SOUND_BOOK6_CH4_ROBOT_IMPACT;
	extern int SOUND_BOOK6_CH4_SCIFI_LASER;
	extern int SOUND_BOOK6_CH4_SCIFI_MECH2;
	extern int SOUND_BOOK6_CH4_SCIFI_MECH;
	extern int SOUND_BOOK6_CH4_SCIFI_TELEPORT;
	extern int SOUND_BOOK6_CH4_SHEEP_BLEAT;
	extern int SOUND_BOOK6_CH4_SLICING_ATTACK;
	extern int SOUND_BOOK6_CH4_SMOKE_ATTACK;
	extern int SOUND_BOOK6_CH4_SONIC_ATTACK;
	extern int SOUND_BOOK6_CH4_SWORD_IMPACT3;

	// Book6Chapter5 Resources
	bool ExtractBook6Chapter5Resources(ResourceManager *theMgr);
	extern Image* IMAGE_B6A_BG5;
	extern int SOUND_BOOK6_CH5_ARROW_SHOT;
	extern int SOUND_BOOK6_CH5_BEAR_ROAR;
	extern int SOUND_BOOK6_CH5_FEMALE_GROAN1;
	extern int SOUND_BOOK6_CH5_FEMALE_GROAN2;
	extern int SOUND_BOOK6_CH5_LIGHTNING_ATTACK;
	extern int SOUND_BOOK6_CH5_MALE_ANGER;
	extern int SOUND_BOOK6_CH5_MALE_LAUGH2;
	extern int SOUND_BOOK6_CH5_MALE_LAUGH;
	extern int SOUND_BOOK6_CH5_MALE_PAIN;
	extern int SOUND_BOOK6_CH5_MISC_IMPACT2;
	extern int SOUND_BOOK6_CH5_MISC_IMPACT;
	extern int SOUND_BOOK6_CH5_SWORD_IMPACT3;
	extern int SOUND_BOOK6_CH5_WET_IMPACT1;
	extern int SOUND_BOOK6_CH5_WET_IMPACT2;

	// Book6Chapter6 Resources
	bool ExtractBook6Chapter6Resources(ResourceManager *theMgr);
	extern Image* IMAGE_B6A_BG6;
	extern int SOUND_BOOK6_CH6_DRAGON_BITE;
	extern int SOUND_BOOK6_CH6_DRAGON_DEATH;
	extern int SOUND_BOOK6_CH6_DRAGON_PAIN;
	extern int SOUND_BOOK6_CH6_DRAGON_ROAR;
	extern int SOUND_BOOK6_CH6_EXPLOSION_3;
	extern int SOUND_BOOK6_CH6_LIGHTNING_ATTACK;
	extern int SOUND_BOOK6_CH6_MALE_ANGER;
	extern int SOUND_BOOK6_CH6_MALE_LAUGH2;
	extern int SOUND_BOOK6_CH6_MALE_LAUGH;
	extern int SOUND_BOOK6_CH6_MALE_PAIN;
	extern int SOUND_BOOK6_CH6_SPARKLE_ATTACK;
	extern int SOUND_BOOK6_CH6_SWORD_IMPACT3;

	// Book6Chapter7 Resources
	bool ExtractBook6Chapter7Resources(ResourceManager *theMgr);
	extern Image* IMAGE_B6A_BG7;
	extern Image* IMAGE_B6A_DANCEBATTLE_BOSS_BATTLE;
	extern int SOUND_BOOK6_CH7_CS_SKULL;
	extern int SOUND_BOOK6_CH7_DANCE_CAMERA;
	extern int SOUND_BOOK6_CH7_DANCE_CHEER;
	extern int SOUND_BOOK6_CH7_DANCE_DEATH;
	extern int SOUND_BOOK6_CH7_DANCE_E;
	extern int SOUND_BOOK6_CH7_DANCE_ENGAGE;
	extern int SOUND_BOOK6_CH7_DANCE_L;
	extern int SOUND_BOOK6_CH7_DANCE_LEX;
	extern int SOUND_BOOK6_CH7_DANCE_X;
	extern int SOUND_BOOK6_CH7_SOUND1;
	extern int SOUND_BOOK6_CH7_SOUND2;
	extern int SOUND_BOOK6_CH7_SOUND3;
	extern int SOUND_BOOK6_CH7_SOUND4;
	extern int SOUND_BOOK6_CH7_SOUND5;
	extern int SOUND_BOOK6_CH7_SOUND6;
	extern int SOUND_BOOK6_CH7_SOUND7;
	extern int SOUND_BOOK6_CH7_SOUND8;
	extern int SOUND_BOOK6_CH7_SOUND9;

	// Book6Chapter8 Resources
	bool ExtractBook6Chapter8Resources(ResourceManager *theMgr);
	extern Image* IMAGE_B6A_BG8;
	extern int SOUND_BOOK6_CH8_DOPEY_ATTACK;
	extern int SOUND_BOOK6_CH8_DOPEY_IMPACT;
	extern int SOUND_BOOK6_CH8_FEMALE_GROAN2;
	extern int SOUND_BOOK6_CH8_FEMALE_OOOH;
	extern int SOUND_BOOK6_CH8_FEMALE_SEDUCE;
	extern int SOUND_BOOK6_CH8_LIGHTNING_ATTACK;
	extern int SOUND_BOOK6_CH8_MALE_GRUNT1;
	extern int SOUND_BOOK6_CH8_MALE_LAUGH2;
	extern int SOUND_BOOK6_CH8_SCIFI_LASER;
	extern int SOUND_BOOK6_CH8_SCIFI_MECH2;
	extern int SOUND_BOOK6_CH8_SCIFI_MECH;
	extern int SOUND_BOOK6_CH8_SCIFI_TELEPORT;
	extern int SOUND_BOOK6_CH8_SMOKE_ATTACK2;
	extern int SOUND_BOOK6_CH8_SMOKE_ATTACK;
	extern int SOUND_BOOK6_CH8_SMOKE_IMPACT;
	extern int SOUND_BOOK6_CH8_SONIC_ATTACK;
	extern int SOUND_BOOK6_CH8_SPARKLE_ATTACK;

	// Book6Chapter9 Resources
	bool ExtractBook6Chapter9Resources(ResourceManager *theMgr);
	extern Image* IMAGE_B6A_BG9;
	extern int SOUND_BOOK6_CH9_BLUNT_IMPACT2;
	extern int SOUND_BOOK6_CH9_DOG_BARK2;
	extern int SOUND_BOOK6_CH9_EXPLOSION_1;
	extern int SOUND_BOOK6_CH9_FIRE_6;
	extern int SOUND_BOOK6_CH9_LIGHTNING_ATTACK;
	extern int SOUND_BOOK6_CH9_MALE_ANGER;
	extern int SOUND_BOOK6_CH9_MALE_LAUGH2;
	extern int SOUND_BOOK6_CH9_MALE_LAUGH;
	extern int SOUND_BOOK6_CH9_MALE_LOW_ANGER;
	extern int SOUND_BOOK6_CH9_MALE_LOW_PAIN;
	extern int SOUND_BOOK6_CH9_MALE_LOW_WARCRY;
	extern int SOUND_BOOK6_CH9_MALE_PAIN;
	extern int SOUND_BOOK6_CH9_ROBOT_ATTACK;
	extern int SOUND_BOOK6_CH9_ROBOT_CHALLENGE;
	extern int SOUND_BOOK6_CH9_ROBOT_IMPACT;
	extern int SOUND_BOOK6_CH9_SCIFI_LASER;
	extern int SOUND_BOOK6_CH9_SCIFI_MECH2;
	extern int SOUND_BOOK6_CH9_SCIFI_MECH;
	extern int SOUND_BOOK6_CH9_SCIFI_TELEPORT;
	extern int SOUND_BOOK6_CH9_SONIC_ATTACK;
	extern int SOUND_BOOK6_CH9_SPARKLE_ATTACK;

	// Book6Init Resources
	bool ExtractBook6InitResources(ResourceManager *theMgr);
	extern Image* IMAGE_B6_ICONANIM10;
	extern Image* IMAGE_B6_ICONANIM1;
	extern Image* IMAGE_B6_ICONANIM2;
	extern Image* IMAGE_B6_ICONANIM3;
	extern Image* IMAGE_B6_ICONANIM4;
	extern Image* IMAGE_B6_ICONANIM5;
	extern Image* IMAGE_B6_ICONANIM6;
	extern Image* IMAGE_B6_ICONANIM7;
	extern Image* IMAGE_B6_ICONANIM8;
	extern Image* IMAGE_B6_ICONANIM9;
	extern Image* IMAGE_B6_ICONMASK10;
	extern Image* IMAGE_B6_ICONMASK1;
	extern Image* IMAGE_B6_ICONMASK2;
	extern Image* IMAGE_B6_ICONMASK3;
	extern Image* IMAGE_B6_ICONMASK4;
	extern Image* IMAGE_B6_ICONMASK5;
	extern Image* IMAGE_B6_ICONMASK6;
	extern Image* IMAGE_B6_ICONMASK7;
	extern Image* IMAGE_B6_ICONMASK8;
	extern Image* IMAGE_B6_ICONMASK9;
	extern Image* IMAGE_B6_MAP;
	extern Image* IMAGE_B6_MAPSCREEN_BANNER;
	extern Image* IMAGE_B6_MINIMAP_ICONS;
	extern Image* IMAGE_TUT_PIC_BIGBROTHER;
	extern Image* IMAGE_TUT_PIC_MAGICPEN;
	extern Image* IMAGE_TUT_PIC_PREV_LEX;
	extern Image* IMAGE_TUT_PIC_SKELETROX;

	enum ResourceId
	{
		IMAGE_B6_MINIMAP_ICONS_ID,
		IMAGE_B6_MAPSCREEN_BANNER_ID,
		IMAGE_B6_ICONANIM1_ID,
		IMAGE_B6_ICONANIM2_ID,
		IMAGE_B6_ICONANIM3_ID,
		IMAGE_B6_ICONANIM4_ID,
		IMAGE_B6_ICONANIM5_ID,
		IMAGE_B6_ICONANIM6_ID,
		IMAGE_B6_ICONANIM7_ID,
		IMAGE_B6_ICONANIM8_ID,
		IMAGE_B6_ICONANIM9_ID,
		IMAGE_B6_ICONANIM10_ID,
		IMAGE_B6_ICONMASK1_ID,
		IMAGE_B6_ICONMASK2_ID,
		IMAGE_B6_ICONMASK3_ID,
		IMAGE_B6_ICONMASK4_ID,
		IMAGE_B6_ICONMASK5_ID,
		IMAGE_B6_ICONMASK6_ID,
		IMAGE_B6_ICONMASK7_ID,
		IMAGE_B6_ICONMASK8_ID,
		IMAGE_B6_ICONMASK9_ID,
		IMAGE_B6_ICONMASK10_ID,
		IMAGE_B6_MAP_ID,
		IMAGE_TUT_PIC_SKELETROX_ID,
		IMAGE_TUT_PIC_BIGBROTHER_ID,
		IMAGE_TUT_PIC_MAGICPEN_ID,
		IMAGE_TUT_PIC_PREV_LEX_ID,
		IMAGE_B6_LEFT_FACING_ARROW_ID,
		IMAGE_B6A_SKIFF_ID,
		IMAGE_B6A_BG1_ID,
		SOUND_BOOK6_CH1_FELINE_ENGAGE_ID,
		SOUND_BOOK6_CH1_FELINE_ROAR_ID,
		SOUND_BOOK6_CH1_SCIFI_LASER_ID,
		SOUND_BOOK6_CH1_SCIFI_MECH_ID,
		SOUND_BOOK6_CH1_SCIFI_MECH2_ID,
		SOUND_BOOK6_CH1_SCIFI_TELEPORT_ID,
		SOUND_BOOK6_CH1_SONIC_ATTACK_ID,
		SOUND_BOOK6_CH1_SPARKLE_ATTACK_ID,
		SOUND_BOOK6_CH1_MONKEY_ATTACK_ID,
		SOUND_BOOK6_CH1_ROBOT_ATTACK_ID,
		SOUND_BOOK6_CH1_ROBOT_CHALLENGE_ID,
		SOUND_BOOK6_CH1_ROBOT_IMPACT_ID,
		SOUND_BOOK6_CH1_SMOKE_ATTACK_ID,
		SOUND_BOOK6_CH1_SMOKE_ATTACK2_ID,
		SOUND_BOOK6_CH1_SMOKE_IMPACT_ID,
		SOUND_BOOK6_CH1_WET_IMPACT1_ID,
		SOUND_BOOK6_CH1_BOVINE_ATTACK1_ID,
		SOUND_BOOK6_CH1_EXPLOSION_1_ID,
		IMAGE_B6A_BG2_ID,
		SOUND_BOOK6_CH2_MONKEY_ATTACK_ID,
		SOUND_BOOK6_CH2_MONKEY_ATTACK2_ID,
		SOUND_BOOK6_CH2_MONKEY_CHALLENGE_ID,
		SOUND_BOOK6_CH2_DOPEY_ATTACK_ID,
		SOUND_BOOK6_CH2_DOPEY_IMPACT_ID,
		SOUND_BOOK6_CH2_MALE_LOW_ANGER_ID,
		SOUND_BOOK6_CH2_OGRE_ATTACK_ID,
		SOUND_BOOK6_CH2_OGRE_ATTACK2_ID,
		SOUND_BOOK6_CH2_OGRE_CHALLENGE_ID,
		SOUND_BOOK6_CH2_OGRE_CHALLENGE2_ID,
		SOUND_BOOK6_CH2_OGRE_IMPACT_ID,
		SOUND_BOOK6_CH2_OGRE_IMPACT2_ID,
		SOUND_BOOK6_CH2_OGRE_IMPACT3_ID,
		SOUND_BOOK6_CH2_WET_IMPACT1_ID,
		SOUND_BOOK6_CH2_WET_IMPACT2_ID,
		SOUND_BOOK6_CH2_EXPLOSION_3_ID,
		SOUND_BOOK6_CH2_SCIFI_LASER_ID,
		SOUND_BOOK6_CH2_MISC_IMPACT_ID,
		IMAGE_B6A_BG3_ID,
		SOUND_BOOK6_CH3_DOPEY_ATTACK_ID,
		SOUND_BOOK6_CH3_DOPEY_IMPACT_ID,
		SOUND_BOOK6_CH3_MALE_LOW_ANGER_ID,
		SOUND_BOOK6_CH3_OGRE_ATTACK_ID,
		SOUND_BOOK6_CH3_OGRE_ATTACK2_ID,
		SOUND_BOOK6_CH3_OGRE_CHALLENGE_ID,
		SOUND_BOOK6_CH3_OGRE_CHALLENGE2_ID,
		SOUND_BOOK6_CH3_OGRE_IMPACT_ID,
		SOUND_BOOK6_CH3_OGRE_IMPACT2_ID,
		SOUND_BOOK6_CH3_OGRE_IMPACT3_ID,
		SOUND_BOOK6_CH3_MALE_ANGER_ID,
		SOUND_BOOK6_CH3_PIG_ATTACK_ID,
		SOUND_BOOK6_CH3_PIG_SQUEAL2_ID,
		SOUND_BOOK6_CH3_MALE_PAIN_ID,
		SOUND_BOOK6_CH3_CS_SHACKLE_ID,
		IMAGE_B6A_BG4_ID,
		SOUND_BOOK6_CH4_ROBOT_ATTACK_ID,
		SOUND_BOOK6_CH4_ROBOT_CHALLENGE_ID,
		SOUND_BOOK6_CH4_ROBOT_IMPACT_ID,
		SOUND_BOOK6_CH4_SCIFI_LASER_ID,
		SOUND_BOOK6_CH4_SCIFI_MECH_ID,
		SOUND_BOOK6_CH4_SCIFI_MECH2_ID,
		SOUND_BOOK6_CH4_SCIFI_TELEPORT_ID,
		SOUND_BOOK6_CH4_SONIC_ATTACK_ID,
		SOUND_BOOK6_CH4_FEMALE_SEDUCE_ID,
		SOUND_BOOK6_CH4_FEMALE_GROAN1_ID,
		SOUND_BOOK6_CH4_FEMALE_GROAN2_ID,
		SOUND_BOOK6_CH4_PLATE_ATTACK2_ID,
		SOUND_BOOK6_CH4_SHEEP_BLEAT_ID,
		SOUND_BOOK6_CH4_SMOKE_ATTACK_ID,
		SOUND_BOOK6_CH4_DRAGON_ROAR_ID,
		SOUND_BOOK6_CH4_SWORD_IMPACT3_ID,
		SOUND_BOOK6_CH4_SLICING_ATTACK_ID,
		IMAGE_B6A_BG5_ID,
		SOUND_BOOK6_CH5_FEMALE_GROAN1_ID,
		SOUND_BOOK6_CH5_FEMALE_GROAN2_ID,
		SOUND_BOOK6_CH5_ARROW_SHOT_ID,
		SOUND_BOOK6_CH5_MALE_ANGER_ID,
		SOUND_BOOK6_CH5_MALE_LAUGH_ID,
		SOUND_BOOK6_CH5_MALE_LAUGH2_ID,
		SOUND_BOOK6_CH5_MALE_PAIN_ID,
		SOUND_BOOK6_CH5_WET_IMPACT1_ID,
		SOUND_BOOK6_CH5_WET_IMPACT2_ID,
		SOUND_BOOK6_CH5_MISC_IMPACT_ID,
		SOUND_BOOK6_CH5_MISC_IMPACT2_ID,
		SOUND_BOOK6_CH5_SWORD_IMPACT3_ID,
		SOUND_BOOK6_CH5_LIGHTNING_ATTACK_ID,
		SOUND_BOOK6_CH5_BEAR_ROAR_ID,
		IMAGE_B6A_BG6_ID,
		SOUND_BOOK6_CH6_DRAGON_BITE_ID,
		SOUND_BOOK6_CH6_DRAGON_DEATH_ID,
		SOUND_BOOK6_CH6_DRAGON_PAIN_ID,
		SOUND_BOOK6_CH6_DRAGON_ROAR_ID,
		SOUND_BOOK6_CH6_MALE_ANGER_ID,
		SOUND_BOOK6_CH6_MALE_LAUGH_ID,
		SOUND_BOOK6_CH6_MALE_LAUGH2_ID,
		SOUND_BOOK6_CH6_MALE_PAIN_ID,
		SOUND_BOOK6_CH6_SPARKLE_ATTACK_ID,
		SOUND_BOOK6_CH6_EXPLOSION_3_ID,
		SOUND_BOOK6_CH6_LIGHTNING_ATTACK_ID,
		SOUND_BOOK6_CH6_SWORD_IMPACT3_ID,
		IMAGE_B6A_BG7_ID,
		IMAGE_B6A_DANCEBATTLE_BOSS_BATTLE_ID,
		SOUND_BOOK6_CH7_SOUND1_ID,
		SOUND_BOOK6_CH7_SOUND2_ID,
		SOUND_BOOK6_CH7_SOUND3_ID,
		SOUND_BOOK6_CH7_SOUND4_ID,
		SOUND_BOOK6_CH7_SOUND5_ID,
		SOUND_BOOK6_CH7_SOUND6_ID,
		SOUND_BOOK6_CH7_SOUND7_ID,
		SOUND_BOOK6_CH7_SOUND8_ID,
		SOUND_BOOK6_CH7_SOUND9_ID,
		SOUND_BOOK6_CH7_DANCE_ENGAGE_ID,
		SOUND_BOOK6_CH7_DANCE_DEATH_ID,
		SOUND_BOOK6_CH7_DANCE_CAMERA_ID,
		SOUND_BOOK6_CH7_DANCE_CHEER_ID,
		SOUND_BOOK6_CH7_DANCE_L_ID,
		SOUND_BOOK6_CH7_DANCE_E_ID,
		SOUND_BOOK6_CH7_DANCE_X_ID,
		SOUND_BOOK6_CH7_DANCE_LEX_ID,
		SOUND_BOOK6_CH7_CS_SKULL_ID,
		IMAGE_B6A_BG8_ID,
		SOUND_BOOK6_CH8_DOPEY_ATTACK_ID,
		SOUND_BOOK6_CH8_DOPEY_IMPACT_ID,
		SOUND_BOOK6_CH8_FEMALE_SEDUCE_ID,
		SOUND_BOOK6_CH8_MALE_GRUNT1_ID,
		SOUND_BOOK6_CH8_LIGHTNING_ATTACK_ID,
		SOUND_BOOK6_CH8_MALE_LAUGH2_ID,
		SOUND_BOOK6_CH8_FEMALE_GROAN2_ID,
		SOUND_BOOK6_CH8_SCIFI_LASER_ID,
		SOUND_BOOK6_CH8_SCIFI_MECH_ID,
		SOUND_BOOK6_CH8_SCIFI_MECH2_ID,
		SOUND_BOOK6_CH8_SCIFI_TELEPORT_ID,
		SOUND_BOOK6_CH8_SONIC_ATTACK_ID,
		SOUND_BOOK6_CH8_SPARKLE_ATTACK_ID,
		SOUND_BOOK6_CH8_SMOKE_ATTACK_ID,
		SOUND_BOOK6_CH8_SMOKE_ATTACK2_ID,
		SOUND_BOOK6_CH8_SMOKE_IMPACT_ID,
		SOUND_BOOK6_CH8_FEMALE_OOOH_ID,
		IMAGE_B6A_BG9_ID,
		SOUND_BOOK6_CH9_MALE_ANGER_ID,
		SOUND_BOOK6_CH9_MALE_LAUGH_ID,
		SOUND_BOOK6_CH9_MALE_LAUGH2_ID,
		SOUND_BOOK6_CH9_MALE_LOW_ANGER_ID,
		SOUND_BOOK6_CH9_MALE_LOW_PAIN_ID,
		SOUND_BOOK6_CH9_MALE_LOW_WARCRY_ID,
		SOUND_BOOK6_CH9_MALE_PAIN_ID,
		SOUND_BOOK6_CH9_ROBOT_ATTACK_ID,
		SOUND_BOOK6_CH9_ROBOT_CHALLENGE_ID,
		SOUND_BOOK6_CH9_ROBOT_IMPACT_ID,
		SOUND_BOOK6_CH9_SCIFI_LASER_ID,
		SOUND_BOOK6_CH9_SCIFI_MECH_ID,
		SOUND_BOOK6_CH9_SCIFI_MECH2_ID,
		SOUND_BOOK6_CH9_SCIFI_TELEPORT_ID,
		SOUND_BOOK6_CH9_FIRE_6_ID,
		SOUND_BOOK6_CH9_SONIC_ATTACK_ID,
		SOUND_BOOK6_CH9_SPARKLE_ATTACK_ID,
		SOUND_BOOK6_CH9_LIGHTNING_ATTACK_ID,
		SOUND_BOOK6_CH9_EXPLOSION_1_ID,
		SOUND_BOOK6_CH9_BLUNT_IMPACT2_ID,
		SOUND_BOOK6_CH9_DOG_BARK2_ID,
		IMAGE_B6A_BG10_ID,
		IMAGE_B6A_THEMACHINE_BOSS_BATTLE_ID,
		SOUND_BOOK6_CH10_ROBOT_ATTACK_ID,
		SOUND_BOOK6_CH10_ROBOT_CHALLENGE_ID,
		SOUND_BOOK6_CH10_ROBOT_IMPACT_ID,
		SOUND_BOOK6_CH10_SCIFI_LASER_ID,
		SOUND_BOOK6_CH10_SCIFI_MECH_ID,
		SOUND_BOOK6_CH10_SCIFI_MECH2_ID,
		SOUND_BOOK6_CH10_SCIFI_TELEPORT_ID,
		SOUND_BOOK6_CH10_FIRE_6_ID,
		SOUND_BOOK6_CH10_SONIC_ATTACK_ID,
		SOUND_BOOK6_CH10_SPARKLE_ATTACK_ID,
		SOUND_BOOK6_CH10_LIGHTNING_ATTACK_ID,
		SOUND_BOOK6_CH10_EXPLOSION_1_ID,
		SOUND_BOOK6_CH10_BLUNT_IMPACT2_ID,
		SOUND_BOOK6_CH10_EXPLOSION_3_ID,
		RESOURCE_ID_MAX
	};

	Image* GetImageById(int theId);
	Font* GetFontById(int theId);
	int GetSoundById(int theId);

	Image*& GetImageRefById(int theId);
	Font*& GetFontRefById(int theId);
	int& GetSoundRefById(int theId);

	ResourceId GetIdByImage(Image *theImage);
	ResourceId GetIdByFont(Font *theFont);
	ResourceId GetIdBySound(int theSound);
	const char* GetStringIdById(int theId);
	ResourceId GetIdByStringId(const char *theStringId);

} // namespace Sexy


#endif
