#include "InitialMiniGames.h"
#include "SexyAppFramework/ResourceManager.h"

using namespace Sexy;

#pragma warning(disable:4311 4312)

static bool gNeedRecalcVariableToIdMap = false;

bool Sexy::ExtractResourcesByName(ResourceManager *theManager, const char *theName)
{
	if (strcmp(theName,"InitialMiniGames")==0) return ExtractInitialMiniGamesResources(theManager);
	if (strcmp(theName,"MiniGame1")==0) return ExtractMiniGame1Resources(theManager);
	if (strcmp(theName,"MiniGame2")==0) return ExtractMiniGame2Resources(theManager);
	if (strcmp(theName,"MiniGame3")==0) return ExtractMiniGame3Resources(theManager);
	if (strcmp(theName,"MiniGame4")==0) return ExtractMiniGame4Resources(theManager);
	if (strcmp(theName,"MiniGame5")==0) return ExtractMiniGame5Resources(theManager);
	if (strcmp(theName,"MiniGame6")==0) return ExtractMiniGame6Resources(theManager);
	if (strcmp(theName,"MiniGame7")==0) return ExtractMiniGame7Resources(theManager);
	return false;
}

Sexy::ResourceId Sexy::GetIdByStringId(const char *theStringId)
{
	typedef std::map<std::string,int> MyMap;
	static MyMap aMap;
	if(aMap.empty())
	{
		for(int i=0; i<RESOURCE_ID_MAX; i++)
			aMap[GetStringIdById(i)] = i;
	}

	MyMap::iterator anItr = aMap.find(theStringId);
	if (anItr == aMap.end())
		return RESOURCE_ID_MAX;
	else
		return (ResourceId) anItr->second;
}

// InitialMiniGames Resources
Image* Sexy::IMAGE_MINIMENU_GOLDENCOINS_BTN;
Image* Sexy::IMAGE_MINIMENU_LETTER_RIP_BTN;
Image* Sexy::IMAGE_MINIMENU_LINKNSPELL_BTN;
Image* Sexy::IMAGE_MINIMENU_MUTANTWORDS_BTN;
Image* Sexy::IMAGE_MINIMENU_WORDMASTER_BTN;
Image* Sexy::IMAGE_MINIMENU_WORDUP_BTN;

bool Sexy::ExtractInitialMiniGamesResources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_MINIMENU_GOLDENCOINS_BTN = aMgr.GetImageThrow("IMAGE_MINIMENU_GOLDENCOINS_BTN");
		IMAGE_MINIMENU_LETTER_RIP_BTN = aMgr.GetImageThrow("IMAGE_MINIMENU_LETTER_RIP_BTN");
		IMAGE_MINIMENU_LINKNSPELL_BTN = aMgr.GetImageThrow("IMAGE_MINIMENU_LINKNSPELL_BTN");
		IMAGE_MINIMENU_MUTANTWORDS_BTN = aMgr.GetImageThrow("IMAGE_MINIMENU_MUTANTWORDS_BTN");
		IMAGE_MINIMENU_WORDMASTER_BTN = aMgr.GetImageThrow("IMAGE_MINIMENU_WORDMASTER_BTN");
		IMAGE_MINIMENU_WORDUP_BTN = aMgr.GetImageThrow("IMAGE_MINIMENU_WORDUP_BTN");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// MiniGame1 Resources
Image* Sexy::IMAGE_MINIGAME1_BRACKET;
Image* Sexy::IMAGE_MINIGAME1_ENTRY_BOXES;
Image* Sexy::IMAGE_MINIGAME1_LABEL_TURNS;
Image* Sexy::IMAGE_MINIGAME1_LEGEND;
Image* Sexy::IMAGE_MINIGAME1_TAB_LEFT_DARK;
Image* Sexy::IMAGE_MINIGAME1_TAB_LEFT_LIT;
Image* Sexy::IMAGE_MINIGAME1_TILE_GOLD;
Image* Sexy::IMAGE_MINIGAME1_TILE_RED;
Image* Sexy::IMAGE_MINIGAME1_TILE_SILVER;
Image* Sexy::IMAGE_MINIGAME1_TITLE_WORDMASTER;
Image* Sexy::IMAGE_MINIGAME1_TURN_NUMBERS;
Image* Sexy::IMAGE_MINIGAME1_X_CHECK;

bool Sexy::ExtractMiniGame1Resources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_MINIGAME1_BRACKET = aMgr.GetImageThrow("IMAGE_MINIGAME1_BRACKET");
		IMAGE_MINIGAME1_ENTRY_BOXES = aMgr.GetImageThrow("IMAGE_MINIGAME1_ENTRY_BOXES");
		IMAGE_MINIGAME1_LABEL_TURNS = aMgr.GetImageThrow("IMAGE_MINIGAME1_LABEL_TURNS");
		IMAGE_MINIGAME1_LEGEND = aMgr.GetImageThrow("IMAGE_MINIGAME1_LEGEND");
		IMAGE_MINIGAME1_TAB_LEFT_DARK = aMgr.GetImageThrow("IMAGE_MINIGAME1_TAB_LEFT_DARK");
		IMAGE_MINIGAME1_TAB_LEFT_LIT = aMgr.GetImageThrow("IMAGE_MINIGAME1_TAB_LEFT_LIT");
		IMAGE_MINIGAME1_TILE_GOLD = aMgr.GetImageThrow("IMAGE_MINIGAME1_TILE_GOLD");
		IMAGE_MINIGAME1_TILE_RED = aMgr.GetImageThrow("IMAGE_MINIGAME1_TILE_RED");
		IMAGE_MINIGAME1_TILE_SILVER = aMgr.GetImageThrow("IMAGE_MINIGAME1_TILE_SILVER");
		IMAGE_MINIGAME1_TITLE_WORDMASTER = aMgr.GetImageThrow("IMAGE_MINIGAME1_TITLE_WORDMASTER");
		IMAGE_MINIGAME1_TURN_NUMBERS = aMgr.GetImageThrow("IMAGE_MINIGAME1_TURN_NUMBERS");
		IMAGE_MINIGAME1_X_CHECK = aMgr.GetImageThrow("IMAGE_MINIGAME1_X_CHECK");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// MiniGame2 Resources
Image* Sexy::IMAGE_MINIGAME2_GOLD_FILL;
Image* Sexy::IMAGE_MINIGAME2_LABEL_TIME;
Image* Sexy::IMAGE_MINIGAME2_SPELLING_BOX;
Image* Sexy::IMAGE_MINIGAME2_TIMER_FILLBAR;
Image* Sexy::IMAGE_MINIGAME2_TIMER_LEFT;
Image* Sexy::IMAGE_MINIGAME2_TITLE;

bool Sexy::ExtractMiniGame2Resources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_MINIGAME2_GOLD_FILL = aMgr.GetImageThrow("IMAGE_MINIGAME2_GOLD_FILL");
		IMAGE_MINIGAME2_LABEL_TIME = aMgr.GetImageThrow("IMAGE_MINIGAME2_LABEL_TIME");
		IMAGE_MINIGAME2_SPELLING_BOX = aMgr.GetImageThrow("IMAGE_MINIGAME2_SPELLING_BOX");
		IMAGE_MINIGAME2_TIMER_FILLBAR = aMgr.GetImageThrow("IMAGE_MINIGAME2_TIMER_FILLBAR");
		IMAGE_MINIGAME2_TIMER_LEFT = aMgr.GetImageThrow("IMAGE_MINIGAME2_TIMER_LEFT");
		IMAGE_MINIGAME2_TITLE = aMgr.GetImageThrow("IMAGE_MINIGAME2_TITLE");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// MiniGame3 Resources
Image* Sexy::IMAGE_MINIGAME3_BRACKET;
Image* Sexy::IMAGE_MINIGAME3_ENTRY_BOXES;
Image* Sexy::IMAGE_MINIGAME3_LABEL_TIME;
Image* Sexy::IMAGE_MINIGAME3_TILE_GOLD;
Image* Sexy::IMAGE_MINIGAME3_TILE_SILVER;
Image* Sexy::IMAGE_MINIGAME3_TIMER_FILLBAR;
Image* Sexy::IMAGE_MINIGAME3_TIMER_LEFT;
Image* Sexy::IMAGE_MINIGAME3_TITLE;
Image* Sexy::IMAGE_MINIGAME3_X_CHECK;

bool Sexy::ExtractMiniGame3Resources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_MINIGAME3_BRACKET = aMgr.GetImageThrow("IMAGE_MINIGAME3_BRACKET");
		IMAGE_MINIGAME3_ENTRY_BOXES = aMgr.GetImageThrow("IMAGE_MINIGAME3_ENTRY_BOXES");
		IMAGE_MINIGAME3_LABEL_TIME = aMgr.GetImageThrow("IMAGE_MINIGAME3_LABEL_TIME");
		IMAGE_MINIGAME3_TILE_GOLD = aMgr.GetImageThrow("IMAGE_MINIGAME3_TILE_GOLD");
		IMAGE_MINIGAME3_TILE_SILVER = aMgr.GetImageThrow("IMAGE_MINIGAME3_TILE_SILVER");
		IMAGE_MINIGAME3_TIMER_FILLBAR = aMgr.GetImageThrow("IMAGE_MINIGAME3_TIMER_FILLBAR");
		IMAGE_MINIGAME3_TIMER_LEFT = aMgr.GetImageThrow("IMAGE_MINIGAME3_TIMER_LEFT");
		IMAGE_MINIGAME3_TITLE = aMgr.GetImageThrow("IMAGE_MINIGAME3_TITLE");
		IMAGE_MINIGAME3_X_CHECK = aMgr.GetImageThrow("IMAGE_MINIGAME3_X_CHECK");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// MiniGame4 Resources
Image* Sexy::IMAGE_MINIGAME4_ARROW_LARGE;
Image* Sexy::IMAGE_MINIGAME4_ARROW_SMALL;
Image* Sexy::IMAGE_MINIGAME4_BG;
Image* Sexy::IMAGE_MINIGAME4_GOOD;
Image* Sexy::IMAGE_MINIGAME4_GREAT;
Image* Sexy::IMAGE_MINIGAME4_HINTBOX;
Image* Sexy::IMAGE_MINIGAME4_HINTGLOW;
Image* Sexy::IMAGE_MINIGAME4_LABEL_TIME;
Image* Sexy::IMAGE_MINIGAME4_TILEHL;
Image* Sexy::IMAGE_MINIGAME4_TILE_GOLD;
Image* Sexy::IMAGE_MINIGAME4_TILE_RED;
Image* Sexy::IMAGE_MINIGAME4_TIMER_DIVIDER;
Image* Sexy::IMAGE_MINIGAME4_TIMER_FILLBAR;
Image* Sexy::IMAGE_MINIGAME4_TIMER_LEFT;
Image* Sexy::IMAGE_MINIGAME4_TRAY3;
Image* Sexy::IMAGE_MINIGAME4_TRAY3_GOLD;
Image* Sexy::IMAGE_MINIGAME4_TRAY4;
Image* Sexy::IMAGE_MINIGAME4_TRAY4_GOLD;
Image* Sexy::IMAGE_MINIGAME4_TRAY5;
Image* Sexy::IMAGE_MINIGAME4_TRAY5_GOLD;
Image* Sexy::IMAGE_MINIGAME4_TRAY6;
Image* Sexy::IMAGE_MINIGAME4_TRAY6_GOLD;
Image* Sexy::IMAGE_MINIGAME4_TRAY7;
Image* Sexy::IMAGE_MINIGAME4_TRAY7_GOLD;

bool Sexy::ExtractMiniGame4Resources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_MINIGAME4_ARROW_LARGE = aMgr.GetImageThrow("IMAGE_MINIGAME4_ARROW_LARGE");
		IMAGE_MINIGAME4_ARROW_SMALL = aMgr.GetImageThrow("IMAGE_MINIGAME4_ARROW_SMALL");
		IMAGE_MINIGAME4_BG = aMgr.GetImageThrow("IMAGE_MINIGAME4_BG");
		IMAGE_MINIGAME4_GOOD = aMgr.GetImageThrow("IMAGE_MINIGAME4_GOOD");
		IMAGE_MINIGAME4_GREAT = aMgr.GetImageThrow("IMAGE_MINIGAME4_GREAT");
		IMAGE_MINIGAME4_HINTBOX = aMgr.GetImageThrow("IMAGE_MINIGAME4_HINTBOX");
		IMAGE_MINIGAME4_HINTGLOW = aMgr.GetImageThrow("IMAGE_MINIGAME4_HINTGLOW");
		IMAGE_MINIGAME4_LABEL_TIME = aMgr.GetImageThrow("IMAGE_MINIGAME4_LABEL_TIME");
		IMAGE_MINIGAME4_TILEHL = aMgr.GetImageThrow("IMAGE_MINIGAME4_TILEHL");
		IMAGE_MINIGAME4_TILE_GOLD = aMgr.GetImageThrow("IMAGE_MINIGAME4_TILE_GOLD");
		IMAGE_MINIGAME4_TILE_RED = aMgr.GetImageThrow("IMAGE_MINIGAME4_TILE_RED");
		IMAGE_MINIGAME4_TIMER_DIVIDER = aMgr.GetImageThrow("IMAGE_MINIGAME4_TIMER_DIVIDER");
		IMAGE_MINIGAME4_TIMER_FILLBAR = aMgr.GetImageThrow("IMAGE_MINIGAME4_TIMER_FILLBAR");
		IMAGE_MINIGAME4_TIMER_LEFT = aMgr.GetImageThrow("IMAGE_MINIGAME4_TIMER_LEFT");
		IMAGE_MINIGAME4_TRAY3 = aMgr.GetImageThrow("IMAGE_MINIGAME4_TRAY3");
		IMAGE_MINIGAME4_TRAY3_GOLD = aMgr.GetImageThrow("IMAGE_MINIGAME4_TRAY3_GOLD");
		IMAGE_MINIGAME4_TRAY4 = aMgr.GetImageThrow("IMAGE_MINIGAME4_TRAY4");
		IMAGE_MINIGAME4_TRAY4_GOLD = aMgr.GetImageThrow("IMAGE_MINIGAME4_TRAY4_GOLD");
		IMAGE_MINIGAME4_TRAY5 = aMgr.GetImageThrow("IMAGE_MINIGAME4_TRAY5");
		IMAGE_MINIGAME4_TRAY5_GOLD = aMgr.GetImageThrow("IMAGE_MINIGAME4_TRAY5_GOLD");
		IMAGE_MINIGAME4_TRAY6 = aMgr.GetImageThrow("IMAGE_MINIGAME4_TRAY6");
		IMAGE_MINIGAME4_TRAY6_GOLD = aMgr.GetImageThrow("IMAGE_MINIGAME4_TRAY6_GOLD");
		IMAGE_MINIGAME4_TRAY7 = aMgr.GetImageThrow("IMAGE_MINIGAME4_TRAY7");
		IMAGE_MINIGAME4_TRAY7_GOLD = aMgr.GetImageThrow("IMAGE_MINIGAME4_TRAY7_GOLD");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// MiniGame5 Resources
Image* Sexy::IMAGE_MINIGAME5_CLOUDS;
Image* Sexy::IMAGE_MINIGAME5_CURTAINS;
Image* Sexy::IMAGE_MINIGAME5_FLAG_GREEN;
Image* Sexy::IMAGE_MINIGAME5_FLAG_YELLOW;
Image* Sexy::IMAGE_MINIGAME5_MOUNTAIN1;
Image* Sexy::IMAGE_MINIGAME5_MOUNTAIN2;
Image* Sexy::IMAGE_MINIGAME5_MOXIE_STUN;
Image* Sexy::IMAGE_MINIGAME5_OHNO;
Image* Sexy::IMAGE_MINIGAME5_PUPPET_LEX;
Image* Sexy::IMAGE_MINIGAME5_PUPPET_MOXIE;
Image* Sexy::IMAGE_MINIGAME5_SIGN;
Image* Sexy::IMAGE_MINIGAME5_SKY;
Image* Sexy::IMAGE_MINIGAME5_SPELLING_BOX;
Image* Sexy::IMAGE_MINIGAME5_SUN;
Image* Sexy::IMAGE_MINIGAME5_TITLE;

bool Sexy::ExtractMiniGame5Resources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_MINIGAME5_CLOUDS = aMgr.GetImageThrow("IMAGE_MINIGAME5_CLOUDS");
		IMAGE_MINIGAME5_CURTAINS = aMgr.GetImageThrow("IMAGE_MINIGAME5_CURTAINS");
		IMAGE_MINIGAME5_FLAG_GREEN = aMgr.GetImageThrow("IMAGE_MINIGAME5_FLAG_GREEN");
		IMAGE_MINIGAME5_FLAG_YELLOW = aMgr.GetImageThrow("IMAGE_MINIGAME5_FLAG_YELLOW");
		IMAGE_MINIGAME5_MOUNTAIN1 = aMgr.GetImageThrow("IMAGE_MINIGAME5_MOUNTAIN1");
		IMAGE_MINIGAME5_MOUNTAIN2 = aMgr.GetImageThrow("IMAGE_MINIGAME5_MOUNTAIN2");
		IMAGE_MINIGAME5_MOXIE_STUN = aMgr.GetImageThrow("IMAGE_MINIGAME5_MOXIE_STUN");
		IMAGE_MINIGAME5_OHNO = aMgr.GetImageThrow("IMAGE_MINIGAME5_OHNO");
		IMAGE_MINIGAME5_PUPPET_LEX = aMgr.GetImageThrow("IMAGE_MINIGAME5_PUPPET_LEX");
		IMAGE_MINIGAME5_PUPPET_MOXIE = aMgr.GetImageThrow("IMAGE_MINIGAME5_PUPPET_MOXIE");
		IMAGE_MINIGAME5_SIGN = aMgr.GetImageThrow("IMAGE_MINIGAME5_SIGN");
		IMAGE_MINIGAME5_SKY = aMgr.GetImageThrow("IMAGE_MINIGAME5_SKY");
		IMAGE_MINIGAME5_SPELLING_BOX = aMgr.GetImageThrow("IMAGE_MINIGAME5_SPELLING_BOX");
		IMAGE_MINIGAME5_SUN = aMgr.GetImageThrow("IMAGE_MINIGAME5_SUN");
		IMAGE_MINIGAME5_TITLE = aMgr.GetImageThrow("IMAGE_MINIGAME5_TITLE");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// MiniGame6 Resources
Image* Sexy::IMAGE_MINIGAME6_BG;
Image* Sexy::IMAGE_MINIGAME6_BOARD;
Image* Sexy::IMAGE_MINIGAME6_LABEL_TIME;
Image* Sexy::IMAGE_MINIGAME6_TILE_GOLD;
Image* Sexy::IMAGE_MINIGAME6_TIMER_FILLBAR;
Image* Sexy::IMAGE_MINIGAME6_TIMER_LEFT;
Image* Sexy::IMAGE_MINIGAME6_TITLESCROLL;
Image* Sexy::IMAGE_MINIGAME6_TRAY3;
Image* Sexy::IMAGE_MINIGAME6_TRAY3_GOLD;
Image* Sexy::IMAGE_MINIGAME6_TRAY4;
Image* Sexy::IMAGE_MINIGAME6_TRAY4_GOLD;
Image* Sexy::IMAGE_MINIGAME6_TRAY5;
Image* Sexy::IMAGE_MINIGAME6_TRAY5_GOLD;
Image* Sexy::IMAGE_MINIGAME6_TRAY6;
Image* Sexy::IMAGE_MINIGAME6_TRAY6_GOLD;
Image* Sexy::IMAGE_MINIGAME6_TRAY7;
Image* Sexy::IMAGE_MINIGAME6_TRAY7_GOLD;

bool Sexy::ExtractMiniGame6Resources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_MINIGAME6_BG = aMgr.GetImageThrow("IMAGE_MINIGAME6_BG");
		IMAGE_MINIGAME6_BOARD = aMgr.GetImageThrow("IMAGE_MINIGAME6_BOARD");
		IMAGE_MINIGAME6_LABEL_TIME = aMgr.GetImageThrow("IMAGE_MINIGAME6_LABEL_TIME");
		IMAGE_MINIGAME6_TILE_GOLD = aMgr.GetImageThrow("IMAGE_MINIGAME6_TILE_GOLD");
		IMAGE_MINIGAME6_TIMER_FILLBAR = aMgr.GetImageThrow("IMAGE_MINIGAME6_TIMER_FILLBAR");
		IMAGE_MINIGAME6_TIMER_LEFT = aMgr.GetImageThrow("IMAGE_MINIGAME6_TIMER_LEFT");
		IMAGE_MINIGAME6_TITLESCROLL = aMgr.GetImageThrow("IMAGE_MINIGAME6_TITLESCROLL");
		IMAGE_MINIGAME6_TRAY3 = aMgr.GetImageThrow("IMAGE_MINIGAME6_TRAY3");
		IMAGE_MINIGAME6_TRAY3_GOLD = aMgr.GetImageThrow("IMAGE_MINIGAME6_TRAY3_GOLD");
		IMAGE_MINIGAME6_TRAY4 = aMgr.GetImageThrow("IMAGE_MINIGAME6_TRAY4");
		IMAGE_MINIGAME6_TRAY4_GOLD = aMgr.GetImageThrow("IMAGE_MINIGAME6_TRAY4_GOLD");
		IMAGE_MINIGAME6_TRAY5 = aMgr.GetImageThrow("IMAGE_MINIGAME6_TRAY5");
		IMAGE_MINIGAME6_TRAY5_GOLD = aMgr.GetImageThrow("IMAGE_MINIGAME6_TRAY5_GOLD");
		IMAGE_MINIGAME6_TRAY6 = aMgr.GetImageThrow("IMAGE_MINIGAME6_TRAY6");
		IMAGE_MINIGAME6_TRAY6_GOLD = aMgr.GetImageThrow("IMAGE_MINIGAME6_TRAY6_GOLD");
		IMAGE_MINIGAME6_TRAY7 = aMgr.GetImageThrow("IMAGE_MINIGAME6_TRAY7");
		IMAGE_MINIGAME6_TRAY7_GOLD = aMgr.GetImageThrow("IMAGE_MINIGAME6_TRAY7_GOLD");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// MiniGame7 Resources
Image* Sexy::IMAGE_MINIGAME7_BG;
Image* Sexy::IMAGE_MINIGAME7_BOARD;
Image* Sexy::IMAGE_MINIGAME7_BRONZE_COIN;
Image* Sexy::IMAGE_MINIGAME7_GOLD_COIN;
Image* Sexy::IMAGE_MINIGAME7_TILE_GOLD;
Image* Sexy::IMAGE_MINIGAME7_TITLESCROLL;

bool Sexy::ExtractMiniGame7Resources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_MINIGAME7_BG = aMgr.GetImageThrow("IMAGE_MINIGAME7_BG");
		IMAGE_MINIGAME7_BOARD = aMgr.GetImageThrow("IMAGE_MINIGAME7_BOARD");
		IMAGE_MINIGAME7_BRONZE_COIN = aMgr.GetImageThrow("IMAGE_MINIGAME7_BRONZE_COIN");
		IMAGE_MINIGAME7_GOLD_COIN = aMgr.GetImageThrow("IMAGE_MINIGAME7_GOLD_COIN");
		IMAGE_MINIGAME7_TILE_GOLD = aMgr.GetImageThrow("IMAGE_MINIGAME7_TILE_GOLD");
		IMAGE_MINIGAME7_TITLESCROLL = aMgr.GetImageThrow("IMAGE_MINIGAME7_TITLESCROLL");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

static void* gResources[] =
{
	&IMAGE_MINIMENU_LETTER_RIP_BTN,
	&IMAGE_MINIMENU_LINKNSPELL_BTN,
	&IMAGE_MINIMENU_WORDMASTER_BTN,
	&IMAGE_MINIMENU_WORDUP_BTN,
	&IMAGE_MINIMENU_MUTANTWORDS_BTN,
	&IMAGE_MINIMENU_GOLDENCOINS_BTN,
	&IMAGE_MINIGAME1_BRACKET,
	&IMAGE_MINIGAME1_ENTRY_BOXES,
	&IMAGE_MINIGAME1_LABEL_TURNS,
	&IMAGE_MINIGAME1_X_CHECK,
	&IMAGE_MINIGAME1_TAB_LEFT_DARK,
	&IMAGE_MINIGAME1_TAB_LEFT_LIT,
	&IMAGE_MINIGAME1_TILE_GOLD,
	&IMAGE_MINIGAME1_TILE_SILVER,
	&IMAGE_MINIGAME1_TILE_RED,
	&IMAGE_MINIGAME1_TITLE_WORDMASTER,
	&IMAGE_MINIGAME1_TURN_NUMBERS,
	&IMAGE_MINIGAME1_LEGEND,
	&IMAGE_MINIGAME2_TITLE,
	&IMAGE_MINIGAME2_GOLD_FILL,
	&IMAGE_MINIGAME2_LABEL_TIME,
	&IMAGE_MINIGAME2_SPELLING_BOX,
	&IMAGE_MINIGAME2_TIMER_FILLBAR,
	&IMAGE_MINIGAME2_TIMER_LEFT,
	&IMAGE_MINIGAME3_TITLE,
	&IMAGE_MINIGAME3_ENTRY_BOXES,
	&IMAGE_MINIGAME3_TIMER_FILLBAR,
	&IMAGE_MINIGAME3_TIMER_LEFT,
	&IMAGE_MINIGAME3_LABEL_TIME,
	&IMAGE_MINIGAME3_TILE_GOLD,
	&IMAGE_MINIGAME3_TILE_SILVER,
	&IMAGE_MINIGAME3_BRACKET,
	&IMAGE_MINIGAME3_X_CHECK,
	&IMAGE_MINIGAME4_BG,
	&IMAGE_MINIGAME4_GOOD,
	&IMAGE_MINIGAME4_GREAT,
	&IMAGE_MINIGAME4_TIMER_FILLBAR,
	&IMAGE_MINIGAME4_ARROW_LARGE,
	&IMAGE_MINIGAME4_ARROW_SMALL,
	&IMAGE_MINIGAME4_HINTBOX,
	&IMAGE_MINIGAME4_TIMER_DIVIDER,
	&IMAGE_MINIGAME4_TRAY3,
	&IMAGE_MINIGAME4_TRAY3_GOLD,
	&IMAGE_MINIGAME4_TRAY4,
	&IMAGE_MINIGAME4_TRAY4_GOLD,
	&IMAGE_MINIGAME4_TRAY5,
	&IMAGE_MINIGAME4_TRAY5_GOLD,
	&IMAGE_MINIGAME4_TRAY6,
	&IMAGE_MINIGAME4_TRAY6_GOLD,
	&IMAGE_MINIGAME4_TRAY7,
	&IMAGE_MINIGAME4_TRAY7_GOLD,
	&IMAGE_MINIGAME4_TILEHL,
	&IMAGE_MINIGAME4_TIMER_LEFT,
	&IMAGE_MINIGAME4_LABEL_TIME,
	&IMAGE_MINIGAME4_TILE_GOLD,
	&IMAGE_MINIGAME4_TILE_RED,
	&IMAGE_MINIGAME4_HINTGLOW,
	&IMAGE_MINIGAME5_TITLE,
	&IMAGE_MINIGAME5_SPELLING_BOX,
	&IMAGE_MINIGAME5_CLOUDS,
	&IMAGE_MINIGAME5_CURTAINS,
	&IMAGE_MINIGAME5_FLAG_GREEN,
	&IMAGE_MINIGAME5_FLAG_YELLOW,
	&IMAGE_MINIGAME5_MOUNTAIN1,
	&IMAGE_MINIGAME5_MOUNTAIN2,
	&IMAGE_MINIGAME5_PUPPET_LEX,
	&IMAGE_MINIGAME5_PUPPET_MOXIE,
	&IMAGE_MINIGAME5_SIGN,
	&IMAGE_MINIGAME5_SKY,
	&IMAGE_MINIGAME5_SUN,
	&IMAGE_MINIGAME5_MOXIE_STUN,
	&IMAGE_MINIGAME5_OHNO,
	&IMAGE_MINIGAME6_TITLESCROLL,
	&IMAGE_MINIGAME6_BG,
	&IMAGE_MINIGAME6_BOARD,
	&IMAGE_MINIGAME6_TRAY3,
	&IMAGE_MINIGAME6_TRAY3_GOLD,
	&IMAGE_MINIGAME6_TRAY4,
	&IMAGE_MINIGAME6_TRAY4_GOLD,
	&IMAGE_MINIGAME6_TRAY5,
	&IMAGE_MINIGAME6_TRAY5_GOLD,
	&IMAGE_MINIGAME6_TRAY6,
	&IMAGE_MINIGAME6_TRAY6_GOLD,
	&IMAGE_MINIGAME6_TRAY7,
	&IMAGE_MINIGAME6_TRAY7_GOLD,
	&IMAGE_MINIGAME6_TIMER_FILLBAR,
	&IMAGE_MINIGAME6_TIMER_LEFT,
	&IMAGE_MINIGAME6_LABEL_TIME,
	&IMAGE_MINIGAME6_TILE_GOLD,
	&IMAGE_MINIGAME7_TITLESCROLL,
	&IMAGE_MINIGAME7_BG,
	&IMAGE_MINIGAME7_BOARD,
	&IMAGE_MINIGAME7_BRONZE_COIN,
	&IMAGE_MINIGAME7_GOLD_COIN,
	&IMAGE_MINIGAME7_TILE_GOLD,
	NULL
};

Image* Sexy::LoadImageById(ResourceManager *theManager, int theId)
{
	return (*((Image**)gResources[theId]) = theManager->LoadImage(GetStringIdById(theId)));
}

void Sexy::ReplaceImageById(ResourceManager *theManager, int theId, Image *theImage)
{
	theManager->ReplaceImage(GetStringIdById(theId),theImage);
	*(Image**)gResources[theId] = theImage;
}

Image* Sexy::GetImageById(int theId)
{
	return *(Image**)gResources[theId];
}

Font* Sexy::GetFontById(int theId)
{
	return *(Font**)gResources[theId];
}

int Sexy::GetSoundById(int theId)
{
	return *(int*)gResources[theId];
}

Image*& Sexy::GetImageRefById(int theId)
{
	return *(Image**)gResources[theId];
}

Font*& Sexy::GetFontRefById(int theId)
{
	return *(Font**)gResources[theId];
}

int& Sexy::GetSoundRefById(int theId)
{
	return *(int*)gResources[theId];
}

static Sexy::ResourceId GetIdByVariable(const void *theVariable)
{
	typedef std::map<int,int> MyMap;
	static MyMap aMap;
	if(gNeedRecalcVariableToIdMap)
	{
		gNeedRecalcVariableToIdMap = false;
		aMap.clear();
		for(int i=0; i<RESOURCE_ID_MAX; i++)
			aMap[*(int*)gResources[i]] = i;
	}

	MyMap::iterator anItr = aMap.find((int)theVariable);
	if (anItr == aMap.end())
		return RESOURCE_ID_MAX;
	else
		return (ResourceId) anItr->second;
}

Sexy::ResourceId Sexy::GetIdByImage(Image *theImage)
{
	return GetIdByVariable(theImage);
}

Sexy::ResourceId Sexy::GetIdByFont(Font *theFont)
{
	return GetIdByVariable(theFont);
}

Sexy::ResourceId Sexy::GetIdBySound(int theSound)
{
	return GetIdByVariable((void*)theSound);
}

const char* Sexy::GetStringIdById(int theId)
{
	switch(theId)
	{
		case IMAGE_MINIMENU_LETTER_RIP_BTN_ID: return "IMAGE_MINIMENU_LETTER_RIP_BTN";
		case IMAGE_MINIMENU_LINKNSPELL_BTN_ID: return "IMAGE_MINIMENU_LINKNSPELL_BTN";
		case IMAGE_MINIMENU_WORDMASTER_BTN_ID: return "IMAGE_MINIMENU_WORDMASTER_BTN";
		case IMAGE_MINIMENU_WORDUP_BTN_ID: return "IMAGE_MINIMENU_WORDUP_BTN";
		case IMAGE_MINIMENU_MUTANTWORDS_BTN_ID: return "IMAGE_MINIMENU_MUTANTWORDS_BTN";
		case IMAGE_MINIMENU_GOLDENCOINS_BTN_ID: return "IMAGE_MINIMENU_GOLDENCOINS_BTN";
		case IMAGE_MINIGAME1_BRACKET_ID: return "IMAGE_MINIGAME1_BRACKET";
		case IMAGE_MINIGAME1_ENTRY_BOXES_ID: return "IMAGE_MINIGAME1_ENTRY_BOXES";
		case IMAGE_MINIGAME1_LABEL_TURNS_ID: return "IMAGE_MINIGAME1_LABEL_TURNS";
		case IMAGE_MINIGAME1_X_CHECK_ID: return "IMAGE_MINIGAME1_X_CHECK";
		case IMAGE_MINIGAME1_TAB_LEFT_DARK_ID: return "IMAGE_MINIGAME1_TAB_LEFT_DARK";
		case IMAGE_MINIGAME1_TAB_LEFT_LIT_ID: return "IMAGE_MINIGAME1_TAB_LEFT_LIT";
		case IMAGE_MINIGAME1_TILE_GOLD_ID: return "IMAGE_MINIGAME1_TILE_GOLD";
		case IMAGE_MINIGAME1_TILE_SILVER_ID: return "IMAGE_MINIGAME1_TILE_SILVER";
		case IMAGE_MINIGAME1_TILE_RED_ID: return "IMAGE_MINIGAME1_TILE_RED";
		case IMAGE_MINIGAME1_TITLE_WORDMASTER_ID: return "IMAGE_MINIGAME1_TITLE_WORDMASTER";
		case IMAGE_MINIGAME1_TURN_NUMBERS_ID: return "IMAGE_MINIGAME1_TURN_NUMBERS";
		case IMAGE_MINIGAME1_LEGEND_ID: return "IMAGE_MINIGAME1_LEGEND";
		case IMAGE_MINIGAME2_TITLE_ID: return "IMAGE_MINIGAME2_TITLE";
		case IMAGE_MINIGAME2_GOLD_FILL_ID: return "IMAGE_MINIGAME2_GOLD_FILL";
		case IMAGE_MINIGAME2_LABEL_TIME_ID: return "IMAGE_MINIGAME2_LABEL_TIME";
		case IMAGE_MINIGAME2_SPELLING_BOX_ID: return "IMAGE_MINIGAME2_SPELLING_BOX";
		case IMAGE_MINIGAME2_TIMER_FILLBAR_ID: return "IMAGE_MINIGAME2_TIMER_FILLBAR";
		case IMAGE_MINIGAME2_TIMER_LEFT_ID: return "IMAGE_MINIGAME2_TIMER_LEFT";
		case IMAGE_MINIGAME3_TITLE_ID: return "IMAGE_MINIGAME3_TITLE";
		case IMAGE_MINIGAME3_ENTRY_BOXES_ID: return "IMAGE_MINIGAME3_ENTRY_BOXES";
		case IMAGE_MINIGAME3_TIMER_FILLBAR_ID: return "IMAGE_MINIGAME3_TIMER_FILLBAR";
		case IMAGE_MINIGAME3_TIMER_LEFT_ID: return "IMAGE_MINIGAME3_TIMER_LEFT";
		case IMAGE_MINIGAME3_LABEL_TIME_ID: return "IMAGE_MINIGAME3_LABEL_TIME";
		case IMAGE_MINIGAME3_TILE_GOLD_ID: return "IMAGE_MINIGAME3_TILE_GOLD";
		case IMAGE_MINIGAME3_TILE_SILVER_ID: return "IMAGE_MINIGAME3_TILE_SILVER";
		case IMAGE_MINIGAME3_BRACKET_ID: return "IMAGE_MINIGAME3_BRACKET";
		case IMAGE_MINIGAME3_X_CHECK_ID: return "IMAGE_MINIGAME3_X_CHECK";
		case IMAGE_MINIGAME4_BG_ID: return "IMAGE_MINIGAME4_BG";
		case IMAGE_MINIGAME4_GOOD_ID: return "IMAGE_MINIGAME4_GOOD";
		case IMAGE_MINIGAME4_GREAT_ID: return "IMAGE_MINIGAME4_GREAT";
		case IMAGE_MINIGAME4_TIMER_FILLBAR_ID: return "IMAGE_MINIGAME4_TIMER_FILLBAR";
		case IMAGE_MINIGAME4_ARROW_LARGE_ID: return "IMAGE_MINIGAME4_ARROW_LARGE";
		case IMAGE_MINIGAME4_ARROW_SMALL_ID: return "IMAGE_MINIGAME4_ARROW_SMALL";
		case IMAGE_MINIGAME4_HINTBOX_ID: return "IMAGE_MINIGAME4_HINTBOX";
		case IMAGE_MINIGAME4_TIMER_DIVIDER_ID: return "IMAGE_MINIGAME4_TIMER_DIVIDER";
		case IMAGE_MINIGAME4_TRAY3_ID: return "IMAGE_MINIGAME4_TRAY3";
		case IMAGE_MINIGAME4_TRAY3_GOLD_ID: return "IMAGE_MINIGAME4_TRAY3_GOLD";
		case IMAGE_MINIGAME4_TRAY4_ID: return "IMAGE_MINIGAME4_TRAY4";
		case IMAGE_MINIGAME4_TRAY4_GOLD_ID: return "IMAGE_MINIGAME4_TRAY4_GOLD";
		case IMAGE_MINIGAME4_TRAY5_ID: return "IMAGE_MINIGAME4_TRAY5";
		case IMAGE_MINIGAME4_TRAY5_GOLD_ID: return "IMAGE_MINIGAME4_TRAY5_GOLD";
		case IMAGE_MINIGAME4_TRAY6_ID: return "IMAGE_MINIGAME4_TRAY6";
		case IMAGE_MINIGAME4_TRAY6_GOLD_ID: return "IMAGE_MINIGAME4_TRAY6_GOLD";
		case IMAGE_MINIGAME4_TRAY7_ID: return "IMAGE_MINIGAME4_TRAY7";
		case IMAGE_MINIGAME4_TRAY7_GOLD_ID: return "IMAGE_MINIGAME4_TRAY7_GOLD";
		case IMAGE_MINIGAME4_TILEHL_ID: return "IMAGE_MINIGAME4_TILEHL";
		case IMAGE_MINIGAME4_TIMER_LEFT_ID: return "IMAGE_MINIGAME4_TIMER_LEFT";
		case IMAGE_MINIGAME4_LABEL_TIME_ID: return "IMAGE_MINIGAME4_LABEL_TIME";
		case IMAGE_MINIGAME4_TILE_GOLD_ID: return "IMAGE_MINIGAME4_TILE_GOLD";
		case IMAGE_MINIGAME4_TILE_RED_ID: return "IMAGE_MINIGAME4_TILE_RED";
		case IMAGE_MINIGAME4_HINTGLOW_ID: return "IMAGE_MINIGAME4_HINTGLOW";
		case IMAGE_MINIGAME5_TITLE_ID: return "IMAGE_MINIGAME5_TITLE";
		case IMAGE_MINIGAME5_SPELLING_BOX_ID: return "IMAGE_MINIGAME5_SPELLING_BOX";
		case IMAGE_MINIGAME5_CLOUDS_ID: return "IMAGE_MINIGAME5_CLOUDS";
		case IMAGE_MINIGAME5_CURTAINS_ID: return "IMAGE_MINIGAME5_CURTAINS";
		case IMAGE_MINIGAME5_FLAG_GREEN_ID: return "IMAGE_MINIGAME5_FLAG_GREEN";
		case IMAGE_MINIGAME5_FLAG_YELLOW_ID: return "IMAGE_MINIGAME5_FLAG_YELLOW";
		case IMAGE_MINIGAME5_MOUNTAIN1_ID: return "IMAGE_MINIGAME5_MOUNTAIN1";
		case IMAGE_MINIGAME5_MOUNTAIN2_ID: return "IMAGE_MINIGAME5_MOUNTAIN2";
		case IMAGE_MINIGAME5_PUPPET_LEX_ID: return "IMAGE_MINIGAME5_PUPPET_LEX";
		case IMAGE_MINIGAME5_PUPPET_MOXIE_ID: return "IMAGE_MINIGAME5_PUPPET_MOXIE";
		case IMAGE_MINIGAME5_SIGN_ID: return "IMAGE_MINIGAME5_SIGN";
		case IMAGE_MINIGAME5_SKY_ID: return "IMAGE_MINIGAME5_SKY";
		case IMAGE_MINIGAME5_SUN_ID: return "IMAGE_MINIGAME5_SUN";
		case IMAGE_MINIGAME5_MOXIE_STUN_ID: return "IMAGE_MINIGAME5_MOXIE_STUN";
		case IMAGE_MINIGAME5_OHNO_ID: return "IMAGE_MINIGAME5_OHNO";
		case IMAGE_MINIGAME6_TITLESCROLL_ID: return "IMAGE_MINIGAME6_TITLESCROLL";
		case IMAGE_MINIGAME6_BG_ID: return "IMAGE_MINIGAME6_BG";
		case IMAGE_MINIGAME6_BOARD_ID: return "IMAGE_MINIGAME6_BOARD";
		case IMAGE_MINIGAME6_TRAY3_ID: return "IMAGE_MINIGAME6_TRAY3";
		case IMAGE_MINIGAME6_TRAY3_GOLD_ID: return "IMAGE_MINIGAME6_TRAY3_GOLD";
		case IMAGE_MINIGAME6_TRAY4_ID: return "IMAGE_MINIGAME6_TRAY4";
		case IMAGE_MINIGAME6_TRAY4_GOLD_ID: return "IMAGE_MINIGAME6_TRAY4_GOLD";
		case IMAGE_MINIGAME6_TRAY5_ID: return "IMAGE_MINIGAME6_TRAY5";
		case IMAGE_MINIGAME6_TRAY5_GOLD_ID: return "IMAGE_MINIGAME6_TRAY5_GOLD";
		case IMAGE_MINIGAME6_TRAY6_ID: return "IMAGE_MINIGAME6_TRAY6";
		case IMAGE_MINIGAME6_TRAY6_GOLD_ID: return "IMAGE_MINIGAME6_TRAY6_GOLD";
		case IMAGE_MINIGAME6_TRAY7_ID: return "IMAGE_MINIGAME6_TRAY7";
		case IMAGE_MINIGAME6_TRAY7_GOLD_ID: return "IMAGE_MINIGAME6_TRAY7_GOLD";
		case IMAGE_MINIGAME6_TIMER_FILLBAR_ID: return "IMAGE_MINIGAME6_TIMER_FILLBAR";
		case IMAGE_MINIGAME6_TIMER_LEFT_ID: return "IMAGE_MINIGAME6_TIMER_LEFT";
		case IMAGE_MINIGAME6_LABEL_TIME_ID: return "IMAGE_MINIGAME6_LABEL_TIME";
		case IMAGE_MINIGAME6_TILE_GOLD_ID: return "IMAGE_MINIGAME6_TILE_GOLD";
		case IMAGE_MINIGAME7_TITLESCROLL_ID: return "IMAGE_MINIGAME7_TITLESCROLL";
		case IMAGE_MINIGAME7_BG_ID: return "IMAGE_MINIGAME7_BG";
		case IMAGE_MINIGAME7_BOARD_ID: return "IMAGE_MINIGAME7_BOARD";
		case IMAGE_MINIGAME7_BRONZE_COIN_ID: return "IMAGE_MINIGAME7_BRONZE_COIN";
		case IMAGE_MINIGAME7_GOLD_COIN_ID: return "IMAGE_MINIGAME7_GOLD_COIN";
		case IMAGE_MINIGAME7_TILE_GOLD_ID: return "IMAGE_MINIGAME7_TILE_GOLD";
		default: return "";
	}
}

