#ifndef __TimedMode_H__
#define __TimedMode_H__

namespace Sexy
{
	class ResourceManager;
	class Image;
	class Font;

	Image* LoadImageById(ResourceManager *theManager, int theId);
	void ReplaceImageById(ResourceManager *theManager, int theId, Image *theImage);
	bool ExtractResourcesByName(ResourceManager *theManager, const char *theName);

	// TimedModeCommon Resources
	bool ExtractTimedModeCommonResources(ResourceManager *theMgr);
	extern Image* IMAGE_TMA_BG;
	extern Image* IMAGE_TMA_CHECKPOINT;
	extern Image* IMAGE_TMA_COUNTDOWN;
	extern Image* IMAGE_TMA_ENEMY_ATTACKING;
	extern Image* IMAGE_TMA_TIMERBAR;
	extern Image* IMAGE_TMA_TIMERBAR_FILL;
	extern int SOUND_ARENA_ARROW_SHOT;
	extern int SOUND_ARENA_BEAR_ATTACK;
	extern int SOUND_ARENA_BEAR_IMPACT;
	extern int SOUND_ARENA_BEAR_ROAR;
	extern int SOUND_ARENA_BOVINE_ATTACK2;
	extern int SOUND_ARENA_DOG_BARK1;
	extern int SOUND_ARENA_DOG_BARK2;
	extern int SOUND_ARENA_DOG_WHIMPER;
	extern int SOUND_ARENA_DRAGON_BITE;
	extern int SOUND_ARENA_DRAGON_DEATH;
	extern int SOUND_ARENA_DRAGON_PAIN;
	extern int SOUND_ARENA_DRAGON_ROAR;
	extern int SOUND_ARENA_EXPLOSION_3;
	extern int SOUND_ARENA_FELINE_ENGAGE;
	extern int SOUND_ARENA_FELINE_ROAR;
	extern int SOUND_ARENA_FEMALE_GROAN1;
	extern int SOUND_ARENA_FEMALE_GROAN2;
	extern int SOUND_ARENA_FEMALE_SEDUCE;
	extern int SOUND_ARENA_FIRE_6;
	extern int SOUND_ARENA_GIANT_GRUNT2;
	extern int SOUND_ARENA_KUBWA_ROAR;
	extern int SOUND_ARENA_LIGHTNING_ATTACK;
	extern int SOUND_ARENA_MALE_ANGER;
	extern int SOUND_ARENA_MALE_GRUNT2;
	extern int SOUND_ARENA_MALE_LAUGH2;
	extern int SOUND_ARENA_MALE_LAUGH;
	extern int SOUND_ARENA_MALE_LOW_ANGER;
	extern int SOUND_ARENA_MALE_LOW_PAIN;
	extern int SOUND_ARENA_MALE_LOW_WARCRY;
	extern int SOUND_ARENA_MALE_PAIN;
	extern int SOUND_ARENA_MISC_IMPACT2;
	extern int SOUND_ARENA_MISC_IMPACT;
	extern int SOUND_ARENA_MONKEY_ATTACK;
	extern int SOUND_ARENA_MONSTER_ATTACK;
	extern int SOUND_ARENA_MONSTER_CHALLENGE;
	extern int SOUND_ARENA_MONSTER_IMPACT;
	extern int SOUND_ARENA_OGRE_ATTACK2;
	extern int SOUND_ARENA_OGRE_ATTACK;
	extern int SOUND_ARENA_OGRE_CHALLENGE2;
	extern int SOUND_ARENA_OGRE_CHALLENGE;
	extern int SOUND_ARENA_OGRE_IMPACT2;
	extern int SOUND_ARENA_OGRE_IMPACT3;
	extern int SOUND_ARENA_PLATE_ATTACK2;
	extern int SOUND_ARENA_PLATE_ATTACK3;
	extern int SOUND_ARENA_PLATE_ATTACK4;
	extern int SOUND_ARENA_PLATE_IMPACT4;
	extern int SOUND_ARENA_PLATE_IMPACT5;
	extern int SOUND_ARENA_PLATE_IMPACT6;
	extern int SOUND_ARENA_ROBOT_ATTACK;
	extern int SOUND_ARENA_ROBOT_CHALLENGE;
	extern int SOUND_ARENA_ROBOT_IMPACT;
	extern int SOUND_ARENA_SCIFI_LASER;
	extern int SOUND_ARENA_SCIFI_MECH2;
	extern int SOUND_ARENA_SCIFI_MECH;
	extern int SOUND_ARENA_SCIFI_TELEPORT;
	extern int SOUND_ARENA_SLICING_ATTACK2;
	extern int SOUND_ARENA_SLICING_ATTACK;
	extern int SOUND_ARENA_SMOKE_ATTACK2;
	extern int SOUND_ARENA_SMOKE_ATTACK;
	extern int SOUND_ARENA_SMOKE_IMPACT;
	extern int SOUND_ARENA_SONIC_ATTACK;
	extern int SOUND_ARENA_SPARKLE_ATTACK;
	extern int SOUND_ARENA_SQ_MAM_ATTACK;
	extern int SOUND_ARENA_SQ_MAM_DEATH;
	extern int SOUND_ARENA_STRING_ATTACK;
	extern int SOUND_ARENA_SWORD_IMPACT3;
	extern int SOUND_ARENA_WITCH_GROAN;
	extern int SOUND_ARENA_WITCH_LAUGH2;
	extern int SOUND_ARENA_WITCH_LAUGH;
	extern int SOUND_ARENA_WOLF_HOWL;

	enum ResourceId
	{
		IMAGE_TMA_BG_ID,
		IMAGE_TMA_ENEMY_ATTACKING_ID,
		IMAGE_TMA_TIMERBAR_ID,
		IMAGE_TMA_TIMERBAR_FILL_ID,
		IMAGE_TMA_CHECKPOINT_ID,
		IMAGE_TMA_COUNTDOWN_ID,
		SOUND_ARENA_ARROW_SHOT_ID,
		SOUND_ARENA_BEAR_ATTACK_ID,
		SOUND_ARENA_BEAR_IMPACT_ID,
		SOUND_ARENA_BEAR_ROAR_ID,
		SOUND_ARENA_BOVINE_ATTACK2_ID,
		SOUND_ARENA_DOG_BARK1_ID,
		SOUND_ARENA_DOG_BARK2_ID,
		SOUND_ARENA_DOG_WHIMPER_ID,
		SOUND_ARENA_DRAGON_BITE_ID,
		SOUND_ARENA_DRAGON_DEATH_ID,
		SOUND_ARENA_DRAGON_PAIN_ID,
		SOUND_ARENA_DRAGON_ROAR_ID,
		SOUND_ARENA_EXPLOSION_3_ID,
		SOUND_ARENA_FELINE_ENGAGE_ID,
		SOUND_ARENA_FELINE_ROAR_ID,
		SOUND_ARENA_FEMALE_SEDUCE_ID,
		SOUND_ARENA_FEMALE_GROAN1_ID,
		SOUND_ARENA_FEMALE_GROAN2_ID,
		SOUND_ARENA_FIRE_6_ID,
		SOUND_ARENA_GIANT_GRUNT2_ID,
		SOUND_ARENA_MALE_GRUNT2_ID,
		SOUND_ARENA_KUBWA_ROAR_ID,
		SOUND_ARENA_LIGHTNING_ATTACK_ID,
		SOUND_ARENA_MALE_ANGER_ID,
		SOUND_ARENA_MALE_LAUGH_ID,
		SOUND_ARENA_MALE_LAUGH2_ID,
		SOUND_ARENA_MALE_LOW_ANGER_ID,
		SOUND_ARENA_MALE_LOW_PAIN_ID,
		SOUND_ARENA_MALE_LOW_WARCRY_ID,
		SOUND_ARENA_MALE_PAIN_ID,
		SOUND_ARENA_MISC_IMPACT_ID,
		SOUND_ARENA_MISC_IMPACT2_ID,
		SOUND_ARENA_MONKEY_ATTACK_ID,
		SOUND_ARENA_MONSTER_ATTACK_ID,
		SOUND_ARENA_MONSTER_CHALLENGE_ID,
		SOUND_ARENA_MONSTER_IMPACT_ID,
		SOUND_ARENA_OGRE_ATTACK_ID,
		SOUND_ARENA_OGRE_ATTACK2_ID,
		SOUND_ARENA_OGRE_CHALLENGE_ID,
		SOUND_ARENA_OGRE_CHALLENGE2_ID,
		SOUND_ARENA_OGRE_IMPACT2_ID,
		SOUND_ARENA_OGRE_IMPACT3_ID,
		SOUND_ARENA_PLATE_ATTACK2_ID,
		SOUND_ARENA_PLATE_ATTACK3_ID,
		SOUND_ARENA_PLATE_ATTACK4_ID,
		SOUND_ARENA_PLATE_IMPACT4_ID,
		SOUND_ARENA_PLATE_IMPACT5_ID,
		SOUND_ARENA_PLATE_IMPACT6_ID,
		SOUND_ARENA_ROBOT_ATTACK_ID,
		SOUND_ARENA_ROBOT_CHALLENGE_ID,
		SOUND_ARENA_ROBOT_IMPACT_ID,
		SOUND_ARENA_SCIFI_LASER_ID,
		SOUND_ARENA_SCIFI_MECH_ID,
		SOUND_ARENA_SCIFI_MECH2_ID,
		SOUND_ARENA_SCIFI_TELEPORT_ID,
		SOUND_ARENA_SLICING_ATTACK_ID,
		SOUND_ARENA_SLICING_ATTACK2_ID,
		SOUND_ARENA_SMOKE_ATTACK_ID,
		SOUND_ARENA_SMOKE_ATTACK2_ID,
		SOUND_ARENA_SMOKE_IMPACT_ID,
		SOUND_ARENA_SONIC_ATTACK_ID,
		SOUND_ARENA_SPARKLE_ATTACK_ID,
		SOUND_ARENA_SQ_MAM_ATTACK_ID,
		SOUND_ARENA_SQ_MAM_DEATH_ID,
		SOUND_ARENA_STRING_ATTACK_ID,
		SOUND_ARENA_SWORD_IMPACT3_ID,
		SOUND_ARENA_WITCH_GROAN_ID,
		SOUND_ARENA_WITCH_LAUGH_ID,
		SOUND_ARENA_WITCH_LAUGH2_ID,
		SOUND_ARENA_WOLF_HOWL_ID,
		RESOURCE_ID_MAX
	};

	Image* GetImageById(int theId);
	Font* GetFontById(int theId);
	int GetSoundById(int theId);

	Image*& GetImageRefById(int theId);
	Font*& GetFontRefById(int theId);
	int& GetSoundRefById(int theId);

	ResourceId GetIdByImage(Image *theImage);
	ResourceId GetIdByFont(Font *theFont);
	ResourceId GetIdBySound(int theSound);
	const char* GetStringIdById(int theId);
	ResourceId GetIdByStringId(const char *theStringId);

} // namespace Sexy


#endif
