#include "TimedMode.h"
#include "SexyAppFramework/ResourceManager.h"

using namespace Sexy;

#pragma warning(disable:4311 4312)

static bool gNeedRecalcVariableToIdMap = false;

bool Sexy::ExtractResourcesByName(ResourceManager *theManager, const char *theName)
{
	if (strcmp(theName,"TimedModeCommon")==0) return ExtractTimedModeCommonResources(theManager);
	return false;
}

Sexy::ResourceId Sexy::GetIdByStringId(const char *theStringId)
{
	typedef std::map<std::string,int> MyMap;
	static MyMap aMap;
	if(aMap.empty())
	{
		for(int i=0; i<RESOURCE_ID_MAX; i++)
			aMap[GetStringIdById(i)] = i;
	}

	MyMap::iterator anItr = aMap.find(theStringId);
	if (anItr == aMap.end())
		return RESOURCE_ID_MAX;
	else
		return (ResourceId) anItr->second;
}

// TimedModeCommon Resources
Image* Sexy::IMAGE_TMA_BG;
Image* Sexy::IMAGE_TMA_CHECKPOINT;
Image* Sexy::IMAGE_TMA_COUNTDOWN;
Image* Sexy::IMAGE_TMA_ENEMY_ATTACKING;
Image* Sexy::IMAGE_TMA_TIMERBAR;
Image* Sexy::IMAGE_TMA_TIMERBAR_FILL;
int Sexy::SOUND_ARENA_ARROW_SHOT;
int Sexy::SOUND_ARENA_BEAR_ATTACK;
int Sexy::SOUND_ARENA_BEAR_IMPACT;
int Sexy::SOUND_ARENA_BEAR_ROAR;
int Sexy::SOUND_ARENA_BOVINE_ATTACK2;
int Sexy::SOUND_ARENA_DOG_BARK1;
int Sexy::SOUND_ARENA_DOG_BARK2;
int Sexy::SOUND_ARENA_DOG_WHIMPER;
int Sexy::SOUND_ARENA_DRAGON_BITE;
int Sexy::SOUND_ARENA_DRAGON_DEATH;
int Sexy::SOUND_ARENA_DRAGON_PAIN;
int Sexy::SOUND_ARENA_DRAGON_ROAR;
int Sexy::SOUND_ARENA_EXPLOSION_3;
int Sexy::SOUND_ARENA_FELINE_ENGAGE;
int Sexy::SOUND_ARENA_FELINE_ROAR;
int Sexy::SOUND_ARENA_FEMALE_GROAN1;
int Sexy::SOUND_ARENA_FEMALE_GROAN2;
int Sexy::SOUND_ARENA_FEMALE_SEDUCE;
int Sexy::SOUND_ARENA_FIRE_6;
int Sexy::SOUND_ARENA_GIANT_GRUNT2;
int Sexy::SOUND_ARENA_KUBWA_ROAR;
int Sexy::SOUND_ARENA_LIGHTNING_ATTACK;
int Sexy::SOUND_ARENA_MALE_ANGER;
int Sexy::SOUND_ARENA_MALE_GRUNT2;
int Sexy::SOUND_ARENA_MALE_LAUGH;
int Sexy::SOUND_ARENA_MALE_LAUGH2;
int Sexy::SOUND_ARENA_MALE_LOW_ANGER;
int Sexy::SOUND_ARENA_MALE_LOW_PAIN;
int Sexy::SOUND_ARENA_MALE_LOW_WARCRY;
int Sexy::SOUND_ARENA_MALE_PAIN;
int Sexy::SOUND_ARENA_MISC_IMPACT;
int Sexy::SOUND_ARENA_MISC_IMPACT2;
int Sexy::SOUND_ARENA_MONKEY_ATTACK;
int Sexy::SOUND_ARENA_MONSTER_ATTACK;
int Sexy::SOUND_ARENA_MONSTER_CHALLENGE;
int Sexy::SOUND_ARENA_MONSTER_IMPACT;
int Sexy::SOUND_ARENA_OGRE_ATTACK;
int Sexy::SOUND_ARENA_OGRE_ATTACK2;
int Sexy::SOUND_ARENA_OGRE_CHALLENGE;
int Sexy::SOUND_ARENA_OGRE_CHALLENGE2;
int Sexy::SOUND_ARENA_OGRE_IMPACT2;
int Sexy::SOUND_ARENA_OGRE_IMPACT3;
int Sexy::SOUND_ARENA_PLATE_ATTACK2;
int Sexy::SOUND_ARENA_PLATE_ATTACK3;
int Sexy::SOUND_ARENA_PLATE_ATTACK4;
int Sexy::SOUND_ARENA_PLATE_IMPACT4;
int Sexy::SOUND_ARENA_PLATE_IMPACT5;
int Sexy::SOUND_ARENA_PLATE_IMPACT6;
int Sexy::SOUND_ARENA_ROBOT_ATTACK;
int Sexy::SOUND_ARENA_ROBOT_CHALLENGE;
int Sexy::SOUND_ARENA_ROBOT_IMPACT;
int Sexy::SOUND_ARENA_SCIFI_LASER;
int Sexy::SOUND_ARENA_SCIFI_MECH;
int Sexy::SOUND_ARENA_SCIFI_MECH2;
int Sexy::SOUND_ARENA_SCIFI_TELEPORT;
int Sexy::SOUND_ARENA_SLICING_ATTACK;
int Sexy::SOUND_ARENA_SLICING_ATTACK2;
int Sexy::SOUND_ARENA_SMOKE_ATTACK;
int Sexy::SOUND_ARENA_SMOKE_ATTACK2;
int Sexy::SOUND_ARENA_SMOKE_IMPACT;
int Sexy::SOUND_ARENA_SONIC_ATTACK;
int Sexy::SOUND_ARENA_SPARKLE_ATTACK;
int Sexy::SOUND_ARENA_SQ_MAM_ATTACK;
int Sexy::SOUND_ARENA_SQ_MAM_DEATH;
int Sexy::SOUND_ARENA_STRING_ATTACK;
int Sexy::SOUND_ARENA_SWORD_IMPACT3;
int Sexy::SOUND_ARENA_WITCH_GROAN;
int Sexy::SOUND_ARENA_WITCH_LAUGH;
int Sexy::SOUND_ARENA_WITCH_LAUGH2;
int Sexy::SOUND_ARENA_WOLF_HOWL;

bool Sexy::ExtractTimedModeCommonResources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_TMA_BG = aMgr.GetImageThrow("IMAGE_TMA_BG");
		IMAGE_TMA_CHECKPOINT = aMgr.GetImageThrow("IMAGE_TMA_CHECKPOINT");
		IMAGE_TMA_COUNTDOWN = aMgr.GetImageThrow("IMAGE_TMA_COUNTDOWN");
		IMAGE_TMA_ENEMY_ATTACKING = aMgr.GetImageThrow("IMAGE_TMA_ENEMY_ATTACKING");
		IMAGE_TMA_TIMERBAR = aMgr.GetImageThrow("IMAGE_TMA_TIMERBAR");
		IMAGE_TMA_TIMERBAR_FILL = aMgr.GetImageThrow("IMAGE_TMA_TIMERBAR_FILL");
		SOUND_ARENA_ARROW_SHOT = aMgr.GetSoundThrow("SOUND_ARENA_ARROW_SHOT");
		SOUND_ARENA_BEAR_ATTACK = aMgr.GetSoundThrow("SOUND_ARENA_BEAR_ATTACK");
		SOUND_ARENA_BEAR_IMPACT = aMgr.GetSoundThrow("SOUND_ARENA_BEAR_IMPACT");
		SOUND_ARENA_BEAR_ROAR = aMgr.GetSoundThrow("SOUND_ARENA_BEAR_ROAR");
		SOUND_ARENA_BOVINE_ATTACK2 = aMgr.GetSoundThrow("SOUND_ARENA_BOVINE_ATTACK2");
		SOUND_ARENA_DOG_BARK1 = aMgr.GetSoundThrow("SOUND_ARENA_DOG_BARK1");
		SOUND_ARENA_DOG_BARK2 = aMgr.GetSoundThrow("SOUND_ARENA_DOG_BARK2");
		SOUND_ARENA_DOG_WHIMPER = aMgr.GetSoundThrow("SOUND_ARENA_DOG_WHIMPER");
		SOUND_ARENA_DRAGON_BITE = aMgr.GetSoundThrow("SOUND_ARENA_DRAGON_BITE");
		SOUND_ARENA_DRAGON_DEATH = aMgr.GetSoundThrow("SOUND_ARENA_DRAGON_DEATH");
		SOUND_ARENA_DRAGON_PAIN = aMgr.GetSoundThrow("SOUND_ARENA_DRAGON_PAIN");
		SOUND_ARENA_DRAGON_ROAR = aMgr.GetSoundThrow("SOUND_ARENA_DRAGON_ROAR");
		SOUND_ARENA_EXPLOSION_3 = aMgr.GetSoundThrow("SOUND_ARENA_EXPLOSION_3");
		SOUND_ARENA_FELINE_ENGAGE = aMgr.GetSoundThrow("SOUND_ARENA_FELINE_ENGAGE");
		SOUND_ARENA_FELINE_ROAR = aMgr.GetSoundThrow("SOUND_ARENA_FELINE_ROAR");
		SOUND_ARENA_FEMALE_GROAN1 = aMgr.GetSoundThrow("SOUND_ARENA_FEMALE_GROAN1");
		SOUND_ARENA_FEMALE_GROAN2 = aMgr.GetSoundThrow("SOUND_ARENA_FEMALE_GROAN2");
		SOUND_ARENA_FEMALE_SEDUCE = aMgr.GetSoundThrow("SOUND_ARENA_FEMALE_SEDUCE");
		SOUND_ARENA_FIRE_6 = aMgr.GetSoundThrow("SOUND_ARENA_FIRE_6");
		SOUND_ARENA_GIANT_GRUNT2 = aMgr.GetSoundThrow("SOUND_ARENA_GIANT_GRUNT2");
		SOUND_ARENA_KUBWA_ROAR = aMgr.GetSoundThrow("SOUND_ARENA_KUBWA_ROAR");
		SOUND_ARENA_LIGHTNING_ATTACK = aMgr.GetSoundThrow("SOUND_ARENA_LIGHTNING_ATTACK");
		SOUND_ARENA_MALE_ANGER = aMgr.GetSoundThrow("SOUND_ARENA_MALE_ANGER");
		SOUND_ARENA_MALE_GRUNT2 = aMgr.GetSoundThrow("SOUND_ARENA_MALE_GRUNT2");
		SOUND_ARENA_MALE_LAUGH = aMgr.GetSoundThrow("SOUND_ARENA_MALE_LAUGH");
		SOUND_ARENA_MALE_LAUGH2 = aMgr.GetSoundThrow("SOUND_ARENA_MALE_LAUGH2");
		SOUND_ARENA_MALE_LOW_ANGER = aMgr.GetSoundThrow("SOUND_ARENA_MALE_LOW_ANGER");
		SOUND_ARENA_MALE_LOW_PAIN = aMgr.GetSoundThrow("SOUND_ARENA_MALE_LOW_PAIN");
		SOUND_ARENA_MALE_LOW_WARCRY = aMgr.GetSoundThrow("SOUND_ARENA_MALE_LOW_WARCRY");
		SOUND_ARENA_MALE_PAIN = aMgr.GetSoundThrow("SOUND_ARENA_MALE_PAIN");
		SOUND_ARENA_MISC_IMPACT = aMgr.GetSoundThrow("SOUND_ARENA_MISC_IMPACT");
		SOUND_ARENA_MISC_IMPACT2 = aMgr.GetSoundThrow("SOUND_ARENA_MISC_IMPACT2");
		SOUND_ARENA_MONKEY_ATTACK = aMgr.GetSoundThrow("SOUND_ARENA_MONKEY_ATTACK");
		SOUND_ARENA_MONSTER_ATTACK = aMgr.GetSoundThrow("SOUND_ARENA_MONSTER_ATTACK");
		SOUND_ARENA_MONSTER_CHALLENGE = aMgr.GetSoundThrow("SOUND_ARENA_MONSTER_CHALLENGE");
		SOUND_ARENA_MONSTER_IMPACT = aMgr.GetSoundThrow("SOUND_ARENA_MONSTER_IMPACT");
		SOUND_ARENA_OGRE_ATTACK = aMgr.GetSoundThrow("SOUND_ARENA_OGRE_ATTACK");
		SOUND_ARENA_OGRE_ATTACK2 = aMgr.GetSoundThrow("SOUND_ARENA_OGRE_ATTACK2");
		SOUND_ARENA_OGRE_CHALLENGE = aMgr.GetSoundThrow("SOUND_ARENA_OGRE_CHALLENGE");
		SOUND_ARENA_OGRE_CHALLENGE2 = aMgr.GetSoundThrow("SOUND_ARENA_OGRE_CHALLENGE2");
		SOUND_ARENA_OGRE_IMPACT2 = aMgr.GetSoundThrow("SOUND_ARENA_OGRE_IMPACT2");
		SOUND_ARENA_OGRE_IMPACT3 = aMgr.GetSoundThrow("SOUND_ARENA_OGRE_IMPACT3");
		SOUND_ARENA_PLATE_ATTACK2 = aMgr.GetSoundThrow("SOUND_ARENA_PLATE_ATTACK2");
		SOUND_ARENA_PLATE_ATTACK3 = aMgr.GetSoundThrow("SOUND_ARENA_PLATE_ATTACK3");
		SOUND_ARENA_PLATE_ATTACK4 = aMgr.GetSoundThrow("SOUND_ARENA_PLATE_ATTACK4");
		SOUND_ARENA_PLATE_IMPACT4 = aMgr.GetSoundThrow("SOUND_ARENA_PLATE_IMPACT4");
		SOUND_ARENA_PLATE_IMPACT5 = aMgr.GetSoundThrow("SOUND_ARENA_PLATE_IMPACT5");
		SOUND_ARENA_PLATE_IMPACT6 = aMgr.GetSoundThrow("SOUND_ARENA_PLATE_IMPACT6");
		SOUND_ARENA_ROBOT_ATTACK = aMgr.GetSoundThrow("SOUND_ARENA_ROBOT_ATTACK");
		SOUND_ARENA_ROBOT_CHALLENGE = aMgr.GetSoundThrow("SOUND_ARENA_ROBOT_CHALLENGE");
		SOUND_ARENA_ROBOT_IMPACT = aMgr.GetSoundThrow("SOUND_ARENA_ROBOT_IMPACT");
		SOUND_ARENA_SCIFI_LASER = aMgr.GetSoundThrow("SOUND_ARENA_SCIFI_LASER");
		SOUND_ARENA_SCIFI_MECH = aMgr.GetSoundThrow("SOUND_ARENA_SCIFI_MECH");
		SOUND_ARENA_SCIFI_MECH2 = aMgr.GetSoundThrow("SOUND_ARENA_SCIFI_MECH2");
		SOUND_ARENA_SCIFI_TELEPORT = aMgr.GetSoundThrow("SOUND_ARENA_SCIFI_TELEPORT");
		SOUND_ARENA_SLICING_ATTACK = aMgr.GetSoundThrow("SOUND_ARENA_SLICING_ATTACK");
		SOUND_ARENA_SLICING_ATTACK2 = aMgr.GetSoundThrow("SOUND_ARENA_SLICING_ATTACK2");
		SOUND_ARENA_SMOKE_ATTACK = aMgr.GetSoundThrow("SOUND_ARENA_SMOKE_ATTACK");
		SOUND_ARENA_SMOKE_ATTACK2 = aMgr.GetSoundThrow("SOUND_ARENA_SMOKE_ATTACK2");
		SOUND_ARENA_SMOKE_IMPACT = aMgr.GetSoundThrow("SOUND_ARENA_SMOKE_IMPACT");
		SOUND_ARENA_SONIC_ATTACK = aMgr.GetSoundThrow("SOUND_ARENA_SONIC_ATTACK");
		SOUND_ARENA_SPARKLE_ATTACK = aMgr.GetSoundThrow("SOUND_ARENA_SPARKLE_ATTACK");
		SOUND_ARENA_SQ_MAM_ATTACK = aMgr.GetSoundThrow("SOUND_ARENA_SQ_MAM_ATTACK");
		SOUND_ARENA_SQ_MAM_DEATH = aMgr.GetSoundThrow("SOUND_ARENA_SQ_MAM_DEATH");
		SOUND_ARENA_STRING_ATTACK = aMgr.GetSoundThrow("SOUND_ARENA_STRING_ATTACK");
		SOUND_ARENA_SWORD_IMPACT3 = aMgr.GetSoundThrow("SOUND_ARENA_SWORD_IMPACT3");
		SOUND_ARENA_WITCH_GROAN = aMgr.GetSoundThrow("SOUND_ARENA_WITCH_GROAN");
		SOUND_ARENA_WITCH_LAUGH = aMgr.GetSoundThrow("SOUND_ARENA_WITCH_LAUGH");
		SOUND_ARENA_WITCH_LAUGH2 = aMgr.GetSoundThrow("SOUND_ARENA_WITCH_LAUGH2");
		SOUND_ARENA_WOLF_HOWL = aMgr.GetSoundThrow("SOUND_ARENA_WOLF_HOWL");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

static void* gResources[] =
{
	&IMAGE_TMA_BG,
	&IMAGE_TMA_ENEMY_ATTACKING,
	&IMAGE_TMA_TIMERBAR,
	&IMAGE_TMA_TIMERBAR_FILL,
	&IMAGE_TMA_CHECKPOINT,
	&IMAGE_TMA_COUNTDOWN,
	&SOUND_ARENA_ARROW_SHOT,
	&SOUND_ARENA_BEAR_ATTACK,
	&SOUND_ARENA_BEAR_IMPACT,
	&SOUND_ARENA_BEAR_ROAR,
	&SOUND_ARENA_BOVINE_ATTACK2,
	&SOUND_ARENA_DOG_BARK1,
	&SOUND_ARENA_DOG_BARK2,
	&SOUND_ARENA_DOG_WHIMPER,
	&SOUND_ARENA_DRAGON_BITE,
	&SOUND_ARENA_DRAGON_DEATH,
	&SOUND_ARENA_DRAGON_PAIN,
	&SOUND_ARENA_DRAGON_ROAR,
	&SOUND_ARENA_EXPLOSION_3,
	&SOUND_ARENA_FELINE_ENGAGE,
	&SOUND_ARENA_FELINE_ROAR,
	&SOUND_ARENA_FEMALE_SEDUCE,
	&SOUND_ARENA_FEMALE_GROAN1,
	&SOUND_ARENA_FEMALE_GROAN2,
	&SOUND_ARENA_FIRE_6,
	&SOUND_ARENA_GIANT_GRUNT2,
	&SOUND_ARENA_MALE_GRUNT2,
	&SOUND_ARENA_KUBWA_ROAR,
	&SOUND_ARENA_LIGHTNING_ATTACK,
	&SOUND_ARENA_MALE_ANGER,
	&SOUND_ARENA_MALE_LAUGH,
	&SOUND_ARENA_MALE_LAUGH2,
	&SOUND_ARENA_MALE_LOW_ANGER,
	&SOUND_ARENA_MALE_LOW_PAIN,
	&SOUND_ARENA_MALE_LOW_WARCRY,
	&SOUND_ARENA_MALE_PAIN,
	&SOUND_ARENA_MISC_IMPACT,
	&SOUND_ARENA_MISC_IMPACT2,
	&SOUND_ARENA_MONKEY_ATTACK,
	&SOUND_ARENA_MONSTER_ATTACK,
	&SOUND_ARENA_MONSTER_CHALLENGE,
	&SOUND_ARENA_MONSTER_IMPACT,
	&SOUND_ARENA_OGRE_ATTACK,
	&SOUND_ARENA_OGRE_ATTACK2,
	&SOUND_ARENA_OGRE_CHALLENGE,
	&SOUND_ARENA_OGRE_CHALLENGE2,
	&SOUND_ARENA_OGRE_IMPACT2,
	&SOUND_ARENA_OGRE_IMPACT3,
	&SOUND_ARENA_PLATE_ATTACK2,
	&SOUND_ARENA_PLATE_ATTACK3,
	&SOUND_ARENA_PLATE_ATTACK4,
	&SOUND_ARENA_PLATE_IMPACT4,
	&SOUND_ARENA_PLATE_IMPACT5,
	&SOUND_ARENA_PLATE_IMPACT6,
	&SOUND_ARENA_ROBOT_ATTACK,
	&SOUND_ARENA_ROBOT_CHALLENGE,
	&SOUND_ARENA_ROBOT_IMPACT,
	&SOUND_ARENA_SCIFI_LASER,
	&SOUND_ARENA_SCIFI_MECH,
	&SOUND_ARENA_SCIFI_MECH2,
	&SOUND_ARENA_SCIFI_TELEPORT,
	&SOUND_ARENA_SLICING_ATTACK,
	&SOUND_ARENA_SLICING_ATTACK2,
	&SOUND_ARENA_SMOKE_ATTACK,
	&SOUND_ARENA_SMOKE_ATTACK2,
	&SOUND_ARENA_SMOKE_IMPACT,
	&SOUND_ARENA_SONIC_ATTACK,
	&SOUND_ARENA_SPARKLE_ATTACK,
	&SOUND_ARENA_SQ_MAM_ATTACK,
	&SOUND_ARENA_SQ_MAM_DEATH,
	&SOUND_ARENA_STRING_ATTACK,
	&SOUND_ARENA_SWORD_IMPACT3,
	&SOUND_ARENA_WITCH_GROAN,
	&SOUND_ARENA_WITCH_LAUGH,
	&SOUND_ARENA_WITCH_LAUGH2,
	&SOUND_ARENA_WOLF_HOWL,
	NULL
};

Image* Sexy::LoadImageById(ResourceManager *theManager, int theId)
{
	return (*((Image**)gResources[theId]) = theManager->LoadImage(GetStringIdById(theId)));
}

void Sexy::ReplaceImageById(ResourceManager *theManager, int theId, Image *theImage)
{
	theManager->ReplaceImage(GetStringIdById(theId),theImage);
	*(Image**)gResources[theId] = theImage;
}

Image* Sexy::GetImageById(int theId)
{
	return *(Image**)gResources[theId];
}

Font* Sexy::GetFontById(int theId)
{
	return *(Font**)gResources[theId];
}

int Sexy::GetSoundById(int theId)
{
	return *(int*)gResources[theId];
}

Image*& Sexy::GetImageRefById(int theId)
{
	return *(Image**)gResources[theId];
}

Font*& Sexy::GetFontRefById(int theId)
{
	return *(Font**)gResources[theId];
}

int& Sexy::GetSoundRefById(int theId)
{
	return *(int*)gResources[theId];
}

static Sexy::ResourceId GetIdByVariable(const void *theVariable)
{
	typedef std::map<int,int> MyMap;
	static MyMap aMap;
	if(gNeedRecalcVariableToIdMap)
	{
		gNeedRecalcVariableToIdMap = false;
		aMap.clear();
		for(int i=0; i<RESOURCE_ID_MAX; i++)
			aMap[*(int*)gResources[i]] = i;
	}

	MyMap::iterator anItr = aMap.find((int)theVariable);
	if (anItr == aMap.end())
		return RESOURCE_ID_MAX;
	else
		return (ResourceId) anItr->second;
}

Sexy::ResourceId Sexy::GetIdByImage(Image *theImage)
{
	return GetIdByVariable(theImage);
}

Sexy::ResourceId Sexy::GetIdByFont(Font *theFont)
{
	return GetIdByVariable(theFont);
}

Sexy::ResourceId Sexy::GetIdBySound(int theSound)
{
	return GetIdByVariable((void*)theSound);
}

const char* Sexy::GetStringIdById(int theId)
{
	switch(theId)
	{
		case IMAGE_TMA_BG_ID: return "IMAGE_TMA_BG";
		case IMAGE_TMA_ENEMY_ATTACKING_ID: return "IMAGE_TMA_ENEMY_ATTACKING";
		case IMAGE_TMA_TIMERBAR_ID: return "IMAGE_TMA_TIMERBAR";
		case IMAGE_TMA_TIMERBAR_FILL_ID: return "IMAGE_TMA_TIMERBAR_FILL";
		case IMAGE_TMA_CHECKPOINT_ID: return "IMAGE_TMA_CHECKPOINT";
		case IMAGE_TMA_COUNTDOWN_ID: return "IMAGE_TMA_COUNTDOWN";
		case SOUND_ARENA_ARROW_SHOT_ID: return "SOUND_ARENA_ARROW_SHOT";
		case SOUND_ARENA_BEAR_ATTACK_ID: return "SOUND_ARENA_BEAR_ATTACK";
		case SOUND_ARENA_BEAR_IMPACT_ID: return "SOUND_ARENA_BEAR_IMPACT";
		case SOUND_ARENA_BEAR_ROAR_ID: return "SOUND_ARENA_BEAR_ROAR";
		case SOUND_ARENA_BOVINE_ATTACK2_ID: return "SOUND_ARENA_BOVINE_ATTACK2";
		case SOUND_ARENA_DOG_BARK1_ID: return "SOUND_ARENA_DOG_BARK1";
		case SOUND_ARENA_DOG_BARK2_ID: return "SOUND_ARENA_DOG_BARK2";
		case SOUND_ARENA_DOG_WHIMPER_ID: return "SOUND_ARENA_DOG_WHIMPER";
		case SOUND_ARENA_DRAGON_BITE_ID: return "SOUND_ARENA_DRAGON_BITE";
		case SOUND_ARENA_DRAGON_DEATH_ID: return "SOUND_ARENA_DRAGON_DEATH";
		case SOUND_ARENA_DRAGON_PAIN_ID: return "SOUND_ARENA_DRAGON_PAIN";
		case SOUND_ARENA_DRAGON_ROAR_ID: return "SOUND_ARENA_DRAGON_ROAR";
		case SOUND_ARENA_EXPLOSION_3_ID: return "SOUND_ARENA_EXPLOSION_3";
		case SOUND_ARENA_FELINE_ENGAGE_ID: return "SOUND_ARENA_FELINE_ENGAGE";
		case SOUND_ARENA_FELINE_ROAR_ID: return "SOUND_ARENA_FELINE_ROAR";
		case SOUND_ARENA_FEMALE_SEDUCE_ID: return "SOUND_ARENA_FEMALE_SEDUCE";
		case SOUND_ARENA_FEMALE_GROAN1_ID: return "SOUND_ARENA_FEMALE_GROAN1";
		case SOUND_ARENA_FEMALE_GROAN2_ID: return "SOUND_ARENA_FEMALE_GROAN2";
		case SOUND_ARENA_FIRE_6_ID: return "SOUND_ARENA_FIRE_6";
		case SOUND_ARENA_GIANT_GRUNT2_ID: return "SOUND_ARENA_GIANT_GRUNT2";
		case SOUND_ARENA_MALE_GRUNT2_ID: return "SOUND_ARENA_MALE_GRUNT2";
		case SOUND_ARENA_KUBWA_ROAR_ID: return "SOUND_ARENA_KUBWA_ROAR";
		case SOUND_ARENA_LIGHTNING_ATTACK_ID: return "SOUND_ARENA_LIGHTNING_ATTACK";
		case SOUND_ARENA_MALE_ANGER_ID: return "SOUND_ARENA_MALE_ANGER";
		case SOUND_ARENA_MALE_LAUGH_ID: return "SOUND_ARENA_MALE_LAUGH";
		case SOUND_ARENA_MALE_LAUGH2_ID: return "SOUND_ARENA_MALE_LAUGH2";
		case SOUND_ARENA_MALE_LOW_ANGER_ID: return "SOUND_ARENA_MALE_LOW_ANGER";
		case SOUND_ARENA_MALE_LOW_PAIN_ID: return "SOUND_ARENA_MALE_LOW_PAIN";
		case SOUND_ARENA_MALE_LOW_WARCRY_ID: return "SOUND_ARENA_MALE_LOW_WARCRY";
		case SOUND_ARENA_MALE_PAIN_ID: return "SOUND_ARENA_MALE_PAIN";
		case SOUND_ARENA_MISC_IMPACT_ID: return "SOUND_ARENA_MISC_IMPACT";
		case SOUND_ARENA_MISC_IMPACT2_ID: return "SOUND_ARENA_MISC_IMPACT2";
		case SOUND_ARENA_MONKEY_ATTACK_ID: return "SOUND_ARENA_MONKEY_ATTACK";
		case SOUND_ARENA_MONSTER_ATTACK_ID: return "SOUND_ARENA_MONSTER_ATTACK";
		case SOUND_ARENA_MONSTER_CHALLENGE_ID: return "SOUND_ARENA_MONSTER_CHALLENGE";
		case SOUND_ARENA_MONSTER_IMPACT_ID: return "SOUND_ARENA_MONSTER_IMPACT";
		case SOUND_ARENA_OGRE_ATTACK_ID: return "SOUND_ARENA_OGRE_ATTACK";
		case SOUND_ARENA_OGRE_ATTACK2_ID: return "SOUND_ARENA_OGRE_ATTACK2";
		case SOUND_ARENA_OGRE_CHALLENGE_ID: return "SOUND_ARENA_OGRE_CHALLENGE";
		case SOUND_ARENA_OGRE_CHALLENGE2_ID: return "SOUND_ARENA_OGRE_CHALLENGE2";
		case SOUND_ARENA_OGRE_IMPACT2_ID: return "SOUND_ARENA_OGRE_IMPACT2";
		case SOUND_ARENA_OGRE_IMPACT3_ID: return "SOUND_ARENA_OGRE_IMPACT3";
		case SOUND_ARENA_PLATE_ATTACK2_ID: return "SOUND_ARENA_PLATE_ATTACK2";
		case SOUND_ARENA_PLATE_ATTACK3_ID: return "SOUND_ARENA_PLATE_ATTACK3";
		case SOUND_ARENA_PLATE_ATTACK4_ID: return "SOUND_ARENA_PLATE_ATTACK4";
		case SOUND_ARENA_PLATE_IMPACT4_ID: return "SOUND_ARENA_PLATE_IMPACT4";
		case SOUND_ARENA_PLATE_IMPACT5_ID: return "SOUND_ARENA_PLATE_IMPACT5";
		case SOUND_ARENA_PLATE_IMPACT6_ID: return "SOUND_ARENA_PLATE_IMPACT6";
		case SOUND_ARENA_ROBOT_ATTACK_ID: return "SOUND_ARENA_ROBOT_ATTACK";
		case SOUND_ARENA_ROBOT_CHALLENGE_ID: return "SOUND_ARENA_ROBOT_CHALLENGE";
		case SOUND_ARENA_ROBOT_IMPACT_ID: return "SOUND_ARENA_ROBOT_IMPACT";
		case SOUND_ARENA_SCIFI_LASER_ID: return "SOUND_ARENA_SCIFI_LASER";
		case SOUND_ARENA_SCIFI_MECH_ID: return "SOUND_ARENA_SCIFI_MECH";
		case SOUND_ARENA_SCIFI_MECH2_ID: return "SOUND_ARENA_SCIFI_MECH2";
		case SOUND_ARENA_SCIFI_TELEPORT_ID: return "SOUND_ARENA_SCIFI_TELEPORT";
		case SOUND_ARENA_SLICING_ATTACK_ID: return "SOUND_ARENA_SLICING_ATTACK";
		case SOUND_ARENA_SLICING_ATTACK2_ID: return "SOUND_ARENA_SLICING_ATTACK2";
		case SOUND_ARENA_SMOKE_ATTACK_ID: return "SOUND_ARENA_SMOKE_ATTACK";
		case SOUND_ARENA_SMOKE_ATTACK2_ID: return "SOUND_ARENA_SMOKE_ATTACK2";
		case SOUND_ARENA_SMOKE_IMPACT_ID: return "SOUND_ARENA_SMOKE_IMPACT";
		case SOUND_ARENA_SONIC_ATTACK_ID: return "SOUND_ARENA_SONIC_ATTACK";
		case SOUND_ARENA_SPARKLE_ATTACK_ID: return "SOUND_ARENA_SPARKLE_ATTACK";
		case SOUND_ARENA_SQ_MAM_ATTACK_ID: return "SOUND_ARENA_SQ_MAM_ATTACK";
		case SOUND_ARENA_SQ_MAM_DEATH_ID: return "SOUND_ARENA_SQ_MAM_DEATH";
		case SOUND_ARENA_STRING_ATTACK_ID: return "SOUND_ARENA_STRING_ATTACK";
		case SOUND_ARENA_SWORD_IMPACT3_ID: return "SOUND_ARENA_SWORD_IMPACT3";
		case SOUND_ARENA_WITCH_GROAN_ID: return "SOUND_ARENA_WITCH_GROAN";
		case SOUND_ARENA_WITCH_LAUGH_ID: return "SOUND_ARENA_WITCH_LAUGH";
		case SOUND_ARENA_WITCH_LAUGH2_ID: return "SOUND_ARENA_WITCH_LAUGH2";
		case SOUND_ARENA_WOLF_HOWL_ID: return "SOUND_ARENA_WOLF_HOWL";
		default: return "";
	}
}

