#ifndef __Res_H__
#define __Res_H__

namespace Sexy
{
	class ResourceManager;
	class Image;
	class Font;

	Image* LoadImageById(ResourceManager *theManager, int theId);
	void ReplaceImageById(ResourceManager *theManager, int theId, Image *theImage);
	bool ExtractResourcesByName(ResourceManager *theManager, const char *theName);

	// Dialog Resources
	bool ExtractDialogResources(ResourceManager *theMgr);
	extern Image* IMAGE_DLG_BLUEFRAME;
	extern Image* IMAGE_DLG_BOTTOMBAR;
	extern Image* IMAGE_DLG_BROWNBUTTON1;
	extern Image* IMAGE_DLG_BROWNBUTTON2;
	extern Image* IMAGE_DLG_BUTTON1;
	extern Image* IMAGE_DLG_BUTTON3;
	extern Image* IMAGE_DLG_CONNECTOR;
	extern Image* IMAGE_DLG_DIALOGBOX;
	extern Image* IMAGE_DLG_MENU;
	extern Image* IMAGE_DLG_PLAYBUTTON1;
	extern Image* IMAGE_DLG_PLAYWIDGET1;
	extern Image* IMAGE_DLG_POPUP;
	extern Image* IMAGE_DLG_SEGMENT;
	extern Image* IMAGE_DLG_SELECTORFRAME;
	extern Image* IMAGE_DLG_SLIDER;
	extern Image* IMAGE_DLG_SLIDERHILIGHT;
	extern Image* IMAGE_DLG_SLIDERORB;
	extern Image* IMAGE_DLG_TEXTBOX;
	extern Image* IMAGE_DLG_TEXTRECT;

	// Game Resources
	bool ExtractGameResources(ResourceManager *theMgr);
	extern Image* IMAGE_ALPHABALL;
	extern Image* IMAGE_BALL;
	extern Image* IMAGE_BALLPEG;
	extern Image* IMAGE_BALLPEGCB;
	extern Image* IMAGE_BALLSHADOW;
	extern Image* IMAGE_BONUS100000;
	extern Image* IMAGE_BONUS100000LIGHT;
	extern Image* IMAGE_BONUS10000;
	extern Image* IMAGE_BONUS10000LIGHT;
	extern Image* IMAGE_BONUS50000;
	extern Image* IMAGE_BONUS50000LIGHT;
	extern Image* IMAGE_BONUSGLOW;
	extern Image* IMAGE_BONUSGLOW_BLUE;
	extern Image* IMAGE_BONUSGLOW_GREEN;
	extern Image* IMAGE_BONUSHALO;
	extern Image* IMAGE_BRICK;
	extern Image* IMAGE_BRICKCB;
	extern Image* IMAGE_BRICKGLOW;
	extern Image* IMAGE_CATCHERGLOW;
	extern Image* IMAGE_CIRCLE;
	extern Image* IMAGE_COINHEADS;
	extern Image* IMAGE_COINHILIGHT;
	extern Image* IMAGE_COINTAILS;
	extern Image* IMAGE_EMBER;
	extern Image* IMAGE_FEVERCAM;
	extern Image* IMAGE_FEVERGLOWSTAR;
	extern Image* IMAGE_FEVERRAY;
	extern Image* IMAGE_FEVERSCORE;
	extern Image* IMAGE_FEVERSCORETOP;
	extern Image* IMAGE_FEVERSPARK;
	extern Image* IMAGE_FEVERSTAR_BLUE;
	extern Image* IMAGE_FEVERSTAR_GREEN;
	extern Image* IMAGE_FEVERSTAR_RED;
	extern Image* IMAGE_FEVERTRAIL;
	extern Image* IMAGE_FLAMETRAIL;
	extern Image* IMAGE_FLECK;
	extern Image* IMAGE_GUIDEARROW;
	extern Image* IMAGE_GUIDEHIT;
	extern Image* IMAGE_GUIDEPOINT;
	extern Image* IMAGE_GUIDERECT2;
	extern Image* IMAGE_GUIDERECT;
	extern Image* IMAGE_PAUSED;
	extern Image* IMAGE_PEGGLOW;
	extern Image* IMAGE_PEGSHADOW;
	extern Image* IMAGE_POWERUPICON;
	extern Image* IMAGE_PULSE2_POWERUP;
	extern Image* IMAGE_PULSE2_SCORE;
	extern Image* IMAGE_PULSE_GOAL;
	extern Image* IMAGE_PULSE_NORMAL;
	extern Image* IMAGE_PULSE_POWERUP;
	extern Image* IMAGE_PULSE_SCORE;
	extern Image* IMAGE_PYRAMIDBALL;
	extern Image* IMAGE_PYRAMIDRAY;
	extern Image* IMAGE_SCOREICON;
	extern Image* IMAGE_SMOKE;
	extern Image* IMAGE_SPACESTAR;
	extern Image* IMAGE_STREAK;
	extern Image* IMAGE_TINYBLUERIBBON;
	extern Image* IMAGE_XFEVER;
	extern Image* IMAGE_XFEVERGLOW;

	// IP Resources
	bool ExtractIPResources(ResourceManager *theMgr);
	extern Image* IMAGE_IP_B;
	extern Image* IMAGE_IP_BALLOTRON;
	extern Image* IMAGE_IP_BLC;
	extern Image* IMAGE_IP_BRC;
	extern Image* IMAGE_IP_FEVERMETER;
	extern Image* IMAGE_IP_L1;
	extern Image* IMAGE_IP_L2;
	extern Image* IMAGE_IP_LWINDOW;
	extern Image* IMAGE_IP_ORBGLOW;
	extern Image* IMAGE_IP_POWERUPBANNER;
	extern Image* IMAGE_IP_R1;
	extern Image* IMAGE_IP_R2;
	extern Image* IMAGE_IP_RWINDOW;
	extern Image* IMAGE_IP_SHOOTER;
	extern Image* IMAGE_IP_SHOOTERBACK;
	extern Image* IMAGE_IP_SHOOTERORB;
	extern Image* IMAGE_IP_TL1;
	extern Image* IMAGE_IP_TL2;
	extern Image* IMAGE_IP_TLC;
	extern Image* IMAGE_IP_TR1;
	extern Image* IMAGE_IP_TR2;
	extern Image* IMAGE_IP_TRC;

	// Init Resources
	bool ExtractInitResources(ResourceManager *theMgr);
	extern Font* FONT_OVERLOAD16;
	extern Font* FONT_OVERLOAD16OUTLINE2;
	extern Font* FONT_OVERLOAD16OUTLINE;
	extern Image* IMAGE_MM_PLAY_BUTTON;

	// Interface Resources
	bool ExtractInterfaceResources(ResourceManager *theMgr);
	extern Image* IMAGE_INT_BACKSHADOW;
	extern Image* IMAGE_INT_BALL;
	extern Image* IMAGE_INT_BALLBACK;
	extern Image* IMAGE_INT_BALLGLASS;
	extern Image* IMAGE_INT_BALLOMASKBL;
	extern Image* IMAGE_INT_BALLOMASKBR;
	extern Image* IMAGE_INT_BALLOMASKTL;
	extern Image* IMAGE_INT_BALLOMASKTR;
	extern Image* IMAGE_INT_BUTTONCOVER;
	extern Image* IMAGE_INT_CANNON;
	extern Image* IMAGE_INT_CANNONCOVER;
	extern Image* IMAGE_INT_COUNTER;
	extern Image* IMAGE_INT_FBCENTERDISC;
	extern Image* IMAGE_INT_FBFREEBALL;
	extern Image* IMAGE_INT_FBGLOW;
	extern Image* IMAGE_INT_FBLIGHTUP;
	extern Image* IMAGE_INT_FBPOINTS;
	extern Image* IMAGE_INT_FEVERBARLITES;
	extern Image* IMAGE_INT_FEVERBARS;
	extern Image* IMAGE_INT_FEVERGLOW1;
	extern Image* IMAGE_INT_FEVERGLOW2;
	extern Image* IMAGE_INT_FEVERGLOW3;
	extern Image* IMAGE_INT_FEVERGLOW;
	extern Image* IMAGE_INT_FEVERMETER;
	extern Image* IMAGE_INT_FEVERMETERBOTTOM;
	extern Image* IMAGE_INT_FEVERMETERTOP;
	extern Image* IMAGE_INT_FEVERRAILING;
	extern Image* IMAGE_INT_FREEBALLMETER;
	extern Image* IMAGE_INT_FREEBALLMETERTOP;
	extern Image* IMAGE_INT_PLUNGER;
	extern Image* IMAGE_INT_SCOREHILIGHT;

	// LoadingThread Resources
	bool ExtractLoadingThreadResources(ResourceManager *theMgr);
	extern Font* FONT_BALLSLEFT;
	extern Font* FONT_BONK;
	extern Font* FONT_BUTTON;
	extern Font* FONT_OVERLOAD10;
	extern Font* FONT_OVERLOAD10OUTLINE;
	extern Font* FONT_OVERLOAD12;
	extern Font* FONT_OVERLOAD12OUTLINE;
	extern Font* FONT_OVERLOAD24;
	extern Font* FONT_OVERLOAD24GRAD1;
	extern Font* FONT_OVERLOAD24GRAD2;
	extern Font* FONT_OVERLOAD24OUTLINE;
	extern Font* FONT_OVERLOADMONO10;
	extern Font* FONT_OVERLOADMONO12;
	extern Font* FONT_PLAIN2;
	extern Font* FONT_PLAIN2BIG;
	extern Font* FONT_PLAIN2BIGOUTLINE;
	extern Font* FONT_PLAIN2OUTLINE;
	extern Font* FONT_PLAIN;
	extern Font* FONT_PLAINOUTLINE;
	extern Font* FONT_SCORE_DISP;
	extern Font* FONT_SMALL;
	extern Font* FONT_SMALLMONO;
	extern Font* FONT_SMALL_DISP;
	extern Font* FONT_STAGE;
	extern int SOUND_ADD_BALL;
	extern int SOUND_BUTTON1;
	extern int SOUND_CANNONCOCK;
	extern int SOUND_CANNONSHOT;
	extern int SOUND_COINSPIN;
	extern int SOUND_COINSPIN_NO;
	extern int SOUND_CYMBAL;
	extern int SOUND_DIALOG_MOVE;
	extern int SOUND_EXTRABALL;
	extern int SOUND_FEVERHIT;
	extern int SOUND_FIREWORKS2;
	extern int SOUND_LEVELDONE;
	extern int SOUND_ODETOJOY;
	extern int SOUND_PEGHIT2;
	extern int SOUND_PEGHIT3;
	extern int SOUND_PEGHIT;
	extern int SOUND_PEGPOP;
	extern int SOUND_POINTBOOST;
	extern int SOUND_POWERUP_GUIDE;
	extern int SOUND_RICHOCHET;
	extern int SOUND_SCORECOUNTER;
	extern int SOUND_SIGH;
	extern int SOUND_SKILLSHOT;
	extern int SOUND_SLOWMO;
	extern int SOUND_TEXT_WOOSH;
	extern int SOUND_WHISTLE;
	extern int SOUND_WOOSH;

	// MainMenu Resources
	bool ExtractMainMenuResources(ResourceManager *theMgr);
	extern Image* IMAGE_MM_BJORN_BUT;
	extern Image* IMAGE_MM_CHALLENGE_GREY;
	extern Image* IMAGE_MM_CHOOSE_MODE;
	extern Image* IMAGE_MM_INSTRUCTIONS;
	extern Image* IMAGE_MM_KATTUT_GREY;

	// SecondPlay Resources
	bool ExtractSecondPlayResources(ResourceManager *theMgr);
	extern Image* IMAGE_LS_CHALLENGEBADGE;
	extern Image* IMAGE_LS_LEVELSCREEN;
	extern Image* IMAGE_LS_LEVELSELECTOR;
	extern Image* IMAGE_LS_RANDOMLEVEL;
	extern Image* IMAGE_MM_CHALLENGE_MODE;
	extern Image* IMAGE_MM_KATTUT_BUT;
	extern int SOUND_POWERUP_PYRAMID;

	// Upsell Resources
	bool ExtractUpsellResources(ResourceManager *theMgr);
	extern Image* IMAGE_US_BOXART;
	extern Image* IMAGE_US_CHALLENGES;
	extern Image* IMAGE_US_CHALLENGES_TEXT;
	extern Image* IMAGE_US_GETDELUXE_TEXT;
	extern Image* IMAGE_US_LEVELS;
	extern Image* IMAGE_US_LEVELS_TEXT;
	extern Image* IMAGE_US_PLAYBUTTON1;
	extern Image* IMAGE_US_PLAYWIDGET1;
	extern Image* IMAGE_US_POWERS;
	extern Image* IMAGE_US_POWERS_TEXT;
	extern Image* IMAGE_US_UPSELLBOX;

	enum ResourceId
	{
		FONT_OVERLOAD16_ID,
		FONT_START1_ID = FONT_OVERLOAD16_ID,
		FONT_OVERLOAD16OUTLINE_ID,
		FONT_OVERLOAD16OUTLINE2_ID,
		FONT_END1_ID = FONT_OVERLOAD16OUTLINE2_ID,
		IMAGE_MM_PLAY_BUTTON_ID,
		FONT_PLAIN_ID,
		FONT_START2_ID = FONT_PLAIN_ID,
		FONT_PLAIN2BIG_ID,
		FONT_SMALL_ID,
		FONT_SMALLMONO_ID,
		FONT_SCORE_DISP_ID,
		FONT_SMALL_DISP_ID,
		FONT_BALLSLEFT_ID,
		FONT_BUTTON_ID,
		FONT_STAGE_ID,
		FONT_BONK_ID,
		FONT_OVERLOAD10_ID,
		FONT_OVERLOAD12_ID,
		FONT_OVERLOAD24_ID,
		FONT_OVERLOADMONO10_ID,
		FONT_OVERLOADMONO12_ID,
		FONT_OVERLOAD10OUTLINE_ID,
		FONT_OVERLOAD12OUTLINE_ID,
		FONT_OVERLOAD24OUTLINE_ID,
		FONT_OVERLOAD24GRAD1_ID,
		FONT_OVERLOAD24GRAD2_ID,
		FONT_PLAINOUTLINE_ID,
		FONT_PLAIN2_ID,
		FONT_PLAIN2OUTLINE_ID,
		FONT_PLAIN2BIGOUTLINE_ID,
		FONT_END2_ID = FONT_PLAIN2BIGOUTLINE_ID,
		SOUND_PEGHIT_ID,
		SOUND_START_ID = SOUND_PEGHIT_ID,
		SOUND_PEGHIT2_ID,
		SOUND_PEGHIT3_ID,
		SOUND_EXTRABALL_ID,
		SOUND_COINSPIN_ID,
		SOUND_COINSPIN_NO_ID,
		SOUND_LEVELDONE_ID,
		SOUND_PEGPOP_ID,
		SOUND_BUTTON1_ID,
		SOUND_POINTBOOST_ID,
		SOUND_SKILLSHOT_ID,
		SOUND_CANNONCOCK_ID,
		SOUND_CANNONSHOT_ID,
		SOUND_SCORECOUNTER_ID,
		SOUND_FIREWORKS2_ID,
		SOUND_RICHOCHET_ID,
		SOUND_CYMBAL_ID,
		SOUND_SIGH_ID,
		SOUND_WOOSH_ID,
		SOUND_TEXT_WOOSH_ID,
		SOUND_WHISTLE_ID,
		SOUND_FEVERHIT_ID,
		SOUND_POWERUP_GUIDE_ID,
		SOUND_SLOWMO_ID,
		SOUND_END_ID = SOUND_SLOWMO_ID,
		SOUND_ADD_BALL_ID,
		SOUND_DIALOG_MOVE_ID,
		SOUND_ODETOJOY_ID,
		IMAGE_INT_BALL_ID,
		IMAGE_INT_BALLBACK_ID,
		IMAGE_INT_BUTTONCOVER_ID,
		IMAGE_INT_CANNON_ID,
		IMAGE_INT_CANNONCOVER_ID,
		IMAGE_INT_PLUNGER_ID,
		IMAGE_INT_BALLGLASS_ID,
		IMAGE_INT_FEVERMETER_ID,
		IMAGE_INT_FEVERMETERTOP_ID,
		IMAGE_INT_FEVERMETERBOTTOM_ID,
		IMAGE_INT_FEVERRAILING_ID,
		IMAGE_INT_FEVERBARS_ID,
		IMAGE_INT_FEVERBARLITES_ID,
		IMAGE_INT_COUNTER_ID,
		IMAGE_INT_FREEBALLMETER_ID,
		IMAGE_INT_FREEBALLMETERTOP_ID,
		IMAGE_INT_BACKSHADOW_ID,
		IMAGE_INT_FEVERGLOW_ID,
		IMAGE_INT_FEVERGLOW1_ID,
		IMAGE_INT_FEVERGLOW2_ID,
		IMAGE_INT_FEVERGLOW3_ID,
		IMAGE_INT_SCOREHILIGHT_ID,
		IMAGE_INT_BALLOMASKBL_ID,
		IMAGE_INT_BALLOMASKBR_ID,
		IMAGE_INT_BALLOMASKTL_ID,
		IMAGE_INT_BALLOMASKTR_ID,
		IMAGE_INT_FBCENTERDISC_ID,
		IMAGE_INT_FBGLOW_ID,
		IMAGE_INT_FBFREEBALL_ID,
		IMAGE_INT_FBLIGHTUP_ID,
		IMAGE_INT_FBPOINTS_ID,
		IMAGE_IP_B_ID,
		IMAGE_IP_BLC_ID,
		IMAGE_IP_BRC_ID,
		IMAGE_IP_L1_ID,
		IMAGE_IP_L2_ID,
		IMAGE_IP_R1_ID,
		IMAGE_IP_R2_ID,
		IMAGE_IP_TL1_ID,
		IMAGE_IP_TL2_ID,
		IMAGE_IP_TR1_ID,
		IMAGE_IP_TR2_ID,
		IMAGE_IP_TLC_ID,
		IMAGE_IP_TRC_ID,
		IMAGE_IP_SHOOTERBACK_ID,
		IMAGE_IP_SHOOTER_ID,
		IMAGE_IP_BALLOTRON_ID,
		IMAGE_IP_FEVERMETER_ID,
		IMAGE_IP_LWINDOW_ID,
		IMAGE_IP_RWINDOW_ID,
		IMAGE_IP_SHOOTERORB_ID,
		IMAGE_IP_POWERUPBANNER_ID,
		IMAGE_IP_ORBGLOW_ID,
		IMAGE_MM_INSTRUCTIONS_ID,
		IMAGE_MM_CHOOSE_MODE_ID,
		IMAGE_MM_BJORN_BUT_ID,
		IMAGE_MM_KATTUT_GREY_ID,
		IMAGE_MM_CHALLENGE_GREY_ID,
		IMAGE_LS_LEVELSCREEN_ID,
		IMAGE_LS_LEVELSELECTOR_ID,
		IMAGE_LS_CHALLENGEBADGE_ID,
		IMAGE_LS_RANDOMLEVEL_ID,
		IMAGE_MM_CHALLENGE_MODE_ID,
		IMAGE_MM_KATTUT_BUT_ID,
		SOUND_POWERUP_PYRAMID_ID,
		IMAGE_US_POWERS_ID,
		IMAGE_US_POWERS_TEXT_ID,
		IMAGE_US_LEVELS_ID,
		IMAGE_US_LEVELS_TEXT_ID,
		IMAGE_US_CHALLENGES_ID,
		IMAGE_US_CHALLENGES_TEXT_ID,
		IMAGE_US_BOXART_ID,
		IMAGE_US_GETDELUXE_TEXT_ID,
		IMAGE_US_PLAYBUTTON1_ID,
		IMAGE_US_PLAYWIDGET1_ID,
		IMAGE_US_UPSELLBOX_ID,
		IMAGE_STREAK_ID,
		IMAGE_POWERUPICON_ID,
		IMAGE_SCOREICON_ID,
		IMAGE_BONUSHALO_ID,
		IMAGE_BONUSGLOW_ID,
		IMAGE_BONUSGLOW_GREEN_ID,
		IMAGE_BONUSGLOW_BLUE_ID,
		IMAGE_BONUS10000_ID,
		IMAGE_BONUS50000_ID,
		IMAGE_BONUS100000_ID,
		IMAGE_BONUS10000LIGHT_ID,
		IMAGE_BONUS50000LIGHT_ID,
		IMAGE_BONUS100000LIGHT_ID,
		IMAGE_BALL_ID,
		IMAGE_GUIDERECT_ID,
		IMAGE_GUIDERECT2_ID,
		IMAGE_ALPHABALL_ID,
		IMAGE_GUIDEARROW_ID,
		IMAGE_GUIDEPOINT_ID,
		IMAGE_GUIDEHIT_ID,
		IMAGE_BRICK_ID,
		IMAGE_BRICKCB_ID,
		IMAGE_BALLPEG_ID,
		IMAGE_BALLPEGCB_ID,
		IMAGE_BALLSHADOW_ID,
		IMAGE_PEGSHADOW_ID,
		IMAGE_CIRCLE_ID,
		IMAGE_COINHEADS_ID,
		IMAGE_COINTAILS_ID,
		IMAGE_COINHILIGHT_ID,
		IMAGE_BRICKGLOW_ID,
		IMAGE_PEGGLOW_ID,
		IMAGE_PYRAMIDRAY_ID,
		IMAGE_FEVERRAY_ID,
		IMAGE_FEVERGLOWSTAR_ID,
		IMAGE_FEVERSTAR_RED_ID,
		IMAGE_FEVERSTAR_GREEN_ID,
		IMAGE_FEVERSTAR_BLUE_ID,
		IMAGE_FEVERSPARK_ID,
		IMAGE_FEVERTRAIL_ID,
		IMAGE_FEVERSCORE_ID,
		IMAGE_FEVERSCORETOP_ID,
		IMAGE_TINYBLUERIBBON_ID,
		IMAGE_PAUSED_ID,
		IMAGE_CATCHERGLOW_ID,
		IMAGE_PYRAMIDBALL_ID,
		IMAGE_FEVERCAM_ID,
		IMAGE_XFEVER_ID,
		IMAGE_XFEVERGLOW_ID,
		IMAGE_PULSE_NORMAL_ID,
		IMAGE_PULSE_GOAL_ID,
		IMAGE_PULSE_SCORE_ID,
		IMAGE_PULSE_POWERUP_ID,
		IMAGE_PULSE2_SCORE_ID,
		IMAGE_PULSE2_POWERUP_ID,
		IMAGE_SPACESTAR_ID,
		IMAGE_EMBER_ID,
		IMAGE_SMOKE_ID,
		IMAGE_FLECK_ID,
		IMAGE_FLAMETRAIL_ID,
		IMAGE_DLG_BOTTOMBAR_ID,
		IMAGE_DLG_BLUEFRAME_ID,
		IMAGE_DLG_SELECTORFRAME_ID,
		IMAGE_DLG_BUTTON1_ID,
		IMAGE_DLG_BUTTON3_ID,
		IMAGE_DLG_BROWNBUTTON1_ID,
		IMAGE_DLG_BROWNBUTTON2_ID,
		IMAGE_DLG_POPUP_ID,
		IMAGE_DLG_TEXTBOX_ID,
		IMAGE_DLG_DIALOGBOX_ID,
		IMAGE_DLG_SLIDER_ID,
		IMAGE_DLG_SLIDERHILIGHT_ID,
		IMAGE_DLG_SLIDERORB_ID,
		IMAGE_DLG_SEGMENT_ID,
		IMAGE_DLG_CONNECTOR_ID,
		IMAGE_DLG_PLAYWIDGET1_ID,
		IMAGE_DLG_PLAYBUTTON1_ID,
		IMAGE_DLG_TEXTRECT_ID,
		IMAGE_DLG_MENU_ID,
		RESOURCE_ID_MAX
	};

	Image* GetImageById(int theId);
	Font* GetFontById(int theId);
	int GetSoundById(int theId);

	Image*& GetImageRefById(int theId);
	Font*& GetFontRefById(int theId);
	int& GetSoundRefById(int theId);

	ResourceId GetIdByImage(Image *theImage);
	ResourceId GetIdByFont(Font *theFont);
	ResourceId GetIdBySound(int theSound);
	const char* GetStringIdById(int theId);
	ResourceId GetIdByStringId(const char *theStringId);

} // namespace Sexy


#endif
