#include "Resources.h"
#include "SexyAppFramework/ResourceManager.h"

using namespace Sexy;

#pragma warning(disable:4311 4312)

static bool gNeedRecalcVariableToIdMap = false;

bool Sexy::ExtractResourcesByName(ResourceManager *theManager, const char *theName)
{
	if (strcmp(theName,"3dImages")==0) return Extract3dImagesResources(theManager);
	if (strcmp(theName,"Init")==0) return ExtractInitResources(theManager);
	if (strcmp(theName,"InitialMainMenu")==0) return ExtractInitialMainMenuResources(theManager);
	if (strcmp(theName,"LoadScreen")==0) return ExtractLoadScreenResources(theManager);
	if (strcmp(theName,"LoadingThread")==0) return ExtractLoadingThreadResources(theManager);
	if (strcmp(theName,"NonResize")==0) return ExtractNonResizeResources(theManager);
	if (strcmp(theName,"Sounds")==0) return ExtractSoundsResources(theManager);
	return false;
}

Sexy::ResourceId Sexy::GetIdByStringId(const char *theStringId)
{
	typedef std::map<std::string,int> MyMap;
	static MyMap aMap;
	if(aMap.empty())
	{
		for(int i=0; i<RESOURCE_ID_MAX; i++)
			aMap[GetStringIdById(i)] = i;
	}

	MyMap::iterator anItr = aMap.find(theStringId);
	if (anItr == aMap.end())
		return RESOURCE_ID_MAX;
	else
		return (ResourceId) anItr->second;
}

// 3dImages Resources
Image* Sexy::IMAGE_BLACK_HOLE;
Image* Sexy::IMAGE_BLACK_HOLE_COVER;
Image* Sexy::IMAGE_FIRE_RING;
Image* Sexy::IMAGE_HYPERSPACE;
Image* Sexy::IMAGE_HYPERSPACE_INITIAL;
Image* Sexy::IMAGE_TUNNEL_END;
Image* Sexy::IMAGE_WARP_LINES;

bool Sexy::Extract3dImagesResources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_BLACK_HOLE = aMgr.GetImageThrow("IMAGE_BLACK_HOLE");
		IMAGE_BLACK_HOLE_COVER = aMgr.GetImageThrow("IMAGE_BLACK_HOLE_COVER");
		IMAGE_FIRE_RING = aMgr.GetImageThrow("IMAGE_FIRE_RING");
		IMAGE_HYPERSPACE = aMgr.GetImageThrow("IMAGE_HYPERSPACE");
		IMAGE_HYPERSPACE_INITIAL = aMgr.GetImageThrow("IMAGE_HYPERSPACE_INITIAL");
		IMAGE_TUNNEL_END = aMgr.GetImageThrow("IMAGE_TUNNEL_END");
		IMAGE_WARP_LINES = aMgr.GetImageThrow("IMAGE_WARP_LINES");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// Init Resources
Font* Sexy::FONT_1;
Font* Sexy::FONT_2;
Font* Sexy::FONT_CONTINUUM_MED_14;
Font* Sexy::FONT_CONTINUUM_MED_14_GLOW;
Font* Sexy::FONT_CONT_MED;
Font* Sexy::FONT_CONT_SM;

bool Sexy::ExtractInitResources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		FONT_1 = aMgr.GetFontThrow("FONT_1");
		FONT_2 = aMgr.GetFontThrow("FONT_2");
		FONT_CONTINUUM_MED_14 = aMgr.GetFontThrow("FONT_CONTINUUM_MED_14");
		FONT_CONTINUUM_MED_14_GLOW = aMgr.GetFontThrow("FONT_CONTINUUM_MED_14_GLOW");
		FONT_CONT_MED = aMgr.GetFontThrow("FONT_CONT_MED");
		FONT_CONT_SM = aMgr.GetFontThrow("FONT_CONT_SM");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// InitialMainMenu Resources
Image* Sexy::IMAGE_MAIN_BKG;
Image* Sexy::IMAGE_MAIN_COMET;
Image* Sexy::IMAGE_MAIN_FG;
Image* Sexy::IMAGE_MAIN_FOG_BANK;
Image* Sexy::IMAGE_MAIN_FOG_BANK_FG;
Image* Sexy::IMAGE_MAIN_PLANET_1;
Image* Sexy::IMAGE_MAIN_STARFIELD;
Image* Sexy::IMAGE_MAIN_STAR_SPARKLE;

bool Sexy::ExtractInitialMainMenuResources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_MAIN_BKG = aMgr.GetImageThrow("IMAGE_MAIN_BKG");
		IMAGE_MAIN_COMET = aMgr.GetImageThrow("IMAGE_MAIN_COMET");
		IMAGE_MAIN_FG = aMgr.GetImageThrow("IMAGE_MAIN_FG");
		IMAGE_MAIN_FOG_BANK = aMgr.GetImageThrow("IMAGE_MAIN_FOG_BANK");
		IMAGE_MAIN_FOG_BANK_FG = aMgr.GetImageThrow("IMAGE_MAIN_FOG_BANK_FG");
		IMAGE_MAIN_PLANET_1 = aMgr.GetImageThrow("IMAGE_MAIN_PLANET_1");
		IMAGE_MAIN_STARFIELD = aMgr.GetImageThrow("IMAGE_MAIN_STARFIELD");
		IMAGE_MAIN_STAR_SPARKLE = aMgr.GetImageThrow("IMAGE_MAIN_STAR_SPARKLE");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// LoadScreen Resources
Image* Sexy::IMAGE_LOADER_BAR;
Image* Sexy::IMAGE_LOADER_BAR_FLASH;
Image* Sexy::IMAGE_LOADER_BAR_LIT_BLUE;
Image* Sexy::IMAGE_LOADER_BAR_LIT_PURPLE;
Image* Sexy::IMAGE_LOADER_BAR_TEXT;
Image* Sexy::IMAGE_LOGO;
Image* Sexy::IMAGE_LOGO_2;
Image* Sexy::IMAGE_LOGO_DELUXE;
Image* Sexy::IMAGE_LOGO_POPCAP;

bool Sexy::ExtractLoadScreenResources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_LOADER_BAR = aMgr.GetImageThrow("IMAGE_LOADER_BAR");
		IMAGE_LOADER_BAR_FLASH = aMgr.GetImageThrow("IMAGE_LOADER_BAR_FLASH");
		IMAGE_LOADER_BAR_LIT_BLUE = aMgr.GetImageThrow("IMAGE_LOADER_BAR_LIT_BLUE");
		IMAGE_LOADER_BAR_LIT_PURPLE = aMgr.GetImageThrow("IMAGE_LOADER_BAR_LIT_PURPLE");
		IMAGE_LOADER_BAR_TEXT = aMgr.GetImageThrow("IMAGE_LOADER_BAR_TEXT");
		IMAGE_LOGO = aMgr.GetImageThrow("IMAGE_LOGO");
		IMAGE_LOGO_2 = aMgr.GetImageThrow("IMAGE_LOGO_2");
		IMAGE_LOGO_DELUXE = aMgr.GetImageThrow("IMAGE_LOGO_DELUXE");
		IMAGE_LOGO_POPCAP = aMgr.GetImageThrow("IMAGE_LOGO_POPCAP");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// LoadingThread Resources
Font* Sexy::FONT_BOMB;
Font* Sexy::FONT_CONTINUUM_BOLD_11_NUM;
Font* Sexy::FONT_CONTINUUM_BOLD_11_NUM_GLOW;
Font* Sexy::FONT_CONTINUUM_BOLD_14_NUM;
Font* Sexy::FONT_CONTINUUM_BOLD_14_NUM_GLOW;
Font* Sexy::FONT_CONTINUUM_MED_18;
Font* Sexy::FONT_CONTINUUM_MED_18_GLOW;
Font* Sexy::FONT_CONTINUUM_MED_33;
Font* Sexy::FONT_CONTINUUM_MED_33_GLOW;
Font* Sexy::FONT_DEBUG;
Font* Sexy::FONT_DIGIT;
Font* Sexy::FONT_HUGE;
Font* Sexy::FONT_SCORE;
Font* Sexy::FONT_VAG_ROUNDED_11;
Image* Sexy::IMAGE_ARROW_UP;
Image* Sexy::IMAGE_BAR_LEFT;
Image* Sexy::IMAGE_BAR_MID;
Image* Sexy::IMAGE_BAR_RIGHT;
Image* Sexy::IMAGE_BIGSTAR;
Image* Sexy::IMAGE_BOARD_BORDER;
Image* Sexy::IMAGE_BOARD_RED_LIGHT;
Image* Sexy::IMAGE_BOMB;
Image* Sexy::IMAGE_BUTTON_HILITE;
Image* Sexy::IMAGE_CHECKBOX;
Image* Sexy::IMAGE_CONTROLS_CLASSIC;
Image* Sexy::IMAGE_CONTROLS_PUZZLE;
Image* Sexy::IMAGE_CONTROLS_SCORE;
Image* Sexy::IMAGE_DIALOG;
Image* Sexy::IMAGE_DIALOG_BUTTON;
Image* Sexy::IMAGE_DIALOG_BUTTON_GLOW;
Image* Sexy::IMAGE_DIALOG_HEADER;
Image* Sexy::IMAGE_EDIT_BOX;
Image* Sexy::IMAGE_ENDLESS_CENTER_1;
Image* Sexy::IMAGE_ENDLESS_CENTER_2;
Image* Sexy::IMAGE_ENDLESS_CENTER_3;
Image* Sexy::IMAGE_ENDLESS_CENTER_4;
Image* Sexy::IMAGE_ENDLESS_CENTER_5;
Image* Sexy::IMAGE_ENDLESS_CENTER_6;
Image* Sexy::IMAGE_ENDLESS_CENTER_7;
Image* Sexy::IMAGE_ENDLESS_GEM_HILITE;
Image* Sexy::IMAGE_ENDLESS_OUTER_1;
Image* Sexy::IMAGE_ENDLESS_OUTER_2;
Image* Sexy::IMAGE_ENDLESS_OUTER_3;
Image* Sexy::IMAGE_ENDLESS_OUTER_4;
Image* Sexy::IMAGE_ENDLESS_OUTER_5;
Image* Sexy::IMAGE_ENDLESS_OUTER_6;
Image* Sexy::IMAGE_ENDLESS_OUTER_7;
Image* Sexy::IMAGE_ENDLESS_SPARK_1;
Image* Sexy::IMAGE_ENDLESS_SPARK_2;
Image* Sexy::IMAGE_ENDLESS_SPARK_3;
Image* Sexy::IMAGE_ENDLESS_WIDGET;
Image* Sexy::IMAGE_EXPLOSION;
Image* Sexy::IMAGE_GALAXY_BUTTON_HILITE;
Image* Sexy::IMAGE_GALAXY_CLOSE_BUTTON;
Image* Sexy::IMAGE_GALAXY_HEADER;
Image* Sexy::IMAGE_GALAXY_MAP;
Image* Sexy::IMAGE_GALAXY_MOON_ALPHA;
Image* Sexy::IMAGE_GALAXY_MOON_SELECT;
Image* Sexy::IMAGE_GALAXY_PLANET_ALPHA;
Image* Sexy::IMAGE_GALAXY_PLANET_COMPLETED;
Image* Sexy::IMAGE_GALAXY_PLANET_SELECT;
Image* Sexy::IMAGE_GALAXY_QUESTION;
Image* Sexy::IMAGE_GALAXY_SUN_GLOW;
Image* Sexy::IMAGE_GALAXY_SUN_MOON_ALPHA;
Image* Sexy::IMAGE_GALAXY_SUN_SWIRL;
Image* Sexy::IMAGE_GALAXY_WARP_BUTTON;
Image* Sexy::IMAGE_GEM0;
Image* Sexy::IMAGE_GEM1;
Image* Sexy::IMAGE_GEM2;
Image* Sexy::IMAGE_GEM3;
Image* Sexy::IMAGE_GEM4;
Image* Sexy::IMAGE_GEM5;
Image* Sexy::IMAGE_GEM6;
Image* Sexy::IMAGE_GEM_ADD;
Image* Sexy::IMAGE_GEM_LIGHTING;
Image* Sexy::IMAGE_HELP_ARROW;
Image* Sexy::IMAGE_HELP_GRID_4;
Image* Sexy::IMAGE_HELP_GRID_5;
Image* Sexy::IMAGE_HELP_INDICATOR;
Image* Sexy::IMAGE_HELP_INDICATOR_ARROW;
Image* Sexy::IMAGE_HS_BACK_TO_GAME_TEXT;
Image* Sexy::IMAGE_HS_BACK_TO_MENU_TEXT;
Image* Sexy::IMAGE_HS_BOTTOM;
Image* Sexy::IMAGE_HS_BUTTON_ROLLOVER;
Image* Sexy::IMAGE_HS_LEFT;
Image* Sexy::IMAGE_HS_PLAY_AGAIN_TEXT;
Image* Sexy::IMAGE_HS_RESET_SCORES_TEXT;
Image* Sexy::IMAGE_HS_RIGHT;
Image* Sexy::IMAGE_HS_TITLE;
Image* Sexy::IMAGE_HS_TOP_BUTTON;
Image* Sexy::IMAGE_LIGHTNING;
Image* Sexy::IMAGE_LIGHTNING_CENTER;
Image* Sexy::IMAGE_MAIN_ACTION;
Image* Sexy::IMAGE_MAIN_BIG_OVER;
Image* Sexy::IMAGE_MAIN_BIG_SELECT;
Image* Sexy::IMAGE_MAIN_BOTTOM_GLOW;
Image* Sexy::IMAGE_MAIN_CENTER_GLOW;
Image* Sexy::IMAGE_MAIN_CENTER_TEXT;
Image* Sexy::IMAGE_MAIN_CLASSIC;
Image* Sexy::IMAGE_MAIN_COGNITO;
Image* Sexy::IMAGE_MAIN_ENDLESS;
Image* Sexy::IMAGE_MAIN_FINITY;
Image* Sexy::IMAGE_MAIN_GADGETS;
Image* Sexy::IMAGE_MAIN_HYPER;
Image* Sexy::IMAGE_MAIN_LIGHT_BIG;
Image* Sexy::IMAGE_MAIN_LIGHT_MED;
Image* Sexy::IMAGE_MAIN_LIGHT_SMALL;
Image* Sexy::IMAGE_MAIN_MORE_GAMES;
Image* Sexy::IMAGE_MAIN_OPTIONS;
Image* Sexy::IMAGE_MAIN_PLAY;
Image* Sexy::IMAGE_MAIN_PLAY_GLOW;
Image* Sexy::IMAGE_MAIN_PUZZLE;
Image* Sexy::IMAGE_MAIN_QUIT;
Image* Sexy::IMAGE_MAIN_SCORES;
Image* Sexy::IMAGE_MAIN_SECRET_FRAME;
Image* Sexy::IMAGE_MAIN_SECRET_GLOW;
Image* Sexy::IMAGE_MAIN_SECRET_SYMBOL;
Image* Sexy::IMAGE_MAIN_SMALL_GLOW;
Image* Sexy::IMAGE_MAIN_TWILIGHT;
Image* Sexy::IMAGE_MORE_GAMES_FRAME;
Image* Sexy::IMAGE_OLD_GEMS;
Image* Sexy::IMAGE_POWER_GLOW;
Image* Sexy::IMAGE_PUZZLE_DOME;
Image* Sexy::IMAGE_PUZZLE_DOME_MASK;
Image* Sexy::IMAGE_PUZZLE_DOME_SLIVER;
Image* Sexy::IMAGE_PUZZLE_FRAME;
Image* Sexy::IMAGE_PUZZLE_MAP_BUTTON;
Image* Sexy::IMAGE_PUZZLE_MAP_BUTTON_GLOW;
Image* Sexy::IMAGE_PUZZLE_PODS;
Image* Sexy::IMAGE_PUZZLE_PODS_LIT;
Image* Sexy::IMAGE_PUZZLE_PUZZLE_LIT;
Image* Sexy::IMAGE_PUZZLE_THUMB_GEM;
Image* Sexy::IMAGE_PUZZLE_VAPOR1;
Image* Sexy::IMAGE_PUZZLE_VAPOR2;
Image* Sexy::IMAGE_PUZZLE_WARP_BUTTON;
Image* Sexy::IMAGE_PUZZLE_WARP_GLOW;
Image* Sexy::IMAGE_PUZZLE_WIDGET;
Image* Sexy::IMAGE_RING_DUDE;
Image* Sexy::IMAGE_ROCK;
Image* Sexy::IMAGE_ROCK_CHUNK;
Image* Sexy::IMAGE_SELECT;
Image* Sexy::IMAGE_SHARD;
Image* Sexy::IMAGE_SIDEBAR_HINT_BUTTON;
Image* Sexy::IMAGE_SIDEBAR_MENU_BUTTON;
Image* Sexy::IMAGE_SLIDER_THUMB;
Image* Sexy::IMAGE_SLIDER_TRACK;
Image* Sexy::IMAGE_SMALL_GEMS;
Image* Sexy::IMAGE_SPARKLE;
Image* Sexy::IMAGE_UI_BIG_ROLLOVER;
Image* Sexy::IMAGE_UI_BUTTON_HINT;
Image* Sexy::IMAGE_UI_BUTTON_MENU;
Image* Sexy::IMAGE_UI_BUTTON_PAUSE;
Image* Sexy::IMAGE_UI_BUTTON_UNDO;
Image* Sexy::IMAGE_UI_SMALL_ROLLOVER;
Image* Sexy::IMAGE_WAIT_COMPONENT;
Image* Sexy::IMAGE_WARP_BOTTOM_GLOW;
Image* Sexy::IMAGE_WARP_TOP_GLOW;
Image* Sexy::IMAGE_WILDCARD_DESTROYER;

bool Sexy::ExtractLoadingThreadResources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		FONT_BOMB = aMgr.GetFontThrow("FONT_BOMB");
		FONT_CONTINUUM_BOLD_11_NUM = aMgr.GetFontThrow("FONT_CONTINUUM_BOLD_11_NUM");
		FONT_CONTINUUM_BOLD_11_NUM_GLOW = aMgr.GetFontThrow("FONT_CONTINUUM_BOLD_11_NUM_GLOW");
		FONT_CONTINUUM_BOLD_14_NUM = aMgr.GetFontThrow("FONT_CONTINUUM_BOLD_14_NUM");
		FONT_CONTINUUM_BOLD_14_NUM_GLOW = aMgr.GetFontThrow("FONT_CONTINUUM_BOLD_14_NUM_GLOW");
		FONT_CONTINUUM_MED_18 = aMgr.GetFontThrow("FONT_CONTINUUM_MED_18");
		FONT_CONTINUUM_MED_18_GLOW = aMgr.GetFontThrow("FONT_CONTINUUM_MED_18_GLOW");
		FONT_CONTINUUM_MED_33 = aMgr.GetFontThrow("FONT_CONTINUUM_MED_33");
		FONT_CONTINUUM_MED_33_GLOW = aMgr.GetFontThrow("FONT_CONTINUUM_MED_33_GLOW");
		FONT_DEBUG = aMgr.GetFontThrow("FONT_DEBUG");
		FONT_DIGIT = aMgr.GetFontThrow("FONT_DIGIT");
		FONT_HUGE = aMgr.GetFontThrow("FONT_HUGE");
		FONT_SCORE = aMgr.GetFontThrow("FONT_SCORE");
		FONT_VAG_ROUNDED_11 = aMgr.GetFontThrow("FONT_VAG_ROUNDED_11");
		IMAGE_ARROW_UP = aMgr.GetImageThrow("IMAGE_ARROW_UP");
		IMAGE_BAR_LEFT = aMgr.GetImageThrow("IMAGE_BAR_LEFT");
		IMAGE_BAR_MID = aMgr.GetImageThrow("IMAGE_BAR_MID");
		IMAGE_BAR_RIGHT = aMgr.GetImageThrow("IMAGE_BAR_RIGHT");
		IMAGE_BIGSTAR = aMgr.GetImageThrow("IMAGE_BIGSTAR");
		IMAGE_BOARD_BORDER = aMgr.GetImageThrow("IMAGE_BOARD_BORDER");
		IMAGE_BOARD_RED_LIGHT = aMgr.GetImageThrow("IMAGE_BOARD_RED_LIGHT");
		IMAGE_BOMB = aMgr.GetImageThrow("IMAGE_BOMB");
		IMAGE_BUTTON_HILITE = aMgr.GetImageThrow("IMAGE_BUTTON_HILITE");
		IMAGE_CHECKBOX = aMgr.GetImageThrow("IMAGE_CHECKBOX");
		IMAGE_CONTROLS_CLASSIC = aMgr.GetImageThrow("IMAGE_CONTROLS_CLASSIC");
		IMAGE_CONTROLS_PUZZLE = aMgr.GetImageThrow("IMAGE_CONTROLS_PUZZLE");
		IMAGE_CONTROLS_SCORE = aMgr.GetImageThrow("IMAGE_CONTROLS_SCORE");
		IMAGE_DIALOG = aMgr.GetImageThrow("IMAGE_DIALOG");
		IMAGE_DIALOG_BUTTON = aMgr.GetImageThrow("IMAGE_DIALOG_BUTTON");
		IMAGE_DIALOG_BUTTON_GLOW = aMgr.GetImageThrow("IMAGE_DIALOG_BUTTON_GLOW");
		IMAGE_DIALOG_HEADER = aMgr.GetImageThrow("IMAGE_DIALOG_HEADER");
		IMAGE_EDIT_BOX = aMgr.GetImageThrow("IMAGE_EDIT_BOX");
		IMAGE_ENDLESS_CENTER_1 = aMgr.GetImageThrow("IMAGE_ENDLESS_CENTER_1");
		IMAGE_ENDLESS_CENTER_2 = aMgr.GetImageThrow("IMAGE_ENDLESS_CENTER_2");
		IMAGE_ENDLESS_CENTER_3 = aMgr.GetImageThrow("IMAGE_ENDLESS_CENTER_3");
		IMAGE_ENDLESS_CENTER_4 = aMgr.GetImageThrow("IMAGE_ENDLESS_CENTER_4");
		IMAGE_ENDLESS_CENTER_5 = aMgr.GetImageThrow("IMAGE_ENDLESS_CENTER_5");
		IMAGE_ENDLESS_CENTER_6 = aMgr.GetImageThrow("IMAGE_ENDLESS_CENTER_6");
		IMAGE_ENDLESS_CENTER_7 = aMgr.GetImageThrow("IMAGE_ENDLESS_CENTER_7");
		IMAGE_ENDLESS_GEM_HILITE = aMgr.GetImageThrow("IMAGE_ENDLESS_GEM_HILITE");
		IMAGE_ENDLESS_OUTER_1 = aMgr.GetImageThrow("IMAGE_ENDLESS_OUTER_1");
		IMAGE_ENDLESS_OUTER_2 = aMgr.GetImageThrow("IMAGE_ENDLESS_OUTER_2");
		IMAGE_ENDLESS_OUTER_3 = aMgr.GetImageThrow("IMAGE_ENDLESS_OUTER_3");
		IMAGE_ENDLESS_OUTER_4 = aMgr.GetImageThrow("IMAGE_ENDLESS_OUTER_4");
		IMAGE_ENDLESS_OUTER_5 = aMgr.GetImageThrow("IMAGE_ENDLESS_OUTER_5");
		IMAGE_ENDLESS_OUTER_6 = aMgr.GetImageThrow("IMAGE_ENDLESS_OUTER_6");
		IMAGE_ENDLESS_OUTER_7 = aMgr.GetImageThrow("IMAGE_ENDLESS_OUTER_7");
		IMAGE_ENDLESS_SPARK_1 = aMgr.GetImageThrow("IMAGE_ENDLESS_SPARK_1");
		IMAGE_ENDLESS_SPARK_2 = aMgr.GetImageThrow("IMAGE_ENDLESS_SPARK_2");
		IMAGE_ENDLESS_SPARK_3 = aMgr.GetImageThrow("IMAGE_ENDLESS_SPARK_3");
		IMAGE_ENDLESS_WIDGET = aMgr.GetImageThrow("IMAGE_ENDLESS_WIDGET");
		IMAGE_EXPLOSION = aMgr.GetImageThrow("IMAGE_EXPLOSION");
		IMAGE_GALAXY_BUTTON_HILITE = aMgr.GetImageThrow("IMAGE_GALAXY_BUTTON_HILITE");
		IMAGE_GALAXY_CLOSE_BUTTON = aMgr.GetImageThrow("IMAGE_GALAXY_CLOSE_BUTTON");
		IMAGE_GALAXY_HEADER = aMgr.GetImageThrow("IMAGE_GALAXY_HEADER");
		IMAGE_GALAXY_MAP = aMgr.GetImageThrow("IMAGE_GALAXY_MAP");
		IMAGE_GALAXY_MOON_ALPHA = aMgr.GetImageThrow("IMAGE_GALAXY_MOON_ALPHA");
		IMAGE_GALAXY_MOON_SELECT = aMgr.GetImageThrow("IMAGE_GALAXY_MOON_SELECT");
		IMAGE_GALAXY_PLANET_ALPHA = aMgr.GetImageThrow("IMAGE_GALAXY_PLANET_ALPHA");
		IMAGE_GALAXY_PLANET_COMPLETED = aMgr.GetImageThrow("IMAGE_GALAXY_PLANET_COMPLETED");
		IMAGE_GALAXY_PLANET_SELECT = aMgr.GetImageThrow("IMAGE_GALAXY_PLANET_SELECT");
		IMAGE_GALAXY_QUESTION = aMgr.GetImageThrow("IMAGE_GALAXY_QUESTION");
		IMAGE_GALAXY_SUN_GLOW = aMgr.GetImageThrow("IMAGE_GALAXY_SUN_GLOW");
		IMAGE_GALAXY_SUN_MOON_ALPHA = aMgr.GetImageThrow("IMAGE_GALAXY_SUN_MOON_ALPHA");
		IMAGE_GALAXY_SUN_SWIRL = aMgr.GetImageThrow("IMAGE_GALAXY_SUN_SWIRL");
		IMAGE_GALAXY_WARP_BUTTON = aMgr.GetImageThrow("IMAGE_GALAXY_WARP_BUTTON");
		IMAGE_GEM0 = aMgr.GetImageThrow("IMAGE_GEM0");
		IMAGE_GEM1 = aMgr.GetImageThrow("IMAGE_GEM1");
		IMAGE_GEM2 = aMgr.GetImageThrow("IMAGE_GEM2");
		IMAGE_GEM3 = aMgr.GetImageThrow("IMAGE_GEM3");
		IMAGE_GEM4 = aMgr.GetImageThrow("IMAGE_GEM4");
		IMAGE_GEM5 = aMgr.GetImageThrow("IMAGE_GEM5");
		IMAGE_GEM6 = aMgr.GetImageThrow("IMAGE_GEM6");
		IMAGE_GEM_ADD = aMgr.GetImageThrow("IMAGE_GEM_ADD");
		IMAGE_GEM_LIGHTING = aMgr.GetImageThrow("IMAGE_GEM_LIGHTING");
		IMAGE_HELP_ARROW = aMgr.GetImageThrow("IMAGE_HELP_ARROW");
		IMAGE_HELP_GRID_4 = aMgr.GetImageThrow("IMAGE_HELP_GRID_4");
		IMAGE_HELP_GRID_5 = aMgr.GetImageThrow("IMAGE_HELP_GRID_5");
		IMAGE_HELP_INDICATOR = aMgr.GetImageThrow("IMAGE_HELP_INDICATOR");
		IMAGE_HELP_INDICATOR_ARROW = aMgr.GetImageThrow("IMAGE_HELP_INDICATOR_ARROW");
		IMAGE_HS_BACK_TO_GAME_TEXT = aMgr.GetImageThrow("IMAGE_HS_BACK_TO_GAME_TEXT");
		IMAGE_HS_BACK_TO_MENU_TEXT = aMgr.GetImageThrow("IMAGE_HS_BACK_TO_MENU_TEXT");
		IMAGE_HS_BOTTOM = aMgr.GetImageThrow("IMAGE_HS_BOTTOM");
		IMAGE_HS_BUTTON_ROLLOVER = aMgr.GetImageThrow("IMAGE_HS_BUTTON_ROLLOVER");
		IMAGE_HS_LEFT = aMgr.GetImageThrow("IMAGE_HS_LEFT");
		IMAGE_HS_PLAY_AGAIN_TEXT = aMgr.GetImageThrow("IMAGE_HS_PLAY_AGAIN_TEXT");
		IMAGE_HS_RESET_SCORES_TEXT = aMgr.GetImageThrow("IMAGE_HS_RESET_SCORES_TEXT");
		IMAGE_HS_RIGHT = aMgr.GetImageThrow("IMAGE_HS_RIGHT");
		IMAGE_HS_TITLE = aMgr.GetImageThrow("IMAGE_HS_TITLE");
		IMAGE_HS_TOP_BUTTON = aMgr.GetImageThrow("IMAGE_HS_TOP_BUTTON");
		IMAGE_LIGHTNING = aMgr.GetImageThrow("IMAGE_LIGHTNING");
		IMAGE_LIGHTNING_CENTER = aMgr.GetImageThrow("IMAGE_LIGHTNING_CENTER");
		IMAGE_MAIN_ACTION = aMgr.GetImageThrow("IMAGE_MAIN_ACTION");
		IMAGE_MAIN_BIG_OVER = aMgr.GetImageThrow("IMAGE_MAIN_BIG_OVER");
		IMAGE_MAIN_BIG_SELECT = aMgr.GetImageThrow("IMAGE_MAIN_BIG_SELECT");
		IMAGE_MAIN_BOTTOM_GLOW = aMgr.GetImageThrow("IMAGE_MAIN_BOTTOM_GLOW");
		IMAGE_MAIN_CENTER_GLOW = aMgr.GetImageThrow("IMAGE_MAIN_CENTER_GLOW");
		IMAGE_MAIN_CENTER_TEXT = aMgr.GetImageThrow("IMAGE_MAIN_CENTER_TEXT");
		IMAGE_MAIN_CLASSIC = aMgr.GetImageThrow("IMAGE_MAIN_CLASSIC");
		IMAGE_MAIN_COGNITO = aMgr.GetImageThrow("IMAGE_MAIN_COGNITO");
		IMAGE_MAIN_ENDLESS = aMgr.GetImageThrow("IMAGE_MAIN_ENDLESS");
		IMAGE_MAIN_FINITY = aMgr.GetImageThrow("IMAGE_MAIN_FINITY");
		IMAGE_MAIN_GADGETS = aMgr.GetImageThrow("IMAGE_MAIN_GADGETS");
		IMAGE_MAIN_HYPER = aMgr.GetImageThrow("IMAGE_MAIN_HYPER");
		IMAGE_MAIN_LIGHT_BIG = aMgr.GetImageThrow("IMAGE_MAIN_LIGHT_BIG");
		IMAGE_MAIN_LIGHT_MED = aMgr.GetImageThrow("IMAGE_MAIN_LIGHT_MED");
		IMAGE_MAIN_LIGHT_SMALL = aMgr.GetImageThrow("IMAGE_MAIN_LIGHT_SMALL");
		IMAGE_MAIN_MORE_GAMES = aMgr.GetImageThrow("IMAGE_MAIN_MORE_GAMES");
		IMAGE_MAIN_OPTIONS = aMgr.GetImageThrow("IMAGE_MAIN_OPTIONS");
		IMAGE_MAIN_PLAY = aMgr.GetImageThrow("IMAGE_MAIN_PLAY");
		IMAGE_MAIN_PLAY_GLOW = aMgr.GetImageThrow("IMAGE_MAIN_PLAY_GLOW");
		IMAGE_MAIN_PUZZLE = aMgr.GetImageThrow("IMAGE_MAIN_PUZZLE");
		IMAGE_MAIN_QUIT = aMgr.GetImageThrow("IMAGE_MAIN_QUIT");
		IMAGE_MAIN_SCORES = aMgr.GetImageThrow("IMAGE_MAIN_SCORES");
		IMAGE_MAIN_SECRET_FRAME = aMgr.GetImageThrow("IMAGE_MAIN_SECRET_FRAME");
		IMAGE_MAIN_SECRET_GLOW = aMgr.GetImageThrow("IMAGE_MAIN_SECRET_GLOW");
		IMAGE_MAIN_SECRET_SYMBOL = aMgr.GetImageThrow("IMAGE_MAIN_SECRET_SYMBOL");
		IMAGE_MAIN_SMALL_GLOW = aMgr.GetImageThrow("IMAGE_MAIN_SMALL_GLOW");
		IMAGE_MAIN_TWILIGHT = aMgr.GetImageThrow("IMAGE_MAIN_TWILIGHT");
		IMAGE_MORE_GAMES_FRAME = aMgr.GetImageThrow("IMAGE_MORE_GAMES_FRAME");
		IMAGE_OLD_GEMS = aMgr.GetImageThrow("IMAGE_OLD_GEMS");
		IMAGE_POWER_GLOW = aMgr.GetImageThrow("IMAGE_POWER_GLOW");
		IMAGE_PUZZLE_DOME = aMgr.GetImageThrow("IMAGE_PUZZLE_DOME");
		IMAGE_PUZZLE_DOME_MASK = aMgr.GetImageThrow("IMAGE_PUZZLE_DOME_MASK");
		IMAGE_PUZZLE_DOME_SLIVER = aMgr.GetImageThrow("IMAGE_PUZZLE_DOME_SLIVER");
		IMAGE_PUZZLE_FRAME = aMgr.GetImageThrow("IMAGE_PUZZLE_FRAME");
		IMAGE_PUZZLE_MAP_BUTTON = aMgr.GetImageThrow("IMAGE_PUZZLE_MAP_BUTTON");
		IMAGE_PUZZLE_MAP_BUTTON_GLOW = aMgr.GetImageThrow("IMAGE_PUZZLE_MAP_BUTTON_GLOW");
		IMAGE_PUZZLE_PODS = aMgr.GetImageThrow("IMAGE_PUZZLE_PODS");
		IMAGE_PUZZLE_PODS_LIT = aMgr.GetImageThrow("IMAGE_PUZZLE_PODS_LIT");
		IMAGE_PUZZLE_PUZZLE_LIT = aMgr.GetImageThrow("IMAGE_PUZZLE_PUZZLE_LIT");
		IMAGE_PUZZLE_THUMB_GEM = aMgr.GetImageThrow("IMAGE_PUZZLE_THUMB_GEM");
		IMAGE_PUZZLE_VAPOR1 = aMgr.GetImageThrow("IMAGE_PUZZLE_VAPOR1");
		IMAGE_PUZZLE_VAPOR2 = aMgr.GetImageThrow("IMAGE_PUZZLE_VAPOR2");
		IMAGE_PUZZLE_WARP_BUTTON = aMgr.GetImageThrow("IMAGE_PUZZLE_WARP_BUTTON");
		IMAGE_PUZZLE_WARP_GLOW = aMgr.GetImageThrow("IMAGE_PUZZLE_WARP_GLOW");
		IMAGE_PUZZLE_WIDGET = aMgr.GetImageThrow("IMAGE_PUZZLE_WIDGET");
		IMAGE_RING_DUDE = aMgr.GetImageThrow("IMAGE_RING_DUDE");
		IMAGE_ROCK = aMgr.GetImageThrow("IMAGE_ROCK");
		IMAGE_ROCK_CHUNK = aMgr.GetImageThrow("IMAGE_ROCK_CHUNK");
		IMAGE_SELECT = aMgr.GetImageThrow("IMAGE_SELECT");
		IMAGE_SHARD = aMgr.GetImageThrow("IMAGE_SHARD");
		IMAGE_SIDEBAR_HINT_BUTTON = aMgr.GetImageThrow("IMAGE_SIDEBAR_HINT_BUTTON");
		IMAGE_SIDEBAR_MENU_BUTTON = aMgr.GetImageThrow("IMAGE_SIDEBAR_MENU_BUTTON");
		IMAGE_SLIDER_THUMB = aMgr.GetImageThrow("IMAGE_SLIDER_THUMB");
		IMAGE_SLIDER_TRACK = aMgr.GetImageThrow("IMAGE_SLIDER_TRACK");
		IMAGE_SMALL_GEMS = aMgr.GetImageThrow("IMAGE_SMALL_GEMS");
		IMAGE_SPARKLE = aMgr.GetImageThrow("IMAGE_SPARKLE");
		IMAGE_UI_BIG_ROLLOVER = aMgr.GetImageThrow("IMAGE_UI_BIG_ROLLOVER");
		IMAGE_UI_BUTTON_HINT = aMgr.GetImageThrow("IMAGE_UI_BUTTON_HINT");
		IMAGE_UI_BUTTON_MENU = aMgr.GetImageThrow("IMAGE_UI_BUTTON_MENU");
		IMAGE_UI_BUTTON_PAUSE = aMgr.GetImageThrow("IMAGE_UI_BUTTON_PAUSE");
		IMAGE_UI_BUTTON_UNDO = aMgr.GetImageThrow("IMAGE_UI_BUTTON_UNDO");
		IMAGE_UI_SMALL_ROLLOVER = aMgr.GetImageThrow("IMAGE_UI_SMALL_ROLLOVER");
		IMAGE_WAIT_COMPONENT = aMgr.GetImageThrow("IMAGE_WAIT_COMPONENT");
		IMAGE_WARP_BOTTOM_GLOW = aMgr.GetImageThrow("IMAGE_WARP_BOTTOM_GLOW");
		IMAGE_WARP_TOP_GLOW = aMgr.GetImageThrow("IMAGE_WARP_TOP_GLOW");
		IMAGE_WILDCARD_DESTROYER = aMgr.GetImageThrow("IMAGE_WILDCARD_DESTROYER");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// NonResize Resources
Image* Sexy::IMAGE_CURSOR_DRAGGING;
Image* Sexy::IMAGE_CURSOR_HAND;
Image* Sexy::IMAGE_CURSOR_POINTER;
Image* Sexy::IMAGE_CURSOR_TEXT;
Image* Sexy::IMAGE_RELOAD_BKG;
Image* Sexy::IMAGE_RELOAD_OVERLAY;
Image* Sexy::IMAGE_RELOAD_OVERLAY_LIT;

bool Sexy::ExtractNonResizeResources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		IMAGE_CURSOR_DRAGGING = aMgr.GetImageThrow("IMAGE_CURSOR_DRAGGING");
		IMAGE_CURSOR_HAND = aMgr.GetImageThrow("IMAGE_CURSOR_HAND");
		IMAGE_CURSOR_POINTER = aMgr.GetImageThrow("IMAGE_CURSOR_POINTER");
		IMAGE_CURSOR_TEXT = aMgr.GetImageThrow("IMAGE_CURSOR_TEXT");
		IMAGE_RELOAD_BKG = aMgr.GetImageThrow("IMAGE_RELOAD_BKG");
		IMAGE_RELOAD_OVERLAY = aMgr.GetImageThrow("IMAGE_RELOAD_OVERLAY");
		IMAGE_RELOAD_OVERLAY_LIT = aMgr.GetImageThrow("IMAGE_RELOAD_OVERLAY_LIT");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

// Sounds Resources
int Sexy::SOUND_BAD;
int Sexy::SOUND_BOMB_EXPLODE;
int Sexy::SOUND_CLICK;
int Sexy::SOUND_CLICK_DIALOG;
int Sexy::SOUND_COMBO_1;
int Sexy::SOUND_COMBO_2;
int Sexy::SOUND_COMBO_3;
int Sexy::SOUND_COMBO_4;
int Sexy::SOUND_COMBO_5;
int Sexy::SOUND_COMBO_6;
int Sexy::SOUND_ELECTRO_EXPLODE;
int Sexy::SOUND_ELECTRO_PATH;
int Sexy::SOUND_ELECTRO_START;
int Sexy::SOUND_EXCELLENT;
int Sexy::SOUND_EXPLODE;
int Sexy::SOUND_FAIRY_DUST;
int Sexy::SOUND_FIRE_CRACKLE;
int Sexy::SOUND_GALAXY_MAP;
int Sexy::SOUND_GALAXY_PLANET_SELECT;
int Sexy::SOUND_GAME_OVER;
int Sexy::SOUND_GEM_HIT;
int Sexy::SOUND_GET_READY;
int Sexy::SOUND_GO;
int Sexy::SOUND_GOOD;
int Sexy::SOUND_GOODBYE;
int Sexy::SOUND_HIGH_SCORE;
int Sexy::SOUND_HYPERGEM_CREATE;
int Sexy::SOUND_HYPERGEM_DESTROYED;
int Sexy::SOUND_INCREDIBLE;
int Sexy::SOUND_LEVEL_COMPELTE;
int Sexy::SOUND_MAIN_GAME_START;
int Sexy::SOUND_MAIN_LANDING_LIGHTS;
int Sexy::SOUND_MAIN_MOUSE_CLICK;
int Sexy::SOUND_MAIN_MOUSE_LEAVE;
int Sexy::SOUND_MAIN_MOUSE_OVER;
int Sexy::SOUND_MULTISHOT;
int Sexy::SOUND_NO_MORE_MOVES;
int Sexy::SOUND_PANEL_SLIDE;
int Sexy::SOUND_PUZZLE_SOLVED;
int Sexy::SOUND_SELECT;
int Sexy::SOUND_TIME_UP;
int Sexy::SOUND_TRANSFER;
int Sexy::SOUND_TRANSFER_BIG;
int Sexy::SOUND_WARNING;
int Sexy::SOUND_WARP_DRIVE_READY;
int Sexy::SOUND_WELCOME;
int Sexy::SOUND_WELCOME_BACK;
int Sexy::SOUND_WHIRLPOOL;
int Sexy::SOUND_WORLD_COMPELTE;
int Sexy::SOUND_WORLD_COMPLETE;

bool Sexy::ExtractSoundsResources(ResourceManager *theManager)
{
	gNeedRecalcVariableToIdMap = true;

	ResourceManager &aMgr = *theManager;
	try
	{
		SOUND_BAD = aMgr.GetSoundThrow("SOUND_BAD");
		SOUND_BOMB_EXPLODE = aMgr.GetSoundThrow("SOUND_BOMB_EXPLODE");
		SOUND_CLICK = aMgr.GetSoundThrow("SOUND_CLICK");
		SOUND_CLICK_DIALOG = aMgr.GetSoundThrow("SOUND_CLICK_DIALOG");
		SOUND_COMBO_1 = aMgr.GetSoundThrow("SOUND_COMBO_1");
		SOUND_COMBO_2 = aMgr.GetSoundThrow("SOUND_COMBO_2");
		SOUND_COMBO_3 = aMgr.GetSoundThrow("SOUND_COMBO_3");
		SOUND_COMBO_4 = aMgr.GetSoundThrow("SOUND_COMBO_4");
		SOUND_COMBO_5 = aMgr.GetSoundThrow("SOUND_COMBO_5");
		SOUND_COMBO_6 = aMgr.GetSoundThrow("SOUND_COMBO_6");
		SOUND_ELECTRO_EXPLODE = aMgr.GetSoundThrow("SOUND_ELECTRO_EXPLODE");
		SOUND_ELECTRO_PATH = aMgr.GetSoundThrow("SOUND_ELECTRO_PATH");
		SOUND_ELECTRO_START = aMgr.GetSoundThrow("SOUND_ELECTRO_START");
		SOUND_EXCELLENT = aMgr.GetSoundThrow("SOUND_EXCELLENT");
		SOUND_EXPLODE = aMgr.GetSoundThrow("SOUND_EXPLODE");
		SOUND_FAIRY_DUST = aMgr.GetSoundThrow("SOUND_FAIRY_DUST");
		SOUND_FIRE_CRACKLE = aMgr.GetSoundThrow("SOUND_FIRE_CRACKLE");
		SOUND_GALAXY_MAP = aMgr.GetSoundThrow("SOUND_GALAXY_MAP");
		SOUND_GALAXY_PLANET_SELECT = aMgr.GetSoundThrow("SOUND_GALAXY_PLANET_SELECT");
		SOUND_GAME_OVER = aMgr.GetSoundThrow("SOUND_GAME_OVER");
		SOUND_GEM_HIT = aMgr.GetSoundThrow("SOUND_GEM_HIT");
		SOUND_GET_READY = aMgr.GetSoundThrow("SOUND_GET_READY");
		SOUND_GO = aMgr.GetSoundThrow("SOUND_GO");
		SOUND_GOOD = aMgr.GetSoundThrow("SOUND_GOOD");
		SOUND_GOODBYE = aMgr.GetSoundThrow("SOUND_GOODBYE");
		SOUND_HIGH_SCORE = aMgr.GetSoundThrow("SOUND_HIGH_SCORE");
		SOUND_HYPERGEM_CREATE = aMgr.GetSoundThrow("SOUND_HYPERGEM_CREATE");
		SOUND_HYPERGEM_DESTROYED = aMgr.GetSoundThrow("SOUND_HYPERGEM_DESTROYED");
		SOUND_INCREDIBLE = aMgr.GetSoundThrow("SOUND_INCREDIBLE");
		SOUND_LEVEL_COMPELTE = aMgr.GetSoundThrow("SOUND_LEVEL_COMPELTE");
		SOUND_MAIN_GAME_START = aMgr.GetSoundThrow("SOUND_MAIN_GAME_START");
		SOUND_MAIN_LANDING_LIGHTS = aMgr.GetSoundThrow("SOUND_MAIN_LANDING_LIGHTS");
		SOUND_MAIN_MOUSE_CLICK = aMgr.GetSoundThrow("SOUND_MAIN_MOUSE_CLICK");
		SOUND_MAIN_MOUSE_LEAVE = aMgr.GetSoundThrow("SOUND_MAIN_MOUSE_LEAVE");
		SOUND_MAIN_MOUSE_OVER = aMgr.GetSoundThrow("SOUND_MAIN_MOUSE_OVER");
		SOUND_MULTISHOT = aMgr.GetSoundThrow("SOUND_MULTISHOT");
		SOUND_NO_MORE_MOVES = aMgr.GetSoundThrow("SOUND_NO_MORE_MOVES");
		SOUND_PANEL_SLIDE = aMgr.GetSoundThrow("SOUND_PANEL_SLIDE");
		SOUND_PUZZLE_SOLVED = aMgr.GetSoundThrow("SOUND_PUZZLE_SOLVED");
		SOUND_SELECT = aMgr.GetSoundThrow("SOUND_SELECT");
		SOUND_TIME_UP = aMgr.GetSoundThrow("SOUND_TIME_UP");
		SOUND_TRANSFER = aMgr.GetSoundThrow("SOUND_TRANSFER");
		SOUND_TRANSFER_BIG = aMgr.GetSoundThrow("SOUND_TRANSFER_BIG");
		SOUND_WARNING = aMgr.GetSoundThrow("SOUND_WARNING");
		SOUND_WARP_DRIVE_READY = aMgr.GetSoundThrow("SOUND_WARP_DRIVE_READY");
		SOUND_WELCOME = aMgr.GetSoundThrow("SOUND_WELCOME");
		SOUND_WELCOME_BACK = aMgr.GetSoundThrow("SOUND_WELCOME_BACK");
		SOUND_WHIRLPOOL = aMgr.GetSoundThrow("SOUND_WHIRLPOOL");
		SOUND_WORLD_COMPELTE = aMgr.GetSoundThrow("SOUND_WORLD_COMPELTE");
		SOUND_WORLD_COMPLETE = aMgr.GetSoundThrow("SOUND_WORLD_COMPLETE");
	}
	catch(ResourceManagerException&)
	{
		return false;
	}
	return true;
}

static void* gResources[] =
{
	&IMAGE_LOGO,
	&IMAGE_LOGO_2,
	&IMAGE_LOGO_DELUXE,
	&IMAGE_LOADER_BAR,
	&IMAGE_LOADER_BAR_LIT_BLUE,
	&IMAGE_LOADER_BAR_LIT_PURPLE,
	&IMAGE_LOADER_BAR_FLASH,
	&IMAGE_LOADER_BAR_TEXT,
	&IMAGE_LOGO_POPCAP,
	&IMAGE_RELOAD_BKG,
	&IMAGE_RELOAD_OVERLAY,
	&IMAGE_RELOAD_OVERLAY_LIT,
	&IMAGE_CURSOR_POINTER,
	&IMAGE_CURSOR_HAND,
	&IMAGE_CURSOR_DRAGGING,
	&IMAGE_CURSOR_TEXT,
	&FONT_1,
	&FONT_2,
	&FONT_CONTINUUM_MED_14,
	&FONT_CONTINUUM_MED_14_GLOW,
	&FONT_CONT_SM,
	&FONT_CONT_MED,
	&SOUND_TRANSFER,
	&SOUND_TRANSFER_BIG,
	&SOUND_COMBO_1,
	&SOUND_COMBO_2,
	&SOUND_COMBO_3,
	&SOUND_COMBO_4,
	&SOUND_COMBO_5,
	&SOUND_COMBO_6,
	&SOUND_BAD,
	&SOUND_GEM_HIT,
	&SOUND_HYPERGEM_CREATE,
	&SOUND_HYPERGEM_DESTROYED,
	&SOUND_EXPLODE,
	&SOUND_CLICK,
	&SOUND_CLICK_DIALOG,
	&SOUND_SELECT,
	&SOUND_MULTISHOT,
	&SOUND_GO,
	&SOUND_GAME_OVER,
	&SOUND_TIME_UP,
	&SOUND_FIRE_CRACKLE,
	&SOUND_WARNING,
	&SOUND_WHIRLPOOL,
	&SOUND_GOOD,
	&SOUND_EXCELLENT,
	&SOUND_INCREDIBLE,
	&SOUND_BOMB_EXPLODE,
	&SOUND_FAIRY_DUST,
	&SOUND_ELECTRO_START,
	&SOUND_ELECTRO_PATH,
	&SOUND_ELECTRO_EXPLODE,
	&SOUND_PANEL_SLIDE,
	&SOUND_HIGH_SCORE,
	&SOUND_MAIN_GAME_START,
	&SOUND_MAIN_MOUSE_CLICK,
	&SOUND_MAIN_MOUSE_OVER,
	&SOUND_MAIN_MOUSE_LEAVE,
	&SOUND_MAIN_LANDING_LIGHTS,
	&SOUND_GALAXY_MAP,
	&SOUND_GALAXY_PLANET_SELECT,
	&SOUND_GET_READY,
	&SOUND_WELCOME,
	&SOUND_GOODBYE,
	&SOUND_WELCOME_BACK,
	&SOUND_PUZZLE_SOLVED,
	&SOUND_LEVEL_COMPELTE,
	&SOUND_WORLD_COMPELTE,
	&SOUND_WARP_DRIVE_READY,
	&SOUND_WORLD_COMPLETE,
	&SOUND_NO_MORE_MOVES,
	&IMAGE_MAIN_BKG,
	&IMAGE_MAIN_FG,
	&IMAGE_MAIN_FOG_BANK,
	&IMAGE_MAIN_FOG_BANK_FG,
	&IMAGE_MAIN_STARFIELD,
	&IMAGE_MAIN_STAR_SPARKLE,
	&IMAGE_MAIN_COMET,
	&IMAGE_MAIN_PLANET_1,
	&IMAGE_HYPERSPACE,
	&IMAGE_HYPERSPACE_INITIAL,
	&IMAGE_TUNNEL_END,
	&IMAGE_WARP_LINES,
	&IMAGE_FIRE_RING,
	&IMAGE_BLACK_HOLE,
	&IMAGE_BLACK_HOLE_COVER,
	&IMAGE_SMALL_GEMS,
	&IMAGE_WILDCARD_DESTROYER,
	&IMAGE_HELP_INDICATOR,
	&IMAGE_HELP_INDICATOR_ARROW,
	&IMAGE_HELP_ARROW,
	&IMAGE_GEM0,
	&IMAGE_GEM1,
	&IMAGE_GEM2,
	&IMAGE_GEM3,
	&IMAGE_GEM4,
	&IMAGE_GEM5,
	&IMAGE_GEM6,
	&IMAGE_OLD_GEMS,
	&IMAGE_GEM_ADD,
	&IMAGE_SELECT,
	&IMAGE_WAIT_COMPONENT,
	&IMAGE_SPARKLE,
	&IMAGE_EDIT_BOX,
	&IMAGE_BOARD_BORDER,
	&IMAGE_BOARD_RED_LIGHT,
	&IMAGE_PUZZLE_FRAME,
	&IMAGE_SIDEBAR_HINT_BUTTON,
	&IMAGE_SIDEBAR_MENU_BUTTON,
	&IMAGE_BOMB,
	&IMAGE_EXPLOSION,
	&IMAGE_SHARD,
	&IMAGE_BIGSTAR,
	&IMAGE_ROCK,
	&IMAGE_ROCK_CHUNK,
	&IMAGE_BAR_LEFT,
	&IMAGE_BAR_RIGHT,
	&IMAGE_BAR_MID,
	&IMAGE_CONTROLS_SCORE,
	&IMAGE_CONTROLS_CLASSIC,
	&IMAGE_CONTROLS_PUZZLE,
	&IMAGE_BUTTON_HILITE,
	&IMAGE_RING_DUDE,
	&IMAGE_GEM_LIGHTING,
	&IMAGE_LIGHTNING,
	&IMAGE_LIGHTNING_CENTER,
	&IMAGE_POWER_GLOW,
	&IMAGE_MORE_GAMES_FRAME,
	&IMAGE_WARP_TOP_GLOW,
	&IMAGE_WARP_BOTTOM_GLOW,
	&IMAGE_HELP_GRID_4,
	&IMAGE_HELP_GRID_5,
	&IMAGE_ARROW_UP,
	&IMAGE_DIALOG,
	&IMAGE_DIALOG_HEADER,
	&IMAGE_DIALOG_BUTTON,
	&IMAGE_DIALOG_BUTTON_GLOW,
	&IMAGE_SLIDER_TRACK,
	&IMAGE_SLIDER_THUMB,
	&IMAGE_CHECKBOX,
	&IMAGE_UI_BIG_ROLLOVER,
	&IMAGE_UI_SMALL_ROLLOVER,
	&IMAGE_UI_BUTTON_HINT,
	&IMAGE_UI_BUTTON_MENU,
	&IMAGE_UI_BUTTON_UNDO,
	&IMAGE_UI_BUTTON_PAUSE,
	&IMAGE_PUZZLE_WIDGET,
	&IMAGE_PUZZLE_PODS,
	&IMAGE_PUZZLE_PODS_LIT,
	&IMAGE_PUZZLE_DOME,
	&IMAGE_PUZZLE_DOME_MASK,
	&IMAGE_PUZZLE_DOME_SLIVER,
	&IMAGE_PUZZLE_PUZZLE_LIT,
	&IMAGE_PUZZLE_THUMB_GEM,
	&IMAGE_PUZZLE_VAPOR1,
	&IMAGE_PUZZLE_VAPOR2,
	&IMAGE_PUZZLE_MAP_BUTTON,
	&IMAGE_PUZZLE_MAP_BUTTON_GLOW,
	&IMAGE_PUZZLE_WARP_BUTTON,
	&IMAGE_PUZZLE_WARP_GLOW,
	&IMAGE_ENDLESS_WIDGET,
	&IMAGE_ENDLESS_CENTER_1,
	&IMAGE_ENDLESS_CENTER_2,
	&IMAGE_ENDLESS_CENTER_3,
	&IMAGE_ENDLESS_CENTER_4,
	&IMAGE_ENDLESS_CENTER_5,
	&IMAGE_ENDLESS_CENTER_6,
	&IMAGE_ENDLESS_CENTER_7,
	&IMAGE_ENDLESS_OUTER_1,
	&IMAGE_ENDLESS_OUTER_2,
	&IMAGE_ENDLESS_OUTER_3,
	&IMAGE_ENDLESS_OUTER_4,
	&IMAGE_ENDLESS_OUTER_5,
	&IMAGE_ENDLESS_OUTER_6,
	&IMAGE_ENDLESS_OUTER_7,
	&IMAGE_ENDLESS_SPARK_1,
	&IMAGE_ENDLESS_SPARK_2,
	&IMAGE_ENDLESS_SPARK_3,
	&IMAGE_ENDLESS_GEM_HILITE,
	&IMAGE_GALAXY_MAP,
	&IMAGE_GALAXY_BUTTON_HILITE,
	&IMAGE_GALAXY_WARP_BUTTON,
	&IMAGE_GALAXY_CLOSE_BUTTON,
	&IMAGE_GALAXY_HEADER,
	&IMAGE_GALAXY_PLANET_ALPHA,
	&IMAGE_GALAXY_SUN_MOON_ALPHA,
	&IMAGE_GALAXY_MOON_ALPHA,
	&IMAGE_GALAXY_PLANET_SELECT,
	&IMAGE_GALAXY_PLANET_COMPLETED,
	&IMAGE_GALAXY_SUN_GLOW,
	&IMAGE_GALAXY_SUN_SWIRL,
	&IMAGE_GALAXY_QUESTION,
	&IMAGE_GALAXY_MOON_SELECT,
	&IMAGE_HS_BOTTOM,
	&IMAGE_HS_LEFT,
	&IMAGE_HS_RIGHT,
	&IMAGE_HS_TITLE,
	&IMAGE_HS_TOP_BUTTON,
	&IMAGE_HS_BACK_TO_MENU_TEXT,
	&IMAGE_HS_BACK_TO_GAME_TEXT,
	&IMAGE_HS_PLAY_AGAIN_TEXT,
	&IMAGE_HS_RESET_SCORES_TEXT,
	&IMAGE_HS_BUTTON_ROLLOVER,
	&IMAGE_MAIN_GADGETS,
	&IMAGE_MAIN_BIG_SELECT,
	&IMAGE_MAIN_BIG_OVER,
	&IMAGE_MAIN_SMALL_GLOW,
	&IMAGE_MAIN_PLAY_GLOW,
	&IMAGE_MAIN_BOTTOM_GLOW,
	&IMAGE_MAIN_CLASSIC,
	&IMAGE_MAIN_ACTION,
	&IMAGE_MAIN_PUZZLE,
	&IMAGE_MAIN_ENDLESS,
	&IMAGE_MAIN_TWILIGHT,
	&IMAGE_MAIN_HYPER,
	&IMAGE_MAIN_COGNITO,
	&IMAGE_MAIN_FINITY,
	&IMAGE_MAIN_MORE_GAMES,
	&IMAGE_MAIN_OPTIONS,
	&IMAGE_MAIN_SCORES,
	&IMAGE_MAIN_PLAY,
	&IMAGE_MAIN_QUIT,
	&IMAGE_MAIN_CENTER_TEXT,
	&IMAGE_MAIN_LIGHT_BIG,
	&IMAGE_MAIN_LIGHT_MED,
	&IMAGE_MAIN_LIGHT_SMALL,
	&IMAGE_MAIN_CENTER_GLOW,
	&IMAGE_MAIN_SECRET_GLOW,
	&IMAGE_MAIN_SECRET_FRAME,
	&IMAGE_MAIN_SECRET_SYMBOL,
	&FONT_CONTINUUM_MED_33,
	&FONT_CONTINUUM_MED_33_GLOW,
	&FONT_CONTINUUM_MED_18,
	&FONT_CONTINUUM_MED_18_GLOW,
	&FONT_VAG_ROUNDED_11,
	&FONT_CONTINUUM_BOLD_14_NUM,
	&FONT_CONTINUUM_BOLD_14_NUM_GLOW,
	&FONT_CONTINUUM_BOLD_11_NUM,
	&FONT_CONTINUUM_BOLD_11_NUM_GLOW,
	&FONT_DIGIT,
	&FONT_BOMB,
	&FONT_HUGE,
	&FONT_SCORE,
	&FONT_DEBUG,
	NULL
};

Image* Sexy::LoadImageById(ResourceManager *theManager, int theId)
{
	return (*((Image**)gResources[theId]) = theManager->LoadImage(GetStringIdById(theId)));
}

void Sexy::ReplaceImageById(ResourceManager *theManager, int theId, Image *theImage)
{
	theManager->ReplaceImage(GetStringIdById(theId),theImage);
	*(Image**)gResources[theId] = theImage;
}

Image* Sexy::GetImageById(int theId)
{
	return *(Image**)gResources[theId];
}

Font* Sexy::GetFontById(int theId)
{
	return *(Font**)gResources[theId];
}

int Sexy::GetSoundById(int theId)
{
	return *(int*)gResources[theId];
}

Image*& Sexy::GetImageRefById(int theId)
{
	return *(Image**)gResources[theId];
}

Font*& Sexy::GetFontRefById(int theId)
{
	return *(Font**)gResources[theId];
}

int& Sexy::GetSoundRefById(int theId)
{
	return *(int*)gResources[theId];
}

static Sexy::ResourceId GetIdByVariable(const void *theVariable)
{
	typedef std::map<int,int> MyMap;
	static MyMap aMap;
	if(gNeedRecalcVariableToIdMap)
	{
		gNeedRecalcVariableToIdMap = false;
		aMap.clear();
		for(int i=0; i<RESOURCE_ID_MAX; i++)
			aMap[*(int*)gResources[i]] = i;
	}

	MyMap::iterator anItr = aMap.find((int)theVariable);
	if (anItr == aMap.end())
		return RESOURCE_ID_MAX;
	else
		return (ResourceId) anItr->second;
}

Sexy::ResourceId Sexy::GetIdByImage(Image *theImage)
{
	return GetIdByVariable(theImage);
}

Sexy::ResourceId Sexy::GetIdByFont(Font *theFont)
{
	return GetIdByVariable(theFont);
}

Sexy::ResourceId Sexy::GetIdBySound(int theSound)
{
	return GetIdByVariable((void*)theSound);
}

const char* Sexy::GetStringIdById(int theId)
{
	switch(theId)
	{
		case IMAGE_LOGO_ID: return "IMAGE_LOGO";
		case IMAGE_LOGO_2_ID: return "IMAGE_LOGO_2";
		case IMAGE_LOGO_DELUXE_ID: return "IMAGE_LOGO_DELUXE";
		case IMAGE_LOADER_BAR_ID: return "IMAGE_LOADER_BAR";
		case IMAGE_LOADER_BAR_LIT_BLUE_ID: return "IMAGE_LOADER_BAR_LIT_BLUE";
		case IMAGE_LOADER_BAR_LIT_PURPLE_ID: return "IMAGE_LOADER_BAR_LIT_PURPLE";
		case IMAGE_LOADER_BAR_FLASH_ID: return "IMAGE_LOADER_BAR_FLASH";
		case IMAGE_LOADER_BAR_TEXT_ID: return "IMAGE_LOADER_BAR_TEXT";
		case IMAGE_LOGO_POPCAP_ID: return "IMAGE_LOGO_POPCAP";
		case IMAGE_RELOAD_BKG_ID: return "IMAGE_RELOAD_BKG";
		case IMAGE_RELOAD_OVERLAY_ID: return "IMAGE_RELOAD_OVERLAY";
		case IMAGE_RELOAD_OVERLAY_LIT_ID: return "IMAGE_RELOAD_OVERLAY_LIT";
		case IMAGE_CURSOR_POINTER_ID: return "IMAGE_CURSOR_POINTER";
		case IMAGE_CURSOR_HAND_ID: return "IMAGE_CURSOR_HAND";
		case IMAGE_CURSOR_DRAGGING_ID: return "IMAGE_CURSOR_DRAGGING";
		case IMAGE_CURSOR_TEXT_ID: return "IMAGE_CURSOR_TEXT";
		case FONT_1_ID: return "FONT_1";
		case FONT_2_ID: return "FONT_2";
		case FONT_CONTINUUM_MED_14_ID: return "FONT_CONTINUUM_MED_14";
		case FONT_CONTINUUM_MED_14_GLOW_ID: return "FONT_CONTINUUM_MED_14_GLOW";
		case FONT_CONT_SM_ID: return "FONT_CONT_SM";
		case FONT_CONT_MED_ID: return "FONT_CONT_MED";
		case SOUND_TRANSFER_ID: return "SOUND_TRANSFER";
		case SOUND_TRANSFER_BIG_ID: return "SOUND_TRANSFER_BIG";
		case SOUND_COMBO_1_ID: return "SOUND_COMBO_1";
		case SOUND_COMBO_2_ID: return "SOUND_COMBO_2";
		case SOUND_COMBO_3_ID: return "SOUND_COMBO_3";
		case SOUND_COMBO_4_ID: return "SOUND_COMBO_4";
		case SOUND_COMBO_5_ID: return "SOUND_COMBO_5";
		case SOUND_COMBO_6_ID: return "SOUND_COMBO_6";
		case SOUND_BAD_ID: return "SOUND_BAD";
		case SOUND_GEM_HIT_ID: return "SOUND_GEM_HIT";
		case SOUND_HYPERGEM_CREATE_ID: return "SOUND_HYPERGEM_CREATE";
		case SOUND_HYPERGEM_DESTROYED_ID: return "SOUND_HYPERGEM_DESTROYED";
		case SOUND_EXPLODE_ID: return "SOUND_EXPLODE";
		case SOUND_CLICK_ID: return "SOUND_CLICK";
		case SOUND_CLICK_DIALOG_ID: return "SOUND_CLICK_DIALOG";
		case SOUND_SELECT_ID: return "SOUND_SELECT";
		case SOUND_MULTISHOT_ID: return "SOUND_MULTISHOT";
		case SOUND_GO_ID: return "SOUND_GO";
		case SOUND_GAME_OVER_ID: return "SOUND_GAME_OVER";
		case SOUND_TIME_UP_ID: return "SOUND_TIME_UP";
		case SOUND_FIRE_CRACKLE_ID: return "SOUND_FIRE_CRACKLE";
		case SOUND_WARNING_ID: return "SOUND_WARNING";
		case SOUND_WHIRLPOOL_ID: return "SOUND_WHIRLPOOL";
		case SOUND_GOOD_ID: return "SOUND_GOOD";
		case SOUND_EXCELLENT_ID: return "SOUND_EXCELLENT";
		case SOUND_INCREDIBLE_ID: return "SOUND_INCREDIBLE";
		case SOUND_BOMB_EXPLODE_ID: return "SOUND_BOMB_EXPLODE";
		case SOUND_FAIRY_DUST_ID: return "SOUND_FAIRY_DUST";
		case SOUND_ELECTRO_START_ID: return "SOUND_ELECTRO_START";
		case SOUND_ELECTRO_PATH_ID: return "SOUND_ELECTRO_PATH";
		case SOUND_ELECTRO_EXPLODE_ID: return "SOUND_ELECTRO_EXPLODE";
		case SOUND_PANEL_SLIDE_ID: return "SOUND_PANEL_SLIDE";
		case SOUND_HIGH_SCORE_ID: return "SOUND_HIGH_SCORE";
		case SOUND_MAIN_GAME_START_ID: return "SOUND_MAIN_GAME_START";
		case SOUND_MAIN_MOUSE_CLICK_ID: return "SOUND_MAIN_MOUSE_CLICK";
		case SOUND_MAIN_MOUSE_OVER_ID: return "SOUND_MAIN_MOUSE_OVER";
		case SOUND_MAIN_MOUSE_LEAVE_ID: return "SOUND_MAIN_MOUSE_LEAVE";
		case SOUND_MAIN_LANDING_LIGHTS_ID: return "SOUND_MAIN_LANDING_LIGHTS";
		case SOUND_GALAXY_MAP_ID: return "SOUND_GALAXY_MAP";
		case SOUND_GALAXY_PLANET_SELECT_ID: return "SOUND_GALAXY_PLANET_SELECT";
		case SOUND_GET_READY_ID: return "SOUND_GET_READY";
		case SOUND_WELCOME_ID: return "SOUND_WELCOME";
		case SOUND_GOODBYE_ID: return "SOUND_GOODBYE";
		case SOUND_WELCOME_BACK_ID: return "SOUND_WELCOME_BACK";
		case SOUND_PUZZLE_SOLVED_ID: return "SOUND_PUZZLE_SOLVED";
		case SOUND_LEVEL_COMPELTE_ID: return "SOUND_LEVEL_COMPELTE";
		case SOUND_WORLD_COMPELTE_ID: return "SOUND_WORLD_COMPELTE";
		case SOUND_WARP_DRIVE_READY_ID: return "SOUND_WARP_DRIVE_READY";
		case SOUND_WORLD_COMPLETE_ID: return "SOUND_WORLD_COMPLETE";
		case SOUND_NO_MORE_MOVES_ID: return "SOUND_NO_MORE_MOVES";
		case IMAGE_MAIN_BKG_ID: return "IMAGE_MAIN_BKG";
		case IMAGE_MAIN_FG_ID: return "IMAGE_MAIN_FG";
		case IMAGE_MAIN_FOG_BANK_ID: return "IMAGE_MAIN_FOG_BANK";
		case IMAGE_MAIN_FOG_BANK_FG_ID: return "IMAGE_MAIN_FOG_BANK_FG";
		case IMAGE_MAIN_STARFIELD_ID: return "IMAGE_MAIN_STARFIELD";
		case IMAGE_MAIN_STAR_SPARKLE_ID: return "IMAGE_MAIN_STAR_SPARKLE";
		case IMAGE_MAIN_COMET_ID: return "IMAGE_MAIN_COMET";
		case IMAGE_MAIN_PLANET_1_ID: return "IMAGE_MAIN_PLANET_1";
		case IMAGE_HYPERSPACE_ID: return "IMAGE_HYPERSPACE";
		case IMAGE_HYPERSPACE_INITIAL_ID: return "IMAGE_HYPERSPACE_INITIAL";
		case IMAGE_TUNNEL_END_ID: return "IMAGE_TUNNEL_END";
		case IMAGE_WARP_LINES_ID: return "IMAGE_WARP_LINES";
		case IMAGE_FIRE_RING_ID: return "IMAGE_FIRE_RING";
		case IMAGE_BLACK_HOLE_ID: return "IMAGE_BLACK_HOLE";
		case IMAGE_BLACK_HOLE_COVER_ID: return "IMAGE_BLACK_HOLE_COVER";
		case IMAGE_SMALL_GEMS_ID: return "IMAGE_SMALL_GEMS";
		case IMAGE_WILDCARD_DESTROYER_ID: return "IMAGE_WILDCARD_DESTROYER";
		case IMAGE_HELP_INDICATOR_ID: return "IMAGE_HELP_INDICATOR";
		case IMAGE_HELP_INDICATOR_ARROW_ID: return "IMAGE_HELP_INDICATOR_ARROW";
		case IMAGE_HELP_ARROW_ID: return "IMAGE_HELP_ARROW";
		case IMAGE_GEM0_ID: return "IMAGE_GEM0";
		case IMAGE_GEM1_ID: return "IMAGE_GEM1";
		case IMAGE_GEM2_ID: return "IMAGE_GEM2";
		case IMAGE_GEM3_ID: return "IMAGE_GEM3";
		case IMAGE_GEM4_ID: return "IMAGE_GEM4";
		case IMAGE_GEM5_ID: return "IMAGE_GEM5";
		case IMAGE_GEM6_ID: return "IMAGE_GEM6";
		case IMAGE_OLD_GEMS_ID: return "IMAGE_OLD_GEMS";
		case IMAGE_GEM_ADD_ID: return "IMAGE_GEM_ADD";
		case IMAGE_SELECT_ID: return "IMAGE_SELECT";
		case IMAGE_WAIT_COMPONENT_ID: return "IMAGE_WAIT_COMPONENT";
		case IMAGE_SPARKLE_ID: return "IMAGE_SPARKLE";
		case IMAGE_EDIT_BOX_ID: return "IMAGE_EDIT_BOX";
		case IMAGE_BOARD_BORDER_ID: return "IMAGE_BOARD_BORDER";
		case IMAGE_BOARD_RED_LIGHT_ID: return "IMAGE_BOARD_RED_LIGHT";
		case IMAGE_PUZZLE_FRAME_ID: return "IMAGE_PUZZLE_FRAME";
		case IMAGE_SIDEBAR_HINT_BUTTON_ID: return "IMAGE_SIDEBAR_HINT_BUTTON";
		case IMAGE_SIDEBAR_MENU_BUTTON_ID: return "IMAGE_SIDEBAR_MENU_BUTTON";
		case IMAGE_BOMB_ID: return "IMAGE_BOMB";
		case IMAGE_EXPLOSION_ID: return "IMAGE_EXPLOSION";
		case IMAGE_SHARD_ID: return "IMAGE_SHARD";
		case IMAGE_BIGSTAR_ID: return "IMAGE_BIGSTAR";
		case IMAGE_ROCK_ID: return "IMAGE_ROCK";
		case IMAGE_ROCK_CHUNK_ID: return "IMAGE_ROCK_CHUNK";
		case IMAGE_BAR_LEFT_ID: return "IMAGE_BAR_LEFT";
		case IMAGE_BAR_RIGHT_ID: return "IMAGE_BAR_RIGHT";
		case IMAGE_BAR_MID_ID: return "IMAGE_BAR_MID";
		case IMAGE_CONTROLS_SCORE_ID: return "IMAGE_CONTROLS_SCORE";
		case IMAGE_CONTROLS_CLASSIC_ID: return "IMAGE_CONTROLS_CLASSIC";
		case IMAGE_CONTROLS_PUZZLE_ID: return "IMAGE_CONTROLS_PUZZLE";
		case IMAGE_BUTTON_HILITE_ID: return "IMAGE_BUTTON_HILITE";
		case IMAGE_RING_DUDE_ID: return "IMAGE_RING_DUDE";
		case IMAGE_GEM_LIGHTING_ID: return "IMAGE_GEM_LIGHTING";
		case IMAGE_LIGHTNING_ID: return "IMAGE_LIGHTNING";
		case IMAGE_LIGHTNING_CENTER_ID: return "IMAGE_LIGHTNING_CENTER";
		case IMAGE_POWER_GLOW_ID: return "IMAGE_POWER_GLOW";
		case IMAGE_MORE_GAMES_FRAME_ID: return "IMAGE_MORE_GAMES_FRAME";
		case IMAGE_WARP_TOP_GLOW_ID: return "IMAGE_WARP_TOP_GLOW";
		case IMAGE_WARP_BOTTOM_GLOW_ID: return "IMAGE_WARP_BOTTOM_GLOW";
		case IMAGE_HELP_GRID_4_ID: return "IMAGE_HELP_GRID_4";
		case IMAGE_HELP_GRID_5_ID: return "IMAGE_HELP_GRID_5";
		case IMAGE_ARROW_UP_ID: return "IMAGE_ARROW_UP";
		case IMAGE_DIALOG_ID: return "IMAGE_DIALOG";
		case IMAGE_DIALOG_HEADER_ID: return "IMAGE_DIALOG_HEADER";
		case IMAGE_DIALOG_BUTTON_ID: return "IMAGE_DIALOG_BUTTON";
		case IMAGE_DIALOG_BUTTON_GLOW_ID: return "IMAGE_DIALOG_BUTTON_GLOW";
		case IMAGE_SLIDER_TRACK_ID: return "IMAGE_SLIDER_TRACK";
		case IMAGE_SLIDER_THUMB_ID: return "IMAGE_SLIDER_THUMB";
		case IMAGE_CHECKBOX_ID: return "IMAGE_CHECKBOX";
		case IMAGE_UI_BIG_ROLLOVER_ID: return "IMAGE_UI_BIG_ROLLOVER";
		case IMAGE_UI_SMALL_ROLLOVER_ID: return "IMAGE_UI_SMALL_ROLLOVER";
		case IMAGE_UI_BUTTON_HINT_ID: return "IMAGE_UI_BUTTON_HINT";
		case IMAGE_UI_BUTTON_MENU_ID: return "IMAGE_UI_BUTTON_MENU";
		case IMAGE_UI_BUTTON_UNDO_ID: return "IMAGE_UI_BUTTON_UNDO";
		case IMAGE_UI_BUTTON_PAUSE_ID: return "IMAGE_UI_BUTTON_PAUSE";
		case IMAGE_PUZZLE_WIDGET_ID: return "IMAGE_PUZZLE_WIDGET";
		case IMAGE_PUZZLE_PODS_ID: return "IMAGE_PUZZLE_PODS";
		case IMAGE_PUZZLE_PODS_LIT_ID: return "IMAGE_PUZZLE_PODS_LIT";
		case IMAGE_PUZZLE_DOME_ID: return "IMAGE_PUZZLE_DOME";
		case IMAGE_PUZZLE_DOME_MASK_ID: return "IMAGE_PUZZLE_DOME_MASK";
		case IMAGE_PUZZLE_DOME_SLIVER_ID: return "IMAGE_PUZZLE_DOME_SLIVER";
		case IMAGE_PUZZLE_PUZZLE_LIT_ID: return "IMAGE_PUZZLE_PUZZLE_LIT";
		case IMAGE_PUZZLE_THUMB_GEM_ID: return "IMAGE_PUZZLE_THUMB_GEM";
		case IMAGE_PUZZLE_VAPOR1_ID: return "IMAGE_PUZZLE_VAPOR1";
		case IMAGE_PUZZLE_VAPOR2_ID: return "IMAGE_PUZZLE_VAPOR2";
		case IMAGE_PUZZLE_MAP_BUTTON_ID: return "IMAGE_PUZZLE_MAP_BUTTON";
		case IMAGE_PUZZLE_MAP_BUTTON_GLOW_ID: return "IMAGE_PUZZLE_MAP_BUTTON_GLOW";
		case IMAGE_PUZZLE_WARP_BUTTON_ID: return "IMAGE_PUZZLE_WARP_BUTTON";
		case IMAGE_PUZZLE_WARP_GLOW_ID: return "IMAGE_PUZZLE_WARP_GLOW";
		case IMAGE_ENDLESS_WIDGET_ID: return "IMAGE_ENDLESS_WIDGET";
		case IMAGE_ENDLESS_CENTER_1_ID: return "IMAGE_ENDLESS_CENTER_1";
		case IMAGE_ENDLESS_CENTER_2_ID: return "IMAGE_ENDLESS_CENTER_2";
		case IMAGE_ENDLESS_CENTER_3_ID: return "IMAGE_ENDLESS_CENTER_3";
		case IMAGE_ENDLESS_CENTER_4_ID: return "IMAGE_ENDLESS_CENTER_4";
		case IMAGE_ENDLESS_CENTER_5_ID: return "IMAGE_ENDLESS_CENTER_5";
		case IMAGE_ENDLESS_CENTER_6_ID: return "IMAGE_ENDLESS_CENTER_6";
		case IMAGE_ENDLESS_CENTER_7_ID: return "IMAGE_ENDLESS_CENTER_7";
		case IMAGE_ENDLESS_OUTER_1_ID: return "IMAGE_ENDLESS_OUTER_1";
		case IMAGE_ENDLESS_OUTER_2_ID: return "IMAGE_ENDLESS_OUTER_2";
		case IMAGE_ENDLESS_OUTER_3_ID: return "IMAGE_ENDLESS_OUTER_3";
		case IMAGE_ENDLESS_OUTER_4_ID: return "IMAGE_ENDLESS_OUTER_4";
		case IMAGE_ENDLESS_OUTER_5_ID: return "IMAGE_ENDLESS_OUTER_5";
		case IMAGE_ENDLESS_OUTER_6_ID: return "IMAGE_ENDLESS_OUTER_6";
		case IMAGE_ENDLESS_OUTER_7_ID: return "IMAGE_ENDLESS_OUTER_7";
		case IMAGE_ENDLESS_SPARK_1_ID: return "IMAGE_ENDLESS_SPARK_1";
		case IMAGE_ENDLESS_SPARK_2_ID: return "IMAGE_ENDLESS_SPARK_2";
		case IMAGE_ENDLESS_SPARK_3_ID: return "IMAGE_ENDLESS_SPARK_3";
		case IMAGE_ENDLESS_GEM_HILITE_ID: return "IMAGE_ENDLESS_GEM_HILITE";
		case IMAGE_GALAXY_MAP_ID: return "IMAGE_GALAXY_MAP";
		case IMAGE_GALAXY_BUTTON_HILITE_ID: return "IMAGE_GALAXY_BUTTON_HILITE";
		case IMAGE_GALAXY_WARP_BUTTON_ID: return "IMAGE_GALAXY_WARP_BUTTON";
		case IMAGE_GALAXY_CLOSE_BUTTON_ID: return "IMAGE_GALAXY_CLOSE_BUTTON";
		case IMAGE_GALAXY_HEADER_ID: return "IMAGE_GALAXY_HEADER";
		case IMAGE_GALAXY_PLANET_ALPHA_ID: return "IMAGE_GALAXY_PLANET_ALPHA";
		case IMAGE_GALAXY_SUN_MOON_ALPHA_ID: return "IMAGE_GALAXY_SUN_MOON_ALPHA";
		case IMAGE_GALAXY_MOON_ALPHA_ID: return "IMAGE_GALAXY_MOON_ALPHA";
		case IMAGE_GALAXY_PLANET_SELECT_ID: return "IMAGE_GALAXY_PLANET_SELECT";
		case IMAGE_GALAXY_PLANET_COMPLETED_ID: return "IMAGE_GALAXY_PLANET_COMPLETED";
		case IMAGE_GALAXY_SUN_GLOW_ID: return "IMAGE_GALAXY_SUN_GLOW";
		case IMAGE_GALAXY_SUN_SWIRL_ID: return "IMAGE_GALAXY_SUN_SWIRL";
		case IMAGE_GALAXY_QUESTION_ID: return "IMAGE_GALAXY_QUESTION";
		case IMAGE_GALAXY_MOON_SELECT_ID: return "IMAGE_GALAXY_MOON_SELECT";
		case IMAGE_HS_BOTTOM_ID: return "IMAGE_HS_BOTTOM";
		case IMAGE_HS_LEFT_ID: return "IMAGE_HS_LEFT";
		case IMAGE_HS_RIGHT_ID: return "IMAGE_HS_RIGHT";
		case IMAGE_HS_TITLE_ID: return "IMAGE_HS_TITLE";
		case IMAGE_HS_TOP_BUTTON_ID: return "IMAGE_HS_TOP_BUTTON";
		case IMAGE_HS_BACK_TO_MENU_TEXT_ID: return "IMAGE_HS_BACK_TO_MENU_TEXT";
		case IMAGE_HS_BACK_TO_GAME_TEXT_ID: return "IMAGE_HS_BACK_TO_GAME_TEXT";
		case IMAGE_HS_PLAY_AGAIN_TEXT_ID: return "IMAGE_HS_PLAY_AGAIN_TEXT";
		case IMAGE_HS_RESET_SCORES_TEXT_ID: return "IMAGE_HS_RESET_SCORES_TEXT";
		case IMAGE_HS_BUTTON_ROLLOVER_ID: return "IMAGE_HS_BUTTON_ROLLOVER";
		case IMAGE_MAIN_GADGETS_ID: return "IMAGE_MAIN_GADGETS";
		case IMAGE_MAIN_BIG_SELECT_ID: return "IMAGE_MAIN_BIG_SELECT";
		case IMAGE_MAIN_BIG_OVER_ID: return "IMAGE_MAIN_BIG_OVER";
		case IMAGE_MAIN_SMALL_GLOW_ID: return "IMAGE_MAIN_SMALL_GLOW";
		case IMAGE_MAIN_PLAY_GLOW_ID: return "IMAGE_MAIN_PLAY_GLOW";
		case IMAGE_MAIN_BOTTOM_GLOW_ID: return "IMAGE_MAIN_BOTTOM_GLOW";
		case IMAGE_MAIN_CLASSIC_ID: return "IMAGE_MAIN_CLASSIC";
		case IMAGE_MAIN_ACTION_ID: return "IMAGE_MAIN_ACTION";
		case IMAGE_MAIN_PUZZLE_ID: return "IMAGE_MAIN_PUZZLE";
		case IMAGE_MAIN_ENDLESS_ID: return "IMAGE_MAIN_ENDLESS";
		case IMAGE_MAIN_TWILIGHT_ID: return "IMAGE_MAIN_TWILIGHT";
		case IMAGE_MAIN_HYPER_ID: return "IMAGE_MAIN_HYPER";
		case IMAGE_MAIN_COGNITO_ID: return "IMAGE_MAIN_COGNITO";
		case IMAGE_MAIN_FINITY_ID: return "IMAGE_MAIN_FINITY";
		case IMAGE_MAIN_MORE_GAMES_ID: return "IMAGE_MAIN_MORE_GAMES";
		case IMAGE_MAIN_OPTIONS_ID: return "IMAGE_MAIN_OPTIONS";
		case IMAGE_MAIN_SCORES_ID: return "IMAGE_MAIN_SCORES";
		case IMAGE_MAIN_PLAY_ID: return "IMAGE_MAIN_PLAY";
		case IMAGE_MAIN_QUIT_ID: return "IMAGE_MAIN_QUIT";
		case IMAGE_MAIN_CENTER_TEXT_ID: return "IMAGE_MAIN_CENTER_TEXT";
		case IMAGE_MAIN_LIGHT_BIG_ID: return "IMAGE_MAIN_LIGHT_BIG";
		case IMAGE_MAIN_LIGHT_MED_ID: return "IMAGE_MAIN_LIGHT_MED";
		case IMAGE_MAIN_LIGHT_SMALL_ID: return "IMAGE_MAIN_LIGHT_SMALL";
		case IMAGE_MAIN_CENTER_GLOW_ID: return "IMAGE_MAIN_CENTER_GLOW";
		case IMAGE_MAIN_SECRET_GLOW_ID: return "IMAGE_MAIN_SECRET_GLOW";
		case IMAGE_MAIN_SECRET_FRAME_ID: return "IMAGE_MAIN_SECRET_FRAME";
		case IMAGE_MAIN_SECRET_SYMBOL_ID: return "IMAGE_MAIN_SECRET_SYMBOL";
		case FONT_CONTINUUM_MED_33_ID: return "FONT_CONTINUUM_MED_33";
		case FONT_CONTINUUM_MED_33_GLOW_ID: return "FONT_CONTINUUM_MED_33_GLOW";
		case FONT_CONTINUUM_MED_18_ID: return "FONT_CONTINUUM_MED_18";
		case FONT_CONTINUUM_MED_18_GLOW_ID: return "FONT_CONTINUUM_MED_18_GLOW";
		case FONT_VAG_ROUNDED_11_ID: return "FONT_VAG_ROUNDED_11";
		case FONT_CONTINUUM_BOLD_14_NUM_ID: return "FONT_CONTINUUM_BOLD_14_NUM";
		case FONT_CONTINUUM_BOLD_14_NUM_GLOW_ID: return "FONT_CONTINUUM_BOLD_14_NUM_GLOW";
		case FONT_CONTINUUM_BOLD_11_NUM_ID: return "FONT_CONTINUUM_BOLD_11_NUM";
		case FONT_CONTINUUM_BOLD_11_NUM_GLOW_ID: return "FONT_CONTINUUM_BOLD_11_NUM_GLOW";
		case FONT_DIGIT_ID: return "FONT_DIGIT";
		case FONT_BOMB_ID: return "FONT_BOMB";
		case FONT_HUGE_ID: return "FONT_HUGE";
		case FONT_SCORE_ID: return "FONT_SCORE";
		case FONT_DEBUG_ID: return "FONT_DEBUG";
		default: return "";
	}
}

