#ifndef __Res_H__
#define __Res_H__

namespace Sexy
{
	class ResourceManager;
	class Image;
	class Font;

	Image* LoadImageById(ResourceManager *theManager, int theId);
	void ReplaceImageById(ResourceManager *theManager, int theId, Image *theImage);
	bool ExtractResourcesByName(ResourceManager *theManager, const char *theName);

	// DelayLoad_Achievements Resources
	bool ExtractDelayLoad_AchievementsResources(ResourceManager *theMgr);
	extern Image* IMAGE_ACHIEVEMENT_10_ICON_CLOSE_SHAVE;
	extern Image* IMAGE_ACHIEVEMENT_11_ICON_SHOPAHOLIC;
	extern Image* IMAGE_ACHIEVEMENT_12_ICON_SUNFLOWER_WALL_CHOMP;
	extern Image* IMAGE_ACHIEVEMENT_13_ICON_GROUNDED;
	extern Image* IMAGE_ACHIEVEMENT_14_ICON_ZOMBOLOGIST;
	extern Image* IMAGE_ACHIEVEMENT_15_ICON_PENNY_PINCHER;
	extern Image* IMAGE_ACHIEVEMENT_16_ICON_SUNNY_DAYS;
	extern Image* IMAGE_ACHIEVEMENT_17_ICON_POPCORN_PARTY;
	extern Image* IMAGE_ACHIEVEMENT_18_ICON_GOOD_MORNING;
	extern Image* IMAGE_ACHIEVEMENT_19_ICON_NO_FUNGUS_AMONG_US;
	extern Image* IMAGE_ACHIEVEMENT_1_ICON_HOMELAWNSECURITY;
	extern Image* IMAGE_ACHIEVEMENT_20_ICON_BORN_SURVIVOR;
	extern Image* IMAGE_ACHIEVEMENT_21_ICON_ICE_AGE;
	extern Image* IMAGE_ACHIEVEMENT_22_ICON_INDUSTRIOUS;
	extern Image* IMAGE_ACHIEVEMENT_23_ICON_PYRO;
	extern Image* IMAGE_ACHIEVEMENT_24_ICON_LAWN_MOWER_MAN;
	extern Image* IMAGE_ACHIEVEMENT_25_ICON_MEX_WINTER_SPORTS;
	extern Image* IMAGE_ACHIEVEMENT_26_ICON_DEFCORN_5;
	extern Image* IMAGE_ACHIEVEMENT_27_ICON_SQUASHED;
	extern Image* IMAGE_ACHIEVEMENT_28_ICON_SURVIVE_IN_DARK;
	extern Image* IMAGE_ACHIEVEMENT_29_ICON_POOLS_CLOSED;
	extern Image* IMAGE_ACHIEVEMENT_2_ICON_MORTICULTURALIST;
	extern Image* IMAGE_ACHIEVEMENT_30_ICON_WINTER_COMES;
	extern Image* IMAGE_ACHIEVEMENT_31_ICON_SECOND_OPINION;
	extern Image* IMAGE_ACHIEVEMENT_32_ICON_LUCKY_SPIN;
	extern Image* IMAGE_ACHIEVEMENT_33_ICON_CHILLI_FREE;
	extern Image* IMAGE_ACHIEVEMENT_34_ICON_ENLIGHTENED;
	extern Image* IMAGE_ACHIEVEMENT_35_ICON_SULTAN;
	extern Image* IMAGE_ACHIEVEMENT_36_ICON_GREENFINGERS;
	extern Image* IMAGE_ACHIEVEMENT_37_ICON_WALLNUT_ATTACK;
	extern Image* IMAGE_ACHIEVEMENT_38_ICON_BEYOND;
	extern Image* IMAGE_ACHIEVEMENT_39_ICON_SHOOTING_STAR;
	extern Image* IMAGE_ACHIEVEMENT_3_ICON_SMARTY_BRANCHES;
	extern Image* IMAGE_ACHIEVEMENT_40_ICON_THRIFTY;
	extern Image* IMAGE_ACHIEVEMENT_41_ICON_SPROING;
	extern Image* IMAGE_ACHIEVEMENT_42_ICON_SPUDOW;
	extern Image* IMAGE_ACHIEVEMENT_4_ICON_CRASH_OF_THE_TITAN;
	extern Image* IMAGE_ACHIEVEMENT_5_ICON_DONT_PEA_IN_POOL;
	extern Image* IMAGE_ACHIEVEMENT_6_ICON_IMMORTAL;
	extern Image* IMAGE_ACHIEVEMENT_7_ICON_SOIL_PLANTS;
	extern Image* IMAGE_ACHIEVEMENT_8_ICON_ROLL_SOME_HEADS;
	extern Image* IMAGE_ACHIEVEMENT_9_ICON_EXPLODONATOR;
	extern Image* IMAGE_ACHIEVEMENT_TOP_BACKGROUND;

	// DelayLoad_Almanac Resources
	bool ExtractDelayLoad_AlmanacResources(ResourceManager *theMgr);
	extern Image* IMAGE_ALMANAC_GROUNDDAY;
	extern Image* IMAGE_ALMANAC_GROUNDICE;
	extern Image* IMAGE_ALMANAC_GROUNDNIGHT;
	extern Image* IMAGE_ALMANAC_GROUNDNIGHTPOOL;
	extern Image* IMAGE_ALMANAC_GROUNDPOOL;
	extern Image* IMAGE_ALMANAC_GROUNDROOF;
	extern Image* IMAGE_ALMANAC_INDEXBACK;
	extern Image* IMAGE_ALMANAC_PLANTBACK;
	extern Image* IMAGE_ALMANAC_PLANTBLANK;
	extern Image* IMAGE_ALMANAC_PLANTCARD;
	extern Image* IMAGE_ALMANAC_ZOMBIEBACK;
	extern Image* IMAGE_ALMANAC_ZOMBIEBLANK;
	extern Image* IMAGE_ALMANAC_ZOMBIECARD;
	extern Image* IMAGE_ALMANAC_ZOMBIEWINDOW2;
	extern Image* IMAGE_ALMANAC_ZOMBIEWINDOW;

	// DelayLoad_AwardScreen Resources
	bool ExtractDelayLoad_AwardScreenResources(ResourceManager *theMgr);
	extern Image* IMAGE_AWARDSCREEN_BACK;

	// DelayLoad_Background1 Resources
	bool ExtractDelayLoad_Background1Resources(ResourceManager *theMgr);
	extern Image* IMAGE_BACKGROUND1;
	extern Image* IMAGE_BACKGROUND1_COVER;
	extern Image* IMAGE_BACKGROUND1_GAMEOVER_INTERIOR_OVERLAY;
	extern Image* IMAGE_BACKGROUND1_GAMEOVER_MASK;

	// DelayLoad_Background2 Resources
	bool ExtractDelayLoad_Background2Resources(ResourceManager *theMgr);
	extern Image* IMAGE_BACKGROUND2;
	extern Image* IMAGE_BACKGROUND2_COVER;
	extern Image* IMAGE_BACKGROUND2_GAMEOVER_INTERIOR_OVERLAY;
	extern Image* IMAGE_BACKGROUND2_GAMEOVER_MASK;

	// DelayLoad_Background3 Resources
	bool ExtractDelayLoad_Background3Resources(ResourceManager *theMgr);
	extern Image* IMAGE_BACKGROUND3;
	extern Image* IMAGE_BACKGROUND3_COVER;
	extern Image* IMAGE_BACKGROUND3_GAMEOVER_INTERIOR_OVERLAY;
	extern Image* IMAGE_BACKGROUND3_GAMEOVER_MASK;

	// DelayLoad_Background4 Resources
	bool ExtractDelayLoad_Background4Resources(ResourceManager *theMgr);
	extern Image* IMAGE_BACKGROUND4;
	extern Image* IMAGE_BACKGROUND4_COVER;
	extern Image* IMAGE_BACKGROUND4_GAMEOVER_INTERIOR_OVERLAY;
	extern Image* IMAGE_BACKGROUND4_GAMEOVER_MASK;
	extern Image* IMAGE_FOG;
	extern Image* IMAGE_FOG_SOFTWARE;

	// DelayLoad_Background5 Resources
	bool ExtractDelayLoad_Background5Resources(ResourceManager *theMgr);
	extern Image* IMAGE_BACKGROUND5;
	extern Image* IMAGE_BACKGROUND5_GAMEOVER_MASK;
	extern Image* IMAGE_ROOF_POLE;
	extern Image* IMAGE_ROOF_TREE;

	// DelayLoad_Background6 Resources
	bool ExtractDelayLoad_Background6Resources(ResourceManager *theMgr);
	extern Image* IMAGE_BACKGROUND6BOSS;
	extern Image* IMAGE_BACKGROUND6_GAMEOVER_MASK;

	// DelayLoad_BackgroundUnsodded Resources
	bool ExtractDelayLoad_BackgroundUnsoddedResources(ResourceManager *theMgr);
	extern Image* IMAGE_BACKGROUND1UNSODDED;
	extern Image* IMAGE_SOD1ROW;
	extern Image* IMAGE_SOD3ROW;

	// DelayLoad_Credits Resources
	bool ExtractDelayLoad_CreditsResources(ResourceManager *theMgr);
	extern Image* IMAGE_CREDITS_PLAYBUTTON;
	extern Image* IMAGE_CREDITS_ZOMBIENOTE;
	extern Image* IMAGE_REANIM_CREDITS_DISCOLIGHTS;
	extern Image* IMAGE_REANIM_CREDITS_FOGMACHINE;
	extern Image* IMAGE_REANIM_SUNFLOWER_HEAD_SING1;
	extern Image* IMAGE_REANIM_SUNFLOWER_HEAD_SING2;
	extern Image* IMAGE_REANIM_SUNFLOWER_HEAD_SING3;
	extern Image* IMAGE_REANIM_SUNFLOWER_HEAD_SING4;
	extern Image* IMAGE_REANIM_SUNFLOWER_HEAD_SING5;
	extern Image* IMAGE_REANIM_SUNFLOWER_HEAD_WINK;

	// DelayLoad_GreenHouseGarden Resources
	bool ExtractDelayLoad_GreenHouseGardenResources(ResourceManager *theMgr);
	extern Image* IMAGE_BACKGROUND_GREENHOUSE;

	// DelayLoad_GreenHouseOverlay Resources
	bool ExtractDelayLoad_GreenHouseOverlayResources(ResourceManager *theMgr);
	extern Image* IMAGE_BACKGROUND_GREENHOUSE_OVERLAY;

	// DelayLoad_MushroomGarden Resources
	bool ExtractDelayLoad_MushroomGardenResources(ResourceManager *theMgr);
	extern Image* IMAGE_BACKGROUND_MUSHROOMGARDEN;

	// DelayLoad_Store Resources
	bool ExtractDelayLoad_StoreResources(ResourceManager *theMgr);
	extern Image* IMAGE_STORESEEDPACK_CATTAIL;
	extern Image* IMAGE_STORESEEDPACK_COBCANNON;
	extern Image* IMAGE_STORESEEDPACK_DOUBLESUNFLOWER;
	extern Image* IMAGE_STORESEEDPACK_FROZENWATERMELON;
	extern Image* IMAGE_STORESEEDPACK_GLOOMSHROOM;
	extern Image* IMAGE_STORESEEDPACK_GOLDMAGNET;
	extern Image* IMAGE_STORESEEDPACK_IMITATER;
	extern Image* IMAGE_STORESEEDPACK_REPEATER;
	extern Image* IMAGE_STORESEEDPACK_SPIKEROCK;
	extern Image* IMAGE_STORE_BACKGROUND;
	extern Image* IMAGE_STORE_BACKGROUNDNIGHT;
	extern Image* IMAGE_STORE_CAR;
	extern Image* IMAGE_STORE_CARCLOSED;
	extern Image* IMAGE_STORE_CARCLOSED_NIGHT;
	extern Image* IMAGE_STORE_CAR_LICENSE0;
	extern Image* IMAGE_STORE_CAR_LICENSE10;
	extern Image* IMAGE_STORE_CAR_LICENSE11;
	extern Image* IMAGE_STORE_CAR_LICENSE1;
	extern Image* IMAGE_STORE_CAR_LICENSE2;
	extern Image* IMAGE_STORE_CAR_LICENSE3;
	extern Image* IMAGE_STORE_CAR_LICENSE4;
	extern Image* IMAGE_STORE_CAR_LICENSE5;
	extern Image* IMAGE_STORE_CAR_LICENSE6;
	extern Image* IMAGE_STORE_CAR_LICENSE7;
	extern Image* IMAGE_STORE_CAR_LICENSE8;
	extern Image* IMAGE_STORE_CAR_LICENSE9;
	extern Image* IMAGE_STORE_CAR_NIGHT;
	extern Image* IMAGE_STORE_COMING_SOON;
	extern Image* IMAGE_STORE_EXTRA_SLOT;
	extern Image* IMAGE_STORE_FIRSTAIDWALLNUTICON;
	extern Image* IMAGE_STORE_HATCHBACKOPEN;
	extern Image* IMAGE_STORE_MAINMENUBUTTON;
	extern Image* IMAGE_STORE_MAINMENUBUTTONDOWN;
	extern Image* IMAGE_STORE_MAINMENUBUTTONHIGHLIGHT;
	extern Image* IMAGE_STORE_NEXTBUTTON;
	extern Image* IMAGE_STORE_NEXTBUTTONDISABLED;
	extern Image* IMAGE_STORE_NEXTBUTTONHIGHLIGHT;
	extern Image* IMAGE_STORE_PACKETUPGRADE;
	extern Image* IMAGE_STORE_PREVBUTTON;
	extern Image* IMAGE_STORE_PREVBUTTONDISABLED;
	extern Image* IMAGE_STORE_PREVBUTTONHIGHLIGHT;
	extern Image* IMAGE_STORE_PRICETAG;
	extern Image* IMAGE_STORE_PVZICON;
	extern Image* IMAGE_STORE_SIGN;
	extern Image* IMAGE_STORE_SOLD_OUT;
	extern Image* IMAGE_STORE_TOUCH_CONTINUEBUTTON;
	extern Image* IMAGE_STORE_TOUCH_CONTINUEBUTTONDOWN;
	extern Image* IMAGE_STORE_TOUCH_MAINMENUBUTTON;
	extern Image* IMAGE_STORE_TOUCH_MAINMENUBUTTONDOWN;
	extern Image* IMAGE_STORE_TOUCH_NEXTBUTTON;
	extern Image* IMAGE_STORE_TOUCH_NEXTBUTTONHIGHLIGHT;
	extern Image* IMAGE_STORE_TOUCH_PREVBUTTON;
	extern Image* IMAGE_STORE_TOUCH_PREVBUTTONHIGHLIGHT;

	// DelayLoad_Zombatar Resources
	bool ExtractDelayLoad_ZombatarResources(ResourceManager *theMgr);
	extern Image* IMAGE_ZOMBATAR_ACCEPT_BUTTON;
	extern Image* IMAGE_ZOMBATAR_ACCEPT_BUTTON_HIGHLIGHT;
	extern Image* IMAGE_ZOMBATAR_ACCESSORY_10;
	extern Image* IMAGE_ZOMBATAR_ACCESSORY_11;
	extern Image* IMAGE_ZOMBATAR_ACCESSORY_12;
	extern Image* IMAGE_ZOMBATAR_ACCESSORY_13;
	extern Image* IMAGE_ZOMBATAR_ACCESSORY_14;
	extern Image* IMAGE_ZOMBATAR_ACCESSORY_15;
	extern Image* IMAGE_ZOMBATAR_ACCESSORY_16;
	extern Image* IMAGE_ZOMBATAR_ACCESSORY_1;
	extern Image* IMAGE_ZOMBATAR_ACCESSORY_2;
	extern Image* IMAGE_ZOMBATAR_ACCESSORY_3;
	extern Image* IMAGE_ZOMBATAR_ACCESSORY_4;
	extern Image* IMAGE_ZOMBATAR_ACCESSORY_5;
	extern Image* IMAGE_ZOMBATAR_ACCESSORY_6;
	extern Image* IMAGE_ZOMBATAR_ACCESSORY_7;
	extern Image* IMAGE_ZOMBATAR_ACCESSORY_8;
	extern Image* IMAGE_ZOMBATAR_ACCESSORY_9;
	extern Image* IMAGE_ZOMBATAR_ACCESSORY_BG;
	extern Image* IMAGE_ZOMBATAR_ACCESSORY_BG_HIGHLIGHT;
	extern Image* IMAGE_ZOMBATAR_ACCESSORY_BG_NONE;
	extern Image* IMAGE_ZOMBATAR_ACCESSORY_BUTTON;
	extern Image* IMAGE_ZOMBATAR_ACCESSORY_BUTTON_HIGHLIGHT;
	extern Image* IMAGE_ZOMBATAR_ACCESSORY_BUTTON_OVER;
	extern Image* IMAGE_ZOMBATAR_BACKDROPS_BUTTON;
	extern Image* IMAGE_ZOMBATAR_BACKDROPS_BUTTON_HIGHLIGHT;
	extern Image* IMAGE_ZOMBATAR_BACKDROPS_BUTTON_OVER;
	extern Image* IMAGE_ZOMBATAR_BACKGROUND_BLANK;
	extern Image* IMAGE_ZOMBATAR_BACKGROUND_CRAZYDAVE;
	extern Image* IMAGE_ZOMBATAR_BACKGROUND_MENU;
	extern Image* IMAGE_ZOMBATAR_BACKGROUND_MENU_DOS;
	extern Image* IMAGE_ZOMBATAR_BACKGROUND_ROOF;
	extern Image* IMAGE_ZOMBATAR_BACK_BUTTON;
	extern Image* IMAGE_ZOMBATAR_BACK_BUTTON_HIGHLIGHT;
	extern Image* IMAGE_ZOMBATAR_BEGIN_BUTTON;
	extern Image* IMAGE_ZOMBATAR_BEGIN_BUTTON_HIGHLIGHT;
	extern Image* IMAGE_ZOMBATAR_CLOTHES_10;
	extern Image* IMAGE_ZOMBATAR_CLOTHES_11;
	extern Image* IMAGE_ZOMBATAR_CLOTHES_12;
	extern Image* IMAGE_ZOMBATAR_CLOTHES_1;
	extern Image* IMAGE_ZOMBATAR_CLOTHES_2;
	extern Image* IMAGE_ZOMBATAR_CLOTHES_3;
	extern Image* IMAGE_ZOMBATAR_CLOTHES_4;
	extern Image* IMAGE_ZOMBATAR_CLOTHES_5;
	extern Image* IMAGE_ZOMBATAR_CLOTHES_6;
	extern Image* IMAGE_ZOMBATAR_CLOTHES_7;
	extern Image* IMAGE_ZOMBATAR_CLOTHES_8;
	extern Image* IMAGE_ZOMBATAR_CLOTHES_9;
	extern Image* IMAGE_ZOMBATAR_CLOTHES_BUTTON;
	extern Image* IMAGE_ZOMBATAR_CLOTHES_BUTTON_HIGHLIGHT;
	extern Image* IMAGE_ZOMBATAR_CLOTHES_BUTTON_OVER;
	extern Image* IMAGE_ZOMBATAR_COLORPICKER;
	extern Image* IMAGE_ZOMBATAR_COLORPICKER_HIGHLIGHT;
	extern Image* IMAGE_ZOMBATAR_COLORPICKER_NONE;
	extern Image* IMAGE_ZOMBATAR_COLORS_BG;
	extern Image* IMAGE_ZOMBATAR_COLORS_BG_SMALL;
	extern Image* IMAGE_ZOMBATAR_DISPLAY_WINDOW;
	extern Image* IMAGE_ZOMBATAR_EYEWEAR_10;
	extern Image* IMAGE_ZOMBATAR_EYEWEAR_10_MASK;
	extern Image* IMAGE_ZOMBATAR_EYEWEAR_11;
	extern Image* IMAGE_ZOMBATAR_EYEWEAR_11_MASK;
	extern Image* IMAGE_ZOMBATAR_EYEWEAR_12;
	extern Image* IMAGE_ZOMBATAR_EYEWEAR_12_MASK;
	extern Image* IMAGE_ZOMBATAR_EYEWEAR_13;
	extern Image* IMAGE_ZOMBATAR_EYEWEAR_14;
	extern Image* IMAGE_ZOMBATAR_EYEWEAR_15;
	extern Image* IMAGE_ZOMBATAR_EYEWEAR_16;
	extern Image* IMAGE_ZOMBATAR_EYEWEAR_1;
	extern Image* IMAGE_ZOMBATAR_EYEWEAR_1_MASK;
	extern Image* IMAGE_ZOMBATAR_EYEWEAR_2;
	extern Image* IMAGE_ZOMBATAR_EYEWEAR_2_MASK;
	extern Image* IMAGE_ZOMBATAR_EYEWEAR_3;
	extern Image* IMAGE_ZOMBATAR_EYEWEAR_3_MASK;
	extern Image* IMAGE_ZOMBATAR_EYEWEAR_4;
	extern Image* IMAGE_ZOMBATAR_EYEWEAR_4_MASK;
	extern Image* IMAGE_ZOMBATAR_EYEWEAR_5;
	extern Image* IMAGE_ZOMBATAR_EYEWEAR_5_MASK;
	extern Image* IMAGE_ZOMBATAR_EYEWEAR_6;
	extern Image* IMAGE_ZOMBATAR_EYEWEAR_6_MASK;
	extern Image* IMAGE_ZOMBATAR_EYEWEAR_7;
	extern Image* IMAGE_ZOMBATAR_EYEWEAR_7_MASK;
	extern Image* IMAGE_ZOMBATAR_EYEWEAR_8;
	extern Image* IMAGE_ZOMBATAR_EYEWEAR_8_MASK;
	extern Image* IMAGE_ZOMBATAR_EYEWEAR_9;
	extern Image* IMAGE_ZOMBATAR_EYEWEAR_9_MASK;
	extern Image* IMAGE_ZOMBATAR_EYEWEAR_BUTTON;
	extern Image* IMAGE_ZOMBATAR_EYEWEAR_BUTTON_HIGHLIGHT;
	extern Image* IMAGE_ZOMBATAR_EYEWEAR_BUTTON_OVER;
	extern Image* IMAGE_ZOMBATAR_FACIALHAIR_10;
	extern Image* IMAGE_ZOMBATAR_FACIALHAIR_10_MASK;
	extern Image* IMAGE_ZOMBATAR_FACIALHAIR_11;
	extern Image* IMAGE_ZOMBATAR_FACIALHAIR_11_MASK;
	extern Image* IMAGE_ZOMBATAR_FACIALHAIR_12;
	extern Image* IMAGE_ZOMBATAR_FACIALHAIR_12_MASK;
	extern Image* IMAGE_ZOMBATAR_FACIALHAIR_13;
	extern Image* IMAGE_ZOMBATAR_FACIALHAIR_14;
	extern Image* IMAGE_ZOMBATAR_FACIALHAIR_14_MASK;
	extern Image* IMAGE_ZOMBATAR_FACIALHAIR_15;
	extern Image* IMAGE_ZOMBATAR_FACIALHAIR_15_MASK;
	extern Image* IMAGE_ZOMBATAR_FACIALHAIR_16;
	extern Image* IMAGE_ZOMBATAR_FACIALHAIR_16_MASK;
	extern Image* IMAGE_ZOMBATAR_FACIALHAIR_17;
	extern Image* IMAGE_ZOMBATAR_FACIALHAIR_18;
	extern Image* IMAGE_ZOMBATAR_FACIALHAIR_18_MASK;
	extern Image* IMAGE_ZOMBATAR_FACIALHAIR_19;
	extern Image* IMAGE_ZOMBATAR_FACIALHAIR_1;
	extern Image* IMAGE_ZOMBATAR_FACIALHAIR_1_MASK;
	extern Image* IMAGE_ZOMBATAR_FACIALHAIR_20;
	extern Image* IMAGE_ZOMBATAR_FACIALHAIR_21;
	extern Image* IMAGE_ZOMBATAR_FACIALHAIR_21_MASK;
	extern Image* IMAGE_ZOMBATAR_FACIALHAIR_22;
	extern Image* IMAGE_ZOMBATAR_FACIALHAIR_22_MASK;
	extern Image* IMAGE_ZOMBATAR_FACIALHAIR_23;
	extern Image* IMAGE_ZOMBATAR_FACIALHAIR_23_MASK;
	extern Image* IMAGE_ZOMBATAR_FACIALHAIR_24;
	extern Image* IMAGE_ZOMBATAR_FACIALHAIR_24_MASK;
	extern Image* IMAGE_ZOMBATAR_FACIALHAIR_2;
	extern Image* IMAGE_ZOMBATAR_FACIALHAIR_3;
	extern Image* IMAGE_ZOMBATAR_FACIALHAIR_4;
	extern Image* IMAGE_ZOMBATAR_FACIALHAIR_4_MASK;
	extern Image* IMAGE_ZOMBATAR_FACIALHAIR_5;
	extern Image* IMAGE_ZOMBATAR_FACIALHAIR_6;
	extern Image* IMAGE_ZOMBATAR_FACIALHAIR_7;
	extern Image* IMAGE_ZOMBATAR_FACIALHAIR_8;
	extern Image* IMAGE_ZOMBATAR_FACIALHAIR_8_MASK;
	extern Image* IMAGE_ZOMBATAR_FACIALHAIR_9;
	extern Image* IMAGE_ZOMBATAR_FACIALHAIR_9_MASK;
	extern Image* IMAGE_ZOMBATAR_FACIAL_HAIR_BUTTON;
	extern Image* IMAGE_ZOMBATAR_FACIAL_HAIR_BUTTON_HIGHLIGHT;
	extern Image* IMAGE_ZOMBATAR_FACIAL_HAIR_BUTTON_OVER;
	extern Image* IMAGE_ZOMBATAR_FINISHED_BUTTON;
	extern Image* IMAGE_ZOMBATAR_FINISHED_BUTTON_HIGHLIGHT;
	extern Image* IMAGE_ZOMBATAR_HAIR_10;
	extern Image* IMAGE_ZOMBATAR_HAIR_11;
	extern Image* IMAGE_ZOMBATAR_HAIR_11_MASK;
	extern Image* IMAGE_ZOMBATAR_HAIR_12;
	extern Image* IMAGE_ZOMBATAR_HAIR_12_MASK;
	extern Image* IMAGE_ZOMBATAR_HAIR_13;
	extern Image* IMAGE_ZOMBATAR_HAIR_13_MASK;
	extern Image* IMAGE_ZOMBATAR_HAIR_14;
	extern Image* IMAGE_ZOMBATAR_HAIR_14_MASK;
	extern Image* IMAGE_ZOMBATAR_HAIR_15;
	extern Image* IMAGE_ZOMBATAR_HAIR_15_MASK;
	extern Image* IMAGE_ZOMBATAR_HAIR_16;
	extern Image* IMAGE_ZOMBATAR_HAIR_1;
	extern Image* IMAGE_ZOMBATAR_HAIR_1_MASK;
	extern Image* IMAGE_ZOMBATAR_HAIR_2;
	extern Image* IMAGE_ZOMBATAR_HAIR_2_MASK;
	extern Image* IMAGE_ZOMBATAR_HAIR_3;
	extern Image* IMAGE_ZOMBATAR_HAIR_4;
	extern Image* IMAGE_ZOMBATAR_HAIR_5;
	extern Image* IMAGE_ZOMBATAR_HAIR_6;
	extern Image* IMAGE_ZOMBATAR_HAIR_7;
	extern Image* IMAGE_ZOMBATAR_HAIR_8;
	extern Image* IMAGE_ZOMBATAR_HAIR_9;
	extern Image* IMAGE_ZOMBATAR_HAIR_BUTTON;
	extern Image* IMAGE_ZOMBATAR_HAIR_BUTTON_HIGHLIGHT;
	extern Image* IMAGE_ZOMBATAR_HAIR_BUTTON_OVER;
	extern Image* IMAGE_ZOMBATAR_HATS_10;
	extern Image* IMAGE_ZOMBATAR_HATS_11;
	extern Image* IMAGE_ZOMBATAR_HATS_11_MASK;
	extern Image* IMAGE_ZOMBATAR_HATS_12;
	extern Image* IMAGE_ZOMBATAR_HATS_13;
	extern Image* IMAGE_ZOMBATAR_HATS_14;
	extern Image* IMAGE_ZOMBATAR_HATS_1;
	extern Image* IMAGE_ZOMBATAR_HATS_1_MASK;
	extern Image* IMAGE_ZOMBATAR_HATS_2;
	extern Image* IMAGE_ZOMBATAR_HATS_3;
	extern Image* IMAGE_ZOMBATAR_HATS_3_MASK;
	extern Image* IMAGE_ZOMBATAR_HATS_4;
	extern Image* IMAGE_ZOMBATAR_HATS_5;
	extern Image* IMAGE_ZOMBATAR_HATS_6;
	extern Image* IMAGE_ZOMBATAR_HATS_6_MASK;
	extern Image* IMAGE_ZOMBATAR_HATS_7;
	extern Image* IMAGE_ZOMBATAR_HATS_7_MASK;
	extern Image* IMAGE_ZOMBATAR_HATS_8;
	extern Image* IMAGE_ZOMBATAR_HATS_8_MASK;
	extern Image* IMAGE_ZOMBATAR_HATS_9;
	extern Image* IMAGE_ZOMBATAR_HATS_9_MASK;
	extern Image* IMAGE_ZOMBATAR_HATS_BUTTON;
	extern Image* IMAGE_ZOMBATAR_HATS_BUTTON_HIGHLIGHT;
	extern Image* IMAGE_ZOMBATAR_HATS_BUTTON_OVER;
	extern Image* IMAGE_ZOMBATAR_LOGO;
	extern Image* IMAGE_ZOMBATAR_MAINMENUBACK_HIGHLIGHT;
	extern Image* IMAGE_ZOMBATAR_MAIN_BG;
	extern Image* IMAGE_ZOMBATAR_NEWZOMBIE_BUTTON;
	extern Image* IMAGE_ZOMBATAR_NEWZOMBIE_BUTTON_HIGHLIGHT;
	extern Image* IMAGE_ZOMBATAR_NEXT_BUTTON;
	extern Image* IMAGE_ZOMBATAR_NEXT_BUTTON_HIGHLIGHT;
	extern Image* IMAGE_ZOMBATAR_PREV_BUTTON;
	extern Image* IMAGE_ZOMBATAR_PREV_BUTTON_HIGHLIGHT;
	extern Image* IMAGE_ZOMBATAR_SKIN_BUTTON;
	extern Image* IMAGE_ZOMBATAR_SKIN_BUTTON_HIGHLIGHT;
	extern Image* IMAGE_ZOMBATAR_TIDBITS_10;
	extern Image* IMAGE_ZOMBATAR_TIDBITS_11;
	extern Image* IMAGE_ZOMBATAR_TIDBITS_12;
	extern Image* IMAGE_ZOMBATAR_TIDBITS_13;
	extern Image* IMAGE_ZOMBATAR_TIDBITS_14;
	extern Image* IMAGE_ZOMBATAR_TIDBITS_1;
	extern Image* IMAGE_ZOMBATAR_TIDBITS_2;
	extern Image* IMAGE_ZOMBATAR_TIDBITS_3;
	extern Image* IMAGE_ZOMBATAR_TIDBITS_4;
	extern Image* IMAGE_ZOMBATAR_TIDBITS_5;
	extern Image* IMAGE_ZOMBATAR_TIDBITS_6;
	extern Image* IMAGE_ZOMBATAR_TIDBITS_7;
	extern Image* IMAGE_ZOMBATAR_TIDBITS_8;
	extern Image* IMAGE_ZOMBATAR_TIDBITS_9;
	extern Image* IMAGE_ZOMBATAR_TIDBITS_BUTTON;
	extern Image* IMAGE_ZOMBATAR_TIDBITS_BUTTON_HIGHLIGHT;
	extern Image* IMAGE_ZOMBATAR_TIDBITS_BUTTON_OVER;
	extern Image* IMAGE_ZOMBATAR_TOS_ARROW;
	extern Image* IMAGE_ZOMBATAR_TOS_SLIDER;
	extern Image* IMAGE_ZOMBATAR_TOS_SLIDER_THUMB;
	extern Image* IMAGE_ZOMBATAR_TRIPTYCH;
	extern Image* IMAGE_ZOMBATAR_VIEW_BUTTON;
	extern Image* IMAGE_ZOMBATAR_VIEW_BUTTON_HIGHLIGHT;
	extern Image* IMAGE_ZOMBATAR_WIDGET_BG;
	extern Image* IMAGE_ZOMBATAR_WIDGET_INNER_BG;
	extern Image* IMAGE_ZOMBATAR_ZOMBIE_BLANK;
	extern Image* IMAGE_ZOMBATAR_ZOMBIE_BLANK_SKIN;

	// DelayLoad_ZombieFinalNote Resources
	bool ExtractDelayLoad_ZombieFinalNoteResources(ResourceManager *theMgr);
	extern Image* IMAGE_ZOMBIE_FINAL_NOTE;

	// DelayLoad_ZombieNote Resources
	bool ExtractDelayLoad_ZombieNoteResources(ResourceManager *theMgr);
	extern Image* IMAGE_ZOMBIE_NOTE;

	// DelayLoad_ZombieNote1 Resources
	bool ExtractDelayLoad_ZombieNote1Resources(ResourceManager *theMgr);
	extern Image* IMAGE_ZOMBIE_NOTE1;

	// DelayLoad_ZombieNote2 Resources
	bool ExtractDelayLoad_ZombieNote2Resources(ResourceManager *theMgr);
	extern Image* IMAGE_ZOMBIE_NOTE2;

	// DelayLoad_ZombieNote3 Resources
	bool ExtractDelayLoad_ZombieNote3Resources(ResourceManager *theMgr);
	extern Image* IMAGE_ZOMBIE_NOTE3;

	// DelayLoad_ZombieNote4 Resources
	bool ExtractDelayLoad_ZombieNote4Resources(ResourceManager *theMgr);
	extern Image* IMAGE_ZOMBIE_NOTE4;

	// DelayLoad_ZombieNoteHelp Resources
	bool ExtractDelayLoad_ZombieNoteHelpResources(ResourceManager *theMgr);
	extern Image* IMAGE_ZOMBIE_NOTE_HELP;

	// DelayLoad_Zombiquarium Resources
	bool ExtractDelayLoad_ZombiquariumResources(ResourceManager *theMgr);
	extern Image* IMAGE_AQUARIUM1;
	extern Image* IMAGE_WAVECENTER;
	extern Image* IMAGE_WAVESIDE;

	// Init Resources
	bool ExtractInitResources(ResourceManager *theMgr);
	extern Image* IMAGE_BLANK;
	extern Image* IMAGE_NO_GAMERPIC;

	// LoaderBar Resources
	bool ExtractLoaderBarResources(ResourceManager *theMgr);
	extern Font* FONT_BRIANNETOD16;
	extern Font* FONT_DWARVENTODCRAFT24;
	extern Image* IMAGE_LOADBAR_DIRT;
	extern Image* IMAGE_LOADBAR_GRASS;
	extern Image* IMAGE_PVZ_LOGO;
	extern Image* IMAGE_REANIM_SODROLLCAP;
	extern Image* IMAGE_TITLESCREEN;
	extern Image* IMAGE_TITLESCREEN_BALL;
	extern Image* IMAGE_TITLESCREEN_GLOW;
	extern int SOUND_BUTTONCLICK;
	extern int SOUND_LOADINGBAR_FLOWER;
	extern int SOUND_LOADINGBAR_ZOMBIE;

	// LoadingFonts Resources
	bool ExtractLoadingFontsResources(ResourceManager *theMgr);
	extern Font* FONT_BRIANNETOD12;
	extern Font* FONT_BRIANNETOD32;
	extern Font* FONT_BRIANNETOD32BLACK;
	extern Font* FONT_CONTINUUMBOLD14;
	extern Font* FONT_CONTINUUMBOLD14OUTLINE;
	extern Font* FONT_DWARVENTODCRAFT12;
	extern Font* FONT_DWARVENTODCRAFT18;
	extern Font* FONT_HOUSEOFTERROR16;
	extern Font* FONT_HOUSEOFTERROR20;
	extern Font* FONT_HOUSEOFTERROR28;

	// LoadingImages Resources
	bool ExtractLoadingImagesResources(ResourceManager *theMgr);
	extern Image* IMAGE_ALMANAC;
	extern Image* IMAGE_ALMANAC_BACKBUTTON;
	extern Image* IMAGE_ALMANAC_CLOSEBUTTON;
	extern Image* IMAGE_ALMANAC_CLOSEBUTTONHIGHLIGHT;
	extern Image* IMAGE_ALMANAC_IMITATER;
	extern Image* IMAGE_ALMANAC_INDEXBUTTON;
	extern Image* IMAGE_ALMANAC_INDEXBUTTONHIGHLIGHT;
	extern Image* IMAGE_ALMANAC_PAPER;
	extern Image* IMAGE_ALMANAC_PLANTS_BOTTOMGRADIENT;
	extern Image* IMAGE_ALMANAC_PLANTS_TOPGRADIENT;
	extern Image* IMAGE_ALMANAC_ROUNDED_OUTLINE;
	extern Image* IMAGE_AWARDPICKUPGLOW;
	extern Image* IMAGE_BEGHOULED_TWIST_OVERLAY;
	extern Image* IMAGE_BRAIN;
	extern Image* IMAGE_BUG_SPRAY;
	extern Image* IMAGE_BUNGEECORD;
	extern Image* IMAGE_BUNGEETARGET;
	extern Image* IMAGE_BUTTER_ICON;
	extern Image* IMAGE_BUTTON_DOWN_LEFT;
	extern Image* IMAGE_BUTTON_DOWN_MIDDLE;
	extern Image* IMAGE_BUTTON_DOWN_RIGHT;
	extern Image* IMAGE_BUTTON_GLOW;
	extern Image* IMAGE_BUTTON_GLOW_LEFT;
	extern Image* IMAGE_BUTTON_GLOW_MIDDLE;
	extern Image* IMAGE_BUTTON_GLOW_RIGHT;
	extern Image* IMAGE_BUTTON_LEFT;
	extern Image* IMAGE_BUTTON_MIDDLE;
	extern Image* IMAGE_BUTTON_RIGHT;
	extern Image* IMAGE_CARKEYS;
	extern Image* IMAGE_CHALLENGE_BACKGROUND;
	extern Image* IMAGE_CHALLENGE_BLANK;
	extern Image* IMAGE_CHALLENGE_NAME_BACK;
	extern Image* IMAGE_CHALLENGE_THUMBNAILS;
	extern Image* IMAGE_CHALLENGE_WINDOW;
	extern Image* IMAGE_CHALLENGE_WINDOW_HIGHLIGHT;
	extern Image* IMAGE_CHOCOLATE;
	extern Image* IMAGE_COBCANNON_POPCORN;
	extern Image* IMAGE_COBCANNON_TARGET;
	extern Image* IMAGE_COBCANNON_TARGET_1;
	extern Image* IMAGE_COBCANNON_TARGET_2;
	extern Image* IMAGE_COBCANNON_TARGET_3;
	extern Image* IMAGE_COBCANNON_TARGET_4;
	extern Image* IMAGE_COINBANK;
	extern Image* IMAGE_CONVEYORBELT;
	extern Image* IMAGE_CONVEYORBELT_BACKDROP;
	extern Image* IMAGE_CONVEYORBELT_BACKDROP_COOP;
	extern Image* IMAGE_CONVEYORBELT_COOP;
	extern Image* IMAGE_COOP_SUN_HIGHLIGHT_1;
	extern Image* IMAGE_COOP_SUN_HIGHLIGHT_2;
	extern Image* IMAGE_CRATER;
	extern Image* IMAGE_CRATER_FADING;
	extern Image* IMAGE_CRATER_ROOF_CENTER;
	extern Image* IMAGE_CRATER_ROOF_LEFT;
	extern Image* IMAGE_CRATER_WATER_DAY;
	extern Image* IMAGE_CRATER_WATER_NIGHT;
	extern Image* IMAGE_CROW_BUBBLE;
	extern Image* IMAGE_CURSOR_ARROW_P1;
	extern Image* IMAGE_CURSOR_ARROW_P2;
	extern Image* IMAGE_CURSOR_FLOWER;
	extern Image* IMAGE_CURSOR_P1_TEXT;
	extern Image* IMAGE_CURSOR_P2_TEXT;
	extern Image* IMAGE_CURSOR_SKULL;
	extern Image* IMAGE_DIALOG_BIGBOTTOMLEFT;
	extern Image* IMAGE_DIALOG_BIGBOTTOMMIDDLE;
	extern Image* IMAGE_DIALOG_BIGBOTTOMRIGHT;
	extern Image* IMAGE_DIALOG_BOTTOMLEFT;
	extern Image* IMAGE_DIALOG_BOTTOMMIDDLE;
	extern Image* IMAGE_DIALOG_BOTTOMRIGHT;
	extern Image* IMAGE_DIALOG_CENTERLEFT;
	extern Image* IMAGE_DIALOG_CENTERMIDDLE;
	extern Image* IMAGE_DIALOG_CENTERRIGHT;
	extern Image* IMAGE_DIALOG_HEADER;
	extern Image* IMAGE_DIALOG_TOPLEFT;
	extern Image* IMAGE_DIALOG_TOPMIDDLE;
	extern Image* IMAGE_DIALOG_TOPRIGHT;
	extern Image* IMAGE_DIRTBIG;
	extern Image* IMAGE_DIRTSMALL;
	extern Image* IMAGE_DLG_SELECTORFRAME;
	extern Image* IMAGE_DOOMSHROOM_EXPLOSION_BASE;
	extern Image* IMAGE_DUST_PUFFS;
	extern Image* IMAGE_EDITBOX;
	extern Image* IMAGE_FERTILIZER;
	extern Image* IMAGE_FLAGMETER;
	extern Image* IMAGE_FLAGMETERLEVELPROGRESS;
	extern Image* IMAGE_FLAGMETERPARTS;
	extern Image* IMAGE_GAMEPAD_CURSOR_ARROWS;
	extern Image* IMAGE_GAMEPAD_CURSOR_ARROWS_SHADOW;
	extern Image* IMAGE_GAMEPAD_CURSOR_FRAME;
	extern Image* IMAGE_GAMEPAD_CURSOR_FRAME_BLUE;
	extern Image* IMAGE_GAMEPAD_CURSOR_FRAME_SHADOW;
	extern Image* IMAGE_GAMEPAD_CURSOR_SHADOW;
	extern Image* IMAGE_GAMEPAD_IMAGE_P1;
	extern Image* IMAGE_GAMEPAD_IMAGE_P2;
	extern Image* IMAGE_HAMMER_ICON;
	extern Image* IMAGE_HEAVY_WEAPON_OVERLAY;
	extern Image* IMAGE_HELP_BUTTONS;
	extern Image* IMAGE_HELP_BUTTONS_SMALL;
	extern Image* IMAGE_HELP_MENU_IMAGE_BUTTER;
	extern Image* IMAGE_HELP_MENU_IMAGE_CONTROLLER;
	extern Image* IMAGE_HELP_MENU_IMAGE_COOP_MENU;
	extern Image* IMAGE_HELP_MENU_IMAGE_COOP_SUN;
	extern Image* IMAGE_HELP_MENU_IMAGE_PLANTS;
	extern Image* IMAGE_HELP_MENU_IMAGE_SHADOW;
	extern Image* IMAGE_HELP_MENU_IMAGE_VS_BRAINS;
	extern Image* IMAGE_HELP_MENU_IMAGE_VS_CONTROLLERS;
	extern Image* IMAGE_HELP_MENU_IMAGE_VS_TARGETS;
	extern Image* IMAGE_HELP_MENU_IMAGE_ZOMBIES;
	extern Image* IMAGE_HELP_MENU_PAPER_1;
	extern Image* IMAGE_HELP_MENU_PAPER_2;
	extern Image* IMAGE_HELP_SUN_SHOT;
	extern Image* IMAGE_HOUSE_HILL;
	extern Image* IMAGE_HOUSE_SIDEWALK;
	extern Image* IMAGE_HOUSE_SKY;
	extern Image* IMAGE_ICE;
	extern Image* IMAGE_ICETRAP2;
	extern Image* IMAGE_ICETRAP;
	extern Image* IMAGE_ICETRAP_PARTICLES;
	extern Image* IMAGE_ICE_CAP;
	extern Image* IMAGE_ICE_SPARKLES;
	extern Image* IMAGE_ICON_POOLCLEANER;
	extern Image* IMAGE_ICON_RAKE;
	extern Image* IMAGE_ICON_ROOFCLEANER;
	extern Image* IMAGE_IMITATERCLOUDS;
	extern Image* IMAGE_IMITATERPUFFS;
	extern Image* IMAGE_IMITATERSEED;
	extern Image* IMAGE_IMITATERSEEDDISABLED;
	extern Image* IMAGE_LEADERBOARD_FILL;
	extern Image* IMAGE_LEADERBOARD_HEADER_LARGE;
	extern Image* IMAGE_LEADERBOARD_HEADER_SMALL;
	extern Image* IMAGE_LEADERBOARD_HOLE;
	extern Image* IMAGE_LEADERBOARD_HOLE_BJORN;
	extern Image* IMAGE_LEADERBOARD_HOLE_CHINA;
	extern Image* IMAGE_LEADERBOARD_HOLE_GEMS;
	extern Image* IMAGE_LEADERBOARD_HOLE_PIPE;
	extern Image* IMAGE_LEADERBOARD_HOLE_ROCKS;
	extern Image* IMAGE_LEADERBOARD_HOLE_TIKI;
	extern Image* IMAGE_LEADERBOARD_HOLE_WORM;
	extern Image* IMAGE_LEADERBOARD_SELECTOR;
	extern Image* IMAGE_LOCK;
	extern Image* IMAGE_LOCK_OPEN;
	extern Image* IMAGE_MAILBOX_TABLE;
	extern Image* IMAGE_MAILBOX_TABLE_LEAVESSHADOWS;
	extern Image* IMAGE_MELONPULT_PARTICLES;
	extern Image* IMAGE_MINIGAME_TROPHY;
	extern Image* IMAGE_MONEYBAG;
	extern Image* IMAGE_MONEYBAG_HI_RES;
	extern Image* IMAGE_MP_PLANT_SIDE;
	extern Image* IMAGE_MP_PLANT_SIDE_PLANTS;
	extern Image* IMAGE_MP_PLANT_SIDE_SELECTED;
	extern Image* IMAGE_MP_PLANT_TROPHY;
	extern Image* IMAGE_MP_PLANT_TROPHY_HI_RES;
	extern Image* IMAGE_MP_TARGET;
	extern Image* IMAGE_MP_TARGETS_UI;
	extern Image* IMAGE_MP_TARGETS_X;
	extern Image* IMAGE_MP_TOMBSTONE;
	extern Image* IMAGE_MP_TROPHY_BASE;
	extern Image* IMAGE_MP_TROPHY_BASE_HI_RES;
	extern Image* IMAGE_MP_ZOMBIE_SIDE;
	extern Image* IMAGE_MP_ZOMBIE_SIDE_SELECTED;
	extern Image* IMAGE_MP_ZOMBIE_SIDE_ZOMBIES;
	extern Image* IMAGE_MP_ZOMBIE_TROPHY;
	extern Image* IMAGE_MP_ZOMBIE_TROPHY_HI_RES;
	extern Image* IMAGE_NIGHT_GRAVE_GRAPHIC;
	extern Image* IMAGE_OPTIONS_CHECKBOX0;
	extern Image* IMAGE_OPTIONS_CHECKBOX1;
	extern Image* IMAGE_OPTIONS_MENUBACK;
	extern Image* IMAGE_OPTIONS_SLIDERKNOB2;
	extern Image* IMAGE_OPTIONS_SLIDERSLOT;
	extern Image* IMAGE_PEA_PARTICLES;
	extern Image* IMAGE_PEA_SHADOWS;
	extern Image* IMAGE_PEA_SPLATS;
	extern Image* IMAGE_PERISCOPE;
	extern Image* IMAGE_PERISCOPE_RETICULE;
	extern Image* IMAGE_PHONOGRAPH;
	extern Image* IMAGE_PINATA;
	extern Image* IMAGE_PLANTSHADOW2;
	extern Image* IMAGE_PLANTSHADOW;
	extern Image* IMAGE_PLANTSPEECHBUBBLE;
	extern Image* IMAGE_PLANT_LAYER_1_1;
	extern Image* IMAGE_PLANT_LAYER_1_2;
	extern Image* IMAGE_PLANT_LAYER_2_1;
	extern Image* IMAGE_PLANT_LAYER_2_2;
	extern Image* IMAGE_PLANT_LAYER_3_1;
	extern Image* IMAGE_PLANT_LAYER_3_2;
	extern Image* IMAGE_POOL;
	extern Image* IMAGE_POOLSPARKLY;
	extern Image* IMAGE_POOL_BASE;
	extern Image* IMAGE_POOL_BASE_NIGHT;
	extern Image* IMAGE_POOL_CAUSTIC_EFFECT;
	extern Image* IMAGE_POOL_NIGHT;
	extern Image* IMAGE_POOL_SHADING;
	extern Image* IMAGE_POOL_SHADING_NIGHT;
	extern Image* IMAGE_POTATOMINE_PARTICLES;
	extern Image* IMAGE_PRESENT;
	extern Image* IMAGE_PRESENTOPEN;
	extern Image* IMAGE_PROJECTILECACTUS;
	extern Image* IMAGE_PROJECTILEPEA;
	extern Image* IMAGE_PROJECTILESNOWPEA;
	extern Image* IMAGE_PROJECTILE_STAR;
	extern Image* IMAGE_PUFFSHROOM_PUFF1;
	extern Image* IMAGE_RAIN;
	extern Image* IMAGE_REANIM_CABBAGEPULT_CABBAGE;
	extern Image* IMAGE_REANIM_COBCANNON_COB;
	extern Image* IMAGE_REANIM_COINGLOW;
	extern Image* IMAGE_REANIM_COIN_GOLD_DOLLAR;
	extern Image* IMAGE_REANIM_COIN_SILVER_DOLLAR;
	extern Image* IMAGE_REANIM_CORNPULT_BUTTER;
	extern Image* IMAGE_REANIM_CORNPULT_BUTTER_SPLAT;
	extern Image* IMAGE_REANIM_CORNPULT_KERNAL;
	extern Image* IMAGE_REANIM_CRAZYDAVE_MOUTH1;
	extern Image* IMAGE_REANIM_CRAZYDAVE_MOUTH4;
	extern Image* IMAGE_REANIM_CRAZYDAVE_MOUTH5;
	extern Image* IMAGE_REANIM_CRAZYDAVE_MOUTH6;
	extern Image* IMAGE_REANIM_DIAMOND;
	extern Image* IMAGE_REANIM_GARLIC_BODY2;
	extern Image* IMAGE_REANIM_GARLIC_BODY3;
	extern Image* IMAGE_REANIM_MELONPULT_MELON;
	extern Image* IMAGE_REANIM_POINT;
	extern Image* IMAGE_REANIM_POT_TOP_DARK;
	extern Image* IMAGE_REANIM_PUMPKIN_DAMAGE1;
	extern Image* IMAGE_REANIM_PUMPKIN_DAMAGE3;
	extern Image* IMAGE_REANIM_SELECTORSCREEN_CLOUD1;
	extern Image* IMAGE_REANIM_SELECTORSCREEN_CLOUD2;
	extern Image* IMAGE_REANIM_SELECTORSCREEN_CLOUD4;
	extern Image* IMAGE_REANIM_SELECTORSCREEN_CLOUD5;
	extern Image* IMAGE_REANIM_SELECTORSCREEN_CLOUD6;
	extern Image* IMAGE_REANIM_SELECTORSCREEN_CLOUD7;
	extern Image* IMAGE_REANIM_STINKY_TURN3;
	extern Image* IMAGE_REANIM_TALLNUT_CRACKED1;
	extern Image* IMAGE_REANIM_TALLNUT_CRACKED2;
	extern Image* IMAGE_REANIM_TREE_BG;
	extern Image* IMAGE_REANIM_WALLNUT_BODY;
	extern Image* IMAGE_REANIM_WALLNUT_CRACKED1;
	extern Image* IMAGE_REANIM_WALLNUT_CRACKED2;
	extern Image* IMAGE_REANIM_WINTERMELON_PROJECTILE;
	extern Image* IMAGE_REANIM_ZENGARDEN_BUGSPRAY_BOTTLE;
	extern Image* IMAGE_REANIM_ZOMBIE_BACKUP_INNERARM_HAND;
	extern Image* IMAGE_REANIM_ZOMBIE_BACKUP_OUTERARM_UPPER2;
	extern Image* IMAGE_REANIM_ZOMBIE_BALLOON_OUTERARM_UPPER2;
	extern Image* IMAGE_REANIM_ZOMBIE_BOBSLED_OUTERARM_HAND;
	extern Image* IMAGE_REANIM_ZOMBIE_BOBSLED_OUTERARM_UPPER2;
	extern Image* IMAGE_REANIM_ZOMBIE_BOSS_EYEGLOW_BLUE;
	extern Image* IMAGE_REANIM_ZOMBIE_BOSS_FOOT_DAMAGE1;
	extern Image* IMAGE_REANIM_ZOMBIE_BOSS_FOOT_DAMAGE2;
	extern Image* IMAGE_REANIM_ZOMBIE_BOSS_HEAD_DAMAGE1;
	extern Image* IMAGE_REANIM_ZOMBIE_BOSS_HEAD_DAMAGE2;
	extern Image* IMAGE_REANIM_ZOMBIE_BOSS_ICEBALL;
	extern Image* IMAGE_REANIM_ZOMBIE_BOSS_JAW_DAMAGE1;
	extern Image* IMAGE_REANIM_ZOMBIE_BOSS_JAW_DAMAGE2;
	extern Image* IMAGE_REANIM_ZOMBIE_BOSS_MOUTHGLOW_BLUE;
	extern Image* IMAGE_REANIM_ZOMBIE_BOSS_OUTERARM_HAND_DAMAGE1;
	extern Image* IMAGE_REANIM_ZOMBIE_BOSS_OUTERARM_HAND_DAMAGE2;
	extern Image* IMAGE_REANIM_ZOMBIE_BOSS_OUTERARM_THUMB_DAMAGE1;
	extern Image* IMAGE_REANIM_ZOMBIE_BOSS_OUTERARM_THUMB_DAMAGE2;
	extern Image* IMAGE_REANIM_ZOMBIE_BUCKET1;
	extern Image* IMAGE_REANIM_ZOMBIE_BUCKET2;
	extern Image* IMAGE_REANIM_ZOMBIE_BUCKET3;
	extern Image* IMAGE_REANIM_ZOMBIE_BUNGI_HEAD_SCARED;
	extern Image* IMAGE_REANIM_ZOMBIE_CATAPULT_BASKETBALL;
	extern Image* IMAGE_REANIM_ZOMBIE_CATAPULT_POLE;
	extern Image* IMAGE_REANIM_ZOMBIE_CATAPULT_POLE_DAMAGE;
	extern Image* IMAGE_REANIM_ZOMBIE_CATAPULT_POLE_DAMAGE_WITHBALL;
	extern Image* IMAGE_REANIM_ZOMBIE_CATAPULT_POLE_WITHBALL;
	extern Image* IMAGE_REANIM_ZOMBIE_CATAPULT_SIDING_DAMAGE;
	extern Image* IMAGE_REANIM_ZOMBIE_CONE1;
	extern Image* IMAGE_REANIM_ZOMBIE_CONE2;
	extern Image* IMAGE_REANIM_ZOMBIE_CONE3;
	extern Image* IMAGE_REANIM_ZOMBIE_DIGGER_HARDHAT2;
	extern Image* IMAGE_REANIM_ZOMBIE_DIGGER_HARDHAT3;
	extern Image* IMAGE_REANIM_ZOMBIE_DIGGER_HARDHAT;
	extern Image* IMAGE_REANIM_ZOMBIE_DIGGER_OUTERARM_UPPER2;
	extern Image* IMAGE_REANIM_ZOMBIE_DIGGER_PICKAXE;
	extern Image* IMAGE_REANIM_ZOMBIE_DISCO_OUTERARM_HAND;
	extern Image* IMAGE_REANIM_ZOMBIE_DISCO_OUTERARM_UPPER2;
	extern Image* IMAGE_REANIM_ZOMBIE_DOLPHINRIDER_OUTERARM_UPPER2;
	extern Image* IMAGE_REANIM_ZOMBIE_FLAG1;
	extern Image* IMAGE_REANIM_ZOMBIE_FLAG3;
	extern Image* IMAGE_REANIM_ZOMBIE_FOOTBALL_HELMET2;
	extern Image* IMAGE_REANIM_ZOMBIE_FOOTBALL_HELMET3;
	extern Image* IMAGE_REANIM_ZOMBIE_FOOTBALL_HELMET;
	extern Image* IMAGE_REANIM_ZOMBIE_FOOTBALL_LEFTARM_HAND;
	extern Image* IMAGE_REANIM_ZOMBIE_FOOTBALL_LEFTARM_UPPER2;
	extern Image* IMAGE_REANIM_ZOMBIE_GARGANTUAR_BODY1_2;
	extern Image* IMAGE_REANIM_ZOMBIE_GARGANTUAR_BODY1_3;
	extern Image* IMAGE_REANIM_ZOMBIE_GARGANTUAR_DUCKXING;
	extern Image* IMAGE_REANIM_ZOMBIE_GARGANTUAR_FOOT2;
	extern Image* IMAGE_REANIM_ZOMBIE_GARGANTUAR_HEAD2;
	extern Image* IMAGE_REANIM_ZOMBIE_GARGANTUAR_HEAD2_REDEYE;
	extern Image* IMAGE_REANIM_ZOMBIE_GARGANTUAR_HEAD_REDEYE;
	extern Image* IMAGE_REANIM_ZOMBIE_GARGANTUAR_OUTERARM_LOWER2;
	extern Image* IMAGE_REANIM_ZOMBIE_GARGANTUAR_ZOMBIE;
	extern Image* IMAGE_REANIM_ZOMBIE_HEAD_GROSSOUT;
	extern Image* IMAGE_REANIM_ZOMBIE_HEAD_SUNGLASSES1;
	extern Image* IMAGE_REANIM_ZOMBIE_HEAD_SUNGLASSES2;
	extern Image* IMAGE_REANIM_ZOMBIE_HEAD_SUNGLASSES3;
	extern Image* IMAGE_REANIM_ZOMBIE_HEAD_SUNGLASSES4;
	extern Image* IMAGE_REANIM_ZOMBIE_IMP_ARM1_BONE;
	extern Image* IMAGE_REANIM_ZOMBIE_IMP_ARM2;
	extern Image* IMAGE_REANIM_ZOMBIE_JACKBOX_BOX;
	extern Image* IMAGE_REANIM_ZOMBIE_JACKBOX_OUTERARM_LOWER2;
	extern Image* IMAGE_REANIM_ZOMBIE_LADDER_1;
	extern Image* IMAGE_REANIM_ZOMBIE_LADDER_1_DAMAGE1;
	extern Image* IMAGE_REANIM_ZOMBIE_LADDER_1_DAMAGE2;
	extern Image* IMAGE_REANIM_ZOMBIE_LADDER_5;
	extern Image* IMAGE_REANIM_ZOMBIE_LADDER_OUTERARM_UPPER2;
	extern Image* IMAGE_REANIM_ZOMBIE_MUSTACHE2;
	extern Image* IMAGE_REANIM_ZOMBIE_MUSTACHE3;
	extern Image* IMAGE_REANIM_ZOMBIE_OUTERARM_HAND;
	extern Image* IMAGE_REANIM_ZOMBIE_OUTERARM_UPPER2;
	extern Image* IMAGE_REANIM_ZOMBIE_PAPER_LEFTARM_LOWER;
	extern Image* IMAGE_REANIM_ZOMBIE_PAPER_LEFTARM_UPPER2;
	extern Image* IMAGE_REANIM_ZOMBIE_PAPER_MADHEAD;
	extern Image* IMAGE_REANIM_ZOMBIE_PAPER_PAPER2;
	extern Image* IMAGE_REANIM_ZOMBIE_PAPER_PAPER3;
	extern Image* IMAGE_REANIM_ZOMBIE_POGO_OUTERARM_UPPER2;
	extern Image* IMAGE_REANIM_ZOMBIE_POGO_STICK2DAMAGE1;
	extern Image* IMAGE_REANIM_ZOMBIE_POGO_STICK2DAMAGE2;
	extern Image* IMAGE_REANIM_ZOMBIE_POGO_STICKDAMAGE1;
	extern Image* IMAGE_REANIM_ZOMBIE_POGO_STICKDAMAGE2;
	extern Image* IMAGE_REANIM_ZOMBIE_POGO_STICKHANDS2;
	extern Image* IMAGE_REANIM_ZOMBIE_POLEVAULTER_OUTERARM_UPPER2;
	extern Image* IMAGE_REANIM_ZOMBIE_SCREENDOOR1;
	extern Image* IMAGE_REANIM_ZOMBIE_SCREENDOOR2;
	extern Image* IMAGE_REANIM_ZOMBIE_SCREENDOOR3;
	extern Image* IMAGE_REANIM_ZOMBIE_SNORKLE_HEAD;
	extern Image* IMAGE_REANIM_ZOMBIE_SNORKLE_OUTERARM_UPPER2;
	extern Image* IMAGE_REANIM_ZOMBIE_TRASHCAN1;
	extern Image* IMAGE_REANIM_ZOMBIE_TRASHCAN2;
	extern Image* IMAGE_REANIM_ZOMBIE_TRASHCAN3;
	extern Image* IMAGE_REANIM_ZOMBIE_YETI_OUTERARM_HAND;
	extern Image* IMAGE_REANIM_ZOMBIE_YETI_OUTERARM_UPPER2;
	extern Image* IMAGE_REANIM_ZOMBIE_ZAMBONI_1_DAMAGE1;
	extern Image* IMAGE_REANIM_ZOMBIE_ZAMBONI_1_DAMAGE2;
	extern Image* IMAGE_REANIM_ZOMBIE_ZAMBONI_2_DAMAGE1;
	extern Image* IMAGE_REANIM_ZOMBIE_ZAMBONI_2_DAMAGE2;
	extern Image* IMAGE_REANIM_ZOMBIE_ZAMBONI_WHEEL_FLAT;
	extern Image* IMAGE_ROCKSMALL;
	extern Image* IMAGE_SCARY_POT;
	extern Image* IMAGE_SCROLL_INDICATOR;
	extern Image* IMAGE_SEEDBANK;
	extern Image* IMAGE_SEEDBANK_COOP;
	extern Image* IMAGE_SEEDCHOOSER_ALMANAC_BUTTON;
	extern Image* IMAGE_SEEDCHOOSER_ALMANAC_BUTTON_PRESSED;
	extern Image* IMAGE_SEEDCHOOSER_BACKGROUND2;
	extern Image* IMAGE_SEEDCHOOSER_BACKGROUND;
	extern Image* IMAGE_SEEDCHOOSER_BUTTON2;
	extern Image* IMAGE_SEEDCHOOSER_BUTTON2_GLOW;
	extern Image* IMAGE_SEEDCHOOSER_BUTTON;
	extern Image* IMAGE_SEEDCHOOSER_BUTTON_DISABLED;
	extern Image* IMAGE_SEEDCHOOSER_IMITATERADDON;
	extern Image* IMAGE_SEEDCHOOSER_SHOP_BUTTON;
	extern Image* IMAGE_SEEDCHOOSER_SHOP_BUTTON_PRESSED;
	extern Image* IMAGE_SEEDPACKETFLASH;
	extern Image* IMAGE_SEEDPACKETSILHOUETTE;
	extern Image* IMAGE_SEEDPACKET_LARGER;
	extern Image* IMAGE_SEEDS;
	extern Image* IMAGE_SEED_SELECTOR;
	extern Image* IMAGE_SEED_SELECTOR_BLUE;
	extern Image* IMAGE_SHOVEL;
	extern Image* IMAGE_SHOVELBANK;
	extern Image* IMAGE_SHOVELMETER_EMTY;
	extern Image* IMAGE_SHOVELMETER_FULL;
	extern Image* IMAGE_SHOVEL_HI_RES;
	extern Image* IMAGE_SLOTMACHINE_BALL_TOUCH;
	extern Image* IMAGE_SLOTMACHINE_OVERLAY;
	extern Image* IMAGE_SNOWFLAKES;
	extern Image* IMAGE_SNOWPEA_PARTICLES;
	extern Image* IMAGE_SNOWPEA_PUFF;
	extern Image* IMAGE_SNOWPEA_SPLATS;
	extern Image* IMAGE_SPOTLIGHT2;
	extern Image* IMAGE_SPOTLIGHT;
	extern Image* IMAGE_SQUARE_TEXTURE;
	extern Image* IMAGE_SQUARE_TEXTURE_ZOMBIE;
	extern Image* IMAGE_STAR_PARTICLES;
	extern Image* IMAGE_STAR_SPLATS;
	extern Image* IMAGE_STORE_AQUARIUMGARDENICON;
	extern Image* IMAGE_STORE_BLUEPRINT_BLING;
	extern Image* IMAGE_STORE_BLUEPRINT_CHANGE;
	extern Image* IMAGE_STORE_BLUEPRINT_CLOWN;
	extern Image* IMAGE_STORE_BLUEPRINT_FUTURE;
	extern Image* IMAGE_STORE_BLUEPRINT_SCARY;
	extern Image* IMAGE_STORE_BLUEPRINT_TRAILER;
	extern Image* IMAGE_STORE_MUSHROOMGARDENICON;
	extern Image* IMAGE_STORE_SPEECHBUBBLE2;
	extern Image* IMAGE_STORE_SPEECHBUBBLE;
	extern Image* IMAGE_STORE_TREEOFWISDOMICON;
	extern Image* IMAGE_STORE_ZENGARDENICON;
	extern Image* IMAGE_SUNBANK;
	extern Image* IMAGE_SUNFLOWER_TROPHY;
	extern Image* IMAGE_SURVIVAL_THUMBNAILS;
	extern Image* IMAGE_TACO;
	extern Image* IMAGE_TOMBSTONES;
	extern Image* IMAGE_TOMBSTONE_MOUNDS;
	extern Image* IMAGE_TRANSITION_HOLE;
	extern Image* IMAGE_TRASHCAN_PLANTS;
	extern Image* IMAGE_TRASHCAN_ZOMBIES;
	extern Image* IMAGE_TREEFOOD;
	extern Image* IMAGE_TROPHY;
	extern Image* IMAGE_TROPHY_HI_RES;
	extern Image* IMAGE_VASE_CHUNKS;
	extern Image* IMAGE_VS_INFO_BOX_PLANTS;
	extern Image* IMAGE_VS_INFO_BOX_PLANTS_OVERLAY;
	extern Image* IMAGE_VS_INFO_BOX_ZOMBIES;
	extern Image* IMAGE_VS_INFO_BOX_ZOMBIES_OVERLAY;
	extern Image* IMAGE_VS_STONE_DIRT;
	extern Image* IMAGE_WALLNUTPARTICLESLARGE;
	extern Image* IMAGE_WALLNUTPARTICLESSMALL;
	extern Image* IMAGE_WALLNUT_BOWLINGSTRIPE;
	extern Image* IMAGE_WATERDROP;
	extern Image* IMAGE_WATERINGCAN;
	extern Image* IMAGE_WATERINGCANGOLD;
	extern Image* IMAGE_WATERPARTICLE;
	extern Image* IMAGE_WHITEPIXEL;
	extern Image* IMAGE_WHITEWATER;
	extern Image* IMAGE_WHITEWATER_SHADOW;
	extern Image* IMAGE_WINTERMELON_PARTICLES;
	extern Image* IMAGE_ZAMBONISMOKE;
	extern Image* IMAGE_ZENSHOPBUTTON;
	extern Image* IMAGE_ZENSHOPBUTTON_HIGHLIGHT;
	extern Image* IMAGE_ZEN_GARDENGLOVE;
	extern Image* IMAGE_ZEN_GOLDTOOLRETICLE;
	extern Image* IMAGE_ZEN_MONEYSIGN;
	extern Image* IMAGE_ZEN_NEED_ICONS;
	extern Image* IMAGE_ZEN_NEXTGARDEN;
	extern Image* IMAGE_ZEN_NEXTGARDEN_HIGHLIGHT;
	extern Image* IMAGE_ZEN_PREVGARDEN;
	extern Image* IMAGE_ZEN_PREVGARDEN_HIGHLIGHT;
	extern Image* IMAGE_ZEN_WHEELBARROW;
	extern Image* IMAGE_ZOMBATAR_SIGN;
	extern Image* IMAGE_ZOMBATAR_SIGN_PRESSED;
	extern Image* IMAGE_ZOMBIEBACKUPDANCERHEAD;
	extern Image* IMAGE_ZOMBIEBALLOONHEAD;
	extern Image* IMAGE_ZOMBIEBOBSLEDHEAD;
	extern Image* IMAGE_ZOMBIEDANCERHEAD;
	extern Image* IMAGE_ZOMBIEDIGGERARM;
	extern Image* IMAGE_ZOMBIEDIGGERHEAD;
	extern Image* IMAGE_ZOMBIEDOLPHINRIDERHEAD;
	extern Image* IMAGE_ZOMBIEFOOTBALLHEAD;
	extern Image* IMAGE_ZOMBIEFUTUREGLASSES;
	extern Image* IMAGE_ZOMBIEIMPHEAD;
	extern Image* IMAGE_ZOMBIEJACKBOXARM;
	extern Image* IMAGE_ZOMBIELADDERHEAD;
	extern Image* IMAGE_ZOMBIEPOGO;
	extern Image* IMAGE_ZOMBIEPOLEVAULTERHEAD;
	extern Image* IMAGE_ZOMBIEYETIHEAD;
	extern Image* IMAGE_ZOMBIE_BOBSLED1;
	extern Image* IMAGE_ZOMBIE_BOBSLED2;
	extern Image* IMAGE_ZOMBIE_BOBSLED3;
	extern Image* IMAGE_ZOMBIE_BOBSLED4;
	extern Image* IMAGE_ZOMBIE_BOBSLED_INSIDE;
	extern Image* IMAGE_ZOMBIE_BOSS_FIREBALL_GROUNDPARTICLES;
	extern Image* IMAGE_ZOMBIE_BOSS_FIREBALL_PARTICLES;
	extern Image* IMAGE_ZOMBIE_BOSS_ICEBALL_GROUNDPARTICLES;
	extern Image* IMAGE_ZOMBIE_BOSS_ICEBALL_PARTICLES;
	extern Image* IMAGE_ZOMBIE_HEAD;
	extern Image* IMAGE_ZOMBIE_LAYER_1_1;
	extern Image* IMAGE_ZOMBIE_LAYER_1_2;
	extern Image* IMAGE_ZOMBIE_LAYER_1_3;
	extern Image* IMAGE_ZOMBIE_LAYER_2_1;
	extern Image* IMAGE_ZOMBIE_LAYER_2_2;
	extern Image* IMAGE_ZOMBIE_LAYER_2_3;
	extern Image* IMAGE_ZOMBIE_LAYER_3_1;
	extern Image* IMAGE_ZOMBIE_LAYER_3_2;
	extern Image* IMAGE_ZOMBIE_LAYER_3_3;
	extern Image* IMAGE_ZOMBIE_LAYER_TEST;
	extern Image* IMAGE_ZOMBIE_NOTE_SMALL;
	extern Image* IMAGE_ZOMBIE_SEAWEED;
	extern Image* IMAGE_ZOMBIE_SEEDBANK;
	extern Image* IMAGE_ZOMBIE_SEEDPACKET;
	extern Image* IMAGE_ZOMBOSS_PARTICLES;

	// LoadingSounds Resources
	bool ExtractLoadingSoundsResources(ResourceManager *theMgr);
	extern int SOUND_ACHIEVEMENT;
	extern int SOUND_ALMANAC;
	extern int SOUND_AWOOGA;
	extern int SOUND_BALLOONINFLATE;
	extern int SOUND_BALLOON_POP;
	extern int SOUND_BASKETBALL;
	extern int SOUND_BIGCHOMP;
	extern int SOUND_BIGTHUD;
	extern int SOUND_BLEEP;
	extern int SOUND_BLOVER;
	extern int SOUND_BOING;
	extern int SOUND_BONK;
	extern int SOUND_BOSSBOULDERATTACK;
	extern int SOUND_BOSSEXPLOSION;
	extern int SOUND_BOWLING;
	extern int SOUND_BOWLINGIMPACT2;
	extern int SOUND_BOWLINGIMPACT;
	extern int SOUND_BUGSPRAY;
	extern int SOUND_BUNGEE_SCREAM2;
	extern int SOUND_BUNGEE_SCREAM3;
	extern int SOUND_BUNGEE_SCREAM;
	extern int SOUND_BUTTER;
	extern int SOUND_BUZZER;
	extern int SOUND_CERAMIC;
	extern int SOUND_CHERRYBOMB;
	extern int SOUND_CHIME;
	extern int SOUND_CHOMP2;
	extern int SOUND_CHOMP;
	extern int SOUND_CHOMPSOFT;
	extern int SOUND_COBLAUNCH;
	extern int SOUND_COFFEE;
	extern int SOUND_COIN;
	extern int SOUND_COOP;
	extern int SOUND_CRAZYDAVECRAZY;
	extern int SOUND_CRAZYDAVEEXTRALONG1;
	extern int SOUND_CRAZYDAVEEXTRALONG2;
	extern int SOUND_CRAZYDAVEEXTRALONG3;
	extern int SOUND_CRAZYDAVELONG1;
	extern int SOUND_CRAZYDAVELONG2;
	extern int SOUND_CRAZYDAVELONG3;
	extern int SOUND_CRAZYDAVESCREAM2;
	extern int SOUND_CRAZYDAVESCREAM;
	extern int SOUND_CRAZYDAVESHORT1;
	extern int SOUND_CRAZYDAVESHORT2;
	extern int SOUND_CRAZYDAVESHORT3;
	extern int SOUND_CROW_CAW1;
	extern int SOUND_CROW_CAW2;
	extern int SOUND_CROW_CAW3;
	extern int SOUND_CROW_FLAP1;
	extern int SOUND_CROW_FLAP2;
	extern int SOUND_CROW_FLAP3;
	extern int SOUND_DANCER;
	extern int SOUND_DIAMOND;
	extern int SOUND_DIGGER_ZOMBIE;
	extern int SOUND_DIRT_RISE;
	extern int SOUND_DOLPHIN_APPEARS;
	extern int SOUND_DOLPHIN_BEFORE_JUMPING;
	extern int SOUND_DOOMSHROOM;
	extern int SOUND_EVILLAUGH;
	extern int SOUND_EXPLOSION;
	extern int SOUND_FERTILIZER;
	extern int SOUND_FINALFANFARE;
	extern int SOUND_FINALWAVE;
	extern int SOUND_FIREPEA;
	extern int SOUND_FLOOP;
	extern int SOUND_FROZEN;
	extern int SOUND_FUME;
	extern int SOUND_GARGANTUAR_THUMP;
	extern int SOUND_GARGANTUDEATH;
	extern int SOUND_GRASSSTEP;
	extern int SOUND_GRAVEBUSTERCHOMP;
	extern int SOUND_GRAVEBUTTON;
	extern int SOUND_GRAVESTONE_RUMBLE;
	extern int SOUND_GROAN2;
	extern int SOUND_GROAN3;
	extern int SOUND_GROAN4;
	extern int SOUND_GROAN5;
	extern int SOUND_GROAN6;
	extern int SOUND_GROAN;
	extern int SOUND_GULP;
	extern int SOUND_HATCHBACK_CLOSE;
	extern int SOUND_HATCHBACK_OPEN;
	extern int SOUND_HUGE_WAVE;
	extern int SOUND_HYDRAULIC;
	extern int SOUND_HYDRAULIC_SHORT;
	extern int SOUND_IGNITE2;
	extern int SOUND_IGNITE;
	extern int SOUND_IMP2;
	extern int SOUND_IMP;
	extern int SOUND_JACKINTHEBOX;
	extern int SOUND_JACK_SURPRISE2;
	extern int SOUND_JACK_SURPRISE;
	extern int SOUND_JALAPENO;
	extern int SOUND_JUICY;
	extern int SOUND_KERNELPULT2;
	extern int SOUND_KERNELPULT;
	extern int SOUND_LADDER_ZOMBIE;
	extern int SOUND_LAWNMOWER;
	extern int SOUND_LIGHTFILL;
	extern int SOUND_LIMBS_POP;
	extern int SOUND_LOSEMUSIC;
	extern int SOUND_LOWGROAN2;
	extern int SOUND_LOWGROAN;
	extern int SOUND_MAGNETSHROOM;
	extern int SOUND_MAIL;
	extern int SOUND_MELONIMPACT2;
	extern int SOUND_MELONIMPACT;
	extern int SOUND_MENU_C_ST;
	extern int SOUND_MENU_L_ST;
	extern int SOUND_MENU_R_ST;
	extern int SOUND_MINDCONTROLLED;
	extern int SOUND_MINIGAMES;
	extern int SOUND_MONEYFALLS;
	extern int SOUND_MP_TIMER;
	extern int SOUND_NEWSPAPER_RARRGH2;
	extern int SOUND_NEWSPAPER_RARRGH;
	extern int SOUND_NEWSPAPER_RIP;
	extern int SOUND_PAPER;
	extern int SOUND_PAUSE;
	extern int SOUND_PHONOGRAPH;
	extern int SOUND_PLANT2;
	extern int SOUND_PLANT;
	extern int SOUND_PLANTERN;
	extern int SOUND_PLANTGROW;
	extern int SOUND_PLANT_WATER;
	extern int SOUND_PLASTICHIT2;
	extern int SOUND_PLASTICHIT;
	extern int SOUND_POGO_ZOMBIE;
	extern int SOUND_POINTS;
	extern int SOUND_POLEVAULT;
	extern int SOUND_POOL_CLEANER;
	extern int SOUND_PORTAL;
	extern int SOUND_POTATO_MINE;
	extern int SOUND_PRIZE;
	extern int SOUND_PUFF;
	extern int SOUND_PUZZLE;
	extern int SOUND_RAIN;
	extern int SOUND_READYSETPLANT;
	extern int SOUND_REVERSE_EXPLOSION;
	extern int SOUND_ROLL_IN;
	extern int SOUND_RVTHROW;
	extern int SOUND_SCREAM;
	extern int SOUND_SEEDLIFT;
	extern int SOUND_SHIELDHIT2;
	extern int SOUND_SHIELDHIT;
	extern int SOUND_SHOOP;
	extern int SOUND_SHOP;
	extern int SOUND_SHOVEL;
	extern int SOUND_SIREN;
	extern int SOUND_SLOT_MACHINE;
	extern int SOUND_SLURP;
	extern int SOUND_SNOW_PEA_SPARKLES;
	extern int SOUND_SPLAT2;
	extern int SOUND_SPLAT3;
	extern int SOUND_SPLAT;
	extern int SOUND_SQUASH_HMM2;
	extern int SOUND_SQUASH_HMM;
	extern int SOUND_SUKHBIR2;
	extern int SOUND_SUKHBIR3;
	extern int SOUND_SUKHBIR4;
	extern int SOUND_SUKHBIR5;
	extern int SOUND_SUKHBIR6;
	extern int SOUND_SUKHBIR;
	extern int SOUND_SURVIVAL;
	extern int SOUND_SWING;
	extern int SOUND_TAP2;
	extern int SOUND_TAP;
	extern int SOUND_TAPGLASS;
	extern int SOUND_THROW2;
	extern int SOUND_THROW;
	extern int SOUND_THUNDER;
	extern int SOUND_THUNDER_1;
	extern int SOUND_THUNDER_1R;
	extern int SOUND_THUNDER_2;
	extern int SOUND_THUNDER_2R;
	extern int SOUND_THUNDER_3;
	extern int SOUND_THUNDER_3R;
	extern int SOUND_VASE_BREAKING;
	extern int SOUND_VS;
	extern int SOUND_VS_HEADPOP;
	extern int SOUND_WAKEUP;
	extern int SOUND_WATERING;
	extern int SOUND_WINMUSIC;
	extern int SOUND_YUCK2;
	extern int SOUND_YUCK;
	extern int SOUND_ZAMBONI;
	extern int SOUND_ZEN;
	extern int SOUND_ZOMBAQUARIUM_DIE;
	extern int SOUND_ZOMBIESPLASH;
	extern int SOUND_ZOMBIE_ENTERING_WATER;
	extern int SOUND_ZOMBIE_FALLING_1;
	extern int SOUND_ZOMBIE_FALLING_2;

	enum ResourceId
	{
		IMAGE_NO_GAMERPIC_ID,
		IMAGE_BLANK_ID,
		IMAGE_TITLESCREEN_ID,
		IMAGE_TITLESCREEN_BALL_ID,
		IMAGE_TITLESCREEN_GLOW_ID,
		IMAGE_LOADBAR_DIRT_ID,
		IMAGE_LOADBAR_GRASS_ID,
		IMAGE_PVZ_LOGO_ID,
		IMAGE_REANIM_SODROLLCAP_ID,
		FONT_BRIANNETOD16_ID,
		FONT_DWARVENTODCRAFT24_ID,
		SOUND_BUTTONCLICK_ID,
		SOUND_LOADINGBAR_FLOWER_ID,
		SOUND_LOADINGBAR_ZOMBIE_ID,
		FONT_HOUSEOFTERROR28_ID,
		FONT_HOUSEOFTERROR20_ID,
		FONT_HOUSEOFTERROR16_ID,
		FONT_CONTINUUMBOLD14_ID,
		FONT_CONTINUUMBOLD14OUTLINE_ID,
		FONT_DWARVENTODCRAFT12_ID,
		FONT_DWARVENTODCRAFT18_ID,
		FONT_BRIANNETOD12_ID,
		FONT_BRIANNETOD32_ID,
		FONT_BRIANNETOD32BLACK_ID,
		IMAGE_EDITBOX_ID,
		IMAGE_DIALOG_TOPLEFT_ID,
		IMAGE_DIALOG_TOPMIDDLE_ID,
		IMAGE_DIALOG_TOPRIGHT_ID,
		IMAGE_DIALOG_CENTERLEFT_ID,
		IMAGE_DIALOG_CENTERMIDDLE_ID,
		IMAGE_DIALOG_CENTERRIGHT_ID,
		IMAGE_DIALOG_BOTTOMLEFT_ID,
		IMAGE_DIALOG_BOTTOMMIDDLE_ID,
		IMAGE_DIALOG_BOTTOMRIGHT_ID,
		IMAGE_DIALOG_BIGBOTTOMLEFT_ID,
		IMAGE_DIALOG_BIGBOTTOMMIDDLE_ID,
		IMAGE_DIALOG_BIGBOTTOMRIGHT_ID,
		IMAGE_DIALOG_HEADER_ID,
		IMAGE_BUTTON_LEFT_ID,
		IMAGE_BUTTON_MIDDLE_ID,
		IMAGE_BUTTON_RIGHT_ID,
		IMAGE_BUTTON_GLOW_LEFT_ID,
		IMAGE_BUTTON_GLOW_MIDDLE_ID,
		IMAGE_BUTTON_GLOW_RIGHT_ID,
		IMAGE_BUTTON_DOWN_LEFT_ID,
		IMAGE_BUTTON_DOWN_MIDDLE_ID,
		IMAGE_BUTTON_DOWN_RIGHT_ID,
		IMAGE_BUTTON_GLOW_ID,
		IMAGE_TRANSITION_HOLE_ID,
		IMAGE_CROW_BUBBLE_ID,
		IMAGE_CHALLENGE_BACKGROUND_ID,
		IMAGE_SEEDCHOOSER_BACKGROUND_ID,
		IMAGE_SEEDCHOOSER_BACKGROUND2_ID,
		IMAGE_SEEDCHOOSER_BUTTON_ID,
		IMAGE_SEEDCHOOSER_BUTTON_DISABLED_ID,
		IMAGE_SEEDCHOOSER_BUTTON2_ID,
		IMAGE_SEEDCHOOSER_BUTTON2_GLOW_ID,
		IMAGE_ALMANAC_CLOSEBUTTON_ID,
		IMAGE_ALMANAC_CLOSEBUTTONHIGHLIGHT_ID,
		IMAGE_ALMANAC_INDEXBUTTON_ID,
		IMAGE_ALMANAC_INDEXBUTTONHIGHLIGHT_ID,
		IMAGE_ALMANAC_PAPER_ID,
		IMAGE_SEEDCHOOSER_IMITATERADDON_ID,
		IMAGE_SEEDS_ID,
		IMAGE_SEEDPACKET_LARGER_ID,
		IMAGE_SEEDPACKETSILHOUETTE_ID,
		IMAGE_FLAGMETER_ID,
		IMAGE_FLAGMETERLEVELPROGRESS_ID,
		IMAGE_FLAGMETERPARTS_ID,
		IMAGE_TROPHY_ID,
		IMAGE_TROPHY_HI_RES_ID,
		IMAGE_MINIGAME_TROPHY_ID,
		IMAGE_ZOMBIE_NOTE_SMALL_ID,
		IMAGE_TACO_ID,
		IMAGE_CARKEYS_ID,
		IMAGE_ALMANAC_ID,
		IMAGE_ICON_POOLCLEANER_ID,
		IMAGE_ICON_ROOFCLEANER_ID,
		IMAGE_ICON_RAKE_ID,
		IMAGE_BRAIN_ID,
		IMAGE_MONEYBAG_ID,
		IMAGE_MONEYBAG_HI_RES_ID,
		IMAGE_CHOCOLATE_ID,
		IMAGE_ZOMBIE_SEEDPACKET_ID,
		IMAGE_ZOMBIE_SEEDBANK_ID,
		IMAGE_MAILBOX_TABLE_ID,
		IMAGE_MAILBOX_TABLE_LEAVESSHADOWS_ID,
		IMAGE_COOP_SUN_HIGHLIGHT_1_ID,
		IMAGE_COOP_SUN_HIGHLIGHT_2_ID,
		IMAGE_DLG_SELECTORFRAME_ID,
		IMAGE_CHALLENGE_NAME_BACK_ID,
		IMAGE_HELP_MENU_PAPER_1_ID,
		IMAGE_HELP_MENU_PAPER_2_ID,
		IMAGE_HELP_MENU_IMAGE_SHADOW_ID,
		IMAGE_HELP_SUN_SHOT_ID,
		IMAGE_HELP_MENU_IMAGE_PLANTS_ID,
		IMAGE_HELP_MENU_IMAGE_ZOMBIES_ID,
		IMAGE_HELP_MENU_IMAGE_CONTROLLER_ID,
		IMAGE_HELP_MENU_IMAGE_VS_CONTROLLERS_ID,
		IMAGE_HELP_MENU_IMAGE_VS_BRAINS_ID,
		IMAGE_HELP_MENU_IMAGE_VS_TARGETS_ID,
		IMAGE_HELP_MENU_IMAGE_COOP_MENU_ID,
		IMAGE_HELP_MENU_IMAGE_COOP_SUN_ID,
		IMAGE_HELP_MENU_IMAGE_BUTTER_ID,
		IMAGE_STORE_BLUEPRINT_BLING_ID,
		IMAGE_STORE_BLUEPRINT_SCARY_ID,
		IMAGE_STORE_BLUEPRINT_FUTURE_ID,
		IMAGE_STORE_BLUEPRINT_TRAILER_ID,
		IMAGE_STORE_BLUEPRINT_CLOWN_ID,
		IMAGE_STORE_BLUEPRINT_CHANGE_ID,
		IMAGE_SEEDCHOOSER_ALMANAC_BUTTON_ID,
		IMAGE_SEEDCHOOSER_ALMANAC_BUTTON_PRESSED_ID,
		IMAGE_SEEDCHOOSER_SHOP_BUTTON_ID,
		IMAGE_SEEDCHOOSER_SHOP_BUTTON_PRESSED_ID,
		IMAGE_ALMANAC_BACKBUTTON_ID,
		IMAGE_OPTIONS_CHECKBOX0_ID,
		IMAGE_OPTIONS_CHECKBOX1_ID,
		IMAGE_OPTIONS_MENUBACK_ID,
		IMAGE_OPTIONS_SLIDERKNOB2_ID,
		IMAGE_OPTIONS_SLIDERSLOT_ID,
		IMAGE_STORE_SPEECHBUBBLE_ID,
		IMAGE_STORE_SPEECHBUBBLE2_ID,
		IMAGE_HELP_BUTTONS_ID,
		IMAGE_HELP_BUTTONS_SMALL_ID,
		IMAGE_SHOVEL_ID,
		IMAGE_SHOVEL_HI_RES_ID,
		IMAGE_TOMBSTONES_ID,
		IMAGE_MP_TOMBSTONE_ID,
		IMAGE_MP_TARGETS_UI_ID,
		IMAGE_MP_TARGETS_X_ID,
		IMAGE_TOMBSTONE_MOUNDS_ID,
		IMAGE_NIGHT_GRAVE_GRAPHIC_ID,
		IMAGE_CRATER_ID,
		IMAGE_CRATER_FADING_ID,
		IMAGE_CRATER_ROOF_CENTER_ID,
		IMAGE_CRATER_ROOF_LEFT_ID,
		IMAGE_CRATER_WATER_DAY_ID,
		IMAGE_CRATER_WATER_NIGHT_ID,
		IMAGE_COBCANNON_TARGET_ID,
		IMAGE_COBCANNON_TARGET_1_ID,
		IMAGE_COBCANNON_TARGET_2_ID,
		IMAGE_COBCANNON_TARGET_3_ID,
		IMAGE_COBCANNON_TARGET_4_ID,
		IMAGE_COBCANNON_POPCORN_ID,
		IMAGE_FERTILIZER_ID,
		IMAGE_WATERINGCAN_ID,
		IMAGE_WATERINGCANGOLD_ID,
		IMAGE_PHONOGRAPH_ID,
		IMAGE_BEGHOULED_TWIST_OVERLAY_ID,
		IMAGE_ZEN_GOLDTOOLRETICLE_ID,
		IMAGE_ZEN_GARDENGLOVE_ID,
		IMAGE_ZEN_MONEYSIGN_ID,
		IMAGE_ZEN_NEXTGARDEN_ID,
		IMAGE_ZEN_NEXTGARDEN_HIGHLIGHT_ID,
		IMAGE_ZEN_PREVGARDEN_ID,
		IMAGE_ZEN_PREVGARDEN_HIGHLIGHT_ID,
		IMAGE_ZEN_WHEELBARROW_ID,
		IMAGE_ZENSHOPBUTTON_ID,
		IMAGE_ZENSHOPBUTTON_HIGHLIGHT_ID,
		IMAGE_PRESENT_ID,
		IMAGE_PRESENTOPEN_ID,
		IMAGE_SUNFLOWER_TROPHY_ID,
		IMAGE_SLOTMACHINE_OVERLAY_ID,
		IMAGE_SCARY_POT_ID,
		IMAGE_BUG_SPRAY_ID,
		IMAGE_PLANTSPEECHBUBBLE_ID,
		IMAGE_WATERDROP_ID,
		IMAGE_TREEFOOD_ID,
		IMAGE_ZEN_NEED_ICONS_ID,
		IMAGE_SEED_SELECTOR_ID,
		IMAGE_SEED_SELECTOR_BLUE_ID,
		IMAGE_PERISCOPE_ID,
		IMAGE_SQUARE_TEXTURE_ID,
		IMAGE_SQUARE_TEXTURE_ZOMBIE_ID,
		IMAGE_CURSOR_FLOWER_ID,
		IMAGE_CURSOR_SKULL_ID,
		IMAGE_CURSOR_ARROW_P1_ID,
		IMAGE_CURSOR_ARROW_P2_ID,
		IMAGE_CURSOR_P1_TEXT_ID,
		IMAGE_CURSOR_P2_TEXT_ID,
		IMAGE_GAMEPAD_CURSOR_SHADOW_ID,
		IMAGE_GAMEPAD_CURSOR_FRAME_ID,
		IMAGE_GAMEPAD_CURSOR_FRAME_BLUE_ID,
		IMAGE_GAMEPAD_CURSOR_FRAME_SHADOW_ID,
		IMAGE_GAMEPAD_CURSOR_ARROWS_ID,
		IMAGE_GAMEPAD_CURSOR_ARROWS_SHADOW_ID,
		IMAGE_MP_TARGET_ID,
		IMAGE_PERISCOPE_RETICULE_ID,
		IMAGE_HEAVY_WEAPON_OVERLAY_ID,
		IMAGE_GAMEPAD_IMAGE_P1_ID,
		IMAGE_GAMEPAD_IMAGE_P2_ID,
		IMAGE_MP_PLANT_TROPHY_ID,
		IMAGE_MP_PLANT_TROPHY_HI_RES_ID,
		IMAGE_MP_ZOMBIE_TROPHY_ID,
		IMAGE_MP_ZOMBIE_TROPHY_HI_RES_ID,
		IMAGE_MP_TROPHY_BASE_ID,
		IMAGE_MP_TROPHY_BASE_HI_RES_ID,
		IMAGE_MP_PLANT_SIDE_ID,
		IMAGE_MP_PLANT_SIDE_SELECTED_ID,
		IMAGE_MP_PLANT_SIDE_PLANTS_ID,
		IMAGE_MP_ZOMBIE_SIDE_ID,
		IMAGE_MP_ZOMBIE_SIDE_SELECTED_ID,
		IMAGE_MP_ZOMBIE_SIDE_ZOMBIES_ID,
		IMAGE_VS_INFO_BOX_PLANTS_ID,
		IMAGE_VS_INFO_BOX_PLANTS_OVERLAY_ID,
		IMAGE_VS_INFO_BOX_ZOMBIES_ID,
		IMAGE_VS_INFO_BOX_ZOMBIES_OVERLAY_ID,
		IMAGE_BUTTER_ICON_ID,
		IMAGE_HAMMER_ICON_ID,
		IMAGE_VS_STONE_DIRT_ID,
		IMAGE_STORE_MUSHROOMGARDENICON_ID,
		IMAGE_STORE_AQUARIUMGARDENICON_ID,
		IMAGE_STORE_TREEOFWISDOMICON_ID,
		IMAGE_STORE_ZENGARDENICON_ID,
		IMAGE_SHOVELMETER_EMTY_ID,
		IMAGE_SHOVELMETER_FULL_ID,
		IMAGE_PROJECTILEPEA_ID,
		IMAGE_PROJECTILESNOWPEA_ID,
		IMAGE_PROJECTILECACTUS_ID,
		IMAGE_DIRTSMALL_ID,
		IMAGE_DIRTBIG_ID,
		IMAGE_ROCKSMALL_ID,
		IMAGE_WATERPARTICLE_ID,
		IMAGE_WHITEWATER_ID,
		IMAGE_WHITEWATER_SHADOW_ID,
		IMAGE_MELONPULT_PARTICLES_ID,
		IMAGE_WINTERMELON_PARTICLES_ID,
		IMAGE_PROJECTILE_STAR_ID,
		IMAGE_SEEDBANK_ID,
		IMAGE_SEEDBANK_COOP_ID,
		IMAGE_CONVEYORBELT_BACKDROP_ID,
		IMAGE_CONVEYORBELT_ID,
		IMAGE_CONVEYORBELT_BACKDROP_COOP_ID,
		IMAGE_CONVEYORBELT_COOP_ID,
		IMAGE_SHOVELBANK_ID,
		IMAGE_SUNBANK_ID,
		IMAGE_COINBANK_ID,
		IMAGE_POOL_ID,
		IMAGE_POOL_NIGHT_ID,
		IMAGE_POOL_BASE_ID,
		IMAGE_POOL_BASE_NIGHT_ID,
		IMAGE_POOL_SHADING_ID,
		IMAGE_POOL_SHADING_NIGHT_ID,
		IMAGE_POOL_CAUSTIC_EFFECT_ID,
		IMAGE_PLANTSHADOW_ID,
		IMAGE_PLANTSHADOW2_ID,
		IMAGE_PEA_SHADOWS_ID,
		IMAGE_WALLNUT_BOWLINGSTRIPE_ID,
		IMAGE_ICE_ID,
		IMAGE_ICE_CAP_ID,
		IMAGE_ICE_SPARKLES_ID,
		IMAGE_IMITATERSEED_ID,
		IMAGE_ALMANAC_IMITATER_ID,
		IMAGE_IMITATERSEEDDISABLED_ID,
		IMAGE_ICETRAP_ID,
		IMAGE_ICETRAP2_ID,
		IMAGE_ICETRAP_PARTICLES_ID,
		IMAGE_ZOMBIE_BOBSLED1_ID,
		IMAGE_ZOMBIE_BOBSLED2_ID,
		IMAGE_ZOMBIE_BOBSLED3_ID,
		IMAGE_ZOMBIE_BOBSLED4_ID,
		IMAGE_ZOMBIE_BOBSLED_INSIDE_ID,
		IMAGE_BUNGEECORD_ID,
		IMAGE_BUNGEETARGET_ID,
		IMAGE_SPOTLIGHT_ID,
		IMAGE_SPOTLIGHT2_ID,
		IMAGE_WHITEPIXEL_ID,
		IMAGE_ZOMBIEPOLEVAULTERHEAD_ID,
		IMAGE_ZOMBIEFOOTBALLHEAD_ID,
		IMAGE_POOLSPARKLY_ID,
		IMAGE_WALLNUTPARTICLESSMALL_ID,
		IMAGE_WALLNUTPARTICLESLARGE_ID,
		IMAGE_PEA_SPLATS_ID,
		IMAGE_STAR_PARTICLES_ID,
		IMAGE_STAR_SPLATS_ID,
		IMAGE_PEA_PARTICLES_ID,
		IMAGE_SNOWPEA_SPLATS_ID,
		IMAGE_SNOWPEA_PARTICLES_ID,
		IMAGE_SNOWPEA_PUFF_ID,
		IMAGE_SNOWFLAKES_ID,
		IMAGE_POTATOMINE_PARTICLES_ID,
		IMAGE_PUFFSHROOM_PUFF1_ID,
		IMAGE_ZAMBONISMOKE_ID,
		IMAGE_ZOMBIEDANCERHEAD_ID,
		IMAGE_ZOMBIEBALLOONHEAD_ID,
		IMAGE_ZOMBIEIMPHEAD_ID,
		IMAGE_ZOMBIEDIGGERHEAD_ID,
		IMAGE_ZOMBIEDIGGERARM_ID,
		IMAGE_ZOMBIEDOLPHINRIDERHEAD_ID,
		IMAGE_ZOMBIEPOGO_ID,
		IMAGE_ZOMBIEBACKUPDANCERHEAD_ID,
		IMAGE_ZOMBIEBOBSLEDHEAD_ID,
		IMAGE_ZOMBIELADDERHEAD_ID,
		IMAGE_ZOMBIEYETIHEAD_ID,
		IMAGE_SEEDPACKETFLASH_ID,
		IMAGE_ZOMBIEJACKBOXARM_ID,
		IMAGE_IMITATERCLOUDS_ID,
		IMAGE_IMITATERPUFFS_ID,
		IMAGE_ZOMBIE_BOSS_FIREBALL_PARTICLES_ID,
		IMAGE_ZOMBIE_BOSS_ICEBALL_PARTICLES_ID,
		IMAGE_ZOMBIE_BOSS_FIREBALL_GROUNDPARTICLES_ID,
		IMAGE_ZOMBIE_BOSS_ICEBALL_GROUNDPARTICLES_ID,
		IMAGE_DOOMSHROOM_EXPLOSION_BASE_ID,
		IMAGE_RAIN_ID,
		IMAGE_VASE_CHUNKS_ID,
		IMAGE_ZOMBOSS_PARTICLES_ID,
		IMAGE_AWARDPICKUPGLOW_ID,
		IMAGE_ZOMBIE_SEAWEED_ID,
		IMAGE_PINATA_ID,
		IMAGE_ZOMBIEFUTUREGLASSES_ID,
		IMAGE_DUST_PUFFS_ID,
		IMAGE_REANIM_WALLNUT_BODY_ID,
		IMAGE_REANIM_WALLNUT_CRACKED1_ID,
		IMAGE_REANIM_WALLNUT_CRACKED2_ID,
		IMAGE_REANIM_TALLNUT_CRACKED1_ID,
		IMAGE_REANIM_TALLNUT_CRACKED2_ID,
		IMAGE_REANIM_PUMPKIN_DAMAGE1_ID,
		IMAGE_REANIM_PUMPKIN_DAMAGE3_ID,
		IMAGE_REANIM_ZOMBIE_CONE1_ID,
		IMAGE_REANIM_ZOMBIE_CONE2_ID,
		IMAGE_REANIM_ZOMBIE_CONE3_ID,
		IMAGE_REANIM_ZOMBIE_BUCKET1_ID,
		IMAGE_REANIM_ZOMBIE_BUCKET2_ID,
		IMAGE_REANIM_ZOMBIE_BUCKET3_ID,
		IMAGE_REANIM_ZOMBIE_DIGGER_HARDHAT_ID,
		IMAGE_REANIM_ZOMBIE_DIGGER_HARDHAT2_ID,
		IMAGE_REANIM_ZOMBIE_DIGGER_HARDHAT3_ID,
		IMAGE_REANIM_ZOMBIE_SCREENDOOR1_ID,
		IMAGE_REANIM_ZOMBIE_SCREENDOOR2_ID,
		IMAGE_REANIM_ZOMBIE_SCREENDOOR3_ID,
		IMAGE_REANIM_ZOMBIE_TRASHCAN1_ID,
		IMAGE_REANIM_ZOMBIE_TRASHCAN2_ID,
		IMAGE_REANIM_ZOMBIE_TRASHCAN3_ID,
		IMAGE_REANIM_ZOMBIE_FLAG1_ID,
		IMAGE_REANIM_ZOMBIE_FLAG3_ID,
		IMAGE_REANIM_ZOMBIE_OUTERARM_UPPER2_ID,
		IMAGE_REANIM_ZOMBIE_FOOTBALL_HELMET_ID,
		IMAGE_REANIM_ZOMBIE_FOOTBALL_HELMET2_ID,
		IMAGE_REANIM_ZOMBIE_FOOTBALL_HELMET3_ID,
		IMAGE_REANIM_ZOMBIE_FOOTBALL_LEFTARM_HAND_ID,
		IMAGE_REANIM_ZOMBIE_FOOTBALL_LEFTARM_UPPER2_ID,
		IMAGE_REANIM_ZOMBIE_PAPER_LEFTARM_UPPER2_ID,
		IMAGE_REANIM_ZOMBIE_PAPER_LEFTARM_LOWER_ID,
		IMAGE_REANIM_ZOMBIE_PAPER_PAPER2_ID,
		IMAGE_REANIM_ZOMBIE_PAPER_PAPER3_ID,
		IMAGE_REANIM_ZOMBIE_PAPER_MADHEAD_ID,
		IMAGE_REANIM_ZOMBIE_ZAMBONI_1_DAMAGE1_ID,
		IMAGE_REANIM_ZOMBIE_ZAMBONI_1_DAMAGE2_ID,
		IMAGE_REANIM_ZOMBIE_ZAMBONI_2_DAMAGE1_ID,
		IMAGE_REANIM_ZOMBIE_ZAMBONI_2_DAMAGE2_ID,
		IMAGE_REANIM_ZOMBIE_ZAMBONI_WHEEL_FLAT_ID,
		IMAGE_REANIM_COIN_SILVER_DOLLAR_ID,
		IMAGE_REANIM_COIN_GOLD_DOLLAR_ID,
		IMAGE_REANIM_DIAMOND_ID,
		IMAGE_REANIM_COINGLOW_ID,
		IMAGE_REANIM_ZOMBIE_DISCO_OUTERARM_HAND_ID,
		IMAGE_REANIM_ZOMBIE_DISCO_OUTERARM_UPPER2_ID,
		IMAGE_REANIM_ZOMBIE_BACKUP_INNERARM_HAND_ID,
		IMAGE_REANIM_ZOMBIE_BACKUP_OUTERARM_UPPER2_ID,
		IMAGE_REANIM_ZOMBIE_POLEVAULTER_OUTERARM_UPPER2_ID,
		IMAGE_REANIM_ZOMBIE_OUTERARM_HAND_ID,
		IMAGE_REANIM_ZOMBIE_BALLOON_OUTERARM_UPPER2_ID,
		IMAGE_REANIM_ZOMBIE_IMP_ARM1_BONE_ID,
		IMAGE_REANIM_ZOMBIE_IMP_ARM2_ID,
		IMAGE_REANIM_ZOMBIE_GARGANTUAR_BODY1_2_ID,
		IMAGE_REANIM_ZOMBIE_GARGANTUAR_BODY1_3_ID,
		IMAGE_REANIM_ZOMBIE_GARGANTUAR_DUCKXING_ID,
		IMAGE_REANIM_ZOMBIE_GARGANTUAR_ZOMBIE_ID,
		IMAGE_REANIM_ZOMBIE_GARGANTUAR_FOOT2_ID,
		IMAGE_REANIM_ZOMBIE_GARGANTUAR_HEAD2_ID,
		IMAGE_REANIM_ZOMBIE_GARGANTUAR_OUTERARM_LOWER2_ID,
		IMAGE_REANIM_ZOMBIE_GARGANTUAR_HEAD2_REDEYE_ID,
		IMAGE_REANIM_ZOMBIE_GARGANTUAR_HEAD_REDEYE_ID,
		IMAGE_REANIM_ZOMBIE_DIGGER_OUTERARM_UPPER2_ID,
		IMAGE_REANIM_ZOMBIE_DOLPHINRIDER_OUTERARM_UPPER2_ID,
		IMAGE_REANIM_ZOMBIE_POGO_OUTERARM_UPPER2_ID,
		IMAGE_REANIM_ZOMBIE_POGO_STICKDAMAGE1_ID,
		IMAGE_REANIM_ZOMBIE_POGO_STICKDAMAGE2_ID,
		IMAGE_REANIM_ZOMBIE_POGO_STICK2DAMAGE1_ID,
		IMAGE_REANIM_ZOMBIE_POGO_STICK2DAMAGE2_ID,
		IMAGE_REANIM_ZOMBIE_POGO_STICKHANDS2_ID,
		IMAGE_REANIM_ZOMBIE_BOBSLED_OUTERARM_UPPER2_ID,
		IMAGE_REANIM_ZOMBIE_BOBSLED_OUTERARM_HAND_ID,
		IMAGE_REANIM_ZOMBIE_JACKBOX_BOX_ID,
		IMAGE_REANIM_ZOMBIE_JACKBOX_OUTERARM_LOWER2_ID,
		IMAGE_REANIM_ZOMBIE_SNORKLE_OUTERARM_UPPER2_ID,
		IMAGE_REANIM_ZOMBIE_BUNGI_HEAD_SCARED_ID,
		IMAGE_REANIM_ZOMBIE_CATAPULT_BASKETBALL_ID,
		IMAGE_REANIM_ZOMBIE_CATAPULT_POLE_ID,
		IMAGE_REANIM_ZOMBIE_CATAPULT_POLE_DAMAGE_ID,
		IMAGE_REANIM_ZOMBIE_CATAPULT_POLE_WITHBALL_ID,
		IMAGE_REANIM_ZOMBIE_CATAPULT_POLE_DAMAGE_WITHBALL_ID,
		IMAGE_REANIM_ZOMBIE_CATAPULT_SIDING_DAMAGE_ID,
		IMAGE_REANIM_ZOMBIE_LADDER_1_ID,
		IMAGE_REANIM_ZOMBIE_LADDER_1_DAMAGE1_ID,
		IMAGE_REANIM_ZOMBIE_LADDER_1_DAMAGE2_ID,
		IMAGE_REANIM_ZOMBIE_LADDER_5_ID,
		IMAGE_REANIM_ZOMBIE_LADDER_OUTERARM_UPPER2_ID,
		IMAGE_REANIM_ZOMBIE_BOSS_ICEBALL_ID,
		IMAGE_REANIM_ZOMBIE_BOSS_HEAD_DAMAGE1_ID,
		IMAGE_REANIM_ZOMBIE_BOSS_HEAD_DAMAGE2_ID,
		IMAGE_REANIM_ZOMBIE_BOSS_JAW_DAMAGE1_ID,
		IMAGE_REANIM_ZOMBIE_BOSS_JAW_DAMAGE2_ID,
		IMAGE_REANIM_ZOMBIE_BOSS_OUTERARM_HAND_DAMAGE1_ID,
		IMAGE_REANIM_ZOMBIE_BOSS_OUTERARM_HAND_DAMAGE2_ID,
		IMAGE_REANIM_ZOMBIE_BOSS_OUTERARM_THUMB_DAMAGE1_ID,
		IMAGE_REANIM_ZOMBIE_BOSS_OUTERARM_THUMB_DAMAGE2_ID,
		IMAGE_REANIM_ZOMBIE_BOSS_FOOT_DAMAGE1_ID,
		IMAGE_REANIM_ZOMBIE_BOSS_FOOT_DAMAGE2_ID,
		IMAGE_REANIM_ZOMBIE_BOSS_EYEGLOW_BLUE_ID,
		IMAGE_REANIM_ZOMBIE_BOSS_MOUTHGLOW_BLUE_ID,
		IMAGE_REANIM_CABBAGEPULT_CABBAGE_ID,
		IMAGE_REANIM_CORNPULT_KERNAL_ID,
		IMAGE_REANIM_CORNPULT_BUTTER_ID,
		IMAGE_REANIM_CORNPULT_BUTTER_SPLAT_ID,
		IMAGE_REANIM_MELONPULT_MELON_ID,
		IMAGE_REANIM_WINTERMELON_PROJECTILE_ID,
		IMAGE_REANIM_ZOMBIE_DIGGER_PICKAXE_ID,
		IMAGE_REANIM_ZOMBIE_HEAD_GROSSOUT_ID,
		IMAGE_REANIM_ZOMBIE_HEAD_SUNGLASSES1_ID,
		IMAGE_REANIM_ZOMBIE_HEAD_SUNGLASSES2_ID,
		IMAGE_REANIM_ZOMBIE_HEAD_SUNGLASSES3_ID,
		IMAGE_REANIM_ZOMBIE_HEAD_SUNGLASSES4_ID,
		IMAGE_REANIM_GARLIC_BODY2_ID,
		IMAGE_REANIM_GARLIC_BODY3_ID,
		IMAGE_REANIM_COBCANNON_COB_ID,
		IMAGE_REANIM_ZOMBIE_YETI_OUTERARM_UPPER2_ID,
		IMAGE_REANIM_ZOMBIE_YETI_OUTERARM_HAND_ID,
		IMAGE_REANIM_ZOMBIE_SNORKLE_HEAD_ID,
		IMAGE_REANIM_TREE_BG_ID,
		IMAGE_REANIM_POT_TOP_DARK_ID,
		IMAGE_REANIM_ZENGARDEN_BUGSPRAY_BOTTLE_ID,
		IMAGE_REANIM_STINKY_TURN3_ID,
		IMAGE_REANIM_CRAZYDAVE_MOUTH1_ID,
		IMAGE_REANIM_CRAZYDAVE_MOUTH4_ID,
		IMAGE_REANIM_CRAZYDAVE_MOUTH5_ID,
		IMAGE_REANIM_CRAZYDAVE_MOUTH6_ID,
		IMAGE_REANIM_ZOMBIE_MUSTACHE2_ID,
		IMAGE_REANIM_ZOMBIE_MUSTACHE3_ID,
		IMAGE_REANIM_POINT_ID,
		IMAGE_REANIM_SELECTORSCREEN_CLOUD1_ID,
		IMAGE_REANIM_SELECTORSCREEN_CLOUD2_ID,
		IMAGE_REANIM_SELECTORSCREEN_CLOUD4_ID,
		IMAGE_REANIM_SELECTORSCREEN_CLOUD5_ID,
		IMAGE_REANIM_SELECTORSCREEN_CLOUD6_ID,
		IMAGE_REANIM_SELECTORSCREEN_CLOUD7_ID,
		IMAGE_HOUSE_SKY_ID,
		IMAGE_HOUSE_HILL_ID,
		IMAGE_HOUSE_SIDEWALK_ID,
		IMAGE_TRASHCAN_ZOMBIES_ID,
		IMAGE_TRASHCAN_PLANTS_ID,
		IMAGE_ZOMBIE_LAYER_TEST_ID,
		IMAGE_ZOMBIE_LAYER_1_1_ID,
		IMAGE_ZOMBIE_LAYER_1_2_ID,
		IMAGE_ZOMBIE_LAYER_1_3_ID,
		IMAGE_ZOMBIE_LAYER_2_1_ID,
		IMAGE_ZOMBIE_LAYER_2_2_ID,
		IMAGE_ZOMBIE_LAYER_2_3_ID,
		IMAGE_ZOMBIE_LAYER_3_1_ID,
		IMAGE_ZOMBIE_LAYER_3_2_ID,
		IMAGE_ZOMBIE_LAYER_3_3_ID,
		IMAGE_PLANT_LAYER_1_1_ID,
		IMAGE_PLANT_LAYER_1_2_ID,
		IMAGE_PLANT_LAYER_2_1_ID,
		IMAGE_PLANT_LAYER_2_2_ID,
		IMAGE_PLANT_LAYER_3_1_ID,
		IMAGE_PLANT_LAYER_3_2_ID,
		IMAGE_CHALLENGE_WINDOW_ID,
		IMAGE_CHALLENGE_WINDOW_HIGHLIGHT_ID,
		IMAGE_CHALLENGE_BLANK_ID,
		IMAGE_CHALLENGE_THUMBNAILS_ID,
		IMAGE_SURVIVAL_THUMBNAILS_ID,
		IMAGE_LOCK_ID,
		IMAGE_LOCK_OPEN_ID,
		IMAGE_ZOMBIE_HEAD_ID,
		IMAGE_LEADERBOARD_HOLE_ID,
		IMAGE_LEADERBOARD_HOLE_PIPE_ID,
		IMAGE_LEADERBOARD_HOLE_WORM_ID,
		IMAGE_LEADERBOARD_HOLE_GEMS_ID,
		IMAGE_LEADERBOARD_HOLE_CHINA_ID,
		IMAGE_LEADERBOARD_HOLE_ROCKS_ID,
		IMAGE_LEADERBOARD_HOLE_TIKI_ID,
		IMAGE_LEADERBOARD_HOLE_BJORN_ID,
		IMAGE_LEADERBOARD_HEADER_SMALL_ID,
		IMAGE_LEADERBOARD_HEADER_LARGE_ID,
		IMAGE_LEADERBOARD_SELECTOR_ID,
		IMAGE_LEADERBOARD_FILL_ID,
		IMAGE_ALMANAC_PLANTS_BOTTOMGRADIENT_ID,
		IMAGE_ALMANAC_PLANTS_TOPGRADIENT_ID,
		IMAGE_ALMANAC_ROUNDED_OUTLINE_ID,
		IMAGE_SCROLL_INDICATOR_ID,
		IMAGE_ZOMBATAR_SIGN_ID,
		IMAGE_ZOMBATAR_SIGN_PRESSED_ID,
		IMAGE_SLOTMACHINE_BALL_TOUCH_ID,
		SOUND_AWOOGA_ID,
		SOUND_BLEEP_ID,
		SOUND_BUZZER_ID,
		SOUND_CHOMP_ID,
		SOUND_CHOMP2_ID,
		SOUND_CHOMPSOFT_ID,
		SOUND_EVILLAUGH_ID,
		SOUND_FLOOP_ID,
		SOUND_FROZEN_ID,
		SOUND_GULP_ID,
		SOUND_GROAN_ID,
		SOUND_GROAN2_ID,
		SOUND_GROAN3_ID,
		SOUND_GROAN4_ID,
		SOUND_GROAN5_ID,
		SOUND_GROAN6_ID,
		SOUND_LOSEMUSIC_ID,
		SOUND_MINDCONTROLLED_ID,
		SOUND_PAUSE_ID,
		SOUND_PLANT_ID,
		SOUND_PLANT2_ID,
		SOUND_POINTS_ID,
		SOUND_SEEDLIFT_ID,
		SOUND_SIREN_ID,
		SOUND_SLURP_ID,
		SOUND_SPLAT_ID,
		SOUND_SPLAT2_ID,
		SOUND_SPLAT3_ID,
		SOUND_SUKHBIR_ID,
		SOUND_SUKHBIR2_ID,
		SOUND_SUKHBIR3_ID,
		SOUND_SUKHBIR4_ID,
		SOUND_SUKHBIR5_ID,
		SOUND_SUKHBIR6_ID,
		SOUND_TAP_ID,
		SOUND_TAP2_ID,
		SOUND_THROW_ID,
		SOUND_THROW2_ID,
		SOUND_BLOVER_ID,
		SOUND_WINMUSIC_ID,
		SOUND_LAWNMOWER_ID,
		SOUND_BOING_ID,
		SOUND_JACKINTHEBOX_ID,
		SOUND_DIAMOND_ID,
		SOUND_DOLPHIN_APPEARS_ID,
		SOUND_DOLPHIN_BEFORE_JUMPING_ID,
		SOUND_POTATO_MINE_ID,
		SOUND_ZAMBONI_ID,
		SOUND_BALLOON_POP_ID,
		SOUND_THUNDER_ID,
		SOUND_ZOMBIESPLASH_ID,
		SOUND_BOWLING_ID,
		SOUND_BOWLINGIMPACT_ID,
		SOUND_BOWLINGIMPACT2_ID,
		SOUND_GRAVEBUSTERCHOMP_ID,
		SOUND_GRAVEBUTTON_ID,
		SOUND_LIMBS_POP_ID,
		SOUND_PLANTERN_ID,
		SOUND_POGO_ZOMBIE_ID,
		SOUND_SNOW_PEA_SPARKLES_ID,
		SOUND_PLANT_WATER_ID,
		SOUND_ZOMBIE_ENTERING_WATER_ID,
		SOUND_ZOMBIE_FALLING_1_ID,
		SOUND_ZOMBIE_FALLING_2_ID,
		SOUND_ACHIEVEMENT_ID,
		SOUND_PUFF_ID,
		SOUND_FUME_ID,
		SOUND_HUGE_WAVE_ID,
		SOUND_SLOT_MACHINE_ID,
		SOUND_COIN_ID,
		SOUND_ROLL_IN_ID,
		SOUND_DIGGER_ZOMBIE_ID,
		SOUND_HATCHBACK_CLOSE_ID,
		SOUND_HATCHBACK_OPEN_ID,
		SOUND_KERNELPULT_ID,
		SOUND_KERNELPULT2_ID,
		SOUND_ZOMBAQUARIUM_DIE_ID,
		SOUND_BUNGEE_SCREAM_ID,
		SOUND_BUNGEE_SCREAM2_ID,
		SOUND_BUNGEE_SCREAM3_ID,
		SOUND_BUTTER_ID,
		SOUND_JACK_SURPRISE_ID,
		SOUND_JACK_SURPRISE2_ID,
		SOUND_NEWSPAPER_RARRGH_ID,
		SOUND_NEWSPAPER_RARRGH2_ID,
		SOUND_NEWSPAPER_RIP_ID,
		SOUND_SQUASH_HMM_ID,
		SOUND_SQUASH_HMM2_ID,
		SOUND_VASE_BREAKING_ID,
		SOUND_POOL_CLEANER_ID,
		SOUND_MAGNETSHROOM_ID,
		SOUND_LADDER_ZOMBIE_ID,
		SOUND_GARGANTUAR_THUMP_ID,
		SOUND_BASKETBALL_ID,
		SOUND_FIREPEA_ID,
		SOUND_IGNITE_ID,
		SOUND_IGNITE2_ID,
		SOUND_READYSETPLANT_ID,
		SOUND_DOOMSHROOM_ID,
		SOUND_EXPLOSION_ID,
		SOUND_FINALWAVE_ID,
		SOUND_REVERSE_EXPLOSION_ID,
		SOUND_RVTHROW_ID,
		SOUND_SHIELDHIT_ID,
		SOUND_SHIELDHIT2_ID,
		SOUND_BOSSEXPLOSION_ID,
		SOUND_CHERRYBOMB_ID,
		SOUND_BONK_ID,
		SOUND_SWING_ID,
		SOUND_RAIN_ID,
		SOUND_LIGHTFILL_ID,
		SOUND_PLASTICHIT_ID,
		SOUND_PLASTICHIT2_ID,
		SOUND_JALAPENO_ID,
		SOUND_BALLOONINFLATE_ID,
		SOUND_BIGCHOMP_ID,
		SOUND_MELONIMPACT_ID,
		SOUND_MELONIMPACT2_ID,
		SOUND_PLANTGROW_ID,
		SOUND_SHOOP_ID,
		SOUND_TAPGLASS_ID,
		SOUND_JUICY_ID,
		SOUND_COFFEE_ID,
		SOUND_WAKEUP_ID,
		SOUND_LOWGROAN_ID,
		SOUND_LOWGROAN2_ID,
		SOUND_PRIZE_ID,
		SOUND_YUCK_ID,
		SOUND_YUCK2_ID,
		SOUND_GRASSSTEP_ID,
		SOUND_SHOVEL_ID,
		SOUND_COBLAUNCH_ID,
		SOUND_WATERING_ID,
		SOUND_POLEVAULT_ID,
		SOUND_GRAVESTONE_RUMBLE_ID,
		SOUND_DIRT_RISE_ID,
		SOUND_FERTILIZER_ID,
		SOUND_PORTAL_ID,
		SOUND_BUGSPRAY_ID,
		SOUND_SCREAM_ID,
		SOUND_PAPER_ID,
		SOUND_MONEYFALLS_ID,
		SOUND_IMP_ID,
		SOUND_IMP2_ID,
		SOUND_HYDRAULIC_SHORT_ID,
		SOUND_HYDRAULIC_ID,
		SOUND_GARGANTUDEATH_ID,
		SOUND_CERAMIC_ID,
		SOUND_BOSSBOULDERATTACK_ID,
		SOUND_CHIME_ID,
		SOUND_CRAZYDAVESHORT1_ID,
		SOUND_CRAZYDAVESHORT2_ID,
		SOUND_CRAZYDAVESHORT3_ID,
		SOUND_CRAZYDAVELONG1_ID,
		SOUND_CRAZYDAVELONG2_ID,
		SOUND_CRAZYDAVELONG3_ID,
		SOUND_CRAZYDAVEEXTRALONG1_ID,
		SOUND_CRAZYDAVEEXTRALONG2_ID,
		SOUND_CRAZYDAVEEXTRALONG3_ID,
		SOUND_CRAZYDAVECRAZY_ID,
		SOUND_PHONOGRAPH_ID,
		SOUND_DANCER_ID,
		SOUND_FINALFANFARE_ID,
		SOUND_CRAZYDAVESCREAM_ID,
		SOUND_CRAZYDAVESCREAM2_ID,
		SOUND_MP_TIMER_ID,
		SOUND_CROW_FLAP1_ID,
		SOUND_CROW_FLAP2_ID,
		SOUND_CROW_FLAP3_ID,
		SOUND_CROW_CAW1_ID,
		SOUND_CROW_CAW2_ID,
		SOUND_CROW_CAW3_ID,
		SOUND_THUNDER_1_ID,
		SOUND_THUNDER_2_ID,
		SOUND_THUNDER_3_ID,
		SOUND_THUNDER_1R_ID,
		SOUND_THUNDER_2R_ID,
		SOUND_THUNDER_3R_ID,
		SOUND_MINIGAMES_ID,
		SOUND_PUZZLE_ID,
		SOUND_SURVIVAL_ID,
		SOUND_COOP_ID,
		SOUND_VS_ID,
		SOUND_MENU_L_ST_ID,
		SOUND_MENU_C_ST_ID,
		SOUND_MENU_R_ST_ID,
		SOUND_SHOP_ID,
		SOUND_ZEN_ID,
		SOUND_MAIL_ID,
		SOUND_ALMANAC_ID,
		SOUND_VS_HEADPOP_ID,
		SOUND_BIGTHUD_ID,
		IMAGE_BACKGROUND1_ID,
		IMAGE_BACKGROUND1_COVER_ID,
		IMAGE_BACKGROUND1_GAMEOVER_INTERIOR_OVERLAY_ID,
		IMAGE_BACKGROUND1_GAMEOVER_MASK_ID,
		IMAGE_BACKGROUND1UNSODDED_ID,
		IMAGE_SOD1ROW_ID,
		IMAGE_SOD3ROW_ID,
		IMAGE_BACKGROUND2_ID,
		IMAGE_BACKGROUND2_COVER_ID,
		IMAGE_BACKGROUND2_GAMEOVER_INTERIOR_OVERLAY_ID,
		IMAGE_BACKGROUND2_GAMEOVER_MASK_ID,
		IMAGE_BACKGROUND3_ID,
		IMAGE_BACKGROUND3_COVER_ID,
		IMAGE_BACKGROUND3_GAMEOVER_INTERIOR_OVERLAY_ID,
		IMAGE_BACKGROUND3_GAMEOVER_MASK_ID,
		IMAGE_BACKGROUND4_ID,
		IMAGE_BACKGROUND4_COVER_ID,
		IMAGE_BACKGROUND4_GAMEOVER_INTERIOR_OVERLAY_ID,
		IMAGE_BACKGROUND4_GAMEOVER_MASK_ID,
		IMAGE_FOG_ID,
		IMAGE_FOG_SOFTWARE_ID,
		IMAGE_BACKGROUND5_ID,
		IMAGE_BACKGROUND5_GAMEOVER_MASK_ID,
		IMAGE_ROOF_POLE_ID,
		IMAGE_ROOF_TREE_ID,
		IMAGE_BACKGROUND6BOSS_ID,
		IMAGE_BACKGROUND6_GAMEOVER_MASK_ID,
		IMAGE_BACKGROUND_MUSHROOMGARDEN_ID,
		IMAGE_BACKGROUND_GREENHOUSE_ID,
		IMAGE_BACKGROUND_GREENHOUSE_OVERLAY_ID,
		IMAGE_AQUARIUM1_ID,
		IMAGE_WAVECENTER_ID,
		IMAGE_WAVESIDE_ID,
		IMAGE_AWARDSCREEN_BACK_ID,
		IMAGE_ALMANAC_INDEXBACK_ID,
		IMAGE_ALMANAC_PLANTBACK_ID,
		IMAGE_ALMANAC_ZOMBIEBACK_ID,
		IMAGE_ALMANAC_PLANTCARD_ID,
		IMAGE_ALMANAC_PLANTBLANK_ID,
		IMAGE_ALMANAC_ZOMBIECARD_ID,
		IMAGE_ALMANAC_ZOMBIEWINDOW_ID,
		IMAGE_ALMANAC_ZOMBIEWINDOW2_ID,
		IMAGE_ALMANAC_ZOMBIEBLANK_ID,
		IMAGE_ALMANAC_GROUNDDAY_ID,
		IMAGE_ALMANAC_GROUNDNIGHT_ID,
		IMAGE_ALMANAC_GROUNDPOOL_ID,
		IMAGE_ALMANAC_GROUNDNIGHTPOOL_ID,
		IMAGE_ALMANAC_GROUNDROOF_ID,
		IMAGE_ALMANAC_GROUNDICE_ID,
		IMAGE_STORE_BACKGROUND_ID,
		IMAGE_STORE_BACKGROUNDNIGHT_ID,
		IMAGE_STORE_CAR_ID,
		IMAGE_STORE_CAR_NIGHT_ID,
		IMAGE_STORE_CARCLOSED_ID,
		IMAGE_STORE_CARCLOSED_NIGHT_ID,
		IMAGE_STORE_CAR_LICENSE0_ID,
		IMAGE_STORE_CAR_LICENSE1_ID,
		IMAGE_STORE_CAR_LICENSE2_ID,
		IMAGE_STORE_CAR_LICENSE3_ID,
		IMAGE_STORE_CAR_LICENSE4_ID,
		IMAGE_STORE_CAR_LICENSE5_ID,
		IMAGE_STORE_CAR_LICENSE6_ID,
		IMAGE_STORE_CAR_LICENSE7_ID,
		IMAGE_STORE_CAR_LICENSE8_ID,
		IMAGE_STORE_CAR_LICENSE9_ID,
		IMAGE_STORE_CAR_LICENSE10_ID,
		IMAGE_STORE_CAR_LICENSE11_ID,
		IMAGE_STORE_HATCHBACKOPEN_ID,
		IMAGE_STORE_SIGN_ID,
		IMAGE_STORE_MAINMENUBUTTON_ID,
		IMAGE_STORE_MAINMENUBUTTONDOWN_ID,
		IMAGE_STORE_MAINMENUBUTTONHIGHLIGHT_ID,
		IMAGE_STORE_NEXTBUTTON_ID,
		IMAGE_STORE_NEXTBUTTONHIGHLIGHT_ID,
		IMAGE_STORE_NEXTBUTTONDISABLED_ID,
		IMAGE_STORE_PREVBUTTON_ID,
		IMAGE_STORE_PREVBUTTONHIGHLIGHT_ID,
		IMAGE_STORE_PREVBUTTONDISABLED_ID,
		IMAGE_STORE_PRICETAG_ID,
		IMAGE_STORE_FIRSTAIDWALLNUTICON_ID,
		IMAGE_STORE_PVZICON_ID,
		IMAGE_STORE_COMING_SOON_ID,
		IMAGE_STORE_SOLD_OUT_ID,
		IMAGE_STORE_EXTRA_SLOT_ID,
		IMAGE_STORESEEDPACK_CATTAIL_ID,
		IMAGE_STORESEEDPACK_COBCANNON_ID,
		IMAGE_STORESEEDPACK_DOUBLESUNFLOWER_ID,
		IMAGE_STORESEEDPACK_FROZENWATERMELON_ID,
		IMAGE_STORESEEDPACK_GLOOMSHROOM_ID,
		IMAGE_STORESEEDPACK_GOLDMAGNET_ID,
		IMAGE_STORESEEDPACK_IMITATER_ID,
		IMAGE_STORESEEDPACK_REPEATER_ID,
		IMAGE_STORESEEDPACK_SPIKEROCK_ID,
		IMAGE_STORE_PACKETUPGRADE_ID,
		IMAGE_STORE_TOUCH_MAINMENUBUTTON_ID,
		IMAGE_STORE_TOUCH_MAINMENUBUTTONDOWN_ID,
		IMAGE_STORE_TOUCH_CONTINUEBUTTON_ID,
		IMAGE_STORE_TOUCH_CONTINUEBUTTONDOWN_ID,
		IMAGE_STORE_TOUCH_NEXTBUTTON_ID,
		IMAGE_STORE_TOUCH_NEXTBUTTONHIGHLIGHT_ID,
		IMAGE_STORE_TOUCH_PREVBUTTON_ID,
		IMAGE_STORE_TOUCH_PREVBUTTONHIGHLIGHT_ID,
		IMAGE_ZOMBIE_NOTE_ID,
		IMAGE_ZOMBIE_NOTE1_ID,
		IMAGE_ZOMBIE_NOTE2_ID,
		IMAGE_ZOMBIE_NOTE3_ID,
		IMAGE_ZOMBIE_NOTE4_ID,
		IMAGE_ZOMBIE_FINAL_NOTE_ID,
		IMAGE_ZOMBIE_NOTE_HELP_ID,
		IMAGE_REANIM_SUNFLOWER_HEAD_SING1_ID,
		IMAGE_REANIM_SUNFLOWER_HEAD_SING2_ID,
		IMAGE_REANIM_SUNFLOWER_HEAD_SING3_ID,
		IMAGE_REANIM_SUNFLOWER_HEAD_SING4_ID,
		IMAGE_REANIM_SUNFLOWER_HEAD_SING5_ID,
		IMAGE_REANIM_SUNFLOWER_HEAD_WINK_ID,
		IMAGE_REANIM_CREDITS_DISCOLIGHTS_ID,
		IMAGE_REANIM_CREDITS_FOGMACHINE_ID,
		IMAGE_CREDITS_ZOMBIENOTE_ID,
		IMAGE_CREDITS_PLAYBUTTON_ID,
		IMAGE_ZOMBATAR_ACCESSORY_BG_ID,
		IMAGE_ZOMBATAR_PREV_BUTTON_ID,
		IMAGE_ZOMBATAR_PREV_BUTTON_HIGHLIGHT_ID,
		IMAGE_ZOMBATAR_NEXT_BUTTON_ID,
		IMAGE_ZOMBATAR_NEXT_BUTTON_HIGHLIGHT_ID,
		IMAGE_ZOMBATAR_ZOMBIE_BLANK_ID,
		IMAGE_ZOMBATAR_ZOMBIE_BLANK_SKIN_ID,
		IMAGE_ZOMBATAR_BACKGROUND_CRAZYDAVE_ID,
		IMAGE_ZOMBATAR_BACKGROUND_MENU_ID,
		IMAGE_ZOMBATAR_BACKGROUND_MENU_DOS_ID,
		IMAGE_ZOMBATAR_BACKGROUND_ROOF_ID,
		IMAGE_ZOMBATAR_WIDGET_BG_ID,
		IMAGE_ZOMBATAR_WIDGET_INNER_BG_ID,
		IMAGE_ZOMBATAR_COLORS_BG_ID,
		IMAGE_ZOMBATAR_LOGO_ID,
		IMAGE_ZOMBATAR_ACCESSORY_BUTTON_ID,
		IMAGE_ZOMBATAR_ACCESSORY_BUTTON_HIGHLIGHT_ID,
		IMAGE_ZOMBATAR_ACCESSORY_BUTTON_OVER_ID,
		IMAGE_ZOMBATAR_BACKDROPS_BUTTON_ID,
		IMAGE_ZOMBATAR_BACKDROPS_BUTTON_HIGHLIGHT_ID,
		IMAGE_ZOMBATAR_BACKDROPS_BUTTON_OVER_ID,
		IMAGE_ZOMBATAR_CLOTHES_BUTTON_ID,
		IMAGE_ZOMBATAR_CLOTHES_BUTTON_HIGHLIGHT_ID,
		IMAGE_ZOMBATAR_CLOTHES_BUTTON_OVER_ID,
		IMAGE_ZOMBATAR_EYEWEAR_BUTTON_ID,
		IMAGE_ZOMBATAR_EYEWEAR_BUTTON_HIGHLIGHT_ID,
		IMAGE_ZOMBATAR_EYEWEAR_BUTTON_OVER_ID,
		IMAGE_ZOMBATAR_FACIAL_HAIR_BUTTON_ID,
		IMAGE_ZOMBATAR_FACIAL_HAIR_BUTTON_HIGHLIGHT_ID,
		IMAGE_ZOMBATAR_FACIAL_HAIR_BUTTON_OVER_ID,
		IMAGE_ZOMBATAR_HAIR_BUTTON_ID,
		IMAGE_ZOMBATAR_HAIR_BUTTON_HIGHLIGHT_ID,
		IMAGE_ZOMBATAR_HAIR_BUTTON_OVER_ID,
		IMAGE_ZOMBATAR_HATS_BUTTON_ID,
		IMAGE_ZOMBATAR_HATS_BUTTON_HIGHLIGHT_ID,
		IMAGE_ZOMBATAR_HATS_BUTTON_OVER_ID,
		IMAGE_ZOMBATAR_SKIN_BUTTON_ID,
		IMAGE_ZOMBATAR_SKIN_BUTTON_HIGHLIGHT_ID,
		IMAGE_ZOMBATAR_TIDBITS_BUTTON_ID,
		IMAGE_ZOMBATAR_TIDBITS_BUTTON_HIGHLIGHT_ID,
		IMAGE_ZOMBATAR_TIDBITS_BUTTON_OVER_ID,
		IMAGE_ZOMBATAR_ACCESSORY_BG_HIGHLIGHT_ID,
		IMAGE_ZOMBATAR_TRIPTYCH_ID,
		IMAGE_ZOMBATAR_COLORPICKER_ID,
		IMAGE_ZOMBATAR_COLORPICKER_HIGHLIGHT_ID,
		IMAGE_ZOMBATAR_COLORPICKER_NONE_ID,
		IMAGE_ZOMBATAR_ACCESSORY_BG_NONE_ID,
		IMAGE_ZOMBATAR_COLORS_BG_SMALL_ID,
		IMAGE_ZOMBATAR_CLOTHES_1_ID,
		IMAGE_ZOMBATAR_CLOTHES_2_ID,
		IMAGE_ZOMBATAR_CLOTHES_3_ID,
		IMAGE_ZOMBATAR_CLOTHES_4_ID,
		IMAGE_ZOMBATAR_CLOTHES_5_ID,
		IMAGE_ZOMBATAR_CLOTHES_6_ID,
		IMAGE_ZOMBATAR_CLOTHES_7_ID,
		IMAGE_ZOMBATAR_CLOTHES_8_ID,
		IMAGE_ZOMBATAR_CLOTHES_9_ID,
		IMAGE_ZOMBATAR_CLOTHES_10_ID,
		IMAGE_ZOMBATAR_CLOTHES_11_ID,
		IMAGE_ZOMBATAR_CLOTHES_12_ID,
		IMAGE_ZOMBATAR_HATS_1_ID,
		IMAGE_ZOMBATAR_HATS_2_ID,
		IMAGE_ZOMBATAR_HATS_3_ID,
		IMAGE_ZOMBATAR_HATS_4_ID,
		IMAGE_ZOMBATAR_HATS_5_ID,
		IMAGE_ZOMBATAR_HATS_6_ID,
		IMAGE_ZOMBATAR_HATS_7_ID,
		IMAGE_ZOMBATAR_HATS_8_ID,
		IMAGE_ZOMBATAR_HATS_9_ID,
		IMAGE_ZOMBATAR_HATS_10_ID,
		IMAGE_ZOMBATAR_HATS_11_ID,
		IMAGE_ZOMBATAR_HATS_12_ID,
		IMAGE_ZOMBATAR_HATS_13_ID,
		IMAGE_ZOMBATAR_HATS_14_ID,
		IMAGE_ZOMBATAR_HAIR_1_ID,
		IMAGE_ZOMBATAR_HAIR_2_ID,
		IMAGE_ZOMBATAR_HAIR_3_ID,
		IMAGE_ZOMBATAR_HAIR_4_ID,
		IMAGE_ZOMBATAR_HAIR_5_ID,
		IMAGE_ZOMBATAR_HAIR_6_ID,
		IMAGE_ZOMBATAR_HAIR_7_ID,
		IMAGE_ZOMBATAR_HAIR_8_ID,
		IMAGE_ZOMBATAR_HAIR_9_ID,
		IMAGE_ZOMBATAR_HAIR_10_ID,
		IMAGE_ZOMBATAR_HAIR_11_ID,
		IMAGE_ZOMBATAR_HAIR_12_ID,
		IMAGE_ZOMBATAR_HAIR_13_ID,
		IMAGE_ZOMBATAR_HAIR_14_ID,
		IMAGE_ZOMBATAR_HAIR_15_ID,
		IMAGE_ZOMBATAR_HAIR_16_ID,
		IMAGE_ZOMBATAR_EYEWEAR_1_ID,
		IMAGE_ZOMBATAR_EYEWEAR_2_ID,
		IMAGE_ZOMBATAR_EYEWEAR_3_ID,
		IMAGE_ZOMBATAR_EYEWEAR_4_ID,
		IMAGE_ZOMBATAR_EYEWEAR_5_ID,
		IMAGE_ZOMBATAR_EYEWEAR_6_ID,
		IMAGE_ZOMBATAR_EYEWEAR_7_ID,
		IMAGE_ZOMBATAR_EYEWEAR_8_ID,
		IMAGE_ZOMBATAR_EYEWEAR_9_ID,
		IMAGE_ZOMBATAR_EYEWEAR_10_ID,
		IMAGE_ZOMBATAR_EYEWEAR_11_ID,
		IMAGE_ZOMBATAR_EYEWEAR_12_ID,
		IMAGE_ZOMBATAR_EYEWEAR_13_ID,
		IMAGE_ZOMBATAR_EYEWEAR_14_ID,
		IMAGE_ZOMBATAR_EYEWEAR_15_ID,
		IMAGE_ZOMBATAR_EYEWEAR_16_ID,
		IMAGE_ZOMBATAR_FACIALHAIR_1_ID,
		IMAGE_ZOMBATAR_FACIALHAIR_2_ID,
		IMAGE_ZOMBATAR_FACIALHAIR_3_ID,
		IMAGE_ZOMBATAR_FACIALHAIR_4_ID,
		IMAGE_ZOMBATAR_FACIALHAIR_5_ID,
		IMAGE_ZOMBATAR_FACIALHAIR_6_ID,
		IMAGE_ZOMBATAR_FACIALHAIR_7_ID,
		IMAGE_ZOMBATAR_FACIALHAIR_8_ID,
		IMAGE_ZOMBATAR_FACIALHAIR_9_ID,
		IMAGE_ZOMBATAR_FACIALHAIR_10_ID,
		IMAGE_ZOMBATAR_FACIALHAIR_11_ID,
		IMAGE_ZOMBATAR_FACIALHAIR_12_ID,
		IMAGE_ZOMBATAR_FACIALHAIR_13_ID,
		IMAGE_ZOMBATAR_FACIALHAIR_14_ID,
		IMAGE_ZOMBATAR_FACIALHAIR_15_ID,
		IMAGE_ZOMBATAR_FACIALHAIR_16_ID,
		IMAGE_ZOMBATAR_FACIALHAIR_17_ID,
		IMAGE_ZOMBATAR_FACIALHAIR_18_ID,
		IMAGE_ZOMBATAR_FACIALHAIR_19_ID,
		IMAGE_ZOMBATAR_FACIALHAIR_20_ID,
		IMAGE_ZOMBATAR_FACIALHAIR_21_ID,
		IMAGE_ZOMBATAR_FACIALHAIR_22_ID,
		IMAGE_ZOMBATAR_FACIALHAIR_23_ID,
		IMAGE_ZOMBATAR_FACIALHAIR_24_ID,
		IMAGE_ZOMBATAR_TIDBITS_1_ID,
		IMAGE_ZOMBATAR_TIDBITS_2_ID,
		IMAGE_ZOMBATAR_TIDBITS_3_ID,
		IMAGE_ZOMBATAR_TIDBITS_4_ID,
		IMAGE_ZOMBATAR_TIDBITS_5_ID,
		IMAGE_ZOMBATAR_TIDBITS_6_ID,
		IMAGE_ZOMBATAR_TIDBITS_7_ID,
		IMAGE_ZOMBATAR_TIDBITS_8_ID,
		IMAGE_ZOMBATAR_TIDBITS_9_ID,
		IMAGE_ZOMBATAR_TIDBITS_10_ID,
		IMAGE_ZOMBATAR_TIDBITS_11_ID,
		IMAGE_ZOMBATAR_TIDBITS_12_ID,
		IMAGE_ZOMBATAR_TIDBITS_13_ID,
		IMAGE_ZOMBATAR_TIDBITS_14_ID,
		IMAGE_ZOMBATAR_ACCESSORY_1_ID,
		IMAGE_ZOMBATAR_ACCESSORY_2_ID,
		IMAGE_ZOMBATAR_ACCESSORY_3_ID,
		IMAGE_ZOMBATAR_ACCESSORY_4_ID,
		IMAGE_ZOMBATAR_ACCESSORY_5_ID,
		IMAGE_ZOMBATAR_ACCESSORY_6_ID,
		IMAGE_ZOMBATAR_ACCESSORY_7_ID,
		IMAGE_ZOMBATAR_ACCESSORY_8_ID,
		IMAGE_ZOMBATAR_ACCESSORY_9_ID,
		IMAGE_ZOMBATAR_ACCESSORY_10_ID,
		IMAGE_ZOMBATAR_ACCESSORY_11_ID,
		IMAGE_ZOMBATAR_ACCESSORY_12_ID,
		IMAGE_ZOMBATAR_ACCESSORY_13_ID,
		IMAGE_ZOMBATAR_ACCESSORY_14_ID,
		IMAGE_ZOMBATAR_HATS_1_MASK_ID,
		IMAGE_ZOMBATAR_HAIR_1_MASK_ID,
		IMAGE_ZOMBATAR_HAIR_2_MASK_ID,
		IMAGE_ZOMBATAR_HAIR_11_MASK_ID,
		IMAGE_ZOMBATAR_HAIR_12_MASK_ID,
		IMAGE_ZOMBATAR_HAIR_13_MASK_ID,
		IMAGE_ZOMBATAR_HAIR_14_MASK_ID,
		IMAGE_ZOMBATAR_HAIR_15_MASK_ID,
		IMAGE_ZOMBATAR_FACIALHAIR_1_MASK_ID,
		IMAGE_ZOMBATAR_FACIALHAIR_4_MASK_ID,
		IMAGE_ZOMBATAR_FACIALHAIR_8_MASK_ID,
		IMAGE_ZOMBATAR_FACIALHAIR_9_MASK_ID,
		IMAGE_ZOMBATAR_FACIALHAIR_10_MASK_ID,
		IMAGE_ZOMBATAR_FACIALHAIR_11_MASK_ID,
		IMAGE_ZOMBATAR_FACIALHAIR_12_MASK_ID,
		IMAGE_ZOMBATAR_FACIALHAIR_14_MASK_ID,
		IMAGE_ZOMBATAR_FACIALHAIR_15_MASK_ID,
		IMAGE_ZOMBATAR_FACIALHAIR_16_MASK_ID,
		IMAGE_ZOMBATAR_FACIALHAIR_18_MASK_ID,
		IMAGE_ZOMBATAR_FACIALHAIR_21_MASK_ID,
		IMAGE_ZOMBATAR_FACIALHAIR_22_MASK_ID,
		IMAGE_ZOMBATAR_FACIALHAIR_23_MASK_ID,
		IMAGE_ZOMBATAR_FACIALHAIR_24_MASK_ID,
		IMAGE_ZOMBATAR_EYEWEAR_1_MASK_ID,
		IMAGE_ZOMBATAR_EYEWEAR_2_MASK_ID,
		IMAGE_ZOMBATAR_EYEWEAR_3_MASK_ID,
		IMAGE_ZOMBATAR_EYEWEAR_4_MASK_ID,
		IMAGE_ZOMBATAR_EYEWEAR_5_MASK_ID,
		IMAGE_ZOMBATAR_EYEWEAR_6_MASK_ID,
		IMAGE_ZOMBATAR_EYEWEAR_7_MASK_ID,
		IMAGE_ZOMBATAR_EYEWEAR_8_MASK_ID,
		IMAGE_ZOMBATAR_EYEWEAR_9_MASK_ID,
		IMAGE_ZOMBATAR_EYEWEAR_10_MASK_ID,
		IMAGE_ZOMBATAR_EYEWEAR_11_MASK_ID,
		IMAGE_ZOMBATAR_EYEWEAR_12_MASK_ID,
		IMAGE_ZOMBATAR_HATS_3_MASK_ID,
		IMAGE_ZOMBATAR_HATS_6_MASK_ID,
		IMAGE_ZOMBATAR_HATS_7_MASK_ID,
		IMAGE_ZOMBATAR_HATS_8_MASK_ID,
		IMAGE_ZOMBATAR_HATS_9_MASK_ID,
		IMAGE_ZOMBATAR_HATS_11_MASK_ID,
		IMAGE_ZOMBATAR_BACKGROUND_BLANK_ID,
		IMAGE_ZOMBATAR_ACCESSORY_15_ID,
		IMAGE_ZOMBATAR_ACCESSORY_16_ID,
		IMAGE_ZOMBATAR_ACCEPT_BUTTON_ID,
		IMAGE_ZOMBATAR_ACCEPT_BUTTON_HIGHLIGHT_ID,
		IMAGE_ZOMBATAR_FINISHED_BUTTON_ID,
		IMAGE_ZOMBATAR_FINISHED_BUTTON_HIGHLIGHT_ID,
		IMAGE_ZOMBATAR_MAIN_BG_ID,
		IMAGE_ZOMBATAR_BACK_BUTTON_ID,
		IMAGE_ZOMBATAR_BACK_BUTTON_HIGHLIGHT_ID,
		IMAGE_ZOMBATAR_NEWZOMBIE_BUTTON_ID,
		IMAGE_ZOMBATAR_NEWZOMBIE_BUTTON_HIGHLIGHT_ID,
		IMAGE_ZOMBATAR_TOS_ARROW_ID,
		IMAGE_ZOMBATAR_BEGIN_BUTTON_ID,
		IMAGE_ZOMBATAR_BEGIN_BUTTON_HIGHLIGHT_ID,
		IMAGE_ZOMBATAR_TOS_SLIDER_ID,
		IMAGE_ZOMBATAR_TOS_SLIDER_THUMB_ID,
		IMAGE_ZOMBATAR_DISPLAY_WINDOW_ID,
		IMAGE_ZOMBATAR_MAINMENUBACK_HIGHLIGHT_ID,
		IMAGE_ZOMBATAR_VIEW_BUTTON_ID,
		IMAGE_ZOMBATAR_VIEW_BUTTON_HIGHLIGHT_ID,
		IMAGE_ACHIEVEMENT_1_ICON_HOMELAWNSECURITY_ID,
		IMAGE_ACHIEVEMENT_2_ICON_MORTICULTURALIST_ID,
		IMAGE_ACHIEVEMENT_3_ICON_SMARTY_BRANCHES_ID,
		IMAGE_ACHIEVEMENT_4_ICON_CRASH_OF_THE_TITAN_ID,
		IMAGE_ACHIEVEMENT_5_ICON_DONT_PEA_IN_POOL_ID,
		IMAGE_ACHIEVEMENT_6_ICON_IMMORTAL_ID,
		IMAGE_ACHIEVEMENT_7_ICON_SOIL_PLANTS_ID,
		IMAGE_ACHIEVEMENT_8_ICON_ROLL_SOME_HEADS_ID,
		IMAGE_ACHIEVEMENT_9_ICON_EXPLODONATOR_ID,
		IMAGE_ACHIEVEMENT_10_ICON_CLOSE_SHAVE_ID,
		IMAGE_ACHIEVEMENT_11_ICON_SHOPAHOLIC_ID,
		IMAGE_ACHIEVEMENT_12_ICON_SUNFLOWER_WALL_CHOMP_ID,
		IMAGE_ACHIEVEMENT_13_ICON_GROUNDED_ID,
		IMAGE_ACHIEVEMENT_14_ICON_ZOMBOLOGIST_ID,
		IMAGE_ACHIEVEMENT_15_ICON_PENNY_PINCHER_ID,
		IMAGE_ACHIEVEMENT_16_ICON_SUNNY_DAYS_ID,
		IMAGE_ACHIEVEMENT_17_ICON_POPCORN_PARTY_ID,
		IMAGE_ACHIEVEMENT_18_ICON_GOOD_MORNING_ID,
		IMAGE_ACHIEVEMENT_19_ICON_NO_FUNGUS_AMONG_US_ID,
		IMAGE_ACHIEVEMENT_20_ICON_BORN_SURVIVOR_ID,
		IMAGE_ACHIEVEMENT_21_ICON_ICE_AGE_ID,
		IMAGE_ACHIEVEMENT_22_ICON_INDUSTRIOUS_ID,
		IMAGE_ACHIEVEMENT_23_ICON_PYRO_ID,
		IMAGE_ACHIEVEMENT_24_ICON_LAWN_MOWER_MAN_ID,
		IMAGE_ACHIEVEMENT_25_ICON_MEX_WINTER_SPORTS_ID,
		IMAGE_ACHIEVEMENT_26_ICON_DEFCORN_5_ID,
		IMAGE_ACHIEVEMENT_27_ICON_SQUASHED_ID,
		IMAGE_ACHIEVEMENT_28_ICON_SURVIVE_IN_DARK_ID,
		IMAGE_ACHIEVEMENT_29_ICON_POOLS_CLOSED_ID,
		IMAGE_ACHIEVEMENT_30_ICON_WINTER_COMES_ID,
		IMAGE_ACHIEVEMENT_31_ICON_SECOND_OPINION_ID,
		IMAGE_ACHIEVEMENT_32_ICON_LUCKY_SPIN_ID,
		IMAGE_ACHIEVEMENT_33_ICON_CHILLI_FREE_ID,
		IMAGE_ACHIEVEMENT_34_ICON_ENLIGHTENED_ID,
		IMAGE_ACHIEVEMENT_35_ICON_SULTAN_ID,
		IMAGE_ACHIEVEMENT_36_ICON_GREENFINGERS_ID,
		IMAGE_ACHIEVEMENT_37_ICON_WALLNUT_ATTACK_ID,
		IMAGE_ACHIEVEMENT_38_ICON_BEYOND_ID,
		IMAGE_ACHIEVEMENT_39_ICON_SHOOTING_STAR_ID,
		IMAGE_ACHIEVEMENT_40_ICON_THRIFTY_ID,
		IMAGE_ACHIEVEMENT_41_ICON_SPROING_ID,
		IMAGE_ACHIEVEMENT_42_ICON_SPUDOW_ID,
		IMAGE_ACHIEVEMENT_TOP_BACKGROUND_ID,
		RESOURCE_ID_MAX
	};

	Image* GetImageById(int theId);
	Font* GetFontById(int theId);
	int GetSoundById(int theId);

	Image*& GetImageRefById(int theId);
	Font*& GetFontRefById(int theId);
	int& GetSoundRefById(int theId);

	ResourceId GetIdByImage(Image *theImage);
	ResourceId GetIdByFont(Font *theFont);
	ResourceId GetIdBySound(int theSound);
	const char* GetStringIdById(int theId);
	ResourceId GetIdByStringId(const char *theStringId);

} // namespace Sexy


#endif
