#ifndef __Res_H__
#define __Res_H__

namespace Sexy
{
	class ResourceManager;
	class Image;
	class Font;

	Image* LoadImageById(ResourceManager *theManager, int theId);
	void ReplaceImageById(ResourceManager *theManager, int theId, Image *theImage);
	bool ExtractResourcesByName(ResourceManager *theManager, const char *theName);

	// BjornBorder Resources
	bool ExtractBjornBorderResources(ResourceManager *theMgr);
	extern Image* IMAGE_IP_BJORN_BOTTOM;
	extern Image* IMAGE_IP_BJORN_GUTTER_BG_LEFT;
	extern Image* IMAGE_IP_BJORN_GUTTER_BG_RIGHT;
	extern Image* IMAGE_IP_BJORN_GUTTER_CLOUDS;
	extern Image* IMAGE_IP_BJORN_GUTTER_HILL;
	extern Image* IMAGE_IP_BJORN_GUTTER_TREE;
	extern Image* IMAGE_IP_BJORN_LEFT;
	extern Image* IMAGE_IP_BJORN_RIGHT;
	extern Image* IMAGE_IP_BJORN_TOP;

	// Character Resources
	bool ExtractCharacterResources(ResourceManager *theMgr);
	extern Image* IMAGE_CHR_CHARACTER10;
	extern Image* IMAGE_CHR_CHARACTER11;
	extern Image* IMAGE_CHR_CHARACTER1;
	extern Image* IMAGE_CHR_CHARACTER2;
	extern Image* IMAGE_CHR_CHARACTER3;
	extern Image* IMAGE_CHR_CHARACTER4;
	extern Image* IMAGE_CHR_CHARACTER5;
	extern Image* IMAGE_CHR_CHARACTER6;
	extern Image* IMAGE_CHR_CHARACTER7;
	extern Image* IMAGE_CHR_CHARACTER8;
	extern Image* IMAGE_CHR_CHARACTER9;
	extern Image* IMAGE_CHR_CHARACTERS;
	extern Image* IMAGE_CHR_CHARACTERSHADOWS;
	extern Image* IMAGE_CHR_YINYANGEYE;

	// CinderBorder Resources
	bool ExtractCinderBorderResources(ResourceManager *theMgr);
	extern Image* IMAGE_IP_CINDERBOTTOM_GUTTER_BG_LEFT;
	extern Image* IMAGE_IP_CINDERBOTTOM_GUTTER_BG_RIGHT;
	extern Image* IMAGE_IP_CINDER_BOTTOM;
	extern Image* IMAGE_IP_CINDER_LEFT;
	extern Image* IMAGE_IP_CINDER_RIGHT;
	extern Image* IMAGE_IP_CINDER_TOP;

	// ClaudeBorder Resources
	bool ExtractClaudeBorderResources(ResourceManager *theMgr);
	extern Image* IMAGE_IP_CLAUDE_BOTTOM;
	extern Image* IMAGE_IP_CLAUDE_GUTTER_BG_LEFT;
	extern Image* IMAGE_IP_CLAUDE_GUTTER_BG_RIGHT;
	extern Image* IMAGE_IP_CLAUDE_GUTTER_BIG_FISH1;
	extern Image* IMAGE_IP_CLAUDE_GUTTER_BIG_FISH2;
	extern Image* IMAGE_IP_CLAUDE_GUTTER_BIG_FISH3;
	extern Image* IMAGE_IP_CLAUDE_GUTTER_L_KELP;
	extern Image* IMAGE_IP_CLAUDE_GUTTER_R_KELP;
	extern Image* IMAGE_IP_CLAUDE_GUTTER_SMALL_FISH1;
	extern Image* IMAGE_IP_CLAUDE_GUTTER_SMALL_FISH2;
	extern Image* IMAGE_IP_CLAUDE_GUTTER_SMALL_FISH3;
	extern Image* IMAGE_IP_CLAUDE_LEFT;
	extern Image* IMAGE_IP_CLAUDE_RIGHT;
	extern Image* IMAGE_IP_CLAUDE_TOP;

	// Dialog Resources
	bool ExtractDialogResources(ResourceManager *theMgr);
	extern Image* IMAGE_DLG_BIGQUESTIONMARK;
	extern Image* IMAGE_DLG_BLUEFRAME;
	extern Image* IMAGE_DLG_BOTTOMBAR;
	extern Image* IMAGE_DLG_BROWNBUTTON1;
	extern Image* IMAGE_DLG_BROWNBUTTON2;
	extern Image* IMAGE_DLG_BUTTON1;
	extern Image* IMAGE_DLG_BUTTON2;
	extern Image* IMAGE_DLG_BUTTON3;
	extern Image* IMAGE_DLG_BUTTONOVERLAY2;
	extern Image* IMAGE_DLG_CONNECTOR;
	extern Image* IMAGE_DLG_DIALOGBOX;
	extern Image* IMAGE_DLG_EDITBUTTON;
	extern Image* IMAGE_DLG_ETCHINGS;
	extern Image* IMAGE_DLG_FRAME1;
	extern Image* IMAGE_DLG_FRAME2;
	extern Image* IMAGE_DLG_FRAME3;
	extern Image* IMAGE_DLG_GLOSS;
	extern Image* IMAGE_DLG_GRAYFRAME;
	extern Image* IMAGE_DLG_GREENOK;
	extern Image* IMAGE_DLG_HELP_BAR;
	extern Image* IMAGE_DLG_HELP_BUTTONS;
	extern Image* IMAGE_DLG_HELP_LB_SLIDER;
	extern Image* IMAGE_DLG_HELP_RB_SLIDER;
	extern Image* IMAGE_DLG_HELP_SLIDER;
	extern Image* IMAGE_DLG_HORZBAR;
	extern Image* IMAGE_DLG_INSTANTREPLAY;
	extern Image* IMAGE_DLG_INSTRUCTIONS2;
	extern Image* IMAGE_DLG_INSTRUCTIONS3;
	extern Image* IMAGE_DLG_INSTRUCTIONS4;
	extern Image* IMAGE_DLG_INSTRUCTIONS;
	extern Image* IMAGE_DLG_LJOINT;
	extern Image* IMAGE_DLG_MASTERSTAGE;
	extern Image* IMAGE_DLG_MASTERSTAGEPROGBAR;
	extern Image* IMAGE_DLG_MENU;
	extern Image* IMAGE_DLG_PLAYBUTTON1;
	extern Image* IMAGE_DLG_PLAYBUTTON2;
	extern Image* IMAGE_DLG_PLAYWIDGET1;
	extern Image* IMAGE_DLG_PLAYWIDGET2;
	extern Image* IMAGE_DLG_POPUP;
	extern Image* IMAGE_DLG_PURPLEBUTTON;
	extern Image* IMAGE_DLG_QUESTIONMARK;
	extern Image* IMAGE_DLG_RANDOM;
	extern Image* IMAGE_DLG_REPLAYSEGMENT;
	extern Image* IMAGE_DLG_REPLAYSPIN;
	extern Image* IMAGE_DLG_REPLAYTOP;
	extern Image* IMAGE_DLG_SEGMENT;
	extern Image* IMAGE_DLG_SELECTORFRAME;
	extern Image* IMAGE_DLG_SLIDER;
	extern Image* IMAGE_DLG_SLIDERHILIGHT;
	extern Image* IMAGE_DLG_SLIDERORB;
	extern Image* IMAGE_DLG_STAGEBAR;
	extern Image* IMAGE_DLG_STAGEBULLET;
	extern Image* IMAGE_DLG_STAGEPROGRESSBAR;
	extern Image* IMAGE_DLG_TEXTBOX;
	extern Image* IMAGE_DLG_TEXTRECT;
	extern Image* IMAGE_DLG_TIP;

	// Duel Resources
	bool ExtractDuelResources(ResourceManager *theMgr);
	extern Image* IMAGE_DUEL_LOBBY_PLAYER;

	// Game Resources
	bool ExtractGameResources(ResourceManager *theMgr);
	extern Image* IMAGE_ALPHABALL;
	extern Image* IMAGE_BALL;
	extern Image* IMAGE_BALLPEG;
	extern Image* IMAGE_BALLPEGCB;
	extern Image* IMAGE_BALLSHADOW;
	extern Image* IMAGE_BIGBALL;
	extern Image* IMAGE_BIGBALLSHADOW;
	extern Image* IMAGE_BLUERIBBON;
	extern Image* IMAGE_BONUS100000;
	extern Image* IMAGE_BONUS100000LIGHT;
	extern Image* IMAGE_BONUS10000;
	extern Image* IMAGE_BONUS10000LIGHT;
	extern Image* IMAGE_BONUS25000;
	extern Image* IMAGE_BONUS25000LIGHT;
	extern Image* IMAGE_BONUS50000;
	extern Image* IMAGE_BONUS50000LIGHT;
	extern Image* IMAGE_BONUS5000;
	extern Image* IMAGE_BONUS5000LIGHT;
	extern Image* IMAGE_BONUSGLOW;
	extern Image* IMAGE_BONUSGLOW_BLUE;
	extern Image* IMAGE_BONUSGLOW_GREEN;
	extern Image* IMAGE_BONUSHALO;
	extern Image* IMAGE_BRICK;
	extern Image* IMAGE_BRICKCB;
	extern Image* IMAGE_BRICKGLOW;
	extern Image* IMAGE_BUBBLES;
	extern Image* IMAGE_CATCHERGLOW;
	extern Image* IMAGE_CIRCLE;
	extern Image* IMAGE_COINHEADS;
	extern Image* IMAGE_COINHILIGHT;
	extern Image* IMAGE_COINTAILS;
	extern Image* IMAGE_DEFINNERPEG;
	extern Image* IMAGE_DEFOUTERPEG;
	extern Image* IMAGE_EMBER;
	extern Image* IMAGE_FEVERBORDER;
	extern Image* IMAGE_FEVERCAM;
	extern Image* IMAGE_FEVERGLOWSTAR;
	extern Image* IMAGE_FEVERRAINBOW;
	extern Image* IMAGE_FEVERRAY;
	extern Image* IMAGE_FEVERSCORE;
	extern Image* IMAGE_FEVERSCORETOP;
	extern Image* IMAGE_FEVERSPARK;
	extern Image* IMAGE_FEVERSTAR_BLUE;
	extern Image* IMAGE_FEVERSTAR_GREEN;
	extern Image* IMAGE_FEVERSTAR_RED;
	extern Image* IMAGE_FEVERTRAIL;
	extern Image* IMAGE_FIREBALL;
	extern Image* IMAGE_FIREBALLFIRE;
	extern Image* IMAGE_FLAMETRAIL;
	extern Image* IMAGE_FLECK;
	extern Image* IMAGE_FLOWER;
	extern Image* IMAGE_GUIDEARROW;
	extern Image* IMAGE_GUIDEHIT;
	extern Image* IMAGE_GUIDEPOINT;
	extern Image* IMAGE_GUIDERECT2;
	extern Image* IMAGE_GUIDERECT;
	extern Image* IMAGE_HAT;
	extern Image* IMAGE_JIMMY;
	extern Image* IMAGE_JIMMYSPEECH;
	extern Image* IMAGE_MAGICHAT;
	extern Image* IMAGE_MASTERBADGE;
	extern Image* IMAGE_NUKE;
	extern Image* IMAGE_NUKESTREAK;
	extern Image* IMAGE_PAUSED;
	extern Image* IMAGE_PEGGLOW;
	extern Image* IMAGE_PEGSHADOW;
	extern Image* IMAGE_POWERUPICON;
	extern Image* IMAGE_PULSE2_POWERUP;
	extern Image* IMAGE_PULSE2_SCORE;
	extern Image* IMAGE_PULSE_GOAL;
	extern Image* IMAGE_PULSE_NORMAL;
	extern Image* IMAGE_PULSE_POWERUP;
	extern Image* IMAGE_PULSE_SCORE;
	extern Image* IMAGE_PYRAMIDBALL;
	extern Image* IMAGE_PYRAMIDRAY;
	extern Image* IMAGE_SCOREICON;
	extern Image* IMAGE_SMOKE;
	extern Image* IMAGE_SPACEBUBBLE;
	extern Image* IMAGE_SPACEBURST;
	extern Image* IMAGE_SPACEHALO;
	extern Image* IMAGE_SPACESTAR;
	extern Image* IMAGE_SPARKLE;
	extern Image* IMAGE_SPARKLE_FEVER;
	extern Image* IMAGE_SPOOKYEYES;
	extern Image* IMAGE_SPOOKYGHOST;
	extern Image* IMAGE_SPOOKYPOOF1;
	extern Image* IMAGE_SPOOKYPOOF2;
	extern Image* IMAGE_SPOOKYTRAIL;
	extern Image* IMAGE_STAR_STREAK;
	extern Image* IMAGE_STREAK;
	extern Image* IMAGE_TINYBLUERIBBON;
	extern Image* IMAGE_TIPARROW;
	extern Image* IMAGE_VS_DUEL;
	extern Image* IMAGE_VS_DUELBACK;
	extern Image* IMAGE_XFEVER;
	extern Image* IMAGE_XFEVERGLOW;
	extern Image* IMAGE_YINYANG;

	// Help Resources
	bool ExtractHelpResources(ResourceManager *theMgr);
	extern Image* IMAGE_HELP_ICONS2;
	extern Image* IMAGE_HELP_ICONS;

	// HuBorder Resources
	bool ExtractHuBorderResources(ResourceManager *theMgr);
	extern Image* IMAGE_IP_HU_BOTTOM;
	extern Image* IMAGE_IP_HU_LEFT;
	extern Image* IMAGE_IP_HU_RIGHT;
	extern Image* IMAGE_IP_HU_TOP;
	extern Image* IMAGE_IP_MASTERHU_GUTTER_BG_LEFT;
	extern Image* IMAGE_IP_MASTERHU_GUTTER_BG_RIGHT;
	extern Image* IMAGE_IP_MASTERHU_GUTTER_CLOUD;
	extern Image* IMAGE_IP_MASTERHU_GUTTER_L_HILL;
	extern Image* IMAGE_IP_MASTERHU_GUTTER_R_HILL;

	// IP Resources
	bool ExtractIPResources(ResourceManager *theMgr);
	extern Image* IMAGE_IP_B;
	extern Image* IMAGE_IP_BALLOTRON;
	extern Image* IMAGE_IP_BEXTEND;
	extern Image* IMAGE_IP_BLC;
	extern Image* IMAGE_IP_BRC;
	extern Image* IMAGE_IP_FEVERMETER;
	extern Image* IMAGE_IP_GOLD_PLATE;
	extern Image* IMAGE_IP_L1;
	extern Image* IMAGE_IP_L2;
	extern Image* IMAGE_IP_LEXTEND;
	extern Image* IMAGE_IP_LWINDOW;
	extern Image* IMAGE_IP_ORBGLOW;
	extern Image* IMAGE_IP_PARTY_BOTTOM;
	extern Image* IMAGE_IP_PARTY_LEFT;
	extern Image* IMAGE_IP_PARTY_RIGHT;
	extern Image* IMAGE_IP_PARTY_TOP;
	extern Image* IMAGE_IP_POWERUPBANNER;
	extern Image* IMAGE_IP_R1;
	extern Image* IMAGE_IP_R2;
	extern Image* IMAGE_IP_REXTEND;
	extern Image* IMAGE_IP_RWINDOW;
	extern Image* IMAGE_IP_SEAMS;
	extern Image* IMAGE_IP_SHOOTER;
	extern Image* IMAGE_IP_SHOOTERBACK;
	extern Image* IMAGE_IP_SHOOTERORB;
	extern Image* IMAGE_IP_TEXTEND;
	extern Image* IMAGE_IP_TITLEBAR;
	extern Image* IMAGE_IP_TITLEGLOSS;
	extern Image* IMAGE_IP_TITLELC;
	extern Image* IMAGE_IP_TITLERC;
	extern Image* IMAGE_IP_TITLESLIDER;
	extern Image* IMAGE_IP_TL1;
	extern Image* IMAGE_IP_TL2;
	extern Image* IMAGE_IP_TLC;
	extern Image* IMAGE_IP_TR1;
	extern Image* IMAGE_IP_TR2;
	extern Image* IMAGE_IP_TRC;

	// Init Resources
	bool ExtractInitResources(ResourceManager *theMgr);
	extern Font* FONT_OVERLOAD16;
	extern Font* FONT_OVERLOAD16OUTLINE2;
	extern Font* FONT_OVERLOAD16OUTLINE;
	extern Image* IMAGE_SUNGLOW;
	extern int SOUND_MORNING;

	// Interface Resources
	bool ExtractInterfaceResources(ResourceManager *theMgr);
	extern Image* IMAGE_INT_BACKSHADOW;
	extern Image* IMAGE_INT_BALL;
	extern Image* IMAGE_INT_BALLBACK;
	extern Image* IMAGE_INT_BALLGLASS;
	extern Image* IMAGE_INT_BALLOMASKBL;
	extern Image* IMAGE_INT_BALLOMASKBR;
	extern Image* IMAGE_INT_BALLOMASKTL;
	extern Image* IMAGE_INT_BALLOMASKTR;
	extern Image* IMAGE_INT_BGCHECKBOX;
	extern Image* IMAGE_INT_BGCHECKGLOW;
	extern Image* IMAGE_INT_BIGDLGBUTTON;
	extern Image* IMAGE_INT_BIGDLGGLOW;
	extern Image* IMAGE_INT_BIGMENUBUTTON;
	extern Image* IMAGE_INT_BIGMENUGLOW;
	extern Image* IMAGE_INT_BUTTONCOVER;
	extern Image* IMAGE_INT_CANNON;
	extern Image* IMAGE_INT_CANNONCOVER;
	extern Image* IMAGE_INT_COLORCHECK;
	extern Image* IMAGE_INT_CONTROLS;
	extern Image* IMAGE_INT_COUNTER;
	extern Image* IMAGE_INT_FBCENTERDISC;
	extern Image* IMAGE_INT_FBFREEBALL;
	extern Image* IMAGE_INT_FBGLOW;
	extern Image* IMAGE_INT_FBLIGHTUP;
	extern Image* IMAGE_INT_FBPOINTS;
	extern Image* IMAGE_INT_FEVERBARLITES;
	extern Image* IMAGE_INT_FEVERBARS;
	extern Image* IMAGE_INT_FEVERGLOW1;
	extern Image* IMAGE_INT_FEVERGLOW2;
	extern Image* IMAGE_INT_FEVERGLOW3;
	extern Image* IMAGE_INT_FEVERGLOW;
	extern Image* IMAGE_INT_FEVERMETER;
	extern Image* IMAGE_INT_FEVERMETERBOTTOM;
	extern Image* IMAGE_INT_FEVERMETERTOP;
	extern Image* IMAGE_INT_FEVERRAILING;
	extern Image* IMAGE_INT_FREEBALLMETER;
	extern Image* IMAGE_INT_FREEBALLMETERTOP;
	extern Image* IMAGE_INT_LEVELSELECT;
	extern Image* IMAGE_INT_LEVELSELECTBUTTON;
	extern Image* IMAGE_INT_LEVELSELECTGLOW;
	extern Image* IMAGE_INT_PADLOCK;
	extern Image* IMAGE_INT_PLUNGER;
	extern Image* IMAGE_INT_SCOREHILIGHT;

	// JimmyBorder Resources
	bool ExtractJimmyBorderResources(ResourceManager *theMgr);
	extern Image* IMAGE_IP_JIMMY_BOTTOM;
	extern Image* IMAGE_IP_JIMMY_GUTTER_BG_LEFT;
	extern Image* IMAGE_IP_JIMMY_GUTTER_BG_RIGHT;
	extern Image* IMAGE_IP_JIMMY_GUTTER_L_FALL1;
	extern Image* IMAGE_IP_JIMMY_GUTTER_L_FALL2;
	extern Image* IMAGE_IP_JIMMY_GUTTER_L_FOREGROUND;
	extern Image* IMAGE_IP_JIMMY_GUTTER_R_FALL1;
	extern Image* IMAGE_IP_JIMMY_GUTTER_R_FALL2;
	extern Image* IMAGE_IP_JIMMY_GUTTER_R_FOREGROUND;
	extern Image* IMAGE_IP_JIMMY_LEFT;
	extern Image* IMAGE_IP_JIMMY_RIGHT;
	extern Image* IMAGE_IP_JIMMY_TOP;

	// KattutBorder Resources
	bool ExtractKattutBorderResources(ResourceManager *theMgr);
	extern Image* IMAGE_IP_KATTUT_BOTTOM;
	extern Image* IMAGE_IP_KATTUT_GUTTER_BG_LEFT;
	extern Image* IMAGE_IP_KATTUT_GUTTER_BG_RIGHT;
	extern Image* IMAGE_IP_KATTUT_GUTTER_CLOUDS;
	extern Image* IMAGE_IP_KATTUT_LEFT;
	extern Image* IMAGE_IP_KATTUT_RIGHT;
	extern Image* IMAGE_IP_KATTUT_TOP;

	// LeaderboardMenu Resources
	bool ExtractLeaderboardMenuResources(ResourceManager *theMgr);
	extern Image* IMAGE_LB_100;
	extern Image* IMAGE_LB_BACKING;
	extern Image* IMAGE_LB_FREEBALL;
	extern Image* IMAGE_LB_GAMECLIP;
	extern Image* IMAGE_LB_GAMECLIP_SMALL;
	extern Image* IMAGE_LB_GAMECLIP_SMALL_STROKE;
	extern Image* IMAGE_LB_HOLDER;
	extern Image* IMAGE_LB_MASTER0;
	extern Image* IMAGE_LB_MASTER1;
	extern Image* IMAGE_LB_MASTER2;
	extern Image* IMAGE_LB_MASTER3;
	extern Image* IMAGE_LB_MASTER4;
	extern Image* IMAGE_LB_MASTER5;
	extern Image* IMAGE_LB_MASTER6;
	extern Image* IMAGE_LB_MASTER7;
	extern Image* IMAGE_LB_MASTER8;
	extern Image* IMAGE_LB_MASTER9;
	extern Image* IMAGE_LB_NOBALL;
	extern Image* IMAGE_LB_SHOT;
	extern Image* IMAGE_LB_ZEN;

	// LevelSelect Resources
	bool ExtractLevelSelectResources(ResourceManager *theMgr);
	extern Image* IMAGE_LS_CHALLENGEBADGE;
	extern Image* IMAGE_LS_DOWNLOAD;
	extern Image* IMAGE_LS_LOCK;
	extern Image* IMAGE_LS_LOCK_SMALL;
	extern Image* IMAGE_LS_RANDOMLEVEL;
	extern Image* IMAGE_LS_TINYBLUERIBBON;
	extern Image* IMAGE_LS_TINYMASTER;
	extern Image* IMAGE_LS_WATERMARK;

	// Load Resources
	bool ExtractLoadResources(ResourceManager *theMgr);
	extern Image* IMAGE_LOAD_BALL;
	extern Image* IMAGE_LOAD_LIGHTS;
	extern Image* IMAGE_LOAD_LOGO;
	extern Image* IMAGE_LOAD_OVERLAY;
	extern Image* IMAGE_LOAD_PLAYNOW;
	extern Image* IMAGE_LOAD_SHADOW;
	extern Image* IMAGE_LOAD_SUNHEAD;
	extern Image* IMAGE_LOAD_TM;

	// LoadingThread Resources
	bool ExtractLoadingThreadResources(ResourceManager *theMgr);
	extern Font* FONT_BALLSLEFT;
	extern Font* FONT_BONK;
	extern Font* FONT_BUTTON;
	extern Font* FONT_LEVELUP;
	extern Font* FONT_OVERLOAD10;
	extern Font* FONT_OVERLOAD10OUTLINE;
	extern Font* FONT_OVERLOAD12;
	extern Font* FONT_OVERLOAD12OUTLINE;
	extern Font* FONT_OVERLOAD24;
	extern Font* FONT_OVERLOAD24GRAD1;
	extern Font* FONT_OVERLOAD24GRAD2;
	extern Font* FONT_OVERLOAD24OUTLINE;
	extern Font* FONT_OVERLOADMONO10;
	extern Font* FONT_OVERLOADMONO12;
	extern Font* FONT_PLAIN2;
	extern Font* FONT_PLAIN2BIG;
	extern Font* FONT_PLAIN2BIGOUTLINE;
	extern Font* FONT_PLAIN2OUTLINE;
	extern Font* FONT_PLAIN;
	extern Font* FONT_PLAINOUTLINE;
	extern Font* FONT_SCORE_DISP;
	extern Font* FONT_SMALL;
	extern Font* FONT_SMALLMONO;
	extern Font* FONT_SMALL_DISP;
	extern Font* FONT_STAGE;
	extern int SOUND_AAH;
	extern int SOUND_ADD_BALL;
	extern int SOUND_ALL_RANDOM_OFF;
	extern int SOUND_ALL_RANDOM_ON;
	extern int SOUND_APPLAUSE;
	extern int SOUND_AWARD;
	extern int SOUND_BEST_SHOT;
	extern int SOUND_BUBBLES;
	extern int SOUND_BUCKETHIT;
	extern int SOUND_BUTTON1;
	extern int SOUND_BUTTON2;
	extern int SOUND_CANNONCOCK;
	extern int SOUND_CANNONSHOT;
	extern int SOUND_COINSPIN;
	extern int SOUND_COINSPIN_NO;
	extern int SOUND_CYMBAL;
	extern int SOUND_DIALOG_MOVE;
	extern int SOUND_DING;
	extern int SOUND_EXPLODE;
	extern int SOUND_EXTRABALL2;
	extern int SOUND_EXTRABALL3;
	extern int SOUND_EXTRABALL;
	extern int SOUND_FEVERHIT;
	extern int SOUND_FIREBALLBOUNCE;
	extern int SOUND_FIREBALLLOOP;
	extern int SOUND_FIREBALLSHOT;
	extern int SOUND_FIREWORKPOP;
	extern int SOUND_FIREWORKS1;
	extern int SOUND_FIREWORKS2;
	extern int SOUND_FLIP;
	extern int SOUND_FLIPPERBOUNCE;
	extern int SOUND_FLIPPERDOWN;
	extern int SOUND_FLIPPERUP;
	extern int SOUND_FREEBALL;
	extern int SOUND_GONG;
	extern int SOUND_JOIN_LOBBY;
	extern int SOUND_LEAVE_LOBBY;
	extern int SOUND_LEVELDONE;
	extern int SOUND_LEVELLOST;
	extern int SOUND_LEVELWON;
	extern int SOUND_MISS;
	extern int SOUND_MOUSEOVER;
	extern int SOUND_MULTIBALL;
	extern int SOUND_NEW_LEVEL;
	extern int SOUND_NEW_LEVEL_FAST1;
	extern int SOUND_NEW_LEVEL_FAST2;
	extern int SOUND_NEW_LEVEL_FAST3;
	extern int SOUND_NEW_LEVEL_FAST4;
	extern int SOUND_NEW_SHOTCLOCK;
	extern int SOUND_NUM_ROUNDS_CHANGE;
	extern int SOUND_OPTIONS_CANCEL;
	extern int SOUND_OPTIONS_CONFIRM;
	extern int SOUND_PEGHIT2;
	extern int SOUND_PEGHIT3;
	extern int SOUND_PEGHIT;
	extern int SOUND_PEGHIT_LOW;
	extern int SOUND_PEGPOP;
	extern int SOUND_PENALTY;
	extern int SOUND_PLAYER_READY;
	extern int SOUND_POINTBOOST;
	extern int SOUND_POWERUP;
	extern int SOUND_POWERUP_FIREBALL;
	extern int SOUND_POWERUP_FLIPPERS;
	extern int SOUND_POWERUP_FLOWERPOWER;
	extern int SOUND_POWERUP_GUIDE;
	extern int SOUND_POWERUP_LUCKYSPIN;
	extern int SOUND_POWERUP_MULTIBALL;
	extern int SOUND_POWERUP_PYRAMID;
	extern int SOUND_POWERUP_SPACEBLAST;
	extern int SOUND_POWERUP_SPOOKYBALL;
	extern int SOUND_POWERUP_ZEN;
	extern int SOUND_RAINBOW;
	extern int SOUND_RESULTS_TEXT;
	extern int SOUND_RIBBON_2ND;
	extern int SOUND_RIBBON_3RD;
	extern int SOUND_RIBBON_4TH;
	extern int SOUND_RIBBON_AWARD;
	extern int SOUND_RICHOCHET;
	extern int SOUND_ROUND_DISC;
	extern int SOUND_SCORECOUNTER;
	extern int SOUND_SCORE_BAR_EXPLODE;
	extern int SOUND_SCORE_BAR_EXPLODE_WIN;
	extern int SOUND_SCORE_BAR_FILL;
	extern int SOUND_SCORE_BAR_REFILL;
	extern int SOUND_SCORE_BAR_TICK;
	extern int SOUND_SCREEN_MOVE;
	extern int SOUND_SHOT_125K;
	extern int SOUND_SHOT_25K;
	extern int SOUND_SHOT_75K;
	extern int SOUND_SHOT_CLOCK_SUBTLE;
	extern int SOUND_SIGH;
	extern int SOUND_SKILLSHOT;
	extern int SOUND_SLOWMO;
	extern int SOUND_SPOOKYBALL2;
	extern int SOUND_SPOOKYBALL3;
	extern int SOUND_SPOOKYBALL4;
	extern int SOUND_STAMP;
	extern int SOUND_START_VIEW_BOARD;
	extern int SOUND_STOP_VIEW_BOARD;
	extern int SOUND_STORY_TYPING;
	extern int SOUND_STYLE_SHOT_FILL;
	extern int SOUND_TEXT_WOOSH;
	extern int SOUND_TING;
	extern int SOUND_TONE;
	extern int SOUND_TONEHI;
	extern int SOUND_TONELO;
	extern int SOUND_TONESUPERHI;
	extern int SOUND_TROPHY_STAY;
	extern int SOUND_TYPING;
	extern int SOUND_WHISTLE;
	extern int SOUND_WOOSH;

	// LuckySpin Resources
	bool ExtractLuckySpinResources(ResourceManager *theMgr);
	extern Image* IMAGE_SPIN_ARROW;
	extern Image* IMAGE_SPIN_EXTRABALLMASK;
	extern Image* IMAGE_SPIN_EXTRAON;
	extern Image* IMAGE_SPIN_HATON;
	extern Image* IMAGE_SPIN_RANDOMON;
	extern Image* IMAGE_SPIN_RANDOMTEXT;
	extern Image* IMAGE_SPIN_RANDOMTEXTON;
	extern Image* IMAGE_SPIN_RIMLIGHT2;
	extern Image* IMAGE_SPIN_RIMLIGHT;
	extern Image* IMAGE_SPIN_SPINNER;
	extern Image* IMAGE_SPIN_TRIPLEON;

	// MainMenu Resources
	bool ExtractMainMenuResources(ResourceManager *theMgr);
	extern Image* IMAGE_MM_BLANKSUN;
	extern Image* IMAGE_MM_BUYIT;
	extern Image* IMAGE_MM_CRY;
	extern Image* IMAGE_MM_MURAL_BACK_MP;
	extern Image* IMAGE_MM_MURAL_BACK_SP;
	extern Image* IMAGE_MM_MURAL_BACK_WAIT;
	extern Image* IMAGE_MM_MURAL_MP;
	extern Image* IMAGE_MM_MURAL_SP;
	extern Image* IMAGE_MM_MURAL_WAIT;
	extern Image* IMAGE_MM_SPEECHBUBBLE;
	extern Image* IMAGE_MM_TROPHIES;
	extern Image* IMAGE_MM_TROPHYREVEAL;

	// NightsPDLC_Loading Resources
	bool ExtractNightsPDLC_LoadingResources(ResourceManager *theMgr);
	extern Image* IMAGE_LOAD_GODRAY;
	extern Image* IMAGE_LOAD_LENSFLARE;
	extern Image* IMAGE_LOAD_MURAL_BG_WAIT_NIGHT;
	extern Image* IMAGE_LOAD_MURAL_SP_NIGHT;
	extern Image* IMAGE_LOAD_MURAL_WAIT_NIGHT;
	extern Image* IMAGE_LOAD_NIGHTSLOGO_MOON;
	extern Image* IMAGE_LOAD_RIM_LIGHT;
	extern Image* IMAGE_LOAD_SUNSET_BG;

	// NightsPDLC_MainMenu Resources
	bool ExtractNightsPDLC_MainMenuResources(ResourceManager *theMgr);
	extern Image* IMAGE_MM_MARINASTAGE;
	extern Image* IMAGE_MM_TROPHY_CROWN;
	extern Image* IMAGE_MM_TROPHY_CUP;
	extern Image* IMAGE_MM_TROPHY_TORCH;
	extern Image* IMAGE_MM_TROPHY_ZEN;

	// NightsPDLC_MarinaBorder Resources
	bool ExtractNightsPDLC_MarinaBorderResources(ResourceManager *theMgr);
	extern Image* IMAGE_IP_MARINA_BOTTOM;
	extern Image* IMAGE_IP_MARINA_GUTTER_JELLYFISH1;
	extern Image* IMAGE_IP_MARINA_GUTTER_JELLYFISH2;
	extern Image* IMAGE_IP_MARINA_GUTTER_LEFT;
	extern Image* IMAGE_IP_MARINA_GUTTER_RIGHT;
	extern Image* IMAGE_IP_MARINA_LEFT;
	extern Image* IMAGE_IP_MARINA_RIGHT;
	extern Image* IMAGE_IP_MARINA_TOP;

	// NightsPDLC_Trophy Resources
	bool ExtractNightsPDLC_TrophyResources(ResourceManager *theMgr);
	extern Image* IMAGE_TROPHY_ADV;
	extern Image* IMAGE_TROPHY_CURTAIN;
	extern Image* IMAGE_TROPHY_CURTAIN_L;
	extern Image* IMAGE_TROPHY_CURTAIN_R;
	extern Image* IMAGE_TROPHY_EXIT_BUTTON;
	extern Image* IMAGE_TROPHY_HOLE;
	extern Image* IMAGE_TROPHY_MASTER1;
	extern Image* IMAGE_TROPHY_MASTER2;
	extern Image* IMAGE_TROPHY_MASTER3;
	extern Image* IMAGE_TROPHY_PARTICLE1;
	extern Image* IMAGE_TROPHY_PARTICLE2;
	extern Image* IMAGE_TROPHY_PARTICLE3;
	extern Image* IMAGE_TROPHY_PARTICLE4;
	extern Image* IMAGE_TROPHY_PARTICLE5;
	extern Image* IMAGE_TROPHY_PARTICLE6;
	extern Image* IMAGE_TROPHY_PARTICLE_WHITE_MED_ROUND;
	extern Image* IMAGE_TROPHY_SPARKLE;
	extern Image* IMAGE_TROPHY_SPEECH_B;
	extern Image* IMAGE_TROPHY_SPEECH_BL;
	extern Image* IMAGE_TROPHY_SPEECH_BP;
	extern Image* IMAGE_TROPHY_SPEECH_BR;
	extern Image* IMAGE_TROPHY_SPEECH_C;
	extern Image* IMAGE_TROPHY_SPEECH_L;
	extern Image* IMAGE_TROPHY_SPEECH_LP;
	extern Image* IMAGE_TROPHY_SPEECH_R;
	extern Image* IMAGE_TROPHY_SPEECH_RP;
	extern Image* IMAGE_TROPHY_SPEECH_T;
	extern Image* IMAGE_TROPHY_SPEECH_TL;
	extern Image* IMAGE_TROPHY_SPEECH_TP;
	extern Image* IMAGE_TROPHY_SPEECH_TR;

	// NightsTU Resources
	bool ExtractNightsTUResources(ResourceManager *theMgr);
	extern Image* IMAGE_ADDTL_GLOW;
	extern Image* IMAGE_BALL_LIGHTNING;
	extern Image* IMAGE_CURVE;
	extern Image* IMAGE_FLY0;
	extern Image* IMAGE_FLY1;
	extern Image* IMAGE_LIGHTNING;
	extern Image* IMAGE_LIGHTNING_BACK;
	extern Image* IMAGE_LIGHTNING_BALLSPARK;
	extern Image* IMAGE_LIGHTNING_FRONT;
	extern Image* IMAGE_LIGHTNING_FRONT_SMALL;
	extern Image* IMAGE_LIGHTNING_ROD;
	extern Image* IMAGE_LIGHTNING_ROD_ON;
	extern Image* IMAGE_LIGHTNING_ROD_RING_BACK;
	extern Image* IMAGE_LIGHTNING_ROD_RING_FRONT;
	extern Image* IMAGE_LIGHTNING_ROD_ZAP;
	extern Image* IMAGE_LIGHTNING_SPARK;
	extern Image* IMAGE_MARINA_BG;
	extern Image* IMAGE_MARINA_LOGO;
	extern Image* IMAGE_MARINA_SHOOTER;
	extern Image* IMAGE_NIGHTS_BUTTON;
	extern Image* IMAGE_OTHERBUTTON_GLOW;
	extern Image* IMAGE_SUPERSWIRL;
	extern Image* IMAGE_TWINKLE_STAR;
	extern int SOUND_APPLAUSE_LONG;
	extern int SOUND_CREDITS_SPOTLIGHT_ON;
	extern int SOUND_INTRO;
	extern int SOUND_LIGHTNING_LOOP;
	extern int SOUND_LIGHTNING_START;
	extern int SOUND_LOGO_BUZZ_ON;
	extern int SOUND_NEON_FLICKER;
	extern int SOUND_PEGSPARK;
	extern int SOUND_POWERUP_LIGHTNING;
	extern int SOUND_POWERUP_LIGHTNING_HIT;
	extern int SOUND_SPEECH_BUBBLE_POPUP;
	extern int SOUND_STAGE_DREAMY_IN;
	extern int SOUND_STAGE_DREAMY_OUT;
	extern int SOUND_TROPHY_PHOTO_IN;
	extern int SOUND_TROPHY_WIN_INTRO;

	// NightsTUChars Resources
	bool ExtractNightsTUCharsResources(ResourceManager *theMgr);
	extern Image* IMAGE_CHR_CHARACTERSHADOWS_NIGHTS;
	extern Image* IMAGE_CHR_CHARACTERS_NIGHTS;
	extern Image* IMAGE_CHR_CHARACTER_ADV12;
	extern Image* IMAGE_CHR_CHARACTER_MARINA;
	extern Image* IMAGE_CHR_CHARACTER_NEW10;
	extern Image* IMAGE_CHR_CHARACTER_NEW1;
	extern Image* IMAGE_CHR_CHARACTER_NEW2;
	extern Image* IMAGE_CHR_CHARACTER_NEW3;
	extern Image* IMAGE_CHR_CHARACTER_NEW4;
	extern Image* IMAGE_CHR_CHARACTER_NEW5;
	extern Image* IMAGE_CHR_CHARACTER_NEW6;
	extern Image* IMAGE_CHR_CHARACTER_NEW7;
	extern Image* IMAGE_CHR_CHARACTER_NEW8;
	extern Image* IMAGE_CHR_CHARACTER_NEW9;
	extern Image* IMAGE_CHR_PARTICLE1;
	extern Image* IMAGE_CHR_PARTICLE2;
	extern Image* IMAGE_CHR_PARTICLE3;
	extern Image* IMAGE_CHR_PARTICLE4;
	extern Image* IMAGE_CHR_PARTICLE5;
	extern Image* IMAGE_CHR_PARTICLE6;

	// NightsTUDialog Resources
	bool ExtractNightsTUDialogResources(ResourceManager *theMgr);
	extern Image* IMAGE_DLG_RANDOM_SQUARE;

	// NightsTULocDE Resources
	bool ExtractNightsTULocDEResources(ResourceManager *theMgr);
	extern Image* IMAGE_MARINA_POWERUP_DE;
	extern Image* IMAGE_PARTY_BOLT_DE;

	// NightsTULocEN Resources
	bool ExtractNightsTULocENResources(ResourceManager *theMgr);
	extern Image* IMAGE_MARINA_POWERUP_EN;
	extern Image* IMAGE_PARTY_BOLT_EN;

	// NightsTULocES Resources
	bool ExtractNightsTULocESResources(ResourceManager *theMgr);
	extern Image* IMAGE_MARINA_POWERUP_ES;
	extern Image* IMAGE_PARTY_BOLT_ES;

	// NightsTULocFR Resources
	bool ExtractNightsTULocFRResources(ResourceManager *theMgr);
	extern Image* IMAGE_MARINA_POWERUP_FR;
	extern Image* IMAGE_PARTY_BOLT_FR;

	// NightsTULocIT Resources
	bool ExtractNightsTULocITResources(ResourceManager *theMgr);
	extern Image* IMAGE_MARINA_POWERUP_IT;
	extern Image* IMAGE_PARTY_BOLT_IT;

	// NightsTULocJP Resources
	bool ExtractNightsTULocJPResources(ResourceManager *theMgr);
	extern Image* IMAGE_MARINA_POWERUP_JP;
	extern Image* IMAGE_PARTY_BOLT_JP;

	// NightsTULocKO Resources
	bool ExtractNightsTULocKOResources(ResourceManager *theMgr);
	extern Image* IMAGE_MARINA_POWERUP_KO;
	extern Image* IMAGE_PARTY_BOLT_KO;

	// NightsTULocPT Resources
	bool ExtractNightsTULocPTResources(ResourceManager *theMgr);
	extern Image* IMAGE_MARINA_POWERUP_PT;
	extern Image* IMAGE_PARTY_BOLT_PT;

	// NightsTULocTC Resources
	bool ExtractNightsTULocTCResources(ResourceManager *theMgr);
	extern Image* IMAGE_MARINA_POWERUP_TC;
	extern Image* IMAGE_PARTY_BOLT_TC;

	// PS3 Resources
	bool ExtractPS3Resources(ResourceManager *theMgr);
	extern Image* IMAGE_PS3_21PIX_BUTTONS;
	extern Image* IMAGE_PS3_26PIX_BUTTONS;
	extern Image* IMAGE_PS3_L1_BUTTON;
	extern Image* IMAGE_PS3_L2_BUTTON;
	extern Image* IMAGE_PS3_R1_BUTTON;
	extern Image* IMAGE_PS3_R2_BUTTON;

	// Party Resources
	bool ExtractPartyResources(ResourceManager *theMgr);
	extern Image* IMAGE_PARTY_BESTSHOT;
	extern Image* IMAGE_PARTY_BIGPURPLE;
	extern Image* IMAGE_PARTY_CHAR_BGS;
	extern Image* IMAGE_PARTY_CLOCK_COIN;
	extern Image* IMAGE_PARTY_FEVERMARKERS;
	extern Image* IMAGE_PARTY_HALO_OVER;
	extern Image* IMAGE_PARTY_HALO_UNDER;
	extern Image* IMAGE_PARTY_HOST_BADGE;
	extern Image* IMAGE_PARTY_MARQUE;
	extern Image* IMAGE_PARTY_OPTIONS;
	extern Image* IMAGE_PARTY_PEGS;
	extern Image* IMAGE_PARTY_PIPS;
	extern Image* IMAGE_PARTY_POWERUPS;
	extern Image* IMAGE_PARTY_READY;
	extern Image* IMAGE_PARTY_READY_BUTTON;
	extern Image* IMAGE_PARTY_REPLAYFRAME;
	extern Image* IMAGE_PARTY_RESULTS_BAR;
	extern Image* IMAGE_PARTY_RESYNC;
	extern Image* IMAGE_PARTY_RIBBON1ST;
	extern Image* IMAGE_PARTY_RIBBON2ND;
	extern Image* IMAGE_PARTY_RIBBON3RD;
	extern Image* IMAGE_PARTY_RIBBON4TH;
	extern Image* IMAGE_PARTY_ROUND_COIN;
	extern Image* IMAGE_PARTY_SCOREMARKERS;
	extern Image* IMAGE_PARTY_SHOT_CLOCK;
	extern Image* IMAGE_PARTY_SHOT_CLOCK_GLOW;
	extern Image* IMAGE_PARTY_SIDEBAR;
	extern Image* IMAGE_PARTY_SIDEBAR_FEVER;
	extern Image* IMAGE_PARTY_SIDEBAR_GLOW;
	extern Image* IMAGE_PARTY_SIDEBAR_PLAYER;
	extern Image* IMAGE_PARTY_SIDEBAR_SELECTED;
	extern Image* IMAGE_PARTY_SPEEDLINES;
	extern Image* IMAGE_PARTY_TAPE3;
	extern Image* IMAGE_PARTY_TAPE4;
	extern Image* IMAGE_PARTY_TFX_GLOW;
	extern Image* IMAGE_PARTY_TFX_RAY;
	extern Image* IMAGE_PARTY_TFX_WAVE;
	extern Image* IMAGE_PARTY_TROPHY;
	extern Image* IMAGE_PARTY_ZOOM;

	// RenfieldBorder Resources
	bool ExtractRenfieldBorderResources(ResourceManager *theMgr);
	extern Image* IMAGE_IP_RENFIELD_GUTTER_BG_LEFT;
	extern Image* IMAGE_IP_RENFIELD_GUTTER_BG_RIGHT;
	extern Image* IMAGE_IP_RENFIELD_GUTTER_MIST;
	extern Image* IMAGE_IP_RENF_BOTTOM;
	extern Image* IMAGE_IP_RENF_LEFT;
	extern Image* IMAGE_IP_RENF_RIGHT;
	extern Image* IMAGE_IP_RENF_TOP;

	// SplorkBorder Resources
	bool ExtractSplorkBorderResources(ResourceManager *theMgr);
	extern Image* IMAGE_IP_SPLORK_BOTTOM;
	extern Image* IMAGE_IP_SPLORK_GUTTER_BG_LEFT;
	extern Image* IMAGE_IP_SPLORK_GUTTER_BG_RIGHT;
	extern Image* IMAGE_IP_SPLORK_GUTTER_COMET;
	extern Image* IMAGE_IP_SPLORK_GUTTER_L_PLANETS;
	extern Image* IMAGE_IP_SPLORK_GUTTER_NEBULA;
	extern Image* IMAGE_IP_SPLORK_GUTTER_R_PLANETS;
	extern Image* IMAGE_IP_SPLORK_LEFT;
	extern Image* IMAGE_IP_SPLORK_RIGHT;
	extern Image* IMAGE_IP_SPLORK_TOP;

	// Story Resources
	bool ExtractStoryResources(ResourceManager *theMgr);
	extern Image* IMAGE_STORY_BIGSPARKLE;
	extern Image* IMAGE_STORY_CLAWS;
	extern Image* IMAGE_STORY_GAMERPIC1;
	extern Image* IMAGE_STORY_GAMERPIC2;
	extern Image* IMAGE_STORY_ROCKET;
	extern Image* IMAGE_STORY_WIN;

	// TulaBorder Resources
	bool ExtractTulaBorderResources(ResourceManager *theMgr);
	extern Image* IMAGE_IP_TULA_BOTTOM;
	extern Image* IMAGE_IP_TULA_GUTTER_BG_LEFT;
	extern Image* IMAGE_IP_TULA_GUTTER_BG_RIGHT;
	extern Image* IMAGE_IP_TULA_GUTTER_BLADES;
	extern Image* IMAGE_IP_TULA_GUTTER_BUTTERFLY1;
	extern Image* IMAGE_IP_TULA_GUTTER_BUTTERFLY2;
	extern Image* IMAGE_IP_TULA_GUTTER_BUTTERFLY3;
	extern Image* IMAGE_IP_TULA_LEFT;
	extern Image* IMAGE_IP_TULA_RIGHT;
	extern Image* IMAGE_IP_TULA_TOP;

	// Upsell Resources
	bool ExtractUpsellResources(ResourceManager *theMgr);
	extern Image* IMAGE_UPSELL_JUNK1;

	// WarrenBorder Resources
	bool ExtractWarrenBorderResources(ResourceManager *theMgr);
	extern Image* IMAGE_IP_WARREN_BOTTOM;
	extern Image* IMAGE_IP_WARREN_GUTTER_BG_LEFT;
	extern Image* IMAGE_IP_WARREN_GUTTER_BG_RIGHT;
	extern Image* IMAGE_IP_WARREN_GUTTER_BUNNY_WHEEL;
	extern Image* IMAGE_IP_WARREN_GUTTER_CARDS;
	extern Image* IMAGE_IP_WARREN_GUTTER_DUCKIES;
	extern Image* IMAGE_IP_WARREN_LEFT;
	extern Image* IMAGE_IP_WARREN_RIGHT;
	extern Image* IMAGE_IP_WARREN_TOP;

	enum ResourceId
	{
		IMAGE_SUNGLOW_ID,
		SOUND_MORNING_ID,
		FONT_OVERLOAD16_ID,
		FONT_START1_ID = FONT_OVERLOAD16_ID,
		FONT_OVERLOAD16OUTLINE_ID,
		FONT_OVERLOAD16OUTLINE2_ID,
		FONT_END1_ID = FONT_OVERLOAD16OUTLINE2_ID,
		IMAGE_LOAD_OVERLAY_ID,
		IMAGE_LOAD_LIGHTS_ID,
		IMAGE_LOAD_LOGO_ID,
		IMAGE_LOAD_SHADOW_ID,
		IMAGE_LOAD_SUNHEAD_ID,
		IMAGE_LOAD_PLAYNOW_ID,
		IMAGE_LOAD_BALL_ID,
		IMAGE_LOAD_TM_ID,
		FONT_PLAIN_ID,
		FONT_START2_ID = FONT_PLAIN_ID,
		FONT_PLAIN2BIG_ID,
		FONT_SMALL_ID,
		FONT_SMALLMONO_ID,
		FONT_SCORE_DISP_ID,
		FONT_SMALL_DISP_ID,
		FONT_BALLSLEFT_ID,
		FONT_BUTTON_ID,
		FONT_STAGE_ID,
		FONT_BONK_ID,
		FONT_OVERLOAD10_ID,
		FONT_OVERLOAD12_ID,
		FONT_OVERLOAD24_ID,
		FONT_LEVELUP_ID,
		FONT_OVERLOADMONO10_ID,
		FONT_OVERLOADMONO12_ID,
		FONT_OVERLOAD10OUTLINE_ID,
		FONT_OVERLOAD12OUTLINE_ID,
		FONT_OVERLOAD24OUTLINE_ID,
		FONT_OVERLOAD24GRAD1_ID,
		FONT_OVERLOAD24GRAD2_ID,
		FONT_PLAINOUTLINE_ID,
		FONT_PLAIN2_ID,
		FONT_PLAIN2OUTLINE_ID,
		FONT_PLAIN2BIGOUTLINE_ID,
		FONT_END2_ID = FONT_PLAIN2BIGOUTLINE_ID,
		SOUND_PEGHIT_LOW_ID,
		SOUND_START_ID = SOUND_PEGHIT_LOW_ID,
		SOUND_PEGHIT_ID,
		SOUND_PEGHIT2_ID,
		SOUND_PEGHIT3_ID,
		SOUND_EXTRABALL_ID,
		SOUND_EXTRABALL2_ID,
		SOUND_EXTRABALL3_ID,
		SOUND_MISS_ID,
		SOUND_COINSPIN_ID,
		SOUND_COINSPIN_NO_ID,
		SOUND_FREEBALL_ID,
		SOUND_PENALTY_ID,
		SOUND_LEVELWON_ID,
		SOUND_LEVELDONE_ID,
		SOUND_LEVELLOST_ID,
		SOUND_POWERUP_ID,
		SOUND_AAH_ID,
		SOUND_MULTIBALL_ID,
		SOUND_PEGPOP_ID,
		SOUND_EXPLODE_ID,
		SOUND_BUTTON1_ID,
		SOUND_BUTTON2_ID,
		SOUND_MOUSEOVER_ID,
		SOUND_DING_ID,
		SOUND_POINTBOOST_ID,
		SOUND_TING_ID,
		SOUND_AWARD_ID,
		SOUND_APPLAUSE_ID,
		SOUND_SKILLSHOT_ID,
		SOUND_SPOOKYBALL2_ID,
		SOUND_SPOOKYBALL3_ID,
		SOUND_SPOOKYBALL4_ID,
		SOUND_BUBBLES_ID,
		SOUND_FLIP_ID,
		SOUND_BUCKETHIT_ID,
		SOUND_CANNONCOCK_ID,
		SOUND_CANNONSHOT_ID,
		SOUND_SCORECOUNTER_ID,
		SOUND_FLIPPERUP_ID,
		SOUND_FLIPPERDOWN_ID,
		SOUND_FLIPPERBOUNCE_ID,
		SOUND_RAINBOW_ID,
		SOUND_FIREWORKS1_ID,
		SOUND_FIREWORKS2_ID,
		SOUND_RICHOCHET_ID,
		SOUND_CYMBAL_ID,
		SOUND_SIGH_ID,
		SOUND_WOOSH_ID,
		SOUND_TEXT_WOOSH_ID,
		SOUND_WHISTLE_ID,
		SOUND_FEVERHIT_ID,
		SOUND_FIREBALLLOOP_ID,
		SOUND_FIREBALLSHOT_ID,
		SOUND_FIREBALLBOUNCE_ID,
		SOUND_POWERUP_GUIDE_ID,
		SOUND_POWERUP_MULTIBALL_ID,
		SOUND_POWERUP_PYRAMID_ID,
		SOUND_POWERUP_SPACEBLAST_ID,
		SOUND_POWERUP_FLIPPERS_ID,
		SOUND_POWERUP_SPOOKYBALL_ID,
		SOUND_POWERUP_FLOWERPOWER_ID,
		SOUND_POWERUP_LUCKYSPIN_ID,
		SOUND_POWERUP_FIREBALL_ID,
		SOUND_POWERUP_ZEN_ID,
		SOUND_GONG_ID,
		SOUND_SLOWMO_ID,
		SOUND_END_ID = SOUND_SLOWMO_ID,
		SOUND_TYPING_ID,
		SOUND_STORY_TYPING_ID,
		SOUND_TONELO_ID,
		SOUND_TONE_ID,
		SOUND_TONEHI_ID,
		SOUND_TONESUPERHI_ID,
		SOUND_STAMP_ID,
		SOUND_ADD_BALL_ID,
		SOUND_DIALOG_MOVE_ID,
		SOUND_SCREEN_MOVE_ID,
		SOUND_JOIN_LOBBY_ID,
		SOUND_LEAVE_LOBBY_ID,
		SOUND_NEW_LEVEL_ID,
		SOUND_NEW_LEVEL_FAST1_ID,
		SOUND_NEW_LEVEL_FAST2_ID,
		SOUND_NEW_LEVEL_FAST3_ID,
		SOUND_NEW_LEVEL_FAST4_ID,
		SOUND_NEW_SHOTCLOCK_ID,
		SOUND_ALL_RANDOM_ON_ID,
		SOUND_ALL_RANDOM_OFF_ID,
		SOUND_OPTIONS_CONFIRM_ID,
		SOUND_OPTIONS_CANCEL_ID,
		SOUND_START_VIEW_BOARD_ID,
		SOUND_STOP_VIEW_BOARD_ID,
		SOUND_SCORE_BAR_REFILL_ID,
		SOUND_SCORE_BAR_TICK_ID,
		SOUND_SCORE_BAR_FILL_ID,
		SOUND_STYLE_SHOT_FILL_ID,
		SOUND_TROPHY_STAY_ID,
		SOUND_RESULTS_TEXT_ID,
		SOUND_ROUND_DISC_ID,
		SOUND_SHOT_CLOCK_SUBTLE_ID,
		SOUND_RIBBON_AWARD_ID,
		SOUND_PLAYER_READY_ID,
		SOUND_BEST_SHOT_ID,
		SOUND_SHOT_25K_ID,
		SOUND_SHOT_75K_ID,
		SOUND_SHOT_125K_ID,
		SOUND_SCORE_BAR_EXPLODE_ID,
		SOUND_NUM_ROUNDS_CHANGE_ID,
		SOUND_SCORE_BAR_EXPLODE_WIN_ID,
		SOUND_RIBBON_4TH_ID,
		SOUND_RIBBON_3RD_ID,
		SOUND_RIBBON_2ND_ID,
		SOUND_FIREWORKPOP_ID,
		IMAGE_INT_BALL_ID,
		IMAGE_INT_BALLBACK_ID,
		IMAGE_INT_BUTTONCOVER_ID,
		IMAGE_INT_CANNON_ID,
		IMAGE_INT_CANNONCOVER_ID,
		IMAGE_INT_PLUNGER_ID,
		IMAGE_INT_BALLGLASS_ID,
		IMAGE_INT_FEVERMETER_ID,
		IMAGE_INT_FEVERMETERTOP_ID,
		IMAGE_INT_FEVERMETERBOTTOM_ID,
		IMAGE_INT_FEVERRAILING_ID,
		IMAGE_INT_FEVERBARS_ID,
		IMAGE_INT_FEVERBARLITES_ID,
		IMAGE_INT_COUNTER_ID,
		IMAGE_INT_FREEBALLMETER_ID,
		IMAGE_INT_FREEBALLMETERTOP_ID,
		IMAGE_INT_BACKSHADOW_ID,
		IMAGE_INT_FEVERGLOW_ID,
		IMAGE_INT_FEVERGLOW1_ID,
		IMAGE_INT_FEVERGLOW2_ID,
		IMAGE_INT_FEVERGLOW3_ID,
		IMAGE_INT_SCOREHILIGHT_ID,
		IMAGE_INT_BALLOMASKBL_ID,
		IMAGE_INT_BALLOMASKBR_ID,
		IMAGE_INT_BALLOMASKTL_ID,
		IMAGE_INT_BALLOMASKTR_ID,
		IMAGE_INT_FBCENTERDISC_ID,
		IMAGE_INT_FBGLOW_ID,
		IMAGE_INT_FBFREEBALL_ID,
		IMAGE_INT_FBLIGHTUP_ID,
		IMAGE_INT_FBPOINTS_ID,
		IMAGE_INT_BIGMENUBUTTON_ID,
		IMAGE_INT_LEVELSELECTBUTTON_ID,
		IMAGE_INT_PADLOCK_ID,
		IMAGE_INT_BIGDLGBUTTON_ID,
		IMAGE_INT_BIGMENUGLOW_ID,
		IMAGE_INT_BIGDLGGLOW_ID,
		IMAGE_INT_BGCHECKBOX_ID,
		IMAGE_INT_BGCHECKGLOW_ID,
		IMAGE_INT_COLORCHECK_ID,
		IMAGE_INT_CONTROLS_ID,
		IMAGE_INT_LEVELSELECT_ID,
		IMAGE_INT_LEVELSELECTGLOW_ID,
		IMAGE_IP_B_ID,
		IMAGE_IP_BLC_ID,
		IMAGE_IP_BRC_ID,
		IMAGE_IP_L1_ID,
		IMAGE_IP_L2_ID,
		IMAGE_IP_R1_ID,
		IMAGE_IP_R2_ID,
		IMAGE_IP_TL1_ID,
		IMAGE_IP_TL2_ID,
		IMAGE_IP_TR1_ID,
		IMAGE_IP_TR2_ID,
		IMAGE_IP_TLC_ID,
		IMAGE_IP_TRC_ID,
		IMAGE_IP_SEAMS_ID,
		IMAGE_IP_SHOOTERBACK_ID,
		IMAGE_IP_SHOOTER_ID,
		IMAGE_IP_BALLOTRON_ID,
		IMAGE_IP_FEVERMETER_ID,
		IMAGE_IP_LWINDOW_ID,
		IMAGE_IP_RWINDOW_ID,
		IMAGE_IP_SHOOTERORB_ID,
		IMAGE_IP_POWERUPBANNER_ID,
		IMAGE_IP_ORBGLOW_ID,
		IMAGE_IP_LEXTEND_ID,
		IMAGE_IP_REXTEND_ID,
		IMAGE_IP_TEXTEND_ID,
		IMAGE_IP_BEXTEND_ID,
		IMAGE_IP_PARTY_TOP_ID,
		IMAGE_IP_PARTY_LEFT_ID,
		IMAGE_IP_PARTY_RIGHT_ID,
		IMAGE_IP_PARTY_BOTTOM_ID,
		IMAGE_IP_GOLD_PLATE_ID,
		IMAGE_IP_TITLEBAR_ID,
		IMAGE_IP_TITLEGLOSS_ID,
		IMAGE_IP_TITLELC_ID,
		IMAGE_IP_TITLERC_ID,
		IMAGE_IP_TITLESLIDER_ID,
		IMAGE_MM_SPEECHBUBBLE_ID,
		IMAGE_MM_CRY_ID,
		IMAGE_MM_BUYIT_ID,
		IMAGE_MM_TROPHIES_ID,
		IMAGE_MM_TROPHYREVEAL_ID,
		IMAGE_MM_MURAL_MP_ID,
		IMAGE_MM_MURAL_BACK_MP_ID,
		IMAGE_MM_MURAL_SP_ID,
		IMAGE_MM_MURAL_BACK_SP_ID,
		IMAGE_MM_MURAL_WAIT_ID,
		IMAGE_MM_MURAL_BACK_WAIT_ID,
		IMAGE_MM_BLANKSUN_ID,
		IMAGE_LB_BACKING_ID,
		IMAGE_LB_HOLDER_ID,
		IMAGE_LB_100_ID,
		IMAGE_LB_FREEBALL_ID,
		IMAGE_LB_NOBALL_ID,
		IMAGE_LB_SHOT_ID,
		IMAGE_LB_ZEN_ID,
		IMAGE_LB_GAMECLIP_ID,
		IMAGE_LB_GAMECLIP_SMALL_ID,
		IMAGE_LB_GAMECLIP_SMALL_STROKE_ID,
		IMAGE_LB_MASTER0_ID,
		IMAGE_LB_MASTER1_ID,
		IMAGE_LB_MASTER2_ID,
		IMAGE_LB_MASTER3_ID,
		IMAGE_LB_MASTER4_ID,
		IMAGE_LB_MASTER5_ID,
		IMAGE_LB_MASTER6_ID,
		IMAGE_LB_MASTER7_ID,
		IMAGE_LB_MASTER8_ID,
		IMAGE_LB_MASTER9_ID,
		IMAGE_LS_LOCK_ID,
		IMAGE_LS_LOCK_SMALL_ID,
		IMAGE_LS_CHALLENGEBADGE_ID,
		IMAGE_LS_RANDOMLEVEL_ID,
		IMAGE_LS_TINYBLUERIBBON_ID,
		IMAGE_LS_TINYMASTER_ID,
		IMAGE_LS_DOWNLOAD_ID,
		IMAGE_LS_WATERMARK_ID,
		IMAGE_HELP_ICONS_ID,
		IMAGE_HELP_ICONS2_ID,
		IMAGE_HAT_ID,
		IMAGE_MAGICHAT_ID,
		IMAGE_SPARKLE_ID,
		IMAGE_SPARKLE_FEVER_ID,
		IMAGE_STREAK_ID,
		IMAGE_FLOWER_ID,
		IMAGE_POWERUPICON_ID,
		IMAGE_SCOREICON_ID,
		IMAGE_BONUSHALO_ID,
		IMAGE_BONUSGLOW_ID,
		IMAGE_BONUSGLOW_GREEN_ID,
		IMAGE_BONUSGLOW_BLUE_ID,
		IMAGE_BONUS5000_ID,
		IMAGE_BONUS10000_ID,
		IMAGE_BONUS25000_ID,
		IMAGE_BONUS50000_ID,
		IMAGE_BONUS100000_ID,
		IMAGE_BONUS5000LIGHT_ID,
		IMAGE_BONUS10000LIGHT_ID,
		IMAGE_BONUS25000LIGHT_ID,
		IMAGE_BONUS50000LIGHT_ID,
		IMAGE_BONUS100000LIGHT_ID,
		IMAGE_BALL_ID,
		IMAGE_YINYANG_ID,
		IMAGE_GUIDERECT_ID,
		IMAGE_GUIDERECT2_ID,
		IMAGE_ALPHABALL_ID,
		IMAGE_GUIDEARROW_ID,
		IMAGE_GUIDEPOINT_ID,
		IMAGE_GUIDEHIT_ID,
		IMAGE_BRICK_ID,
		IMAGE_BRICKCB_ID,
		IMAGE_BALLPEG_ID,
		IMAGE_BALLPEGCB_ID,
		IMAGE_BALLSHADOW_ID,
		IMAGE_PEGSHADOW_ID,
		IMAGE_BIGBALLSHADOW_ID,
		IMAGE_BIGBALL_ID,
		IMAGE_DEFINNERPEG_ID,
		IMAGE_DEFOUTERPEG_ID,
		IMAGE_CIRCLE_ID,
		IMAGE_FIREBALLFIRE_ID,
		IMAGE_FIREBALL_ID,
		IMAGE_COINHEADS_ID,
		IMAGE_COINTAILS_ID,
		IMAGE_COINHILIGHT_ID,
		IMAGE_BUBBLES_ID,
		IMAGE_BRICKGLOW_ID,
		IMAGE_PEGGLOW_ID,
		IMAGE_PYRAMIDRAY_ID,
		IMAGE_FEVERRAY_ID,
		IMAGE_FEVERGLOWSTAR_ID,
		IMAGE_FEVERSTAR_RED_ID,
		IMAGE_FEVERSTAR_GREEN_ID,
		IMAGE_FEVERSTAR_BLUE_ID,
		IMAGE_FEVERSPARK_ID,
		IMAGE_FEVERTRAIL_ID,
		IMAGE_FEVERRAINBOW_ID,
		IMAGE_FEVERSCORE_ID,
		IMAGE_FEVERSCORETOP_ID,
		IMAGE_STAR_STREAK_ID,
		IMAGE_TIPARROW_ID,
		IMAGE_BLUERIBBON_ID,
		IMAGE_TINYBLUERIBBON_ID,
		IMAGE_MASTERBADGE_ID,
		IMAGE_PAUSED_ID,
		IMAGE_CATCHERGLOW_ID,
		IMAGE_PYRAMIDBALL_ID,
		IMAGE_JIMMY_ID,
		IMAGE_JIMMYSPEECH_ID,
		IMAGE_FEVERCAM_ID,
		IMAGE_XFEVER_ID,
		IMAGE_XFEVERGLOW_ID,
		IMAGE_PULSE_NORMAL_ID,
		IMAGE_PULSE_GOAL_ID,
		IMAGE_PULSE_SCORE_ID,
		IMAGE_PULSE_POWERUP_ID,
		IMAGE_PULSE2_SCORE_ID,
		IMAGE_PULSE2_POWERUP_ID,
		IMAGE_SPACEBURST_ID,
		IMAGE_SPACEBUBBLE_ID,
		IMAGE_SPACEHALO_ID,
		IMAGE_SPACESTAR_ID,
		IMAGE_SPOOKYPOOF1_ID,
		IMAGE_SPOOKYPOOF2_ID,
		IMAGE_SPOOKYGHOST_ID,
		IMAGE_SPOOKYTRAIL_ID,
		IMAGE_SPOOKYEYES_ID,
		IMAGE_EMBER_ID,
		IMAGE_SMOKE_ID,
		IMAGE_FLECK_ID,
		IMAGE_FLAMETRAIL_ID,
		IMAGE_NUKE_ID,
		IMAGE_NUKESTREAK_ID,
		IMAGE_VS_DUEL_ID,
		IMAGE_VS_DUELBACK_ID,
		IMAGE_FEVERBORDER_ID,
		IMAGE_DLG_BOTTOMBAR_ID,
		IMAGE_DLG_RANDOM_ID,
		IMAGE_DLG_BLUEFRAME_ID,
		IMAGE_DLG_GRAYFRAME_ID,
		IMAGE_DLG_SELECTORFRAME_ID,
		IMAGE_DLG_BUTTON1_ID,
		IMAGE_DLG_BUTTON2_ID,
		IMAGE_DLG_BUTTON3_ID,
		IMAGE_DLG_BROWNBUTTON1_ID,
		IMAGE_DLG_BROWNBUTTON2_ID,
		IMAGE_DLG_GREENOK_ID,
		IMAGE_DLG_POPUP_ID,
		IMAGE_DLG_TEXTBOX_ID,
		IMAGE_DLG_HORZBAR_ID,
		IMAGE_DLG_LJOINT_ID,
		IMAGE_DLG_EDITBUTTON_ID,
		IMAGE_DLG_DIALOGBOX_ID,
		IMAGE_DLG_SLIDER_ID,
		IMAGE_DLG_SLIDERHILIGHT_ID,
		IMAGE_DLG_SLIDERORB_ID,
		IMAGE_DLG_FRAME1_ID,
		IMAGE_DLG_FRAME2_ID,
		IMAGE_DLG_FRAME3_ID,
		IMAGE_DLG_SEGMENT_ID,
		IMAGE_DLG_CONNECTOR_ID,
		IMAGE_DLG_REPLAYTOP_ID,
		IMAGE_DLG_REPLAYSEGMENT_ID,
		IMAGE_DLG_STAGEBULLET_ID,
		IMAGE_DLG_MASTERSTAGE_ID,
		IMAGE_DLG_MASTERSTAGEPROGBAR_ID,
		IMAGE_DLG_PLAYWIDGET1_ID,
		IMAGE_DLG_PLAYWIDGET2_ID,
		IMAGE_DLG_PLAYBUTTON1_ID,
		IMAGE_DLG_PLAYBUTTON2_ID,
		IMAGE_DLG_STAGEBAR_ID,
		IMAGE_DLG_STAGEPROGRESSBAR_ID,
		IMAGE_DLG_TEXTRECT_ID,
		IMAGE_DLG_QUESTIONMARK_ID,
		IMAGE_DLG_BIGQUESTIONMARK_ID,
		IMAGE_DLG_TIP_ID,
		IMAGE_DLG_INSTRUCTIONS_ID,
		IMAGE_DLG_INSTRUCTIONS2_ID,
		IMAGE_DLG_INSTRUCTIONS3_ID,
		IMAGE_DLG_INSTRUCTIONS4_ID,
		IMAGE_DLG_BUTTONOVERLAY2_ID,
		IMAGE_DLG_PURPLEBUTTON_ID,
		IMAGE_DLG_MENU_ID,
		IMAGE_DLG_INSTANTREPLAY_ID,
		IMAGE_DLG_REPLAYSPIN_ID,
		IMAGE_DLG_HELP_BAR_ID,
		IMAGE_DLG_HELP_SLIDER_ID,
		IMAGE_DLG_HELP_LB_SLIDER_ID,
		IMAGE_DLG_HELP_RB_SLIDER_ID,
		IMAGE_DLG_HELP_BUTTONS_ID,
		IMAGE_DLG_GLOSS_ID,
		IMAGE_DLG_ETCHINGS_ID,
		IMAGE_CHR_CHARACTERS_ID,
		IMAGE_CHR_CHARACTERSHADOWS_ID,
		IMAGE_CHR_CHARACTER1_ID,
		IMAGE_CHR_CHARACTER2_ID,
		IMAGE_CHR_CHARACTER3_ID,
		IMAGE_CHR_CHARACTER4_ID,
		IMAGE_CHR_CHARACTER5_ID,
		IMAGE_CHR_CHARACTER6_ID,
		IMAGE_CHR_CHARACTER7_ID,
		IMAGE_CHR_CHARACTER8_ID,
		IMAGE_CHR_CHARACTER9_ID,
		IMAGE_CHR_CHARACTER10_ID,
		IMAGE_CHR_CHARACTER11_ID,
		IMAGE_CHR_YINYANGEYE_ID,
		IMAGE_SPIN_SPINNER_ID,
		IMAGE_SPIN_ARROW_ID,
		IMAGE_SPIN_HATON_ID,
		IMAGE_SPIN_EXTRAON_ID,
		IMAGE_SPIN_TRIPLEON_ID,
		IMAGE_SPIN_RANDOMON_ID,
		IMAGE_SPIN_RANDOMTEXT_ID,
		IMAGE_SPIN_RANDOMTEXTON_ID,
		IMAGE_SPIN_RIMLIGHT_ID,
		IMAGE_SPIN_RIMLIGHT2_ID,
		IMAGE_SPIN_EXTRABALLMASK_ID,
		IMAGE_PARTY_MARQUE_ID,
		IMAGE_PARTY_OPTIONS_ID,
		IMAGE_PARTY_SIDEBAR_ID,
		IMAGE_PARTY_SIDEBAR_PLAYER_ID,
		IMAGE_PARTY_SIDEBAR_SELECTED_ID,
		IMAGE_PARTY_SIDEBAR_GLOW_ID,
		IMAGE_PARTY_SIDEBAR_FEVER_ID,
		IMAGE_PARTY_RESULTS_BAR_ID,
		IMAGE_PARTY_ROUND_COIN_ID,
		IMAGE_PARTY_CLOCK_COIN_ID,
		IMAGE_PARTY_SHOT_CLOCK_ID,
		IMAGE_PARTY_SHOT_CLOCK_GLOW_ID,
		IMAGE_PARTY_TROPHY_ID,
		IMAGE_PARTY_TFX_RAY_ID,
		IMAGE_PARTY_TFX_WAVE_ID,
		IMAGE_PARTY_TFX_GLOW_ID,
		IMAGE_PARTY_RIBBON1ST_ID,
		IMAGE_PARTY_RIBBON2ND_ID,
		IMAGE_PARTY_RIBBON3RD_ID,
		IMAGE_PARTY_RIBBON4TH_ID,
		IMAGE_PARTY_PEGS_ID,
		IMAGE_PARTY_CHAR_BGS_ID,
		IMAGE_PARTY_BESTSHOT_ID,
		IMAGE_PARTY_POWERUPS_ID,
		IMAGE_PARTY_SPEEDLINES_ID,
		IMAGE_PARTY_ZOOM_ID,
		IMAGE_PARTY_READY_ID,
		IMAGE_PARTY_SCOREMARKERS_ID,
		IMAGE_PARTY_FEVERMARKERS_ID,
		IMAGE_PARTY_PIPS_ID,
		IMAGE_PARTY_TAPE3_ID,
		IMAGE_PARTY_TAPE4_ID,
		IMAGE_PARTY_BIGPURPLE_ID,
		IMAGE_PARTY_REPLAYFRAME_ID,
		IMAGE_PARTY_HOST_BADGE_ID,
		IMAGE_PARTY_READY_BUTTON_ID,
		IMAGE_PARTY_HALO_OVER_ID,
		IMAGE_PARTY_HALO_UNDER_ID,
		IMAGE_PARTY_RESYNC_ID,
		IMAGE_DUEL_LOBBY_PLAYER_ID,
		IMAGE_STORY_WIN_ID,
		IMAGE_STORY_CLAWS_ID,
		IMAGE_STORY_GAMERPIC1_ID,
		IMAGE_STORY_GAMERPIC2_ID,
		IMAGE_STORY_ROCKET_ID,
		IMAGE_STORY_BIGSPARKLE_ID,
		IMAGE_UPSELL_JUNK1_ID,
		IMAGE_LIGHTNING_ROD_ID,
		IMAGE_LIGHTNING_ROD_ZAP_ID,
		IMAGE_LIGHTNING_ROD_ON_ID,
		IMAGE_LIGHTNING_ROD_RING_FRONT_ID,
		IMAGE_LIGHTNING_ROD_RING_BACK_ID,
		IMAGE_BALL_LIGHTNING_ID,
		IMAGE_LIGHTNING_FRONT_ID,
		IMAGE_LIGHTNING_FRONT_SMALL_ID,
		IMAGE_LIGHTNING_ID,
		IMAGE_LIGHTNING_BACK_ID,
		IMAGE_LIGHTNING_SPARK_ID,
		IMAGE_LIGHTNING_BALLSPARK_ID,
		IMAGE_SUPERSWIRL_ID,
		IMAGE_CURVE_ID,
		IMAGE_NIGHTS_BUTTON_ID,
		IMAGE_FLY0_ID,
		IMAGE_FLY1_ID,
		IMAGE_ADDTL_GLOW_ID,
		IMAGE_OTHERBUTTON_GLOW_ID,
		IMAGE_TWINKLE_STAR_ID,
		IMAGE_MARINA_LOGO_ID,
		IMAGE_MARINA_SHOOTER_ID,
		IMAGE_MARINA_BG_ID,
		SOUND_APPLAUSE_LONG_ID,
		SOUND_LOGO_BUZZ_ON_ID,
		SOUND_NEON_FLICKER_ID,
		SOUND_TROPHY_PHOTO_IN_ID,
		SOUND_STAGE_DREAMY_IN_ID,
		SOUND_STAGE_DREAMY_OUT_ID,
		SOUND_POWERUP_LIGHTNING_HIT_ID,
		SOUND_CREDITS_SPOTLIGHT_ON_ID,
		SOUND_SPEECH_BUBBLE_POPUP_ID,
		SOUND_TROPHY_WIN_INTRO_ID,
		SOUND_POWERUP_LIGHTNING_ID,
		SOUND_LIGHTNING_LOOP_ID,
		SOUND_LIGHTNING_START_ID,
		SOUND_PEGSPARK_ID,
		SOUND_INTRO_ID,
		IMAGE_MARINA_POWERUP_EN_ID,
		IMAGE_PARTY_BOLT_EN_ID,
		IMAGE_MARINA_POWERUP_FR_ID,
		IMAGE_PARTY_BOLT_FR_ID,
		IMAGE_MARINA_POWERUP_DE_ID,
		IMAGE_PARTY_BOLT_DE_ID,
		IMAGE_MARINA_POWERUP_PT_ID,
		IMAGE_PARTY_BOLT_PT_ID,
		IMAGE_MARINA_POWERUP_ES_ID,
		IMAGE_PARTY_BOLT_ES_ID,
		IMAGE_MARINA_POWERUP_IT_ID,
		IMAGE_PARTY_BOLT_IT_ID,
		IMAGE_MARINA_POWERUP_KO_ID,
		IMAGE_PARTY_BOLT_KO_ID,
		IMAGE_MARINA_POWERUP_JP_ID,
		IMAGE_PARTY_BOLT_JP_ID,
		IMAGE_MARINA_POWERUP_TC_ID,
		IMAGE_PARTY_BOLT_TC_ID,
		IMAGE_CHR_CHARACTERS_NIGHTS_ID,
		IMAGE_CHR_CHARACTERSHADOWS_NIGHTS_ID,
		IMAGE_CHR_CHARACTER_MARINA_ID,
		IMAGE_CHR_CHARACTER_ADV12_ID,
		IMAGE_CHR_CHARACTER_NEW1_ID,
		IMAGE_CHR_CHARACTER_NEW2_ID,
		IMAGE_CHR_CHARACTER_NEW3_ID,
		IMAGE_CHR_CHARACTER_NEW4_ID,
		IMAGE_CHR_CHARACTER_NEW5_ID,
		IMAGE_CHR_CHARACTER_NEW6_ID,
		IMAGE_CHR_CHARACTER_NEW7_ID,
		IMAGE_CHR_CHARACTER_NEW8_ID,
		IMAGE_CHR_CHARACTER_NEW9_ID,
		IMAGE_CHR_CHARACTER_NEW10_ID,
		IMAGE_CHR_PARTICLE1_ID,
		IMAGE_CHR_PARTICLE2_ID,
		IMAGE_CHR_PARTICLE3_ID,
		IMAGE_CHR_PARTICLE4_ID,
		IMAGE_CHR_PARTICLE5_ID,
		IMAGE_CHR_PARTICLE6_ID,
		IMAGE_DLG_RANDOM_SQUARE_ID,
		IMAGE_MM_TROPHY_ZEN_ID,
		IMAGE_MM_TROPHY_CROWN_ID,
		IMAGE_MM_TROPHY_CUP_ID,
		IMAGE_MM_TROPHY_TORCH_ID,
		IMAGE_MM_MARINASTAGE_ID,
		IMAGE_LOAD_MURAL_SP_NIGHT_ID,
		IMAGE_LOAD_MURAL_WAIT_NIGHT_ID,
		IMAGE_LOAD_MURAL_BG_WAIT_NIGHT_ID,
		IMAGE_LOAD_NIGHTSLOGO_MOON_ID,
		IMAGE_LOAD_SUNSET_BG_ID,
		IMAGE_LOAD_LENSFLARE_ID,
		IMAGE_LOAD_GODRAY_ID,
		IMAGE_LOAD_RIM_LIGHT_ID,
		IMAGE_TROPHY_CURTAIN_ID,
		IMAGE_TROPHY_CURTAIN_L_ID,
		IMAGE_TROPHY_CURTAIN_R_ID,
		IMAGE_TROPHY_PARTICLE_WHITE_MED_ROUND_ID,
		IMAGE_TROPHY_MASTER1_ID,
		IMAGE_TROPHY_MASTER2_ID,
		IMAGE_TROPHY_MASTER3_ID,
		IMAGE_TROPHY_ADV_ID,
		IMAGE_TROPHY_PARTICLE1_ID,
		IMAGE_TROPHY_PARTICLE2_ID,
		IMAGE_TROPHY_PARTICLE3_ID,
		IMAGE_TROPHY_PARTICLE4_ID,
		IMAGE_TROPHY_PARTICLE5_ID,
		IMAGE_TROPHY_PARTICLE6_ID,
		IMAGE_TROPHY_HOLE_ID,
		IMAGE_TROPHY_EXIT_BUTTON_ID,
		IMAGE_TROPHY_SPARKLE_ID,
		IMAGE_TROPHY_SPEECH_BR_ID,
		IMAGE_TROPHY_SPEECH_BL_ID,
		IMAGE_TROPHY_SPEECH_B_ID,
		IMAGE_TROPHY_SPEECH_BP_ID,
		IMAGE_TROPHY_SPEECH_C_ID,
		IMAGE_TROPHY_SPEECH_L_ID,
		IMAGE_TROPHY_SPEECH_R_ID,
		IMAGE_TROPHY_SPEECH_LP_ID,
		IMAGE_TROPHY_SPEECH_RP_ID,
		IMAGE_TROPHY_SPEECH_T_ID,
		IMAGE_TROPHY_SPEECH_TL_ID,
		IMAGE_TROPHY_SPEECH_TP_ID,
		IMAGE_TROPHY_SPEECH_TR_ID,
		IMAGE_IP_MARINA_TOP_ID,
		IMAGE_IP_MARINA_LEFT_ID,
		IMAGE_IP_MARINA_RIGHT_ID,
		IMAGE_IP_MARINA_BOTTOM_ID,
		IMAGE_IP_MARINA_GUTTER_LEFT_ID,
		IMAGE_IP_MARINA_GUTTER_RIGHT_ID,
		IMAGE_IP_MARINA_GUTTER_JELLYFISH1_ID,
		IMAGE_IP_MARINA_GUTTER_JELLYFISH2_ID,
		IMAGE_IP_BJORN_TOP_ID,
		IMAGE_IP_BJORN_LEFT_ID,
		IMAGE_IP_BJORN_RIGHT_ID,
		IMAGE_IP_BJORN_BOTTOM_ID,
		IMAGE_IP_BJORN_GUTTER_BG_LEFT_ID,
		IMAGE_IP_BJORN_GUTTER_BG_RIGHT_ID,
		IMAGE_IP_BJORN_GUTTER_HILL_ID,
		IMAGE_IP_BJORN_GUTTER_TREE_ID,
		IMAGE_IP_BJORN_GUTTER_CLOUDS_ID,
		IMAGE_IP_JIMMY_TOP_ID,
		IMAGE_IP_JIMMY_LEFT_ID,
		IMAGE_IP_JIMMY_RIGHT_ID,
		IMAGE_IP_JIMMY_BOTTOM_ID,
		IMAGE_IP_JIMMY_GUTTER_BG_LEFT_ID,
		IMAGE_IP_JIMMY_GUTTER_BG_RIGHT_ID,
		IMAGE_IP_JIMMY_GUTTER_L_FALL1_ID,
		IMAGE_IP_JIMMY_GUTTER_L_FALL2_ID,
		IMAGE_IP_JIMMY_GUTTER_R_FALL1_ID,
		IMAGE_IP_JIMMY_GUTTER_R_FALL2_ID,
		IMAGE_IP_JIMMY_GUTTER_L_FOREGROUND_ID,
		IMAGE_IP_JIMMY_GUTTER_R_FOREGROUND_ID,
		IMAGE_IP_KATTUT_TOP_ID,
		IMAGE_IP_KATTUT_LEFT_ID,
		IMAGE_IP_KATTUT_RIGHT_ID,
		IMAGE_IP_KATTUT_BOTTOM_ID,
		IMAGE_IP_KATTUT_GUTTER_BG_LEFT_ID,
		IMAGE_IP_KATTUT_GUTTER_BG_RIGHT_ID,
		IMAGE_IP_KATTUT_GUTTER_CLOUDS_ID,
		IMAGE_IP_SPLORK_TOP_ID,
		IMAGE_IP_SPLORK_LEFT_ID,
		IMAGE_IP_SPLORK_RIGHT_ID,
		IMAGE_IP_SPLORK_BOTTOM_ID,
		IMAGE_IP_SPLORK_GUTTER_BG_LEFT_ID,
		IMAGE_IP_SPLORK_GUTTER_BG_RIGHT_ID,
		IMAGE_IP_SPLORK_GUTTER_COMET_ID,
		IMAGE_IP_SPLORK_GUTTER_L_PLANETS_ID,
		IMAGE_IP_SPLORK_GUTTER_R_PLANETS_ID,
		IMAGE_IP_SPLORK_GUTTER_NEBULA_ID,
		IMAGE_IP_RENF_TOP_ID,
		IMAGE_IP_RENF_LEFT_ID,
		IMAGE_IP_RENF_RIGHT_ID,
		IMAGE_IP_RENF_BOTTOM_ID,
		IMAGE_IP_RENFIELD_GUTTER_BG_LEFT_ID,
		IMAGE_IP_RENFIELD_GUTTER_BG_RIGHT_ID,
		IMAGE_IP_RENFIELD_GUTTER_MIST_ID,
		IMAGE_IP_CLAUDE_TOP_ID,
		IMAGE_IP_CLAUDE_LEFT_ID,
		IMAGE_IP_CLAUDE_RIGHT_ID,
		IMAGE_IP_CLAUDE_BOTTOM_ID,
		IMAGE_IP_CLAUDE_GUTTER_BG_LEFT_ID,
		IMAGE_IP_CLAUDE_GUTTER_BG_RIGHT_ID,
		IMAGE_IP_CLAUDE_GUTTER_BIG_FISH1_ID,
		IMAGE_IP_CLAUDE_GUTTER_BIG_FISH2_ID,
		IMAGE_IP_CLAUDE_GUTTER_BIG_FISH3_ID,
		IMAGE_IP_CLAUDE_GUTTER_SMALL_FISH1_ID,
		IMAGE_IP_CLAUDE_GUTTER_SMALL_FISH2_ID,
		IMAGE_IP_CLAUDE_GUTTER_SMALL_FISH3_ID,
		IMAGE_IP_CLAUDE_GUTTER_L_KELP_ID,
		IMAGE_IP_CLAUDE_GUTTER_R_KELP_ID,
		IMAGE_IP_TULA_TOP_ID,
		IMAGE_IP_TULA_LEFT_ID,
		IMAGE_IP_TULA_RIGHT_ID,
		IMAGE_IP_TULA_BOTTOM_ID,
		IMAGE_IP_TULA_GUTTER_BG_LEFT_ID,
		IMAGE_IP_TULA_GUTTER_BG_RIGHT_ID,
		IMAGE_IP_TULA_GUTTER_BUTTERFLY1_ID,
		IMAGE_IP_TULA_GUTTER_BUTTERFLY2_ID,
		IMAGE_IP_TULA_GUTTER_BUTTERFLY3_ID,
		IMAGE_IP_TULA_GUTTER_BLADES_ID,
		IMAGE_IP_WARREN_TOP_ID,
		IMAGE_IP_WARREN_LEFT_ID,
		IMAGE_IP_WARREN_RIGHT_ID,
		IMAGE_IP_WARREN_BOTTOM_ID,
		IMAGE_IP_WARREN_GUTTER_BG_LEFT_ID,
		IMAGE_IP_WARREN_GUTTER_BG_RIGHT_ID,
		IMAGE_IP_WARREN_GUTTER_DUCKIES_ID,
		IMAGE_IP_WARREN_GUTTER_BUNNY_WHEEL_ID,
		IMAGE_IP_WARREN_GUTTER_CARDS_ID,
		IMAGE_IP_CINDER_TOP_ID,
		IMAGE_IP_CINDER_LEFT_ID,
		IMAGE_IP_CINDER_RIGHT_ID,
		IMAGE_IP_CINDER_BOTTOM_ID,
		IMAGE_IP_CINDERBOTTOM_GUTTER_BG_LEFT_ID,
		IMAGE_IP_CINDERBOTTOM_GUTTER_BG_RIGHT_ID,
		IMAGE_IP_HU_TOP_ID,
		IMAGE_IP_HU_LEFT_ID,
		IMAGE_IP_HU_RIGHT_ID,
		IMAGE_IP_HU_BOTTOM_ID,
		IMAGE_IP_MASTERHU_GUTTER_BG_LEFT_ID,
		IMAGE_IP_MASTERHU_GUTTER_BG_RIGHT_ID,
		IMAGE_IP_MASTERHU_GUTTER_L_HILL_ID,
		IMAGE_IP_MASTERHU_GUTTER_R_HILL_ID,
		IMAGE_IP_MASTERHU_GUTTER_CLOUD_ID,
		IMAGE_PS3_21PIX_BUTTONS_ID,
		IMAGE_PS3_26PIX_BUTTONS_ID,
		IMAGE_PS3_L1_BUTTON_ID,
		IMAGE_PS3_L2_BUTTON_ID,
		IMAGE_PS3_R1_BUTTON_ID,
		IMAGE_PS3_R2_BUTTON_ID,
		RESOURCE_ID_MAX
	};

	Image* GetImageById(int theId);
	Font* GetFontById(int theId);
	int GetSoundById(int theId);

	Image*& GetImageRefById(int theId);
	Font*& GetFontRefById(int theId);
	int& GetSoundRefById(int theId);

	ResourceId GetIdByImage(Image *theImage);
	ResourceId GetIdByFont(Font *theFont);
	ResourceId GetIdBySound(int theSound);
	const char* GetStringIdById(int theId);
	ResourceId GetIdByStringId(const char *theStringId);

} // namespace Sexy


#endif
