#ifndef __Res_H__
#define __Res_H__

namespace Sexy
{
	class ResourceManager;
	class Image;
	class Font;

	Image* LoadImageById(ResourceManager *theManager, int theId);
	void ReplaceImageById(ResourceManager *theManager, int theId, Image *theImage);
	bool ExtractResourcesByName(ResourceManager *theManager, const char *theName);

	// CommonGame Resources
	bool ExtractCommonGameResources(ResourceManager *theMgr);
	extern Image* IMAGE_B1A_BG1;
	extern Image* IMAGE_B1A_BG2;
	extern Image* IMAGE_B1A_BG3;
	extern Image* IMAGE_B1A_BG4;
	extern Image* IMAGE_BANNER_LARGE;
	extern Image* IMAGE_BANNER_SMALL;
	extern Image* IMAGE_BLUE_SPARKLE;
	extern Image* IMAGE_BUTTON_ATTACK;
	extern Image* IMAGE_BUTTON_MENU;
	extern Image* IMAGE_BUTTON_SCRAMBLE;
	extern Image* IMAGE_BUTTON_SCRAMBLE_SHADOW;
	extern Image* IMAGE_COMBAT_UI_BOTTOM;
	extern Image* IMAGE_COMBAT_UI_TOP;
	extern Image* IMAGE_CP_SKIP;
	extern Image* IMAGE_GRAYBAR_BG;
	extern Image* IMAGE_HEARTBLINK;
	extern Image* IMAGE_HEARTBLINK_CC;
	extern Image* IMAGE_HEARTS;
	extern Image* IMAGE_HEARTS_BG;
	extern Image* IMAGE_HEARTS_CC;
	extern Image* IMAGE_HEART_BITS;
	extern Image* IMAGE_HEART_MASK;
	extern Image* IMAGE_HEART_MASK_CC;
	extern Image* IMAGE_IMPACT_LARGE;
	extern Image* IMAGE_IMPACT_SMALL;
	extern Image* IMAGE_ITEM_ATTACK;
	extern Image* IMAGE_ITEM_ATTACK_NB;
	extern Image* IMAGE_ITEM_HEALTH;
	extern Image* IMAGE_ITEM_HEALTH_NB;
	extern Image* IMAGE_ITEM_PURIFY;
	extern Image* IMAGE_ITEM_PURIFY_NB;
	extern Image* IMAGE_LEX_ICON;
	extern Image* IMAGE_LOW_HEALTH_OUTLINE;
	extern Image* IMAGE_MAP_CHECK;
	extern Image* IMAGE_MAP_LEX_WARP;
	extern Image* IMAGE_MAP_MINIGAME_ANIM;
	extern Image* IMAGE_MINIGAME_ICON;
	extern Image* IMAGE_PAUSED_BANNER;
	extern Image* IMAGE_PORTRAIT_CODEX;
	extern Image* IMAGE_PORTRAIT_HAMLET;
	extern Image* IMAGE_PORTRAIT_LEX;
	extern Image* IMAGE_PORTRAIT_LIBRARIAN;
	extern Image* IMAGE_PORTRAIT_ODIN;
	extern Image* IMAGE_PORTRAIT_RATKING;
	extern Image* IMAGE_RED_SPARKLE;
	extern Image* IMAGE_STATS_BOX;
	extern Image* IMAGE_STATUSTEXT_FROZEN;
	extern Image* IMAGE_STATUSTEXT_POISONED;
	extern Image* IMAGE_STATUSTEXT_POWERDOWN;
	extern Image* IMAGE_STATUSTEXT_POWERUP;
	extern Image* IMAGE_STATUS_ICONS;
	extern Image* IMAGE_TILE_BASIC;
	extern Image* IMAGE_TILE_PIPS;
	extern Image* IMAGE_WORDPOWER_GLOW_INNER_LEFT;
	extern Image* IMAGE_WORDPOWER_GLOW_INNER_MID;
	extern Image* IMAGE_WORDPOWER_GLOW_INNER_RIGHT;
	extern Image* IMAGE_WORDPOWER_GLOW_LEFT;
	extern Image* IMAGE_WORDPOWER_GLOW_LEFT_SMALL;
	extern Image* IMAGE_WORDPOWER_GLOW_MIDDLE;
	extern Image* IMAGE_WORDPOWER_GLOW_MIDDLE_SMALL;
	extern Image* IMAGE_WORDPOWER_GLOW_RIGHT;
	extern Image* IMAGE_WORDPOWER_GLOW_RIGHT_SMALL;
	extern Image* IMAGE_WP_SPARKLE_MEDIUM;
	extern Image* IMAGE_WP_SPARKLE_SMALL;
	extern int SOUND_CLICK1;
	extern int SOUND_CLICK2;
	extern int SOUND_CROWD_CHEER;
	extern int SOUND_EFFECT_FROZEN;
	extern int SOUND_EFFECT_POISON;
	extern int SOUND_FREEZE;
	extern int SOUND_GEMSPAWN;
	extern int SOUND_HEAL;
	extern int SOUND_IMPACT_LARGE;
	extern int SOUND_IMPACT_SMALL;
	extern int SOUND_LEX_ASTONISHING;
	extern int SOUND_LEX_ATTACK1;
	extern int SOUND_LEX_AWESOME;
	extern int SOUND_LEX_EXCELLENT;
	extern int SOUND_LEX_FANTASTIC;
	extern int SOUND_LEX_GOOD;
	extern int SOUND_LEX_INCREDIBLE;
	extern int SOUND_LEX_NICE;
	extern int SOUND_LEX_VERYGOOD;
	extern int SOUND_LEX_WOW;
	extern int SOUND_LOW_HEALTH;
	extern int SOUND_POISON;
	extern int SOUND_POTION_HEAL;
	extern int SOUND_SCRAMBLE;
	extern int SOUND_TILELOCK;
	extern int SOUND_TILE_SELECT;
	extern int SOUND_WORD_POWER;

	// Init Resources
	bool ExtractInitResources(ResourceManager *theMgr);
	extern Font* FONT_LARGE;
	extern Font* FONT_LARGER;
	extern Font* FONT_LARGE_OUTLINE;
	extern Font* FONT_MEDIUM;
	extern Font* FONT_MEDIUM_BOLD;
	extern Font* FONT_OPTIMA_MEDIUM;
	extern Font* FONT_OPTIMA_SMALL;
	extern Font* FONT_SCORE;
	extern Font* FONT_SMALL;
	extern Font* FONT_TILE;
	extern Font* FONT_TILE_STATUS;
	extern Image* IMAGE_CURTAIN_ANIM;
	extern Image* IMAGE_CURTAIN_TOP;
	extern Image* IMAGE_DIALOG;
	extern Image* IMAGE_DIALOG_BANNER_CODE;
	extern Image* IMAGE_DIALOG_BANNER_GAMEOVER;
	extern Image* IMAGE_DIALOG_BANNER_HOWTOPLAY;
	extern Image* IMAGE_DIALOG_BANNER_LOADING;
	extern Image* IMAGE_DIALOG_BANNER_MENU;
	extern Image* IMAGE_DIALOG_BANNER_OPTIONS;
	extern Image* IMAGE_DIALOG_BANNER_RUSURE;
	extern Image* IMAGE_DIALOG_BANNER_UNLOCK;
	extern Image* IMAGE_DIALOG_BANNER_VICTORY;
	extern Image* IMAGE_DIALOG_BUTTON;
	extern Image* IMAGE_DIALOG_CHECKBOX;
	extern Image* IMAGE_DIALOG_DIVIDER_BOT;
	extern Image* IMAGE_DIALOG_DIVIDER_TOP;
	extern Image* IMAGE_DIALOG_USER_ENTRY;
	extern Image* IMAGE_ORANGE_STAR;
	extern Image* IMAGE_RED_STAR;
	extern Image* IMAGE_SLIDER_THUMB;
	extern Image* IMAGE_SLIDER_TRACK;
	extern Image* IMAGE_SLIDER_TRACK_VERT;
	extern Image* IMAGE_WAIT_BAR;
	extern Image* IMAGE_YELLOW_STAR;

	// TitleAndMM Resources
	bool ExtractTitleAndMMResources(ResourceManager *theMgr);
	extern Image* IMAGE_AX_MM_BG;
	extern Image* IMAGE_AX_MM_BSHADOWS1;
	extern Image* IMAGE_AX_MM_BSHADOWS2;
	extern Image* IMAGE_AX_MM_CASUAL;
	extern Image* IMAGE_AX_MM_CHALLENGE;
	extern Image* IMAGE_AX_MM_DELUXE;
	extern Image* IMAGE_AX_MM_DIFF_BANNER;
	extern Image* IMAGE_AX_MM_EASY;
	extern Image* IMAGE_AX_MM_EXTREME;
	extern Image* IMAGE_AX_MM_GLOW;
	extern Image* IMAGE_AX_MM_HOWTOPLAY;
	extern Image* IMAGE_AX_MM_LEX;
	extern Image* IMAGE_AX_MM_LOCK;
	extern Image* IMAGE_AX_MM_LOGO;
	extern Image* IMAGE_AX_MM_MASTER;
	extern Image* IMAGE_AX_MM_PLAYNOW;
	extern Image* IMAGE_AX_MM_WORDBUBBLE;
	extern Image* IMAGE_HTP_BG;
	extern Image* IMAGE_HTP_CONTINUE;
	extern Image* IMAGE_UP_0;
	extern Image* IMAGE_UP_1;
	extern Image* IMAGE_UP_2;
	extern Image* IMAGE_UP_3;
	extern Image* IMAGE_UP_4;
	extern Image* IMAGE_UP_BG;
	extern Image* IMAGE_UP_DOWNLOAD;
	extern Image* IMAGE_UP_NOTHANKS;

	enum ResourceId
	{
		FONT_SMALL_ID,
		FONT_MEDIUM_ID,
		FONT_MEDIUM_BOLD_ID,
		FONT_LARGE_ID,
		FONT_LARGE_OUTLINE_ID,
		FONT_TILE_ID,
		FONT_TILE_STATUS_ID,
		FONT_LARGER_ID,
		FONT_OPTIMA_SMALL_ID,
		FONT_OPTIMA_MEDIUM_ID,
		FONT_SCORE_ID,
		IMAGE_WAIT_BAR_ID,
		IMAGE_DIALOG_BANNER_MENU_ID,
		IMAGE_DIALOG_BANNER_UNLOCK_ID,
		IMAGE_DIALOG_BANNER_OPTIONS_ID,
		IMAGE_DIALOG_BANNER_RUSURE_ID,
		IMAGE_DIALOG_BANNER_HOWTOPLAY_ID,
		IMAGE_DIALOG_BANNER_LOADING_ID,
		IMAGE_DIALOG_BANNER_VICTORY_ID,
		IMAGE_DIALOG_BANNER_GAMEOVER_ID,
		IMAGE_DIALOG_BANNER_CODE_ID,
		IMAGE_DIALOG_DIVIDER_BOT_ID,
		IMAGE_DIALOG_DIVIDER_TOP_ID,
		IMAGE_DIALOG_ID,
		IMAGE_DIALOG_BUTTON_ID,
		IMAGE_DIALOG_CHECKBOX_ID,
		IMAGE_DIALOG_USER_ENTRY_ID,
		IMAGE_YELLOW_STAR_ID,
		IMAGE_ORANGE_STAR_ID,
		IMAGE_RED_STAR_ID,
		IMAGE_SLIDER_THUMB_ID,
		IMAGE_SLIDER_TRACK_ID,
		IMAGE_SLIDER_TRACK_VERT_ID,
		IMAGE_CURTAIN_ANIM_ID,
		IMAGE_CURTAIN_TOP_ID,
		IMAGE_AX_MM_BG_ID,
		IMAGE_AX_MM_BSHADOWS1_ID,
		IMAGE_AX_MM_BSHADOWS2_ID,
		IMAGE_AX_MM_CASUAL_ID,
		IMAGE_AX_MM_CHALLENGE_ID,
		IMAGE_AX_MM_DIFF_BANNER_ID,
		IMAGE_AX_MM_EASY_ID,
		IMAGE_AX_MM_EXTREME_ID,
		IMAGE_AX_MM_DELUXE_ID,
		IMAGE_AX_MM_HOWTOPLAY_ID,
		IMAGE_AX_MM_LEX_ID,
		IMAGE_AX_MM_LOCK_ID,
		IMAGE_AX_MM_LOGO_ID,
		IMAGE_AX_MM_GLOW_ID,
		IMAGE_AX_MM_MASTER_ID,
		IMAGE_AX_MM_PLAYNOW_ID,
		IMAGE_AX_MM_WORDBUBBLE_ID,
		IMAGE_HTP_BG_ID,
		IMAGE_HTP_CONTINUE_ID,
		IMAGE_UP_BG_ID,
		IMAGE_UP_DOWNLOAD_ID,
		IMAGE_UP_NOTHANKS_ID,
		IMAGE_UP_0_ID,
		IMAGE_UP_1_ID,
		IMAGE_UP_2_ID,
		IMAGE_UP_3_ID,
		IMAGE_UP_4_ID,
		IMAGE_B1A_BG1_ID,
		IMAGE_B1A_BG2_ID,
		IMAGE_B1A_BG3_ID,
		IMAGE_B1A_BG4_ID,
		IMAGE_GRAYBAR_BG_ID,
		IMAGE_HEARTS_ID,
		IMAGE_HEART_MASK_ID,
		IMAGE_HEART_MASK_CC_ID,
		IMAGE_HEARTBLINK_ID,
		IMAGE_HEARTBLINK_CC_ID,
		IMAGE_HEARTS_BG_ID,
		IMAGE_HEARTS_CC_ID,
		IMAGE_STATS_BOX_ID,
		IMAGE_MAP_LEX_WARP_ID,
		IMAGE_MAP_MINIGAME_ANIM_ID,
		IMAGE_MINIGAME_ICON_ID,
		IMAGE_BANNER_LARGE_ID,
		IMAGE_BANNER_SMALL_ID,
		IMAGE_LEX_ICON_ID,
		IMAGE_MAP_CHECK_ID,
		IMAGE_RED_SPARKLE_ID,
		IMAGE_BLUE_SPARKLE_ID,
		IMAGE_WP_SPARKLE_SMALL_ID,
		IMAGE_WP_SPARKLE_MEDIUM_ID,
		IMAGE_TILE_PIPS_ID,
		IMAGE_TILE_BASIC_ID,
		IMAGE_WORDPOWER_GLOW_LEFT_ID,
		IMAGE_WORDPOWER_GLOW_RIGHT_ID,
		IMAGE_WORDPOWER_GLOW_MIDDLE_ID,
		IMAGE_WORDPOWER_GLOW_LEFT_SMALL_ID,
		IMAGE_WORDPOWER_GLOW_MIDDLE_SMALL_ID,
		IMAGE_WORDPOWER_GLOW_RIGHT_SMALL_ID,
		IMAGE_WORDPOWER_GLOW_INNER_LEFT_ID,
		IMAGE_WORDPOWER_GLOW_INNER_MID_ID,
		IMAGE_WORDPOWER_GLOW_INNER_RIGHT_ID,
		IMAGE_CP_SKIP_ID,
		IMAGE_PORTRAIT_CODEX_ID,
		IMAGE_PORTRAIT_HAMLET_ID,
		IMAGE_PORTRAIT_LEX_ID,
		IMAGE_PORTRAIT_LIBRARIAN_ID,
		IMAGE_PORTRAIT_ODIN_ID,
		IMAGE_PORTRAIT_RATKING_ID,
		IMAGE_ITEM_ATTACK_ID,
		IMAGE_ITEM_ATTACK_NB_ID,
		IMAGE_ITEM_HEALTH_ID,
		IMAGE_ITEM_HEALTH_NB_ID,
		IMAGE_ITEM_PURIFY_ID,
		IMAGE_ITEM_PURIFY_NB_ID,
		IMAGE_STATUSTEXT_FROZEN_ID,
		IMAGE_STATUSTEXT_POISONED_ID,
		IMAGE_STATUSTEXT_POWERDOWN_ID,
		IMAGE_STATUSTEXT_POWERUP_ID,
		IMAGE_HEART_BITS_ID,
		IMAGE_IMPACT_LARGE_ID,
		IMAGE_IMPACT_SMALL_ID,
		IMAGE_STATUS_ICONS_ID,
		IMAGE_LOW_HEALTH_OUTLINE_ID,
		IMAGE_PAUSED_BANNER_ID,
		IMAGE_BUTTON_ATTACK_ID,
		IMAGE_BUTTON_MENU_ID,
		IMAGE_BUTTON_SCRAMBLE_ID,
		IMAGE_BUTTON_SCRAMBLE_SHADOW_ID,
		IMAGE_COMBAT_UI_TOP_ID,
		IMAGE_COMBAT_UI_BOTTOM_ID,
		SOUND_TILE_SELECT_ID,
		SOUND_CLICK1_ID,
		SOUND_CLICK2_ID,
		SOUND_GEMSPAWN_ID,
		SOUND_CROWD_CHEER_ID,
		SOUND_LEX_ATTACK1_ID,
		SOUND_LEX_WOW_ID,
		SOUND_LEX_ASTONISHING_ID,
		SOUND_LEX_AWESOME_ID,
		SOUND_LEX_EXCELLENT_ID,
		SOUND_LEX_FANTASTIC_ID,
		SOUND_LEX_GOOD_ID,
		SOUND_LEX_VERYGOOD_ID,
		SOUND_LEX_NICE_ID,
		SOUND_LEX_INCREDIBLE_ID,
		SOUND_SCRAMBLE_ID,
		SOUND_EFFECT_POISON_ID,
		SOUND_EFFECT_FROZEN_ID,
		SOUND_POTION_HEAL_ID,
		SOUND_LOW_HEALTH_ID,
		SOUND_WORD_POWER_ID,
		SOUND_POISON_ID,
		SOUND_IMPACT_LARGE_ID,
		SOUND_IMPACT_SMALL_ID,
		SOUND_HEAL_ID,
		SOUND_FREEZE_ID,
		SOUND_TILELOCK_ID,
		RESOURCE_ID_MAX
	};

	Image* GetImageById(int theId);
	Font* GetFontById(int theId);
	int GetSoundById(int theId);

	Image*& GetImageRefById(int theId);
	Font*& GetFontRefById(int theId);
	int& GetSoundRefById(int theId);

	ResourceId GetIdByImage(Image *theImage);
	ResourceId GetIdByFont(Font *theFont);
	ResourceId GetIdBySound(int theSound);
	const char* GetStringIdById(int theId);
	ResourceId GetIdByStringId(const char *theStringId);

} // namespace Sexy


#endif
